Git Tests/force-app/main/default/default/objects/CodigosCFOP__c/CodigosCFOP__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Códigos de devolução NF CFOP</description>
    <label>Códigos de CFOP</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ItensNotaFiscal__c/ItensNotaFiscal__c.object-meta.xml
<CustomObject>
    <label>Item da nota fiscal</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Item da nota fiscal</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens da nota fiscal</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ItensNotaFiscal__c/fields/CFOP__c.field-meta.xml
<CustomField>
    <fullName>CFOP__c</fullName>
    <label>CFOP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItensNotaFiscal__c/fields/CodigoItemNotaVenda__c.field-meta.xml
<CustomField>
    <fullName>CodigoItemNotaVenda__c</fullName>
    <externalId>true</externalId>
    <label>Código do item da nota de venda</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItensNotaFiscal__c/fields/ItemNotaVenda__c.field-meta.xml
<CustomField>
    <fullName>ItemNotaVenda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item da nota de venda</label>
    <referenceTo>ItensNotaFiscal__c</referenceTo>
    <relationshipName>ItensNotaFiscal</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItensNotaFiscal__c/fields/NotaFiscal__c.field-meta.xml
<CustomField>
    <fullName>NotaFiscal__c</fullName>
    <label>Número da Nota Fiscal</label>
    <referenceTo>NotasFiscais__c</referenceTo>
    <relationshipLabel>Itens da nota fiscal</relationshipLabel>
    <relationshipName>ItensNotaFiscal</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/NotasFiscais__c/NotasFiscais__c.object-meta.xml
<CustomObject>
    <label>Nota fiscal</label>
    <nameField>
        <label>Número da nota fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas fiscais</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/NotasFiscais__c/fields/CFOP__c.field-meta.xml
<CustomField>
    <fullName>CFOP__c</fullName>
    <label>CFOP</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/NotasFiscais__c/fields/NaturezaOperacao__c.field-meta.xml
<CustomField>
    <fullName>NaturezaOperacao__c</fullName>
    <label>Natureza da Operação</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/NotasFiscais__c/recordTypes/Devolucao.recordType-meta.xml
<RecordType>
    <fullName>Devolucao</fullName>
    <active>true</active>
    <label>Devolução</label>
</RecordType>

Git Tests/force-app/main/default/default/classes/ItensNotasFiscaisBO.cls
public virtual without sharing class ItensNotasFiscaisBO {

    public void vinculaItemVenda(Map<Id,ItensNotaFiscal__c> oldMap, List<ItensNotaFiscal__c> newRecordList) {

        Map<String,String> mapCodItem = new Map<String,String>();
        Set<String> setCodItem = new Set<String>();
        List<ItensNotaFiscal__c> lstNotasVenda = new List<ItensNotaFiscal__c>();

        for(ItensNotaFiscal__c item: newRecordList){

            if (!String.isBlank(item.CodigoItemNotaVenda__c)) {               
                
                setCodItem.add(item.CodigoItemNotaVenda__c);                
            }
        }

        if (setCodItem.size() > 0){
            
            lstNotasVenda = [SELECT Id, ExternalId__c, NotaFiscal__c  FROM ItensNotaFiscal__c WHERE ExternalId__c IN: setCodItem];
            System.debug(lstNotasVenda);
            if (lstNotasVenda.size() > 0) {

                for (ItensNotaFiscal__c item : lstNotasVenda) {

                    if (!mapCodItem.containsKey(item.ExternalId__c)) {
                        
                        mapCodItem.put(item.ExternalId__c, item.Id);
                    }                    
                }

                for (ItensNotaFiscal__c itemDevolucao: newRecordList){                      
                        
                    if (mapCodItem.containsKey(itemDevolucao.CodigoItemNotaVenda__c)) {
                        System.debug('======= '+ itemDevolucao.CodigoItemNotaVenda__c);
                        
                        itemDevolucao.ItemNotaVenda__c = mapCodItem.get(itemDevolucao.CodigoItemNotaVenda__c);
                    }
                }                
            }
        }
    }

    public void validateCFOP(Map<Id,ItensNotaFiscal__c> oldMap, List<ItensNotaFiscal__c> newRecordList) {

        Map<String,ItensNotaFiscal__c> mapNotaxItem = new Map<String,ItensNotaFiscal__c>();
        List<NotasFiscais__c> lstNotas = new List<NotasFiscais__c>();
        Id DEVOLUCAO_RECORDTYPE = Schema.SObjectType.NotasFiscais__c.getRecordTypeInfosByDeveloperName().get('Devolucao').getRecordTypeId();
        NotasFiscais__c nf = new NotasFiscais__c();
        for(ItensNotaFiscal__c item: newRecordList){

            if (!mapNotaxItem.containsKey(item.NotaFiscal__c)) {
                        
                mapNotaxItem.put(item.NotaFiscal__c, item);
            } 
        }

        if (mapNotaxItem.size() > 0){
            Set<String> setIds = new Set<String>();
            for(ItensNotaFiscal__c item: newRecordList){
                if (!String.isBlank(mapNotaxItem.get(item.NotaFiscal__c).CFOP__c) && CodigosCFOP__c.getAll().get(mapNotaxItem.get(item.NotaFiscal__c).CFOP__c) != null && !setIds.contains(item.NotaFiscal__c)) {
                    nf = new NotasFiscais__c();
                    nf.Id = item.NotaFiscal__c;
                    nf.RecordTypeId = DEVOLUCAO_RECORDTYPE;
                    nf.NaturezaOperacao__c = 'DEVOLUÇÃO';
                    lstNotas.add(nf);
                    setIds.add(item.NotaFiscal__c);
                }

            }
           
        }

        if (lstNotas.size() > 0) {
            update lstNotas;
        }
    }
}