Git Tests/force-app/main/default/default/objects/CodigosCFOP__c/CodigosCFOP__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Códigos de devolução NF CFOP</description>
    <label>Códigos de CFOP</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/NotasFiscais__c/NotasFiscais__c.object-meta.xml
<CustomObject>
    <label>Nota fiscal</label>
    <nameField>
        <label>Número da nota fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas fiscais</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/NotasFiscais__c/fields/CFOP__c.field-meta.xml
<CustomField>
    <fullName>CFOP__c</fullName>
    <label>CFOP</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/NotasFiscais__c/recordTypes/Devolucao.recordType-meta.xml
<RecordType>
    <fullName>Devolucao</fullName>
    <active>true</active>
    <label>Devolução</label>
</RecordType>

Git Tests/force-app/main/default/default/classes/NotasFiscaisBO.cls
public virtual without sharing class NotasFiscaisBO {

     public void validateCFOP(Map<Id,NotasFiscais__c> oldMap, List<NotasFiscais__c> newRecordList) {

        Id DEVOLUCAO_RECORDTYPE = Schema.SObjectType.NotasFiscais__c.getRecordTypeInfosByDeveloperName().get('Devolucao').getRecordTypeId();
        for(NotasFiscais__c nf: newRecordList){
            
            if (CodigosCFOP__c.getAll().get(nf.CFOP__c) != null) {
                
                //nf.RecordTypeId = DEVOLUCAO_RECORDTYPE;
            }
        }
    }
}