Git Tests/force-app/main/default/default/objects/DestinatarioReserva__c/DestinatarioReserva__c.object-meta.xml
<CustomObject>
    <label>Destinatário da reserva</label>
    <nameField>
        <displayFormat>DR-{000000}</displayFormat>
        <label>Nome de Destinatário da reserva</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Destinatários da reserva</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/DestinatarioReserva__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Destinatários da reserva</relationshipLabel>
    <relationshipName>DestinatariosReserva</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/DestinatarioReserva__c/fields/CodigoRegiao__c.field-meta.xml
<CustomField>
    <fullName>CodigoRegiao__c</fullName>
    <label>Código da região</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/DestinatarioReserva__c/fields/Reserva__c.field-meta.xml
<CustomField>
    <fullName>Reserva__c</fullName>
    <label>Reserva</label>
    <referenceTo>Reserva__c</referenceTo>
    <relationshipLabel>Destinatários da reserva</relationshipLabel>
    <relationshipName>DestinatariosReserva</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/CategoriaComercial__c.field-meta.xml
<CustomField>
    <fullName>CategoriaComercial__c</fullName>
    <label>Categoria comercial</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>G</fullName>
                <label>GENÉRICO</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>MATERIAIS</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>NUTRIÇÃO</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Medctech</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>REFERÊNCIA</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>AMBOS</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>DIABETES</label>
            </value>
            <value>
                <fullName>Q</fullName>
                <label>ODONTOLOGIA</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Especialidade</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <label>EQUIPAMENTO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/ProdutoReserva__c.object-meta.xml
<CustomObject>
    <label>Produto da reserva</label>
    <nameField>
        <displayFormat>PR-{00000000}</displayFormat>
        <label>Nome de Produto da reserva</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Produtos da reserva</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/Armazem__c.field-meta.xml
<CustomField>
    <fullName>Armazem__c</fullName>
    <externalId>true</externalId>
    <label>Armazém</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/DataUltimaMovimentacao__c.field-meta.xml
<CustomField>
    <fullName>DataUltimaMovimentacao__c</fullName>
    <label>Data última movimentação</label>
    <type>DateTime</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/Preco__c.field-meta.xml
<CustomField>
    <fullName>Preco__c</fullName>
    <label>Preço</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Produtos da reserva</relationshipLabel>
    <relationshipName>ProdutosReserva</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/QuantidadeAtiva__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeAtiva__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantidade solicitada</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/QuantidadeConsumida__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeConsumida__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantidade consumida</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/QuantidadeReservada__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeReservada__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantidade reservada</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/QuantidadeTransferida__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeTransferida__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantidade transferida</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/Reserva__c.field-meta.xml
<CustomField>
    <fullName>Reserva__c</fullName>
    <label>Reserva</label>
    <referenceTo>Reserva__c</referenceTo>
    <relationshipLabel>Produtos da reserva</relationshipLabel>
    <relationshipName>ProdutosReserva</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/ReservaRecebedora__c.field-meta.xml
<CustomField>
    <fullName>ReservaRecebedora__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reserva recebedora</label>
    <referenceTo>Reserva__c</referenceTo>
    <relationshipLabel>Produtos da reserva (Reserva recebedora)</relationshipLabel>
    <relationshipName>ProdutoReserva</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/StatusReserva__c.field-meta.xml
<CustomField>
    <fullName>StatusReserva__c</fullName>
    <label>Status da reserva</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando aprovação</fullName>
            </value>
            <value>
                <fullName>Ativa</fullName>
            </value>
            <value>
                <fullName>Rejeitada</fullName>
            </value>
            <value>
                <fullName>Aguardando integração</fullName>
            </value>
            <value>
                <fullName>Erro de integração</fullName>
            </value>
            <value>
                <fullName>Aguardando exclusão</fullName>
            </value>
            <value>
                <fullName>Expirada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Reserva__c/Reserva__c.object-meta.xml
<CustomObject>
    <label>Reserva</label>
    <nameField>
        <displayFormat>RE-{000000}</displayFormat>
        <label>Nome da reserva</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Reserva__c/fields/CodigoCD__c.field-meta.xml
<CustomField>
    <fullName>CodigoCD__c</fullName>
    <label>Código do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Reserva__c/fields/CodigoReserva__c.field-meta.xml
<CustomField>
    <fullName>CodigoReserva__c</fullName>
    <externalId>true</externalId>
    <label>Código da reserva</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Reserva__c/fields/StatusReserva__c.field-meta.xml
<CustomField>
    <fullName>StatusReserva__c</fullName>
    <label>Status da reserva</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativa</fullName>
                <default>true</default>
                <label>Ativa</label>
            </value>
            <value>
                <fullName>Expirada</fullName>
            </value>
            <value>
                <fullName>Aguardando aprovação</fullName>
                <isActive>false</isActive>
                <label>Aguardando aprovação</label>
            </value>
            <value>
                <fullName>Aguardando envio de exclusão</fullName>
                <isActive>false</isActive>
                <label>Aguardando envio de exclusão</label>
            </value>
            <value>
                <fullName>Aguardando integração</fullName>
                <isActive>false</isActive>
                <label>Aguardando integração</label>
            </value>
            <value>
                <fullName>Aprovada</fullName>
                <isActive>false</isActive>
                <label>Aprovada</label>
            </value>
            <value>
                <fullName>Cancelada</fullName>
                <isActive>false</isActive>
                <label>Cancelada</label>
            </value>
            <value>
                <fullName>Em digitação</fullName>
                <isActive>false</isActive>
                <label>Em digitação</label>
            </value>
            <value>
                <fullName>Erro de integração</fullName>
                <isActive>false</isActive>
                <label>Erro de integração</label>
            </value>
            <value>
                <fullName>Integrado</fullName>
                <isActive>false</isActive>
                <label>Integrado</label>
            </value>
            <value>
                <fullName>Rejeitada</fullName>
                <isActive>false</isActive>
                <label>Rejeitada</label>
            </value>
            <value>
                <fullName>Vencida</fullName>
                <isActive>false</isActive>
                <label>Vencida</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Reserva__c/recordTypes/ReservaRegional.recordType-meta.xml
<RecordType>
    <fullName>ReservaRegional</fullName>
    <active>true</active>
    <label>Reserva regional</label>
</RecordType>

Git Tests/force-app/main/default/default/objects/ResponsabilidadeAprovacao__c/ResponsabilidadeAprovacao__c.object-meta.xml
<CustomObject>
    <label>Responsabilidade de aprovação</label>
    <nameField>
        <displayFormat>RA-{00000}</displayFormat>
        <label>Nome de Responsabilidade de aprovação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responsabilidades de aprovação</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ResponsabilidadeAprovacao__c/fields/Categorias__c.field-meta.xml
<CustomField>
    <fullName>Categorias__c</fullName>
    <label>Categorias</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>AMBOS</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>DIABETES</label>
            </value>
            <value>
                <fullName>G</fullName>
                <label>GENÉRICO</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>MATERIAIS</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>NUTRIÇÃO</label>
            </value>
            <value>
                <fullName>Q</fullName>
                <label>ODONTOLOGIA</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>MEDCTECH</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>SPECIALTY</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <label>EQUIPAMENTO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/ResponsabilidadeAprovacao__c/fields/Regiao__c.field-meta.xml
<CustomField>
    <fullName>Regiao__c</fullName>
    <externalId>true</externalId>
    <label>Região</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ResponsabilidadeAprovacao__c/fields/UsuarioAprovador__c.field-meta.xml
<CustomField>
    <fullName>UsuarioAprovador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário aprovador</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ResponsabilidadeAprovacao</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ResponsabilidadeAprovacao__c/recordTypes/AprovacaoReserva.recordType-meta.xml
<RecordType>
    <fullName>AprovacaoReserva</fullName>
    <active>true</active>
    <label>Aprovação reserva de produto</label>
</RecordType>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/Setorizacao__c.object-meta.xml
<CustomObject>
    <label>Setorização</label>
    <nameField>
        <displayFormat>SET-{000000}</displayFormat>
        <label>Número da setorização</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setorizações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome do cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Setorização</relationshipLabel>
    <relationshipName>Setorizacao</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Setorização</relationshipLabel>
    <relationshipName>Setorizacao</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Regiao__c.field-meta.xml
<CustomField>
    <fullName>Regiao__c</fullName>
    <label>Região</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/ReservationProductTriggerHelper.cls
public without sharing class ReservationProductTriggerHelper {

    public ReservationProductTriggerHelper() {}

    public static final Id RESERVATION_REGION_RECORDTYPE = Schema.SObjectType.Reserva__c.getRecordTypeInfosByDeveloperName().get('ReservaRegional').getRecordTypeId();
    public static final Id RESPONSABILITY_RESERVATION_REGION_RECORDTYPE = Schema.SObjectType.ResponsabilidadeAprovacao__c.getRecordTypeInfosByDeveloperName().get('AprovacaoReserva').getRecordTypeId();
    public static final Set<String> setProductRegion = new Set<String>();  
    public static final Set<String> setProductClient = new Set<String>();  
    public static final Set<String> setClients = new Set<String>();  

    public static void validateStatusReservation(Map<Id, ProdutoReserva__c> newMap){

        List<ProdutoReserva__c> lstReservationApproval = new List<ProdutoReserva__c>();
        List<Id> lstReservationIntegration = new List<Id>();
        List<ProdutoReserva__c> lstReservationDelete = new List<ProdutoReserva__c>();
        Map<String,String> mapApproval = new Map<String,String>();
        Set<Id> resultIds = new Set<Id>();
        List<ProdutoReserva__c> lstReservationTransfer = new List<ProdutoReserva__c>();
        List<ProdutoReserva__c> lstReservationTransferReject = new List<ProdutoReserva__c>();
        Set<String> setReceiverReservation = new Set<String>();
        Set<String> setProduct = new Set<String>();

      
        for (ProdutoReserva__c reservationProduct : newMap.values()) {

            if (reservationProduct.StatusReserva__c == 'Aguardando aprovação') {              

                lstReservationApproval.add(reservationProduct);
                resultIds.add(reservationProduct.Reserva__c);

            }else if (reservationProduct.StatusReserva__c == 'Aguardando Integração') {
              
                if (!String.isBlank(reservationProduct.ReservaRecebedora__c)) {
                    lstReservationTransfer.add(reservationProduct);
                    setReceiverReservation.add(reservationProduct.ReservaRecebedora__c);
                    setProduct.add(reservationProduct.Produto__c);
                }
                lstReservationIntegration.add(reservationProduct.Reserva__c);
                mapApproval.put(reservationProduct.Id, 'Approve');
               

            }else if (reservationProduct.StatusReserva__c == 'Rejeitada' || reservationProduct.StatusReserva__c == 'Ativa') {
              
                if (reservationProduct.StatusReserva__c == 'Ativa') {

                    if (!String.isBlank(reservationProduct.ReservaRecebedora__c)) {
                        lstReservationTransferReject.add(reservationProduct);
                        setReceiverReservation.add(reservationProduct.ReservaRecebedora__c);
                        setProduct.add(reservationProduct.Produto__c);
                    }
                    
                } else {
                    
                     //lstReservationIntegration.add(reservationProduct);
                    mapApproval.put(reservationProduct.Id, 'Reject');
                }
               
               

            }
            // else if (reservationProduct.StatusReserva__c == 'Aguardando envio de exclusão') {              
                
            //     lstReservationDelete.add(reservationProduct);
            // }

        }

        if (lstReservationApproval.size() > 0) {

            Map<String,List<DestinatarioReserva__c>> mapReservation = getRecordTypeReservation(resultIds);
        
            validateTypeApproval(lstReservationApproval, mapReservation );

        }

        if (lstReservationIntegration.size() > 0) {

            System.debug(lstReservationTransfer);

            if (lstReservationTransfer.size() > 0) {
                
                lstReservationIntegration.addAll(reservationTransfer(lstReservationTransfer, setReceiverReservation, setProduct,true));
            }            

            IntegrationReservationOUT.asyncSendToProtheus(lstReservationIntegration);
        }

        if (lstReservationTransferReject.size() > 0) {
                
            reservationTransfer(lstReservationTransfer, setReceiverReservation, setProduct, false);
        }

        // if (lstReservationDelete.size() > 0) {
            
        //     //sendReservationDelete(lstReservationDelete);
        // }

        if (mapApproval.size() > 0) {
            updateApprovalStep(mapApproval);
        }
    }
     
    public static void validateTypeApproval(List<ProdutoReserva__c> lstReservaAprovacao, Map<String,List<DestinatarioReserva__c>> mapReservation){

        List<ProdutoReserva__c> lstReservationRegion = new List<ProdutoReserva__c>();
        List<ProdutoReserva__c> lstReservationClient = new List<ProdutoReserva__c>();
        
        for (ProdutoReserva__c productReservation : lstReservaAprovacao) {
            System.debug('============================ '+mapReservation.get(productReservation.Reserva__c));
            
            if (mapReservation.get(productReservation.Reserva__c)[0].Reserva__r.RecordTypeId == RESERVATION_REGION_RECORDTYPE) {

                lstReservationRegion.add(productReservation);
                setProductRegion.add(productReservation.Produto__c);
            
            }else{

                lstReservationClient.add(productReservation);
                setProductClient.add(productReservation.Produto__c);
            }            
        }

        if (lstReservationRegion.size() > 0) {

            reservationApproval(lstReservationRegion,  mapReservation , true, null);

        } else if (lstReservationClient.size() > 0) {            

            reservationApproval(lstReservationClient,  mapReservation , false, getClientRegionReservation(setClients));
            
        }
    }
    
    public static void reservationApproval(List<ProdutoReserva__c> lstReservationProduct, Map<String,List<DestinatarioReserva__c>> mapReservation, Boolean isRegion, Map<String,List<String>> mapReservationClient){

        String recType = RESPONSABILITY_RESERVATION_REGION_RECORDTYPE;
        Set<String> setRegion = new Set<String>();
        Set<String> setCategoryProduct = new Set<String>();
        Map<String, String> mapCategoryProduct = isRegion ? getProductCategory(setProductRegion) : getProductCategory(setProductClient);
        Map<String, String> mapApprover = new Map<String, String>();
        Map<String, List<String>> mapApproverList = new Map<String, List<String>>();
        Map<String, ProdutoReserva__c> mapRegionCategoryxReservation = new Map<String, ProdutoReserva__c>();
        String categories = '';

        for (ProdutoReserva__c produtoReserva : lstReservationProduct) {
            
            for (DestinatarioReserva__c destination : mapReservation.get(produtoReserva.Reserva__c)) {

                if (isRegion) {

                    setRegion.add(destination.CodigoRegiao__c);

                    if (!mapRegionCategoryxReservation.containsKey(destination.CodigoRegiao__c + mapCategoryProduct.get(produtoReserva.Produto__c) +produtoReserva.Produto__c)) {
                    
                        mapRegionCategoryxReservation.put(destination.CodigoRegiao__c + mapCategoryProduct.get(produtoReserva.Produto__c) +produtoReserva.Produto__c, produtoReserva);
                    } 

                }else{
                    if(mapReservationClient.containsKey(destination.Cliente__c)) {
                        for (String region : mapReservationClient.get(destination.Cliente__c)) {

                            setRegion.add(region);
                        
                            if (!mapRegionCategoryxReservation.containsKey(region + mapCategoryProduct.get(produtoReserva.Produto__c)+produtoReserva.Produto__c)) {
                            
                            mapRegionCategoryxReservation.put(region + mapCategoryProduct.get(produtoReserva.Produto__c)+produtoReserva.Produto__c, produtoReserva);
                            }                         
                        } 
                    }
                 
                }
            }                    
           
            setCategoryProduct.add(mapCategoryProduct.get(produtoReserva.Produto__c));            
        }
         System.debug(setRegion);
         System.debug(setCategoryProduct);
         System.debug(recType);
        categories = string.valueof(setCategoryProduct).replace('{', '').replace('}', '').replace(',', ';');
         System.debug(categories);
        List<ResponsabilidadeAprovacao__c> lstApprovers = getApprovers(setRegion, categories, new Set<String>{recType});
         System.debug(lstApprovers);

        if (lstApprovers.size() > 0) {
            
            for (ResponsabilidadeAprovacao__c respApproval : lstApprovers) {           
                
                List<string> categoria = respApproval.Categorias__c != null ? respApproval.Categorias__c.split(';') : new List<string>() ;

                for(string cat : categoria) {
            
                    if (!mapApprover.containsKey(respApproval.Regiao__c + cat)) {
                
                        mapApprover.put(respApproval.Regiao__c + cat, respApproval.UsuarioAprovador__c);
                    }              
                }

                if (!mapApproverList.containsKey(respApproval.Regiao__c)) {
                    
                    mapApproverList.put(respApproval.Regiao__c, new List<String>{respApproval.UsuarioAprovador__c});

                }else{
                    
                    mapApproverList.get(respApproval.Regiao__c).add(respApproval.UsuarioAprovador__c);
                }       
                
            }

            System.debug('lstApprovers '+lstApprovers);
            System.debug('mapApprover '+mapApprover);

            sendReservationApproval(mapApprover, mapRegionCategoryxReservation, mapApproverList);
        }
    }

    public static void sendReservationApproval(Map<String, String> mapApprover, Map<String, ProdutoReserva__c> mapRegionCategoryxReservation, Map<String, List<String>> mapApproverList){

        Approval.ProcessResult[] processResults = null;
        List<Approval.ProcessSubmitRequest> requests = new List<Approval.ProcessSubmitRequest> ();
        Set<String> setApprovers = new Set<String>();
        Set<String> setIds = new Set<String>();
       
        System.debug(mapRegionCategoryxReservation.size());
        for (String reservation : mapRegionCategoryxReservation.keySet()) {

            string Auxreservation = reservation.left(reservation.length()-18);

            if (!setApprovers.contains(mapApprover.get(Auxreservation)) && mapApprover.get(Auxreservation)!= null) {

                requests.add(getProcessRequest(mapRegionCategoryxReservation.get(reservation).Id, mapApprover.get(Auxreservation), String.isBlank(mapRegionCategoryxReservation.get(reservation).ReservaRecebedora__c) ? 'ProdutoReserva_Aprovacao' : 'ProdutoReserva_AprovTransferencia'));
                setApprovers.add(mapApprover.get(Auxreservation));
                setIds.add(mapRegionCategoryxReservation.get(reservation).Id);

            }else  if (setApprovers.contains(mapApprover.get(Auxreservation)) && mapApprover.get(Auxreservation)!= null && !setIds.contains(mapRegionCategoryxReservation.get(reservation).Id)) {

                requests.add(getProcessRequest(mapRegionCategoryxReservation.get(reservation).Id, mapApprover.get(Auxreservation), String.isBlank(mapRegionCategoryxReservation.get(reservation).ReservaRecebedora__c) ? 'ProdutoReserva_Aprovacao' : 'ProdutoReserva_AprovTransferencia'));
                setIds.add(mapRegionCategoryxReservation.get(reservation).Id);
            }
            
            if (mapApproverList.containsKey(Auxreservation.Substring(0, Auxreservation.length() -1))) {

                for (String approversWithoutCategory : mapApproverList.get(Auxreservation.Substring(0, Auxreservation.length() -1))) {

                    if (!setApprovers.contains(approversWithoutCategory)) {
                        setApprovers.add(approversWithoutCategory);                       
                        requests.add(getProcessRequest(mapRegionCategoryxReservation.get(reservation).Id, approversWithoutCategory, String.isBlank(mapRegionCategoryxReservation.get(reservation).ReservaRecebedora__c) ? 'ProdutoReserva_Aprovacao' : 'ProdutoReserva_AprovTransferencia'));
                    } else {
                        requests.add(getProcessRequest(mapRegionCategoryxReservation.get(reservation).Id, approversWithoutCategory, String.isBlank(mapRegionCategoryxReservation.get(reservation).ReservaRecebedora__c) ? 'ProdutoReserva_Aprovacao' : 'ProdutoReserva_AprovTransferencia'));
                    }              
                }                
            }
               
            System.debug('====mapApproverList '+mapApproverList);                 
            
        }
        System.debug('====setApprovers '+setApprovers);   
        System.debug('====requests '+requests.size());   
        try {
            processResults = Approval.process(requests, true);
        }catch (System.DmlException e) {
            System.debug('Exception Is ' + e.getMessage());
        }
    }

    public static Map<String, String> getProductCategory(Set<String> setProduto){

        List<Product2> lstProduto = [SELECT id, CategoriaComercial__c FROM Product2 WHERE Id IN:setProduto];
        Map<String, String> mapCategoriaProduto = new Map<String, String>();       

        for (Product2 pd : lstProduto) {
            
            if (!mapCategoriaProduto.containsKey(pd.Id)) {
                
                mapCategoriaProduto.put(pd.Id, pd.CategoriaComercial__c == 'R' ? 'S': pd.CategoriaComercial__c);
            }
        }
        
        return mapCategoriaProduto;
    }

    public static List<ResponsabilidadeAprovacao__c> getApprovers(Set<String> setRegiao, String categorias, Set<String> setRecordtype){

        List<ResponsabilidadeAprovacao__c> lstAprovadores = [
                                                                SELECT id, Regiao__c, Categorias__c, UsuarioAprovador__c
                                                                FROM
                                                                ResponsabilidadeAprovacao__c
                                                                WHERE
                                                                Regiao__c IN:setRegiao
                                                                AND RecordTypeId IN: setRecordtype 
                                                                AND (Categorias__c INCLUDES(:categorias) 
                                                                OR Categorias__c = null)                                                               
                                                            ];
        return lstAprovadores;
    }

    public static Approval.ProcessSubmitRequest getProcessRequest(Id reservaId, Id userId, String processoDef) {
        Approval.ProcessSubmitRequest req = new Approval.ProcessSubmitRequest();
        req.setComments('Aprovação da reserva de produto');
        req.setObjectId(reservaId);
        req.setProcessDefinitionNameOrId(processoDef);
        req.setNextApproverIds(new Id[] {userId});

        return req;
    }

    public static void updateApprovalStep(Map<String, String> mapAprovacoes){

        List<ProcessInstanceWorkitem> workItems = [
            SELECT Id, ProcessInstanceId, ProcessInstance.TargetObjectId 
            FROM ProcessInstanceWorkitem 
            WHERE ProcessInstance.TargetObjectId IN :mapAprovacoes.keySet() 
            AND ProcessInstance.Status = 'Pending'
        ];

        System.debug('==== workItems' + workItems);
        List<Approval.ProcessWorkitemRequest> requests = new List<Approval.ProcessWorkitemRequest>();

        for(ProcessInstanceWorkitem workItem : workItems){

            Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
            req.setWorkitemId(workItem.Id);          
            req.setAction(mapAprovacoes.get(workItem.ProcessInstance.TargetObjectId));
            requests.add(req);
        }
        Approval.ProcessResult[] processResults = Approval.process(requests);
    }

    public static void validateQuantityUsed( Map<Id, ProdutoReserva__c> oldMap){
      
        for (ProdutoReserva__c productReservation : oldMap.values()) {

            if (productReservation.QuantidadeConsumida__c > 0 ) {              

                //productReservation.addError('A Reserva não pode ser deletada com saldo utilizado!');
            }
        }
    }

    public static Map<String,List<DestinatarioReserva__c>> getRecordTypeReservation(Set<Id> setIds){

        Map<String,List<DestinatarioReserva__c>> mapReservation = new Map<String,List<DestinatarioReserva__c>>();
        List<DestinatarioReserva__c> listReservation = [
                                                            SELECT Id, Reserva__r.RecordTypeId, Reserva__c, CodigoRegiao__c, Cliente__c
                                                            FROM
                                                            DestinatarioReserva__c
                                                            WHERE
                                                            Reserva__c IN:setIds                                                              
                                                       ];
        System.debug(setIds);
        for (DestinatarioReserva__c reservationDestination : listReservation) {

            if (!mapReservation.containsKey(reservationDestination.Reserva__c)) {

                mapReservation.put(reservationDestination.Reserva__c, new List<DestinatarioReserva__c>{reservationDestination});
                
            }else{
                mapReservation.get(reservationDestination.Reserva__c).add(reservationDestination);
            }

            System.debug(reservationDestination.Cliente__c );
            if (reservationDestination.Cliente__c != null) {
                setClients.add(reservationDestination.Cliente__c);
            }
            
        }
        System.debug(setClients);
        System.debug(mapReservation);
        return mapReservation;
    }

    public static Map<String,List<String>> getClientRegionReservation(Set<String> setIds){

        Map<String,List<String>> mapReservationRegion = new Map<String,List<String>>();
        List<Setorizacao__c> listReservation = [
                                                    SELECT Id, Conta__c, Regiao__c
                                                    FROM
                                                    Setorizacao__c
                                                    WHERE
                                                    Conta__c IN:setIds                                                              
                                               ];

        for (Setorizacao__c reservationRegion : listReservation) {

            if (!mapReservationRegion.containsKey(reservationRegion.Conta__c)) {

                mapReservationRegion.put(reservationRegion.Conta__c, new List<String>{reservationRegion.Regiao__c});
                
            }else{

                mapReservationRegion.get(reservationRegion.Conta__c).add(reservationRegion.Regiao__c);
            }
           
        }
       
        System.debug(setIds);
        System.debug(mapReservationRegion);
        return mapReservationRegion;
    }

    public static List<Id> reservationTransfer(List<ProdutoReserva__c> lstReservationTransfer, Set<String> setReceiverReservation, Set<String> setProduct, Boolean isApproved){
        
        List<Reserva__c> lstReceiverReservationProduct = getReservationProductTransfer(setReceiverReservation, setProduct);
        Map<String, ProdutoReserva__c> mapReceiverReservationProduct = new Map<String, ProdutoReserva__c>();
        List<ProdutoReserva__c> lstInsertReservationProductReceiver = new List<ProdutoReserva__c>();
        ProdutoReserva__c productReceiver = new ProdutoReserva__c();
        List<Id> lstReservationIntegration = new List<Id>();     
        List<FeedItem> lstFeedItem = new List<FeedItem>();
        Map<String,String> mapReservationReceiverName = new Map<String,String>();
        
        System.debug('==== lstReceiverReservationProduct'+lstReceiverReservationProduct);

        if (lstReceiverReservationProduct.size() > 0) {
            
            for (Reserva__c resTransfer : lstReceiverReservationProduct) {

                if (!mapReservationReceiverName.containsKey(resTransfer.Id)) {
                          
                    mapReservationReceiverName.put(resTransfer.Id, resTransfer.Name);
                }

                if (resTransfer.ProdutosReserva__r.size() > 0) {

                    for (ProdutoReserva__c resTransferPd : resTransfer.ProdutosReserva__r) {

                        if (!mapReceiverReservationProduct.containsKey(resTransferPd.Reserva__c+'-'+resTransferPd.Produto__c)) {
                            mapReceiverReservationProduct.put(resTransferPd.Reserva__c+'-'+resTransferPd.Produto__c, resTransferPd);
                        }                      

                    }                    
                }                
            }
        }       

        for (ProdutoReserva__c res : lstReservationTransfer) {
           
            if (!mapReceiverReservationProduct.containsKey(res.ReservaRecebedora__c+'-'+res.Produto__c) && isApproved) {

                lstInsertReservationProductReceiver.add(createInstanceReservationProduct(res));                    
                
            }else{

                mapReceiverReservationProduct.get(res.ReservaRecebedora__c+'-'+res.Produto__c).QuantidadeReservada__c += res.QuantidadeTransferida__c;

                if (!isApproved) {
                    
                    mapReceiverReservationProduct.get(res.ReservaRecebedora__c+'-'+res.Produto__c).StatusReserva__c = 'Ativa';

                }else{

                    mapReceiverReservationProduct.get(res.ReservaRecebedora__c+'-'+res.Produto__c).StatusReserva__c = 'Aguardando integração';
                }
                

                if (mapReceiverReservationProduct.get(res.ReservaRecebedora__c+'-'+res.Produto__c).StatusReserva__c != 'Aguardando aprovação') {
                    
                    lstReservationIntegration.add(mapReceiverReservationProduct.get(res.ReservaRecebedora__c+'-'+res.Produto__c).Id);
                }
            }            

            lstFeedItem.add(createChatterReservationList(res, mapReservationReceiverName.get(res.ReservaRecebedora__c),isApproved));
            mapReceiverReservationProduct.put(res.Reserva__c+'-'+res.Produto__c, updateTransferQuantity(res));
        }

        if (lstInsertReservationProductReceiver.size() > 0) {
            
            insertReservationProductTransfer(lstInsertReservationProductReceiver);
        }
        
        if (lstFeedItem.size() > 0) {
           insert lstFeedItem;
        }
        
        System.debug(mapReceiverReservationProduct.values());
        update mapReceiverReservationProduct.values();

        return lstReservationIntegration;

    }

    public static ProdutoReserva__c createInstanceReservationProduct(ProdutoReserva__c res){
        
        ProdutoReserva__c productReceiver = new ProdutoReserva__c();
        productReceiver.Reserva__c = res.ReservaRecebedora__c;
        productReceiver.Produto__c = res.Produto__c;
        productReceiver.QuantidadeReservada__c = res.QuantidadeTransferida__c;
        // productReceiver.QuantidadeAtiva__c = res.QuantidadeAtiva__c;
        productReceiver.QuantidadeAtiva__c = 0;
        productReceiver.Armazem__c = res.Armazem__c;
        productReceiver.Preco__c = res.Preco__c;
        productReceiver.StatusReserva__c = 'Aguardando integração';

        return productReceiver;

    }

    public static void insertReservationProductTransfer(List<ProdutoReserva__c> lstInsertProductReceiver){

        insert lstInsertProductReceiver; 
    }

    public static List<Reserva__c> getReservationProductTransfer(Set<String> setReceiverReservation, Set<String> setProduct){

        return  [
                    SELECT Id, Name, CodigoReserva__c, CodigoCD__c, (SELECT Id, Reserva__c, QuantidadeTransferida__c, QuantidadeReservada__c, StatusReserva__c, Produto__c FROM ProdutosReserva__r WHERE Produto__c IN:setProduct)
                    FROM Reserva__c 
                    WHERE Id IN: setReceiverReservation 
                ];
    }

    public static ProdutoReserva__c updateTransferQuantity(ProdutoReserva__c res){        
      
        ProdutoReserva__c productReceiver = new ProdutoReserva__c();
        productReceiver.Id = res.Id;
        productReceiver.QuantidadeReservada__c = res.QuantidadeReservada__c;
        productReceiver.QuantidadeReservada__c -= res.QuantidadeTransferida__c;
        productReceiver.QuantidadeTransferida__c = null;
        productReceiver.ReservaRecebedora__c = null;
       
        return productReceiver;
    }

    public static FeedItem createChatterReservationList(ProdutoReserva__c reservationsender, String nameReservationReceiver, Boolean isApproved){

        String bodyMsg = isApproved ?'.\nQuantidade transferida: '+String.valueOf(reservationsender.QuantidadeTransferida__c.setScale(0))  :' não foi aprovada.';
        FeedItem feed = new FeedItem();
        feed.ParentId = reservationsender.Reserva__c;  
        feed.Body     = 'Transferência realizada do produto '+ reservationsender.CodigoProduto__c  +' para a reserva '+ nameReservationReceiver+ bodyMsg;

        return feed;
    }

    public static void updateLastDateReservationMovement(Map<Id, ProdutoReserva__c> mapReservation, Map<Id, ProdutoReserva__c> mapReservationOld){
       
        for (ProdutoReserva__c productReservation : mapReservation.values()) {
            
            ProdutoReserva__c oldProdutoReserva = mapReservationOld.get(productReservation.Id);

            if (productReservation.QuantidadeConsumida__c != oldProdutoReserva.QuantidadeConsumida__c) {
                
                productReservation.DataUltimaMovimentacao__c = System.now();
            }
           
        }     
    }

    
    public static void populateChaveUnica(List<ProdutoReserva__c> newRecordList){

        Set<String> setReservation = new Set<String>();
        List<Reserva__c> lstreservation = new List<Reserva__c>();
        Map<String, String> mapProd = new Map<String, String>();
        Map<Id, Product2> mapProductcode = new Map<Id, Product2>();

        System.debug(newRecordList);

        for (ProdutoReserva__c produtoReserva : newRecordList) {

            setReservation.add(produtoReserva.Reserva__c);
            mapProd.put(produtoReserva.Produto__c, '');
            
        }

        mapProductcode = new Map<ID, Product2>([SELECT Id, ProductCode FROM Product2 WHERE Id IN: mapProd.keySet()]);


        for (Product2 pd : mapProductcode.values()) {

            mapProd.put(pd.Id, pd.ProductCode);
            
        }

        lstreservation = getReservationProductTransfer(setReservation, mapProd.keySet());

        for (ProdutoReserva__c produtoReserva : newRecordList) {

            for (Reserva__c reserva : lstreservation) {
                System.debug('=============== '+reserva.CodigoReserva__c);
                System.debug('=============== '+produtoReserva.ChaveUnica__c);

                if (produtoReserva.Reserva__c == reserva.Id && (String.isBlank(produtoReserva.ChaveUnica__c) || produtoReserva.ChaveUnica__c == null)) {
                    
                    produtoReserva.ChaveUnica__c = reserva.CodigoReserva__c + mapProd.get(produtoReserva.Produto__c) + produtoReserva.Armazem__c;
                }
            
            }
            
        }

    }
}