Git Tests/force-app/main/default/default/objects/Integracoes__c/Integracoes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuração  personalizada utilizada para gerir os dados de acessos das integrações</description>
    <label>Integrações</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Order/fields/ErroIntegracaoRejeitado__c.field-meta.xml
<CustomField>
    <fullName>ErroIntegracaoRejeitado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Erro de integração Rejeitado</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/BatchResendOrderTest.cls
@IsTest
public with sharing class BatchResendOrderTest {
    @TestSetup
    static void makeData(){
        Account acc = TestUtility.createAccPJ();
        insert acc;

        Order order = TestUtility.createOrder(acc);
        insert order;

        order.ErroIntegracaoRejeitado__c = true;
        update order;

        Integracoes__c integration = TestUtility.createCustomSettingApproval();
        insert integration;
    }
    
    @isTest
    public static void BatchResendOrder() {
        BatchResendOrderSchedule batchSchedule = new BatchResendOrderSchedule();
        batchSchedule.execute(null);
        BatchResendOrderSchedule.scheduleBatch();
    }
}