Git Tests/force-app/main/default/default/objects/Integracoes__c/Integracoes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuração  personalizada utilizada para gerir os dados de acessos das integrações</description>
    <label>Integrações</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <inlineHelpText>URL de acesso ao serviço</inlineHelpText>
    <label>EndPoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Método</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Senha</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>Usuário</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ErroIntegracaoAprovacao__c.field-meta.xml
<CustomField>
    <fullName>ErroIntegracaoAprovacao__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Erro de integração Aprovação</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ErroIntegracaoCancelamento__c.field-meta.xml
<CustomField>
    <fullName>ErroIntegracaoCancelamento__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Erro de integração Cancelamento</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ErroIntegracaoConfirmacao__c.field-meta.xml
<CustomField>
    <fullName>ErroIntegracaoConfirmacao__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Erro de integração Confirmação</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ErroIntegracaoRejeitado__c.field-meta.xml
<CustomField>
    <fullName>ErroIntegracaoRejeitado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Erro de integração Rejeitado</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Chave única: Número do pedido + Código do CD</description>
    <externalId>true</externalId>
    <label>Código do pedido TOTVS</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/MensagemErroIntegracao__c.field-meta.xml
<CustomField>
    <fullName>MensagemErroIntegracao__c</fullName>
    <label>Mensagem Erro Integração</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/PedidoOriginal__c.field-meta.xml
<CustomField>
    <fullName>PedidoOriginal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido original</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Pedidos (Pedido original)</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/PedidoPai__c.field-meta.xml
<CustomField>
    <fullName>PedidoPai__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido pai</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Pedidos filho</relationshipLabel>
    <relationshipName>PedidoFilho</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/PedidoPendente__c.field-meta.xml
<CustomField>
    <fullName>PedidoPendente__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pedido pendente</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/RejeicaoProcesso__c.field-meta.xml
<CustomField>
    <fullName>RejeicaoProcesso__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Rejeição do processo?</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/StatusIntegracao__c.field-meta.xml
<CustomField>
    <fullName>StatusIntegracao__c</fullName>
    <label>Status da integração</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Integrado</fullName>
            </value>
            <value>
                <fullName>Não integrado</fullName>
            </value>
            <value>
                <fullName>Erro de aprovação/rejeição</fullName>
            </value>
            <value>
                <fullName>Nota fiscal cancelada</fullName>
            </value>
            <value>
                <fullName>Pedido em aberto</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por regra</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por crédito</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por estoque</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por crédito e estoque</fullName>
            </value>
            <value>
                <fullName>Pedido aguardando separação</fullName>
            </value>
            <value>
                <fullName>Pedido em separação</fullName>
            </value>
            <value>
                <fullName>Pedido separado/aguardando faturamento</fullName>
            </value>
            <value>
                <fullName>Pedido faturado</fullName>
            </value>
            <value>
                <fullName>Pedido com resíduo eliminado (sem faturamento)</fullName>
            </value>
            <value>
                <fullName>Pedido com resíduo eliminado (com faturamento)</fullName>
            </value>
            <value>
                <fullName>Pedido liberado</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado na alçada de desconto</fullName>
            </value>
            <value>
                <fullName>Pedido com SC</fullName>
            </value>
            <value>
                <fullName>Pedido aguardando saldo</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por regra de bonificação</fullName>
            </value>
            <value>
                <fullName>Pedido cancelado</fullName>
            </value>
            <value>
                <fullName>Pedido rejeitado no Salesforce</fullName>
            </value>
            <value>
                <fullName>Pedido rejeitado na alçada financeira</fullName>
            </value>
            <value>
                <fullName>Erro integração (Envio ao Protheus)</fullName>
            </value>
            <value>
                <fullName>Erro integração (geração do pedido no Protheus)</fullName>
            </value>
            <value>
                <fullName>Pedido aguardando envio/processamento do comprovante de pagamento RA</fullName>
            </value>
            <value>
                <fullName>Pedido aguardando aprovação de pagamento RA</fullName>
            </value>
            <value>
                <fullName>Pedido rejeitado na alçada de aprovação de pagamento RA</fullName>
            </value>
            <value>
                <fullName>Aguardando processamento na integradora</fullName>
            </value>
            <value>
                <fullName>Aprovado na integradora</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/classes/IntegrationReprocessOrderOUT.cls
public without sharing class IntegrationReprocessOrderOUT {

    public class OrderRequest {
        public String  PedidoIntegrador;
        
        public OrderRequest(Order ord) {
            this.PedidoIntegrador = ord.OrderNumber;
        }
    }

    public class ResultClass {
        public String  result   { get; set; }
        public Boolean atualizado { get; set; }
    }

    @InvocableMethod(label='Reprocess order' description='Reprocess order and send to TOTVS')
    public static List<String> sendReprocessOrder(List<Id> ordIdList){
        Order contextOrd = null;
        Set<Id> ordIdSet = new Set<Id>();
        for (Order order : [SELECT Id, ExternalId__c, Status, StatusIntegracao__c, OrderNumber, CNPJCD__c, RejeicaoProcesso__c, RecordTypeId,
                                PedidoOriginal__c, PedidoPendente__c, PedidoPai__c, ErroIntegracaoCancelamento__c, MensagemErroIntegracao__c,
                                Description, ErroIntegracaoAprovacao__c, ErroIntegracaoConfirmacao__c, ErroIntegracaoRejeitado__c 
                            FROM Order WHERE Id IN :ordIdList AND Status != 'Cancelado']) {
            if (order.Status == 'ErroIntegracao' && (order.StatusIntegracao__c == 'Erro integração (Envio ao Protheus)' || order.StatusIntegracao__c == 'Erro integração (geração do pedido no Protheus)')) {
                contextOrd = order;
            } 
        }
        if (contextOrd != null) {
            sendReprocessOrderToERP(contextOrd);
        }
        return null;
    }

    public static void sendReprocessOrderToERP(Order contextOrd) {
        Integracoes__c intCustomerApi = Integracoes__c.getValues('ElfaReprocessOrderAPI');
        String method   = intCustomerApi.Method__c;
        String endpoint = intCustomerApi.Endpoint__c;
        String username = intCustomerApi.User__c;
        String password = intCustomerApi.Password__c;
        
        HttpRequest req = new HttpRequest();
        req.setEndpoint(endpoint);
        req.setHeader('Authorization', 'Basic ' + EncodingUtil.base64Encode(Blob.valueOf(username + ':' + password)));
        req.setHeader('Content-Type', 'application/json');
        req.setMethod(method);
        req.setTimeout(120000);

        System.debug(EncodingUtil.base64Encode(Blob.valueOf(username + ':' + password)));
        OrderRequest orderReq = new OrderRequest(contextOrd);
        System.debug('contractReq: ' + orderReq);

        String body;
        body = Json.serialize(orderReq);
        System.debug('Body: '+ body);

        String resultString = '';
        HttpResponse resp = new HttpResponse();
        try {
            req.setBody(body);
            resp = new Http().send(req);
            
            System.debug(resp);
            System.debug(resp.getStatusCode());
            Boolean hasError = false;
            resultString = resp.getBody();
            System.debug('resp' + resultString);            
            String statusIntegration = null;
            if (resp.getStatusCode() == 200 || resp.getStatusCode() == 201) {        
                resultString = resp.getBody();
                IntegrationUtils.WSLog('Reprocessamento Pedido', 'Outbound', body, resultString, hasError);
            } else {
                hasError = true;
                resultString = resp.getBody();
                IntegrationUtils.WSLog('Reprocessamento Pedido', 'Outbound', body, resultString, hasError);
            }
            ResultClass resClass = null;
            String errorMessage  = null;
            
            try {
                resClass = (ResultClass)JSON.deserialize(resultString, ResultClass.class);
                hasError = !resClass.atualizado;
                errorMessage = hasError ? resClass.result : null;
            } catch (Exception e) {
                system.debug(e.getMessage());
                hasError = true;
                errorMessage = 'Erro de integração do reprocessamento do pedido.';
            }           
            
            if (!hasError)  {
                contextOrd.Status                    = 'Aguardando integração';
                contextOrd.StatusIntegracao__c       = null;
                contextOrd.MensagemErroIntegracao__c = errorMessage;
                
                OrderHandler.disableTrigger();
                update contextOrd;
                OrderHandler.enableTrigger();
            }
        } catch (Exception e) {
            resultString = e.getMessage();
        }
    }
}