Git Tests/force-app/main/default/default/objects/Integracoes__c/Integracoes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuração  personalizada utilizada para gerir os dados de acessos das integrações</description>
    <label>Integrações</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <inlineHelpText>URL de acesso ao serviço</inlineHelpText>
    <label>EndPoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Método</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Senha</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>Usuário</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/AttachmentId__c.field-meta.xml
<CustomField>
    <fullName>AttachmentId__c</fullName>
    <externalId>true</externalId>
    <label>Comprovante de pagamento Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ComprovanteAnexado__c.field-meta.xml
<CustomField>
    <fullName>ComprovanteAnexado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Comprovante anexado</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/FileIntegrationStatus__c.field-meta.xml
<CustomField>
    <fullName>FileIntegrationStatus__c</fullName>
    <label>Status da integração de comprovante</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ok</fullName>
            </value>
            <value>
                <fullName>Erro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/MessageIntegrationStatus__c.field-meta.xml
<CustomField>
    <fullName>MessageIntegrationStatus__c</fullName>
    <label>Mensagem da integração de comprovante</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/PedidoProtheusResumido__c.field-meta.xml
<CustomField>
    <fullName>PedidoProtheusResumido__c</fullName>
    <description>Campo criado para considerar apenas o número do pedido no Protheus (6 caracteres) sem o número do CD.</description>
    <label>Pedido Protheus resumido</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/IntegrationPaymentAttachment.cls
global without sharing class IntegrationPaymentAttachment {
    public static final String STATUS_INTEGRATED = 'Ok';
    public static final String STATUS_ERROR = 'Erro';

    global class OrderRequest {
        public String CgcEmp;
        public String NumPedido;
        public String comprovante;

        public OrderRequest (Order order, String attachment) {
            this.comprovante = attachment;
            this.NumPedido   = order.PedidoProtheusResumido__c;
            this.CgcEmp      = order.CNPJCD__c;
        }
    }

    @AuraEnabled
    public static void updatePayment(Id orderId, String documentId) {
        Order orderToUpdate;
        for (Order ord : [SELECT Id, AttachmentId__c, ComprovanteAnexado__c FROM Order WHERE Id = :orderId]) {
            orderToUpdate = ord;
        }
        if (orderToUpdate != null) {
            orderToUpdate.AttachmentId__c = documentId;
            orderToUpdate.ComprovanteAnexado__c = true;
            OrderHandler.disableTrigger();
            update orderToUpdate;
            OrderHandler.enableTrigger();
        }
    }
    
    @AuraEnabled
    public static String sendAttachment(Id orderId) {
        String statusIntegracao = STATUS_INTEGRATED;
        Integracoes__c integrationPayment = Integracoes__c.getValues('GetPaymentAttachment');

        String method   = integrationPayment.Method__c;
        String endpoint = integrationPayment.Endpoint__c;
        String username = integrationPayment.User__c;
        String password = integrationPayment.Password__c;

        HttpRequest request = new HttpRequest();
        request.setEndpoint(endpoint);
        request.setHeader('Authorization', 'Basic ' + EncodingUtil.base64Encode(Blob.valueOf(username + ':' + password)));
        request.setHeader('Content-Type', 'application/json;charset=UTF-8');
        request.setMethod(method);
        request.setTimeout(120000);

        System.debug('Username : password =>');
        System.debug(EncodingUtil.base64Encode(Blob.valueOf(username + ':' + password)));

        Order orderToIntegration = [SELECT Id, AttachmentId__c, PedidoProtheusResumido__c, CNPJCD__c FROM Order WHERE Id = :orderId][0];
        ContentDocument document = [SELECT Id, LatestPublishedVersionId, LatestPublishedVersion.VersionData FROM ContentDocument WHERE Id = :orderToIntegration.AttachmentId__c][0];

        OrderRequest orderRequest = new OrderRequest(orderToIntegration, EncodingUtil.base64Encode(document.LatestPublishedVersion.VersionData));
        System.debug('OrderRequest =>');
        System.debug(orderRequest);
        
        String body;
        body = JSON.serialize(orderRequest);
        System.debug('Body: ' + body);

        String resultString = '';
        HttpResponse response = new HttpResponse();
        try {
            request.setBody(body);
            response = new Http().send(request);
            
            System.debug(response);
            System.debug(response.getStatusCode());
            
            resultString = response.getBody();
            System.debug('Response: ' + resultString);

            if (response.getStatusCode() == 200) {
                resultString = response.getBody();
                IntegrationUtils.WSLog('Envio do comprovante de pagamento', 'Outbound', body, resultString, false);
            } else {
                resultString = response.getBody();
                IntegrationUtils.WSLog('Envio do comprovante de pagamento', 'Outbound', body, resultString, true);
                statusIntegracao = STATUS_ERROR;
            }

            String integrationMessage = statusIntegracao == STATUS_ERROR ? 'Erro no envio do comprovante de para o Protheus, será reenviado novamente em 1 hora.' : 'Comprovante anexado ao pedido de venda com sucesso!!';
            Boolean hasError          = statusIntegracao == STATUS_ERROR;

            Order orderUpdate;
            if (statusIntegracao == STATUS_INTEGRATED) {
                orderUpdate = new Order(
                    Id = orderId,
                    Status = 'Aguardando aprovação RA',
                    FileIntegrationStatus__c    = statusIntegracao,
                    MessageIntegrationStatus__c = integrationMessage
                );
            } else {
                orderUpdate = new Order(
                    Id = orderId,
                    FileIntegrationStatus__c    = statusIntegracao,
                    MessageIntegrationStatus__c = integrationMessage
                );
            }

            OrderHandler.disableTrigger();
            update orderUpdate;
            OrderHandler.enableTrigger();

            System.debug('Status: ' + statusIntegracao);
        } catch (Exception e) {
            resultString = e.getMessage();
            IntegrationUtils.WSLog('Envio do comprovante de pagamento', 'Outbound', body, resultString, true);
        }
        return statusIntegracao;
    }

    @InvocableMethod(label='Send Order Attachment to Protheus' 
                    description='Send Order Attachment to Protheus')
    public static void flowSendAttachment(List<Id> orderIdList) {
        
        sendAttachment(orderIdList[0]);
    }
}