Git Tests/force-app/main/default/default/objects/Integracoes__c/Integracoes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuração  personalizada utilizada para gerir os dados de acessos das integrações</description>
    <label>Integrações</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <inlineHelpText>URL de acesso ao serviço</inlineHelpText>
    <label>EndPoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Método</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Senha</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>Usuário</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/ValorUn__c.field-meta.xml
<CustomField>
    <fullName>ValorUn__c</fullName>
    <inlineHelpText>Secundário: Segunda unidade de medida do produto</inlineHelpText>
    <label>Valor (Secundário)</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/TemplatePDF__c/TemplatePDF__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Objeto para os dados de template de PDF.</description>
    <label>Template PDF</label>
</CustomObject>

Git Tests/force-app/main/default/default/classes/OpportunityCreatePDFTest.cls
@IsTest
public with sharing class OpportunityCreatePDFTest { 
    @TestSetup
    static void makeData(){
        Integracoes__c integration =  new Integracoes__c(
			Name        = 'ElfaLaboratoryOrderAPI',
			Method__c   = 'POST',
			Endpoint__c = 'https://na1.ai.dm-us.informaticacloud.com/active-bpel/rt/P-SFDC-Reprocessamento-Pedido',
			User__c     = 'cloud.dev@grupoelfa.com.br',
			Password__c = 'Elf@Cloud'
		);
        insert integration;
       
    }
    @IsTest
    public static void flowCreatePDFTest() {
        TemplatePDF__c template = new TemplatePDF__c(Name = 'ElfaQuoteTemplate', Id	= null);
        insert template;
        Product2 product        = TestUtility.createProduct();
        insert product;
        User user               = TestUtility.createUser();
        insert user;
        Opportunity opportunity = TestUtility.createOpportunity(user);
        insert opportunity;
        PricebookEntry pricebookEntry = [SELECT Id, UnitPrice FROM PricebookEntry][0];
        pricebookEntry.IsActive       = true;
        update pricebookEntry;
        OpportunityLineItem opportunityLineItem = TestUtility.createOpportunityLineItem(opportunity, product, pricebookEntry);
        insert opportunityLineItem;
        opportunityLineItem.ValorUn__c = 10.00;
        update opportunityLineItem;

        OpportunityCreatePDF.FlowInputs flowInput = new OpportunityCreatePDF.FlowInputs();
        flowInput.opportunityId = opportunity.id;
        flowInput.pdfChoice = 'ElfaQuoteTemplate';
        flowInput.productCode = '000001,000002';

        OpportunityCreatePDF.flowCreatePDF(new List<OpportunityCreatePDF.FlowInputs>{flowInput});
    }
}