Git Tests/force-app/main/default/default/objects/Integracoes__c/Integracoes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuração  personalizada utilizada para gerir os dados de acessos das integrações</description>
    <label>Integrações</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/PrecoTotal__c.field-meta.xml
<CustomField>
    <fullName>PrecoTotal__c</fullName>
    <label>Preço total</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/BatchSendOrderTest.cls
@IsTest
public with sharing class BatchSendOrderTest {
    @TestSetup
    static void makeData(){
        Account acc = TestUtility.createAccPJ();
        insert acc;

        Order order = TestUtility.createOrder(acc);
        insert order;

        Product2 product = TestUtility.createProduct();
        insert product;

        PricebookEntry pricebookEntry = [SELECT Id, UnitPrice FROM PricebookEntry WHERE Product2Id =: product.Id];
        OrderItem orderItem = TestUtility.createOrderItem(order, product, pricebookEntry);
        orderItem.PrecoTotal__c = 100;
        insert orderItem;
        
        Integracoes__c integration = TestUtility.createCustomSettingOrder();
        insert integration;
    }
    
    @isTest
    public static void BatchSendOrder() {
        Set<Id> orderIdSet = new Set<Id>();
        for (Order order : [SELECT Id FROM Order]) {
            orderIdSet.add(order.Id);
        }

        BatchSendOrder.run(orderIdSet);
    }
}