Git Tests/force-app/main/default/default/objects/Integracoes__c/Integracoes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuração  personalizada utilizada para gerir os dados de acessos das integrações</description>
    <label>Integrações</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <inlineHelpText>URL de acesso ao serviço</inlineHelpText>
    <label>EndPoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Método</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Senha</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>Usuário</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ErroIntegracaoAprovacao__c.field-meta.xml
<CustomField>
    <fullName>ErroIntegracaoAprovacao__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Erro de integração Aprovação</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ErroIntegracaoRejeitado__c.field-meta.xml
<CustomField>
    <fullName>ErroIntegracaoRejeitado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Erro de integração Rejeitado</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Chave única: Número do pedido + Código do CD</description>
    <externalId>true</externalId>
    <label>Código do pedido TOTVS</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/MensagemErroIntegracao__c.field-meta.xml
<CustomField>
    <fullName>MensagemErroIntegracao__c</fullName>
    <label>Mensagem Erro Integração</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/PedidoPai__c.field-meta.xml
<CustomField>
    <fullName>PedidoPai__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido pai</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Pedidos filho</relationshipLabel>
    <relationshipName>PedidoFilho</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/RecallProcesso__c.field-meta.xml
<CustomField>
    <fullName>RecallProcesso__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recall do processo?</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/RejeicaoProcesso__c.field-meta.xml
<CustomField>
    <fullName>RejeicaoProcesso__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Rejeição do processo?</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/StatusAprovacao__c.field-meta.xml
<CustomField>
    <fullName>StatusAprovacao__c</fullName>
    <label>Status de aprovação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>StatusAprovacao</valueSetName>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/StatusIntegracao__c.field-meta.xml
<CustomField>
    <fullName>StatusIntegracao__c</fullName>
    <label>Status da integração</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Integrado</fullName>
            </value>
            <value>
                <fullName>Não integrado</fullName>
            </value>
            <value>
                <fullName>Erro de aprovação/rejeição</fullName>
            </value>
            <value>
                <fullName>Nota fiscal cancelada</fullName>
            </value>
            <value>
                <fullName>Pedido em aberto</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por regra</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por crédito</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por estoque</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por crédito e estoque</fullName>
            </value>
            <value>
                <fullName>Pedido aguardando separação</fullName>
            </value>
            <value>
                <fullName>Pedido em separação</fullName>
            </value>
            <value>
                <fullName>Pedido separado/aguardando faturamento</fullName>
            </value>
            <value>
                <fullName>Pedido faturado</fullName>
            </value>
            <value>
                <fullName>Pedido com resíduo eliminado (sem faturamento)</fullName>
            </value>
            <value>
                <fullName>Pedido com resíduo eliminado (com faturamento)</fullName>
            </value>
            <value>
                <fullName>Pedido liberado</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado na alçada de desconto</fullName>
            </value>
            <value>
                <fullName>Pedido com SC</fullName>
            </value>
            <value>
                <fullName>Pedido aguardando saldo</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por regra de bonificação</fullName>
            </value>
            <value>
                <fullName>Pedido cancelado</fullName>
            </value>
            <value>
                <fullName>Pedido rejeitado no Salesforce</fullName>
            </value>
            <value>
                <fullName>Pedido rejeitado na alçada financeira</fullName>
            </value>
            <value>
                <fullName>Erro integração (Envio ao Protheus)</fullName>
            </value>
            <value>
                <fullName>Erro integração (geração do pedido no Protheus)</fullName>
            </value>
            <value>
                <fullName>Pedido aguardando envio/processamento do comprovante de pagamento RA</fullName>
            </value>
            <value>
                <fullName>Pedido aguardando aprovação de pagamento RA</fullName>
            </value>
            <value>
                <fullName>Pedido rejeitado na alçada de aprovação de pagamento RA</fullName>
            </value>
            <value>
                <fullName>Aguardando processamento na integradora</fullName>
            </value>
            <value>
                <fullName>Aprovado na integradora</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/TipoOperacao__c.field-meta.xml
<CustomField>
    <fullName>TipoOperacao__c</fullName>
    <label>Tipo de operação</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/CodigoProduto__c.field-meta.xml
<CustomField>
    <fullName>CodigoProduto__c</fullName>
    <formula>Product2.ExternalId__c</formula>
    <label>Código do produto</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Número do item do pedido</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/Lote__c.field-meta.xml
<CustomField>
    <fullName>Lote__c</fullName>
    <label>Lote</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/PrecoTotal__c.field-meta.xml
<CustomField>
    <fullName>PrecoTotal__c</fullName>
    <label>Preço total</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/TipoOperacao__c.field-meta.xml
<CustomField>
    <fullName>TipoOperacao__c</fullName>
    <label>Tipo da operação</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/ValidadeMinima__c.field-meta.xml
<CustomField>
    <fullName>ValidadeMinima__c</fullName>
    <label>Validade mínima</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>168</fullName>
                <label>7 dias</label>
            </value>
            <value>
                <fullName>720</fullName>
                <label>30 dias</label>
            </value>
            <value>
                <fullName>1440</fullName>
                <label>60 dias</label>
            </value>
            <value>
                <fullName>2160</fullName>
                <label>90 dias</label>
            </value>
            <value>
                <fullName>4320</fullName>
                <label>180 dias</label>
            </value>
            <value>
                <fullName>8760</fullName>
                <label>1 ano</label>
            </value>
            <value>
                <fullName>13140</fullName>
                <label>18 meses</label>
            </value>
            <value>
                <fullName>17520</fullName>
                <label>24 meses</label>
            </value>
            <value>
                <fullName>Vazio</fullName>
            </value>
            <value>
                <fullName>Shelf Life</fullName>
            </value>
            <value>
                <fullName>Entre 3 a 6 meses</fullName>
                <isActive>false</isActive>
                <label>Entre 3 a 6 meses</label>
            </value>
            <value>
                <fullName>Entre 6 a 12 meses</fullName>
                <isActive>false</isActive>
                <label>Entre 6 a 12 meses</label>
            </value>
            <value>
                <fullName>Maior que 12 meses</fullName>
                <isActive>false</isActive>
                <label>Maior que 12 meses</label>
            </value>
            <value>
                <fullName>Menor que 3 meses</fullName>
                <isActive>false</isActive>
                <label>Menor que 3 meses</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/globalValueSets/StatusAprovacao.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Em digitação</fullName>
    </customValue>
    <customValue>
        <fullName>Em aprovação</fullName>
    </customValue>
    <customValue>
        <fullName>Aprovado</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelado</fullName>
    </customValue>
    <description>Valores de status para os processos de aprovação de orçamento e pedido.</description>
    <masterLabel>Status de aprovação</masterLabel>
</GlobalValueSet>

Git Tests/force-app/main/default/default/classes/IntegrationApprovalOrderOUT.cls
global without sharing class IntegrationApprovalOrderOUT {
    public static final String STATUS_INTEGRATED = 'Integrado';
    public static final String STATUS_APPROVAL_ERROR = 'Erro de aprovação/rejeição';

    global class OrderRequest {
        public String  BranchCGC;//CgcEmp;
        public String  InternalOrderNumber;//NumPedido;
        public String  ExternalOrderNumber;//NumPedInte;
        public Boolean Approved;//liberado;
        
        public OrderRequest(Order ord, String cnpjCD) {
            this.BranchCGC     = cnpjCD;
            this.InternalOrderNumber  = ord.ExternalId__c == null ? '000000' : getExternalId(ord.ExternalId__c);
            this.ExternalOrderNumber = ord.OrderNumber;
            this.Approved   = ord.StatusIntegracao__c == 'Pedido rejeitado na alçada financeira' ? false : ord.PedidoPai__r.Status == 'Aprovado';
        }
    }

    public class ResultClass {
        public String  result   { get; set; }
        public String incluido { get; set; }
    }

    // IntegrationApprovalOrderOUT.sendApprovalOrderToERP('801q0000001DUQdAAO');

    public static void sendApprovalOrderToERP(Id ordId) {
        
        Integracoes__c intCustomerApi = Integracoes__c.getValues('ElfaApprovalOrderAPI');
        
        String method   = intCustomerApi.Method__c;
        String endpoint = intCustomerApi.Endpoint__c;
        String username = intCustomerApi.User__c;
        String password = intCustomerApi.Password__c;
        
        HttpRequest req = new HttpRequest();
        req.setEndpoint(endpoint);
        req.setHeader('Authorization', 'Basic ' + EncodingUtil.base64Encode(Blob.valueOf(username + ':' + password)));
        req.setHeader('Content-Type', 'application/json');
        req.setMethod(method);
        req.setTimeout(120000);

        System.debug(EncodingUtil.base64Encode(Blob.valueOf(username + ':' + password)));

        OrderRequest orderReq;

        String cnpjCD = '';

        for (OrderItem orderItem : [SELECT Id, Quantity, TipoOperacao__c, CodigoProduto__c, Lote__c, PrecoTotal__c, ValidadeMinima__c, CNPJCD__c FROM OrderItem WHERE OrderId = :ordId]) {
            cnpjCD = orderItem.CNPJCD__c;
        }
        Boolean shouldSend = true;
        for (Order order : [SELECT Id, ExternalId__c, PedidoPai__r.Status, Status, StatusIntegracao__c, StatusAprovacao__c, OrderNumber, CNPJCD__c, RejeicaoProcesso__c,
                                   PedidoPai__r.RejeicaoProcesso__c, PedidoPai__r.RecallProcesso__c, RecallProcesso__c FROM Order WHERE Id = :ordId]) {
            if (cnpjCD == null || cnpjCD == '') cnpjCD = order.CNPJCD__c;
            orderReq = new OrderRequest(order, cnpjCD);
            //if (order.PedidoPai__r.Status != 'Aprovado' && order.PedidoPai__r.Status != 'Reprovado') shouldSend = false;
            if (order.PedidoPai__r.Status == 'Aprovado' && order.ExternalId__c == null) shouldSend = false;
        }

        System.debug('contractReq: ' + orderReq);

        String body;
        body = Json.serialize(orderReq);
        System.debug('Body: '+ body);

        if (shouldSend) {
            String resultString = '';
            HttpResponse resp = new HttpResponse();
            try {
                req.setBody(body);
                resp = new Http().send(req);
                
                System.debug(resp);
                System.debug(resp.getStatusCode());
                
                resultString = resp.getBody();
                System.debug('resp' + resultString);            
                String statusIntegration = null;
                if (resp.getStatusCode() == 200 || resp.getStatusCode() == 201) {        
                    resultString = resp.getBody();
                    IntegrationUtils.WSLog('Pedido Aprovação/Rejeição', 'Outbound', body, resultString, false);
                } else {
                    resultString = resp.getBody();
                    IntegrationUtils.WSLog('Pedido Aprovação/Rejeição', 'Outbound', body, resultString, true);
                    statusIntegration = STATUS_APPROVAL_ERROR;
                }
    
                ResultClass resClass = null;
    
                try {
                    resClass = (ResultClass)JSON.deserialize(resultString, ResultClass.class);
                } catch (Exception e) {
                    system.debug(e.getMessage());
                }
                Boolean hasError    = statusIntegration == STATUS_APPROVAL_ERROR ? true : false;
                String errorMessage = statusIntegration == STATUS_APPROVAL_ERROR ? 'Erro de integração do pedido aprovado/rejeitado! Aguardar o tempo de reenvio automático. (Pedido já integrado/reservado).' : null;
                
                Order ord = new Order(Id = ordId);
                if (statusIntegration != null) {
                    ord.StatusIntegracao__c = statusIntegration;
                }
                
                if (orderReq.Approved) {
                    ord.MensagemErroIntegracao__c  = errorMessage;
                    ord.Status                     = hasError ? 'ErroIntegracao' : 'Pai - Aprovado';
                    ord.ErroIntegracaoAprovacao__c = hasError;
                } else {
                    ord.MensagemErroIntegracao__c  = errorMessage;
                    ord.Status                     = hasError ? 'ErroIntegracao' : 'Aguardando envio de rejeição';
                    ord.ErroIntegracaoRejeitado__c = hasError;
                }
    
                OrderHandler.disableTrigger();
                update ord;
                OrderHandler.enableTrigger();

                if (ord.Status == 'Aguardando envio de rejeição') {
                    ord.Status = 'Cancelado';
                    OrderHandler.disableTrigger();
                    update ord;
                    OrderHandler.enableTrigger();
                }
    
            } catch (Exception e) {
                System.debug(e.getMessage() +''+e.getStackTraceString());
                resultString = e.getMessage();
            }
        }        
    }
    
    public static String getExternalId(String val){
        return val.trim().substring(5, val.length());
    }
}