Git Tests/force-app/main/default/default/objects/Integracoes__c/Integracoes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuração  personalizada utilizada para gerir os dados de acessos das integrações</description>
    <label>Integrações</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <inlineHelpText>URL de acesso ao serviço</inlineHelpText>
    <label>EndPoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Método</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Senha</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>Usuário</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/ItemCampanha__c.object-meta.xml
<CustomObject>
    <label>Item da campanha</label>
    <nameField>
        <label>Código do item de campanha</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens da campanha</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/CodigoProduto__c.field-meta.xml
<CustomField>
    <fullName>CodigoProduto__c</fullName>
    <formula>NomeProduto__r.ProductCode</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código do produto</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/Lote__c.field-meta.xml
<CustomField>
    <fullName>Lote__c</fullName>
    <label>Lote</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/PrecoMinimo__c.field-meta.xml
<CustomField>
    <fullName>PrecoMinimo__c</fullName>
    <label>Preço mínimo</label>
    <precision>12</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/PrecoUnitario__c.field-meta.xml
<CustomField>
    <fullName>PrecoUnitario__c</fullName>
    <label>Preço unitário</label>
    <precision>12</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/ProductShelfLifeController.cls
public without sharing class ProductShelfLifeController {

    @AuraEnabled(cacheable=true)
    public static List<LoteResponse> getLotes(String clienteCGC, String productCode) {
		Integracoes__c customSettingsGetLotes = Integracoes__c.getValues('InformaticaConsultaLotes');
        Blob headerValue = Blob.valueOf(customSettingsGetLotes.User__c + ':' + customSettingsGetLotes.Password__c);
        Map<String, ItemCampanha__c> mapItemCampanhaLoteNameToCampanha = getMapLoteNameItemCampanhaToCampanha(productCode);
        Map<String, LoteResponse> mapLoteNameToLote = new Map<String, LoteResponse>();
        List<LoteResponse> loteList = new List<LoteResponse>();
        HttpResponse response = new HttpResponse();
        HttpRequest request = new HttpRequest();

        request.setEndpoint(customSettingsGetLotes.Endpoint__c);
        request.setMethod(customSettingsGetLotes.Method__c);
        request.setHeader('Authorization', 'Basic ' + EncodingUtil.base64Encode(headerValue));
        request.setHeader('Content-Type', 'application/json');
        request.setHeader('Accept', '*/*');
        request.setTimeout(120000);
        request.setBody(JSON.serializePretty(new LoteRequest(clienteCGC, productCode)));

        try {
            String resultResponseString = '';
            response = new Http().send(request);
            resultResponseString = response.getBody();
            
            if(response.getStatusCode() == 200 || response.getStatusCode() == 201) {        
                LoteResponseList responseFromIntegration = (LoteResponseList) JSON.deserialize(resultResponseString, LoteResponseList.class);
                loteList = responseFromIntegration.estoque;
                
                if(!mapItemCampanhaLoteNameToCampanha.isEmpty()) {
                    for(LoteResponse iLoteResponse : loteList) {
                        if(mapItemCampanhaLoteNameToCampanha.containsKey(iLoteResponse.lote)) {
                            iLoteResponse.setFields(true, mapItemCampanhaLoteNameToCampanha.get(iLoteResponse.lote).PrecoUnitario__c, mapItemCampanhaLoteNameToCampanha.get(iLoteResponse.lote).PrecoMinimo__c);
                            mapLoteNameToLote = getMapLoteNameToLote(iLoteResponse, mapLoteNameToLote);
                        } else {
                            iLoteResponse.setFields(false, 0.0, 0.0);
                            mapLoteNameToLote = getMapLoteNameToLote(iLoteResponse, mapLoteNameToLote);
                        }
                    }
                } else {
                    for(LoteResponse iLoteResponse : loteList) {
                        iLoteResponse.setFields(false, 0.0, 0.0);
                        mapLoteNameToLote = getMapLoteNameToLote(iLoteResponse, mapLoteNameToLote);
                    }
                }
            }

            System.debug(resultResponseString);
        } catch (Exception e) {
            System.debug(e.getMessage());
        }

        if(!mapLoteNameToLote.isEmpty()) {
            return mapLoteNameToLote.values();
        } else {
            if(!loteList.isEmpty()) return loteList;
            else return null;
        }
    }

    private static Map<String, ItemCampanha__c> getMapLoteNameItemCampanhaToCampanha(String productCode) {
        Map<String, ItemCampanha__c> mapItemCampanhaLoteNameToCampanha = new Map<String, ItemCampanha__c>();

        for(ItemCampanha__c iItemCampanha : [
            SELECT Id, CodigoProduto__c, Lote__c, PrecoMinimo__c, PrecoUnitario__c 
            FROM ItemCampanha__c 
            WHERE CodigoProduto__c =: productCode
            AND RecordType.Name = 'Item de campanha de shelf life'
        ]) {
            mapItemCampanhaLoteNameToCampanha.put(iItemCampanha.Lote__c, iItemCampanha);
        }

        return mapItemCampanhaLoteNameToCampanha;
    }

    private static Map<String, LoteResponse> getMapLoteNameToLote(LoteResponse iLoteResponse, Map<String, LoteResponse> mapLoteNameToLote) {
        if(mapLoteNameToLote.containsKey(iLoteResponse.lote)) {
            mapLoteNameToLote.get(iLoteResponse.lote).estoque = String.valueOf(Decimal.valueOf(mapLoteNameToLote.get(iLoteResponse.lote).estoque) + Decimal.valueOf(iLoteResponse.estoque));
        } else {
            mapLoteNameToLote.put(iLoteResponse.lote, iLoteResponse);
        }

        return mapLoteNameToLote;
    }

    @TestVisible
    private class LoteRequest {
        public String cnpj;
        public String produto;
        
        public LoteRequest (String clienteCgc, String productCode) {
            cnpj    = clienteCgc;
            produto = productCode;
        }
    }

    @TestVisible
    private class LoteResponseList {
        public List<LoteResponse> estoque;
    }

    @TestVisible
    private class LoteResponse {
        @AuraEnabled public String cod_produto;
        @AuraEnabled public String cod_produto_polo;
        @AuraEnabled public String descricao;
        @AuraEnabled public String lote;
        @AuraEnabled public String validade;
        @AuraEnabled public String cod_operacao_logistica;
        @AuraEnabled public String cod_operacao_logistica_polo;
        @AuraEnabled public String id_endereco;
        @AuraEnabled public String endereco;
        @AuraEnabled public String endereco_completo;
        @AuraEnabled public String ean13;
        @AuraEnabled public String id_lote_classificacao;
        @AuraEnabled public String id_lote_classificacao_polo;
        @AuraEnabled public String estoque;
        @AuraEnabled public String retido;
        @AuraEnabled public String cod_situacao;
        @AuraEnabled public String divergencia;
        @AuraEnabled public String cod_distribuicao;
        @AuraEnabled public String data_fabricacao;
        @AuraEnabled public Boolean is_shelflife = false;
        @AuraEnabled public Decimal minimum_price = 0.0;
        @AuraEnabled public Decimal maximum_price = 0.0;

        private void setFields(Boolean isShelfLife, Decimal maximumPrice, Decimal minimumPrice) {
            this.is_shelflife  = isShelfLife;
            this.minimum_price = minimumPrice;
            this.maximum_price = maximumPrice;
        }
    }
}