Git Tests/force-app/main/default/default/objects/Integracoes__c/Integracoes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuração  personalizada utilizada para gerir os dados de acessos das integrações</description>
    <label>Integrações</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <inlineHelpText>URL de acesso ao serviço</inlineHelpText>
    <label>EndPoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Método</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Senha</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>Usuário</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/NotasFiscais__c/NotasFiscais__c.object-meta.xml
<CustomObject>
    <label>Nota fiscal</label>
    <nameField>
        <label>Número da nota fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas fiscais</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/NotasFiscais__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Nome do cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>NotasFiscais</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/NotasFiscais__c/fields/Pedido__c.field-meta.xml
<CustomField>
    <fullName>Pedido__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número do pedido</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>NotasFiscais</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/PaymentSlipPreviewControllerTest.cls
@isTest
private class PaymentSlipPreviewControllerTest {
    @isTest
    static void testGetPaymentSlip(){
        Test.setMock(HttpCalloutMock.class, new PaymentSlipCalloutMock());

        Integracoes__c integracao = new Integracoes__c(
			Name        = 'ElfaTitulosAbertosAPI',
			Method__c   = 'POST',
			Endpoint__c = 'undefined',
			User__c     = 'sample@grupoelfa.com.br',
			Password__c = 'samplePassword'
		);
        insert integracao;

        Id recordTypeId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Pessoa jurídica').getRecordTypeId();
        System.debug('recordTypeId: ' + recordTypeId);
        Account acc = new Account(
            name ='Test Account',
            recordTypeId = recordTypeId
        );
        insert acc;

        Order order = TestUtility.createOrder(acc);
        insert order;
        NotasFiscais__c nf = new NotasFiscais__c(
            Pedido__c = order.Id,
            Name = 'Test Nf',
            Conta__c = acc.id
        );
        insert nf;

        Test.startTest();
        String json  = PaymentSlipPreviewController.getPaymentSlip(nf.id);
        String json2 = PaymentSlipPreviewController.getPaymentTitle(acc.id);
        Test.stopTest();
        
        System.debug('Json2: ' + json2);
        System.assertEquals('{"EMPRESA":"ATRIAL"}', json);
    }
}