Git Tests/force-app/main/default/default/objects/Integracoes__c/Integracoes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuração  personalizada utilizada para gerir os dados de acessos das integrações</description>
    <label>Integrações</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <inlineHelpText>URL de acesso ao serviço</inlineHelpText>
    <label>EndPoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Método</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Senha</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>Usuário</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/NotasFiscais__c/NotasFiscais__c.object-meta.xml
<CustomObject>
    <label>Nota fiscal</label>
    <nameField>
        <label>Número da nota fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas fiscais</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Order/fields/AttachmentId__c.field-meta.xml
<CustomField>
    <fullName>AttachmentId__c</fullName>
    <externalId>true</externalId>
    <label>Comprovante de pagamento Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ComprovanteAnexado__c.field-meta.xml
<CustomField>
    <fullName>ComprovanteAnexado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Comprovante anexado</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/FileIntegrationStatus__c.field-meta.xml
<CustomField>
    <fullName>FileIntegrationStatus__c</fullName>
    <label>Status da integração de comprovante</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ok</fullName>
            </value>
            <value>
                <fullName>Erro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/TitulosAbertos__c/TitulosAbertos__c.object-meta.xml
<CustomObject>
    <label>Título em aberto</label>
    <nameField>
        <displayFormat>TIT-{0000000}</displayFormat>
        <label>Número do título em aberto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Títulos em aberto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/classes/BatchPaymentAttachmentTest.cls
@isTest
public with sharing class BatchPaymentAttachmentTest {
    @TestSetup
    static void makeData(){
        ContentVersion ctVersionNf = TestUtility.createContentVersion();
        ctVersionNf.Description = 'nf001';
        insert ctVersionNf;
        ContentVersion ctVersionTit = TestUtility.createContentVersion();
        ctVersionTit.Description = 'tit001';
        insert ctVersionTit;
        Account acc = TestUtility.createAccPJ();
        insert acc;
        Order ord = TestUtility.createOrder(acc);
        insert ord;
        NotasFiscais__c nf = TestUtility.createNotaFiscal(ord, acc);
        insert nf;
        TitulosAbertos__c tit = TestUtility.createTituloAberto(acc, nf);
        insert tit;

        Integracoes__c integration =  new Integracoes__c(
			Name        = 'GetPaymentAttachment',
			Method__c   = 'POST',
			Endpoint__c = 'https://teste.com/',
			User__c     = 'test@test.com.br',
			Password__c = 'test'
		);
        insert integration;
    }
    
    @isTest
    public static void BatchPaymentAttachment() {
        List<ContentDocument> contentDocumentList = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        List<Order> orderList = [SELECT Id, AttachmentId__c, ComprovanteAnexado__c, FileIntegrationStatus__c FROM Order];
        
        orderList[0].AttachmentId__c = contentDocumentList[0].Id;
        orderList[0].ComprovanteAnexado__c = true;
        orderList[0].FileIntegrationStatus__c = 'Erro';
        OrderHandler.disableTrigger();
        update orderList;
        OrderHandler.enableTrigger();

        ContentDocumentLink link = new ContentDocumentLink();
        link.LinkedEntityId = orderList[0].Id;
        link.ContentDocumentId = contentDocumentList[0].Id;
        link.ShareType = 'V';
        link.Visibility = 'AllUsers';
        insert link;

        BatchPaymentAttachmentSchedule batchSchedule = new BatchPaymentAttachmentSchedule();
        batchSchedule.execute(null);
        BatchPaymentAttachment batchPA = new BatchPaymentAttachment();
        batchPA.execute(null, orderList);
        BatchPaymentAttachmentSchedule.scheduleBatch();
    }
}