Git Tests/force-app/main/default/default/objects/Integracoes__c/Integracoes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuração  personalizada utilizada para gerir os dados de acessos das integrações</description>
    <label>Integrações</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <inlineHelpText>URL de acesso ao serviço</inlineHelpText>
    <label>EndPoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Método</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Senha</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>Usuário</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ComentariosCancelamento__c.field-meta.xml
<CustomField>
    <fullName>ComentariosCancelamento__c</fullName>
    <label>Comentários (opcional)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ErroIntegracaoAprovacao__c.field-meta.xml
<CustomField>
    <fullName>ErroIntegracaoAprovacao__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Erro de integração Aprovação</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ErroIntegracaoCancelamento__c.field-meta.xml
<CustomField>
    <fullName>ErroIntegracaoCancelamento__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Erro de integração Cancelamento</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ErroIntegracaoConfirmacao__c.field-meta.xml
<CustomField>
    <fullName>ErroIntegracaoConfirmacao__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Erro de integração Confirmação</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ErroIntegracaoRejeitado__c.field-meta.xml
<CustomField>
    <fullName>ErroIntegracaoRejeitado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Erro de integração Rejeitado</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Chave única: Número do pedido + Código do CD</description>
    <externalId>true</externalId>
    <label>Código do pedido TOTVS</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/MensagemErroIntegracao__c.field-meta.xml
<CustomField>
    <fullName>MensagemErroIntegracao__c</fullName>
    <label>Mensagem Erro Integração</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/MotivoCancelamento__c.field-meta.xml
<CustomField>
    <fullName>MotivoCancelamento__c</fullName>
    <label>Motivo de cancelamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Desistência do cliente</fullName>
            </value>
            <value>
                <fullName>Cancelado para correção</fullName>
            </value>
            <value>
                <fullName>Falha operacional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/PedidoOriginal__c.field-meta.xml
<CustomField>
    <fullName>PedidoOriginal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido original</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Pedidos (Pedido original)</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/PedidoPai__c.field-meta.xml
<CustomField>
    <fullName>PedidoPai__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido pai</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Pedidos filho</relationshipLabel>
    <relationshipName>PedidoFilho</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/PedidoPendente__c.field-meta.xml
<CustomField>
    <fullName>PedidoPendente__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pedido pendente</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/RejeicaoProcesso__c.field-meta.xml
<CustomField>
    <fullName>RejeicaoProcesso__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Rejeição do processo?</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/StatusIntegracao__c.field-meta.xml
<CustomField>
    <fullName>StatusIntegracao__c</fullName>
    <label>Status da integração</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Integrado</fullName>
            </value>
            <value>
                <fullName>Não integrado</fullName>
            </value>
            <value>
                <fullName>Erro de aprovação/rejeição</fullName>
            </value>
            <value>
                <fullName>Nota fiscal cancelada</fullName>
            </value>
            <value>
                <fullName>Pedido em aberto</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por regra</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por crédito</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por estoque</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por crédito e estoque</fullName>
            </value>
            <value>
                <fullName>Pedido aguardando separação</fullName>
            </value>
            <value>
                <fullName>Pedido em separação</fullName>
            </value>
            <value>
                <fullName>Pedido separado/aguardando faturamento</fullName>
            </value>
            <value>
                <fullName>Pedido faturado</fullName>
            </value>
            <value>
                <fullName>Pedido com resíduo eliminado (sem faturamento)</fullName>
            </value>
            <value>
                <fullName>Pedido com resíduo eliminado (com faturamento)</fullName>
            </value>
            <value>
                <fullName>Pedido liberado</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado na alçada de desconto</fullName>
            </value>
            <value>
                <fullName>Pedido com SC</fullName>
            </value>
            <value>
                <fullName>Pedido aguardando saldo</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por regra de bonificação</fullName>
            </value>
            <value>
                <fullName>Pedido cancelado</fullName>
            </value>
            <value>
                <fullName>Pedido rejeitado no Salesforce</fullName>
            </value>
            <value>
                <fullName>Pedido rejeitado na alçada financeira</fullName>
            </value>
            <value>
                <fullName>Erro integração (Envio ao Protheus)</fullName>
            </value>
            <value>
                <fullName>Erro integração (geração do pedido no Protheus)</fullName>
            </value>
            <value>
                <fullName>Pedido aguardando envio/processamento do comprovante de pagamento RA</fullName>
            </value>
            <value>
                <fullName>Pedido aguardando aprovação de pagamento RA</fullName>
            </value>
            <value>
                <fullName>Pedido rejeitado na alçada de aprovação de pagamento RA</fullName>
            </value>
            <value>
                <fullName>Aguardando processamento na integradora</fullName>
            </value>
            <value>
                <fullName>Aprovado na integradora</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/SubmotivosCancelamento__c.field-meta.xml
<CustomField>
    <fullName>SubmotivosCancelamento__c</fullName>
    <label>Submotivo de cancelamento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>MotivoCancelamento__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Preço</fullName>
            </value>
            <value>
                <fullName>Prazo de entrega</fullName>
            </value>
            <value>
                <fullName>Condição de pagamento</fullName>
            </value>
            <value>
                <fullName>Qualidade do produto</fullName>
            </value>
            <value>
                <fullName>Quantidade insuficiente</fullName>
            </value>
            <value>
                <fullName>Preferiu a concorrência</fullName>
            </value>
            <value>
                <fullName>Inclusão de item</fullName>
            </value>
            <value>
                <fullName>Exclusão de item</fullName>
            </value>
            <value>
                <fullName>Erro de estoque</fullName>
            </value>
            <value>
                <fullName>Correção de preço</fullName>
            </value>
            <value>
                <fullName>Marca do produto</fullName>
            </value>
            <value>
                <fullName>Quantidade do item</fullName>
            </value>
            <value>
                <fullName>Endereço de entrega</fullName>
            </value>
            <value>
                <fullName>Tamanho diferente da nota fiscal</fullName>
            </value>
            <value>
                <fullName>Quantidade diferente da nota fiscal</fullName>
            </value>
            <value>
                <fullName>Aprovação fora do prazo</fullName>
            </value>
            <value>
                <fullName>Aprovação de cadastro</fullName>
            </value>
            <value>
                <fullName>Erro na descrição</fullName>
            </value>
            <value>
                <fullName>Devolução e troca do material</fullName>
            </value>
            <value>
                <fullName>Faturado o mesmo pedido duas vezes</fullName>
            </value>
            <value>
                <fullName>Fator de conversão e unidade de medida</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/TipoOperacao__c.field-meta.xml
<CustomField>
    <fullName>TipoOperacao__c</fullName>
    <label>Tipo de operação</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/recordTypes/PedidoMae.recordType-meta.xml
<RecordType>
    <fullName>PedidoMae</fullName>
    <active>true</active>
    <label>Pedido pai</label>
</RecordType>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/CodigoProduto__c.field-meta.xml
<CustomField>
    <fullName>CodigoProduto__c</fullName>
    <formula>Product2.ExternalId__c</formula>
    <label>Código do produto</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Número do item do pedido</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/Lote__c.field-meta.xml
<CustomField>
    <fullName>Lote__c</fullName>
    <label>Lote</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/PrecoTotal__c.field-meta.xml
<CustomField>
    <fullName>PrecoTotal__c</fullName>
    <label>Preço total</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/TipoOperacao__c.field-meta.xml
<CustomField>
    <fullName>TipoOperacao__c</fullName>
    <label>Tipo da operação</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/PedidoIntegradora__c/PedidoIntegradora__c.object-meta.xml
<CustomObject>
    <label>Pedido de integradora</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Nome de Pedido de integradora</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pedidos de integradora</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/PedidoIntegradora__c/fields/RejeicaoProcesso__c.field-meta.xml
<CustomField>
    <fullName>RejeicaoProcesso__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Rejeição processo</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/IntegrationCancelOrderOUT.cls
public without sharing class IntegrationCancelOrderOUT {
    
    public static final Id MOTHERORDER_RECORDTYPE = Schema.SObjectType.Order.getRecordTypeInfosByDeveloperName().get('PedidoMae').getRecordTypeId();

    public class OrderRequest {
        public String  BranchCGC;//CgcEmp;
        public String  InternalOrderNumber;//NumPedido;
        public String  ExternalOrderNumber;//NumPedInte;
        
        public OrderRequest(Order ord, String cnpjCD) {
            this.BranchCGC     = cnpjCD;
            this.InternalOrderNumber  = ord.ExternalId__c == null ? '000000' : getExternalId(ord.ExternalId__c);
            this.ExternalOrderNumber = ord.OrderNumber;
        }
    }

    public class ResultClass {
        public String  result   { get; set; }
        public Boolean incluido { get; set; }
    }

    @InvocableMethod(label='Cancel order' description='Cancel order and send to TOTVS')
    public static List<String> sendCancelledOrder(List<FlowInputs> flowInputs){
        Id ordId = null;
        String cancelReason = null;
        String cancelSubReason = null;
        String cancelCommentary = null;
        for (FlowInputs flowInput : flowInputs) {
            ordId = flowInput.orderId;
            cancelCommentary = flowInput.commentary;
            cancelSubReason = flowInput.subReason;
            cancelReason = flowInput.reason;
        }

        Set<Id> ordIdSet = new Set<Id>();
        Boolean isParent = false;
        List<Order> ordListToUpdate = new List<Order>();
        for (Order order : [SELECT Id, ExternalId__c, Status, StatusIntegracao__c, OrderNumber, CNPJCD__c, RejeicaoProcesso__c, RecordTypeId,
                                PedidoOriginal__c, PedidoPendente__c, PedidoPai__c, ErroIntegracaoCancelamento__c, MensagemErroIntegracao__c,
                                Description, ErroIntegracaoAprovacao__c, ErroIntegracaoConfirmacao__c, ErroIntegracaoRejeitado__c, MotivoCancelamento__c,
                                SubmotivosCancelamento__c, ComentariosCancelamento__c, OwnerId, AccountId, LastModifiedDate 
                            FROM Order WHERE Id = :ordId AND Status != 'Cancelado']) {
            cancelReasons(order, cancelReason, cancelSubReason, cancelCommentary);
            if (order.RecordTypeId == MOTHERORDER_RECORDTYPE) {
                order.Status = 'Cancelado';
                if (!order.PedidoPendente__c) {
                    isParent = true;
                }
            } else {
                if ((order.Status == 'ErroIntegracao' && order.StatusIntegracao__c == 'Não integrado') || order.Status == 'Em digitação') {
                    order.Status = 'Cancelado';
                    clearErrors(order, false);
                } else {
                    ordIdSet.add(order.Id);
                }
            }
            ordListToUpdate.add(order);
        }

        if (isParent) {
            OrderHandler.disableTrigger();
            recallApprovalProcess(ordId);
            OrderHandler.enableTrigger();
            for (Order order : [SELECT Id, ExternalId__c, Status, StatusIntegracao__c, OrderNumber, CNPJCD__c, RejeicaoProcesso__c, RecordTypeId,
                                    PedidoOriginal__c, PedidoPendente__c, PedidoPai__c, ErroIntegracaoCancelamento__c, MensagemErroIntegracao__c,
                                    Description, ErroIntegracaoAprovacao__c, ErroIntegracaoConfirmacao__c, ErroIntegracaoRejeitado__c, MotivoCancelamento__c,
                                    SubmotivosCancelamento__c, ComentariosCancelamento__c, OwnerId, AccountId, LastModifiedDate 
                                FROM Order WHERE PedidoPai__c = :ordId AND Status != 'Cancelado']) {
                cancelReasons(order, cancelReason, cancelSubReason, cancelCommentary);
                if (order.Status == 'ErroIntegracao' && order.StatusIntegracao__c == 'Não integrado') {
                    order.Status = 'Cancelado';
                    clearErrors(order, false);
                } else {
                    ordIdSet.add(order.Id);
                }
                ordListToUpdate.add(order);
            }
        }
        List<Order> sendEmailCancelledOrders = new List<Order>();

        for (Order order : [SELECT Id, ExternalId__c, Status, StatusIntegracao__c, OrderNumber, CNPJCD__c, RejeicaoProcesso__c, RecordTypeId,
                                PedidoOriginal__c, PedidoPendente__c, PedidoPai__c, ErroIntegracaoCancelamento__c, MensagemErroIntegracao__c,
                                Description, ErroIntegracaoAprovacao__c, ErroIntegracaoConfirmacao__c, ErroIntegracaoRejeitado__c, MotivoCancelamento__c,
                                SubmotivosCancelamento__c, ComentariosCancelamento__c, OwnerId, AccountId, LastModifiedDate  
                            FROM Order WHERE PedidoOriginal__c = :ordId AND Status = 'Em digitação']) {
            order.Status = 'Cancelado';
            cancelReasons(order, cancelReason, cancelSubReason, cancelCommentary);
            ordListToUpdate.add(order);
            sendEmailCancelledOrders.add(order);
        }

        if (!sendEmailCancelledOrders.isEmpty()) {            
            SendEmailMessage.sendEmailMessageCancelledOrder(sendEmailCancelledOrders);
        }

        if (!ordListToUpdate.isEmpty()) {
            OrderHandler.disableTrigger();
            update ordListToUpdate;
            OrderHandler.enableTrigger();
        }

        if (!ordIdSet.isEmpty()) {     
            if (ordIdSet.size() < 50){
                System.enqueueJob(new IntegrationCancelOrderQueueable(0, new List<Id>(ordIdSet)));      
            }            
        }
        return null;
    }

    public static void sendCancelOrderToERP(Id ordId) {

        Integracoes__c intCustomerApi = Integracoes__c.getValues('ElfaCancelOrderAPI');
        
        String method   = intCustomerApi.Method__c;
        String endpoint = intCustomerApi.Endpoint__c;
        String username = intCustomerApi.User__c;
        String password = intCustomerApi.Password__c;
        
        HttpRequest req = new HttpRequest();
        req.setEndpoint(endpoint);
        req.setHeader('Authorization', 'Basic ' + EncodingUtil.base64Encode(Blob.valueOf(username + ':' + password)));
        req.setHeader('Content-Type', 'application/json');
        req.setMethod(method);
        req.setTimeout(120000);

        System.debug(EncodingUtil.base64Encode(Blob.valueOf(username + ':' + password)));

        OrderRequest orderReq;

        String cnpjCD = '';

        for (OrderItem orderItem : [SELECT Id, Quantity, TipoOperacao__c, CodigoProduto__c, Lote__c, PrecoTotal__c, ValidadeMinima__c, CNPJCD__c FROM OrderItem WHERE OrderId = :ordId]) {
            cnpjCD = orderItem.CNPJCD__c;
        }
        Order ord;
        for (Order order : [SELECT Id, ExternalId__c, Status, StatusIntegracao__c, OrderNumber, CNPJCD__c, RejeicaoProcesso__c, ErroIntegracaoCancelamento__c, CodigoIntegradora__c,
                                    MensagemErroIntegracao__c, Description, ErroIntegracaoAprovacao__c, ErroIntegracaoConfirmacao__c, ErroIntegracaoRejeitado__c
                            FROM Order WHERE Id = :ordId]) {
            orderReq = new OrderRequest(order, cnpjCD);
            ord = order;
        }

        System.debug('contractReq: ' + orderReq);

        String body;
        body = Json.serialize(orderReq);
        System.debug('Body: '+ body);

        String resultString = '';
        HttpResponse resp = new HttpResponse();
        try {
            req.setBody(body);
            resp = new Http().send(req);
            
            System.debug(resp);
            System.debug(resp.getStatusCode());
            Boolean hasError = false;
            resultString = resp.getBody();
            System.debug('resp' + resultString);            
            String statusIntegration = null;
            if (resp.getStatusCode() == 200 || resp.getStatusCode() == 201) {        
                resultString = resp.getBody();
                IntegrationUtils.WSLog('Cancelamento Pedido', 'Outbound', body, resultString, hasError);
            } else {
                hasError = true;
                resultString = resp.getBody();
                IntegrationUtils.WSLog('Cancelamento Pedido', 'Outbound', body, resultString, hasError);
                statusIntegration = IntegrationOrderOUT.STATUS_ERROR;
            }

            ResultClass resClass = null;
            String errorMessage  = null;
            
            try {
                system.debug('resultString: ' + resultString);
                resClass = (ResultClass)JSON.deserialize(resultString, ResultClass.class);
                system.debug('resClass: ' + resClass);
                hasError = resClass?.incluido != null ? !resClass.incluido : false;
                errorMessage = hasError ? resClass.result : null;
            } catch (Exception e) {
                system.debug(e.getMessage());
                hasError = true;
                clearErrors(ord, hasError);
                if (ord.ExternalId__c == null) {
                    ord.Status = 'Cancelado';
                    ord.StatusIntegracao__c = null;
                    ord.MensagemErroIntegracao__c = null;
                    OrderHandler.disableTrigger();
                    update ord;
                    OrderHandler.enableTrigger();
                } else {
                    throw new IntegrationCancelOrderException('Erro de integração do cancelamento do pedido. Aguardar reenvio automático para o cancelamento no Protheus.');
                }
            }
            
            ord.StatusIntegracao__c           = statusIntegration;
            ord.MensagemErroIntegracao__c     = errorMessage;
            clearErrors(ord, hasError);
            
            if (!hasError)  {
                if (ord.ExternalId__c == null) {
                    ord.Status = 'Cancelado';
                } else {
                    ord.Status = 'Aguardando envio de cancelamento';
                }
                ord.StatusIntegracao__c = null;
                ord.Description         = null;
                
                OrderHandler.disableTrigger();
                update ord;
                OrderHandler.enableTrigger();

                if (ord.CodigoIntegradora__c != null) {
                    List<PedidoIntegradora__c> labOrderList = new List<PedidoIntegradora__c>();
                    for (PedidoIntegradora__c labOrd : [SELECT Id, Status__c FROM PedidoIntegradora__c WHERE CodigoIntegradora__c = :ord.CodigoIntegradora__c]) {
                        labOrd.Status__c = 'Aguardando envio de cancelamento';
                        labOrderList.add(labOrd);
                    }
                    if (!labOrderList.isEmpty()) {
                        update labOrderList;
                    }
                }
            }
        } catch (Exception e) {
            resultString = e.getMessage();
            throw new IntegrationCancelOrderException(resultString);
        }
    }

    public static String getExternalId(String val){
        return val.trim().substring(5, val.length());
    }

    public static void clearErrors(Order ord, Boolean hasError){
        ord.ErroIntegracaoCancelamento__c = hasError;
        ord.ErroIntegracaoAprovacao__c    = false;
        ord.ErroIntegracaoConfirmacao__c  = false;
        ord.ErroIntegracaoRejeitado__c    = false;
    }

    public static void cancelReasons(Order order, String reason, String subReason, String commentary) {
        order.MotivoCancelamento__c      = reason;
        order.SubmotivosCancelamento__c  = subReason;
        order.ComentariosCancelamento__c = commentary;
    }

    public static void recallApprovalProcess(Id ordId) {
        List<Approval.ProcessWorkitemRequest> requests = new List<Approval.ProcessWorkitemRequest> ();
        Map<Id, ProcessInstance> mapIdToProcessInstance = new Map<Id, ProcessInstance>([SELECT Id, TargetObjectId FROM ProcessInstance WHERE (TargetObjectId = :ordId)]);

        List<ProcessInstanceWorkItem> processInstanceWkItemList = [SELECT Id, ProcessInstanceId, ProcessInstance.TargetObjectId, ProcessInstance.Status FROM ProcessInstanceWorkItem WHERE ProcessInstanceId IN :mapIdToProcessInstance.keySet() AND ProcessInstance.Status = 'Pending'];
        for(ProcessInstanceWorkItem workItem : processInstanceWkItemList){
            System.debug('workItem: ' + workItem);
            // if there's a work item, set the action to 'removed' and execute
            System.debug('mapIdToProcessInstance: ' + mapIdToProcessInstance);
            Approval.ProcessWorkitemRequest req = new Approval.ProcessWorkitemRequest();
            req.setAction('Removed');
            req.setWorkitemId(workItem.Id);
            requests.add(req);
        }

        Approval.ProcessResult[] processResults;
        if (!requests.isEmpty()) {
            processResults = Approval.process(requests, true);
        }
    }
    public class IntegrationCancelOrderException extends Exception {}

    public class FlowInputs{
    
        @InvocableVariable
        public String orderId;
        
        @InvocableVariable
        public String reason;

        @InvocableVariable
        public String subReason;

        @InvocableVariable
        public String commentary;
    }
}