Git Tests/force-app/main/default/default/objects/ResponsabilidadeAprovacao__c/ResponsabilidadeAprovacao__c.object-meta.xml
<CustomObject>
    <label>Responsabilidade de aprovação</label>
    <nameField>
        <displayFormat>RA-{00000}</displayFormat>
        <label>Nome de Responsabilidade de aprovação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responsabilidades de aprovação</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ResponsabilidadeAprovacao__c/fields/Categorias__c.field-meta.xml
<CustomField>
    <fullName>Categorias__c</fullName>
    <label>Categorias</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>AMBOS</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>DIABETES</label>
            </value>
            <value>
                <fullName>G</fullName>
                <label>GENÉRICO</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>MATERIAIS</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>NUTRIÇÃO</label>
            </value>
            <value>
                <fullName>Q</fullName>
                <label>ODONTOLOGIA</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>MEDCTECH</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>SPECIALTY</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <label>EQUIPAMENTO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/ResponsabilidadeAprovacao__c/fields/CodigoMesa__c.field-meta.xml
<CustomField>
    <fullName>CodigoMesa__c</fullName>
    <externalId>true</externalId>
    <label>Código da mesa</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ResponsabilidadeAprovacao__c/fields/Regiao__c.field-meta.xml
<CustomField>
    <fullName>Regiao__c</fullName>
    <externalId>true</externalId>
    <label>Região</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ResponsabilidadeAprovacao__c/fields/UsuarioAprovador__c.field-meta.xml
<CustomField>
    <fullName>UsuarioAprovador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário aprovador</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ResponsabilidadeAprovacao</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/Setorizacao__c.object-meta.xml
<CustomObject>
    <label>Setorização</label>
    <nameField>
        <displayFormat>SET-{000000}</displayFormat>
        <label>Número da setorização</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setorizações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>BU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>G</fullName>
                <label>GENÉRICO</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>MATERIAIS</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>NUTRIÇÃO</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Medctech</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>SPECIALTY</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>AMBOS</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>DIABETES</label>
            </value>
            <value>
                <fullName>Q</fullName>
                <label>ODONTOLOGIA</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <label>EQUIPAMENTO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/CodigoMesa__c.field-meta.xml
<CustomField>
    <fullName>CodigoMesa__c</fullName>
    <externalId>true</externalId>
    <label>Código da mesa</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome do cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Setorização</relationshipLabel>
    <relationshipName>Setorizacao</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Regiao__c.field-meta.xml
<CustomField>
    <fullName>Regiao__c</fullName>
    <label>Região</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/ApprovalProcessManagement.cls
public with sharing class ApprovalProcessManagement {
    public static Map<String, Set<Id>> getApprovalUsers(Set<Id> setAccountId, Map<String, Set<String>> mapRecTypeToCategories) {
        Set<Id> setUserId = new Set<Id>();
        Set<String> setKeysectorization = new Set<String>();

        Set<String> setApprovalRecTypeName = new Set<String>();
        Set<String> setProcessCategories = new Set<String>();
        Map<String, Set<Id>> mapApprovalProcessToSetUser = new Map<String, Set<Id>>(); // "Pedido_AprovacaoPricingM", Set<Id> (Usuários)

        Boolean isOrder = true;

        Map<String, Set<String>> mapApprovalProcessToCategories = new Map<String, Set<String>>();

        for (String mapKey : mapRecTypeToCategories.keySet()) {
            String approvalProcess = mapKey.split('----')[1];
            if (!approvalProcess.contains('Pedido_')) {
                isOrder = false;
            }
            String recTypeName = approvalProcess.replace('Pedido_', '').replace('Oportunidade_', '');
            mapApprovalProcessToCategories.put(approvalProcess, mapRecTypeToCategories.get(mapKey));
            system.debug('recTypeName: ' + recTypeName);
            setApprovalRecTypeName.add(recTypeName);

            for (String cat : mapRecTypeToCategories.get(mapKey)) {
                setProcessCategories.add(recTypeName + cat);
            }
        }

        system.debug('setProcessCategories: ' + setProcessCategories);

        system.debug(setApprovalRecTypeName);
        system.debug('mapApprovalProcessToCategories: ' + mapApprovalProcessToCategories);
        system.debug('setAccountId: ' + setAccountId);

        // Busca de setorizações por cliente
        for (Setorizacao__c setorizacao : [SELECT Id, CodigoMesa__c, Categoria__c, Regiao__c FROM Setorizacao__c WHERE Conta__c IN: setAccountId AND Categoria__c != null AND Regiao__c != null]) {
            if (setorizacao.CodigoMesa__c != null) {
                setKeysectorization.add(setorizacao.CodigoMesa__c);
                setKeysectorization.add(setorizacao.CodigoMesa__c + setorizacao.Regiao__c);
            }
            setKeysectorization.add(setorizacao.Regiao__c);
        }
        system.debug('Chaves setorização: ' + setKeysectorization);

        system.debug('mapRecTypeToCategories: ' + mapRecTypeToCategories);
        // BUSCA DE PRA APROVADORES
        for (ResponsabilidadeAprovacao__c resp : [SELECT Id, UsuarioAprovador__c, RecordType.DeveloperName, CodigoMesa__c, Categorias__c, Regiao__c FROM ResponsabilidadeAprovacao__c WHERE RecordType.DeveloperName IN: setApprovalRecTypeName]) {
            if (resp.CodigoMesa__c == null && resp.Categorias__c == null && resp.Regiao__c == null) {
                system.debug('RESPONSAVEL OBRIGATÓRIO DE APROVAÇÃO');
                for (String processo : mapApprovalProcessToCategories.keySet()) {
                    for (String categoria : mapApprovalProcessToCategories.get(processo)) {
                        system.debug('Caiu no IF: ' + resp.RecordType.DeveloperName + categoria);
                        system.debug(setProcessCategories.contains(resp.RecordType.DeveloperName + categoria));
                        if (setProcessCategories.contains(resp.RecordType.DeveloperName + categoria)) {
                            String mapKey = (isOrder ? 'Pedido_' : 'Oportunidade_') + resp.RecordType.DeveloperName + categoria;
                            if (!mapApprovalProcessToSetUser.containsKey(mapKey)) {
                                mapApprovalProcessToSetUser.put(mapKey, new Set<Id>{resp.UsuarioAprovador__c});
                            } else {
                                mapApprovalProcessToSetUser.get(mapKey).add(resp.UsuarioAprovador__c);
                            }
                        }
                    }
                }
            } else if (resp.Categorias__c != null) {
                system.debug(resp.UsuarioAprovador__c);
                system.debug(resp.CodigoMesa__c);
                system.debug(resp.Regiao__c);
                String key = (resp.CodigoMesa__c != null ? resp.CodigoMesa__c : '');
                key += (resp.Regiao__c != null ? resp.Regiao__c : '');
                system.debug(key);
                List<String> listCatSplit = resp.Categorias__c.split(';');
                for (String splittedCat : listCatSplit) {
                    system.debug('Caiu no ELSE IF cat: ' + resp.RecordType.DeveloperName + splittedCat);
                    system.debug(setProcessCategories.contains(resp.RecordType.DeveloperName + splittedCat));
                    if (setProcessCategories.contains(resp.RecordType.DeveloperName + splittedCat) && resp.CodigoMesa__c == null && resp.Regiao__c == null) {
                        String mapKey = (isOrder ? 'Pedido_' : 'Oportunidade_') + resp.RecordType.DeveloperName + splittedCat;
                        if (!mapApprovalProcessToSetUser.containsKey(mapKey)) {
                            mapApprovalProcessToSetUser.put(mapKey, new Set<Id>{resp.UsuarioAprovador__c});
                        } else {
                            mapApprovalProcessToSetUser.get(mapKey).add(resp.UsuarioAprovador__c);
                        }
                    } else if (setProcessCategories.contains(resp.RecordType.DeveloperName + splittedCat) && setKeysectorization.contains(key)) {
                        String mapKey = (isOrder ? 'Pedido_' : 'Oportunidade_') + resp.RecordType.DeveloperName + splittedCat;
                        if (!mapApprovalProcessToSetUser.containsKey(mapKey)) {
                            mapApprovalProcessToSetUser.put(mapKey, new Set<Id>{resp.UsuarioAprovador__c});
                        } else {
                            mapApprovalProcessToSetUser.get(mapKey).add(resp.UsuarioAprovador__c);
                        }
                    }
                }
            } else {
                system.debug(resp.UsuarioAprovador__c);
                system.debug(resp.CodigoMesa__c);
                system.debug(resp.Regiao__c);
                String key = (resp.CodigoMesa__c != null ? resp.CodigoMesa__c : '');
                key += (resp.Regiao__c != null ? resp.Regiao__c : '');
                system.debug(key);
                Boolean hasKey = key != '' ? true : false;
                system.debug(hasKey);
                for (String processo : mapApprovalProcessToCategories.keySet()) {
                    for (String categoria : mapApprovalProcessToCategories.get(processo)) {
                        system.debug('Caiu no ELSE: ' + resp.RecordType.DeveloperName + categoria);
                        system.debug(setProcessCategories.contains(resp.RecordType.DeveloperName + categoria));
                        if (setProcessCategories.contains(resp.RecordType.DeveloperName + categoria) && setKeysectorization.contains(key)) {
                            String mapKey = (isOrder ? 'Pedido_' : 'Oportunidade_') + resp.RecordType.DeveloperName + categoria;
                            system.debug(mapKey);
                            if (hasKey) {
                                if (setKeysectorization.contains(key)) {
                                    if (!mapApprovalProcessToSetUser.containsKey(mapKey)) {
                                        mapApprovalProcessToSetUser.put(mapKey, new Set<Id>{resp.UsuarioAprovador__c});
                                    } else {
                                        mapApprovalProcessToSetUser.get(mapKey).add(resp.UsuarioAprovador__c);
                                    }
                                }
                            } else {
                                if (!mapApprovalProcessToSetUser.containsKey(mapKey)) {
                                    mapApprovalProcessToSetUser.put(mapKey, new Set<Id>{resp.UsuarioAprovador__c});
                                } else {
                                    mapApprovalProcessToSetUser.get(mapKey).add(resp.UsuarioAprovador__c);
                                }
                            }
                        }
                    }
                }
            }
        }

        system.debug('Mapa de processo de aprovação para lista de usuários: ' + mapApprovalProcessToSetUser);

        for (String processo : mapApprovalProcessToSetUser.keySet()) {
            system.debug('Processo de aprovação: ' + processo);
            for (Id userId : mapApprovalProcessToSetUser.get(processo)) {
                system.debug('Usuário: ' + userId);
            }
        }

        return mapApprovalProcessToSetUser;
    }
}