Git Tests/force-app/main/default/default/objects/ResponsabilidadeAprovacao__c/ResponsabilidadeAprovacao__c.object-meta.xml
<CustomObject>
    <label>Responsabilidade de aprovação</label>
    <nameField>
        <displayFormat>RA-{00000}</displayFormat>
        <label>Nome de Responsabilidade de aprovação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responsabilidades de aprovação</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ResponsabilidadeAprovacao__c/fields/UsuarioAprovador__c.field-meta.xml
<CustomField>
    <fullName>UsuarioAprovador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário aprovador</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ResponsabilidadeAprovacao</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/QueueRevalidateUserApprovalAssociations.cls
public without sharing class QueueRevalidateUserApprovalAssociations implements Queueable {
    public void execute(QueueableContext context) {
        Set<Id> responsibleUsersIds = new Set<Id>();
        
        List<ResponsabilidadeAprovacao__c> responsibleApprovalsList = [
            SELECT 
                Id,
                UsuarioAprovador__c
            FROM ResponsabilidadeAprovacao__c
        ];

        for (ResponsabilidadeAprovacao__c currResponsibleUser : responsibleApprovalsList) {
            responsibleUsersIds.add(currResponsibleUser.UsuarioAprovador__c);
        }
        
        ResponsabilidadeAprovacaoHelper.revalidateAssociationsAsync(responsibleUsersIds);        
    }
}