Git Tests/force-app/main/default/default/objects/ResponsabilidadeAprovacao__c/ResponsabilidadeAprovacao__c.object-meta.xml
<CustomObject>
    <label>Responsabilidade de aprovação</label>
    <nameField>
        <displayFormat>RA-{00000}</displayFormat>
        <label>Nome de Responsabilidade de aprovação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responsabilidades de aprovação</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ResponsabilidadeAprovacao__c/fields/Categorias__c.field-meta.xml
<CustomField>
    <fullName>Categorias__c</fullName>
    <label>Categorias</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>AMBOS</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>DIABETES</label>
            </value>
            <value>
                <fullName>G</fullName>
                <label>GENÉRICO</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>MATERIAIS</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>NUTRIÇÃO</label>
            </value>
            <value>
                <fullName>Q</fullName>
                <label>ODONTOLOGIA</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>MEDCTECH</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>SPECIALTY</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <label>EQUIPAMENTO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/ResponsabilidadeAprovacao__c/fields/CodigoMesa__c.field-meta.xml
<CustomField>
    <fullName>CodigoMesa__c</fullName>
    <externalId>true</externalId>
    <label>Código da mesa</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ResponsabilidadeAprovacao__c/fields/Regiao__c.field-meta.xml
<CustomField>
    <fullName>Regiao__c</fullName>
    <externalId>true</externalId>
    <label>Região</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ResponsabilidadeAprovacao__c/fields/UsuarioAprovador__c.field-meta.xml
<CustomField>
    <fullName>UsuarioAprovador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário aprovador</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ResponsabilidadeAprovacao</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Territory2/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <externalId>true</externalId>
    <label>Categoria</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Territory2/fields/CodigoMesa__c.field-meta.xml
<CustomField>
    <fullName>CodigoMesa__c</fullName>
    <externalId>true</externalId>
    <label>Código da mesa</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Territory2/fields/Regiao__c.field-meta.xml
<CustomField>
    <fullName>Regiao__c</fullName>
    <externalId>true</externalId>
    <label>Região</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/ResponsabilidadeAprovacaoHelper.cls
public without sharing class ResponsabilidadeAprovacaoHelper {

    public static final String ROLE_IN_TERRITORY = 'Responsabilidade Aprovação';
    
    public static void createUserTerritoryAssiciation(Map<Id, ResponsabilidadeAprovacao__c> newMap) {
        Set<Id> responsibleUsersIds = new Set<Id>();
        
        for (ResponsabilidadeAprovacao__c currResponsibleUser : newMap.values()) {
            responsibleUsersIds.add(currResponsibleUser.UsuarioAprovador__c);
        }
        
        revalidateAssociationsAsync(responsibleUsersIds);
    }

    public static void deleteUserTerritoryAssiciation(List<ResponsabilidadeAprovacao__c> oldRecords) {
        Set<Id> responsibleUsersIds = new Set<Id>();
        
        for (ResponsabilidadeAprovacao__c currResponsibleUser : oldRecords) {
            responsibleUsersIds.add(currResponsibleUser.UsuarioAprovador__c);
        }
        
        revalidateAssociationsAsync(responsibleUsersIds);
    }

    @future()
    public static void revalidateAssociationsAsync(Set<Id> responsibleUsersIds) {
        List<ResponsabilidadeAprovacao__c> newRecords = [
            SELECT 
                UsuarioAprovador__c,
                CodigoMesa__c,
                Regiao__c,
                Categorias__c
            FROM ResponsabilidadeAprovacao__c
            WHERE UsuarioAprovador__c IN: responsibleUsersIds
        ];

        // Reset user territory associations (only for approvers)
        delete [
            SELECT Id
            FROM UserTerritory2Association
            WHERE UserId IN: responsibleUsersIds
            AND RoleInTerritory2 =: ROLE_IN_TERRITORY
        ];
        
        Map<String, Territory2> mapAllTerritories =
            ActingTableTerritoryManagement.getThirdLayerTerritoriesDeveloperNameMap();

        system.debug(mapAllTerritories);
        Map<Id, Set<String>> mapUserAssociations = new Map<Id, Set<String>>();

        List<UserTerritory2Association> responsibleUsersAssociations =
            ActingTableTerritoryManagement.getAllUsersAssociationsByUserIds(responsibleUsersIds);

        for (UserTerritory2Association currAssociation : responsibleUsersAssociations) {
            if (!mapUserAssociations.containsKey(currAssociation.UserId)) {
                mapUserAssociations.put(
                    currAssociation.UserId,
                    new Set<String>()
                );
            }
            
            mapUserAssociations
                .get(currAssociation.UserId)
                .add(currAssociation.Territory2.DeveloperName);
        }

        List<UserTerritory2Association> newAssociations = new List<UserTerritory2Association>();

        for (ResponsabilidadeAprovacao__c currResponsibleUser : newRecords) {
            Id userId = currResponsibleUser.UsuarioAprovador__c;
            String actingTable = currResponsibleUser.CodigoMesa__c;
            String region = currResponsibleUser.Regiao__c;
            List<String> categories = 
                currResponsibleUser.Categorias__c != null
                ? currResponsibleUser.Categorias__c.split(';')
                : null;
            
            for (Territory2 currTerritory : mapAllTerritories.values()) {

                if (!mapUserAssociations.containsKey(userId)) {
                    mapUserAssociations.put(
                        userId,
                        new Set<String>()
                    );
                }

                if (mapUserAssociations.get(userId).contains(currTerritory.DeveloperName)) {
                    continue;
                }

                if (actingTable == null && categories == null && region == null) {
                    UserTerritory2Association userAssociation = 
                        ActingTableTerritoryManagement.createUserAssociationForActingTableTerritory(
                            currTerritory,
                            userId,
                            ROLE_IN_TERRITORY
                        );
                    if (userId != null) {
                        newAssociations.add(userAssociation);
                    }
                    
                    mapUserAssociations
                        .get(userId)
                        .add(currTerritory.DeveloperName);

                } else if (actingTable != null && categories != null && region != null) {
                    if (
                        currTerritory.CodigoMesa__c == actingTable &&
                        categories.contains(currTerritory.Categoria__c) &&
                        currTerritory.Regiao__c == region
                    ) {
                        UserTerritory2Association userAssociation = 
                            ActingTableTerritoryManagement.createUserAssociationForActingTableTerritory(
                                currTerritory,
                                userId,
                                ROLE_IN_TERRITORY
                            );
                        if (userId != null) {
                            newAssociations.add(userAssociation);
                        }
                        
                        mapUserAssociations
                            .get(userId)
                            .add(currTerritory.DeveloperName);
                    }
                } else if (actingTable != null && categories != null && region == null) {
                    if (
                        currTerritory.CodigoMesa__c == actingTable &&
                        categories.contains(currTerritory.Categoria__c)
                    ) {
                        UserTerritory2Association userAssociation = 
                            ActingTableTerritoryManagement.createUserAssociationForActingTableTerritory(
                                currTerritory,
                                userId,
                                ROLE_IN_TERRITORY
                            );
                        if (userId != null) {
                            newAssociations.add(userAssociation);
                        }
                        
                        mapUserAssociations
                            .get(userId)
                            .add(currTerritory.DeveloperName);
                    }
                } else if (actingTable != null && categories == null && region != null) {
                    if (
                        currTerritory.CodigoMesa__c == actingTable &&
                        currTerritory.Regiao__c == region
                    ) {
                        UserTerritory2Association userAssociation = 
                            ActingTableTerritoryManagement.createUserAssociationForActingTableTerritory(
                                currTerritory,
                                userId,
                                ROLE_IN_TERRITORY
                            );
                        if (userId != null) {
                            newAssociations.add(userAssociation);
                        }
                        
                        mapUserAssociations
                            .get(userId)
                            .add(currTerritory.DeveloperName);
                    }
                } else if (actingTable == null && categories != null && region != null) {
                    if (
                        categories.contains(currTerritory.Categoria__c) &&
                        currTerritory.Regiao__c == region
                    ) {
                        UserTerritory2Association userAssociation = 
                            ActingTableTerritoryManagement.createUserAssociationForActingTableTerritory(
                                currTerritory,
                                userId,
                                ROLE_IN_TERRITORY
                            );
                        if (userId != null) {
                            newAssociations.add(userAssociation);
                        }
                        
                        mapUserAssociations
                            .get(userId)
                            .add(currTerritory.DeveloperName);
                    }
                } else if (actingTable != null && currTerritory.CodigoMesa__c == actingTable) {
                    UserTerritory2Association userAssociation = 
                            ActingTableTerritoryManagement.createUserAssociationForActingTableTerritory(
                                currTerritory,
                                userId,
                                ROLE_IN_TERRITORY
                            );
                        if (userId != null) {
                            newAssociations.add(userAssociation);
                        }
                        
                        mapUserAssociations
                            .get(userId)
                            .add(currTerritory.DeveloperName);
                } else if (categories != null && categories.contains(currTerritory.Categoria__c)) {
                    UserTerritory2Association userAssociation = 
                            ActingTableTerritoryManagement.createUserAssociationForActingTableTerritory(
                                currTerritory,
                                userId,
                                ROLE_IN_TERRITORY
                            );
                        if (userId != null) {
                            newAssociations.add(userAssociation);
                        }
                        
                        mapUserAssociations
                            .get(userId)
                            .add(currTerritory.DeveloperName);
                } else if (region != null && currTerritory.Regiao__c == region) {
                    UserTerritory2Association userAssociation = 
                            ActingTableTerritoryManagement.createUserAssociationForActingTableTerritory(
                                currTerritory,
                                userId,
                                ROLE_IN_TERRITORY
                            );
                        if (userId != null) {
                            newAssociations.add(userAssociation);
                        }
                        
                        mapUserAssociations
                            .get(userId)
                            .add(currTerritory.DeveloperName);
                }
            }
        }

        system.debug(newAssociations);
        if (!newAssociations.isEmpty()) {
            insert newAssociations;
        }
    }
}