Git Tests/force-app/main/default/default/objects/Timeline__c/Timeline__c.object-meta.xml
<CustomObject>
    <label>Timeline</label>
    <nameField>
        <label>Timeline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Timelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Timeline__c/fields/Elapsed_days__c.field-meta.xml
<CustomField>
    <fullName>Elapsed_days__c</fullName>
    <label>Elapsed days</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Timeline__c/fields/Elapsed_hours__c.field-meta.xml
<CustomField>
    <fullName>Elapsed_hours__c</fullName>
    <label>Elapsed hours</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Timeline__c/fields/Elapsed_milisenconds__c.field-meta.xml
<CustomField>
    <fullName>Elapsed_milisenconds__c</fullName>
    <label>Elapsed milisenconds</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Timeline__c/fields/Elapsed_minutes__c.field-meta.xml
<CustomField>
    <fullName>Elapsed_minutes__c</fullName>
    <label>Elapsed minutes</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Timeline__c/fields/Elapsed_seconds__c.field-meta.xml
<CustomField>
    <fullName>Elapsed_seconds__c</fullName>
    <label>Elapsed seconds</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Timeline__c/fields/Elapsed_years__c.field-meta.xml
<CustomField>
    <fullName>Elapsed_years__c</fullName>
    <label>Elapsed years</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Timeline__c/fields/End_date__c.field-meta.xml
<CustomField>
    <fullName>End_date__c</fullName>
    <label>End date</label>
    <type>DateTime</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/Timeline.cls
public with sharing class Timeline {
    
    @InvocableMethod(label='Calculate elapsed time' description='Calculate eplased time when closing a timeline' category='Timeline__c')
    public static List<Timeline__c> calculateElapsedTime(List<Timeline__c> timelines) {

        BusinessDays businessDays = BusinessDays.getInstance();
        for (Timeline__c timeline : timelines) {
            
            timeline.End_date__c = System.now();

            Long eplasedDate = BusinessHours.diff(businessDays.bHours.Id, timeline.CreatedDate, timeline.End_date__c);
            Long milliseconds = eplasedDate;
            Long seconds = milliseconds / 1000;
            Long minutes = seconds / 60;
            Long hours = minutes / 60;
            Long days = hours / 24;
            Long years = days / 365;
 
            timeline.Elapsed_milisenconds__c = milliseconds;
            timeline.Elapsed_minutes__c = minutes;
            timeline.Elapsed_seconds__c = seconds;   
            timeline.Elapsed_hours__c = hours;
            timeline.Elapsed_days__c = days;
            timeline.Elapsed_years__c = years;
            
        }

        return timelines;
    }
}