Git Tests/force-app/main/default/default/objects/Timeline__c/Timeline__c.object-meta.xml
<CustomObject>
    <label>Timeline</label>
    <nameField>
        <label>Timeline Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Timelines</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Timeline__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Timelines</relationshipLabel>
    <relationshipName>Timelines</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Timeline__c/fields/Elapsed_milisenconds__c.field-meta.xml
<CustomField>
    <fullName>Elapsed_milisenconds__c</fullName>
    <label>Elapsed milisenconds</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/TimelineTest.cls
@isTest
public class TimelineTest {
        
    @testSetup
    public static void setup() {
        Account acc = TestUtility.createAccPJ();
        insert acc;
        
        Contact ctt = TestUtility.createContact(acc.Id);
        insert ctt;
        
        Case c = TestUtility.createCase(acc, ctt);
        insert c;          
    }
    
    @isTest
    public static void createCase() {
                
        Case c = [SELECT Id FROM Case];
        
        Timeline__c tm = new Timeline__c(
            Name = 'Test',
			Case__c = c.Id
		);
        insert tm;
        
        tm = [SELECT Id, CreatedDate FROM Timeline__c ORDER BY CreatedDate DESC LIMIT 1];
            
        List<Timeline__c> timelines = Timeline.calculateElapsedTime(new List<Timeline__c> { tm });
        
        System.assertNotEquals(null, timelines[0].Elapsed_milisenconds__c);
    }

}