Git Tests/force-app/main/default/default/objects/Opportunity/fields/CanalEntrada__c.field-meta.xml
<CustomField>
    <fullName>CanalEntrada__c</fullName>
    <label>Canal de entrada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ACSC - Associação Congregação de Santa Catarina</fullName>
            </value>
            <value>
                <fullName>Apoio</fullName>
            </value>
            <value>
                <fullName>Ariba/Amil</fullName>
            </value>
            <value>
                <fullName>Bionexo</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>CONTRATO</fullName>
            </value>
            <value>
                <fullName>E-mail</fullName>
            </value>
            <value>
                <fullName>E-MAIL MARKETING</fullName>
            </value>
            <value>
                <fullName>GERENCIA</fullName>
                <label>GERÊNCIA</label>
            </value>
            <value>
                <fullName>GT Plan</fullName>
            </value>
            <value>
                <fullName>Humma</fullName>
            </value>
            <value>
                <fullName>INPART</fullName>
            </value>
            <value>
                <fullName>Max Cotações</fullName>
            </value>
            <value>
                <fullName>Portal Sintese</fullName>
            </value>
            <value>
                <fullName>Portal GTPLAN</fullName>
            </value>
            <value>
                <fullName>Medical VM</fullName>
            </value>
            <value>
                <fullName>MICROSOFT TEAMS</fullName>
            </value>
            <value>
                <fullName>Movi Tech</fullName>
            </value>
            <value>
                <fullName>MVM RS</fullName>
            </value>
            <value>
                <fullName>NEOGRID</fullName>
            </value>
            <value>
                <fullName>Nimbi</fullName>
            </value>
            <value>
                <fullName>PANFLETO</fullName>
            </value>
            <value>
                <fullName>Paradigma</fullName>
            </value>
            <value>
                <fullName>Plani Max</fullName>
            </value>
            <value>
                <fullName>PORTAL FAEPA</fullName>
            </value>
            <value>
                <fullName>Portal HR</fullName>
            </value>
            <value>
                <fullName>PORTAL MULTICENTRAIS</fullName>
            </value>
            <value>
                <fullName>PORTAL MV SISTEMA</fullName>
            </value>
            <value>
                <fullName>PORTAL SAO MARTINHO</fullName>
            </value>
            <value>
                <fullName>PORTAL SGHCOT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/DataVencimento__c.field-meta.xml
<CustomField>
    <fullName>DataVencimento__c</fullName>
    <label>Data de Vencimento</label>
    <type>DateTime</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/IdPortal__c.field-meta.xml
<CustomField>
    <fullName>IdPortal__c</fullName>
    <externalId>true</externalId>
    <label>Id Portal</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/Idportalcotacoes__c.field-meta.xml
<CustomField>
    <fullName>Idportalcotacoes__c</fullName>
    <externalId>true</externalId>
    <label>Id do portal de cotações</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <inlineHelpText>Vendedor / Vendedor Externo</inlineHelpText>
    <label>Representante VDE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/VendedorSuporte__c.field-meta.xml
<CustomField>
    <fullName>VendedorSuporte__c</fullName>
    <inlineHelpText>Vendedor Interno / Vendedor Suporte</inlineHelpText>
    <label>Representante VDI/VDS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/IdPortal__c.field-meta.xml
<CustomField>
    <fullName>IdPortal__c</fullName>
    <description>Id do item no Portal de Cotações.</description>
    <externalId>true</externalId>
    <label>Id do Portal</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ProdutoOrcamento</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CanalEntrada__c.field-meta.xml
<CustomField>
    <fullName>CanalEntrada__c</fullName>
    <label>Canal de entrada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ACSC - Associação Congregação de Santa Catarina</fullName>
            </value>
            <value>
                <fullName>Apoio</fullName>
            </value>
            <value>
                <fullName>Ariba/Amil</fullName>
            </value>
            <value>
                <fullName>Bionexo</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>CONTRATO</fullName>
            </value>
            <value>
                <fullName>E-mail</fullName>
            </value>
            <value>
                <fullName>E-MAIL MARKETING</fullName>
            </value>
            <value>
                <fullName>GERENCIA</fullName>
                <label>GERÊNCIA</label>
            </value>
            <value>
                <fullName>GTPLAN</fullName>
            </value>
            <value>
                <fullName>Humma</fullName>
            </value>
            <value>
                <fullName>INPART</fullName>
            </value>
            <value>
                <fullName>Max Cotações</fullName>
            </value>
            <value>
                <fullName>Medical VM</fullName>
            </value>
            <value>
                <fullName>MICROSOFT TEAMS</fullName>
            </value>
            <value>
                <fullName>Movi Tech</fullName>
            </value>
            <value>
                <fullName>MVM RS</fullName>
            </value>
            <value>
                <fullName>NEOGRID</fullName>
            </value>
            <value>
                <fullName>Nimbi</fullName>
            </value>
            <value>
                <fullName>PANFLETO</fullName>
            </value>
            <value>
                <fullName>Paradigma</fullName>
            </value>
            <value>
                <fullName>Plani Max</fullName>
            </value>
            <value>
                <fullName>PORTAL FAEPA</fullName>
            </value>
            <value>
                <fullName>Portal HR</fullName>
            </value>
            <value>
                <fullName>PORTAL MULTICENTRAIS</fullName>
            </value>
            <value>
                <fullName>PORTAL MV SISTEMA</fullName>
            </value>
            <value>
                <fullName>PORTAL SAO MARTINHO</fullName>
            </value>
            <value>
                <fullName>PORTAL SGHCOT</fullName>
            </value>
            <value>
                <fullName>PORTAL SINCONECTA</fullName>
            </value>
            <value>
                <fullName>PORTAL UNIFENAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/Idportalcotacoes__c.field-meta.xml
<CustomField>
    <fullName>Idportalcotacoes__c</fullName>
    <externalId>true</externalId>
    <label>Id do portal de cotações</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <description>
        Objeto recebido na integração do portal de cotações (class: IntegrationPortalQuoteIN) e
        utilizado para armazenar as requisições de produtos efetuada pelos clientes,
        assim como a resposta efetuada pelos vendedores.
        Sua estrutura a nível de negócio existe de duas formas:
        1. a nível de item, sendo o item entendido como as informações advindas da integração com a requisição do cliente.
        2. a nível de resposta, sendo a resposta entendida como as informações enviadas do vendedor para o cliente como resposta.
        Esse objeto pode ser visualizado a nível de usuário nas telas de orçamento do tipo portal (Opportunity > RecordType > OrcamentoPortal),
        que é o mestre do relacionamento mestre-detalhe contido nesse objeto.
        O item é enviado ao portal como resposta na integração do portal de cotação (class: IntegrationPortalQuoteOUT).
        E também é enviado quando é efetuado vínculo de produto (class: IntegrationPortalVinculoOUT)
    </description>
    <label>Item da Cotação</label>
    <nameField>
        <label>Nome do Item da Cotação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens da Cotação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <description>Campo usado para itentificar a categoria do vendedor responsável (advém de setorizacao__c)</description>
    <label>Categoria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <description>Cnpj do centro de distribuição vinculado</description>
    <label>CNPJ do CD</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/IdPortal__c.field-meta.xml
<CustomField>
    <fullName>IdPortal__c</fullName>
    <description>Id do item no Portal de Cotações (hash), não vem da integradora, é criado para cada item dentro do portal.</description>
    <externalId>true</externalId>
    <label>Id do Portal</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/OpportunityLineItem__c.field-meta.xml
<CustomField>
    <fullName>OpportunityLineItem__c</fullName>
    <description>
        Quando existe oferta para o QuoteItem__c em questão é criado um OpportunityLineItem com as informações do QuoteItem__c
        Esse item que foi criado fica relacionado por meio desse campo.
    </description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto de oportunidade</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Items da Cotação</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <description>
        Vendedor responsável por dar a resposta, advem da setorização, relacionado a VendedorSuporte__c
        Também chamado de VDS ou VDI
    </description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ItensOrcamentosPortal</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/VendedorRespondeu__c.field-meta.xml
<CustomField>
    <fullName>VendedorRespondeu__c</fullName>
    <description>
        Em alguns casos o vendedor que responde a cotação não é o responsável primário por dar a resposta.
        Esse campo armazena o usuário que efetuou a resposta do item por último.
    </description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor que respondeu</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ItemOrcamentoRespondido</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/Setorizacao__c.object-meta.xml
<CustomObject>
    <label>Setorização</label>
    <nameField>
        <displayFormat>SET-{000000}</displayFormat>
        <label>Número da setorização</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setorizações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>BU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>G</fullName>
                <label>GENÉRICO</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>MATERIAIS</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>NUTRIÇÃO</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Medctech</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>SPECIALTY</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>AMBOS</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>DIABETES</label>
            </value>
            <value>
                <fullName>Q</fullName>
                <label>ODONTOLOGIA</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <label>EQUIPAMENTO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome do cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Setorização</relationshipLabel>
    <relationshipName>Setorizacao</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VDE</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Setorizacao</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/VendedorSuporte__c.field-meta.xml
<CustomField>
    <fullName>VendedorSuporte__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VDI</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SetorizacoesVendedor</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/SalesmanNotificationPortal.cls
public without sharing class SalesmanNotificationPortal {

    @future
    public static void orderInNotification(String orderId, String oppId, List<String> quoteItemIdList, Decimal totalAmount){
        try {
            
            Order newOrder = getOrder(orderId);
            Opportunity opp = getOpportunity(oppId);
            Map<Id, QuoteItem__c> qItemMap = getQuoteItemMap(oppId);
            Map<String, Set<String>> salesManBuMap = getSalesManBuMap(opp.AccountId);

            Map<String, List<QuoteItem__c>> qItemMapByIdPortal = new Map<String, List<QuoteItem__c>>();
            List<QuoteItem__c> qItemWonList = new List<QuoteItem__c>();
            Set<String> idsVDS = new Set<String>();


            for(QuoteItem__c qItem : qItemMap.values()){
                if(!qItemMapByIdPortal.containsKey(qItem.IdPortal__c)){
                    qItemMapByIdPortal.put(qItem.IdPortal__c, new List<QuoteItem__c>());
                }

                qItemMapByIdPortal.get(qItem.IdPortal__c).add(qItem);

                if(quoteItemIdList.contains(qItem.Id)){
                    qItemWonList.add(qItem);
                }
            }

            for(QuoteItem__c qItemWon : qItemWonList){

                List<QuoteItem__c> qItemRelatedList = qItemMapByIdPortal.get(qItemWon.IdPortal__c);
                Set<String> salesManBuSet = salesManBuMap.get(qItemWon.Vendedor__c);

                idsVDS.add(qItemWon.Vendedor__c);
                if(qItemWon.Vendedor__c != qItemWon.VendedorRespondeu__c && qItemWon.VendedorRespondeu__c != null){
                    idsVDS.add(qItemWon.VendedorRespondeu__c);
                    salesManBuSet.addAll(salesManBuMap.get(qItemWon.VendedorRespondeu__c));
                }


                for(QuoteItem__c qItemRelated : qItemRelatedList){
                    if(qItemWon.Id == qItemRelated.Id){
                        continue;
                    }

                    if(salesManBuSet != null && salesManBuSet.contains(qItemRelated.Categoria__c)){
                        idsVDS.add(qItemRelated.Vendedor__c);
                    }
                }
            }

            notifyUsers(newOrder, idsVDS, opp);
            sendEmailVDS(idsVDS, newOrder, opp, totalAmount);
        } catch (Exception ex) {
            ExceptionUtils.debug(ex);
        }
    }    

    public static void notifyUsers(Order order , Set<String> IdsVDS, Opportunity opp){

        Messaging.CustomNotification notification = new Messaging.CustomNotification();

        CustomNotificationType notificationType = [
            SELECT Id, DeveloperName
            FROM CustomNotificationType
            WHERE DeveloperName = 'NotificaoCasoEncerrado'
        ];
      
        notification.setTitle('Pedido ' + order.IdPortalCotacoes__c + ' Confirmado - '+opp.CanalEntrada__c);
        notification.setBody(opp.Account.Name +' confirmou um pedido: BIONEXO ID '+ order.IdPortalCotacoes__c +' - SF ID '+ order.Id);
        notification.setNotificationTypeId(notificationType.Id);
        notification.setTargetId(order.Id);
        notification.send(IdsVDS);
    }

    public static void sendEmailVDS(Set<String> IdsVDS, Order newOrder, Opportunity opp, Decimal totalAmount){

        try {

            List<Messaging.SingleEmailMessage> emailList  = new List<Messaging.SingleEmailMessage>();
            List<String> subjectValues = new List<String>{    
                opp.CanalEntrada__c,
                newOrder.IdPortalCotacoes__c,
                opp.Account.Name
            };
            String subjectPattern = 'Pedido confirmado: {0} - {1} - {2}';
            String emailSubject = String.format(subjectPattern, subjectValues);
            
            String emailHtmlBody = createEmailTemplateBody(newOrder, opp, totalAmount);

            for(String id : IdsVDS){
                Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
                
                email.setSenderDisplayName('Salesforce');
                email.setBccSender(false);
                email.setTargetObjectId(id);
                email.setSubject(emailSubject);
                email.setHtmlBody(emailHtmlBody);
                email.saveAsActivity = false;
                emailList.add(email);
            }
            Messaging.reserveSingleEmailCapacity(emailList.size()); 

            if(!Test.isRunningTest()) {
                Messaging.sendEmail(emailList, false);
            }
            
        }  catch (Exception e) {
            ExceptionUtils.debug(e);
        }
    }

    public static String createEmailTemplateBody(Order newOrder, Opportunity opp, Decimal totalAmount){
        
        List<String> values = new List<String>{
            newOrder.Idportalcotacoes__c,
            opp.DataVencimento__c.formatGMT('dd/MM/yy HH:mm'),
            String.valueOf(TotalAmount),
            opp.Account.Name,
            URL.getSalesforceBaseUrl().toExternalForm()+'/'+newOrder.Id
        };

        String template = (
            '<p>Foram confirmados itens da cotação <b>{0}</b></p>'+
            '<p>Com vencimento em {1} </p>'+
            '<p>Com  Valor Total R$ {2}</p>'+
            '<p>Cotada pela empresa {3}.</p>'+
            '<p><a href={4}>Link do Pedido</a></p>'
        );

        return String.format(template, values);
    }

    public static Map<String, Set<String>> getSalesManBuMap(String accountId){
        Map<String, Set<String>> salesManBuMap = new Map<String, Set<String>>();

        List<Setorizacao__c> setorList = [
            SELECT VendedorSuporte__c, Categoria__c
            FROM Setorizacao__c 
            WHERE conta__c = :accountId
            AND VendedorSuporte__c != null
        ];

        for(Setorizacao__c setor : setorList){
            if(!salesManBuMap.containsKey(setor.VendedorSuporte__c)){
                salesManBuMap.put(setor.VendedorSuporte__c, new Set<String>());
            }
            salesManBuMap.get(setor.VendedorSuporte__c).add(setor.Categoria__c);
        }

        return salesManBuMap;
    }

    public static Map<Id, QuoteItem__c> getQuoteItemMap(String oppId){
        if(oppId != null){

            return new Map<Id, QuoteItem__c>([
                SELECT Id, 
                Categoria__c, CNPJCD__c, 
                IdPortal__c,
                OpportunityLineItem__c, OpportunityLineItem__r.PriceBookEntryId, 
                OpportunityLineItem__r.CentroDistribuicao__c, OpportunityLineItem__r.Product2Id, 
                OpportunityLineItem__r.ValorPortal__c, OpportunityLineItem__r.FatorConversao__c,
                OpportunityLineItem__r.TipoConversao__c, OpportunityLineItem__r.UnitPrice,
                OpportunityLineItem__r.Quantity, OpportunityLineItem__r.QuantidadePortal__c,
                Status__c,
                Vendedor__c, VendedorRespondeu__c
                FROM QuoteItem__c
                WHERE OpportunityId__c = :oppId
            ]);
        }
        else{
            return new Map<Id, QuoteItem__c>();
        }
    }

    public static Order getOrder(String orderId){

        List<Order> orderList = [
            SELECT Id,
            AccountId,
            IdPortalCotacoes__c
            FROM Order
            WHERE Id = :orderId
            LIMIT 1
        ];

        return !orderList.isEmpty() ? orderList[0] : null;
    }

    public static Opportunity getOpportunity(String oppId){
        
        List<Opportunity> opportunityList = [
            SELECT Id,
            AccountId, Account.Name,
            CanalEntrada__c,
            DataVencimento__c
            FROM Opportunity
            WHERE Id = :oppId
            LIMIT 1
        ];

        return !opportunityList.isEmpty() ? opportunityList[0] : null;
    }
}