Git Tests/force-app/main/default/default/objects/Opportunity/fields/DataVencimento__c.field-meta.xml
<CustomField>
    <fullName>DataVencimento__c</fullName>
    <label>Data de Vencimento</label>
    <type>DateTime</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/recordTypes/OrcamentoPortal.recordType-meta.xml
<RecordType>
    <fullName>OrcamentoPortal</fullName>
    <active>true</active>
    <businessProcess>Portal de Cotações</businessProcess>
    <label>Orçamento do Portal</label>
    <!---->
    <!---->
</RecordType>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/Setorizacao__c.object-meta.xml
<CustomObject>
    <label>Setorização</label>
    <nameField>
        <displayFormat>SET-{000000}</displayFormat>
        <label>Número da setorização</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setorizações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/classes/BatchOpportunityStatusTest.cls
@isTest
public with sharing class BatchOpportunityStatusTest {

    @TestSetup
    static void makeData(){
        Id recordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('OrcamentoPortal').getRecordTypeId();

        Account acc = TestUtility.createAccPJ();
        insert acc;
        User us = TestUtility.createUser();
        insert us;
        Setorizacao__c setorizacao = TestUtility.createSetorizacaoWithValidData(acc, us);
        insert setorizacao;
        Opportunity opportunity    = TestUtility.createOpportunity(us);
        opportunity.StageName = 'Novo';
        opportunity.DataVencimento__c = Datetime.now().addDays(-1);
        opportunity.RecordTypeId = recordTypeId;
        insert opportunity;
        Opportunity opportunity2   = TestUtility.createOpportunityTwo(us);
        opportunity2.StageName = 'Respondida';
        opportunity2.DataVencimento__c = Datetime.now().addDays(-11);
        
        opportunity.RecordTypeId = recordTypeId;
        insert opportunity2; 
    }
    
    @isTest
    public static void BatchOpportunityStatus() {
        BatchOpportunityStatusSchedule batchSchedule = new BatchOpportunityStatusSchedule();
        Test.startTest();
        batchSchedule.execute(null);
        BatchOpportunityStatusSchedule.scheduleBatch();
        BatchOpportunityStatus batchStatus = new BatchOpportunityStatus();
        Database.executeBatch(batchStatus);
        Test.stopTest();
    }
}