Git Tests/force-app/main/default/default/objects/Opportunity/fields/DataVencimento__c.field-meta.xml
<CustomField>
    <fullName>DataVencimento__c</fullName>
    <label>Data de Vencimento</label>
    <type>DateTime</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/TabulacaoN1__c.field-meta.xml
<CustomField>
    <fullName>TabulacaoN1__c</fullName>
    <inlineHelpText>Este campo é um refinamento do valor do campo Status</inlineHelpText>
    <label>Tabulação N1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recusa</fullName>
            </value>
            <value>
                <fullName>Aceite</fullName>
            </value>
            <value>
                <fullName>Improdutiva</fullName>
            </value>
            <value>
                <fullName>Envio Automático</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/TabulacaoN2__c.field-meta.xml
<CustomField>
    <fullName>TabulacaoN2__c</fullName>
    <inlineHelpText>Este campo é o segundo refinamento do valor do campo Status</inlineHelpText>
    <label>Tabulação N2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>TabulacaoN1__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cotação Enviada TT</fullName>
            </value>
            <value>
                <fullName>Cotação Enviada Parcial</fullName>
            </value>
            <value>
                <fullName>Fora de Malha</fullName>
            </value>
            <value>
                <fullName>Falta de estoque</fullName>
            </value>
            <value>
                <fullName>Não temos o item no portifólio</fullName>
            </value>
            <value>
                <fullName>Não temos a apresentação solicitada</fullName>
            </value>
            <value>
                <fullName>Não temos a validade solicitada</fullName>
            </value>
            <value>
                <fullName>Não temos a quantidade solicitada</fullName>
            </value>
            <value>
                <fullName>Não trabalhamos</fullName>
            </value>
            <value>
                <fullName>Não conseguimos atender no prazo solicitado</fullName>
            </value>
            <value>
                <fullName>Não atinge o faturamento mínimo</fullName>
            </value>
            <value>
                <fullName>Área Restrita / Regionalização</fullName>
            </value>
            <value>
                <fullName>Bloqueio Financeiro</fullName>
            </value>
            <value>
                <fullName>Cotação Vencida</fullName>
            </value>
            <value>
                <fullName>BU Material</fullName>
            </value>
            <value>
                <fullName>BU Genérico</fullName>
            </value>
            <value>
                <fullName>BU Especialidade</fullName>
            </value>
            <value>
                <fullName>Envio Automático</fullName>
            </value>
            <value>
                <fullName>BLACK LIST</fullName>
                <isActive>false</isActive>
                <label>BLACK LIST</label>
            </value>
            <value>
                <fullName>NÃO É CLIENTE ALVO</fullName>
                <isActive>false</isActive>
                <label>NÃO É CLIENTE ALVO</label>
            </value>
            <value>
                <fullName>Outro Distribuidor</fullName>
                <isActive>false</isActive>
                <label>Outro Distribuidor</label>
            </value>
            <value>
                <fullName>PARCIAL</fullName>
                <isActive>false</isActive>
                <label>PARCIAL</label>
            </value>
            <value>
                <fullName>Preço melhor do concorrente</fullName>
                <isActive>false</isActive>
                <label>Preço melhor do concorrente</label>
            </value>
            <value>
                <fullName>TODOS OS ITENS - NÃO CONSEGUIMOS ATENDER NO PRAZO SOLICITADO</fullName>
                <isActive>false</isActive>
                <label>TODOS OS ITENS - NÃO CONSEGUIMOS ATENDER NO PRAZO SOLICITADO</label>
            </value>
            <value>
                <fullName>TODOS OS ITENS - NÃO TRABALHAMOS</fullName>
                <isActive>false</isActive>
                <label>TODOS OS ITENS - NÃO TRABALHAMOS</label>
            </value>
            <value>
                <fullName>TODOS OS ITENS FORA DE MALHA</fullName>
                <isActive>false</isActive>
                <label>TODOS OS ITENS FORA DE MALHA</label>
            </value>
            <value>
                <fullName>TODOS OS ITENS FORA DO PORTFOLIO</fullName>
                <isActive>false</isActive>
                <label>TODOS OS ITENS FORA DO PORTFOLIO</label>
            </value>
            <value>
                <fullName>TODOS OS ITENS SEM A APRESENTAÇÃO SOLICITADA</fullName>
                <isActive>false</isActive>
                <label>TODOS OS ITENS SEM A APRESENTAÇÃO SOLICITADA</label>
            </value>
            <value>
                <fullName>TODOS OS ITENS SEM A QUANTIDADE SOLICITADA</fullName>
                <isActive>false</isActive>
                <label>TODOS OS ITENS SEM A QUANTIDADE SOLICITADA</label>
            </value>
            <value>
                <fullName>TODOS OS ITENS SEM A VALIDADE SOLICITADA</fullName>
                <isActive>false</isActive>
                <label>TODOS OS ITENS SEM A VALIDADE SOLICITADA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/recordTypes/OrcamentoPortal.recordType-meta.xml
<RecordType>
    <fullName>OrcamentoPortal</fullName>
    <active>true</active>
    <businessProcess>Portal de Cotações</businessProcess>
    <label>Orçamento do Portal</label>
    <!---->
    <!---->
</RecordType>

Git Tests/force-app/main/default/default/classes/BatchOpportunityStatus.cls
global class BatchOpportunityStatus implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext BC) {
        Id recordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('OrcamentoPortal').getRecordTypeId();

        return Database.getQueryLocator([
            SELECT Id, StageName, DataVencimento__c, TabulacaoN1__c, TabulacaoN2__c
            FROM Opportunity WHERE DataVencimento__c <= :Datetime.now()
            AND (StageName = 'Novo' OR StageName = 'Respondida')
            AND RecordTypeId = :recordTypeId
        ]);
    }

    global void execute(Database.BatchableContext BC, List<SObject> scope ) {
        List<Opportunity> listOpp = (List<Opportunity>)scope;
        for(Opportunity opp : listOpp){

            if(opp.StageName == 'Novo' && opp.DataVencimento__c < Datetime.now()){
                opp.StageName = 'Não Respondida';
                opp.TabulacaoN1__c = 'Recusa';
                opp.TabulacaoN2__c = 'Cotação Vencida';
            }

            if(opp.StageName == 'Respondida' && opp.DataVencimento__c < Datetime.now().addDays(-10)){
                opp.StageName = 'Sem Retorno';
            }
        }

        update listOpp;
    }

    global void finish(Database.BatchableContext BC) {}

}