Git Tests/force-app/main/default/default/objects/Opportunity/fields/ExternalPortal__c.field-meta.xml
<CustomField>
    <fullName>ExternalPortal__c</fullName>
    <externalId>true</externalId>
    <label>ExternalPortal</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/MensagemErroIntegracaoPortalCotacoes__c.field-meta.xml
<CustomField>
    <fullName>MensagemErroIntegracaoPortalCotacoes__c</fullName>
    <label>Mensagem de erro Integração (Portal)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/NumeroOrcamento__c.field-meta.xml
<CustomField>
    <fullName>NumeroOrcamento__c</fullName>
    <displayFormat>OR-{00000000}</displayFormat>
    <label>Número do orçamento</label>
    <type>AutoNumber</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/StatusIntegracaoPortalCotacoes__c.field-meta.xml
<CustomField>
    <fullName>StatusIntegracaoPortalCotacoes__c</fullName>
    <label>Status de Integração (Portal)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não Integrado</fullName>
                <default>true</default>
                <label>Não Integrado</label>
            </value>
            <value>
                <fullName>Falha na Integração</fullName>
            </value>
            <value>
                <fullName>Integrado</fullName>
            </value>
            <value>
                <fullName>Recebendo dados</fullName>
            </value>
            <value>
                <fullName>Recebida</fullName>
            </value>
            <value>
                <fullName>Integrada</fullName>
                <isActive>false</isActive>
                <label>Integrada</label>
            </value>
            <value>
                <fullName>Não Integrada</fullName>
                <isActive>false</isActive>
                <label>Não Integrada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <description>
        Objeto recebido na integração do portal de cotações (class: IntegrationPortalQuoteIN) e
        utilizado para armazenar as requisições de produtos efetuada pelos clientes,
        assim como a resposta efetuada pelos vendedores.
        Sua estrutura a nível de negócio existe de duas formas:
        1. a nível de item, sendo o item entendido como as informações advindas da integração com a requisição do cliente.
        2. a nível de resposta, sendo a resposta entendida como as informações enviadas do vendedor para o cliente como resposta.
        Esse objeto pode ser visualizado a nível de usuário nas telas de orçamento do tipo portal (Opportunity > RecordType > OrcamentoPortal),
        que é o mestre do relacionamento mestre-detalhe contido nesse objeto.
        O item é enviado ao portal como resposta na integração do portal de cotação (class: IntegrationPortalQuoteOUT).
        E também é enviado quando é efetuado vínculo de produto (class: IntegrationPortalVinculoOUT)
    </description>
    <label>Item da Cotação</label>
    <nameField>
        <label>Nome do Item da Cotação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens da Cotação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <description>relacionamento mestre detalhe, orçamento, cotação, opportunidade referente ao item.</description>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Itens da Cotação</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Identificador de condição da resposta, (Responde a pergunta: Em que estapa está a resposta?)</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NÃO IDENTIFICADO</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>IDENTIFICADO</fullName>
            </value>
            <value>
                <fullName>QUALIFICADO</fullName>
            </value>
            <value>
                <fullName>Respondido</fullName>
            </value>
            <value>
                <fullName>Resgatado</fullName>
            </value>
            <value>
                <fullName>Aguardando Integração</fullName>
            </value>
            <value>
                <fullName>Falha na Integração</fullName>
            </value>
            <value>
                <fullName>Não Vinculado</fullName>
                <default>true</default>
                <label>Não Vinculado</label>
            </value>
            <value>
                <fullName>Vinculado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/StatusIntegrationResponse__c.field-meta.xml
<CustomField>
    <fullName>StatusIntegrationResponse__c</fullName>
    <description>status de integração do item com a integradora, recebido via integraçãoIN com o portal, na classe: IntegrationPortalResponseIN</description>
    <label>StatusIntegrationResponse</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não Respondido</fullName>
                <default>true</default>
                <label>Não Respondido</label>
            </value>
            <value>
                <fullName>Não Integrado</fullName>
            </value>
            <value>
                <fullName>Integrado</fullName>
            </value>
            <value>
                <fullName>Falha na Integração</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/classes/IntegrationPortalResponseIN.cls
/**
 * @description       : 
 * @author            : Raphael Soares
 * @author username   : raphael.holanda.ext@iconit.com.br
 * @company           : Icon IT Solutions
 * @last modified on  : 17-05-2022
 * @last modified by  : raphael.holanda.ext@iconit.com.br
**/
@RestResource(urlMapping='/integrationResponse/v1/*')
global without sharing class IntegrationPortalResponseIN {
    
    global static final List<String> FALSE_STATUS = new List<String>{'Não Integrado', 'Falha na Integração'};

    @HttpPost
    global static void saveResponse() {
        StandardResponse response = new StandardResponse();
        RestRequest req = RestContext.request;
        String requestBody = req.requestBody.toString();
        RestResponse res = RestContext.response;
        String responseBody;

        Opportunity opp;
        Opportunity oppToUpdate = new Opportunity();
        Map<String, QuoteItem__c> mapItemsToUpdate = new Map<String, QuoteItem__c>();
        
        try{
            
            RequestData reqData = validateRequestBody(requestBody);

            List<Opportunity> oppList = [
                SELECT Id, NumeroOrcamento__c,
                    (SELECT UserId FROM OpportunityTeamMembers)
                FROM Opportunity 
                WHERE ExternalPortal__c =: reqData.idPortalOrcamento
                LIMIT 1
            ];

            if(oppList.isEmpty()){
                throw new CustomException('O idPortalOrcamento:\''+reqData.idPortalOrcamento+'\' não foi encontrado no Salesforce');
            }
            opp = oppList[0];
            oppToUpdate.Id = opp.Id;
            oppToUpdate.MensagemErroIntegracaoPortalCotacoes__c = null;
            
            if(!reqData.success){
                oppToUpdate.StageName = 'Falha na integração';
                oppToUpdate.StatusIntegracaoPortalCotacoes__c = 'Falha na Integração';

                if(!String.isBlank(reqData.messages)){
                    oppToUpdate.MensagemErroIntegracaoPortalCotacoes__c = Datetime.now().format('dd/MM/yyyy\' \'HH:mm:ss') + ';' + reqData.messages;
                }
            }

            Map<Id, QuoteItem__c> quoteItemMap = new Map<Id, QuoteItem__c>([
                SELECT Id, Status__c, StatusIntegrationResponse__c
                FROM QuoteItem__c
                WHERE OpportunityId__c = :opp.Id
                FOR UPDATE
            ]);

            Boolean fail = false;

            for(ItemResult item: reqData.items){
                QuoteItem__c qitem = quoteItemMap.get(item.idSalesforce);
                if(item.success){

                    qItem.Status__c = 'Respondido';
                    qItem.StatusIntegrationResponse__c = 'Integrado';
                } else {
                    fail = true;
                    oppToUpdate.StageName = 'Falha na integração';
                    oppToUpdate.StatusIntegracaoPortalCotacoes__c = 'Falha na Integração';
                    qItem.StatusIntegrationResponse__c = 'Falha na Integração';
                    if(String.isEmpty(oppToUpdate.MensagemErroIntegracaoPortalCotacoes__c)){
                        oppToUpdate.MensagemErroIntegracaoPortalCotacoes__c = 'Falha na integração:';
                    }
                }
            }
            if(reqData.success && !fail && validateChangeStatus(quoteItemMap.values())){
                oppToUpdate.StageName = 'Respondida';
                oppToUpdate.StatusIntegracaoPortalCotacoes__c = 'Integrado';
            }

            update quoteItemMap.values();
            oppToUpdate.MensagemErroIntegracaoPortalCotacoes__c = StringUtils.cutByFieldLength(Opportunity.MensagemErroIntegracaoPortalCotacoes__c, oppToUpdate.MensagemErroIntegracaoPortalCotacoes__c);
            update oppToUpdate;

            if(!mapItemsToUpdate.isEmpty()){
                update mapItemsToUpdate.values();
            }

        } catch(Exception ex){
            response.addError(ExceptionUtils.debug(ex));
        }

        Boolean hasError = response.code != '200';
        res.statuscode = Integer.valueOf(response.code);
        res.headers.put('Content-Type', 'application/json;charset=UTF-8');
        responseBody = response.toJSON();
        res.responseBody = Blob.valueOf(responseBody);

        if(!String.isBlank(oppToUpdate.MensagemErroIntegracaoPortalCotacoes__c) && !opp.OpportunityTeamMembers.isEmpty()){

            Set<String> targetUserIds = new Set<String>();
            for(OpportunityTeamMember otm: opp.OpportunityTeamMembers){
                targetUserIds.add(otm.UserId);
            }
            
            sendNotification(targetUserIds, opp.Id, 'A cotação de número ' + opp.NumeroOrcamento__c + ' teve falha na integração, acesse-a para mais detalhes', oppToUpdate.MensagemErroIntegracaoPortalCotacoes__c);
        }
        
        IntegrationUtils.WSLog('IntegrationResponse', 'Inbound', requestBody, responseBody, hasError, '/integrationResponse/v1/*', response.code);
    }

    private static RequestData validateRequestBody(String requestBody){
        RequestData rData;
        // System.debug('requestBody:::' + requestBody);
        if(String.isBlank(requestBody)){
            throw new CustomException('Dados não enviados.');
        } else {
            rData = (RequestData)JSON.deserialize(requestBody, RequestData.class);
        }
        if(String.isBlank(rData.idPortalOrcamento)){
            throw new CustomException('O campo \'idPortalOrcamento\' é obrigatório!');
        }
        if(rData.items == null || rData.items.isEmpty()){
            throw new CustomException('É obrigatório conter ao menos um item na requsição');
        }
        return rData;
    }

    public static Boolean validateChangeStatus(List<QuoteItem__c> qitemList){
        Map<String, List<QuoteItem__c>> qitemByStatusInt = (Map<String, List<QuoteItem__c>>)SObjectUtils.mapObjectsByField(qitemList, 'StatusIntegrationResponse__c', true);
        for(String stat : FALSE_STATUS){
            if(qitemByStatusInt.get(stat) != null && qitemByStatusInt.get(stat).size() > 0){
                return false;
            }
        }
        return true;
    }

    public static void sendNotification(Set<String> targetUserIds, String targetId, String title, String body){
            
        Messaging.CustomNotification notification = new Messaging.CustomNotification();

        CustomNotificationType notificationType = [
            SELECT Id, DeveloperName
            FROM CustomNotificationType
            WHERE DeveloperName = 'NotificaoCasoEncerrado'
        ];
        
        notification.setTitle(title);
        notification.setBody('\n' + body.replaceAll(';', '\n'));
        notification.setNotificationTypeId(notificationType.Id);
        notification.setTargetId(targetId);
        try {
            notification.send(targetUserIds);
        }
        catch (Exception e) {
            ExceptionUtils.debug(e);
        }

    }

    public class RequestData {
        public Boolean success;
        public String messages;
        public String idPortalOrcamento;
        public List<ItemResult> items;
    }

    public class ItemResult {
        public Boolean success;
        public String idSalesforce;
        public String messages;
    }

    public static RequestData parse(String json){
        return (RequestData) System.JSON.deserialize(json, RequestData.class);
    }
}