Git Tests/force-app/main/default/default/objects/Opportunity/fields/ExternalPortal__c.field-meta.xml
<CustomField>
    <fullName>ExternalPortal__c</fullName>
    <externalId>true</externalId>
    <label>ExternalPortal</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/IdPortal__c.field-meta.xml
<CustomField>
    <fullName>IdPortal__c</fullName>
    <externalId>true</externalId>
    <label>Id Portal</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/MensagemErroIntegracaoPortalCotacoes__c.field-meta.xml
<CustomField>
    <fullName>MensagemErroIntegracaoPortalCotacoes__c</fullName>
    <label>Mensagem de erro Integração (Portal)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Chave Externa</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/IdPortal__c.field-meta.xml
<CustomField>
    <fullName>IdPortal__c</fullName>
    <description>Id do item no Portal de Cotações.</description>
    <externalId>true</externalId>
    <label>Id do Portal</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NÃO IDENTIFICADO</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>IDENTIFICADO</fullName>
            </value>
            <value>
                <fullName>QUALIFICADO</fullName>
            </value>
            <value>
                <fullName>Respondido</fullName>
            </value>
            <value>
                <fullName>Resgatado</fullName>
            </value>
            <value>
                <fullName>Aguardando Integração</fullName>
            </value>
            <value>
                <fullName>Falha na Integração</fullName>
            </value>
            <value>
                <fullName>Não Vinculado</fullName>
            </value>
            <value>
                <fullName>Vinculado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityTeamMember/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Centro de distribuição</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do produto</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/ProductCodeElfa__c.field-meta.xml
<CustomField>
    <fullName>ProductCodeElfa__c</fullName>
    <externalId>true</externalId>
    <label>Código do produto Elfa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <description>
        Objeto recebido na integração do portal de cotações (class: IntegrationPortalQuoteIN) e
        utilizado para armazenar as requisições de produtos efetuada pelos clientes,
        assim como a resposta efetuada pelos vendedores.
        Sua estrutura a nível de negócio existe de duas formas:
        1. a nível de item, sendo o item entendido como as informações advindas da integração com a requisição do cliente.
        2. a nível de resposta, sendo a resposta entendida como as informações enviadas do vendedor para o cliente como resposta.
        Esse objeto pode ser visualizado a nível de usuário nas telas de orçamento do tipo portal (Opportunity > RecordType > OrcamentoPortal),
        que é o mestre do relacionamento mestre-detalhe contido nesse objeto.
        O item é enviado ao portal como resposta na integração do portal de cotação (class: IntegrationPortalQuoteOUT).
        E também é enviado quando é efetuado vínculo de produto (class: IntegrationPortalVinculoOUT)
    </description>
    <label>Item da Cotação</label>
    <nameField>
        <label>Nome do Item da Cotação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens da Cotação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>OpportunityId__r.ExternalPortal__c + _ + IdPotal__c + _ + Vendedor__c + _ + Categoria__c</description>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Chave Externa</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/IdPortal__c.field-meta.xml
<CustomField>
    <fullName>IdPortal__c</fullName>
    <description>Id do item no Portal de Cotações (hash), não vem da integradora, é criado para cada item dentro do portal.</description>
    <externalId>true</externalId>
    <label>Id do Portal</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <description>relacionamento mestre detalhe, orçamento, cotação, opportunidade referente ao item.</description>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Itens da Cotação</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/OpportunityLineItem__c.field-meta.xml
<CustomField>
    <fullName>OpportunityLineItem__c</fullName>
    <description>
        Quando existe oferta para o QuoteItem__c em questão é criado um OpportunityLineItem com as informações do QuoteItem__c
        Esse item que foi criado fica relacionado por meio desse campo.
    </description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto de oportunidade</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Items da Cotação</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>produto vinculado a resposta.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Items da Cotação</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Identificador de condição da resposta, (Responde a pergunta: Em que estapa está a resposta?)</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NÃO IDENTIFICADO</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>IDENTIFICADO</fullName>
            </value>
            <value>
                <fullName>QUALIFICADO</fullName>
            </value>
            <value>
                <fullName>Respondido</fullName>
            </value>
            <value>
                <fullName>Resgatado</fullName>
            </value>
            <value>
                <fullName>Aguardando Integração</fullName>
            </value>
            <value>
                <fullName>Falha na Integração</fullName>
            </value>
            <value>
                <fullName>Não Vinculado</fullName>
                <default>true</default>
                <label>Não Vinculado</label>
            </value>
            <value>
                <fullName>Vinculado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/classes/IntegrationPortalResponseINTest.cls
@isTest 
private class IntegrationPortalResponseINTest {

	/*@isTest
	private static void saveResponseTest() {
		IntegrationPortalResponseIN.RequestData dataRequest = new IntegrationPortalResponseIN.RequestData();

		dataRequest.success				= true;
		dataRequest.messages			= null;
		dataRequest.idPortalOrcamento	= '625da2cbd2568958f9038025';

		dataRequest.items = new List<IntegrationPortalResponseIN.ItemResult>();
		
		IntegrationPortalResponseIN.ItemResult ItemResultObj = new IntegrationPortalResponseIN.ItemResult();
		
		ItemResultObj.idSalesforce		= '625da2cbd2568958f903802d';
		ItemResultObj.messages			= 'error mensagem A;error mensagem b; abafgviauefhgeaiufeugiuagfiuaef';
		ItemResultObj.success			= true;

		dataRequest.items.add(ItemResultObj);
		
		IntegrationPortalResponseIN.saveResponse();
	}*/
	
	@isTest
        public static void saveResponseTest(){                
            
			Product2 product = TestUtility.createProduct();
            product.ExternalId__c = 'PQITEST1074';
            //product.ProductCodeElfa__c = 'PQITEST1074';
            insert product;

			Opportunity opportunity = TestUtility.createOpportunity(new User(Id=UserInfo.getUserId()));
            opportunity.CloseDate = Date.today().addDays(-1);
            opportunity.StageName = 'Em digitação';
            opportunity.IdPortal__c = 'IDPORTAL';
			opportunity.ExternalPortal__c = '625da2cbd2568958f9038025';
			opportunity.MensagemErroIntegracaoPortalCotacoes__c = 'Teste';			
            PricebookEntry pricebookEntry   = [SELECT Id FROM PricebookEntry WHERE Product2Id =: product.Id][0];
            pricebookEntry.IsActive         = true;
            update pricebookEntry;
            OpportunityLineItem oppLineItem = TestUtility.createOpportunityLineItem(opportunity.Id, product.Id, pricebookEntry.Id);
            insert opportunity;

            QuoteItem__c quoteitem = TestUtility.createQuoteItem(opportunity);
            quoteitem.OpportunityLineItem__c = oppLineItem.Id;
            quoteitem.OpportunityId__c = opportunity.Id;
            quoteitem.Product__c = product.Id;
            quoteitem.idportal__C = 'IDPORTAL';
            quoteitem.Status__c = 'Aguardando Integração';
            insert quoteitem;

			OpportunityTeamMember teamMember = TestUtility.createOpportunityTeamMember(opportunity);
            //OpportunityTeamMember teamMember2 = TestUtility.createOpportunityTeamMember(opportunity2);
            insert teamMember;									

			List<Opportunity> listOpportunity = [SELECT Id, Name FROM Opportunity LIMIT 2];
			
			Test.startTest();
                
                RestRequest req = new RestRequest();
                RestResponse res = new RestResponse();
                RestContext.response = res;
                req.requestUri = 'https://test.salesforce.com/services/apexrest/integrationResponse/v1';
                req.httpMethod = 'POST';
                																
				req.requestBody = Blob.valueOf(
                    '{'+
					'	"success": true,'+
					'	"messages": "test",'+
					'	"idPortalOrcamento": "625da2cbd2568958f9038025",'+
					'	"items": ['+
					'		{'+
					'			"success": true,'+
					'			"idSalesforce": "' + quoteitem.Id + '",'+
					'			"messages": "error mensagem A;error mensagem b; abafgviauefhgeaiufeugiuagfiuaef"'+
					'		}'+
					'	]'+
					'}'
                );
                RestContext.request = req;
                
                IntegrationPortalResponseIN.saveResponse();                        
            Test.stopTest();
        }
		
		@isTest
        public static void saveResponseTestError(){                
            
			Product2 product = TestUtility.createProduct();
            product.ExternalId__c = 'PQITEST1074';
            //product.ProductCodeElfa__c = 'PQITEST1074';
            insert product;

			Opportunity opportunity = TestUtility.createOpportunity(new User(Id=UserInfo.getUserId()));
            opportunity.CloseDate = Date.today().addDays(-1);
            opportunity.StageName = 'Em digitação';
            opportunity.IdPortal__c = 'IDPORTAL';
			opportunity.ExternalPortal__c = '625da2cbd2568958f9038025';
            PricebookEntry pricebookEntry   = [SELECT Id FROM PricebookEntry WHERE Product2Id =: product.Id][0];
            pricebookEntry.IsActive         = true;
            update pricebookEntry;
            OpportunityLineItem oppLineItem = TestUtility.createOpportunityLineItem(opportunity.Id, product.Id, pricebookEntry.Id);
            insert opportunity;

			OpportunityTeamMember teamMember = TestUtility.createOpportunityTeamMember(opportunity);
            insert teamMember;

            QuoteItem__c quoteitem = TestUtility.createQuoteItem(opportunity);
            quoteitem.OpportunityLineItem__c = oppLineItem.Id;
            quoteitem.OpportunityId__c = opportunity.Id;
            quoteitem.Product__c = product.Id;
            quoteitem.idportal__C = 'IDPORTAL';
            quoteitem.Status__c = 'Aguardando Integração';
            insert quoteitem;
			
			List<Opportunity> listOpportunity = [SELECT Id, Name FROM Opportunity LIMIT 2];
			
			Test.startTest();
                
                RestRequest req = new RestRequest();
                RestResponse res = new RestResponse();
                RestContext.response = res;
                req.requestUri = 'https://test.salesforce.com/services/apexrest/integrationResponse/v1';
                req.httpMethod = 'POST';
                																
				req.requestBody = Blob.valueOf(
                    '{'+
					'	"success": false,'+
					'	"messages": "error mensagem A;error mensagem b; abafgviauefhgeaiufeugiuagfiuaef",'+
					'	"idPortalOrcamento": "625da2cbd2568958f9038025",'+
					'	"items": ['+
					'		{'+
					'			"success": false,'+
					'			"idSalesforce": "' + quoteitem.Id + '",'+
					'			"messages": "error mensagem A;error mensagem b; abafgviauefhgeaiufeugiuagfiuaef"'+
					'		}'+
					'	]'+
					'}'
                );
                RestContext.request = req;
                
                IntegrationPortalResponseIN.saveResponse();                        
            Test.stopTest();
        }	
}