Git Tests/force-app/main/default/default/objects/Opportunity/fields/IdPortal__c.field-meta.xml
<CustomField>
    <fullName>IdPortal__c</fullName>
    <externalId>true</externalId>
    <label>Id Portal</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/QuantidadeItens__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeItens__c</fullName>
    <inlineHelpText>Quantidade de itens no orçamento</inlineHelpText>
    <label>Quantidade de Itens</label>
    <summaryForeignKey>QuoteItem__c.OpportunityId__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/GanhoParcialTotal__c.field-meta.xml
<CustomField>
    <fullName>GanhoParcialTotal__c</fullName>
    <description>Como gestora do produto, desejo saber se o pedido foi ganho totalmente ou parcialmente, para que assim tenha mais informações para decisões/estratégias de negócio</description>
    <label>Ganho Parcial ou Total</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/QuantidadeItens__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeItens__c</fullName>
    <label>Quantidade de itens</label>
    <summaryForeignKey>OrderItem.OrderId</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/QuoteItem__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resposta do Orçamento</label>
    <referenceTo>QuoteItem__c</referenceTo>
    <relationshipLabel>Items Pedidos</relationshipLabel>
    <relationshipName>ProdutoPedidoGerado</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <description>
        Objeto recebido na integração do portal de cotações (class: IntegrationPortalQuoteIN) e
        utilizado para armazenar as requisições de produtos efetuada pelos clientes,
        assim como a resposta efetuada pelos vendedores.
        Sua estrutura a nível de negócio existe de duas formas:
        1. a nível de item, sendo o item entendido como as informações advindas da integração com a requisição do cliente.
        2. a nível de resposta, sendo a resposta entendida como as informações enviadas do vendedor para o cliente como resposta.
        Esse objeto pode ser visualizado a nível de usuário nas telas de orçamento do tipo portal (Opportunity > RecordType > OrcamentoPortal),
        que é o mestre do relacionamento mestre-detalhe contido nesse objeto.
        O item é enviado ao portal como resposta na integração do portal de cotação (class: IntegrationPortalQuoteOUT).
        E também é enviado quando é efetuado vínculo de produto (class: IntegrationPortalVinculoOUT)
    </description>
    <label>Item da Cotação</label>
    <nameField>
        <label>Nome do Item da Cotação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens da Cotação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/IdPortal__c.field-meta.xml
<CustomField>
    <fullName>IdPortal__c</fullName>
    <description>Id do item no Portal de Cotações (hash), não vem da integradora, é criado para cada item dentro do portal.</description>
    <externalId>true</externalId>
    <label>Id do Portal</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <description>relacionamento mestre detalhe, orçamento, cotação, opportunidade referente ao item.</description>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Itens da Cotação</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/OrderItem__c.field-meta.xml
<CustomField>
    <fullName>OrderItem__c</fullName>
    <description>
        Quando recebemos a confirmação do orçamento do portal é criado um pedido e seus respectivos itens
        com base nas informações que vem na integração (IntegrationPortalOrderIN) e do que havia no SF no QuoteItem__c
        Esse item do pedido (OrderItem) fica vinculado ao item da cotação por esse campo. 
    </description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto do pedido</label>
    <referenceTo>OrderItem</referenceTo>
    <relationshipLabel>Items da Cotação</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/OrderItemHelper.cls
public with sharing class OrderItemHelper {

    public static void updateTotalOrParcialWinField(Map<Id, OrderItem> newMapOrderItem, Map<Id, OrderItem> oldMap, boolean isInsertion) {
        try {
            
            Map<String, List<OrderItem>> newMapByOrder = (Map<String, List<OrderItem>>) SObjectUtils.mapObjectsByField(newMapOrderItem.values(), 'OrderId', true);
            List<Order> orderList = getOrderList(newMapByOrder.keySet());
    
            Map<String, List<Order>> orderMapByOpportunity = (Map<String, List<Order>>) SObjectUtils.mapObjectsByField(orderList, 'OpportunityId', true);
            Map<Id, Opportunity> opportunityMap = getMapOpportunity(orderMapByOpportunity.keySet());
    
            List<Order> ordersToUpdate = new List<Order>();
            for (Order order : orderList) {
                Opportunity opp = opportunityMap.get(order.OpportunityId);
                Decimal orderItemsSize = order.quantidadeItens__c;
                if (isInsertion) {
                    orderItemsSize = orderItemsSize + newMapByOrder.get(order.id).size();
                }
                if ((opp != null) && (opp.quoteItems__r != null) && (!opp.quoteItems__r.isEmpty())) {
                    Map<String, List<QuoteItem__c>> mapQuoteItemsByIdIntegrator = (Map<String, List<QuoteItem__c>>) SObjectUtils.mapObjectsByField(opp.quoteItems__r, 'IdPortal__c', true);
                    System.debug(order.QuantidadeItens__c + ' | ' + mapQuoteItemsByIdIntegrator.keySet().size());
                    if ((orderItemsSize > 0) && (mapQuoteItemsByIdIntegrator.keySet().size() == orderItemsSize)) {
                        order.GanhoParcialTotal__c = 'Ganho Total';
                    } else if ((orderItemsSize > 0)) {
                        order.GanhoParcialTotal__c = 'Ganho Parcial';
                    }
                    if ( ! order.RecordType.Name.equals('Pedido pai')) {
                        order.GanhoParcialTotal__c = '-';
                    }
                    ordersToUpdate.add(order);
                }
            }
            OrderItemHandler.disableTrigger();
            update ordersToUpdate;
            OrderItemHandler.enableTrigger();
        } catch (Exception e) {
            ExceptionUtils.debug(e);
        }
    }

    public static void updateTotalOrParcialWinField(Map<Id, OrderItem> newMap) {
        updateTotalOrParcialWinField(newMap, null, true);
    }

    private static Map<Id, Opportunity> getMapOpportunity(Set<String> opportunityId) {
        return new Map<Id, Opportunity>([
            SELECT
                Id, 
                (
                SELECT
                    Id,
                    IdPortal__c
                FROM
                    QuoteItems__r
                )
            FROM
                Opportunity
            WHERE
                Id IN :OpportunityId
        ]);
    }

    private static List<Order> getOrderList(Set<String> orderIdSet) {
        return [
            SELECT
                Id,
                OpportunityId,
                GanhoParcialTotal__c,
                RecordType.Name,
                QuantidadeItens__c
            FROM
                Order
            WHERE
                Id IN :orderIdSet
        ];
    }
}