Git Tests/force-app/main/default/default/objects/ListaCentroDistribuicao__c/ListaCentroDistribuicao__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Lista com todos os centros de distribuição do Grupo Elfa.</description>
    <label>Centros de distribuição</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ListaCentroDistribuicao__c/fields/CodigoCD__c.field-meta.xml
<CustomField>
    <fullName>CodigoCD__c</fullName>
    <label>Código do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ListaCentroDistribuicao__c/fields/NomeCD__c.field-meta.xml
<CustomField>
    <fullName>NomeCD__c</fullName>
    <label>Nome do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/CreateReservationFormControllerTest.cls
@IsTest
public with sharing class CreateReservationFormControllerTest {

    @IsTest
    static void itShouldGetRecordTypeOptions() {
        Test.startTest();
        CreateReservationFormController.getRecordTypeOptions();
        Test.stopTest();
    }

    @IsTest
    static void itShouldGetDistributionCenters() {
        ListaCentroDistribuicao__c distributionCenter = new ListaCentroDistribuicao__c();
        distributionCenter.Name = 'Teste';
        distributionCenter.NomeCD__c = 'Teste';
        distributionCenter.CodigoCD__c = '001';
        insert distributionCenter;
        
        Test.startTest();
        List<CreateReservationFormController.DefaultOptions> response = CreateReservationFormController.getDeliveryCenters();
        Test.stopTest();

        System.assertEquals(1, response.size(), 'Esperado retorno de 1 centro de distribuição');
    }
}