Git Tests/force-app/main/default/default/objects/ListaCentroDistribuicao__c/ListaCentroDistribuicao__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Lista com todos os centros de distribuição do Grupo Elfa.</description>
    <label>Centros de distribuição</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ListaCentroDistribuicao__c/fields/CodigoCD__c.field-meta.xml
<CustomField>
    <fullName>CodigoCD__c</fullName>
    <label>Código do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ListaCentroDistribuicao__c/fields/NomeCD__c.field-meta.xml
<CustomField>
    <fullName>NomeCD__c</fullName>
    <label>Nome do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Reserva__c/Reserva__c.object-meta.xml
<CustomObject>
    <label>Reserva</label>
    <nameField>
        <displayFormat>RE-{000000}</displayFormat>
        <label>Nome da reserva</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Reserva__c/fields/CodigoCD__c.field-meta.xml
<CustomField>
    <fullName>CodigoCD__c</fullName>
    <label>Código do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/CreateReservationFormController.cls
public with sharing class CreateReservationFormController {
    
    @AuraEnabled(cacheable=true)
    public static List<DefaultOptions> getDeliveryCenters() {
        List<DefaultOptions> options = new List<DefaultOptions>();
        List<ListaCentroDistribuicao__c> deliveryCenters = ListaCentroDistribuicao__c.getAll().values();

        for (ListaCentroDistribuicao__c deliveryCenter : deliveryCenters) {
            DefaultOptions newOption = new DefaultOptions();
            newOption.label = deliveryCenter.CodigoCD__c + ' - ' +deliveryCenter.NomeCD__c;
            newOption.value = deliveryCenter.CodigoCD__c;

            options.add(newOption);
        }

        return options;
    }

    @AuraEnabled(cacheable=true)
    public static List<DefaultOptions> getRecordTypeOptions() {
        List<DefaultOptions> options = new List<DefaultOptions>();

        Map<Id, Schema.RecordTypeInfo> mapRecordTypesInfos = Schema.SObjectType.Reserva__c.getRecordTypeInfosById();

        for (RecordTypeInfo recordTypeInfo : mapRecordTypesInfos.values()) {
            if (!recordTypeInfo.isMaster()) {
                DefaultOptions newOption = new DefaultOptions();
                newOption.label = recordTypeInfo.getName();
                newOption.value = recordTypeInfo.getRecordTypeId();

                options.add(newOption);
            }
        }

        return options;
    }

    public class DefaultOptions {
        @AuraEnabled public String label;
        @AuraEnabled public String value;
    }
}