Git Tests/force-app/main/default/default/objects/ListaCentroDistribuicao__c/ListaCentroDistribuicao__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Lista com todos os centros de distribuição do Grupo Elfa.</description>
    <label>Centros de distribuição</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ListaCentroDistribuicao__c/fields/CodigoCD__c.field-meta.xml
<CustomField>
    <fullName>CodigoCD__c</fullName>
    <label>Código do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ListaCentroDistribuicao__c/fields/NomeCD__c.field-meta.xml
<CustomField>
    <fullName>NomeCD__c</fullName>
    <label>Nome do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Reserva__c/Reserva__c.object-meta.xml
<CustomObject>
    <label>Reserva</label>
    <nameField>
        <displayFormat>RE-{000000}</displayFormat>
        <label>Nome da reserva</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Reserva__c/fields/CentroDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentroDistribuicao__c</fullName>
    <externalId>true</externalId>
    <label>Centro de distribuição</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Reserva__c/fields/CodigoCD__c.field-meta.xml
<CustomField>
    <fullName>CodigoCD__c</fullName>
    <label>Código do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/ReservationTriggerHelper.cls
public with sharing class ReservationTriggerHelper {

    public ReservationTriggerHelper() {}

    public static void updateCodigoReserva(Map<Id, Reserva__c> newMap){

        List<Id> lstReservationId = new List<Id>();

        for (Reserva__c reservation : newMap.values()) {
            
            lstReservationId.add(reservation.Id);
        }

        IntegrationReservationOUT.asyncSendToProtheus(lstReservationId);
    }

    public static void updateDeliveryCenterName(List<Reserva__c> newList) {
        List<ListaCentroDistribuicao__c> deliveryCenters = ListaCentroDistribuicao__c.getAll().values();
        
        for (Reserva__c reservation : newList) {
            for (ListaCentroDistribuicao__c deliveryCenter : deliveryCenters) {
    
                if (reservation.CodigoCD__c == deliveryCenter.CodigoCD__c) {
                    reservation.CentroDistribuicao__c = deliveryCenter.NomeCD__c;
                    break;
                }
            }
        }
    }
}