Git Tests/force-app/main/default/default/objects/Campaign/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Campaign/fields/MetaValor__c.field-meta.xml
<CustomField>
    <fullName>MetaValor__c</fullName>
    <description>Valor (em reais) da meta da campanha.</description>
    <inlineHelpText>Valor (em reais) da meta da campanha.</inlineHelpText>
    <label>Meta (R$)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Campaign/fields/MetaVolume__c.field-meta.xml
<CustomField>
    <fullName>MetaVolume__c</fullName>
    <description>Valor (em quantidade) da meta da campanha.</description>
    <inlineHelpText>Valor (em quantidade) da meta da campanha.</inlineHelpText>
    <label>Meta</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Campaign/fields/NomeCD__c.field-meta.xml
<CustomField>
    <fullName>NomeCD__c</fullName>
    <label>Nome do CD</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>02001</fullName>
                <label>ART MEDICA - EUSEBIO (MATRIZ)</label>
            </value>
            <value>
                <fullName>17002</fullName>
                <label>BIOHOSP - BELO HORIZONTE (FILIAL 02)</label>
            </value>
            <value>
                <fullName>17001</fullName>
                <label>BIOHOSP - CONTAGEM (MATRIZ)</label>
            </value>
            <value>
                <fullName>17003</fullName>
                <label>BIOHOSP - RIO DE JANIERO (FILIAL 03)</label>
            </value>
            <value>
                <fullName>04001</fullName>
                <label>COMERCIAL COMMED - SAO PAULO (MATRIZ)</label>
            </value>
            <value>
                <fullName>16008</fullName>
                <label>DUPATRI - BETIM (FILIAL 08)</label>
            </value>
            <value>
                <fullName>16003</fullName>
                <label>DUPATRI - CATALAO (FILIAL 03)</label>
            </value>
            <value>
                <fullName>16001</fullName>
                <label>DUPATRI - SANTOS (MATRIZ)</label>
            </value>
            <value>
                <fullName>16007</fullName>
                <label>DUPATRI - SUMARE (FILIAL 07)</label>
            </value>
            <value>
                <fullName>13003</fullName>
                <label>MEDCOM - BRASILIA (FILIAL 03)</label>
            </value>
            <value>
                <fullName>13004</fullName>
                <label>MEDCOM - CAMPO GRANDE (FILIAL 04)</label>
            </value>
            <value>
                <fullName>13002</fullName>
                <label>MEDCOM - CUIABA (FILIAL 02)</label>
            </value>
            <value>
                <fullName>13005</fullName>
                <label>MEDCOM - GOIANIA (FILIAL 05)</label>
            </value>
            <value>
                <fullName>13001</fullName>
                <label>MEDCOM - GOIANIA (MATRIZ)</label>
            </value>
            <value>
                <fullName>15001</fullName>
                <label>MOSTAERT - RECIFE (MATRIZ)</label>
            </value>
            <value>
                <fullName>01009</fullName>
                <label>NACIONAL - CONTAGEM (FILIAL 09)</label>
            </value>
            <value>
                <fullName>01010</fullName>
                <label>NACIONAL - CONTAGEM (FILIAL 10)</label>
            </value>
            <value>
                <fullName>01008</fullName>
                <label>NACIONAL - MACAE (FILIAL 08)</label>
            </value>
            <value>
                <fullName>01001</fullName>
                <label>NACIONAL - RIBEIRAO PRETO (MATRIZ)</label>
            </value>
            <value>
                <fullName>01003</fullName>
                <label>NACIONAL - S. J. RIO PRETO (FILIAL 03)</label>
            </value>
            <value>
                <fullName>01005</fullName>
                <label>NACIONAL - SANT. DE PARNAIBA (FILIAL 05)</label>
            </value>
            <value>
                <fullName>01006</fullName>
                <label>NACIONAL - SANT. DE PARNAIBA (FILIAL 06)</label>
            </value>
            <value>
                <fullName>01007</fullName>
                <label>NACIONAL - SANT. DE PARNAIBA (FILIAL 07)</label>
            </value>
            <value>
                <fullName>14003</fullName>
                <label>ONCORIO - CURITIBA (FILIAL 03)</label>
            </value>
            <value>
                <fullName>14002</fullName>
                <label>ONCORIO - ITUMBIARA (FILIAL 02)</label>
            </value>
            <value>
                <fullName>14005</fullName>
                <label>ONCORIO - PINHAIS (FILIAL 05)</label>
            </value>
            <value>
                <fullName>14001</fullName>
                <label>ONCORIO - RIO CLARO (MATRIZ)</label>
            </value>
            <value>
                <fullName>05001</fullName>
                <label>PROCIFAR DISTRIB. - SALVADOR (MATRIZ)</label>
            </value>
            <value>
                <fullName>11001</fullName>
                <label>SALUS LATAM - SAO PAULO (MATRIZ)</label>
            </value>
            <value>
                <fullName>03002</fullName>
                <label>VITAL - SALVADOR (FILIAL 02)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Campaign/fields/Validade__c.field-meta.xml
<CustomField>
    <fullName>Validade__c</fullName>
    <label>Validade</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Segunda</fullName>
            </value>
            <value>
                <fullName>Terça</fullName>
            </value>
            <value>
                <fullName>Quarta</fullName>
            </value>
            <value>
                <fullName>Quinta</fullName>
            </value>
            <value>
                <fullName>Sexta</fullName>
            </value>
            <value>
                <fullName>Sábado</fullName>
            </value>
            <value>
                <fullName>Domingo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Campaign/recordTypes/Campanha.recordType-meta.xml
<RecordType>
    <fullName>Campanha</fullName>
    <active>true</active>
    <description>Tipo de registro utilizado para campanhas de produtos</description>
    <label>Campanha de produto</label>
</RecordType>

Git Tests/force-app/main/default/default/objects/Fornecedor__c/Fornecedor__c.object-meta.xml
<CustomObject>
    <label>Fornecedor</label>
    <nameField>
        <label>Nome do fornecedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fornecedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/ItemCampanha__c.object-meta.xml
<CustomObject>
    <label>Item da campanha</label>
    <nameField>
        <label>Código do item de campanha</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens da campanha</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/Campanha__c.field-meta.xml
<CustomField>
    <fullName>Campanha__c</fullName>
    <label>Campanha</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipName>ItemCampanha</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <formula>NomeProduto__r.Fornecedor__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fornecedor</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/Meta__c.field-meta.xml
<CustomField>
    <fullName>Meta__c</fullName>
    <label>Meta</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/MetaVolume__c.field-meta.xml
<CustomField>
    <fullName>MetaVolume__c</fullName>
    <label>Meta (Volume)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/NomeEmpresa__c.field-meta.xml
<CustomField>
    <fullName>NomeEmpresa__c</fullName>
    <label>Nome do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/NomeProduto__c.field-meta.xml
<CustomField>
    <fullName>NomeProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome do produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>ItemCampanha</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/TipoGatilho__c.field-meta.xml
<CustomField>
    <fullName>TipoGatilho__c</fullName>
    <label>Tipo de gatilho</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FLD</fullName>
            </value>
            <value>
                <fullName>Volume</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/Validade__c.field-meta.xml
<CustomField>
    <fullName>Validade__c</fullName>
    <label>Validade</label>
    <type>Date</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/VigenciaFinal__c.field-meta.xml
<CustomField>
    <fullName>VigenciaFinal__c</fullName>
    <label>Vigência final</label>
    <type>Date</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/VigenciaInicial__c.field-meta.xml
<CustomField>
    <fullName>VigenciaInicial__c</fullName>
    <label>Vigência inicial</label>
    <type>Date</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/recordTypes/ItemCampanhaVendedor.recordType-meta.xml
<RecordType>
    <fullName>ItemCampanhaVendedor</fullName>
    <active>true</active>
    <label>Item de campanha de vendedor</label>
</RecordType>

Git Tests/force-app/main/default/default/objects/ListaCentroDistribuicao__c/ListaCentroDistribuicao__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Lista com todos os centros de distribuição do Grupo Elfa.</description>
    <label>Centros de distribuição</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ListaCentroDistribuicao__c/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ListaCentroDistribuicao__c/fields/NomeCD__c.field-meta.xml
<CustomField>
    <fullName>NomeCD__c</fullName>
    <label>Nome do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Meta__c/Meta__c.object-meta.xml
<CustomObject>
    <label>Meta</label>
    <nameField>
        <displayFormat>M-{000000}</displayFormat>
        <label>Número da meta</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Meta__c/fields/Meta__c.field-meta.xml
<CustomField>
    <fullName>Meta__c</fullName>
    <label>Meta</label>
    <precision>18</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fornecedor</label>
    <referenceTo>Fornecedor__c</referenceTo>
    <relationshipLabel>Produtos</relationshipLabel>
    <relationshipName>Produtos</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/CampaignManagementController.cls
public without sharing class CampaignManagementController {

    public CampaignManagementController() {}

    @AuraEnabled(cacheable=true)
    public static CampaignData getCampaignData(String campaignId) {
        
        CampaignData data = new CampaignData();
        data.params = loadParams();
        data.campaign = loadCampaign(campaignId);
        data.campaignItems = loadCampaignItems(campaignId);
        
        return data;
    }

    @AuraEnabled(cacheable=true)
    public static ResponseAvailabeProducts getAvailableProducts(String data) {

        AvailableProductsParams params = (AvailableProductsParams) JSON.deserialize(
            data, 
            AvailableProductsParams.class
        );

        ResponseAvailabeProducts response = new ResponseAvailabeProducts();
        response.products = loadProducts(params.filter, params.offset);

        return response;
    }

    @AuraEnabled
    public static List<ItemCampanha__c> refreshProducts(String campaignId) {
        List<ItemCampanha__c> campaignItems = loadCampaignItems(campaignId);
        return campaignItems;
    }

    @AuraEnabled(cacheable=true)
    public static Map<String, String> getAvailableDistributionCenters() {
        Map<String, String> distributionCenters = new Map<String, String>{
            'Todos' => 'Todos os centros'
        };

        List<ListaCentroDistribuicao__c> listaCd = [
            SELECT 
                Id, 
                CNPJCD__c,
                NomeCD__c 
            FROM ListaCentroDistribuicao__c 
            ORDER BY NomeCD__c
        ];

        for (ListaCentroDistribuicao__c Cd : listaCd) {
            distributionCenters.put(cd.CNPJCD__c, cd.NomeCD__c);
        }

        return distributionCenters;
    }

    @AuraEnabled
    public static  List<ItemCampanha__c> saveProducts(String campaignId, String records) {
        RecordType rtSalesmanCampaign = [SELECT Id FROM RecordType WHERE DeveloperName = 'ItemCampanhaVendedor' LIMIT 1];
        List<SaveData> dataList = (List<SaveData>) JSON.deserialize(records, List<SaveData>.class);

        List<ItemCampanha__c> recordsList = new List<ItemCampanha__c>();

        for (SaveData data : dataList) {
            String triggerType = null;

            if (data.MetaVolume != null && data.MetaValor != null) {
                triggerType = 'FLD;Volume';
            } else if (data.MetaVolume != null) {
                triggerType = 'Volume';
            } else if (data.MetaValor != null) {
                triggerType = 'FLD';
            }

            ItemCampanha__c campaignItem = new ItemCampanha__c(
                Id = data.Id,
                CNPJCD__c = data.CNPJCD,
                NomeEmpresa__c = data.NomeEmpresa,
                // VigenciaInicial__c = data.VigenciaInicial,
                // VigenciaFinal__c = data.VigenciaFinal,
                MetaVolume__c = data.MetaVolume,
                Meta__c = data.MetaValor,
                TipoGatilho__c = triggerType
            );

            if (campaignItem.Id == null) {
                campaignItem.Campanha__c = data.Campanha;
                campaignItem.NomeProduto__c = data.NomeProduto;
                campaignItem.RecordTypeId = rtSalesmanCampaign?.Id;
            }

            recordsList.add(campaignItem);
        }

        upsert recordsList;

        updateSequence(campaignId);

        List<ItemCampanha__c> campaignItems = loadCampaignItems(campaignId);
        return campaignItems;
    }

    @AuraEnabled(cacheable=false)
    public static  List<ItemCampanha__c> deleteProduct(String campaignId, String recordId) {
        delete new ItemCampanha__c(Id = recordId);

        List<ItemCampanha__c> campaignItems = loadCampaignItems(campaignId);
        return campaignItems;
    }

    @AuraEnabled(cacheable=false)
    public static List<ItemCampanha__c> createItemsByCSVFile(String campaignId, String documentId) {
        RecordType rtSalesmanCampaign = [SELECT Id FROM RecordType WHERE DeveloperName = 'ItemCampanhaVendedor' LIMIT 1];
        String documentData = ReadCSVFileService.getDocumentData(documentId);
        List<String> lines = ReadCSVFileService.getLines(documentData);
    
        Map<String, ItemCampanha__c> mapProductCodeToItem = new Map<String, ItemCampanha__c>();
        Set<String> productCodesSet = new Set<String>();
        
        for (Integer i=0; i<lines.size();i++) {
            
            if (i>0) {
                
                List<String> cols = lines[i].split(',');

                if (cols.size() == 4) { // ok
                    String productCode = cols[0].replaceAll('"', '');
                    // String validityFromCol = cols[1].replaceAll('"', '');
                    // String validityToCol = cols[2].replaceAll('"', '');
                    String MetaCol = cols[1].replaceAll('"', '');
                    String MetaVolumeCol = cols[2].replaceAll('"', '');
                    String CNPJCDcol = cols[3].replaceAll('"', '');

                    // List<String> dateFrom = validityFromCol.split('-');
                    // Date validityFrom = dateFrom.size() == 3 
                    //     ? Date.newInstance(
                    //         Integer.valueOf(dateFrom[0]),
                    //         Integer.valueOf(dateFrom[1]), 
                    //         Integer.valueOf(dateFrom[2])
                    //     ) : null;

                    // List<String> dateTo = validityToCol.split('-');
                    // Date validityTo = dateTo.size() == 3 
                    //     ? Date.newInstance(
                    //         Integer.valueOf(dateTo[0]),
                    //         Integer.valueOf(dateTo[1]), 
                    //         Integer.valueOf(dateTo[2])
                    //     ) : null;

                    Decimal metaVolume;
                    Decimal metaValor;

                    if (MetaVolumeCol != '') {
                        metaVolume = Decimal.valueOf(MetaVolumeCol);
                    }

                    if (MetaCol != '') {
                        metaValor = Decimal.valueOf(MetaCol);
                    }

                    String triggerType = null;

                    if (metaVolume != null && metaValor != null) {
                        triggerType = 'FLD;Volume';
                    } else if (metaVolume != null) {
                        triggerType = 'FLD';
                    } else if (metaValor != null) {
                        triggerType = 'Volume';
                    }

                    ItemCampanha__c campaignItem = new ItemCampanha__c(
                        // VigenciaInicial__c = validityFrom,
                        // VigenciaFinal__c = validityTo,
                        CNPJCD__c = CNPJCDcol.replaceAll(';', ','),
                        Meta__c = metaValor,
                        MetaVolume__c = metaVolume,
                        TipoGatilho__c = triggerType,
                        RecordTypeId = rtSalesmanCampaign?.Id
                    );
    
                    mapProductCodeToItem.put(productCode+'#'+CNPJCDcol, campaignItem);
                    productCodesSet.add(productCode);
                }
            }
        }

        // System.debug(mapProductCodeToItem);
        // System.debug('mapProductCodeToItem '+ mapProductCodeToItem.size());

        Map<String, Id> mapProductCodeToId = loadProductIdsByProductCode(productCodesSet);
        // System.debug('mapProductCodeToId ==>' + mapProductCodeToId);
        Map<String, ItemCampanha__c> mapProductCodeToExistItemCampanha = loadMapProductToCampaignItems(campaignId);

        List<ItemCampanha__c> itemsToUpsert = new List<ItemCampanha__c>();
        for (String customKey : mapProductCodeToItem.keySet()) {
            ItemCampanha__c updatedItem = mapProductCodeToItem.get(customKey);
            List<String> customKeyValues = customKey.split('#');

            System.debug('updatedItem ==>' + updatedItem);
            System.debug('customKeyValues ==>' + customKeyValues);

            if (mapProductCodeToExistItemCampanha.containsKey(customKey)) {
                updatedItem.Id = mapProductCodeToExistItemCampanha.get(customKeyValues[0]).Id;
                itemsToUpsert.add(updatedItem);
            } else {
                System.debug('customKeyValues[0] ==>' + customKeyValues[0]);
                System.debug('mapProductCodeToId.containsKey ==>' + mapProductCodeToId.containsKey(customKeyValues[0]));
                if (mapProductCodeToId.containsKey(customKeyValues[0])) {
                    updatedItem.Campanha__c = campaignId;
                    updatedItem.NomeProduto__c = mapProductCodeToId.get(customKeyValues[0]);
                    itemsToUpsert.add(updatedItem);
                }
            }
        }

        System.debug('itemsToUpsert ' + itemsToUpsert.size());

        upsert itemsToUpsert;
        updateSequence(campaignId);

        delete new ContentDocument(Id = documentId);

        List<ItemCampanha__c> campaignItems = loadCampaignItems(campaignId);
        return campaignItems;
    }

    public static ParamsData loadParams() {
        ParamsData params = new ParamsData();
        params.availableDistributionCenters = getAvailableDistributionCenters();

        return params;
    }

    public static List<Product2> loadProducts(FilterProductData filter, Integer offset) {
        String statement =
            ' SELECT '+
                ' Id, Name, ProductCode, Description, Fornecedor__r.Name ' +
            ' FROM Product2' +
            ' WHERE Id != NULL';
        
        if (filter.product != null && filter.product != '') {
            statement += 
            ' AND ( ' +
                '     Name LIKE \'%'+ filter.product +'%\'' +
                '     OR ProductCode LIKE \'%'+ filter.product +'%\'' +
                '     OR Description LIKE \'%'+ filter.product +'%\'' +
            ' )';
        }

        if (filter.producer != null && filter.producer != '') {
            statement += ' AND Fornecedor__r.Name LIKE \'%'+ filter.producer +'%\'';
        }

        if (offset == null) {
            offset = 20;
        }

        statement += ' ORDER BY Name LIMIT 20 OFFSET ' + offset;

        return Database.query(statement);
    }

    public static Campaign loadCampaign(String campaignId) {
        return [
            SELECT
                Id,
                Name,
                Validade__c,
                RecordType.Name,
                MetaValor__c,
                MetaVolume__c
            FROM Campaign
            WHERE Id =: campaignId
            LIMIT 1
        ];
    }

    public static List<ItemCampanha__c> loadCampaignItems(String campaignId) {
        return [
            SELECT
                Id,
                Campanha__c,
                CNPJCD__c,
                NomeEmpresa__c,
                VigenciaInicial__c,
                VigenciaFinal__c,
                Meta__c,
                MetaVolume__c,
                NomeProduto__c,
                NomeProduto__r.Name,
                NomeProduto__r.Description,
                NomeProduto__r.ProductCode,
                NomeProduto__r.Fornecedor__r.Name
            FROM ItemCampanha__c
            WHERE Campanha__c =: campaignId
            ORDER BY CreatedDate ASC
        ];
    }

    public static List<ItemCampanha__c> loadCampaignItemsByProductId(String campaignId, String productId) {
        return [
            SELECT
                Id
            FROM ItemCampanha__c
            WHERE Campanha__c =: campaignId
            AND NomeProduto__c =: productId
        ];
    }

    public static Map<String, ItemCampanha__c> loadMapProductToCampaignItems(String campaignId) {
        List<ItemCampanha__c> items = [
            SELECT
                Id,
                CNPJCD__c,
                VigenciaInicial__c,
                VigenciaFinal__c,
                NomeProduto__r.Name,
                NomeProduto__r.Description,
                NomeProduto__r.ProductCode,
                NomeProduto__r.Fornecedor__r.Name
            FROM ItemCampanha__c
            WHERE Campanha__c =: campaignId
        ];

        Map<String, ItemCampanha__c> mapItems = new Map<String, ItemCampanha__c>();
        for (ItemCampanha__c item : items) {
            mapItems.put(item.NomeProduto__r.ProductCode+'#'+item.CNPJCD__c, item);
        }

        return mapItems;
    }

    public static Map<String, Id> loadProductIdsByProductCode(Set<String> productCodes) {
        List<Product2> products = [
            SELECT Id, ProductCode
            FROM Product2
            WHERE ProductCode IN: productCodes
        ];

        Map<String, Id> mapProducts = new Map<String, Id>();
        for (Product2 product : products) {
            mapProducts.put(product.ProductCode, product.Id);
        }

        return mapProducts;
    }

    public static void updateSequence(String campaignId) {
        List<ItemCampanha__c> campaignItems = loadCampaignItems(campaignId);
        List<ItemCampanha__c> listToUpdate = new List<ItemCampanha__c>();

        for (Integer i=0; i<campaignItems.size(); i++) {
            String sequence = String.valueOf((i+1));
            String fullSequence = sequence.leftPad(5, '0');

            ItemCampanha__c campaignItem = new ItemCampanha__c(
                Id = campaignItems[i].Id,
                Name = fullSequence.right(5)
            );

            listToUpdate.add(campaignItem);
        }

        update listToUpdate;
    }

    public class ParamsData {
        @AuraEnabled public Map<String, String> availableDistributionCenters;
    }

    public class CampaignData {
        @AuraEnabled public ParamsData params;
        @AuraEnabled public Campaign campaign;
        @AuraEnabled public List<ItemCampanha__c> campaignItems;
    }

    public class AvailableProductsParams {
        @AuraEnabled public FilterProductData filter;
        @AuraEnabled public Integer offset;
    }

    public class ResponseAvailabeProducts {
        @AuraEnabled public List<Product2> products;
    }

    public class FilterProductData {
        @AuraEnabled public String product;
        @AuraEnabled public String producer;
    }

    public class SaveData {
        @AuraEnabled public String Id;
        @AuraEnabled public String Campanha;
        @AuraEnabled public String NomeProduto;
        @AuraEnabled public String CNPJCD;
        @AuraEnabled public String NomeEmpresa;
        @AuraEnabled public Date VigenciaInicial;
        @AuraEnabled public Date VigenciaFinal;
        @AuraEnabled public Decimal MetaVolume;
        @AuraEnabled public Decimal MetaValor;
    }
}