Git Tests/force-app/main/default/default/objects/Campaign/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Campaign/fields/CodigoCD__c.field-meta.xml
<CustomField>
    <fullName>CodigoCD__c</fullName>
    <label>Código de CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Campaign/fields/NomeCD__c.field-meta.xml
<CustomField>
    <fullName>NomeCD__c</fullName>
    <label>Nome do CD</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>02001</fullName>
                <label>ART MEDICA - EUSEBIO (MATRIZ)</label>
            </value>
            <value>
                <fullName>17002</fullName>
                <label>BIOHOSP - BELO HORIZONTE (FILIAL 02)</label>
            </value>
            <value>
                <fullName>17001</fullName>
                <label>BIOHOSP - CONTAGEM (MATRIZ)</label>
            </value>
            <value>
                <fullName>17003</fullName>
                <label>BIOHOSP - RIO DE JANIERO (FILIAL 03)</label>
            </value>
            <value>
                <fullName>04001</fullName>
                <label>COMERCIAL COMMED - SAO PAULO (MATRIZ)</label>
            </value>
            <value>
                <fullName>16008</fullName>
                <label>DUPATRI - BETIM (FILIAL 08)</label>
            </value>
            <value>
                <fullName>16003</fullName>
                <label>DUPATRI - CATALAO (FILIAL 03)</label>
            </value>
            <value>
                <fullName>16001</fullName>
                <label>DUPATRI - SANTOS (MATRIZ)</label>
            </value>
            <value>
                <fullName>16007</fullName>
                <label>DUPATRI - SUMARE (FILIAL 07)</label>
            </value>
            <value>
                <fullName>13003</fullName>
                <label>MEDCOM - BRASILIA (FILIAL 03)</label>
            </value>
            <value>
                <fullName>13004</fullName>
                <label>MEDCOM - CAMPO GRANDE (FILIAL 04)</label>
            </value>
            <value>
                <fullName>13002</fullName>
                <label>MEDCOM - CUIABA (FILIAL 02)</label>
            </value>
            <value>
                <fullName>13005</fullName>
                <label>MEDCOM - GOIANIA (FILIAL 05)</label>
            </value>
            <value>
                <fullName>13001</fullName>
                <label>MEDCOM - GOIANIA (MATRIZ)</label>
            </value>
            <value>
                <fullName>15001</fullName>
                <label>MOSTAERT - RECIFE (MATRIZ)</label>
            </value>
            <value>
                <fullName>01009</fullName>
                <label>NACIONAL - CONTAGEM (FILIAL 09)</label>
            </value>
            <value>
                <fullName>01010</fullName>
                <label>NACIONAL - CONTAGEM (FILIAL 10)</label>
            </value>
            <value>
                <fullName>01008</fullName>
                <label>NACIONAL - MACAE (FILIAL 08)</label>
            </value>
            <value>
                <fullName>01001</fullName>
                <label>NACIONAL - RIBEIRAO PRETO (MATRIZ)</label>
            </value>
            <value>
                <fullName>01003</fullName>
                <label>NACIONAL - S. J. RIO PRETO (FILIAL 03)</label>
            </value>
            <value>
                <fullName>01005</fullName>
                <label>NACIONAL - SANT. DE PARNAIBA (FILIAL 05)</label>
            </value>
            <value>
                <fullName>01006</fullName>
                <label>NACIONAL - SANT. DE PARNAIBA (FILIAL 06)</label>
            </value>
            <value>
                <fullName>01007</fullName>
                <label>NACIONAL - SANT. DE PARNAIBA (FILIAL 07)</label>
            </value>
            <value>
                <fullName>14003</fullName>
                <label>ONCORIO - CURITIBA (FILIAL 03)</label>
            </value>
            <value>
                <fullName>14002</fullName>
                <label>ONCORIO - ITUMBIARA (FILIAL 02)</label>
            </value>
            <value>
                <fullName>14005</fullName>
                <label>ONCORIO - PINHAIS (FILIAL 05)</label>
            </value>
            <value>
                <fullName>14001</fullName>
                <label>ONCORIO - RIO CLARO (MATRIZ)</label>
            </value>
            <value>
                <fullName>05001</fullName>
                <label>PROCIFAR DISTRIB. - SALVADOR (MATRIZ)</label>
            </value>
            <value>
                <fullName>11001</fullName>
                <label>SALUS LATAM - SAO PAULO (MATRIZ)</label>
            </value>
            <value>
                <fullName>03002</fullName>
                <label>VITAL - SALVADOR (FILIAL 02)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/ItemCampanha__c.object-meta.xml
<CustomObject>
    <label>Item da campanha</label>
    <nameField>
        <label>Código do item de campanha</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens da campanha</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/Campanha__c.field-meta.xml
<CustomField>
    <fullName>Campanha__c</fullName>
    <label>Campanha</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipName>ItemCampanha</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/Lote__c.field-meta.xml
<CustomField>
    <fullName>Lote__c</fullName>
    <label>Lote</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/NomeProduto__c.field-meta.xml
<CustomField>
    <fullName>NomeProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome do produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>ItemCampanha</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/PrecoMinimo__c.field-meta.xml
<CustomField>
    <fullName>PrecoMinimo__c</fullName>
    <label>Preço mínimo</label>
    <precision>12</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/VigenciaFinal__c.field-meta.xml
<CustomField>
    <fullName>VigenciaFinal__c</fullName>
    <label>Vigência final</label>
    <type>Date</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/VigenciaInicial__c.field-meta.xml
<CustomField>
    <fullName>VigenciaInicial__c</fullName>
    <label>Vigência inicial</label>
    <type>Date</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/recordTypes/ItemContratoShelfLife.recordType-meta.xml
<RecordType>
    <fullName>ItemContratoShelfLife</fullName>
    <active>true</active>
    <label>Item de campanha de shelf life</label>
</RecordType>

Git Tests/force-app/main/default/default/objects/ListaCentroDistribuicao__c/ListaCentroDistribuicao__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Lista com todos os centros de distribuição do Grupo Elfa.</description>
    <label>Centros de distribuição</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ListaCentroDistribuicao__c/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ListaCentroDistribuicao__c/fields/CodigoCD__c.field-meta.xml
<CustomField>
    <fullName>CodigoCD__c</fullName>
    <label>Código do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ListaCentroDistribuicao__c/fields/NomeCD__c.field-meta.xml
<CustomField>
    <fullName>NomeCD__c</fullName>
    <label>Nome do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/ProductDistributionCenterLotsController.cls
public without sharing class ProductDistributionCenterLotsController {
    
    @AuraEnabled(cacheable=true)
    public static String getShelfLifeProducts(Id productId, String distributionCenterCNPJ) {
        try {
            System.debug('productId: ' + productId);
            System.debug('distributionCenterCNPJ: '+ distributionCenterCNPJ);

            List<ListaCentroDistribuicao__c> distributionCenters = [
                SELECT 
                    CNPJCD__c, 
                    CodigoCD__c 
                FROM ListaCentroDistribuicao__c
                WHERE CNPJCD__c = :distributionCenterCNPJ
                LIMIT 1
            ];

            if (distributionCenters.size() <= 0) {
                throw new AuraHandledException('Centro de distribuição não encontrado.');
            }

            Map<String, Decimal> productPriceByLot = new Map<String, Decimal>();

            List<ItemCampanha__c> shelfLifeItems = [
                SELECT 
                    Id,
                    Lote__c,
                    PrecoMinimo__c
                FROM ItemCampanha__c 
                WHERE NomeProduto__c = :productId
                AND RecordType.DeveloperName = 'ItemContratoShelfLife'
                // AND VigenciaFinal__c <= TODAY 
                // AND VigenciaInicial__c >= TODAY
                AND Campanha__r.NomeCD__c = :distributionCenters[0].CodigoCD__c
            ];

            System.debug('distributionCenters[0].CodigoCD__c: '+ distributionCenters[0].CodigoCD__c);
            System.debug('shelfLifeItems: '+ shelfLifeItems);

            for (ItemCampanha__c item : shelfLifeItems) {
                productPriceByLot.put(item.Lote__c, item.PrecoMinimo__c);
            }
            
            return JSON.serialize(productPriceByLot);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}