Git Tests/force-app/main/default/default/objects/Case/fields/BypassValidationRules__c.field-meta.xml
<CustomField>
    <fullName>BypassValidationRules__c</fullName>
    <defaultValue>false</defaultValue>
    <label>BypassValidationRules</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Case/fields/CasoReaberto__c.field-meta.xml
<CustomField>
    <fullName>CasoReaberto__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo criado para marcar um caso que foi reaberto</description>
    <label>Caso Reaberto</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Case/fields/NotaFiscal__c.field-meta.xml
<CustomField>
    <fullName>NotaFiscal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Nota fiscal</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Favor informar uma Nota Fiscal que se relacione ao CLIENTE informado no CASO.</errorMessage>
        <filterItems>
            <field>NotasFiscais__c.Conta__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <infoMessage>Favor informar uma Nota Fiscal que se relacione ao CLIENTE informado no CASO..</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>NotasFiscais__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Case/fields/ResponsavelAtendimento__c.field-meta.xml
<CustomField>
    <fullName>ResponsavelAtendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Informação do atendente responsável pelo caso</description>
    <inlineHelpText>Nome do Atendente responsável pelo Caso</inlineHelpText>
    <label>Responsável pelo Atendimento</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Selecionar APENAS um responsável dentro da área de Atendimento ao Cliente do Grupo Elfa.</errorMessage>
        <filterItems>
            <field>User.Department</field>
            <operation>equals</operation>
            <value>Atendimento ao Cliente</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/NotasFiscais__c/NotasFiscais__c.object-meta.xml
<CustomObject>
    <label>Nota fiscal</label>
    <nameField>
        <label>Número da nota fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas fiscais</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/NotasFiscais__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Nome do cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>NotasFiscais</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/CaseHelperTest.cls
/**
 * @description       : 
 * @author            : Raphael Soares
 * @author username   : raphael.holanda.ext@iconit.com.br
 * @company           : Icon IT Solutions
 * @last modified on  : 18-11-2021
 * @last modified by  : raphael.holanda.ext@iconit.com.br
**/
@isTest
    public class CaseHelperTest {
    @isTest
    public static void markReopenedField_test() {
        
        
        Account acc = TestUtility.createAccount();
        insert acc;
        
        Contact ctt = TestUtility.createContact(acc.Id);
        insert ctt;
        
        Case c = TestUtility.createCase(acc, ctt);
        insert c;
        
        c.Status = 'Em Andamento';
        update c;
        
        CaseTH.disableTrigger();
        c.BypassValidationRules__c = true;
        c.Status = 'Finalizado';
        update c;
        CaseTH.enableTrigger();
        
        Test.startTest();
        
        c.Status = 'Atrasado';
        update c;
        c = [SELECT CasoReaberto__c FROM Case WHERE Id =: c.Id];
        
        c.BypassValidationRules__c = false;
        c.Status = 'Finalizado';
        update c;
        System.assert(c.CasoReaberto__c);
        Test.stopTest();
    }
    
    @isTest
    public static void closeCase() {
        Account acc = TestUtility.createAccount();
        insert acc;
        
        Contact ctt = TestUtility.createContact(acc.Id);
        insert ctt;
        
        Case c = TestUtility.createCase(acc, ctt);
        insert c;
        
        c.Status = 'Em Andamento';
        update c;
        
        Test.startTest();
        CaseController.closeCase(c.Id);
        Test.stopTest();
    }    
    
    @isTest
    public static void closeCaseWithError() {
        Account acc = TestUtility.createAccount();
        insert acc;
        
        Contact ctt = TestUtility.createContact(acc.Id);
        insert ctt;
        
        Case c = TestUtility.createCase(acc, ctt);
        insert c;
        
        Test.startTest();
        try {
            CaseController.closeCase(c.Id);
        } catch (Exception ex) {
            System.assert(ex instanceof AuraHandledException);
        }
       
        Test.stopTest();
    } 
    
    @isTest
    public static void changeCaseOwner() {
        Account acc = TestUtility.createAccount();
        insert acc;
        
        Contact ctt = TestUtility.createContact(acc.Id);
        insert ctt;
        
        Case c = TestUtility.createCase(acc, ctt);
        c.ResponsavelAtendimento__c = UserInfo.getUserId();
        insert c;
        
        Test.startTest();
        CaseController.changeOwner(c.Id);

        c = [SELECT Id, OwnerId, Status, BypassValidationRules__c FROM Case WHERE Id =: c.Id];

        c.Status = 'Atrasado';
        update c;        

        c.Status = 'Encerrado';
        c.BypassValidationRules__c = true;
        update c;

        try {
            CaseController.changeOwner(c.Id);
        } catch (Exception ex) {
            System.assert(ex instanceof AuraHandledException);
        }

        Test.stopTest();
    }    

    @isTest
    public static void changeCaseOwnerWithError() {

        try {
            CaseController.changeOwner(UserInfo.getUserId());
        } catch (Exception ex) {
            System.assert(ex instanceof AuraHandledException);
        }

    }        
    
    @isTest
    public static void checkDuplicatedIncoiceAssignment() {

        Case c1;
        Account acc = TestUtility.createAccount();
        insert acc;
        
        Contact ctt = TestUtility.createContact(acc.Id);
        insert ctt;

        Order ord = TestUtility.createOrder(acc);
        insert ord;
        
        NotasFiscais__c nf = TestUtility.createNotaFiscal(ord, acc);
        nf.Conta__c = acc.Id;
        insert nf;
        
        c1 = TestUtility.createCase(acc, ctt);
        c1.NotaFiscal__c = nf.Id;
        insert c1;     

        Test.startTest();
    
        try {

            c1 = [SELECT CaseNumber, NotaFiscal__c FROM Case WHERE Id =: c1.Id];

            Case c2 = TestUtility.createCase(acc, ctt);
            insert c2;  
            
            c2.NotaFiscal__c = nf.Id;
            update c2;
            
        } catch (Exception ex) {
            System.debug(ex.getMessage());
            String label = Label.CannotSaveNewCaseWhenOngoingCaseWithSameInvoiceNumber.replace('__CASENUMBER__', c1.CaseNumber);
            System.assert(ex.getMessage().contains(label));
        }

        Test.stopTest();
    } 
           
}