Git Tests/force-app/main/default/default/objects/Case/fields/CasoReaberto__c.field-meta.xml
<CustomField>
    <fullName>CasoReaberto__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo criado para marcar um caso que foi reaberto</description>
    <label>Caso Reaberto</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Case/fields/Elapsed_time_in_miliseconds__c.field-meta.xml
<CustomField>
    <fullName>Elapsed_time_in_miliseconds__c</fullName>
    <description>Elapsed time in miliseconds since the case was created until its closure</description>
    <label>Tempo Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Case/fields/FinishedDate__c.field-meta.xml
<CustomField>
    <fullName>FinishedDate__c</fullName>
    <label>Data de Finalização</label>
    <type>DateTime</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Case/fields/NotaFiscal__c.field-meta.xml
<CustomField>
    <fullName>NotaFiscal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Nota fiscal</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Favor informar uma Nota Fiscal que se relacione ao CLIENTE informado no CASO.</errorMessage>
        <filterItems>
            <field>NotasFiscais__c.Conta__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <infoMessage>Favor informar uma Nota Fiscal que se relacione ao CLIENTE informado no CASO..</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>NotasFiscais__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Case/fields/ReopenedDatetime__c.field-meta.xml
<CustomField>
    <fullName>ReopenedDatetime__c</fullName>
    <label>Data e Hora de Reabertura</label>
    <type>DateTime</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Case/fields/ReopeningFinishedDate__c.field-meta.xml
<CustomField>
    <fullName>ReopeningFinishedDate__c</fullName>
    <label>Data de Finalização (Reabertura)</label>
    <type>DateTime</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/CaseHelper.cls
/**
 * @description       : 
 * @author            : Raphael Soares
 * @author username   : raphael.holanda.ext@iconit.com.br
 * @company           : Icon IT Solutions
 * @last modified on  : 18-11-2021
 * @last modified by  : raphael.holanda.ext@iconit.com.br
**/
public without sharing class CaseHelper {
    
    public static void markReopenedField(Case c, Case oldCase){
        if(oldCase != null && c.Status != oldCase.Status && (oldCase.Status == 'Finalizado' || oldCase.Status == 'Encerrado')) {
            if(c.Status == 'Em Andamento' || c.Status == 'Em Espera' || c.Status == 'Atrasado'){
                c.CasoReaberto__c = true;
                c.ReopenedDatetime__c = Datetime.now();
            }
        }
    }

    public static void fillFinishedDates(Case c, Case oldCase) {
        if(oldCase != null && c.Status != oldCase.Status && (c.Status == 'Finalizado' || c.Status == 'Encerrado')){
            if(c.CasoReaberto__c){
                c.ReopeningFinishedDate__c = Datetime.now();
            } else {
                c.FinishedDate__c = Datetime.now();
            }
        }
    }
    
    public static void checkInvoiceNumbers(Map<Id, Set<Case>> casesByInvoice) {
        
        Set<Case> cases = new Set<Case>();
        for (Id invoiceId : casesByInvoice.keySet()) {
            cases.addAll(casesByInvoice.get(invoiceId));
        }

        for (Case ca : [SELECT Id, CaseNumber, NotaFiscal__c FROM Case 
                        WHERE NotaFiscal__c =: casesByInvoice.keySet()
                        AND Id !=: cases
                        AND Status NOT IN ('Closed')])
        {
            for (Case currentCase : casesByInvoice.get(ca.NotaFiscal__c)) 
            {
               String label = Label.CannotSaveNewCaseWhenOngoingCaseWithSameInvoiceNumber.replace('__CASENUMBER__', ca.CaseNumber);
               currentCase.addError(label); 
            }
        }        
    }

    public static void calculateCaseElapsedTime(Case record) {

        BusinessDays businessDays = BusinessDays.getInstance();
        Datetime endDate = businessDays.getDateConsideringOnlyBusinessDays(record.CreatedDate, System.now());
        Long milliseconds = endDate.getTime() - record.CreatedDate.getTime();

        record.Elapsed_time_in_miliseconds__c = milliseconds;
   
    }    
    
}