Git Tests/force-app/main/default/default/objects/Case/fields/DevolucaoAtoOuPosEntrega__c.field-meta.xml
<CustomField>
    <fullName>DevolucaoAtoOuPosEntrega__c</fullName>
    <label>Devolução Ato ou Pós Entrega?</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Razao__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Não Aplicável</fullName>
            </value>
            <value>
                <fullName>No Ato</fullName>
            </value>
            <value>
                <fullName>Pós Entrega</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Case/fields/FormatoDeDevolucao__c.field-meta.xml
<CustomField>
    <fullName>FormatoDeDevolucao__c</fullName>
    <label>Formato de Devolução</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Razao__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Física</fullName>
            </value>
            <value>
                <fullName>Não Aplicável</fullName>
            </value>
            <value>
                <fullName>Virtual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Case/fields/Motivo__c.field-meta.xml
<CustomField>
    <fullName>Motivo__c</fullName>
    <label>Motivo</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Razao__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>2ª Via de Nota Fiscal/Boleto</fullName>
            </value>
            <value>
                <fullName>Atendimento</fullName>
            </value>
            <value>
                <fullName>Atualização de Cadastro</fullName>
            </value>
            <value>
                <fullName>Ausência na Entrega</fullName>
            </value>
            <value>
                <fullName>Cadastro</fullName>
            </value>
            <value>
                <fullName>Cancelamento do Pedido</fullName>
            </value>
            <value>
                <fullName>Carta de Comprometimento de Troca</fullName>
            </value>
            <value>
                <fullName>Carta de Correção</fullName>
            </value>
            <value>
                <fullName>Cotação</fullName>
            </value>
            <value>
                <fullName>Desvio de Qualidade</fullName>
            </value>
            <value>
                <fullName>Devolução</fullName>
            </value>
            <value>
                <fullName>Documentos de Filiais</fullName>
            </value>
            <value>
                <fullName>Endereço errado</fullName>
            </value>
            <value>
                <fullName>Entrega em Atraso</fullName>
            </value>
            <value>
                <fullName>Entrega Programada</fullName>
            </value>
            <value>
                <fullName>Erro no Cadastro Produto</fullName>
            </value>
            <value>
                <fullName>Erro XML/ 2ª via</fullName>
            </value>
            <value>
                <fullName>Extravio do Pedido</fullName>
            </value>
            <value>
                <fullName>Falta de Estoque</fullName>
            </value>
            <value>
                <fullName>Falta de Informação no COMPROVEI/ LYNCROS</fullName>
            </value>
            <value>
                <fullName>Faturamento do Pedido</fullName>
            </value>
            <value>
                <fullName>Faturamento Incorreto</fullName>
            </value>
            <value>
                <fullName>Financeiro</fullName>
            </value>
            <value>
                <fullName>Fiscal</fullName>
            </value>
            <value>
                <fullName>Histórico de Pagamentos</fullName>
            </value>
            <value>
                <fullName>Histórico de Pedidos</fullName>
            </value>
            <value>
                <fullName>Inconsistência Geral</fullName>
            </value>
            <value>
                <fullName>Não Aplicável</fullName>
            </value>
            <value>
                <fullName>NPS</fullName>
            </value>
            <value>
                <fullName>Paciente Veio a Óbto/Alta</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Case/fields/NotaFiscal__c.field-meta.xml
<CustomField>
    <fullName>NotaFiscal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Nota fiscal</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Favor informar uma Nota Fiscal que se relacione ao CLIENTE informado no CASO.</errorMessage>
        <filterItems>
            <field>NotasFiscais__c.Conta__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <infoMessage>Favor informar uma Nota Fiscal que se relacione ao CLIENTE informado no CASO..</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>NotasFiscais__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Case/fields/OwnerDeveloperName__c.field-meta.xml
<CustomField>
    <fullName>OwnerDeveloperName__c</fullName>
    <formula>IF(Owner:Queue.QueueName = &quot;&quot;,Owner:User.Department, Owner:Queue.DeveloperName)</formula>
    <label>Owner Developer Name</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Case/fields/ProdutoTermolabil__c.field-meta.xml
<CustomField>
    <fullName>ProdutoTermolabil__c</fullName>
    <label>Produto Termolábil?</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Razao__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Não</fullName>
            </value>
            <value>
                <fullName>Sim</fullName>
            </value>
            <value>
                <fullName>Não Aplicável</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Case/fields/Razao__c.field-meta.xml
<CustomField>
    <fullName>Razao__c</fullName>
    <label>Razão</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Cadastro</fullName>
            </value>
            <value>
                <fullName>Carta de Comprometimento de Troca</fullName>
            </value>
            <value>
                <fullName>Carta de Correção</fullName>
            </value>
            <value>
                <fullName>Cotação</fullName>
            </value>
            <value>
                <fullName>Devolução</fullName>
            </value>
            <value>
                <fullName>Faturamento Pedido</fullName>
            </value>
            <value>
                <fullName>Fechamento de Loop</fullName>
            </value>
            <value>
                <fullName>Financeiro</fullName>
            </value>
            <value>
                <fullName>Pedido não faturado</fullName>
            </value>
            <value>
                <fullName>Pesquisa Ativa</fullName>
            </value>
            <value>
                <fullName>Reclamação</fullName>
            </value>
            <value>
                <fullName>Tracking do Pedido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Case/fields/ResponsavelAtendimento__c.field-meta.xml
<CustomField>
    <fullName>ResponsavelAtendimento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Informação do atendente responsável pelo caso</description>
    <inlineHelpText>Nome do Atendente responsável pelo Caso</inlineHelpText>
    <label>Responsável pelo Atendimento</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Selecionar APENAS um responsável dentro da área de Atendimento ao Cliente do Grupo Elfa.</errorMessage>
        <filterItems>
            <field>User.Department</field>
            <operation>equals</operation>
            <value>Atendimento ao Cliente</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>User</referenceTo>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Case/fields/Submotivo__c.field-meta.xml
<CustomField>
    <fullName>Submotivo__c</fullName>
    <label>Submotivo</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Motivo__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Alterar data de entrega</fullName>
            </value>
            <value>
                <fullName>Alterar endereço de entrega</fullName>
            </value>
            <value>
                <fullName>Alvará Vencido</fullName>
            </value>
            <value>
                <fullName>Arrependimento de Compra</fullName>
            </value>
            <value>
                <fullName>Atendimento ao Cliente</fullName>
            </value>
            <value>
                <fullName>Atraso na rota de entrega</fullName>
            </value>
            <value>
                <fullName>Atraso na separação</fullName>
            </value>
            <value>
                <fullName>Avaria</fullName>
            </value>
            <value>
                <fullName>Bloqueado por crédito</fullName>
            </value>
            <value>
                <fullName>Cadastro Desatualizado</fullName>
            </value>
            <value>
                <fullName>Cadastro do Cliente</fullName>
            </value>
            <value>
                <fullName>Cadastro do Produto</fullName>
            </value>
            <value>
                <fullName>Cliente Não Aceita Lotes Variados</fullName>
            </value>
            <value>
                <fullName>Cliente Não Usa a Marca</fullName>
            </value>
            <value>
                <fullName>CNPJ Divergente do Cotado</fullName>
            </value>
            <value>
                <fullName>Código de Barra Incorreto</fullName>
            </value>
            <value>
                <fullName>Conversão / Unidade de Medida</fullName>
            </value>
            <value>
                <fullName>Cotação Errada</fullName>
            </value>
            <value>
                <fullName>Dados de Qualidade</fullName>
            </value>
            <value>
                <fullName>Descrição Incorreta</fullName>
            </value>
            <value>
                <fullName>Desvio de Qualidade</fullName>
            </value>
            <value>
                <fullName>EAN/REGISTRO ANVISA</fullName>
            </value>
            <value>
                <fullName>Erro de Estoque</fullName>
            </value>
            <value>
                <fullName>Erro Integração de Sistemas</fullName>
            </value>
            <value>
                <fullName>Erro na Separação</fullName>
            </value>
            <value>
                <fullName>Erro no cadastro do produto</fullName>
            </value>
            <value>
                <fullName>Erro VDE</fullName>
            </value>
            <value>
                <fullName>Erro VDI</fullName>
            </value>
            <value>
                <fullName>Extravio de Mercadoria</fullName>
            </value>
            <value>
                <fullName>Fabricante</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/NotasFiscais__c/NotasFiscais__c.object-meta.xml
<CustomObject>
    <label>Nota fiscal</label>
    <nameField>
        <label>Número da nota fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas fiscais</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/NotasFiscais__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Nome do cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>NotasFiscais</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/CaseControllerTest.cls
@isTest
public class CaseControllerTest {
    
    @testSetup
    public static void setup() {
        Account acc = TestUtility.createAccPJ();
        insert acc;
        
        Contact ctt = TestUtility.createContact(acc.Id);
        insert ctt;
        
        Order ord = TestUtility.createOrder(acc);
        insert ord;        
        
        NotasFiscais__c nf = TestUtility.createNotaFiscal(ord, acc);
        nf.Conta__c = acc.Id;
        insert nf;     
        
        Group queue = [SELECT Id FROM Group WHERE DeveloperName ='AtendimentoAoClienteQueue'];
        
        Case c = TestUtility.createCase(acc, ctt);
        c.NotaFiscal__c = nf.Id;
        c.OwnerId = queue.Id;
        insert c;          
    }
    
    @isTest
    public static void changeOwner() {
        
        Case record = [SELECT Id, OwnerDeveloperName__c FROM Case];
        
        System.assertEquals('AtendimentoAoClienteQueue', record.OwnerDeveloperName__c);
        
        record = new Case ( Id = record.Id);
        record.ResponsavelAtendimento__c = UserInfo.getUserId();
        record.Type = 'Incidente';
        record.Razao__c = 'Devolução';
        record.Motivo__c = 'Cadastro';
        record.FormatoDeDevolucao__c = 'Virtual';
        record.Submotivo__c = 'Cadastro do Cliente';        
        record.DevolucaoAtoOuPosEntrega__c = 'No Ato';
        record.ProdutoTermolabil__c = 'Sim';
        update record;
        
        CaseController.changeOwner(record.Id);
        
        record = [SELECT Id, OwnerDeveloperName__c FROM Case];
        
        System.assertEquals('Registration', record.OwnerDeveloperName__c);        
    }    
    
    @isTest
    public static void changeOwnerUnexpectedError() {
        
        try {
            CaseController.changeOwner(UserInfo.getUserId());
        } catch (Exception ex) {
            System.assert(ex instanceof AuraHandledException);
        }
        
    }
    
    @isTest
    public static void closeCaseDMLError() {
        
        try {
            CaseController.closeCase(UserInfo.getUserId());  
        } catch (Exception ex) {
            System.assert(ex instanceof AuraHandledException);
        }
        
        Case record = [SELECT Id FROM Case];
        try {
            CaseController.closeCase(record.Id);  
        } catch (Exception ex) {
            System.assert(ex instanceof AuraHandledException);
        }        
        
    }      
    
    @isTest
    public static void closeCase() {
        
        Case record = [SELECT Motivo__c, Submotivo__c, Type, Razao__c, Status FROM Case];
        record.Status = 'Em Andamento';       
        record.Type = 'Solicitação';
        record.Razao__c = 'Cadastro';
        record.Motivo__c = 'Atualização de Cadastro';
        record.Submotivo__c = 'Cadastro do Cliente';
        update record;
        
        CaseController.closeCase(record.Id);
        
        record = [SELECT Status FROM Case]; 
        System.assertEquals('Closed', record.Status);
        
        try {
            CaseController.closeCase(record.Id);
        } catch (Exception ex) {
            System.assert(ex instanceof DMLException);
        }        
        
    }          
    
}