Git Tests/force-app/main/default/default/objects/Case/fields/NotaFiscal__c.field-meta.xml
<CustomField>
    <fullName>NotaFiscal__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Nota fiscal</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Favor informar uma Nota Fiscal que se relacione ao CLIENTE informado no CASO.</errorMessage>
        <filterItems>
            <field>NotasFiscais__c.Conta__c</field>
            <operation>equals</operation>
            <valueField>$Source.AccountId</valueField>
        </filterItems>
        <infoMessage>Favor informar uma Nota Fiscal que se relacione ao CLIENTE informado no CASO..</infoMessage>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>NotasFiscais__c</referenceTo>
    <relationshipLabel>Cases</relationshipLabel>
    <relationshipName>Cases</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/NotasFiscais__c/NotasFiscais__c.object-meta.xml
<CustomObject>
    <label>Nota fiscal</label>
    <nameField>
        <label>Número da nota fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas fiscais</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/NotasFiscais__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Nome do cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>NotasFiscais</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/NumeroPedidoCliente__c.field-meta.xml
<CustomField>
    <fullName>NumeroPedidoCliente__c</fullName>
    <inlineHelpText>Ex: AF123, OC345, ID6864</inlineHelpText>
    <label>Ordem de compra do cliente</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/PedidoPai__c.field-meta.xml
<CustomField>
    <fullName>PedidoPai__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido pai</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Pedidos filho</relationshipLabel>
    <relationshipName>PedidoFilho</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/ChatBotTest.cls
@isTest
public class ChatBotTest {
    
    @testSetup
    public static void setup() {
        Account acc = TestUtility.createAccPJ();
        insert acc;
        
        Contact ctt = TestUtility.createContact(acc.Id);
        insert ctt;
        
        Order ordParent = TestUtility.createOrder(acc);
        insert ordParent;      

        Order ord = TestUtility.createOrder(acc);
        ord.NumeroPedidoCliente__c = '0001';
        ord.PedidoPai__c = ordParent.Id;
        insert ord;        
        
        NotasFiscais__c nf = TestUtility.createNotaFiscal(ord, acc);
        nf.Conta__c = acc.Id;
        insert nf;     
        
        Case c = TestUtility.createCase(acc, ctt);
        c.NotaFiscal__c = nf.Id;  
        insert c;             
    }
    
    @isTest
    public static void createCase() {
        
        List<Case> records = [SELECT Id FROM Case WHERE Origin = 'Chatbot'];
        System.assertEquals(0, records.size());
        
        Test.startTest();
        ChatBot.createCase(new List<String> {'04585497000108'});
        Test.stopTest();
        
        records = [SELECT Id FROM Case WHERE Origin = 'Chatbot'];
        System.assertEquals(1, records.size());
    }      
    
    @isTest
    public static void createCaseError() {
        
        List<Case> records = [SELECT Id FROM Case WHERE Origin = 'Chatbot'];
        System.assertEquals(0, records.size());
        
        Test.startTest();
        ChatBot.createCase(new List<String> {});
        Test.stopTest();
        
        records = [SELECT Id FROM Case WHERE Origin = 'Chatbot'];
        System.assertEquals(0, records.size());
    }    
    
    @isTest
    public static void fetchInvoiceBase64File() {
        
        Test.startTest();
        
        Map<String, String> params = new Map<String, String> {
                'invoiceNumber' => 'nf0000000000001',
                'documentType' => 'invoice'
                };   
                    
        Test.setMock(HttpCalloutMock.class, new SingleRequestMock(200, 'OK', '{"danfe":"document"}', null));
        String response = ChatBot.fetchBase64File(params);
        System.assertEquals('document', response);
        
        Test.stopTest();
    }
    
    @isTest
    public static void fetchPaymentSlipBase64File() {
        
        Test.startTest();
        
        Map<String, String> params = new Map<String, String> {
            'customerId' => '04585497000108',
                'orderNumber' => '0001',
                'documentType' => 'paymentSlip'
                };   
                    
                    Test.setMock(HttpCalloutMock.class, new SingleRequestMock(200, 'OK', '{"TituloAberto" : [{"PEDIDO":"0001","NUM":"0002", "CGC_CD":"", "PREFIXO":"", "TIPO":"", "PARCELA":""}], "boleto":"document"}', null));
        String response = ChatBot.fetchBase64File(params);
        System.assertEquals('document', response);
        
        Test.stopTest();
    }     
    
    @isTest
    public static void fetchBase64FileError() {
        
        Test.startTest();
        
        Map<String, String> params = new Map<String, String> {
            'customerId' => '02643718000121',
                'invoiceNumber' => '000758215',
                'documentType' => 'invoice'
                };   
                    
		Test.setMock(HttpCalloutMock.class, new SingleRequestMock(200, 'OK', '{"error":""}', null));
        String response = ChatBot.fetchBase64File(params);
        System.assertEquals(true, response instanceof Id);  
        
        Test.stopTest();
    }
    
    @isTest
    public static void fetchBase64FileUnknownError() {
        
        Test.startTest();
        
        Map<String, String> params = new Map<String, String> {
            'customerId' => '02643718000121',
                'invoiceNumber' => '000758215',
                'documentType' => 'invoice'
                };   
                    
		Test.setMock(HttpCalloutMock.class, new SingleRequestMock(400, 'NOK', '', null));
        String response = ChatBot.fetchBase64File(params);
        System.assertEquals(true, response instanceof Id);    
        
        Test.stopTest();
    }      
    
}