Git Tests/force-app/main/default/default/objects/AnaliseERB__c/AnaliseERB__c.object-meta.xml
<CustomObject>
    <label>Análise ERB</label>
    <nameField>
        <displayFormat>ERB-{000}</displayFormat>
        <label>Recomendação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Análise ERB</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/AnaliseERB__c/fields/Descricao__c.field-meta.xml
<CustomField>
    <fullName>Descricao__c</fullName>
    <label>Comentários (opcional)</label>
    <type>TextArea</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/AnaliseERB__c/fields/Orcamento__c.field-meta.xml
<CustomField>
    <fullName>Orcamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Orçamento</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Análise ERB</relationshipLabel>
    <relationshipName>AnaliseERB</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/AnaliseERB__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Análise ERB</relationshipLabel>
    <relationshipName>AnaliseERB</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/AnaliseERB__c/fields/StatusRecomendacao__c.field-meta.xml
<CustomField>
    <fullName>StatusRecomendacao__c</fullName>
    <label>Status da Recomendação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aceita efetuou a compra</fullName>
            </value>
            <value>
                <fullName>Aceita vai efetuar a compra</fullName>
            </value>
            <value>
                <fullName>Aceita porém cliente sem budget</fullName>
            </value>
            <value>
                <fullName>Aceita porém cliente não quer agora</fullName>
            </value>
            <value>
                <fullName>Aceita (Outros justificar)</fullName>
            </value>
            <value>
                <fullName>Recusada sem interesse por ainda ter estoque</fullName>
            </value>
            <value>
                <fullName>Recusada não trabalha com este produto</fullName>
            </value>
            <value>
                <fullName>Recusada sem interesse por ser laboratório/marca não padronizada</fullName>
            </value>
            <value>
                <fullName>Recusada sem interesse por prazo de entrega</fullName>
            </value>
            <value>
                <fullName>Recusada sem interesse pelo preço</fullName>
            </value>
            <value>
                <fullName>Recusada (Outros Justificar)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/GeneralParameters__c/GeneralParameters__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Parâmetros gerais.</description>
    <label>Parâmetros gerais</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/GeneralParameters__c/fields/QuantidadeProdutosRecomendados__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeProdutosRecomendados__c</fullName>
    <label>Quantidade de produtos recomendados</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do produto</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/classes/RecommendationsService.cls
public with sharing class RecommendationsService {

    public static List<RecommendationData> getRecommendations(String contextRecordId, Integer maxResults) {
        List<RecommendationData> recommendations = new List<RecommendationData>();
        
        ConnectApi.NBARecommendations nbaRecommendations = 
            ConnectApi.NextBestAction.executeStrategy('ERB', maxResults, contextRecordId);

        for (ConnectApi.NBARecommendation currentNBARecommendation : nbaRecommendations.recommendations) {
            
            ConnectApi.NBANativeRecommendation nbaRecommendationTarget = 
                (ConnectApi.NBANativeRecommendation) currentNBARecommendation.target;

            ConnectApi.NBAFlowAction nbaRecommendationTargetAction = 
                (ConnectApi.NBAFlowAction) currentNBARecommendation.targetAction;
            
            RecommendationData recommendation = new RecommendationData();
            recommendation.externalId       = currentNBARecommendation.externalId;
            recommendation.targetId         = nbaRecommendationTarget.id;
            recommendation.targetActionId   = nbaRecommendationTargetAction.id;
            recommendation.targetActionName = nbaRecommendationTargetAction.name;
            recommendations.add(recommendation);
        }
        
        return recommendations;
    }

    public static void setReaction(ReactionDataInput reactionDataInput) {
        ConnectApi.RecommendationReactionInput reaction = new ConnectApi.RecommendationReactionInput();
        reaction.strategyName       = 'ERB';
        reaction.externalId         = reactionDataInput.externalId;
        reaction.targetId           = reactionDataInput.targetId;
        //reaction.targetActionId     = reactionDataInput.targetActionId;
        reaction.targetActionName   = reactionDataInput.targetActionName;
        reaction.reactionType       = reactionDataInput.reaction == 'Accepted'
            ? ConnectApi.RecommendationReactionType.ACCEPTED
            : ConnectApi.RecommendationReactionType.REJECTED;

        ConnectApi.NextBestAction.setRecommendationReaction(reaction);

        AnaliseERB__c analise = new AnaliseERB__c(
            Orcamento__c = reactionDataInput.contextRecordId,
            Produto__c = reactionDataInput.externalId,
            Descricao__c = reactionDataInput.reactionMessage,
            StatusRecomendacao__c = reactionDataInput.reactionOption
        );

        insert analise;
    }
    
    @InvocableMethod(label='Get recommendation' description='Get recommendation products for PDF')
    public static List<String> getRecommendationPDF(List<String> oppIdList) {
        GeneralParameters__c parameters = GeneralParameters__c.getValues('Parametro geral');
        String oppId = null;
        for (String str : oppIdList) {
            oppId = str;
        }
        Set<String> productIdSet = new Set<String>();
        // System.debug(LIMIT.);
        List<RecommendationsService.RecommendationData> recommendationList = RecommendationsService.getRecommendations(oppId, Integer.valueOf(parameters.QuantidadeProdutosRecomendados__c));
        for (RecommendationsService.RecommendationData rec : recommendationList) {
            System.debug(rec);
            productIdSet.add(rec.externalId);
        }
        
        String prodCode = '';
        for (Product2 prod : [SELECT Id, ExternalId__c FROM Product2 WHERE Id IN: productIdSet]) {
            if (prodCode != '') {
                prodCode += ',';
            }
            prodCode += prod.ExternalId__c;
            System.debug(prodCode);
        }    
        
        return new List<String>{prodCode};
    }

    public class RecommendationData {
        public String externalId;
        public String targetId;
        public String targetActionId;
        public String targetActionName;
    }

    public class ReactionDataInput {
        public String externalId;
        public String targetId;
        public String targetActionId;
        public String targetActionName;
        public String contextRecordId;
        public String reaction;
        public String reactionOption;
        public String reactionMessage;
    }
}