Git Tests/force-app/main/default/default/objects/Configuration_Contract_Temp__mdt/Configuration_Contract_Temp__mdt.object-meta.xml
<CustomObject>
    <label>Configuration Contract Temp</label>
    <pluralLabel>Configuration Contract Temp</pluralLabel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Configuration_Contract_Temp__mdt/fields/Field_Name_CSV__c.field-meta.xml
<CustomField>
    <fullName>Field_Name_CSV__c</fullName>
    <label>Field Name CSV</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Configuration_Contract_Temp__mdt/fields/Field_Name_SF__c.field-meta.xml
<CustomField>
    <fullName>Field_Name_SF__c</fullName>
    <label>Field Name SF</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Contract/recordTypes/Contrato.recordType-meta.xml
<RecordType>
    <fullName>Contrato</fullName>
    <active>true</active>
    <description>Tipo de registro para os contratos de operação logística, acordo comercial e preço fixo.</description>
    <label>Contrato</label>
</RecordType>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/ItemContrato__c.object-meta.xml
<CustomObject>
    <label>Item de contrato</label>
    <nameField>
        <displayFormat>IT-{00000000}</displayFormat>
        <label>Número do item de contrato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens de contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/fields/NomeProduto__c.field-meta.xml
<CustomField>
    <fullName>NomeProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome do produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>ItensContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/fields/NumeroContrato__c.field-meta.xml
<CustomField>
    <fullName>NumeroContrato__c</fullName>
    <label>Número do contrato</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Itens de contrato (Número do contrato)</relationshipLabel>
    <relationshipName>ItensContrato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/fields/PrecoMinimo__c.field-meta.xml
<CustomField>
    <fullName>PrecoMinimo__c</fullName>
    <label>Preço compra</label>
    <precision>12</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/fields/PrecoUnitario__c.field-meta.xml
<CustomField>
    <fullName>PrecoUnitario__c</fullName>
    <label>Preço venda</label>
    <precision>12</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rascunho</fullName>
                <default>true</default>
                <label>Rascunho</label>
            </value>
            <value>
                <fullName>Em Aprovação</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
            <value>
                <fullName>Expirado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
            <value>
                <fullName>Aguardando integração</fullName>
            </value>
            <value>
                <fullName>Ativo</fullName>
                <isActive>false</isActive>
                <label>Ativo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/fields/VigenciaFinal__c.field-meta.xml
<CustomField>
    <fullName>VigenciaFinal__c</fullName>
    <label>Vigência final</label>
    <type>Date</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/fields/VigenciaInicial__c.field-meta.xml
<CustomField>
    <fullName>VigenciaInicial__c</fullName>
    <label>Vigência inicial</label>
    <type>Date</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/BatchContractUpload.cls
global class BatchContractUpload implements Database.Batchable<SObject>, Database.Stateful{
    global Map<String,Object> dataMap;
    global List<ItemContrato__c> contractToInsertList;
    global Set<String> productsName;
    global BatchContractUpload(Map<String,Object> dataMapPar){
        dataMap = dataMapPar;
        contractToInsertList = new List<ItemContrato__c>();
        productsName = new Set<String>();
    }
    global Database.QueryLocator start(Database.BatchableContext BC) {
        
        contractToInsertList = new List<ItemContrato__c>();
        productsName = new Set<String>();

        String jsonToUpload = (String)dataMap.get(ContractUploadConstants.JSON_STR);
        String jsonHeader = (String)dataMap.get(ContractUploadConstants.HEADER_LIST_STR);
        List<Configuration_Contract_Temp__mdt> headerList = (List<Configuration_Contract_Temp__mdt>) JSON.deserialize(jsonHeader, List<Configuration_Contract_Temp__mdt>.class);
        for(Configuration_Contract_Temp__mdt key: headerList){
            jsonToUpload = jsonToUpload.replace('"'+key.Field_Name_CSV__c+'"','"'+key.Field_Name_SF__c+'"');
        }
        contractToInsertList = (List<ItemContrato__c>) JSON.deserialize(jsonToUpload, List<ItemContrato__c>.class);

        Set<String> contractNumberList = new Set<String>();
        for(ItemContrato__c contract : contractToInsertList){
            contractNumberList.add(contract.NumeroContrato__c);
            productsName.add(contract.NomeProduto__c);
        }

        return Database.getQueryLocator('SELECT Id, ContractNumber FROM Contract WHERE ContractNumber IN :contractNumberList ');
    }
    global void execute(Database.BatchableContext BC, List<Contract> scope){
        Map<String,Contract> contractMap = new Map<String,Contract>();
        for(Contract contract : scope){
            contractMap.put(contract.ContractNumber,contract);
        }
        List<ItemContrato__c> itensToInsertList = new List<ItemContrato__c>();

        Map<String,ItemContrato__c> contractItemMap = new Map<String,ItemContrato__c>();
        for(ItemContrato__c contract : [SELECT Id, NomeProduto__c, NumeroContrato__c, NumeroContrato__r.ContractNumber, NomeProduto__r.ProductCode FROM ItemContrato__c WHERE NumeroContrato__c IN :scope]){
            contractItemMap.put(contract.NomeProduto__r.ProductCode+contract.NumeroContrato__r.ContractNumber,contract);
        }

        Map<String,Product2> prodtct2Map = new Map<String,Product2>();
        for(Product2 product : [SELECT Id, ProductCode FROM Product2 WHERE ProductCode IN :productsName]){
            prodtct2Map.put(product.ProductCode,product);
        }

        for(ItemContrato__c contract : contractToInsertList){
            if(contractMap.containsKey(contract.NumeroContrato__c)){
                Contract contractObj = contractMap.get(contract.NumeroContrato__c);
                String contractItemKey = contract.NomeProduto__c+contractObj.ContractNumber;

                ItemContrato__c newContractLineItem;
                if(contractItemMap.containsKey(contractItemKey)){
                    newContractLineItem = contractItemMap.get(contractItemKey);
                }else{
                    Product2 product = prodtct2Map.get(contract.NomeProduto__c);
                    newContractLineItem = new ItemContrato__c();
                    newContractLineItem.NomeProduto__c = product.Id;
                    newContractLineItem.NumeroContrato__c = contractObj.Id;
                    newContractLineItem.Status__c = 'Rascunho';
                }
                newContractLineItem.PrecoMinimo__c = contract.PrecoMinimo__c;
                newContractLineItem.PrecoUnitario__c = contract.PrecoUnitario__c;
                newContractLineItem.Quantidade__c = contract.Quantidade__c;                
                newContractLineItem.VigenciaFinal__c = contract.VigenciaFinal__c;
                newContractLineItem.VigenciaInicial__c = contract.VigenciaInicial__c;
    
                itensToInsertList.add(newContractLineItem);
            }
        }
        upsert itensToInsertList;
        
    }
    global void finish(Database.BatchableContext BC) {
        String body = 'Processado com sucesso. ';
        String subject = 'Items do contrato atualizados com sucesso';
        Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();

        email.setSubject( subject );
        email.setToAddresses( new String[] {UserInfo.getUserEmail()} );
        email.setPlainTextBody( body );
       
        Messaging.SendEmailResult [] r = Messaging.sendEmail(new Messaging.SingleEmailMessage[] {email});
    }
    
}