Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/ProdutoReserva__c.object-meta.xml
<CustomObject>
    <label>Produto da reserva</label>
    <nameField>
        <displayFormat>PR-{00000000}</displayFormat>
        <label>Nome de Produto da reserva</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Produtos da reserva</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/Reserva__c.field-meta.xml
<CustomField>
    <fullName>Reserva__c</fullName>
    <label>Reserva</label>
    <referenceTo>Reserva__c</referenceTo>
    <relationshipLabel>Produtos da reserva</relationshipLabel>
    <relationshipName>ProdutosReserva</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/StatusReserva__c.field-meta.xml
<CustomField>
    <fullName>StatusReserva__c</fullName>
    <label>Status da reserva</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando aprovação</fullName>
            </value>
            <value>
                <fullName>Ativa</fullName>
            </value>
            <value>
                <fullName>Rejeitada</fullName>
            </value>
            <value>
                <fullName>Aguardando integração</fullName>
            </value>
            <value>
                <fullName>Erro de integração</fullName>
            </value>
            <value>
                <fullName>Aguardando exclusão</fullName>
            </value>
            <value>
                <fullName>Expirada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Reserva__c/Reserva__c.object-meta.xml
<CustomObject>
    <label>Reserva</label>
    <nameField>
        <displayFormat>RE-{000000}</displayFormat>
        <label>Nome da reserva</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Reserva__c/fields/DiasVencimento__c.field-meta.xml
<CustomField>
    <fullName>DiasVencimento__c</fullName>
    <formula>ABS(

CASE(MOD (datevalue(InicioReserva__c)- DATE(1985,6,24),7),
0 , CASE( MOD( Datevalue( FimReserva__c) - datevalue(InicioReserva__c)
,7),1,2,2,3,3,4,4,5,5,5,6,5,1),
1 , CASE( MOD( Datevalue( FimReserva__c) - datevalue(InicioReserva__c)
,7),1,2,2,3,3,4,4,4,5,4,6,5,1),
2 , CASE( MOD( Datevalue( FimReserva__c) - datevalue(InicioReserva__c)
,7),1,2,2,3,3,3,4,3,5,4,6,5,1),
3 , CASE( MOD( Datevalue( FimReserva__c) - datevalue(InicioReserva__c)
,7),1,2,2,2,3,2,4,3,5,4,6,5,1),
4 , CASE( MOD( Datevalue( FimReserva__c) - datevalue(InicioReserva__c)
,7),1,1,2,1,3,2,4,3,5,4,6,5,1),
5 , CASE( MOD( Datevalue( FimReserva__c) - datevalue(InicioReserva__c)
,7),1,0,2,1,3,2,4,3,5,4,6,5,0),
6 , CASE( MOD( Datevalue( FimReserva__c) - datevalue(InicioReserva__c)
,7),1,1,2,2,3,3,4,4,5,5,6,5,0),999)
+
(FLOOR((( FimReserva__c) - ( InicioReserva__c) )/7)*5)-1 +
( FimReserva__c - InicioReserva__c) - (datevalue( FimReserva__c) -
datevalue(InicioReserva__c))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dias para vencimento</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Reserva__c/fields/DiasVencimentoUltimaMovimentacao__c.field-meta.xml
<CustomField>
    <fullName>DiasVencimentoUltimaMovimentacao__c</fullName>
    <formula>ABS(

				CASE(MOD (datevalue(DataUltimaMovimentacao__c)- DATE(1985,6,24),7),
									0 , CASE( MOD( Datevalue( FimReserva__c) - datevalue(DataUltimaMovimentacao__c)
																							,7),1,2,2,3,3,4,4,5,5,5,6,5,1),
									1 , CASE( MOD( Datevalue( FimReserva__c) - datevalue(DataUltimaMovimentacao__c)
																							,7),1,2,2,3,3,4,4,4,5,4,6,5,1),
									2 , CASE( MOD( Datevalue( FimReserva__c) - datevalue(DataUltimaMovimentacao__c)
																							,7),1,2,2,3,3,3,4,3,5,4,6,5,1),
									3 , CASE( MOD( Datevalue( FimReserva__c) - datevalue(DataUltimaMovimentacao__c)
																							,7),1,2,2,2,3,2,4,3,5,4,6,5,1),
									4 , CASE( MOD( Datevalue( FimReserva__c) - datevalue(DataUltimaMovimentacao__c)
																							,7),1,1,2,1,3,2,4,3,5,4,6,5,1),
									5 , CASE( MOD( Datevalue( FimReserva__c) - datevalue(DataUltimaMovimentacao__c)
																							,7),1,0,2,1,3,2,4,3,5,4,6,5,0),
									6 , CASE( MOD( Datevalue( FimReserva__c) - datevalue(DataUltimaMovimentacao__c)
																							,7),1,1,2,2,3,3,4,4,5,5,6,5,0),999)
				+
				(FLOOR((( FimReserva__c) - ( DataUltimaMovimentacao__c) )/7)*5)-1 +
				( FimReserva__c - DataUltimaMovimentacao__c) - (datevalue( FimReserva__c) - 
																																											datevalue(DataUltimaMovimentacao__c))
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Dias para vencimento última movimentação</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Reserva__c/fields/StatusReserva__c.field-meta.xml
<CustomField>
    <fullName>StatusReserva__c</fullName>
    <label>Status da reserva</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativa</fullName>
                <default>true</default>
                <label>Ativa</label>
            </value>
            <value>
                <fullName>Expirada</fullName>
            </value>
            <value>
                <fullName>Aguardando aprovação</fullName>
                <isActive>false</isActive>
                <label>Aguardando aprovação</label>
            </value>
            <value>
                <fullName>Aguardando envio de exclusão</fullName>
                <isActive>false</isActive>
                <label>Aguardando envio de exclusão</label>
            </value>
            <value>
                <fullName>Aguardando integração</fullName>
                <isActive>false</isActive>
                <label>Aguardando integração</label>
            </value>
            <value>
                <fullName>Aprovada</fullName>
                <isActive>false</isActive>
                <label>Aprovada</label>
            </value>
            <value>
                <fullName>Cancelada</fullName>
                <isActive>false</isActive>
                <label>Cancelada</label>
            </value>
            <value>
                <fullName>Em digitação</fullName>
                <isActive>false</isActive>
                <label>Em digitação</label>
            </value>
            <value>
                <fullName>Erro de integração</fullName>
                <isActive>false</isActive>
                <label>Erro de integração</label>
            </value>
            <value>
                <fullName>Integrado</fullName>
                <isActive>false</isActive>
                <label>Integrado</label>
            </value>
            <value>
                <fullName>Rejeitada</fullName>
                <isActive>false</isActive>
                <label>Rejeitada</label>
            </value>
            <value>
                <fullName>Vencida</fullName>
                <isActive>false</isActive>
                <label>Vencida</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/classes/BatchSendNotificationReservation.cls
global class BatchSendNotificationReservation implements Database.Batchable<sObject>, Database.Stateful{

    
    global Database.QueryLocator start(Database.BatchableContext BC) {

        System.debug('entrou no batch');
        return Database.getQueryLocator(
                                            [
                                                SELECT Id, Name,DiasVencimentoUltimaMovimentacao__c, DiasVencimento__c, (SELECT Id, CreatedById FROM ProdutosReserva__r ) 
                                                FROM Reserva__c 
                                                WHERE (DiasVencimento__c = 7 OR DiasVencimentoUltimaMovimentacao__c = 52) 
                                                AND StatusReserva__c != 'Expirada'
                                            ]
                                        );
    }

    global void execute(Database.BatchableContext BC, List<Reserva__c> scope) {

        System.debug(scope);
        CustomNotificationType notificationType = [SELECT Id, DeveloperName FROM CustomNotificationType WHERE DeveloperName = 'NotificationPendingOrder'];
        Set<String> recipientsIds = new Set<String>();
        Messaging.CustomNotification notification = new Messaging.CustomNotification();
        List<Reserva__c> lstUpdateVencido = new List<Reserva__c>();
        
        for (Reserva__c reserva : scope) {

            if (reserva.ProdutosReserva__r.size() > 0 ) {
                
                for (ProdutoReserva__c produtoReserva : reserva.ProdutosReserva__r) {

                    if (!recipientsIds.contains(produtoReserva.CreatedById)) {

                        try {

                            if (reserva.DiasVencimento__c == 7 || reserva.DiasVencimentoUltimaMovimentacao__c == 52) {
            
                                notification = new Messaging.CustomNotification();
            
                                notification.setTitle('Vencimento da reserva!');
                                notification.setBody('Reserva '+reserva.Name+ ' está próxima do vencimento!');
                    
                                notification.setNotificationTypeId(notificationType.Id);
                                notification.setTargetId(reserva.Id);
                    
                                recipientsIds.add(produtoReserva.CreatedById);
                                System.debug(recipientsIds);
                                notification.send(recipientsIds);
            
                            } 

                        } catch (Exception e) {
                            System.debug(e.getMessage());
                        }                        
                    }                    
                }
            }           
        }        
    }

    global void finish(Database.BatchableContext BC) {}
}