Git Tests/force-app/main/default/default/objects/Contract/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <formula>Account.CNPJ__c</formula>
    <label>CNPJ</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Contract/fields/CodigoCliente__c.field-meta.xml
<CustomField>
    <fullName>CodigoCliente__c</fullName>
    <formula>Account.CodigoCliente__c</formula>
    <label>Código do cliente</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Contract/fields/CodigoLoja__c.field-meta.xml
<CustomField>
    <fullName>CodigoLoja__c</fullName>
    <formula>Account.CodigoCliente__c + &apos;/&apos; + Account.LojaCliente__c</formula>
    <label>Código/Loja</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Contract/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fornecedor</label>
    <referenceTo>Fornecedor__c</referenceTo>
    <relationshipLabel>Contratos</relationshipLabel>
    <relationshipName>Contratos</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Contract/fields/LojaCliente__c.field-meta.xml
<CustomField>
    <fullName>LojaCliente__c</fullName>
    <formula>Account.LojaCliente__c</formula>
    <label>Loja do cliente</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Contract/fields/TipoRegra__c.field-meta.xml
<CustomField>
    <fullName>TipoRegra__c</fullName>
    <label>Tipo da regra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Acordo comercial</label>
            </value>
            <value>
                <fullName>O</fullName>
                <label>Operação logística (OL)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Fornecedor__c/Fornecedor__c.object-meta.xml
<CustomObject>
    <label>Fornecedor</label>
    <nameField>
        <label>Nome do fornecedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fornecedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Fornecedor__c/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/ItemContrato__c.object-meta.xml
<CustomObject>
    <label>Item de contrato</label>
    <nameField>
        <displayFormat>IT-{00000000}</displayFormat>
        <label>Número do item de contrato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens de contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <formula>CASESAFEID(NumeroContrato__r.AccountId)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>ID do cliente</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/fields/CodigoProduto__c.field-meta.xml
<CustomField>
    <fullName>CodigoProduto__c</fullName>
    <formula>NomeProduto__r.ProductCode</formula>
    <label>Código do produto</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <formula>NomeProduto__r.Fornecedor__r.Name</formula>
    <label>Fornecedor</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/fields/Margem__c.field-meta.xml
<CustomField>
    <fullName>Margem__c</fullName>
    <label>Margem (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/fields/NomeProduto__c.field-meta.xml
<CustomField>
    <fullName>NomeProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome do produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>ItensContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/fields/NumeroContrato__c.field-meta.xml
<CustomField>
    <fullName>NumeroContrato__c</fullName>
    <label>Número do contrato</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Itens de contrato (Número do contrato)</relationshipLabel>
    <relationshipName>ItensContrato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/fields/PercentualDescontoBoleto__c.field-meta.xml
<CustomField>
    <fullName>PercentualDescontoBoleto__c</fullName>
    <label>% desconto no boleto</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/fields/PrecoMinimo__c.field-meta.xml
<CustomField>
    <fullName>PrecoMinimo__c</fullName>
    <label>Preço compra</label>
    <precision>12</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/fields/PrecoUnitario__c.field-meta.xml
<CustomField>
    <fullName>PrecoUnitario__c</fullName>
    <label>Preço venda</label>
    <precision>12</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/fields/PrincipioAtivoProduto__c.field-meta.xml
<CustomField>
    <fullName>PrincipioAtivoProduto__c</fullName>
    <formula>NomeProduto__r.Description</formula>
    <label>Princípio ativo do produto</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rascunho</fullName>
                <default>true</default>
                <label>Rascunho</label>
            </value>
            <value>
                <fullName>Em Aprovação</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
            <value>
                <fullName>Expirado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
            <value>
                <fullName>Aguardando integração</fullName>
            </value>
            <value>
                <fullName>Ativo</fullName>
                <isActive>false</isActive>
                <label>Ativo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/fields/ValidadeLote__c.field-meta.xml
<CustomField>
    <fullName>ValidadeLote__c</fullName>
    <label>Validade do lote</label>
    <type>Date</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/fields/VigenciaFinal__c.field-meta.xml
<CustomField>
    <fullName>VigenciaFinal__c</fullName>
    <label>Vigência final</label>
    <type>Date</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/fields/VigenciaInicial__c.field-meta.xml
<CustomField>
    <fullName>VigenciaInicial__c</fullName>
    <label>Vigência inicial</label>
    <type>Date</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/CloneContract.cls
public without sharing class CloneContract {

    @InvocableMethod(label='Clone Contract' 
                    description='Button to clone the contract and its items')
    public static List<String> flowCloneContract(List<FlowInputs> flowInputs) {
        Id contractId = null;
        Id accountId = null;
        Date vigenciaInicial = null;
        Date vigenciaFinal = null;
        for (FlowInputs flowInput : flowInputs) {
            contractId = flowInput.contractId;
            accountId = flowInput.accountId;
            vigenciaInicial = flowInput.vigenciaInicial;
            vigenciaFinal = flowInput.vigenciaFinal;
        }

        Contract contextContract = null;
        for (Contract o : [SELECT Id, AccountId, CNPJ__c, CodigoCliente__c, CodigoLoja__c, LojaCliente__c, RecordTypeId, TipoRegra__c
                           FROM Contract WHERE Id = :contractId]) {
            
            contextContract = o;
        }
        Contract newContract = new Contract();
        if (contextContract != null) {
            newContract.Status                      = 'Rascunho';
            newContract.AccountId                   = accountId;
            newContract.RecordTypeId                = contextContract.RecordTypeId;
            newContract.TipoRegra__c                = contextContract.TipoRegra__c;

            try {
                insert newContract;
            } catch (DmlException de) {
                throw new ContractException(de.getDmlMessage(0));
            }
            

            List<ItemContrato__c> newContractLineItemList = new List<ItemContrato__c>();

            for (ItemContrato__c oLineItem : [SELECT Id, AccountId__c, CodigoProduto__c, Fornecedor__c, Lote__c, Margem__c, NomeProduto__c, NumeroContrato__c, PrecoMinimo__c, 
                                                PrecoUnitario__c, PrincipioAtivoProduto__c, Quantidade__c, Status__c, ValidadeLote__c, VigenciaFinal__c, VigenciaInicial__c, PercentualDescontoBoleto__c  
                                             FROM ItemContrato__c WHERE NumeroContrato__c = :contextContract.Id]) {
            
            ItemContrato__c newContractLineItem = new ItemContrato__c();
            newContractLineItem.Lote__c                     = oLineItem.Lote__c;
            newContractLineItem.Margem__c                   = oLineItem.Margem__c;
            newContractLineItem.NomeProduto__c              = oLineItem.NomeProduto__c;
            newContractLineItem.NumeroContrato__c           = newContract.Id;
            newContractLineItem.PrecoMinimo__c              = oLineItem.PrecoMinimo__c;
            newContractLineItem.PrecoUnitario__c            = oLineItem.PrecoUnitario__c;
            newContractLineItem.Quantidade__c               = oLineItem.Quantidade__c;
            newContractLineItem.Status__c                   = 'Rascunho';
            newContractLineItem.ValidadeLote__c             = oLineItem.ValidadeLote__c;
            newContractLineItem.VigenciaFinal__c            = vigenciaFinal;
            newContractLineItem.VigenciaInicial__c          = vigenciaInicial;
            newContractLineItem.PercentualDescontoBoleto__c = oLineItem.PercentualDescontoBoleto__c;

            newContractLineItemList.add(newContractLineItem);
            }

            if (!newContractLineItemList.isEmpty()){
                insert newContractLineItemList;
            }
        }

        return new List<String>{newContract.Id};
    }

    public class FlowInputs{

        @InvocableVariable
        public String contractId;
        
        @InvocableVariable
        public String accountId;
        
        @InvocableVariable
        public Date vigenciaInicial;
        
        @InvocableVariable
        public Date vigenciaFinal;
    }

    public class ContractException extends Exception {}
}