Git Tests/force-app/main/default/default/objects/ItemContrato__c/ItemContrato__c.object-meta.xml
<CustomObject>
    <label>Item de contrato</label>
    <nameField>
        <displayFormat>IT-{00000000}</displayFormat>
        <label>Número do item de contrato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens de contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rascunho</fullName>
                <default>true</default>
                <label>Rascunho</label>
            </value>
            <value>
                <fullName>Em Aprovação</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
            <value>
                <fullName>Expirado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
            <value>
                <fullName>Aguardando integração</fullName>
            </value>
            <value>
                <fullName>Ativo</fullName>
                <isActive>false</isActive>
                <label>Ativo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/fields/VigenciaFinal__c.field-meta.xml
<CustomField>
    <fullName>VigenciaFinal__c</fullName>
    <label>Vigência final</label>
    <type>Date</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/BatchExpiredContractItem.cls
global class BatchExpiredContractItem implements Database.Batchable<sObject>, Database.Stateful{
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([
            SELECT 
                Id, 
                VigenciaFinal__c
            FROM ItemContrato__c
            WHERE VigenciaFinal__c < TODAY
            AND Status__c != 'Expirado'
        ]);
    }

    global void execute(Database.BatchableContext BC, List<ItemContrato__c> scope) {
        List<ItemContrato__c> contractItemList = new List<ItemContrato__c>();
        for (ItemContrato__c contractItem : scope) {
            contractItemList.add(new ItemContrato__c(Id = contractItem.Id, Status__c = 'Expirado'));
        }
        if(!contractItemList.isEmpty()) {
            ContractHandler.disableTrigger();
            ContractItemHandler.disableTrigger();
            update contractItemList;
            ContractHandler.enableTrigger();
            ContractItemHandler.enableTrigger();
        }
    }

    global void finish(Database.BatchableContext BC) {}
}