Git Tests/force-app/main/default/default/objects/Setorizacao__c/Setorizacao__c.object-meta.xml
<CustomObject>
    <label>Setorização</label>
    <nameField>
        <displayFormat>SET-{000000}</displayFormat>
        <label>Número da setorização</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setorizações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/DataFinal__c.field-meta.xml
<CustomField>
    <fullName>DataFinal__c</fullName>
    <label>Data final</label>
    <type>Date</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/BatchSectorization.cls
global class BatchSectorization implements Database.Batchable<sObject>, Database.Stateful {

    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([SELECT Id FROM Setorizacao__c WHERE DataFinal__c < TODAY]);
    }
    
    global void execute(Database.BatchableContext BC, List<SObject> scope) {        
        List<Setorizacao__c> listSetorizacao = (List<Setorizacao__c>) scope;
        delete listSetorizacao;

    }

    global void finish(Database.BatchableContext BC) {}
}