Git Tests/force-app/main/default/default/objects/ProcessActingTable__e/ProcessActingTable__e.object-meta.xml
<CustomObject>
    <label>ProcessActingTable</label>
    <pluralLabel>ProcessActingTables</pluralLabel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ProcessActingTable__e/fields/ExecuteNextProcesses__c.field-meta.xml
<CustomField>
    <fullName>ExecuteNextProcesses__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ExecuteNextProcesses</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProcessActingTable__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo de processo</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/Setorizacao__c.object-meta.xml
<CustomObject>
    <label>Setorização</label>
    <nameField>
        <displayFormat>SET-{000000}</displayFormat>
        <label>Número da setorização</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setorizações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>BU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>G</fullName>
                <label>GENÉRICO</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>MATERIAIS</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>NUTRIÇÃO</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Medctech</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>SPECIALTY</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>AMBOS</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>DIABETES</label>
            </value>
            <value>
                <fullName>Q</fullName>
                <label>ODONTOLOGIA</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <label>EQUIPAMENTO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/CodigoMesa__c.field-meta.xml
<CustomField>
    <fullName>CodigoMesa__c</fullName>
    <externalId>true</externalId>
    <label>Código da mesa</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome do cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Setorização</relationshipLabel>
    <relationshipName>Setorizacao</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Regiao__c.field-meta.xml
<CustomField>
    <fullName>Regiao__c</fullName>
    <label>Região</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Territory2/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <externalId>true</externalId>
    <label>Categoria</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Territory2/fields/CodigoMesa__c.field-meta.xml
<CustomField>
    <fullName>CodigoMesa__c</fullName>
    <externalId>true</externalId>
    <label>Código da mesa</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Territory2/fields/Regiao__c.field-meta.xml
<CustomField>
    <fullName>Regiao__c</fullName>
    <externalId>true</externalId>
    <label>Região</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/BatchAssociateAccountsInActingTables.cls
public with sharing class BatchAssociateAccountsInActingTables implements Database.Batchable<SObject> {
    public Boolean callNextProcess = false;
    
    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([
            SELECT
                Id,
                Conta__c,
                CodigoMesa__c,
                Categoria__c,
                Regiao__c
            FROM Setorizacao__c WHERE CodigoMesa__c != null AND Regiao__c != null AND Categoria__c != null
        ]);
    }

    public void execute(Database.BatchableContext BC, List<Setorizacao__c> scope) {
        // check if association x territory already exists.
        Set<String> scopeAccAlreadyAssociate = new Set<String>();
        Set<Id> setAccIdsToCheckInExistingAssociations = new Set<Id>();

        Map<Id, Set<Id>> mapAccIdToUserSetId = new Map<Id, Set<Id>>();

        for (Setorizacao__c sectorization : scope) {
            if (sectorization.Conta__c != null) {
                setAccIdsToCheckInExistingAssociations.add(sectorization.Conta__c);
            }
        }
        
        List<ObjectTerritory2Association> existingAssociationsList = ActingTableTerritoryManagement.getAllObjectAssociationsByAccountIds(setAccIdsToCheckInExistingAssociations);
        
        for (ObjectTerritory2Association existingAssociation : existingAssociationsList) {
            String customKey = 
                existingAssociation.Territory2.DeveloperName + 
                existingAssociation.ObjectId;

            if (!scopeAccAlreadyAssociate.contains(customKey)) {
                scopeAccAlreadyAssociate.add(customKey);
            }
        }

        List<ObjectTerritory2Association> AccountsToAssociate = new List<ObjectTerritory2Association>();
        
        Map<String, Territory2> allTerritoriesDeveloperNameMap = ActingTableTerritoryManagement.getAllTerritoriesDeveloperNameMap();

        for (Setorizacao__c sectorization : scope) {
            String developerNameKey = ActingTableTerritoryManagement.getDeveloperNameKey(sectorization, true);
            Territory2 territoryForAssociation;

            if (!allTerritoriesDeveloperNameMap.containsKey(developerNameKey)) {
                continue;
            } else {
                territoryForAssociation = allTerritoriesDeveloperNameMap.get(developerNameKey);
            }

            if (!scopeAccAlreadyAssociate.contains(developerNameKey+sectorization.Conta__c)) {
                AccountsToAssociate.add(
                    ActingTableTerritoryManagement.createAccountAssociationForActingTableTerritory(
                        territoryForAssociation,
                        sectorization.Conta__c
                    )
                );
                scopeAccAlreadyAssociate.add(developerNameKey+sectorization.Conta__c);
            }
        }

        if (AccountsToAssociate.size() > 0) {
            insert AccountsToAssociate;
        }
    }

    public void finish(Database.BatchableContext BC) {
        if (callNextProcess) {
            Eventbus.publish(new ProcessActingTable__e(
                Type__c = 'delete_associate_users',
                ExecuteNextProcesses__c = true
            ));
        }
    }
}