Git Tests/force-app/main/default/default/objects/ProcessActingTable__e/ProcessActingTable__e.object-meta.xml
<CustomObject>
    <label>ProcessActingTable</label>
    <pluralLabel>ProcessActingTables</pluralLabel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ProcessActingTable__e/fields/ExecuteNextProcesses__c.field-meta.xml
<CustomField>
    <fullName>ExecuteNextProcesses__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ExecuteNextProcesses</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProcessActingTable__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo de processo</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/ProcessActingTableHelperTest.cls
@isTest
public with sharing class ProcessActingTableHelperTest {

    @isTest
    public static void ProcessActingTableHelperTest() {
        ProcessActingTable__e pCreateTerritory = new ProcessActingTable__e(
            Type__c = 'create_territory',
            ExecuteNextProcesses__c = false
        );

        Test.startTest();
        Database.SaveResult sr = EventBus.publish(pCreateTerritory);
        Test.stopTest();
    }
    @isTest
    public static void ProcessAssociateAccTest() {
        ProcessActingTable__e pAssociateAcc = new ProcessActingTable__e(
            Type__c = 'associate_accounts',
            ExecuteNextProcesses__c = false
        );

        Test.startTest();
        Database.SaveResult sr = EventBus.publish(pAssociateAcc);
        Test.stopTest();
    }
    @isTest
    public static void ProcessDelAssociateUsersTest() {
        ProcessActingTable__e pDelAssociateUsers = new ProcessActingTable__e(
            Type__c = 'delete_associate_users',
            ExecuteNextProcesses__c = false
        );

        Test.startTest();
        Database.SaveResult sr = EventBus.publish(pDelAssociateUsers);
        Test.stopTest();
    }
    @isTest
    public static void ProcessAssociateUsersTest() {
        ProcessActingTable__e pAssociateUsers = new ProcessActingTable__e(
            Type__c = 'associate_users',
            ExecuteNextProcesses__c = false
        );

        Test.startTest();
        Database.SaveResult sr = EventBus.publish(pAssociateUsers);
        Test.stopTest();
    }
    @isTest
    public static void ProcessAssociateUsersWithoutATTest() {
        ProcessActingTable__e pAssociateUsersWithoutAT = new ProcessActingTable__e(
            Type__c = 'associate_users_without_acting_table',
            ExecuteNextProcesses__c = false
        );

        Test.startTest();
        Database.SaveResult sr = EventBus.publish(pAssociateUsersWithoutAT);
        Test.stopTest();
    }
    @isTest
    public static void ProcessAssociateUsersWithoutSTTest() {
        ProcessActingTable__e pAssociateUsersWithoutST = new ProcessActingTable__e(
            Type__c = 'associate_account_without_setorizacao',
            ExecuteNextProcesses__c = false
        );

        Test.startTest();
        Database.SaveResult sr = EventBus.publish(pAssociateUsersWithoutST);
        Test.stopTest();
    }
    @isTest
    public static void ProcessRevalidateApprovalAssTest() {
        ProcessActingTable__e pRevalidateApprovalAss = new ProcessActingTable__e(
            Type__c = 'revalidate_approval_associations',
            ExecuteNextProcesses__c = false
        );

        Test.startTest();
        Database.SaveResult sr = EventBus.publish(pRevalidateApprovalAss);
        Test.stopTest();
    }
    @isTest
    public static void ProcessNoTypeTest() {
        ProcessActingTable__e pNoType = new ProcessActingTable__e(
            Type__c = '',
            ExecuteNextProcesses__c = false
        );

        Test.startTest();
        Database.SaveResult sr = EventBus.publish(pNoType);
        Test.stopTest();
    }
}