Git Tests/force-app/main/default/default/objects/ProcessActingTable__e/ProcessActingTable__e.object-meta.xml
<CustomObject>
    <label>ProcessActingTable</label>
    <pluralLabel>ProcessActingTables</pluralLabel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ProcessActingTable__e/fields/ExecuteNextProcesses__c.field-meta.xml
<CustomField>
    <fullName>ExecuteNextProcesses__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ExecuteNextProcesses</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProcessActingTable__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo de processo</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/Setorizacao__c.object-meta.xml
<CustomObject>
    <label>Setorização</label>
    <nameField>
        <displayFormat>SET-{000000}</displayFormat>
        <label>Número da setorização</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setorizações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>BU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>G</fullName>
                <label>GENÉRICO</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>MATERIAIS</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>NUTRIÇÃO</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Medctech</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>SPECIALTY</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>AMBOS</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>DIABETES</label>
            </value>
            <value>
                <fullName>Q</fullName>
                <label>ODONTOLOGIA</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <label>EQUIPAMENTO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/CodigoMesa__c.field-meta.xml
<CustomField>
    <fullName>CodigoMesa__c</fullName>
    <externalId>true</externalId>
    <label>Código da mesa</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Coordenador__c.field-meta.xml
<CustomField>
    <fullName>Coordenador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coordenador</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SetorizacoesCoordenador</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/DataFinal__c.field-meta.xml
<CustomField>
    <fullName>DataFinal__c</fullName>
    <label>Data final</label>
    <type>Date</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Gerente__c.field-meta.xml
<CustomField>
    <fullName>Gerente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gerente externo</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Setor</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Regiao__c.field-meta.xml
<CustomField>
    <fullName>Regiao__c</fullName>
    <label>Região</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VDE</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Setorizacao</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/VendedorSuporte__c.field-meta.xml
<CustomField>
    <fullName>VendedorSuporte__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VDI</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SetorizacoesVendedor</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Territory2/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <externalId>true</externalId>
    <label>Categoria</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Territory2/fields/CodigoMesa__c.field-meta.xml
<CustomField>
    <fullName>CodigoMesa__c</fullName>
    <externalId>true</externalId>
    <label>Código da mesa</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Territory2/fields/Regiao__c.field-meta.xml
<CustomField>
    <fullName>Regiao__c</fullName>
    <externalId>true</externalId>
    <label>Região</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/BatchAssociateUsersInActingTables.cls
public with sharing class BatchAssociateUsersInActingTables implements Database.Batchable<SObject> {
    public Boolean callNextProcess = false;

    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([
            SELECT
                Id,
                CodigoMesa__c,
                Categoria__c,
                Regiao__c,
                Vendedor__c,
                Vendedor__r.IsActive,
                VendedorSuporte__c,
                VendedorSuporte__r.IsActive,
                Gerente__c,
                Gerente__r.IsActive,
                Coordenador__c,
                Coordenador__r.IsActive
            FROM Setorizacao__c
            WHERE CodigoMesa__c != NULL
            AND DataFinal__c >: System.Today()
        ]);
    }

    public void execute(Database.BatchableContext BC, List<Setorizacao__c> scope) {
        
        // check if association x territory already exists.
        Set<String> scopeUsersAlreadyAddedInTerritory = new Set<String>();
        Set<Id> userIdsToCheckInExistingAssociations = new Set<Id>();

        for (Setorizacao__c sectorization : scope) {
            if (sectorization.Vendedor__c != null && sectorization.Vendedor__r.IsActive) {
                userIdsToCheckInExistingAssociations.add(sectorization.Vendedor__c);
            }

            if (sectorization.VendedorSuporte__c != null && sectorization.VendedorSuporte__r.IsActive) {
                userIdsToCheckInExistingAssociations.add(sectorization.VendedorSuporte__c);
            }

            if (sectorization.Gerente__c != null && sectorization.Gerente__r.IsActive) {
                userIdsToCheckInExistingAssociations.add(sectorization.Gerente__c);
            }

            if (sectorization.Coordenador__c != null && sectorization.Coordenador__r.IsActive) {
                userIdsToCheckInExistingAssociations.add(sectorization.Coordenador__c);
            }
        }
        
        List<UserTerritory2Association> existingAssociationsList = 
            ActingTableTerritoryManagement.getAllUsersAssociationsByUserIds(userIdsToCheckInExistingAssociations);
        
        for (UserTerritory2Association existingAssociation : existingAssociationsList) {
            String customKey = 
                existingAssociation.Territory2.DeveloperName + 
                existingAssociation.UserId;

            if (!scopeUsersAlreadyAddedInTerritory.contains(customKey)) {
                scopeUsersAlreadyAddedInTerritory.add(customKey);
            }
        }

        List<UserTerritory2Association> usersToAssociate = new List<UserTerritory2Association>();
        
        Map<String, Territory2> allTerritoriesDeveloperNameMap = 
            ActingTableTerritoryManagement.getAllTerritoriesDeveloperNameMap();

        // primeira etapa, assumindo que temos a chave completa (Mesa, Categoria, Regiao)        
        for (Setorizacao__c sectorization : scope) {
            String developerNameKey = ActingTableTerritoryManagement.getDeveloperNameKey(sectorization, true);
            Territory2 territoryForAssociation;

            if (!allTerritoriesDeveloperNameMap.containsKey(developerNameKey)) {
                continue;
            } else {
                territoryForAssociation = allTerritoriesDeveloperNameMap.get(developerNameKey);
            }

            if (
                sectorization.Vendedor__r.IsActive &&
                !scopeUsersAlreadyAddedInTerritory.contains(developerNameKey+sectorization.Vendedor__c)
            ) {
                usersToAssociate.add(
                    ActingTableTerritoryManagement.createUserAssociationForActingTableTerritory(
                        territoryForAssociation,
                        sectorization.Vendedor__c,
                        'Vendedor'
                    )
                );
                scopeUsersAlreadyAddedInTerritory.add(developerNameKey+sectorization.Vendedor__c);
            }

            if (
                sectorization.VendedorSuporte__r.IsActive &&
                !scopeUsersAlreadyAddedInTerritory.contains(developerNameKey+sectorization.VendedorSuporte__c)
            ) {
                usersToAssociate.add(
                    ActingTableTerritoryManagement.createUserAssociationForActingTableTerritory(
                        territoryForAssociation,
                        sectorization.VendedorSuporte__c,
                        'Vendedor Suporte'
                    )
                );
                scopeUsersAlreadyAddedInTerritory.add(developerNameKey+sectorization.VendedorSuporte__c);
            }

            if (
                sectorization.Gerente__r.IsActive &&
                !scopeUsersAlreadyAddedInTerritory.contains(developerNameKey+sectorization.Gerente__c)
            ) {
                usersToAssociate.add(
                    ActingTableTerritoryManagement.createUserAssociationForActingTableTerritory(
                        territoryForAssociation,
                        sectorization.Gerente__c,
                        'Gerente'
                    )
                );
                scopeUsersAlreadyAddedInTerritory.add(developerNameKey+sectorization.Gerente__c);
            }

            if (
                sectorization.Coordenador__r.IsActive &&
                !scopeUsersAlreadyAddedInTerritory.contains(developerNameKey+sectorization.Coordenador__c)
            ) {
                usersToAssociate.add(
                    ActingTableTerritoryManagement.createUserAssociationForActingTableTerritory(
                        territoryForAssociation,
                        sectorization.Coordenador__c,
                        'Coordenador'
                    )
                );
                scopeUsersAlreadyAddedInTerritory.add(developerNameKey+sectorization.Coordenador__c);
            }
        }

        System.debug(usersToAssociate.size());
        if (usersToAssociate.size() > 0) {
            System.debug(usersToAssociate);
            Database.insert(usersToAssociate, false);
        }
    }

    public void finish(Database.BatchableContext BC) {
        if (callNextProcess) {
            Eventbus.publish(new ProcessActingTable__e(
                Type__c = 'associate_users_without_acting_table',
                ExecuteNextProcesses__c = true
            ));
        }
    }
}