Git Tests/force-app/main/default/default/objects/ProcessActingTable__e/ProcessActingTable__e.object-meta.xml
<CustomObject>
    <label>ProcessActingTable</label>
    <pluralLabel>ProcessActingTables</pluralLabel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ProcessActingTable__e/fields/ExecuteNextProcesses__c.field-meta.xml
<CustomField>
    <fullName>ExecuteNextProcesses__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ExecuteNextProcesses</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProcessActingTable__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo de processo</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/Setorizacao__c.object-meta.xml
<CustomObject>
    <label>Setorização</label>
    <nameField>
        <displayFormat>SET-{000000}</displayFormat>
        <label>Número da setorização</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setorizações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>BU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>G</fullName>
                <label>GENÉRICO</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>MATERIAIS</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>NUTRIÇÃO</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Medctech</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>SPECIALTY</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>AMBOS</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>DIABETES</label>
            </value>
            <value>
                <fullName>Q</fullName>
                <label>ODONTOLOGIA</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <label>EQUIPAMENTO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/CodigoMesa__c.field-meta.xml
<CustomField>
    <fullName>CodigoMesa__c</fullName>
    <externalId>true</externalId>
    <label>Código da mesa</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Coordenador__c.field-meta.xml
<CustomField>
    <fullName>Coordenador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Coordenador</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SetorizacoesCoordenador</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Gerente__c.field-meta.xml
<CustomField>
    <fullName>Gerente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gerente externo</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Setor</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Regiao__c.field-meta.xml
<CustomField>
    <fullName>Regiao__c</fullName>
    <label>Região</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VDE</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Setorizacao</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/VendedorSuporte__c.field-meta.xml
<CustomField>
    <fullName>VendedorSuporte__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VDI</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SetorizacoesVendedor</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Territory2/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <externalId>true</externalId>
    <label>Categoria</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Territory2/fields/CodigoMesa__c.field-meta.xml
<CustomField>
    <fullName>CodigoMesa__c</fullName>
    <externalId>true</externalId>
    <label>Código da mesa</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Territory2/fields/Regiao__c.field-meta.xml
<CustomField>
    <fullName>Regiao__c</fullName>
    <externalId>true</externalId>
    <label>Região</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/BatchAssociateUsersWithoutActingTables.cls
public with sharing class BatchAssociateUsersWithoutActingTables implements Database.Batchable<SObject> {
    public Boolean callNextProcess = false;
    
    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([
            SELECT
                Id,
                CodigoMesa__c,
                Categoria__c,
                Regiao__c,
                Vendedor__c,
                Vendedor__r.IsActive,
                VendedorSuporte__c,
                VendedorSuporte__r.IsActive,
                Gerente__c,
                Gerente__r.IsActive,
                Coordenador__c,
                Coordenador__r.IsActive
            FROM Setorizacao__c
            WHERE CodigoMesa__c = NULL
        ]);
    }

    public void execute(Database.BatchableContext BC, List<Setorizacao__c> scope) {
        // identificar usuarios do escopo
        Set<Id> userIdsToCheckInExistingAssociations = new Set<Id>();

        for (Setorizacao__c sectorization : scope) {if (sectorization.Vendedor__c != null && sectorization.Vendedor__r.IsActive) {userIdsToCheckInExistingAssociations.add(sectorization.Vendedor__c);}if (sectorization.VendedorSuporte__c != null && sectorization.VendedorSuporte__r.IsActive) {userIdsToCheckInExistingAssociations.add(sectorization.VendedorSuporte__c);}if (sectorization.Gerente__c != null && sectorization.Gerente__r.IsActive) {userIdsToCheckInExistingAssociations.add(sectorization.Gerente__c);}if (sectorization.Coordenador__c != null && sectorization.Coordenador__r.IsActive) {userIdsToCheckInExistingAssociations.add(sectorization.Coordenador__c);}}
        // buscar associações existentes
        List<UserTerritory2Association> existingAssociationsList = 
        ActingTableTerritoryManagement.getAllUsersAssociationsByUserIds(userIdsToCheckInExistingAssociations);
        
        // criar mapa de { DEVELOPERNAME_TERRI => Set<Id> userIds } (mapTerritoriesWithUsers)
        Map<String, Set<Id>> mapTerritoryToUserIds = new Map<String, Set<Id>>();
        for (UserTerritory2Association association : existingAssociationsList) {
            if (!mapTerritoryToUserIds.containsKey(association.Territory2.DeveloperName)) {mapTerritoryToUserIds.put(association.Territory2.DeveloperName,new Set<Id>());}
            mapTerritoryToUserIds.get(association.Territory2.DeveloperName).add(association.UserId);
        }

        // buscar todas os territórios de 3ª camada
        Map<String, Territory2> mapThirdLayerTerritories = ActingTableTerritoryManagement.getThirdLayerTerritoriesDeveloperNameMap();

        List<UserTerritory2Association> associationsToCreate = new List<UserTerritory2Association>();
        
        //for no escopo
        for (Setorizacao__c sectorization : scope) {
            // for nos territorios de 3ª camada
            for (Territory2 thirdLayerTerritory : mapThirdLayerTerritories.values()) {
                // comparar categoria e regiao -> scope x thirdLayer
                if (sectorization.Categoria__c == thirdLayerTerritory.Categoria__c && sectorization.Regiao__c == thirdLayerTerritory.Regiao__c) {
                    // verificar se existe chave em mapTerritoryToUserIds (thirdLayerTerritory.developerName)
                    if (mapTerritoryToUserIds.containsKey(thirdLayerTerritory.DeveloperName)) {
                        // verificar se esse usuário já foi adicionado contains in mapTerritoryToUserIds
                        Set<Id> usersIdsInTerritory = mapTerritoryToUserIds.get(thirdLayerTerritory.DeveloperName);
                        
                        if (sectorization.Vendedor__c != null && sectorization.Vendedor__r.IsActive && !usersIdsInTerritory.contains(sectorization.Vendedor__c)) {
                            // (ñ) criar associação com o territorio
                            associationsToCreate.add(ActingTableTerritoryManagement.createUserAssociationForActingTableTerritory(thirdLayerTerritory,sectorization.Vendedor__c,'Vendedor'));
                            usersIdsInTerritory.add(sectorization.Vendedor__c);
                        }

                        if (sectorization.Gerente__c != null && sectorization.Gerente__r.IsActive && !usersIdsInTerritory.contains(sectorization.Gerente__c)) {
                            // (ñ) criar associação com o territorio
                            associationsToCreate.add(ActingTableTerritoryManagement.createUserAssociationForActingTableTerritory(thirdLayerTerritory,sectorization.Gerente__c,'Gerente'));
                            usersIdsInTerritory.add(sectorization.Gerente__c);
                        }
                        
                        if (sectorization.Coordenador__c != null && sectorization.Coordenador__r.IsActive && !usersIdsInTerritory.contains(sectorization.Coordenador__c)) {
                            // (ñ) criar associação com o territorio
                            associationsToCreate.add(ActingTableTerritoryManagement.createUserAssociationForActingTableTerritory(thirdLayerTerritory,sectorization.Coordenador__c,'Coordenador'));
                            usersIdsInTerritory.add(sectorization.Coordenador__c); 
                        }

                        if (sectorization.VendedorSuporte__c != null && sectorization.VendedorSuporte__r.IsActive != null && !usersIdsInTerritory.contains(sectorization.VendedorSuporte__c)) {
                            // (ñ) criar associação com o territorio
                            associationsToCreate.add(ActingTableTerritoryManagement.createUserAssociationForActingTableTerritory(thirdLayerTerritory,sectorization.VendedorSuporte__c,'Vendedor Suporte'));
                            usersIdsInTerritory.add(sectorization.VendedorSuporte__c);
                        }

                        mapTerritoryToUserIds.get(thirdLayerTerritory.DeveloperName).addAll(usersIdsInTerritory);
                    }
                }
            }
        }

        if (associationsToCreate.size() > 0) {Database.insert(associationsToCreate, false);}
    }

    public void finish(Database.BatchableContext BC) {
        if (callNextProcess) {Eventbus.publish(new ProcessActingTable__e(Type__c = 'associate_account_without_setorizacao',ExecuteNextProcesses__c = true));}
    }
}