Git Tests/force-app/main/default/default/objects/ProcessActingTable__e/ProcessActingTable__e.object-meta.xml
<CustomObject>
    <label>ProcessActingTable</label>
    <pluralLabel>ProcessActingTables</pluralLabel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ProcessActingTable__e/fields/ExecuteNextProcesses__c.field-meta.xml
<CustomField>
    <fullName>ExecuteNextProcesses__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ExecuteNextProcesses</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProcessActingTable__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo de processo</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/Setorizacao__c.object-meta.xml
<CustomObject>
    <label>Setorização</label>
    <nameField>
        <displayFormat>SET-{000000}</displayFormat>
        <label>Número da setorização</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setorizações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>BU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>G</fullName>
                <label>GENÉRICO</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>MATERIAIS</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>NUTRIÇÃO</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Medctech</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>SPECIALTY</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>AMBOS</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>DIABETES</label>
            </value>
            <value>
                <fullName>Q</fullName>
                <label>ODONTOLOGIA</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <label>EQUIPAMENTO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/CodigoMesa__c.field-meta.xml
<CustomField>
    <fullName>CodigoMesa__c</fullName>
    <externalId>true</externalId>
    <label>Código da mesa</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome do cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Setorização</relationshipLabel>
    <relationshipName>Setorizacao</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Mesa__c.field-meta.xml
<CustomField>
    <fullName>Mesa__c</fullName>
    <label>Mesa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Regiao__c.field-meta.xml
<CustomField>
    <fullName>Regiao__c</fullName>
    <label>Região</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VDE</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Setorizacao</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Territory2/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <externalId>true</externalId>
    <label>Categoria</label>
    <length>1</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Territory2/fields/CodigoMesa__c.field-meta.xml
<CustomField>
    <fullName>CodigoMesa__c</fullName>
    <externalId>true</externalId>
    <label>Código da mesa</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Territory2/fields/Regiao__c.field-meta.xml
<CustomField>
    <fullName>Regiao__c</fullName>
    <externalId>true</externalId>
    <label>Região</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/BatchProcessSectorization.cls
public class BatchProcessSectorization implements Database.Batchable<SObject> {
    public Boolean callNextProcess = false;

    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([
            SELECT 
                Id,
                Conta__c,
                Vendedor__c,
                CodigoMesa__c,
                Mesa__c,
                Regiao__c,
                Categoria__c,
                TOLABEL(Categoria__c) CategoriaLabel
            FROM Setorizacao__c WHERE CodigoMesa__c != null AND Regiao__c != null AND Categoria__c != null
        ]);
    }

    public void execute(Database.BatchableContext BC, List<Setorizacao__c> scope) {
        Territory2Model territoryModel = ActingTableTerritoryManagement.getTerritory2Model('Mesas');
        Territory2Type territoryType = ActingTableTerritoryManagement.getTerritory2Type('Mesas');

        if (territoryModel != null || territoryType != null) {
            Set<String> existingTerritoriesSet = new Set<String>();
            existingTerritoriesSet.addAll(ActingTableTerritoryManagement.getAllTerritoriesDeveloperNameMap().keySet());

            List<Territory2> firstLayerTerritories = new List<Territory2>();
            List<Territory2> secondLayerTerritories = new List<Territory2>();
            List<Territory2> thirdLayerTerritories = new List<Territory2>();
        
            for (Setorizacao__c currSectorization : scope) {
                String firstLayerKey = 'M'+ currSectorization.CodigoMesa__c;
                String secondLayerKey = firstLayerKey + '_' + currSectorization.Categoria__c;
                String thirdLayerLayerKey = secondLayerKey + '_' + currSectorization.Regiao__c;

                // create 1st layer
                if (!existingTerritoriesSet.contains(firstLayerKey) && currSectorization.CodigoMesa__c != null) {
                    Territory2 firstLayerObject = ActingTableTerritoryManagement.createFirstLayerTerritoryObject(
                        territoryModel,
                        territoryType,
                        currSectorization
                    );

                    firstLayerTerritories.add(firstLayerObject);
                    existingTerritoriesSet.add(firstLayerObject.DeveloperName);
                }

                // create 2nd layer
                if (!existingTerritoriesSet.contains(secondLayerKey) && currSectorization.Categoria__c != null) {
                    Territory2 secondLayerObject = ActingTableTerritoryManagement.createSecondLayerTerritoryObject(
                        territoryModel,
                        territoryType,
                        currSectorization
                    );

                    secondLayerTerritories.add(secondLayerObject);
                    existingTerritoriesSet.add(secondLayerObject.DeveloperName);
                }

                // create 3rd layer
                if (!existingTerritoriesSet.contains(thirdLayerLayerKey) && currSectorization.Regiao__c != null) {
                    Territory2 thirdLayerObject = ActingTableTerritoryManagement.createThirdLayerTerritoryObject(
                        territoryModel,
                        territoryType,
                        currSectorization
                    );

                    thirdLayerTerritories.add(thirdLayerObject);
                    existingTerritoriesSet.add(thirdLayerObject.DeveloperName);
                } 
            }

            // three inserts for same object, because "upsert" doesn't exists for territory2 object.
            // and parents territories MUST exist before to insert children, for association purpose.
            if (firstLayerTerritories.size() > 0) {
                insert firstLayerTerritories;
            }

            if (secondLayerTerritories.size() > 0) {
                insert secondLayerTerritories;
            }
            
            if (thirdLayerTerritories.size() > 0) {
                insert thirdLayerTerritories;
            }
        }
    }

    public void finish(Database.BatchableContext BC) {
        if (callNextProcess) {
            Eventbus.publish(new ProcessActingTable__e(
                Type__c = 'associate_accounts',
                ExecuteNextProcesses__c = true
            ));
        }
    }
}