Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/CondicaoPagamentoPorCD__c.object-meta.xml
<CustomObject>
    <label>Condição de pagamento por CD</label>
    <nameField>
        <label>Nome de Condição de pagamento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condições de pagamentos por CD</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Condição de Pagamento CD</relationshipLabel>
    <relationshipName>CondicoesPagamento</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/CondicaoPagamentoPL__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamentoPL__c</fullName>
    <label>Condição de Pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Integradora__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>002/28 D</fullName>
            </value>
            <value>
                <fullName>003/30 D</fullName>
            </value>
            <value>
                <fullName>004/45 D</fullName>
            </value>
            <value>
                <fullName>042/60 D</fullName>
            </value>
            <value>
                <fullName>012/30,45,60 D</fullName>
            </value>
            <value>
                <fullName>028/35 D</fullName>
            </value>
            <value>
                <fullName>058/56 D</fullName>
            </value>
            <value>
                <fullName>046/45,60 D</fullName>
            </value>
            <value>
                <fullName>013/30,60 D</fullName>
            </value>
            <value>
                <fullName>036/21 D</fullName>
            </value>
            <value>
                <fullName>115/20 D</fullName>
            </value>
            <value>
                <fullName>065/25 D</fullName>
            </value>
            <value>
                <fullName>007/28,35 D</fullName>
            </value>
            <value>
                <fullName>008/28,35,42 D</fullName>
            </value>
            <value>
                <fullName>010/28,35,42,49,56</fullName>
            </value>
            <value>
                <fullName>081/28,42 D</fullName>
            </value>
            <value>
                <fullName>011/30,45 D</fullName>
            </value>
            <value>
                <fullName>049/14 DIAS</fullName>
            </value>
            <value>
                <fullName>066/10 D</fullName>
            </value>
            <value>
                <fullName>045/120 D</fullName>
            </value>
            <value>
                <fullName>006/90 D</fullName>
            </value>
            <value>
                <fullName>043/A VISTA</fullName>
            </value>
            <value>
                <fullName>001/30 D - 5,15,25</fullName>
            </value>
            <value>
                <fullName>003</fullName>
            </value>
            <value>
                <fullName>004</fullName>
            </value>
            <value>
                <fullName>005</fullName>
            </value>
            <value>
                <fullName>005/49 D</fullName>
            </value>
            <value>
                <fullName>006</fullName>
            </value>
            <value>
                <fullName>009/28,35,42,49 D</fullName>
            </value>
            <value>
                <fullName>014/30,60,90 D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/FretePicklist__c.field-meta.xml
<CustomField>
    <fullName>FretePicklist__c</fullName>
    <label>Tipo de Frete</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CIF</fullName>
                <default>true</default>
                <label>CIF</label>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/MinimumBilling__c.field-meta.xml
<CustomField>
    <fullName>MinimumBilling__c</fullName>
    <label>Faturamento Mínimo</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/ObservacoesLongText__c.field-meta.xml
<CustomField>
    <fullName>ObservacoesLongText__c</fullName>
    <label>Observações</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/Orcamento__c.field-meta.xml
<CustomField>
    <fullName>Orcamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Orçamento</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Condições de pagamentos por CD</relationshipLabel>
    <relationshipName>Condicespagamentospor_CD</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/PrazoEntrega__c.field-meta.xml
<CustomField>
    <fullName>PrazoEntrega__c</fullName>
    <label>Prazo de Entrega</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Orcamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/DataVencimento__c.field-meta.xml
<CustomField>
    <fullName>DataVencimento__c</fullName>
    <label>Data de Vencimento</label>
    <type>DateTime</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/FretePicklist__c.field-meta.xml
<CustomField>
    <fullName>FretePicklist__c</fullName>
    <label>Tipo de Frete</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/MinimumBilling__c.field-meta.xml
<CustomField>
    <fullName>MinimumBilling__c</fullName>
    <label>Faturamento Mínimo</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/ObservacoesLongText__c.field-meta.xml
<CustomField>
    <fullName>ObservacoesLongText__c</fullName>
    <label>Observações</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/PrazoEntrega__c.field-meta.xml
<CustomField>
    <fullName>PrazoEntrega__c</fullName>
    <label>Prazo de Entrega</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/TabulacaoN1__c.field-meta.xml
<CustomField>
    <fullName>TabulacaoN1__c</fullName>
    <inlineHelpText>Este campo é um refinamento do valor do campo Status</inlineHelpText>
    <label>Tabulação N1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recusa</fullName>
            </value>
            <value>
                <fullName>Aceite</fullName>
            </value>
            <value>
                <fullName>Improdutiva</fullName>
            </value>
            <value>
                <fullName>Envio Automático</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/TabulacaoN2__c.field-meta.xml
<CustomField>
    <fullName>TabulacaoN2__c</fullName>
    <inlineHelpText>Este campo é o segundo refinamento do valor do campo Status</inlineHelpText>
    <label>Tabulação N2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>TabulacaoN1__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cotação Enviada TT</fullName>
            </value>
            <value>
                <fullName>Cotação Enviada Parcial</fullName>
            </value>
            <value>
                <fullName>Fora de Malha</fullName>
            </value>
            <value>
                <fullName>Falta de estoque</fullName>
            </value>
            <value>
                <fullName>Não temos o item no portifólio</fullName>
            </value>
            <value>
                <fullName>Não temos a apresentação solicitada</fullName>
            </value>
            <value>
                <fullName>Não temos a validade solicitada</fullName>
            </value>
            <value>
                <fullName>Não temos a quantidade solicitada</fullName>
            </value>
            <value>
                <fullName>Não trabalhamos</fullName>
            </value>
            <value>
                <fullName>Não conseguimos atender no prazo solicitado</fullName>
            </value>
            <value>
                <fullName>Não atinge o faturamento mínimo</fullName>
            </value>
            <value>
                <fullName>Área Restrita / Regionalização</fullName>
            </value>
            <value>
                <fullName>Bloqueio Financeiro</fullName>
            </value>
            <value>
                <fullName>Cotação Vencida</fullName>
            </value>
            <value>
                <fullName>BU Material</fullName>
            </value>
            <value>
                <fullName>BU Genérico</fullName>
            </value>
            <value>
                <fullName>BU Especialidade</fullName>
            </value>
            <value>
                <fullName>Envio Automático</fullName>
            </value>
            <value>
                <fullName>BLACK LIST</fullName>
                <isActive>false</isActive>
                <label>BLACK LIST</label>
            </value>
            <value>
                <fullName>NÃO É CLIENTE ALVO</fullName>
                <isActive>false</isActive>
                <label>NÃO É CLIENTE ALVO</label>
            </value>
            <value>
                <fullName>Outro Distribuidor</fullName>
                <isActive>false</isActive>
                <label>Outro Distribuidor</label>
            </value>
            <value>
                <fullName>PARCIAL</fullName>
                <isActive>false</isActive>
                <label>PARCIAL</label>
            </value>
            <value>
                <fullName>Preço melhor do concorrente</fullName>
                <isActive>false</isActive>
                <label>Preço melhor do concorrente</label>
            </value>
            <value>
                <fullName>TODOS OS ITENS - NÃO CONSEGUIMOS ATENDER NO PRAZO SOLICITADO</fullName>
                <isActive>false</isActive>
                <label>TODOS OS ITENS - NÃO CONSEGUIMOS ATENDER NO PRAZO SOLICITADO</label>
            </value>
            <value>
                <fullName>TODOS OS ITENS - NÃO TRABALHAMOS</fullName>
                <isActive>false</isActive>
                <label>TODOS OS ITENS - NÃO TRABALHAMOS</label>
            </value>
            <value>
                <fullName>TODOS OS ITENS FORA DE MALHA</fullName>
                <isActive>false</isActive>
                <label>TODOS OS ITENS FORA DE MALHA</label>
            </value>
            <value>
                <fullName>TODOS OS ITENS FORA DO PORTFOLIO</fullName>
                <isActive>false</isActive>
                <label>TODOS OS ITENS FORA DO PORTFOLIO</label>
            </value>
            <value>
                <fullName>TODOS OS ITENS SEM A APRESENTAÇÃO SOLICITADA</fullName>
                <isActive>false</isActive>
                <label>TODOS OS ITENS SEM A APRESENTAÇÃO SOLICITADA</label>
            </value>
            <value>
                <fullName>TODOS OS ITENS SEM A QUANTIDADE SOLICITADA</fullName>
                <isActive>false</isActive>
                <label>TODOS OS ITENS SEM A QUANTIDADE SOLICITADA</label>
            </value>
            <value>
                <fullName>TODOS OS ITENS SEM A VALIDADE SOLICITADA</fullName>
                <isActive>false</isActive>
                <label>TODOS OS ITENS SEM A VALIDADE SOLICITADA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/recordTypes/OrcamentoPortal.recordType-meta.xml
<RecordType>
    <fullName>OrcamentoPortal</fullName>
    <active>true</active>
    <businessProcess>Portal de Cotações</businessProcess>
    <label>Orçamento do Portal</label>
    <!---->
    <!---->
</RecordType>

Git Tests/force-app/main/default/default/objects/OpportunityTeamMember/fields/HasChangesUnsync__c.field-meta.xml
<CustomField>
    <fullName>HasChangesUnsync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>HasChangesUnsync</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityTeamMember/fields/TabulacaoN1__c.field-meta.xml
<CustomField>
    <fullName>TabulacaoN1__c</fullName>
    <inlineHelpText>Este campo é um refinamento do valor do campo Status</inlineHelpText>
    <label>Tabulação N1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recusa</fullName>
            </value>
            <value>
                <fullName>Aceite</fullName>
            </value>
            <value>
                <fullName>Improdutiva</fullName>
            </value>
            <value>
                <fullName>Envio Automático</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/classes/IntegrationPortalQuoteOUTSchedule.cls
public class IntegrationPortalQuoteOUTSchedule implements Schedulable {

    public static final Id RECORDTYPE_PORTALID = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('OrcamentoPortal').getRecordTypeId();

    public void execute(SchedulableContext sc) {
        System.debug('método principal');
        Savepoint sp;
        try {
            Map<Id, Opportunity> oppMap = getOpportunityMap();
            String standardConPayId = getStandardConditionPaymentId();
            sp = Database.setSavepoint();
            List<Id> oppIdList = updateOpportunities(oppMap, standardConPayId);

            if(!oppIdList.isEmpty()) System.enqueueJob(new IntegrationPortalQuoteOUTQueueable(0, oppIdList));
        } catch (Exception ex) {
            if(sp != null){
                Database.rollback(sp);
            }
            ExceptionUtils.debug(ex);
        }


    }

    public static void scheduleQueue() {
        
        IntegrationPortalQuoteOUTSchedule s = new IntegrationPortalQuoteOUTSchedule();
        for(String cronExp : getCronExpList()){
            System.debug('agendando '+cronExp);
            System.schedule(Test.isRunningTest() ? 'IntegrateQuoteOUT'+cronExp.mid(2, 2)+'min job test' : 'IntegrateQuoteOUT'+cronExp.mid(2, 2)+'min job', cronExp, s);
        }
    }

    private static List<String> getCronExpList(){
        return new List<String>{
            '0 0 * * * ?',
            '0 5 * * * ?',
            '0 10 * * * ?',
            '0 15 * * * ?',
            '0 20 * * * ?',
            '0 25 * * * ?',
            '0 30 * * * ?',
            '0 35 * * * ?',
            '0 40 * * * ?',
            '0 45 * * * ?',
            '0 50 * * * ?',
            '0 55 * * * ?'
        };
    }

    private static Map<Id, Opportunity> getOpportunityMap(){
        return new Map<Id, Opportunity> ([
            SELECT Id, 
            (SELECT Id, MinimumBilling__c, PrazoEntrega__c, FretePicklist__c, CondicaoPagamento__c, CondicaoPagamentoPL__c, ObservacoesLongText__c FROM Condicespagamentospor_CD__r),
            (SELECT Id FROM OpportunityTeamMembers WHERE HasChangesUnsync__c = true)
            FROM Opportunity
            WHERE DataVencimento__c > :Datetime.now().addMinutes(-1)
            AND DataVencimento__c < :Datetime.now().addMinutes(5).addSeconds(30)
            AND RecordTypeId = :RECORDTYPE_PORTALID
            AND HasChangesUnsync__c = true
        ]);
    }

    private static String getStandardConditionPaymentId(){
        String standardConPayId = null;
        List<CondicaoPagamento__c> conPayList = [
            SELECT Id 
            FROM CondicaoPagamento__c 
            WHERE Name = '043/A VISTA'
        ];
        if(!conPayList.isEmpty()) standardConPayId = conPayList[0].Id;
        return standardConPayId;
    }

    private static List<Id> updateOpportunities(Map<Id, Opportunity> oppMap, String standardConPayId){
        List<Id> oppIdList = new List<Id>();
        List<CondicaoPagamentoPorCD__c> cdList = new List<CondicaoPagamentoPorCD__c>();
        List<Opportunity> oppToUpdate = new List<Opportunity>();
        List<OpportunityTeamMember> oppTeamMemberToUpdate = new List<OpportunityTeamMember>();
        
        for(Opportunity opp : oppMap.values()){
            oppIdList.add(opp.id);
            oppToUpdate.add(
                new Opportunity(
                    id= opp.id,
                    StageName = 'Aguardando Integração',
                    TabulacaoN1__c = 'Aceite',
                    TabulacaoN2__c = 'Envio Automático',
                    OrcamentoTravado__c = true
                )
            );

            if(!opp.OpportunityTeamMembers.isEmpty()){
                for(OpportunityTeamMember oppTm : opp.OpportunityTeamMembers){
                    oppTeamMemberToUpdate.add(
                        new OpportunityTeamMember(
                            id= oppTm.id,
                            TabulacaoN1__c = 'Aceite',
                            TabulacaoN2__c = 'Envio Automático'
                        )
                    );
                }
            }

            if(opp.Condicespagamentospor_CD__r.isEmpty()) continue;
            
            for(CondicaoPagamentoPorCD__c cd : opp.Condicespagamentospor_CD__r){
                Boolean changeCD = false;
                if(cd.MinimumBilling__c == 0  || cd.MinimumBilling__c == null){
                    cd.MinimumBilling__c = 600;
                    changeCD = true;
                }
                if(cd.PrazoEntrega__c   == 0  || cd.PrazoEntrega__c   == null){
                    cd.PrazoEntrega__c = 5;
                    changeCD = true;
                }
                if(String.isEmpty(cd.FretePicklist__c)){
                    cd.FretePicklist__c = 'CIF';
                    changeCD = true;
                }
                if(String.isEmpty(cd.CondicaoPagamento__c)){
                    cd.CondicaoPagamentoPL__c = '043/A VISTA';
                    cd.CondicaoPagamento__c = standardConPayId;
                    cd.ObservacoesLongText__c = String.isEmpty(cd.ObservacoesLongText__c) ? '' : cd.ObservacoesLongText__c + '\n';
                    cd.ObservacoesLongText__c += 'Atenção: Condição de pagamento a combinar!';
                    changeCD = true;
                }

                if(changeCD) cdList.add(cd);
            }
            
        }
        update oppToUpdate;
        update oppTeamMemberToUpdate;
        update cdList;
        return oppIdList;
    }
}