Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/CondicaoPagamentoPorCD__c.object-meta.xml
<CustomObject>
    <label>Condição de pagamento por CD</label>
    <nameField>
        <label>Nome de Condição de pagamento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condições de pagamentos por CD</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/CentroDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentroDistribuicao__c</fullName>
    <label>Centro de distribuição</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/CloseDate__c.field-meta.xml
<CustomField>
    <fullName>CloseDate__c</fullName>
    <label>Data de validade</label>
    <type>Date</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/CondicaoPagamentoPL__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamentoPL__c</fullName>
    <label>Condição de Pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Integradora__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>002/28 D</fullName>
            </value>
            <value>
                <fullName>003/30 D</fullName>
            </value>
            <value>
                <fullName>004/45 D</fullName>
            </value>
            <value>
                <fullName>042/60 D</fullName>
            </value>
            <value>
                <fullName>012/30,45,60 D</fullName>
            </value>
            <value>
                <fullName>028/35 D</fullName>
            </value>
            <value>
                <fullName>058/56 D</fullName>
            </value>
            <value>
                <fullName>046/45,60 D</fullName>
            </value>
            <value>
                <fullName>013/30,60 D</fullName>
            </value>
            <value>
                <fullName>036/21 D</fullName>
            </value>
            <value>
                <fullName>115/20 D</fullName>
            </value>
            <value>
                <fullName>065/25 D</fullName>
            </value>
            <value>
                <fullName>007/28,35 D</fullName>
            </value>
            <value>
                <fullName>008/28,35,42 D</fullName>
            </value>
            <value>
                <fullName>010/28,35,42,49,56</fullName>
            </value>
            <value>
                <fullName>081/28,42 D</fullName>
            </value>
            <value>
                <fullName>011/30,45 D</fullName>
            </value>
            <value>
                <fullName>049/14 DIAS</fullName>
            </value>
            <value>
                <fullName>066/10 D</fullName>
            </value>
            <value>
                <fullName>045/120 D</fullName>
            </value>
            <value>
                <fullName>006/90 D</fullName>
            </value>
            <value>
                <fullName>043/A VISTA</fullName>
            </value>
            <value>
                <fullName>001/30 D - 5,15,25</fullName>
            </value>
            <value>
                <fullName>003</fullName>
            </value>
            <value>
                <fullName>004</fullName>
            </value>
            <value>
                <fullName>005</fullName>
            </value>
            <value>
                <fullName>005/49 D</fullName>
            </value>
            <value>
                <fullName>006</fullName>
            </value>
            <value>
                <fullName>009/28,35,42,49 D</fullName>
            </value>
            <value>
                <fullName>014/30,60,90 D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/FretePicklist__c.field-meta.xml
<CustomField>
    <fullName>FretePicklist__c</fullName>
    <label>Tipo de Frete</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CIF</fullName>
                <default>true</default>
                <label>CIF</label>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/MinimumBilling__c.field-meta.xml
<CustomField>
    <fullName>MinimumBilling__c</fullName>
    <label>Faturamento Mínimo</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/ObservacoesLongText__c.field-meta.xml
<CustomField>
    <fullName>ObservacoesLongText__c</fullName>
    <label>Observações</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/PrazoEntrega__c.field-meta.xml
<CustomField>
    <fullName>PrazoEntrega__c</fullName>
    <label>Prazo de Entrega</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/PrazoValidade__c.field-meta.xml
<CustomField>
    <fullName>PrazoValidade__c</fullName>
    <label>Prazo de validade (em dias)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/budgetCtrlTest.cls
@isTest
public with sharing class budgetCtrlTest {
    @isTest
    public static void testBudgetCtrl(){
        BudgetCtrl.ParamsMalha paramsMalha = new BudgetCtrl.ParamsMalha();
        paramsMalha.cnpj = null;
        paramsMalha.UF = null;
        paramsMalha.productCode = null;
        paramsMalha.calcMargem = null;
        paramsMalha.pricebookExternalId = null;
        paramsMalha.condPagamento = null;
        paramsMalha.isForaMalha = null;

        BudgetCtrl.ParamsProd paramsProd = new BudgetCtrl.ParamsProd();
        paramsProd.unidadePrincipal = null;
        paramsProd.quantidadeSolicitada = null;
        paramsProd.cdsBloqueados = null;
        paramsProd.accountId = null;
        paramsProd.accountType = null;
        paramsProd.unidadeSecundaria = null;
        paramsProd.tipoConversao = null;
        paramsProd.fatorConversao = null;

        BudgetCtrl.Malha malha = new BudgetCtrl.Malha();
        malha.cds = null;
        malha.code = null;
        malha.msgErro = null;
        malha.codprotheus = null;
        malha.ean = null;

        BudgetCtrl.MalhaData malhaData = new BudgetCtrl.MalhaData();
        malhaData.TipoIntegradora = null;
        malhaData.pf = null;
        malhaData.laboratorio = null;
        malhaData.EnviaIntegrador = null;
        malhaData.range = null;
        malhaData.BloqRegionalizacao = null;
        malhaData.preco = null;
        malhaData.tipopreco = null;
        malhaData.filial = null;
        malhaData.cd = null;
        malhaData.custo = null;
        malhaData.saldo = null;
        malhaData.cnpj = null;
        malhaData.prioridade = null;
        malhaData.foramalha = null;
        malhaData.aliquota = null;
    
        BudgetCtrl.Range range = new BudgetCtrl.Range();
        BudgetCtrl.DistCenter distCenter = new BudgetCtrl.DistCenter();
        distCenter.id = null;
        distCenter.nome = null;
        distCenter.cnpj = null;
        distCenter.custo = null;
        distCenter.preco = null;
        distCenter.aliquota = null;
        distCenter.precoFabrica = null;
        distCenter.estoque = null;
        distCenter.prioridade = null;
        distCenter.foramalha = null;
        distCenter.unidadePrincipal = null;
        distCenter.quantidadeElfa = null;
        distCenter.valorElfa = null;
        distCenter.desconto = null;
        distCenter.validadeMin = null;
        distCenter.score = null;
        distCenter.margem = null;
        distCenter.margemAlvo = null;
        distCenter.quantidadePortal = null;
        distCenter.valorPortal = null;
        distCenter.valorTotal = null;
        distCenter.cdBloqueado = null;
        distCenter.dataGanho = null;
        distCenter.valorGanho = null;
        distCenter.dataPerdido = null;
        distCenter.valorPerdido = null;
        distCenter.bloqueioRegional = false;
        distCenter.quantPrevista = null;
        distCenter.previsaoEntrada = null;
        distCenter.badges = null;
        distCenter.unidadeSecundaria = null;
        distCenter.conversaoUnidadeTexto = null;
        distCenter.estoqueSecundario = null;
        distCenter.precoSecundario = null;
        distCenter.precoFabricaSecundario = null;

        BudgetCtrl.ExtraFields extraFields = new BudgetCtrl.ExtraFields();
        extraFields.oppId = null;
        extraFields.foraMalha = null;
        extraFields.fatorConversaoProd = null;
        extraFields.tipoConversaoProd = null;
        extraFields.comentario = null;

        BudgetCtrl.Badge b1 = new BudgetCtrl.Badge('O', 0);
        String labelb1 = b1.label;
        String b1a = b1.style;
        BudgetCtrl.Badge b2 = new BudgetCtrl.Badge('A', 0);
        String labelb2 = b2.label;
        BudgetCtrl.Badge b3 = new BudgetCtrl.Badge('ContratoShelfLife', 0);
        String labelb3 = b3.label;
        BudgetCtrl.Badge b4 = new BudgetCtrl.Badge('Campanha', 0);
        String labelb4 = b4.label;
        BudgetCtrl.Badge b5 = new BudgetCtrl.Badge('CampanhaVendedor', 0);
        String labelb5 = b5.label;
        BudgetCtrl.Badge b6 = new BudgetCtrl.Badge('ProdutoConsignado', 0);
        String labelb6 = b6.label;
        BudgetCtrl.Badge b7 = new BudgetCtrl.Badge('ProdutoReservado', 0);
        String labelb7 = b7.label;
        BudgetCtrl.Badge b8 = new BudgetCtrl.Badge('nada', 0);
        String labelb8 = b8.label;

        BudgetCtrl.CampaignData camp = new BudgetCtrl.CampaignData();
        camp.price = 1;

        BudgetCtrl.PicklistOption picklist = new BudgetCtrl.PicklistOption(false, '', '');

        BudgetCtrl.SomatoriaDTO somatoria = new BudgetCtrl.SomatoriaDTO();
        
        CondicaoPagamentoPorCD__c condPagCD = new CondicaoPagamentoPorCD__c(
            CentroDistribuicao__c = '',
            CNPJCD__c = '',
            FretePicklist__c = '',
            CondicaoPagamentoPL__c = '002/28 D',
            ObservacoesLongText__c = '',
            CloseDate__c = System.today(),
            PrazoValidade__c = 0,
            PrazoEntrega__c = 0,
            MinimumBilling__c = 0
        );
        BudgetCtrl.DistCenterDTO distCenterDTO = new BudgetCtrl.DistCenterDTO(somatoria, condPagCD);
        distCenterDTO.build();
    }
}