Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/CondicaoPagamentoPorCD__c.object-meta.xml
<CustomObject>
    <label>Condição de pagamento por CD</label>
    <nameField>
        <label>Nome de Condição de pagamento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condições de pagamentos por CD</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/CentroDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentroDistribuicao__c</fullName>
    <label>Centro de distribuição</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/CloseDate__c.field-meta.xml
<CustomField>
    <fullName>CloseDate__c</fullName>
    <label>Data de validade</label>
    <type>Date</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/CondicaoPagamentoPL__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamentoPL__c</fullName>
    <label>Condição de Pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Integradora__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>002/28 D</fullName>
            </value>
            <value>
                <fullName>003/30 D</fullName>
            </value>
            <value>
                <fullName>004/45 D</fullName>
            </value>
            <value>
                <fullName>042/60 D</fullName>
            </value>
            <value>
                <fullName>012/30,45,60 D</fullName>
            </value>
            <value>
                <fullName>028/35 D</fullName>
            </value>
            <value>
                <fullName>058/56 D</fullName>
            </value>
            <value>
                <fullName>046/45,60 D</fullName>
            </value>
            <value>
                <fullName>013/30,60 D</fullName>
            </value>
            <value>
                <fullName>036/21 D</fullName>
            </value>
            <value>
                <fullName>115/20 D</fullName>
            </value>
            <value>
                <fullName>065/25 D</fullName>
            </value>
            <value>
                <fullName>007/28,35 D</fullName>
            </value>
            <value>
                <fullName>008/28,35,42 D</fullName>
            </value>
            <value>
                <fullName>010/28,35,42,49,56</fullName>
            </value>
            <value>
                <fullName>081/28,42 D</fullName>
            </value>
            <value>
                <fullName>011/30,45 D</fullName>
            </value>
            <value>
                <fullName>049/14 DIAS</fullName>
            </value>
            <value>
                <fullName>066/10 D</fullName>
            </value>
            <value>
                <fullName>045/120 D</fullName>
            </value>
            <value>
                <fullName>006/90 D</fullName>
            </value>
            <value>
                <fullName>043/A VISTA</fullName>
            </value>
            <value>
                <fullName>001/30 D - 5,15,25</fullName>
            </value>
            <value>
                <fullName>003</fullName>
            </value>
            <value>
                <fullName>004</fullName>
            </value>
            <value>
                <fullName>005</fullName>
            </value>
            <value>
                <fullName>005/49 D</fullName>
            </value>
            <value>
                <fullName>006</fullName>
            </value>
            <value>
                <fullName>009/28,35,42,49 D</fullName>
            </value>
            <value>
                <fullName>014/30,60,90 D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/FretePicklist__c.field-meta.xml
<CustomField>
    <fullName>FretePicklist__c</fullName>
    <label>Tipo de Frete</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CIF</fullName>
                <default>true</default>
                <label>CIF</label>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/MinimumBilling__c.field-meta.xml
<CustomField>
    <fullName>MinimumBilling__c</fullName>
    <label>Faturamento Mínimo</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/ObservacoesLongText__c.field-meta.xml
<CustomField>
    <fullName>ObservacoesLongText__c</fullName>
    <label>Observações</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/PrazoEntrega__c.field-meta.xml
<CustomField>
    <fullName>PrazoEntrega__c</fullName>
    <label>Prazo de Entrega</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/PrazoValidade__c.field-meta.xml
<CustomField>
    <fullName>PrazoValidade__c</fullName>
    <label>Prazo de validade (em dias)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/BudgetCtrl.cls
public inherited sharing class BudgetCtrl {
    public inherited sharing class ParamsMalha {
        public String cnpj              {get; set;}
        public String UF                {get; set;}
        public String productCode       {get; set;}
        public Boolean calcMargem       {get; set;}
        public String pricebookExternalId {get; set;}      
        public String condPagamento     {get; set;}
        public Boolean isForaMalha      {get; set;}
    }

    public inherited sharing class ParamsProd {
        public String unidadePrincipal  {get; set;}
        public Decimal quantidadeSolicitada {get; set;}
        public String cdsBloqueados     {get; set;}
        public String accountId         {get; set;}
        public String accountType       {get; set;}
        public String unidadeSecundaria {get; set;}
        public String tipoConversao     {get; set;}
        public String fatorConversao    {get; set;}
    }

    public inherited sharing class Malha {
        public List<MalhaData> cds      {get; set;}
        public String code              {get; set;}
        public String msgErro           {get; set;}
        public String codprotheus       {get; set;}
        public String ean               {get; set;}
    }
    
    public inherited sharing class MalhaData {
        public String TipoIntegradora   {get; set;}
        public Decimal pf               {get; set;}
        public String laboratorio       {get; set;}
        public Boolean EnviaIntegrador  {get; set;}
        public List<Range> range        {get; set;}
        public Boolean BloqRegionalizacao {get; set;}
        public Decimal preco            {get; set;}
        public String tipopreco         {get; set;}
        public String filial            {get; set;}
        public String cd                {get; set;}
        public Decimal custo            {get; set;}
        public Decimal saldo            {get; set;}
        public String cnpj              {get; set;}
        public String prioridade        {get; set;}
        public Boolean foramalha        {get; set;}
        public Decimal aliquota         {get; set;}
    }

    public inherited sharing class Range {}


    public inherited sharing class DistCenter {
        public String id                {get; set;}
        public String nome              {get; set;}
        public String cnpj              {get; set;}
        public Decimal custo            {get; set;}
        public Decimal preco            {get; set;}
        public Decimal aliquota         {get; set;}
        public Decimal precoFabrica     {get; set;}
        public Decimal estoque          {get; set;}
        public String prioridade        {get; set;}
        public Boolean foramalha        {get; set;}
        public String unidadePrincipal  {get; set;}
        public Decimal quantidadeElfa   {get; set;}
        public Decimal valorElfa        {get; set;}
        public Decimal desconto         {get; set;}
        public String validadeMin       {get; set;}
        public Decimal score            {get; set;}
        public Decimal margem           {get; set;}
        public Decimal margemAlvo       {get; set;}
        public Decimal quantidadePortal {get; set;}
        public Decimal valorPortal      {get; set;}
        public Decimal valorTotal       {get; set;}
        public Boolean cdBloqueado      {get; set;}
        public Boolean bloqueioRegional {get; set;}
        public String dataGanho         {get; set;}
        public Decimal valorGanho       {get; set;}
        public String dataPerdido       {get; set;}
        public Decimal valorPerdido     {get; set;}
        public String previsaoEntrada   {get; set;}
        public Decimal quantPrevista    {get; set;}
        public List<Badge> badges       {get; set;}
        public String unidadeSecundaria {get; set;}
        public String conversaoUnidadeTexto {get; set;}
        public Decimal estoqueSecundario {get; set;}
        public Decimal precoSecundario  {get; set;}
        public Decimal precoFabricaSecundario {get; set;}
    }

    public inherited sharing class Badge {
        public String name              {get; set;}
        public Decimal price            {get; set;}
        public String style             {get{
            return 'slds-badge_inverse badge-portal ' + this.name + 'Css';
        }}
        public String label             {get{
            Map<String, String> labelMap = new Map<String, String>{
                'O' => 'Produto OL',
                'A' => 'Acordo Comercial',
                'ContratoShelfLife' => 'Produto Shelflife',
                'Campanha' => 'Campanha Produto',
                'CampanhaVendedor' => 'Campanha Vendedor',
                'ProdutoConsignado' => 'Produto Consignado',
                'ProdutoReservado' => 'Produto Reservado'
            };
                
            return labelMap.get(this.name);
        }}

        public Badge(String name, Decimal price){
            this.name = name;
            this.price = price;
        }
    }

    public inherited sharing class ExtraFields {
        public String oppId             {get;set;}
        public Boolean foraMalha        {get; set;}
        public Decimal fatorConversaoProd {get; set;}
        public String tipoConversaoProd {get; set;}
        public String comentario        {get; set;}
    }

    public inherited sharing class CampaignData {
        public Set<String> cdCodeSet    {get; set;}
        public Decimal price            {get; set;}

        public CampaignData(){
            this.cdCodeSet = new Set<String>();
        }
    }

    public class PicklistOption {
        public Boolean selected {get; set;}
        public String value {get; set;}
        public String label {get; set;}
        
        public PicklistOption(Boolean slc,String param1, String param2 ){
            this.selected = slc;
            this.value = param1;
            this.label = param2;
        }
    }

    public class ProgramacaoEntrega {
        @AuraEnabled public String data;
        @AuraEnabled public String quantidade;
    }

    public class DistCenterDTO {
        public Decimal resp {get;set;}
        public Decimal totItem {get;set;}
        public Double qtdItensTotal {get;set;}
        public String Id {get;set;}
        public String CentroDistribuicao {get;set;}
        public String CNPJCD {get;set;}
        public String FretePicklist {get;set;}
        public String CondicaoPagamentoPL {get;set;}
        public String ObservacoesLongText {get;set;}
        public Date CloseDate {get; set;}
        public Decimal PrazoValidade {get;set;}
        public Decimal PrazoEntrega {get;set;}
        public Decimal MinimumBilling {get;set;}

        public DistCenterDTO(SomatoriaDTO sum, CondicaoPagamentoPorCD__c cd){
            this.resp = sum.resp;
            this.totItem = sum.totItem;
            this.qtdItensTotal = sum.qtdItensTotal;

            this.Id = cd.Id;
            this.CentroDistribuicao = cd.CentroDistribuicao__c;
            this.CNPJCD = cd.CNPJCD__c;
            this.FretePicklist = cd.FretePicklist__c;
            this.CondicaoPagamentoPL = cd.CondicaoPagamentoPL__c;
            this.ObservacoesLongText = cd.ObservacoesLongText__c;
            this.CloseDate = cd.CloseDate__c;
            this.PrazoValidade = cd.PrazoValidade__c;
            this.PrazoEntrega = cd.PrazoEntrega__c;
            this.MinimumBilling = cd.MinimumBilling__c;
        }

        public CondicaoPagamentoPorCD__c build(){
            return new CondicaoPagamentoPorCD__c(
                Id = this.Id,
                CentroDistribuicao__c = this.CentroDistribuicao,
                CNPJCD__c = this.CNPJCD,
                FretePicklist__c = this.FretePicklist,
                CondicaoPagamentoPL__c = this.CondicaoPagamentoPL,
                ObservacoesLongText__c = this.ObservacoesLongText,
                CloseDate__c = this.CloseDate,
                PrazoValidade__c = this.PrazoValidade,
                PrazoEntrega__c = this.PrazoEntrega,
                MinimumBilling__c = this.MinimumBilling
            );
        }
    }
    
    public class SomatoriaDTO  {
        @AuraEnabled
        public Decimal resp             {get; set;}
        @AuraEnabled
        public Decimal totItem          {get; set;}
        @AuraEnabled
        public Double qtdItensTotal      {get; set;}
        
        public SomatoriaDTO(){
            this.resp = 0;
            this.totItem = 0;
            this.qtdItensTotal = 0;
        }
    }
}