Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/CondicaoPagamentoPorCD__c.object-meta.xml
<CustomObject>
    <label>Condição de pagamento por CD</label>
    <nameField>
        <label>Nome de Condição de pagamento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condições de pagamentos por CD</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/QuantidadeItensTotal__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeItensTotal__c</fullName>
    <label>Quantidade de Itens Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/TotalPortal__c.field-meta.xml
<CustomField>
    <fullName>TotalPortal__c</fullName>
    <label>Total Portal</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/QuantidadePortal__c.field-meta.xml
<CustomField>
    <fullName>QuantidadePortal__c</fullName>
    <inlineHelpText>Quantidade Portal</inlineHelpText>
    <label>Quantidade Portal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/ValorPortal__c.field-meta.xml
<CustomField>
    <fullName>ValorPortal__c</fullName>
    <inlineHelpText>Valor Portal</inlineHelpText>
    <label>Valor Portal</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <description>
        Objeto recebido na integração do portal de cotações (class: IntegrationPortalQuoteIN) e
        utilizado para armazenar as requisições de produtos efetuada pelos clientes,
        assim como a resposta efetuada pelos vendedores.
        Sua estrutura a nível de negócio existe de duas formas:
        1. a nível de item, sendo o item entendido como as informações advindas da integração com a requisição do cliente.
        2. a nível de resposta, sendo a resposta entendida como as informações enviadas do vendedor para o cliente como resposta.
        Esse objeto pode ser visualizado a nível de usuário nas telas de orçamento do tipo portal (Opportunity > RecordType > OrcamentoPortal),
        que é o mestre do relacionamento mestre-detalhe contido nesse objeto.
        O item é enviado ao portal como resposta na integração do portal de cotação (class: IntegrationPortalQuoteOUT).
        E também é enviado quando é efetuado vínculo de produto (class: IntegrationPortalVinculoOUT)
    </description>
    <label>Item da Cotação</label>
    <nameField>
        <label>Nome do Item da Cotação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens da Cotação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <description>Cnpj do centro de distribuição vinculado</description>
    <label>CNPJ do CD</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <description>relacionamento mestre detalhe, orçamento, cotação, opportunidade referente ao item.</description>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Itens da Cotação</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/OpportunityLineItem__c.field-meta.xml
<CustomField>
    <fullName>OpportunityLineItem__c</fullName>
    <description>
        Quando existe oferta para o QuoteItem__c em questão é criado um OpportunityLineItem com as informações do QuoteItem__c
        Esse item que foi criado fica relacionado por meio desse campo.
    </description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto de oportunidade</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Items da Cotação</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>produto vinculado a resposta.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Items da Cotação</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/ConditionPaymentBudgetController.cls
public without sharing class ConditionPaymentBudgetController {
    @AuraEnabled
    public static StandardResponse getConditionPayment(String oppId){
        StandardResponse response = new StandardResponse();
        List<String> cnpjList = new List<String>();
        List<BudgetCtrl.DistCenterDTO> responsedata = new List<BudgetCtrl.DistCenterDTO>();
        try {
            List<CondicaoPagamentoPorCD__c> condPayCDlist = BudgetDetailSelector.getCondicaoPagamentoPorCD(oppId);
            for(CondicaoPagamentoPorCD__c conpg : condPayCDlist){
                cnpjList.add(conpg.CNPJCD__c);
            }
            Map<String,BudgetCtrl.SomatoriaDTO> sumaryMap = getSumaryResponse(oppId, cnpjList);
            for(CondicaoPagamentoPorCD__c cd : condPayCDlist){
                if(sumaryMap.containsKey(cd.CNPJCD__c)){
                    BudgetCtrl.DistCenterDTO distCenter = new BudgetCtrl.DistCenterDTO(sumaryMap.get(cd.CNPJCD__c), cd);
                    responsedata.add(distCenter);
                }
            }
            response.setData(JSON.serialize(responsedata));
           
        } catch (Exception ex) {
            ExceptionUtils.debug(ex);
            response.addError(ex.getMessage());
        }
        
        return response;
    }

    public static Map<String,BudgetCtrl.SomatoriaDTO> getSumaryResponse(String oppId, List<String> CNPJList){
        Map<String,BudgetCtrl.SomatoriaDTO> response = new Map<String,BudgetCtrl.SomatoriaDTO>();
        Decimal AmountOK = 0;
        //response.resp = 0;
        //response.totItem = 0;
        
        for(List<QuoteItem__c> listOli: [
            SELECT OpportunityLineItem__r.QuantidadePortal__c, OpportunityLineItem__r.ValorPortal__c,
            OpportunityLineItem__r.CNPJCD__c, OpportunityId__r.QuantidadeItensTotal__c  
            FROM QuoteItem__c 
            WHERE Product__c != null 
            AND OpportunityLineItem__c != null
            AND OpportunityId__c =: oppId ORDER BY Product__c
        ]){
            
            for(QuoteItem__c oli: listOli){
                if(response.get(oli.OpportunityLineItem__r.CNPJCD__c) == null){
                    response.put(oli.OpportunityLineItem__r.CNPJCD__c, new BudgetCtrl.SomatoriaDTO());

                    response.get(oli.OpportunityLineItem__r.CNPJCD__c).resp = 0;
                    response.get(oli.OpportunityLineItem__r.CNPJCD__c).totItem = 0;
                    response.get(oli.OpportunityLineItem__r.CNPJCD__c).qtdItensTotal = 0;
                }
                
                Decimal qntPortal = oli.OpportunityLineItem__r.QuantidadePortal__c != null ? oli.OpportunityLineItem__r.QuantidadePortal__c : 0;
                Decimal valuePortal = oli.OpportunityLineItem__r.ValorPortal__c != null ? oli.OpportunityLineItem__r.ValorPortal__c : 0;
                Decimal totItem = qntPortal * valuePortal; 
                AmountOK += totItem;

                if(!CNPJList.isEmpty() && CNPJList.contains(oli.OpportunityLineItem__r?.CNPJCD__c)){
                    response.get(oli.OpportunityLineItem__r.CNPJCD__c).totItem += totItem;
                    response.get(oli.OpportunityLineItem__r.CNPJCD__c).qtdItensTotal = oli.OpportunityId__r.QuantidadeItensTotal__c;
                    response.get(oli.OpportunityLineItem__r.CNPJCD__c).resp++;
                }
            }
        }
        
        if(AmountOK != 0){
            try {
                Opportunity opp = new Opportunity();
                opp.Id = oppId;
                opp.TotalPortal__c = AmountOK.setScale(6, RoundingMode.HALF_UP);
                update opp;
            } catch (Exception ex) {}
        }
        for(BudgetCtrl.SomatoriaDTO resp : response.values()){
            resp.totItem = resp.totItem.setScale(6, RoundingMode.HALF_UP);
        }

        return response;
    }

}