Git Tests/force-app/main/default/default/objects/Fornecedor__c/Fornecedor__c.object-meta.xml
<CustomObject>
    <label>Fornecedor</label>
    <nameField>
        <label>Nome do fornecedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fornecedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/IdPortal__c.field-meta.xml
<CustomField>
    <fullName>IdPortal__c</fullName>
    <externalId>true</externalId>
    <label>Id Portal</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/CategoriaComercial__c.field-meta.xml
<CustomField>
    <fullName>CategoriaComercial__c</fullName>
    <formula>TEXT(PricebookEntry.Product2.CategoriaComercial__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Categoria comercial</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/FatorConversao__c.field-meta.xml
<CustomField>
    <fullName>FatorConversao__c</fullName>
    <label>Fator de Conversao</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <formula>PricebookEntry.Product2.Fornecedor__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fornecedor</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/IdPortal__c.field-meta.xml
<CustomField>
    <fullName>IdPortal__c</fullName>
    <description>Id do item no Portal de Cotações.</description>
    <externalId>true</externalId>
    <label>Id do Portal</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/TipoConversao__c.field-meta.xml
<CustomField>
    <fullName>TipoConversao__c</fullName>
    <label>Tipo de conversão</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NENHUMA</fullName>
                <default>true</default>
                <label>NENHUMA</label>
            </value>
            <value>
                <fullName>MULTIPLICAR</fullName>
            </value>
            <value>
                <fullName>DIVIDIR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/ValorTotal__c.field-meta.xml
<CustomField>
    <fullName>ValorTotal__c</fullName>
    <label>Valor total</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/CategoriaComercial__c.field-meta.xml
<CustomField>
    <fullName>CategoriaComercial__c</fullName>
    <label>Categoria comercial</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>G</fullName>
                <label>GENÉRICO</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>MATERIAIS</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>NUTRIÇÃO</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Medctech</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>REFERÊNCIA</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>AMBOS</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>DIABETES</label>
            </value>
            <value>
                <fullName>Q</fullName>
                <label>ODONTOLOGIA</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Especialidade</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <label>EQUIPAMENTO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/FatorConversao__c.field-meta.xml
<CustomField>
    <fullName>FatorConversao__c</fullName>
    <label>Fator de conversão</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fornecedor</label>
    <referenceTo>Fornecedor__c</referenceTo>
    <relationshipLabel>Produtos</relationshipLabel>
    <relationshipName>Produtos</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/TipoConversao__c.field-meta.xml
<CustomField>
    <fullName>TipoConversao__c</fullName>
    <label>Tipo de conversão</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>M</fullName>
                <label>Multiplicação</label>
            </value>
            <value>
                <fullName>D</fullName>
                <label>Divisão</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>Nenhuma</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/UnidadeMedida__c.field-meta.xml
<CustomField>
    <fullName>UnidadeMedida__c</fullName>
    <label>Unidade de medida</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <description>
        Objeto recebido na integração do portal de cotações (class: IntegrationPortalQuoteIN) e
        utilizado para armazenar as requisições de produtos efetuada pelos clientes,
        assim como a resposta efetuada pelos vendedores.
        Sua estrutura a nível de negócio existe de duas formas:
        1. a nível de item, sendo o item entendido como as informações advindas da integração com a requisição do cliente.
        2. a nível de resposta, sendo a resposta entendida como as informações enviadas do vendedor para o cliente como resposta.
        Esse objeto pode ser visualizado a nível de usuário nas telas de orçamento do tipo portal (Opportunity > RecordType > OrcamentoPortal),
        que é o mestre do relacionamento mestre-detalhe contido nesse objeto.
        O item é enviado ao portal como resposta na integração do portal de cotação (class: IntegrationPortalQuoteOUT).
        E também é enviado quando é efetuado vínculo de produto (class: IntegrationPortalVinculoOUT)
    </description>
    <label>Item da Cotação</label>
    <nameField>
        <label>Nome do Item da Cotação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens da Cotação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/FatorConversao__c.field-meta.xml
<CustomField>
    <fullName>FatorConversao__c</fullName>
    <description>
        campo utilizado para armazenar o fator de conversão inputado pelo vendedor durante a resposta cotada
        Também pode ser visto como a quantidade presente em caixa caso o valor do TipoConversao__c seja Dividir
    </description>
    <label>Fator de Conversao</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/IdPortal__c.field-meta.xml
<CustomField>
    <fullName>IdPortal__c</fullName>
    <description>Id do item no Portal de Cotações (hash), não vem da integradora, é criado para cada item dentro do portal.</description>
    <externalId>true</externalId>
    <label>Id do Portal</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <description>relacionamento mestre detalhe, orçamento, cotação, opportunidade referente ao item.</description>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Itens da Cotação</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/ProdutosVinculadosAnteriormente__c.field-meta.xml
<CustomField>
    <fullName>ProdutosVinculadosAnteriormente__c</fullName>
    <description>JSON de produtos que estavam vinculados a mesma requisição (mesmo IdCustomer__c) em outras cotações.</description>
    <label>Produtos Vinculados Anteriormente</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/TipoConversao__c.field-meta.xml
<CustomField>
    <fullName>TipoConversao__c</fullName>
    <description>Tipo de conversão usada pelo vendedor para transformar a unidade de medida elfa na unidade que o cliente solicitou.</description>
    <label>Tipo de conversão</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>NENHUMA</fullName>
                <default>true</default>
                <label>NENHUMA</label>
            </value>
            <value>
                <fullName>MULTIPLICAR</fullName>
            </value>
            <value>
                <fullName>DIVIDIR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/ValorTotal__c.field-meta.xml
<CustomField>
    <fullName>ValorTotal__c</fullName>
    <description>UnitPrice__c * Quantity__c</description>
    <label>Valor Total</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/BudgetHistoricoVinculosController.cls
public with sharing class BudgetHistoricoVinculosController {
    @AuraEnabled
    public static StandardResponse getHistoricoVinculos(String idPortalItem, String oppId){
        StandardResponse response = new StandardResponse();
        
        if(String.isBlank(idPortalItem)){
            return response.addError('É necessário o IdPortal__c do item para consultar o histórico de vínculos.');
        }
        try {

            List<VinculoData> historicoList = new List<VinculoData>();
            QuoteItem__c qItem = BudgetDetailSelector.getQuoteitemWithHistory(idPortalItem, oppId);
            if(
                qItem != null &&
                String.isNotEmpty(qItem.ProdutosVinculadosAnteriormente__c) &&
                qItem.ProdutosVinculadosAnteriormente__c != '[]'
            ){
                List<VinculoDataDTO> vinculoList = (List<VinculoDataDTO>)JSON.deserialize(qItem.ProdutosVinculadosAnteriormente__c, List<VinculoDataDTO>.class);
                Map<String, VinculoDataDTO> vinculoByProdCodeMap = new Map<String, VinculoDataDTO>(); 
                for(VinculoDataDTO vinculo : vinculoList){
                    vinculoByProdCodeMap.put(vinculo.codigoProdutoERP, vinculo);
                }
                Map<Id, Product2> productMap = BudgetDetailSelector.getProductMapFromCode(vinculoByProdCodeMap.keySet());
                Map<String, Product2> productMapByCode = new Map<String, Product2>();
                for(Product2 prod : productMap.values()){
                    productMapByCode.put(prod.ProductCode, prod);
                }

                List<AggregateResult> estoqueAggregateList = BudgetDetailSelector.getEstoqueAggregated(
                    qItem.OpportunityId__r.AccountId,
                    productMap.keySet()
                );
                Map<String, Decimal> estoqueMap = BudgetDetailController.processEstoqueAggregated(estoqueAggregateList);
                    system.debug(qItem.OpportunityId__r.AccountId);
                    system.debug(productMap.keySet());
                    
                List<AggregateResult> oppLineItemAggrList = BudgetDetailSelector.getLastOpportunityLineItemAggr(qItem.OpportunityId__r.AccountId, productMap.keySet());
                Map<String, String> mapLastOLIByProdCode = processOppLineItemAggregated(oppLineItemAggrList);
                Map<Id, OpportunityLineItem> oppLineItemMap = BudgetDetailSelector.getLastOpportunityLineItemMap(mapLastOLIByProdCode.values());
                
                for(Product2 product : productMapByCode.values()){
                    OpportunityLineItem oppLineItem = mapLastOLIByProdCode.get(product.ProductCode) != null ? oppLineItemMap.get(mapLastOLIByProdCode.get(product.ProductCode)) : null;
                    historicoList.add(new VinculoData(
                        vinculoByProdCodeMap.get(product.ProductCode),
                        product,
                        estoqueMap.get(product.ProductCode),
                        oppLineItem
                    ));
                }
            }
            response.setData('vinculos', historicoList);

        }catch(Exception ex) {
            ExceptionUtils.debug(ex);
            response.addError(ex.getMessage());
        }
        return response;
    }

    public static Map<String, String> processOppLineItemAggregated(List<AggregateResult> oppLineItemAggrList){
        Map<String, String> oppLineItemMap = new Map<String, String>();
        for(AggregateResult aggrResult : oppLineItemAggrList){
            oppLineItemMap.put((String)aggrResult.get('ProductCode'), (String)aggrResult.get('id'));
        }
        return oppLineItemMap;
    }

    public class VinculoDataDTO {
        public String codigoProdutoERP;	//123
        public String bu;	//Materiais
        public String mesa;	//A
        public String vendedor;	//001234
        public String createdAt;	//2021-11-11T12:14:19.000Z
        public String updateAt;
        public Decimal fatorConversao;
        public String tipoConversaoUnidadeMedida;
    }

    public class VinculoData {
        @AuraEnabled public String idCustomer;
        @AuraEnabled public String nome;
        @AuraEnabled public String id;
        @AuraEnabled public String estoque;
        @AuraEnabled public String prodCode;
        @AuraEnabled public String unidadePrincipal;
        //@AuraEnabled public Decimal quantidadeCx; ainda não foi decidido
        @AuraEnabled public String principioAtivo;
        @AuraEnabled public String fornecedor;
        @AuraEnabled public String lastOferDate;
        @AuraEnabled public String lastOferStage;
        @AuraEnabled public Decimal lastOferAmount;
        @AuraEnabled public String tipoConversao;
        @AuraEnabled public Decimal fatorConversao;
        @AuraEnabled public String CategoriaComercial;
        @AuraEnabled public String createdAt;
        @AuraEnabled public String updateAt;

        // usado para mostrar os valores de um único item solicitado, getHistoricoVinculos
        public VinculoData(VinculoDataDTO vinculo, Product2 prod, Decimal estoqueValue, OpportunityLineItem lastItem) {
            
            this.nome               = prod.Name;
            this.id                 = prod.Id;
            this.prodCode           = prod.ProductCode;
            this.unidadePrincipal   = prod.UnidadeMedida__c;
            this.principioAtivo     = prod.Description;
            this.fornecedor         = prod.Fornecedor__r?.Name;
            this.CategoriaComercial = prod.CategoriaComercial__c;
            this.estoque = estoqueValue == null ? 'Informação não disponível' : String.valueOf(estoqueValue);
            
            if(vinculo != null){
                this.fatorConversao     = vinculo.fatorConversao;
                this.tipoConversao      = vinculo.tipoConversaoUnidadeMedida;
                this.createdAt = String.isNotBlank(vinculo.createdAt) ? vinculo.createdAt : null;
                this.updateAt = String.isNotBlank(vinculo.updateAt) ? vinculo.updateAt : null;
            }

            if(lastItem != null){
                
                this.fatorConversao         = lastItem.FatorConversao__c;
                this.tipoConversao          = lastItem.TipoConversao__c;
                this.lastOferDate           = lastItem.CreatedDate.formatGMT('dd/MM/yyyy');
                this.lastOferAmount         = lastItem.ValorTotal__c > 0 ? lastItem.ValorTotal__c : lastItem.UnitPrice;
                this.lastOferStage          = lastItem.Opportunity.Probability == 100 ? 'Ganha' : 'Perdida';
            }

        }
    }
}