Git Tests/force-app/main/default/default/objects/CondicaoPagamento__c/CondicaoPagamento__c.object-meta.xml
<CustomObject>
    <label>Condição de pagamento</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condições de pagamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Integracoes__c/Integracoes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuração  personalizada utilizada para gerir os dados de acessos das integrações</description>
    <label>Integrações</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <inlineHelpText>URL de acesso ao serviço</inlineHelpText>
    <label>EndPoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Método</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Senha</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>Usuário</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CodigoIntegradora__c.field-meta.xml
<CustomField>
    <fullName>CodigoIntegradora__c</fullName>
    <externalId>true</externalId>
    <label>Código integradora</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Chave única: Número do pedido + Código do CD</description>
    <externalId>true</externalId>
    <label>Código do pedido TOTVS</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/Laboratorio__c.field-meta.xml
<CustomField>
    <fullName>Laboratorio__c</fullName>
    <label>Laboratório</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/MensagemNF__c.field-meta.xml
<CustomField>
    <fullName>MensagemNF__c</fullName>
    <label>Mensagem da NF</label>
    <type>TextArea</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/RejeicaoProcesso__c.field-meta.xml
<CustomField>
    <fullName>RejeicaoProcesso__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Rejeição do processo?</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/SolicitacaoAprovada__c.field-meta.xml
<CustomField>
    <fullName>SolicitacaoAprovada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Solicitação Aprovada</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/StatusAprovacao__c.field-meta.xml
<CustomField>
    <fullName>StatusAprovacao__c</fullName>
    <label>Status de aprovação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>StatusAprovacao</valueSetName>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/PedidoIntegradora__c/PedidoIntegradora__c.object-meta.xml
<CustomObject>
    <label>Pedido de integradora</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Nome de Pedido de integradora</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pedidos de integradora</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/PedidoIntegradora__c/fields/AprovadoParcial__c.field-meta.xml
<CustomField>
    <fullName>AprovadoParcial__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Aprovado Parcial</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/PedidoIntegradora__c/fields/CodigoIntegradora__c.field-meta.xml
<CustomField>
    <fullName>CodigoIntegradora__c</fullName>
    <externalId>true</externalId>
    <label>Código integradora</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/PedidoIntegradora__c/fields/EnviadoAprovacao__c.field-meta.xml
<CustomField>
    <fullName>EnviadoAprovacao__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enviado aprovação</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/PedidoIntegradora__c/fields/Laboratorio__c.field-meta.xml
<CustomField>
    <fullName>Laboratorio__c</fullName>
    <label>Laboratório</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/PedidoIntegradora__c/fields/Pedido__c.field-meta.xml
<CustomField>
    <fullName>Pedido__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Pedidos de integradora</relationshipLabel>
    <relationshipName>PedidosIntegradora</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/PedidoIntegradora__c/fields/RejeicaoProcesso__c.field-meta.xml
<CustomField>
    <fullName>RejeicaoProcesso__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Rejeição processo</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/PedidoIntegradora__c/fields/SolicitacaoAprovada__c.field-meta.xml
<CustomField>
    <fullName>SolicitacaoAprovada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Solicitação aprovada</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/PedidoIntegradora__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando análise</fullName>
            </value>
            <value>
                <fullName>Aguardando confirmação do Protheus</fullName>
            </value>
            <value>
                <fullName>Erro de integração</fullName>
            </value>
            <value>
                <fullName>Pedido gerado</fullName>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
            <value>
                <fullName>Aprovado na integradora</fullName>
            </value>
            <value>
                <fullName>Reprovado na integradora</fullName>
            </value>
            <value>
                <fullName>Aguardando envio de cancelamento</fullName>
            </value>
            <value>
                <fullName>Aguardando aprovação comercial</fullName>
            </value>
            <value>
                <fullName>Aprovado comercial</fullName>
            </value>
            <value>
                <fullName>Reprovado comercial</fullName>
            </value>
            <value>
                <fullName>Aguardando confirmação de cancelamento</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/PedidoIntegradora__c/fields/StatusAprovacao__c.field-meta.xml
<CustomField>
    <fullName>StatusAprovacao__c</fullName>
    <label>Status de aprovação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/PedidoIntegradora__c/fields/TipoIntegradora__c.field-meta.xml
<CustomField>
    <fullName>TipoIntegradora__c</fullName>
    <label>Tipo integradora</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/globalValueSets/StatusAprovacao.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Em digitação</fullName>
    </customValue>
    <customValue>
        <fullName>Em aprovação</fullName>
    </customValue>
    <customValue>
        <fullName>Aprovado</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelado</fullName>
    </customValue>
    <description>Valores de status para os processos de aprovação de orçamento e pedido.</description>
    <masterLabel>Status de aprovação</masterLabel>
</GlobalValueSet>

Git Tests/force-app/main/default/default/classes/IntegrationLaboratoryOrderOUT.cls
global without sharing class IntegrationLaboratoryOrderOUT {

    global class LaboratoryRequest {
        public String  TpInteg;
        public String  PedidoIntegrador;
        public Boolean aprovado;
        public String  CondicaoPagamento;
        public String  ObsNF;
        public String  FaturaParcial;
        public String  Laboratorio;

        public LaboratoryRequest(PedidoIntegradora__c lab, String partialInvoice) {
            this.TpInteg            = lab.TipoIntegradora__c;
            this.Laboratorio        = lab.Laboratorio__c;
            this.PedidoIntegrador   = lab.CodigoIntegradora__c;
            this.aprovado           = lab.StatusAprovacao__c == 'Aprovado';
            this.CondicaoPagamento  = lab.Pedido__r?.CondicaoPagamento__r?.ExternalId__c == null ? '' : lab.Pedido__r?.CondicaoPagamento__r?.ExternalId__c;
            this.ObsNF              = lab.Pedido__r?.MensagemNF__c == null ? '' : lab.Pedido__r?.MensagemNF__c;
            this.FaturaParcial      = partialInvoice;
        }
    }

    global class ResultClass{
        public String  result   { get; set; }
    }

    @InvocableMethod(label='Approve or reject laboratory order' description=' Method to approve or reject laboratory order')
    public static List<String> ApproveRejectLaboratoryOrder(List<FlowInputs> flowInputs){
        Id labId          = null;
        Boolean isApprove = true;
        String partialInvoice = '';
        for (FlowInputs flowInput : flowInputs) {
            labId     = flowInput.labId;
            isApprove = flowInput.isApprove;
            partialInvoice = flowInput.partialInvoice;
        }

        PedidoIntegradora__c lab = new PedidoIntegradora__c(
            Id                 = labId,
            StatusAprovacao__c = isApprove ? 'Aprovado' : 'Reprovado',
            AprovadoParcial__c = partialInvoice == 'S' ? true : false
        );

        if (validateUserApprover(labId)) {

            PedidoIntegradoraHandler.disableTrigger();
            update lab;
            PedidoIntegradoraHandler.enableTrigger();
            System.enqueueJob(new IntegrationLaboratoryOrderQueueable(0, new List<Id>{labId}, partialInvoice));

            return new List<String>{'Success'};

        }else{
            
            return null;
        }
        
        //return null;
    }

    public static void sendLaboratoryToERP(Id labId, String partialInvoice) {
        
        Integracoes__c integration = Integracoes__c.getValues('ElfaLaboratoryOrderAPI');        
        String method              = integration.Method__c;
        String endpoint            = integration.Endpoint__c;
        String username            = integration.User__c;
        String password            = integration.Password__c;
        
        HttpRequest req = new HttpRequest();
        req.setEndpoint(endpoint);
        req.setHeader('Authorization', 'Basic ' + EncodingUtil.base64Encode(Blob.valueOf(username + ':' + password)));
        req.setHeader('Content-Type', 'application/json;charset=UTF-8');
        req.setMethod(method);
        req.setTimeout(120000);

        System.debug(EncodingUtil.base64Encode(Blob.valueOf(username + ':' + password)));

        LaboratoryRequest labReq;

        for (PedidoIntegradora__c lab : [
                                            SELECT 
                                                Id, 
                                                CodigoIntegradora__c, 
                                                TipoIntegradora__c, 
                                                Laboratorio__c,
                                                Status__c, 
                                                StatusAprovacao__c,
                                                Pedido__r.CondicaoPagamento__r.ExternalId__c,
                                                Pedido__r.MensagemNF__c
                                            FROM PedidoIntegradora__c 
                                            WHERE Id = :labId
                                        ]) {
            labReq = new LaboratoryRequest(lab, partialInvoice);
        }

        System.debug('labReq: ' + labReq);

        String body;
        body = Json.serialize(labReq);
        System.debug('Body: '+ body);

        String resultString = '';
        HttpResponse resp = new HttpResponse();
        try {
            req.setBody(body);
            resp = new Http().send(req);
            
            System.debug(resp);
            System.debug(resp.getStatusCode());
            
            resultString = resp.getBody();
            System.debug('resp' + resultString);
            Boolean hasError = false;

            if (resp.getStatusCode() == 200 || resp.getStatusCode() == 201) {        
                resultString = resp.getBody();
                IntegrationUtils.WSLog('Pedido Integradora', 'Outbound', body, resultString, false);
            } else {
                resultString = resp.getBody();
                IntegrationUtils.WSLog('Pedido Integradora', 'Outbound', body, resultString, true);
                hasError = true;
            }

            ResultClass resClass = null;
            try {
                resClass = (ResultClass)JSON.deserialize(resultString, ResultClass.class);                
            } catch (Exception e) {
                hasError = true;
                System.debug(e.getMessage());
            }            

            PedidoIntegradora__c lab = new PedidoIntegradora__c(
                Id        = labId,
                EnviadoAprovacao__c = true,
                Status__c = hasError ? 'Erro de integração' : (labReq.aprovado ? 'Aguardando confirmação do Protheus' : 'Reprovado')
            );
            // if (labReq.aprovado) {
            //     lab.SolicitacaoAprovada__c = true;
            // } else {
            //     lab.RejeicaoProcesso__c = true;
            // }
            PedidoIntegradoraHandler.disableTrigger();
            update lab;
            PedidoIntegradoraHandler.enableTrigger();

        } catch (Exception e) {
            resultString = e.getMessage();
            System.debug(resultString);
        }
    }

    public class FlowInputs{
    
        @InvocableVariable
        public String labId;
        
        @InvocableVariable
        public Boolean isApprove;
        
        @InvocableVariable
        public String partialInvoice;
    }

    public static Boolean validateUserApprover(Id labId) {

        Boolean isApprover = false;
        List<ProcessInstance> lstApp = [SELECT Id, (SELECT Id, Actor.name, ActorId, ProcessInstanceId FROM Workitems)
        FROM ProcessInstance  WHERE TargetObjectId =:labId];

        if (lstApp.size() > 0) {

            for (ProcessInstance processInstance : lstApp) {

                if (processInstance.Workitems.size() > 0) {

                    for (ProcessInstanceWorkitem  workItems : processInstance.Workitems) {

                        if (UserInfo.getUserId().equals(workItems.ActorId)) {
                            
                            isApprover = true;
                            break;
                        }
                        
                    }

                    if (isApprover) {
                        break;
                    }                    
                }                
            }            
        }

        return isApprover; 
     }
}