Git Tests/force-app/main/default/default/objects/CondicaoPagamento__c/CondicaoPagamento__c.object-meta.xml
<CustomObject>
    <label>Condição de pagamento</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condições de pagamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Integracoes__c/Integracoes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuração  personalizada utilizada para gerir os dados de acessos das integrações</description>
    <label>Integrações</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <inlineHelpText>URL de acesso ao serviço</inlineHelpText>
    <label>EndPoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Método</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Senha</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>Usuário</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Chave única: Número do pedido + Código do CD</description>
    <externalId>true</externalId>
    <label>Código do pedido TOTVS</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/MensagemNF__c.field-meta.xml
<CustomField>
    <fullName>MensagemNF__c</fullName>
    <label>Mensagem da NF</label>
    <type>TextArea</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/PedidoIntegradora__c/PedidoIntegradora__c.object-meta.xml
<CustomObject>
    <label>Pedido de integradora</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Nome de Pedido de integradora</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pedidos de integradora</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/PedidoIntegradora__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando análise</fullName>
            </value>
            <value>
                <fullName>Aguardando confirmação do Protheus</fullName>
            </value>
            <value>
                <fullName>Erro de integração</fullName>
            </value>
            <value>
                <fullName>Pedido gerado</fullName>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
            <value>
                <fullName>Aprovado na integradora</fullName>
            </value>
            <value>
                <fullName>Reprovado na integradora</fullName>
            </value>
            <value>
                <fullName>Aguardando envio de cancelamento</fullName>
            </value>
            <value>
                <fullName>Aguardando aprovação comercial</fullName>
            </value>
            <value>
                <fullName>Aprovado comercial</fullName>
            </value>
            <value>
                <fullName>Reprovado comercial</fullName>
            </value>
            <value>
                <fullName>Aguardando confirmação de cancelamento</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/classes/IntegrationVansOrderOUT.cls
global without sharing class IntegrationVansOrderOUT {

    global class VansOrderRequest {
        public List<OrderRequest> pedidos;

        public VansOrderRequest() {
            this.pedidos = new List<OrderRequest>();
        }
    }
    
    global class OrderRequest {
        public String filial;
        public String NumeroPedido;
        public String CondicaoPagamento;
        public String Obs_NF;

        public OrderRequest(Order ord) {
            this.filial            = '';
            this.NumeroPedido      = ord.ExternalId__c;
            this.CondicaoPagamento = ord.CondicaoPagamento__r?.ExternalId__c;
            this.Obs_NF            = ord.MensagemNF__c;
        }
    }

    global class ResultClass{
        public String  result   { get; set; }
        public Boolean incluido { get; set; }
    }

    public static void sendVansOrderToERP(Id ordId) {
        
        Integracoes__c integration = Integracoes__c.getValues('ElfaVansOrderAPI');        
        String method              = integration.Method__c;
        String endpoint            = integration.Endpoint__c;
        String username            = integration.User__c;
        String password            = integration.Password__c;
        
        HttpRequest req = new HttpRequest();
        req.setEndpoint(endpoint);
        req.setHeader('Authorization', 'Basic ' + EncodingUtil.base64Encode(Blob.valueOf(username + ':' + password)));
        req.setHeader('Content-Type', 'application/json;charset=UTF-8');
        req.setMethod(method);
        req.setTimeout(120000);

        System.debug(EncodingUtil.base64Encode(Blob.valueOf(username + ':' + password)));

        VansOrderRequest labReq = new VansOrderRequest();

        for (Order ord : [
                            SELECT 
                                Id, 
                                ExternalId__c, 
                                CondicaoPagamento__r.ExternalId__c, 
                                MensagemNF__c
                            FROM Order 
                            WHERE Id = :ordId
                        ]) {
            labReq.pedidos.add(new OrderRequest(ord));
        }

        System.debug('labReq: ' + labReq);

        String body;
        body = Json.serialize(labReq);
        System.debug('Body: '+ body);

        String resultString = '';
        HttpResponse resp = new HttpResponse();
        try {
            req.setBody(body);
            resp = new Http().send(req);
            
            System.debug(resp);
            System.debug(resp.getStatusCode());
            
            resultString = resp.getBody();
            System.debug('resp' + resultString);
            Boolean hasError = false;

            if (resp.getStatusCode() == 200 || resp.getStatusCode() == 201) {        
                resultString = resp.getBody();
                IntegrationUtils.WSLog('Pedido Vans', 'Outbound', body, resultString, false);
            } else {
                resultString = resp.getBody();
                IntegrationUtils.WSLog('Pedido Vans', 'Outbound', body, resultString, true);
                hasError = true;
            }

            ResultClass resClass = null;
            try {
                resClass = (ResultClass)JSON.deserialize(resultString, ResultClass.class);                
            } catch (Exception e) {
                hasError = true;
                System.debug(e.getMessage());
            }

        } catch (Exception e) {
            resultString = e.getMessage();
            System.debug(resultString);
        }
    }

    @InvocableMethod(label='update laboratory order' description='Method to update laboratory order')
    public static List<String> updateLabOrder(List<FlowInputs> flowInputs){
        Id labId          = null;
        for (FlowInputs flowInput : flowInputs) {
            labId     = flowInput.labId;
        }
        PedidoIntegradora__c labOrd = new PedidoIntegradora__c();
        for (PedidoIntegradora__c lab : [SELECT Id, Status__c FROM PedidoIntegradora__c WHERE Id = :labId]) {
            lab.Status__c = 'Aguardando confirmação de cancelamento';
            labOrd = lab;
        }
        PedidoIntegradoraHandler.disableTrigger();
        update labOrd;
        PedidoIntegradoraHandler.enableTrigger();

        return null;
    }

    public class FlowInputs{
    
        @InvocableVariable
        public String labId;
    }
}