Git Tests/force-app/main/default/default/objects/CondicaoPagamento__c/CondicaoPagamento__c.object-meta.xml
<CustomObject>
    <label>Condição de pagamento</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condições de pagamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/CondicaoPagamentoPorCD__c.object-meta.xml
<CustomObject>
    <label>Condição de pagamento por CD</label>
    <nameField>
        <label>Nome de Condição de pagamento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condições de pagamentos por CD</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Condição de Pagamento CD</relationshipLabel>
    <relationshipName>CondicoesPagamento</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/Orcamento__c.field-meta.xml
<CustomField>
    <fullName>Orcamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Orçamento</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Condições de pagamentos por CD</relationshipLabel>
    <relationshipName>Condicespagamentospor_CD</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Fornecedor__c/Fornecedor__c.object-meta.xml
<CustomObject>
    <label>Fornecedor</label>
    <nameField>
        <label>Nome do fornecedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fornecedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Fornecedor__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do fornecedor</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Orcamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/IdPortal__c.field-meta.xml
<CustomField>
    <fullName>IdPortal__c</fullName>
    <externalId>true</externalId>
    <label>Id Portal</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Chave Externa</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <formula>PricebookEntry.Product2.Fornecedor__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fornecedor</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/IdPortal__c.field-meta.xml
<CustomField>
    <fullName>IdPortal__c</fullName>
    <description>Id do item no Portal de Cotações.</description>
    <externalId>true</externalId>
    <label>Id do Portal</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NÃO IDENTIFICADO</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>IDENTIFICADO</fullName>
            </value>
            <value>
                <fullName>QUALIFICADO</fullName>
            </value>
            <value>
                <fullName>Respondido</fullName>
            </value>
            <value>
                <fullName>Resgatado</fullName>
            </value>
            <value>
                <fullName>Aguardando Integração</fullName>
            </value>
            <value>
                <fullName>Falha na Integração</fullName>
            </value>
            <value>
                <fullName>Não Vinculado</fullName>
            </value>
            <value>
                <fullName>Vinculado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Pricebook2/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Catálogos de preços</relationshipLabel>
    <relationshipName>CatalogoPreco</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Pricebook2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do produto</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fornecedor</label>
    <referenceTo>Fornecedor__c</referenceTo>
    <relationshipLabel>Produtos</relationshipLabel>
    <relationshipName>Produtos</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/UnidadeMedida__c.field-meta.xml
<CustomField>
    <fullName>UnidadeMedida__c</fullName>
    <label>Unidade de medida</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <description>
        Objeto recebido na integração do portal de cotações (class: IntegrationPortalQuoteIN) e
        utilizado para armazenar as requisições de produtos efetuada pelos clientes,
        assim como a resposta efetuada pelos vendedores.
        Sua estrutura a nível de negócio existe de duas formas:
        1. a nível de item, sendo o item entendido como as informações advindas da integração com a requisição do cliente.
        2. a nível de resposta, sendo a resposta entendida como as informações enviadas do vendedor para o cliente como resposta.
        Esse objeto pode ser visualizado a nível de usuário nas telas de orçamento do tipo portal (Opportunity > RecordType > OrcamentoPortal),
        que é o mestre do relacionamento mestre-detalhe contido nesse objeto.
        O item é enviado ao portal como resposta na integração do portal de cotação (class: IntegrationPortalQuoteOUT).
        E também é enviado quando é efetuado vínculo de produto (class: IntegrationPortalVinculoOUT)
    </description>
    <label>Item da Cotação</label>
    <nameField>
        <label>Nome do Item da Cotação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens da Cotação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <description>Cnpj do centro de distribuição vinculado</description>
    <label>CNPJ do CD</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>OpportunityId__r.ExternalPortal__c + _ + IdPotal__c + _ + Vendedor__c + _ + Categoria__c</description>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Chave Externa</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/IdPortal__c.field-meta.xml
<CustomField>
    <fullName>IdPortal__c</fullName>
    <description>Id do item no Portal de Cotações (hash), não vem da integradora, é criado para cada item dentro do portal.</description>
    <externalId>true</externalId>
    <label>Id do Portal</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <description>relacionamento mestre detalhe, orçamento, cotação, opportunidade referente ao item.</description>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Itens da Cotação</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/OpportunityLineItem__c.field-meta.xml
<CustomField>
    <fullName>OpportunityLineItem__c</fullName>
    <description>
        Quando existe oferta para o QuoteItem__c em questão é criado um OpportunityLineItem com as informações do QuoteItem__c
        Esse item que foi criado fica relacionado por meio desse campo.
    </description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto de oportunidade</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Items da Cotação</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>produto vinculado a resposta.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Items da Cotação</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Identificador de condição da resposta, (Responde a pergunta: Em que estapa está a resposta?)</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NÃO IDENTIFICADO</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>IDENTIFICADO</fullName>
            </value>
            <value>
                <fullName>QUALIFICADO</fullName>
            </value>
            <value>
                <fullName>Respondido</fullName>
            </value>
            <value>
                <fullName>Resgatado</fullName>
            </value>
            <value>
                <fullName>Aguardando Integração</fullName>
            </value>
            <value>
                <fullName>Falha na Integração</fullName>
            </value>
            <value>
                <fullName>Não Vinculado</fullName>
                <default>true</default>
                <label>Não Vinculado</label>
            </value>
            <value>
                <fullName>Vinculado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/classes/BudgetPortalPDFControllerTest.cls
@IsTest 
public with sharing class BudgetPortalPDFControllerTest {
    @TestSetup
    static void makeData(){
        Opportunity opp = TestUtility.createOpportunity(new User(Id = UserInfo.getUserId()));
        insert opp;
        Fornecedor__c fornecedor = new Fornecedor__c(Name = 'testfor', ExternalId__c = '12345');
        insert fornecedor;

        Product2 product = TestUtility.createProduct();
        product.ExternalId__c = '1234';
        product.UnidadeMedida__c = 'F';
        product.fornecedor__c = fornecedor.Id;
        insert product;
        CondicaoPagamento__c conpag = TestUtility.createPaymentCondition();
        insert conpag;
        CondicaoPagamentoPorCD__c conpagCD = TestUtility.createCondicaoPagamentoPorCD(conpag);
        conpagCD.Orcamento__c = opp.Id;
        insert conpagCD;
        Pricebook2 pb2 = TestUtility.createPricebook2();
        pb2.ExternalId__c = 'B01';
        pb2.isActive = true;
        upsert pb2 Pricebook2.ExternalId__c;

        PricebookEntry pricebookEntry  = new PriceBookEntry(
            pricebook2Id = pb2.Id, 
            product2Id = product.Id,
            unitPrice = 10,
            isActive = true
        );
        insert pricebookEntry;

        OpportunityLineItem opportunityLineItem = TestUtility.createOpportunityLineItem(opp, product, pricebookEntry);
        opportunityLineItem.Status__c = 'Aguardando Integração';
        opportunityLineItem.CNPJCD__c = '52202744000788';
        

        OpportunityLineItem opportunityLineItem2 = TestUtility.createOpportunityLineItem(opp, product, pricebookEntry);
        opportunityLineItem2.CNPJCD__c = '52202744000788';
        opportunityLineItem2.Status__c = 'Respondido';
        insert new List<OpportunityLineItem>{opportunityLineItem, OpportunityLineItem2};

        QuoteItem__c quoteitem = TestUtility.createQuoteItem(opp, new User(Id = UserInfo.getUserId()));
        quoteitem.OpportunityLineItem__c = opportunityLineItem.Id;
        quoteitem.OpportunityId__c = opp.Id;
        quoteitem.Product__c = product.Id;
        quoteitem.idportal__c = '32443';
        quoteitem.Status__c = 'Vinculado';
        insert new List<QuoteItem__c> {quoteitem};
    }
    @IsTest
    static void BudgetPortalPDFControllerTest() {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        ApexPages.StandardController sc = new ApexPages.StandardController(opp);
        BudgetPortalPDFController testAccPlan = new BudgetPortalPDFController(sc);
        
        PageReference pageRef = Page.BudgetPortalPDF;
        pageRef.getParameters().put('id', String.valueOf(opp.Id));
        Test.setCurrentPage(pageRef);
    }
}