Git Tests/force-app/main/default/default/objects/Order/fields/AttachmentId__c.field-meta.xml
<CustomField>
    <fullName>AttachmentId__c</fullName>
    <externalId>true</externalId>
    <label>Comprovante de pagamento Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ComprovanteAnexado__c.field-meta.xml
<CustomField>
    <fullName>ComprovanteAnexado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Comprovante anexado</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/FileIntegrationStatus__c.field-meta.xml
<CustomField>
    <fullName>FileIntegrationStatus__c</fullName>
    <label>Status da integração de comprovante</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ok</fullName>
            </value>
            <value>
                <fullName>Erro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/PedidoPai__c.field-meta.xml
<CustomField>
    <fullName>PedidoPai__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido pai</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Pedidos filho</relationshipLabel>
    <relationshipName>PedidoFilho</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/StatusIntegracao__c.field-meta.xml
<CustomField>
    <fullName>StatusIntegracao__c</fullName>
    <label>Status da integração</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Integrado</fullName>
            </value>
            <value>
                <fullName>Não integrado</fullName>
            </value>
            <value>
                <fullName>Erro de aprovação/rejeição</fullName>
            </value>
            <value>
                <fullName>Nota fiscal cancelada</fullName>
            </value>
            <value>
                <fullName>Pedido em aberto</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por regra</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por crédito</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por estoque</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por crédito e estoque</fullName>
            </value>
            <value>
                <fullName>Pedido aguardando separação</fullName>
            </value>
            <value>
                <fullName>Pedido em separação</fullName>
            </value>
            <value>
                <fullName>Pedido separado/aguardando faturamento</fullName>
            </value>
            <value>
                <fullName>Pedido faturado</fullName>
            </value>
            <value>
                <fullName>Pedido com resíduo eliminado (sem faturamento)</fullName>
            </value>
            <value>
                <fullName>Pedido com resíduo eliminado (com faturamento)</fullName>
            </value>
            <value>
                <fullName>Pedido liberado</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado na alçada de desconto</fullName>
            </value>
            <value>
                <fullName>Pedido com SC</fullName>
            </value>
            <value>
                <fullName>Pedido aguardando saldo</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por regra de bonificação</fullName>
            </value>
            <value>
                <fullName>Pedido cancelado</fullName>
            </value>
            <value>
                <fullName>Pedido rejeitado no Salesforce</fullName>
            </value>
            <value>
                <fullName>Pedido rejeitado na alçada financeira</fullName>
            </value>
            <value>
                <fullName>Erro integração (Envio ao Protheus)</fullName>
            </value>
            <value>
                <fullName>Erro integração (geração do pedido no Protheus)</fullName>
            </value>
            <value>
                <fullName>Pedido aguardando envio/processamento do comprovante de pagamento RA</fullName>
            </value>
            <value>
                <fullName>Pedido aguardando aprovação de pagamento RA</fullName>
            </value>
            <value>
                <fullName>Pedido rejeitado na alçada de aprovação de pagamento RA</fullName>
            </value>
            <value>
                <fullName>Aguardando processamento na integradora</fullName>
            </value>
            <value>
                <fullName>Aprovado na integradora</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/classes/BatchPaymentAttachment.cls
global class BatchPaymentAttachment implements Database.batchable<sObject>, Database.stateful, Database.AllowsCallouts {
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([SELECT Id, OrderNumber, PedidoPai__r.Status, AttachmentId__c, FileIntegrationStatus__c, ComprovanteAnexado__c, StatusIntegracao__c, Status FROM Order WHERE AttachmentId__c != NULL AND FileIntegrationStatus__c != 'Ok' AND ComprovanteAnexado__c = true AND PedidoPai__r.Status = 'Aprovado' AND StatusIntegracao__c = 'Pedido aguardando envio/processamento do comprovante de pagamento RA' AND Status = 'Aguardando comprovante']);
    }

    global void execute(Database.BatchableContext BC, List<Order> scope) {
        Map<Id, Id> documentToOrder = new Map<Id, Id>();
        List<ContentDocument> attachmentList = new List<ContentDocument>();

        for (Order order : scope) {
            documentToOrder.put(order.AttachmentId__c, order.Id);
        }

        for (ContentDocument document : [SELECT Id, Title FROM ContentDocument WHERE Id IN: documentToOrder.keySet()]) {
            attachmentList.add(document);
        }

        if (!attachmentList.isEmpty()) {
            for (ContentDocument document : attachmentList) {
                String statusIntegration = IntegrationPaymentAttachment.sendAttachment(documentToOrder.get(document.Id));
                System.debug('Status Envio de Comprovante: ' + statusIntegration);
            }
        }
    }

    global void finish(Database.BatchableContext BC) {}
}