Git Tests/force-app/main/default/default/objects/Order/fields/CentroDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentroDistribuicao__c</fullName>
    <label>Centro de distribuição</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/MensagemErroIntegracao__c.field-meta.xml
<CustomField>
    <fullName>MensagemErroIntegracao__c</fullName>
    <label>Mensagem Erro Integração</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/ProdutoReserva__c.object-meta.xml
<CustomObject>
    <label>Produto da reserva</label>
    <nameField>
        <displayFormat>PR-{00000000}</displayFormat>
        <label>Nome de Produto da reserva</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Produtos da reserva</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/Reserva__c.field-meta.xml
<CustomField>
    <fullName>Reserva__c</fullName>
    <label>Reserva</label>
    <referenceTo>Reserva__c</referenceTo>
    <relationshipLabel>Produtos da reserva</relationshipLabel>
    <relationshipName>ProdutosReserva</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/StatusReserva__c.field-meta.xml
<CustomField>
    <fullName>StatusReserva__c</fullName>
    <label>Status da reserva</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando aprovação</fullName>
            </value>
            <value>
                <fullName>Ativa</fullName>
            </value>
            <value>
                <fullName>Rejeitada</fullName>
            </value>
            <value>
                <fullName>Aguardando integração</fullName>
            </value>
            <value>
                <fullName>Erro de integração</fullName>
            </value>
            <value>
                <fullName>Aguardando exclusão</fullName>
            </value>
            <value>
                <fullName>Expirada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Reserva__c/Reserva__c.object-meta.xml
<CustomObject>
    <label>Reserva</label>
    <nameField>
        <displayFormat>RE-{000000}</displayFormat>
        <label>Nome da reserva</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Reserva__c/fields/CentroDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentroDistribuicao__c</fullName>
    <externalId>true</externalId>
    <label>Centro de distribuição</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Reserva__c/fields/CodigoReserva__c.field-meta.xml
<CustomField>
    <fullName>CodigoReserva__c</fullName>
    <externalId>true</externalId>
    <label>Código da reserva</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Reserva__c/fields/FimReserva__c.field-meta.xml
<CustomField>
    <fullName>FimReserva__c</fullName>
    <label>Fim da reserva</label>
    <type>DateTime</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Reserva__c/fields/MensagemErroIntegracao__c.field-meta.xml
<CustomField>
    <fullName>MensagemErroIntegracao__c</fullName>
    <label>Mensagem de erro (integração)</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Reserva__c/fields/StatusReserva__c.field-meta.xml
<CustomField>
    <fullName>StatusReserva__c</fullName>
    <label>Status da reserva</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativa</fullName>
                <default>true</default>
                <label>Ativa</label>
            </value>
            <value>
                <fullName>Expirada</fullName>
            </value>
            <value>
                <fullName>Aguardando aprovação</fullName>
                <isActive>false</isActive>
                <label>Aguardando aprovação</label>
            </value>
            <value>
                <fullName>Aguardando envio de exclusão</fullName>
                <isActive>false</isActive>
                <label>Aguardando envio de exclusão</label>
            </value>
            <value>
                <fullName>Aguardando integração</fullName>
                <isActive>false</isActive>
                <label>Aguardando integração</label>
            </value>
            <value>
                <fullName>Aprovada</fullName>
                <isActive>false</isActive>
                <label>Aprovada</label>
            </value>
            <value>
                <fullName>Cancelada</fullName>
                <isActive>false</isActive>
                <label>Cancelada</label>
            </value>
            <value>
                <fullName>Em digitação</fullName>
                <isActive>false</isActive>
                <label>Em digitação</label>
            </value>
            <value>
                <fullName>Erro de integração</fullName>
                <isActive>false</isActive>
                <label>Erro de integração</label>
            </value>
            <value>
                <fullName>Integrado</fullName>
                <isActive>false</isActive>
                <label>Integrado</label>
            </value>
            <value>
                <fullName>Rejeitada</fullName>
                <isActive>false</isActive>
                <label>Rejeitada</label>
            </value>
            <value>
                <fullName>Vencida</fullName>
                <isActive>false</isActive>
                <label>Vencida</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/classes/BatchReservationIncAlt.cls
global class BatchReservationIncAlt implements Database.batchable<sObject>, Database.stateful, Database.AllowsCallouts{
    public IntegrationReservationOUT.ResultClass response;
    public List<Reserva__c> reservationList;

    global BatchReservationIncAlt() {}

    global Database.QueryLocator start(Database.BatchableContext BC) {
        // return Database.getQueryLocator([SELECT Id, CodigoReserva__c, FimReserva__c, CentroDistribuicao__c, MensagemErroIntegracao__c, StatusReserva__c FROM Reserva__c WHERE StatusReserva__c = :IntegrationConstants.STATUS_INTEGRATION_ERROR ORDER BY FimReserva__c DESC]);
        return Database.getQueryLocator([SELECT Id, Reserva__c FROM ProdutoReserva__c WHERE StatusReserva__c ='Erro de integração' ORDER BY Reserva__r.FimReserva__c DESC]);
    }
    
    global void execute(Database.BatchableContext BC, List<SObject> scope) {        
        List<ProdutoReserva__c> lstProdutoReserva  = (List<ProdutoReserva__c>) scope;
        List<Id> reservas = new List<Id>();

        for (ProdutoReserva__c pd : lstProdutoReserva) {
            
            reservas.add(pd.Reserva__c);
        }

        if (reservas.size() > 0) {
            reservationList = IntegrationReservationOUT.getReservations(reservas);
            response = IntegrationReservationOUT.sendReservationERP(reservationList, true);

        }
    }
    
    global void finish(Database.BatchableContext BC) {
        if (!Test.isRunningTest()) {
            IntegrationReservationOUT.updateReservationInt(reservationList,response);            
        }
	}
}