Git Tests/force-app/main/default/default/objects/Order/fields/CentroDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentroDistribuicao__c</fullName>
    <label>Centro de distribuição</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/Idportalcotacoes__c.field-meta.xml
<CustomField>
    <fullName>Idportalcotacoes__c</fullName>
    <externalId>true</externalId>
    <label>Id do portal de cotações</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/OrderListWonController.cls
public class OrderListWonController {
   
    @AuraEnabled
    public static StandardResponse getOrdersListWonFromCurrentUser(){        
        StandardResponse response = new StandardResponse();
                   
            for(List<Order> ordersList : [
                SELECT  Id, OrderNumber, AccountId, Account.Name, EffectiveDate, TotalAmount, Status, Idportalcotacoes__c, (select CentroDistribuicao__c from OrderItems)
                FROM    Order 
                WHERE   Status = 'Em digitação' 
                AND     OpportunityId IN (
                            SELECT  OpportunityId 
                            FROM    OpportunityTeamMember 
                            WHERE   UserId = :UserInfo.getUserId()
                        ) 
                LIMIT 49999
            ]){
                
                response.setData('records',ordersList);
            }
        
        return response;
    }

}