Git Tests/force-app/main/default/default/objects/Order/fields/CodigoIntegradora__c.field-meta.xml
<CustomField>
    <fullName>CodigoIntegradora__c</fullName>
    <externalId>true</externalId>
    <label>Código integradora</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ErroIntegracaoAprovacao__c.field-meta.xml
<CustomField>
    <fullName>ErroIntegracaoAprovacao__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Erro de integração Aprovação</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ErroIntegracaoCancelamento__c.field-meta.xml
<CustomField>
    <fullName>ErroIntegracaoCancelamento__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Erro de integração Cancelamento</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ErroIntegracaoConfirmacao__c.field-meta.xml
<CustomField>
    <fullName>ErroIntegracaoConfirmacao__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Erro de integração Confirmação</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ErroIntegracaoRejeitado__c.field-meta.xml
<CustomField>
    <fullName>ErroIntegracaoRejeitado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Erro de integração Rejeitado</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Chave única: Número do pedido + Código do CD</description>
    <externalId>true</externalId>
    <label>Código do pedido TOTVS</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/StatusIntegracao__c.field-meta.xml
<CustomField>
    <fullName>StatusIntegracao__c</fullName>
    <label>Status da integração</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Integrado</fullName>
            </value>
            <value>
                <fullName>Não integrado</fullName>
            </value>
            <value>
                <fullName>Erro de aprovação/rejeição</fullName>
            </value>
            <value>
                <fullName>Nota fiscal cancelada</fullName>
            </value>
            <value>
                <fullName>Pedido em aberto</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por regra</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por crédito</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por estoque</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por crédito e estoque</fullName>
            </value>
            <value>
                <fullName>Pedido aguardando separação</fullName>
            </value>
            <value>
                <fullName>Pedido em separação</fullName>
            </value>
            <value>
                <fullName>Pedido separado/aguardando faturamento</fullName>
            </value>
            <value>
                <fullName>Pedido faturado</fullName>
            </value>
            <value>
                <fullName>Pedido com resíduo eliminado (sem faturamento)</fullName>
            </value>
            <value>
                <fullName>Pedido com resíduo eliminado (com faturamento)</fullName>
            </value>
            <value>
                <fullName>Pedido liberado</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado na alçada de desconto</fullName>
            </value>
            <value>
                <fullName>Pedido com SC</fullName>
            </value>
            <value>
                <fullName>Pedido aguardando saldo</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por regra de bonificação</fullName>
            </value>
            <value>
                <fullName>Pedido cancelado</fullName>
            </value>
            <value>
                <fullName>Pedido rejeitado no Salesforce</fullName>
            </value>
            <value>
                <fullName>Pedido rejeitado na alçada financeira</fullName>
            </value>
            <value>
                <fullName>Erro integração (Envio ao Protheus)</fullName>
            </value>
            <value>
                <fullName>Erro integração (geração do pedido no Protheus)</fullName>
            </value>
            <value>
                <fullName>Pedido aguardando envio/processamento do comprovante de pagamento RA</fullName>
            </value>
            <value>
                <fullName>Pedido aguardando aprovação de pagamento RA</fullName>
            </value>
            <value>
                <fullName>Pedido rejeitado na alçada de aprovação de pagamento RA</fullName>
            </value>
            <value>
                <fullName>Aguardando processamento na integradora</fullName>
            </value>
            <value>
                <fullName>Aprovado na integradora</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/classes/BatchResendOrder.cls
global class BatchResendOrder implements Database.batchable<sObject>, Database.stateful, Database.AllowsCallouts{
    
    public static void executeBatch(Order ord) {
        Boolean approvalError = false;
        Boolean cancellingError = false;
        Boolean confirmingError = false;
        Boolean rejectionError = false;
        Set<String> invalidIntegrationStatus = new Set<String>{'Bloqueado ERP', 'Liberado ERP', 'Aguardando separação', 'Separado', 'Faturado', 'Cancelado','Aguardando envio de cancelamento'};
        System.debug('ord: '+ord);
        List<Order> orderList = new List<Order>{ord};
        Id ordId = null;
        for (Order o : orderList){
            ordId = o.id;
            if (o.ErroIntegracaoConfirmacao__c && o.ExternalId__c == null) {
                System.debug('entrou ErroIntegracaoConfirmacao');
                confirmingError = true;
            } else if (o.ErroIntegracaoAprovacao__c && o.ExternalId__c != null && !invalidIntegrationStatus.contains(o.Status)) {
                System.debug('entrou ErroIntegracaoAprovacao');
                approvalError = true;
            } else if (o.ErroIntegracaoCancelamento__c && !invalidIntegrationStatus.contains(o.Status)) {
                System.debug('entrou ErroIntegracaoCancelamento');
                cancellingError = true;
            } else if (o.ErroIntegracaoRejeitado__c && o.ExternalId__c != null && !invalidIntegrationStatus.contains(o.Status)) {
                System.debug('entrou ErroIntegracaoRejeitado');
                rejectionError = true;
            }
        }
        if (ordId != null) {
            if (approvalError || rejectionError) {
                IntegrationApprovalOrderOUT.sendApprovalOrderToERP(ordId);
            } else if (cancellingError) {
                IntegrationCancelOrderOUT.FlowInputs flowInput = new IntegrationCancelOrderOUT.FlowInputs();
                flowInput.orderId = ordId;
                flowInput.reason = null;
                flowInput.subReason = null;
                flowInput.commentary = null;
                IntegrationCancelOrderOUT.sendCancelledOrder(new List<IntegrationCancelOrderOUT.FlowInputs>{flowInput});
            } else if (confirmingError) {
                IntegrationOrderOUT.sendOrderToERP(ordId);
            } 
        }
    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([SELECT Id, ErroIntegracaoAprovacao__c, ErroIntegracaoCancelamento__c, ErroIntegracaoConfirmacao__c, ErroIntegracaoRejeitado__c, ExternalId__c, StatusIntegracao__c, Status, CodigoIntegradora__c 
                                         FROM Order WHERE RecordTypeId != :OrderHelper.MOTHERORDER_RECORDTYPE AND CodigoIntegradora__c != null
                                                       AND (ErroIntegracaoAprovacao__c  = true 
                                                       OR ErroIntegracaoCancelamento__c = true 
                                                       OR ErroIntegracaoConfirmacao__c  = true
                                                       OR ErroIntegracaoRejeitado__c    = true
                                                       OR StatusIntegracao__c           = 'Não integrado')]);
    }
    
    global void execute(Database.BatchableContext BC, List<SObject> scope) {        
        List<Order> orderList = (List<Order>) scope;
        executeBatch(orderList[0]);
    }
    
    global void finish(Database.BatchableContext BC) {
		
	}
}