Git Tests/force-app/main/default/default/objects/Order/fields/CodigoIntegradora__c.field-meta.xml
<CustomField>
    <fullName>CodigoIntegradora__c</fullName>
    <externalId>true</externalId>
    <label>Código integradora</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Chave única: Número do pedido + Código do CD</description>
    <externalId>true</externalId>
    <label>Código do pedido TOTVS</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Número do item do pedido</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/ProdutoCampanha__c.field-meta.xml
<CustomField>
    <fullName>ProdutoCampanha__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Produto está em campanha?</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/ProdutoCampanhaDesc__c.field-meta.xml
<CustomField>
    <fullName>ProdutoCampanhaDesc__c</fullName>
    <label>Descrição do produto de campanha</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/IntegrationLabSonOrderItemIN.cls
public without sharing class IntegrationLabSonOrderItemIN {
    public static List<TemplateDataIntegrationFields.Response> upsertLabSonOrderItem(Map<String, List<TemplateDataIntegrationFields.LabSonOrderItemINData>> mapLabSonOrderItem, Map<String, Id> lookups, Map<String, String> mapCampToRule) {
        List<TemplateDataIntegrationFields.Response> responseList = new List<TemplateDataIntegrationFields.Response>();
        List<TemplateDataIntegrationFields.LabSonOrderItemINData> listLabSonOrderItemINData = new List<TemplateDataIntegrationFields.LabSonOrderItemINData>();
        List<OrderItem> listOrderItem = new List<OrderItem>();

        Set<String> setOrderExternalId = new Set<String>();
        Set<String> setOrderItemExternalId = new Set<String>();
        Set<String> descProdExternalId = new Set<String>();
        Set<String> setProduct2Id = new Set<String>();
        Set<String> setPricebook2Id = new Set<String>();
        Set<String> setPricebookKey = new Set<String>();

        for (String key : mapLabSonOrderItem.keySet()) {
            system.debug(key);
            for (TemplateDataIntegrationFields.LabSonOrderItemINData item : mapLabSonOrderItem.get(key)) {
                item.Chave = key;
                system.debug(item.PedidoFilho);
                setOrderExternalId.add(item.PedidoFilho);
                system.debug(item.Produto);
                system.debug(item.Tabela);
                descProdExternalId.add(item.Produto);
                setPricebookKey.add(item.Tabela);
                setOrderItemExternalId.add(item.PedidoFilho + '_' + item.Produto);
            }
        }

        // lookup para Pedido
        for(Order ord : [SELECT Id, ExternalId__c, CodigoIntegradora__c, Pricebook2Id FROM Order WHERE ExternalId__c IN: setOrderExternalId]){
            system.debug('ord.ExternalId__c: ' + ord.ExternalId__c);
            system.debug('ord.CodigoIntegradora__c: ' + ord.CodigoIntegradora__c);
            lookups.put('PedidoFilho' + ord.ExternalId__c, ord.Id);
            // lookups.put('CatalogoPedido'+ord.ExternalId__c.trim(), ord.Pricebook2Id);
        }

        for (String key : mapLabSonOrderItem.keySet()) {
            for (TemplateDataIntegrationFields.LabSonOrderItemINData ordItem : mapLabSonOrderItem.get(key)) {
                listLabSonOrderItemINData.add(ordItem);
            }
        }

        system.debug(listLabSonOrderItemINData);
        FactoryDataIntegration.convertSObject(new OrderItem(), 'IN', listLabSonOrderItemINData, responseList, listOrderItem, lookups);

        if (!listOrderItem.isEmpty()) {
            for (OrderItem ordItem: listOrderItem) {
                system.debug(ordItem.Product2Id);
                ordItem.ProdutoCampanhaDesc__c = mapCampToRule.get('ProdCampaignRule_' + ordItem.Product2Id);
                if (ordItem.ProdutoCampanhaDesc__c != null && ordItem.ProdutoCampanhaDesc__c != '') {
                    ordItem.ProdutoCampanha__c = true;
                }
            }
        }
        OrderHandler.disableTrigger();
        IntegrationUtils.upsertRecords(
            Database.upsert(listOrderItem, OrderItem.ExternalId__c, false), 
            responseList, 
            listOrderItem, 
            OrderItem.ExternalId__c
        );
        OrderHandler.enableTrigger();
            
        system.debug(responseList);

        return responseList;
    }
}