Git Tests/force-app/main/default/default/objects/Order/fields/DataEntrega__c.field-meta.xml
<CustomField>
    <fullName>DataEntrega__c</fullName>
    <label>Data prevista de entrega</label>
    <type>Date</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/ValorCx__c.field-meta.xml
<CustomField>
    <fullName>ValorCx__c</fullName>
    <inlineHelpText>Principal: Unidade de medida principal do produto</inlineHelpText>
    <label>Valor (Principal)</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/TemplatePDF__c/TemplatePDF__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Objeto para os dados de template de PDF.</description>
    <label>Template PDF</label>
</CustomObject>

Git Tests/force-app/main/default/default/classes/OrderCreatePDFTest.cls
@IsTest
public without sharing class OrderCreatePDFTest {
    @IsTest
    public static void flowCreateOrderPDFTest() {
        TemplatePDF__c template = new TemplatePDF__c(Name = 'ElfaQuoteOrderTemplate', Id = null);
        insert template;
        Account account  = TestUtility.createAccPJ();
        insert account;
        Order order      = TestUtility.createOrder(account);
        order.DataEntrega__c = Date.today();
        insert order;
        Product2 product = TestUtility.createProduct();
        insert product;
        PricebookEntry pricebookEntry = [SELECT Id, UnitPrice FROM PricebookEntry][0];
        pricebookEntry.IsActive       = true;
        update pricebookEntry;
        OrderItem orderItem  = TestUtility.createorderItem(order, product, pricebookEntry);
        orderItem.UnitPrice = 10;
        orderItem.ValorCx__c = 10;
        insert orderItem;

        OrderCreatePDF.FlowInputs flowInput = new OrderCreatePDF.FlowInputs();
        flowInput.orderId = order.id;
        flowInput.pdfChoice = 'ElfaQuoteOrderTemplate';

        OrderCreatePDF.flowCreateOrderPDF(new List<OrderCreatePDF.FlowInputs>{flowInput});
    }
}