Git Tests/force-app/main/default/default/objects/Order/fields/DescricaoStatusEntrega__c.field-meta.xml
<CustomField>
    <fullName>DescricaoStatusEntrega__c</fullName>
    <label>Descrição do status de entrega</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/StatusEntrega__c.field-meta.xml
<CustomField>
    <fullName>StatusEntrega__c</fullName>
    <label>Status de entrega</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Link de rastreamento disponível</fullName>
            </value>
            <value>
                <fullName>Em Rota</fullName>
                <label>Em rota</label>
            </value>
            <value>
                <fullName>A caminho</fullName>
            </value>
            <value>
                <fullName>Chegou</fullName>
            </value>
            <value>
                <fullName>Entregue</fullName>
            </value>
            <value>
                <fullName>Entregue SL</fullName>
            </value>
            <value>
                <fullName>Em pausa</fullName>
            </value>
            <value>
                <fullName>Não entregue</fullName>
            </value>
            <value>
                <fullName>Abortada</fullName>
            </value>
            <value>
                <fullName>Coletado</fullName>
            </value>
            <value>
                <fullName>Não coletado</fullName>
            </value>
            <value>
                <fullName>Conferindo</fullName>
            </value>
            <value>
                <fullName>Conferido</fullName>
            </value>
            <value>
                <fullName>Sem rota</fullName>
            </value>
            <value>
                <fullName>Devolvido</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Agendado</fullName>
            </value>
            <value>
                <fullName>Com ajudante</fullName>
            </value>
            <value>
                <fullName>Transferido</fullName>
            </value>
            <value>
                <fullName>Em transferência</fullName>
            </value>
            <value>
                <fullName>Programado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/URLRastreio__c.field-meta.xml
<CustomField>
    <fullName>URLRastreio__c</fullName>
    <label>URL de rastreio</label>
    <type>Url</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/ShippingTrackingController.cls
public without sharing class ShippingTrackingController {
    
    @AuraEnabled(cacheable=true)
    public static List<StatusData> getDeliveryHistory(String recordId) {
        List<OrderHistory> orderHistoryList = [
            SELECT 
                OrderId,
                Order.DescricaoStatusEntrega__c, 
                NewValue, 
                OldValue, 
                CreatedDate 
            FROM OrderHistory 
            WHERE Field = 'StatusEntrega__c' 
            AND OrderId = :recordId
            ORDER BY CreatedDate DESC
        ];
        
        List<StatusData> statusDataList = new List<StatusData>();

        for (OrderHistory oh : orderHistoryList) {
            StatusData newStatusData = new StatusData();
            newStatusData.label        = String.valueOf(oh.NewValue);
            newStatusData.description  = '';
            newStatusData.modifiedDate = oh.CreatedDate.format('HH:mm | dd/MM/YYYY');
            newStatusData.type         = getStatusType(String.valueOf(oh.NewValue));
            if (oh.NewValue != 'Link de rastreamento disponível') 
                statusDataList.add(newStatusData);
            System.debug(newStatusData);
        }
        if (!orderHistoryList.isEmpty()) {
            StatusData statusData = statusDataList.get(0);
            statusData.description = orderHistoryList[0].Order.DescricaoStatusEntrega__c;
        }
        System.debug(statusDataList);
        return statusDataList;
    }

    @AuraEnabled(cacheable=true)
    public static String getDeliveryURL(String recordId) {
        return [SELECT URLRastreio__c FROM Order WHERE Id = :recordId LIMIT 1].URLRastreio__c;
    }

    public class StatusData {
        @AuraEnabled public String label;
        @AuraEnabled public String description;
        @AuraEnabled public String modifiedDate;
        @AuraEnabled public String type;
    }

    public static String getStatusType(String type) {
        Set<String> completedStatus = new Set<String>{'Entregue', 'Entregue SL'};
        Set<String> canceledStatus = new Set<String>{'Não entregue', 'Abortada', 'Não coletado', 'Sem rota', 'Devolvido', 'Cancelado'};
        if (completedStatus.contains(type)) {
            return 'completed';
        } else if (canceledStatus.contains(type)) {
            return 'error';
        } else {
            return 'onHold';
        }
    }
}