Git Tests/force-app/main/default/default/objects/Order/fields/ErroIntegracaoAprovacao__c.field-meta.xml
<CustomField>
    <fullName>ErroIntegracaoAprovacao__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Erro de integração Aprovação</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ErroIntegracaoCancelamento__c.field-meta.xml
<CustomField>
    <fullName>ErroIntegracaoCancelamento__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Erro de integração Cancelamento</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ErroIntegracaoConfirmacao__c.field-meta.xml
<CustomField>
    <fullName>ErroIntegracaoConfirmacao__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Erro de integração Confirmação</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ErroIntegracaoRejeitado__c.field-meta.xml
<CustomField>
    <fullName>ErroIntegracaoRejeitado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Erro de integração Rejeitado</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Chave única: Número do pedido + Código do CD</description>
    <externalId>true</externalId>
    <label>Código do pedido TOTVS</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/StatusIntegracao__c.field-meta.xml
<CustomField>
    <fullName>StatusIntegracao__c</fullName>
    <label>Status da integração</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Integrado</fullName>
            </value>
            <value>
                <fullName>Não integrado</fullName>
            </value>
            <value>
                <fullName>Erro de aprovação/rejeição</fullName>
            </value>
            <value>
                <fullName>Nota fiscal cancelada</fullName>
            </value>
            <value>
                <fullName>Pedido em aberto</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por regra</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por crédito</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por estoque</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por crédito e estoque</fullName>
            </value>
            <value>
                <fullName>Pedido aguardando separação</fullName>
            </value>
            <value>
                <fullName>Pedido em separação</fullName>
            </value>
            <value>
                <fullName>Pedido separado/aguardando faturamento</fullName>
            </value>
            <value>
                <fullName>Pedido faturado</fullName>
            </value>
            <value>
                <fullName>Pedido com resíduo eliminado (sem faturamento)</fullName>
            </value>
            <value>
                <fullName>Pedido com resíduo eliminado (com faturamento)</fullName>
            </value>
            <value>
                <fullName>Pedido liberado</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado na alçada de desconto</fullName>
            </value>
            <value>
                <fullName>Pedido com SC</fullName>
            </value>
            <value>
                <fullName>Pedido aguardando saldo</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por regra de bonificação</fullName>
            </value>
            <value>
                <fullName>Pedido cancelado</fullName>
            </value>
            <value>
                <fullName>Pedido rejeitado no Salesforce</fullName>
            </value>
            <value>
                <fullName>Pedido rejeitado na alçada financeira</fullName>
            </value>
            <value>
                <fullName>Erro integração (Envio ao Protheus)</fullName>
            </value>
            <value>
                <fullName>Erro integração (geração do pedido no Protheus)</fullName>
            </value>
            <value>
                <fullName>Pedido aguardando envio/processamento do comprovante de pagamento RA</fullName>
            </value>
            <value>
                <fullName>Pedido aguardando aprovação de pagamento RA</fullName>
            </value>
            <value>
                <fullName>Pedido rejeitado na alçada de aprovação de pagamento RA</fullName>
            </value>
            <value>
                <fullName>Aguardando processamento na integradora</fullName>
            </value>
            <value>
                <fullName>Aprovado na integradora</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/classes/ResendOrder.cls
public without sharing class ResendOrder {
    
    @InvocableMethod(label='Resend order' description='Send to TOTVS')
    public static List<String> resendOrderToTOTVS(List<Id> ordIdList){
        Id ordId = null;
        for (Id oId : ordIdList) {
            ordId = oId;
        }
        List<Order> ordList = [SELECT Id, ErroIntegracaoAprovacao__c, ErroIntegracaoCancelamento__c, ErroIntegracaoConfirmacao__c, ErroIntegracaoRejeitado__c, ExternalId__c, StatusIntegracao__c
                                 FROM Order WHERE Id = :ordId];
        BatchResendOrder.executeBatch(ordList[0]);

        return null;
    }
}