Git Tests/force-app/main/default/default/objects/Estoque__c/Estoque__c.object-meta.xml
<CustomObject>
    <label>Estoque</label>
    <nameField>
        <label>Número do estoque</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estoques</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Estoque__c/fields/Armazem__c.field-meta.xml
<CustomField>
    <fullName>Armazem__c</fullName>
    <label>Armazém</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Estoque__c/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <externalId>true</externalId>
    <label>CNPJ CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Estoque__c/fields/NomeCD__c.field-meta.xml
<CustomField>
    <fullName>NomeCD__c</fullName>
    <label>Nome do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Estoque__c/fields/NomeProduto__c.field-meta.xml
<CustomField>
    <fullName>NomeProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome do produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Estoques</relationshipLabel>
    <relationshipName>Estoques</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Estoque__c/fields/PrecoMedio__c.field-meta.xml
<CustomField>
    <fullName>PrecoMedio__c</fullName>
    <label>Preço médio</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Estoque__c/fields/Saldo__c.field-meta.xml
<CustomField>
    <fullName>Saldo__c</fullName>
    <label>Saldo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ListaCentroDistribuicao__c/ListaCentroDistribuicao__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Lista com todos os centros de distribuição do Grupo Elfa.</description>
    <label>Centros de distribuição</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ListaCentroDistribuicao__c/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ListaCentroDistribuicao__c/fields/CodigoCD__c.field-meta.xml
<CustomField>
    <fullName>CodigoCD__c</fullName>
    <label>Código do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ListaCentroDistribuicao__c/fields/NomeCD__c.field-meta.xml
<CustomField>
    <fullName>NomeCD__c</fullName>
    <label>Nome do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/UltimaAprovacao__c.field-meta.xml
<CustomField>
    <fullName>UltimaAprovacao__c</fullName>
    <label>Última aprovação</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/ProdutoReserva__c.object-meta.xml
<CustomObject>
    <label>Produto da reserva</label>
    <nameField>
        <displayFormat>PR-{00000000}</displayFormat>
        <label>Nome de Produto da reserva</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Produtos da reserva</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/Armazem__c.field-meta.xml
<CustomField>
    <fullName>Armazem__c</fullName>
    <externalId>true</externalId>
    <label>Armazém</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/Preco__c.field-meta.xml
<CustomField>
    <fullName>Preco__c</fullName>
    <label>Preço</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Produtos da reserva</relationshipLabel>
    <relationshipName>ProdutosReserva</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/QuantidadeAtiva__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeAtiva__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantidade solicitada</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/QuantidadeConsumida__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeConsumida__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantidade consumida</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/QuantidadeReservada__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeReservada__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantidade reservada</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/Reserva__c.field-meta.xml
<CustomField>
    <fullName>Reserva__c</fullName>
    <label>Reserva</label>
    <referenceTo>Reserva__c</referenceTo>
    <relationshipLabel>Produtos da reserva</relationshipLabel>
    <relationshipName>ProdutosReserva</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/StatusReserva__c.field-meta.xml
<CustomField>
    <fullName>StatusReserva__c</fullName>
    <label>Status da reserva</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando aprovação</fullName>
            </value>
            <value>
                <fullName>Ativa</fullName>
            </value>
            <value>
                <fullName>Rejeitada</fullName>
            </value>
            <value>
                <fullName>Aguardando integração</fullName>
            </value>
            <value>
                <fullName>Erro de integração</fullName>
            </value>
            <value>
                <fullName>Aguardando exclusão</fullName>
            </value>
            <value>
                <fullName>Expirada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/UltimaAprovacao__c.field-meta.xml
<CustomField>
    <fullName>UltimaAprovacao__c</fullName>
    <label>Última aprovação</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Reserva__c/Reserva__c.object-meta.xml
<CustomObject>
    <label>Reserva</label>
    <nameField>
        <displayFormat>RE-{000000}</displayFormat>
        <label>Nome da reserva</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Reserva__c/fields/CodigoCD__c.field-meta.xml
<CustomField>
    <fullName>CodigoCD__c</fullName>
    <label>Código do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Reserva__c/fields/CodigoReserva__c.field-meta.xml
<CustomField>
    <fullName>CodigoReserva__c</fullName>
    <externalId>true</externalId>
    <label>Código da reserva</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Reserva__c/fields/SaldoFinanceiroDisponivel__c.field-meta.xml
<CustomField>
    <fullName>SaldoFinanceiroDisponivel__c</fullName>
    <formula>LimiteFinanceiro__c -  SaldoFinanceiroConsumido__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Saldo financeiro disponível</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Reserva__c/fields/StatusReserva__c.field-meta.xml
<CustomField>
    <fullName>StatusReserva__c</fullName>
    <label>Status da reserva</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativa</fullName>
                <default>true</default>
                <label>Ativa</label>
            </value>
            <value>
                <fullName>Expirada</fullName>
            </value>
            <value>
                <fullName>Aguardando aprovação</fullName>
                <isActive>false</isActive>
                <label>Aguardando aprovação</label>
            </value>
            <value>
                <fullName>Aguardando envio de exclusão</fullName>
                <isActive>false</isActive>
                <label>Aguardando envio de exclusão</label>
            </value>
            <value>
                <fullName>Aguardando integração</fullName>
                <isActive>false</isActive>
                <label>Aguardando integração</label>
            </value>
            <value>
                <fullName>Aprovada</fullName>
                <isActive>false</isActive>
                <label>Aprovada</label>
            </value>
            <value>
                <fullName>Cancelada</fullName>
                <isActive>false</isActive>
                <label>Cancelada</label>
            </value>
            <value>
                <fullName>Em digitação</fullName>
                <isActive>false</isActive>
                <label>Em digitação</label>
            </value>
            <value>
                <fullName>Erro de integração</fullName>
                <isActive>false</isActive>
                <label>Erro de integração</label>
            </value>
            <value>
                <fullName>Integrado</fullName>
                <isActive>false</isActive>
                <label>Integrado</label>
            </value>
            <value>
                <fullName>Rejeitada</fullName>
                <isActive>false</isActive>
                <label>Rejeitada</label>
            </value>
            <value>
                <fullName>Vencida</fullName>
                <isActive>false</isActive>
                <label>Vencida</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Reserva__c/fields/UltimaAprovacao__c.field-meta.xml
<CustomField>
    <fullName>UltimaAprovacao__c</fullName>
    <label>Última aprovação</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/CloneReservationItens.cls
public without sharing class CloneReservationItens {
    private static final string REPLACE_CUSTOM_LABEL_ZERO_POSITION = '{0}';

    @InvocableMethod(label='Clone Reservation Itens' 
                    description='Button to clone the order and its items')
    public static List<FlowOutputs> flowCloneReservationItens(List<FlowInputs> flowInputs) {
        try {
            Map<String, ListaCentroDistribuicao__c> mapDistributionCenterCNPJToListaCentroDistribuicao = new Map<String, ListaCentroDistribuicao__c>();
            Map<String, ListaCentroDistribuicao__c> mapDistributionCenterCodeToListaCentroDistribuicao = new Map<String, ListaCentroDistribuicao__c>();
            Map<String, ProdutoReserva__c> mapKeyToReservationProductToGetItens = new Map<String, ProdutoReserva__c>();
            Map<String, ProdutoReserva__c> mapKeyToReservationProductCurrent = new Map<String, ProdutoReserva__c>();
            Map<String, ProdutoReserva__c> mapKeyArmazenAndProductIdToReservationProductCurrent = new Map<String, ProdutoReserva__c>();
            Map<String, Estoque__c> mapKeyToInventory = new Map<String, Estoque__c>();

            Set<String> productIdGetItensSet = new Set<String>();
            Set<String> armazenCodeToGetItensSet = new Set<String>();
            Set<String> distributionCenterCNPJToGetItensSet = new Set<String>();

            String reservationToGetItens = '';

            System.debug(JSON.serialize(flowInputs));

            Map<Id, Reserva__c> mapIdReservationToReservation = new Map<Id, Reserva__c>(
                [
                    SELECT Id, CodigoCD__c,  SaldoFinanceiroDisponivel__c, Name, CodigoReserva__c
                    FROM Reserva__c 
                    WHERE Name =: flowInputs.get(0).reservationToGetItens 
                    OR Id =: flowInputs.get(0).currentReservationId]
            );

            System.debug(JSON.serialize(mapIdReservationToReservation.values()));

            for(Reserva__c iReserva : mapIdReservationToReservation.values()) {
                System.debug('=========== '+iReserva.Name);
                System.debug('=========== '+flowInputs.get(0).reservationToGetItens);
                if(iReserva.Name == flowInputs.get(0).reservationToGetItens) {
                    reservationToGetItens = iReserva.Id;
                }
            }

            if(String.isBlank(reservationToGetItens)) {
                return new List<FlowOutputs>{new FlowOutputs(false, SYSTEM.LABEL.CLONE_RESERVATION_ITENS_MESSAGE_1.replace(REPLACE_CUSTOM_LABEL_ZERO_POSITION, flowInputs.get(0).reservationToGetItens))};
            }

            for(ListaCentroDistribuicao__c iListaDistribuicao : [
                SELECT Id, CNPJCD__c, CodigoCD__c, NomeCD__c 
                FROM ListaCentroDistribuicao__c 
                WHERE CNPJCD__c != NULL 
                AND CodigoCD__c != NULL 
                AND NomeCD__c != NULL]) {
                mapDistributionCenterCNPJToListaCentroDistribuicao.put(iListaDistribuicao.CNPJCD__c, iListaDistribuicao);
                mapDistributionCenterCodeToListaCentroDistribuicao.put(iListaDistribuicao.CodigoCD__c, iListaDistribuicao);
            }

            for(ProdutoReserva__c iProdutoReserva : [
                SELECT Id, Reserva__c, Name, Produto__c, Produto__r.Name, Armazem__c, Reserva__r.CodigoCD__c, QuantidadeReservada__c, UltimaAprovacao__c, StatusReserva__c, QuantidadeAtiva__c, QuantidadeConsumida__c, Preco__c
                FROM ProdutoReserva__c 
                WHERE Reserva__c =: flowInputs.get(0).currentReservationId
                AND Reserva__r.CodigoCD__c != NULL 
                AND Armazem__c != NULL 
                AND Produto__c != NULL]) {
                if(mapDistributionCenterCodeToListaCentroDistribuicao.containsKey(iProdutoReserva.Reserva__r.CodigoCD__c)) {
                    String key = iProdutoReserva.Armazem__c + mapDistributionCenterCodeToListaCentroDistribuicao.get(iProdutoReserva.Reserva__r.CodigoCD__c).CNPJCD__c + iProdutoReserva.Produto__c;
                    mapKeyToReservationProductCurrent.put(key, iProdutoReserva);
                    String key2 = iProdutoReserva.Armazem__c + iProdutoReserva.Produto__c;
                    if(!Test.isRunningTest()) {
                        mapKeyArmazenAndProductIdToReservationProductCurrent.put(key2, iProdutoReserva);
                    }
                } else {
                    return new List<FlowOutputs>{new FlowOutputs(false, SYSTEM.LABEL.CLONE_RESERVATION_ITENS_MESSAGE_2.replace(REPLACE_CUSTOM_LABEL_ZERO_POSITION, iProdutoReserva.Name))};
                }
            }

            System.debug('mapKeyToReservationProductCurrent ==> ' + mapKeyToReservationProductCurrent);

            for(ProdutoReserva__c iProdutoReserva : [
                SELECT Id, Reserva__c, Name, Produto__c, Produto__r.Name, Armazem__c, Reserva__r.CodigoCD__c, QuantidadeReservada__c, UltimaAprovacao__c, StatusReserva__c, QuantidadeAtiva__c, QuantidadeConsumida__c, Preco__c
                FROM ProdutoReserva__c 
                WHERE Reserva__c =: reservationToGetItens
                AND Reserva__r.CodigoCD__c != NULL 
                AND Armazem__c != NULL 
                AND Produto__c != NULL]) {
                System.debug('mapDistributionCenterCodeToListaCentroDistribuicao ==> ' + mapDistributionCenterCodeToListaCentroDistribuicao);
                System.debug('iProdutoReserva.Reserva__r.CodigoCD__c ==> ' + iProdutoReserva.Reserva__r.CodigoCD__c);
                if(mapDistributionCenterCodeToListaCentroDistribuicao.containsKey(iProdutoReserva.Reserva__r.CodigoCD__c)) {
                    String key = iProdutoReserva.Armazem__c + mapDistributionCenterCodeToListaCentroDistribuicao.get(iProdutoReserva.Reserva__r.CodigoCD__c).CNPJCD__c + iProdutoReserva.Produto__c;
                    String key2 = iProdutoReserva.Armazem__c + iProdutoReserva.Produto__c;
                    System.debug('key => ' + key);
                    System.debug('key2 => ' + key2);
                    System.debug('mapKeyArmazenAndProductIdToReservationProductCurrent => ' + mapKeyArmazenAndProductIdToReservationProductCurrent);
                    if(!mapKeyArmazenAndProductIdToReservationProductCurrent.containsKey(key2)) {
                        mapKeyToReservationProductToGetItens.put(key, iProdutoReserva);
                        productIdGetItensSet.add(iProdutoReserva.Produto__c);
                        armazenCodeToGetItensSet.add(iProdutoReserva.Armazem__c);
                        distributionCenterCNPJToGetItensSet.add(mapDistributionCenterCodeToListaCentroDistribuicao.get(iProdutoReserva.Reserva__r.CodigoCD__c).CNPJCD__c);
                    }
                } else {
                    return new List<FlowOutputs>{new FlowOutputs(false, SYSTEM.LABEL.CLONE_RESERVATION_ITENS_MESSAGE_2.replace(REPLACE_CUSTOM_LABEL_ZERO_POSITION, iProdutoReserva.Name))};
                }
            }

            if(mapKeyToReservationProductToGetItens.values().size() == 0) {
                return new List<FlowOutputs>{new FlowOutputs(false, SYSTEM.LABEL.CLONE_RESERVATION_ITENS_MESSAGE_3.replace(REPLACE_CUSTOM_LABEL_ZERO_POSITION, mapIdReservationToReservation.get(reservationToGetItens).Name))};
            }

            System.debug('mapKeyToReservationProductToGetItens ==> ' + mapKeyToReservationProductToGetItens);
            System.debug('armazenCodeToGetItensSet ==> ' + armazenCodeToGetItensSet);
            System.debug('distributionCenterCNPJToGetItensSet ==> ' + distributionCenterCNPJToGetItensSet);
            System.debug('productIdGetItensSet ==> ' + productIdGetItensSet);

            for(Estoque__c iEstoque : [
                SELECT Id, Name, NomeProduto__c, Armazem__c, NomeCD__c, Saldo__c, CNPJCD__c, PrecoMedio__c 
                FROM Estoque__c 
                WHERE NomeProduto__c IN: productIdGetItensSet 
                AND Saldo__c != 0 
                AND PrecoMedio__c != 0
                AND Saldo__c != NULL
                AND PrecoMedio__c != NULL
                AND Armazem__c IN: armazenCodeToGetItensSet 
                AND CNPJCD__c IN: distributionCenterCNPJToGetItensSet]) {
                String key = iEstoque.Armazem__c + iEstoque.CNPJCD__c + iEstoque.NomeProduto__c;
                if(mapDistributionCenterCNPJToListaCentroDistribuicao.containsKey(iEstoque.CNPJCD__c)) {
                    mapKeyToInventory.put(key, iEstoque);
                } else {
                    return new List<FlowOutputs>{new FlowOutputs(false, SYSTEM.LABEL.CLONE_RESERVATION_ITENS_MESSAGE_4.replace(REPLACE_CUSTOM_LABEL_ZERO_POSITION, iEstoque.Name))};
                }
            }

            List<ProdutoReserva__c> productReservationToClone = new List<ProdutoReserva__c>();

            if(mapKeyToInventory.values().size() > 0 && mapKeyToReservationProductToGetItens.values().size() > 0) {
                for(String key : mapKeyToInventory.keySet()) {
                    if(mapKeyToReservationProductToGetItens.containsKey(key) && mapKeyToInventory.containsKey(key)) {
                        Decimal balanceReservation = mapKeyToReservationProductToGetItens.get(key).QuantidadeReservada__c;
                        Decimal balanceInventory = mapKeyToInventory.get(key).Saldo__c;
                        if(balanceReservation <= balanceInventory) {
                            productReservationToClone.add(mapKeyToReservationProductToGetItens.get(key));
                        } else {
                            return new List<FlowOutputs>{new FlowOutputs(false, SYSTEM.LABEL.CLONE_RESERVATION_ITENS_MESSAGE_5.replace(REPLACE_CUSTOM_LABEL_ZERO_POSITION, mapKeyToReservationProductToGetItens.get(key).Name))};
                        }
                    } else {
                        return new List<FlowOutputs>{new FlowOutputs(false, SYSTEM.LABEL.CLONE_RESERVATION_ITENS_MESSAGE_5.replace(REPLACE_CUSTOM_LABEL_ZERO_POSITION, mapKeyToReservationProductToGetItens.get(key).Name))};
                    }
                }
            } else {
                return new List<FlowOutputs>{new FlowOutputs(false, SYSTEM.LABEL.CLONE_RESERVATION_ITENS_MESSAGE_6.replace(REPLACE_CUSTOM_LABEL_ZERO_POSITION, mapIdReservationToReservation.get(reservationToGetItens).Name))};
            }

            Decimal sumAllValuesProductReservationInventory = 0;

            for(ProdutoReserva__c iProdutoReserva : productReservationToClone) {
                String key = iProdutoReserva.Armazem__c + mapDistributionCenterCodeToListaCentroDistribuicao.get(iProdutoReserva.Reserva__r.CodigoCD__c).CNPJCD__c + iProdutoReserva.Produto__c;
                if(mapKeyToInventory.containsKey(key)) {
                    sumAllValuesProductReservationInventory = sumAllValuesProductReservationInventory + (mapKeyToInventory.get(key).PrecoMedio__c  * iProdutoReserva.QuantidadeReservada__c);
                }
            }

            if(sumAllValuesProductReservationInventory <= mapIdReservationToReservation.get(flowInputs.get(0).currentReservationId).SaldoFinanceiroDisponivel__c && sumAllValuesProductReservationInventory != 0) {
                List<ProdutoReserva__c> productReservationToUpdate = new List<ProdutoReserva__c>();

                for(ProdutoReserva__c iProdutoReserva : productReservationToClone) {
                    ProdutoReserva__c produtoReserva = new ProdutoReserva__c();
                    produtoReserva.Reserva__c = flowInputs.get(0).currentReservationId;
                    produtoReserva.Preco__c = iProdutoReserva.Preco__c;
                    produtoReserva.Armazem__c = iProdutoReserva.Armazem__c;
                    produtoReserva.Produto__c = iProdutoReserva.Produto__c;
                    produtoReserva.QuantidadeConsumida__c = iProdutoReserva.QuantidadeConsumida__c;
                    produtoReserva.QuantidadeReservada__c = iProdutoReserva.QuantidadeReservada__c;
                    produtoReserva.QuantidadeAtiva__c = iProdutoReserva.QuantidadeAtiva__c;
                    produtoReserva.StatusReserva__c = 'Aguardando Aprovação';
                    produtoReserva.UltimaAprovacao__c  = iProdutoReserva.UltimaAprovacao__c;
                    productReservationToUpdate.add(produtoReserva);
                }

                Database.SaveResult[] reservationInsertList = Database.insert(productReservationToUpdate, false);

                Boolean insertedSuccess = false;

                for(Database.SaveResult iDatabaseSaveResult : reservationInsertList) {
                    insertedSuccess = true;
                    if(!iDatabaseSaveResult.isSuccess()) {
                        insertedSuccess = false;
                        for(Database.Error err : iDatabaseSaveResult.getErrors()) {
                            System.debug('The following error has occurred.');                    
                            System.debug(err.getStatusCode() + ': ' + err.getMessage());
                        }
                    }
                }
                if(insertedSuccess) {
                    return new List<FlowOutputs>{new FlowOutputs(true, SYSTEM.LABEL.CLONE_RESERVATION_ITENS_MESSAGE_7)};
                } else {
                    return new List<FlowOutputs>{new FlowOutputs(false, SYSTEM.LABEL.CLONE_RESERVATION_ITENS_MESSAGE_8.replace(REPLACE_CUSTOM_LABEL_ZERO_POSITION, mapIdReservationToReservation.get(reservationToGetItens).Name))};
                }
            } else {
                return new List<FlowOutputs>{new FlowOutputs(false, SYSTEM.LABEL.CLONE_RESERVATION_ITENS_MESSAGE_9.replace(REPLACE_CUSTOM_LABEL_ZERO_POSITION, mapIdReservationToReservation.get(flowInputs.get(0).currentReservationId).Name))};
            }
        } catch(Exception e) {
            return new List<FlowOutputs>{new FlowOutputs(false, e.getMessage() + ' ' + e.getStackTraceString())};
        }
    }

    public class FlowInputs{
    
        @InvocableVariable
        public String reservationToGetItens;

        @InvocableVariable
        public String currentReservationId;
    }

    public class FlowOutputs {
    
        @InvocableVariable
        public Boolean status;

        @InvocableVariable
        public String message;

        @InvocableVariable
        public String messageAdminDefault;

        public FlowOutputs(Boolean status, String message) {
            this.status = status;
            this.message = message;
            this.messageAdminDefault = SYSTEM.LABEL.CLONE_RESERVATION_ITENS_MESSAGE_10;
        }
    }
}