Git Tests/force-app/main/default/default/objects/Account/fields/Armazem__c.field-meta.xml
<CustomField>
    <fullName>Armazem__c</fullName>
    <label>Armazém</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <externalId>true</externalId>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/CodigoRegiao__c.field-meta.xml
<CustomField>
    <fullName>CodigoRegiao__c</fullName>
    <label>Código da Região</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/GrupoCliente__c.field-meta.xml
<CustomField>
    <fullName>GrupoCliente__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Grupo de clientes</label>
    <referenceTo>GrupoCliente__c</referenceTo>
    <relationshipLabel>Clientes</relationshipLabel>
    <relationshipName>Clientes</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/DestinatarioReserva__c/DestinatarioReserva__c.object-meta.xml
<CustomObject>
    <label>Destinatário da reserva</label>
    <nameField>
        <displayFormat>DR-{000000}</displayFormat>
        <label>Nome de Destinatário da reserva</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Destinatários da reserva</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/DestinatarioReserva__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Destinatários da reserva</relationshipLabel>
    <relationshipName>DestinatariosReserva</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/DestinatarioReserva__c/fields/CodigoRegiao__c.field-meta.xml
<CustomField>
    <fullName>CodigoRegiao__c</fullName>
    <label>Código da região</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/DestinatarioReserva__c/fields/GrupoClientes__c.field-meta.xml
<CustomField>
    <fullName>GrupoClientes__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grupo de clientes</label>
    <referenceTo>GrupoCliente__c</referenceTo>
    <relationshipLabel>Destinatários da reserva</relationshipLabel>
    <relationshipName>DestinatariosReserva</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/DestinatarioReserva__c/fields/Reserva__c.field-meta.xml
<CustomField>
    <fullName>Reserva__c</fullName>
    <label>Reserva</label>
    <referenceTo>Reserva__c</referenceTo>
    <relationshipLabel>Destinatários da reserva</relationshipLabel>
    <relationshipName>DestinatariosReserva</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Fornecedor__c/Fornecedor__c.object-meta.xml
<CustomObject>
    <label>Fornecedor</label>
    <nameField>
        <label>Nome do fornecedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fornecedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Fornecedor__c/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Fornecedor__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do fornecedor</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/GrupoCliente__c/GrupoCliente__c.object-meta.xml
<CustomObject>
    <label>Grupo de clientes</label>
    <nameField>
        <label>Nome de grupo de clientes</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos de cliente</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/GrupoCliente__c/fields/CodigoGrupo__c.field-meta.xml
<CustomField>
    <fullName>CodigoGrupo__c</fullName>
    <externalId>true</externalId>
    <label>Código do grupo</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/CategoriaComercial__c.field-meta.xml
<CustomField>
    <fullName>CategoriaComercial__c</fullName>
    <label>Categoria comercial</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>G</fullName>
                <label>GENÉRICO</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>MATERIAIS</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>NUTRIÇÃO</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Medctech</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>REFERÊNCIA</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>AMBOS</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>DIABETES</label>
            </value>
            <value>
                <fullName>Q</fullName>
                <label>ODONTOLOGIA</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Especialidade</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <label>EQUIPAMENTO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do produto</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fornecedor</label>
    <referenceTo>Fornecedor__c</referenceTo>
    <relationshipLabel>Produtos</relationshipLabel>
    <relationshipName>Produtos</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/UnidadeMedida__c.field-meta.xml
<CustomField>
    <fullName>UnidadeMedida__c</fullName>
    <label>Unidade de medida</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/ProdutoReserva__c.object-meta.xml
<CustomObject>
    <label>Produto da reserva</label>
    <nameField>
        <displayFormat>PR-{00000000}</displayFormat>
        <label>Nome de Produto da reserva</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Produtos da reserva</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/Armazem__c.field-meta.xml
<CustomField>
    <fullName>Armazem__c</fullName>
    <externalId>true</externalId>
    <label>Armazém</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <formula>Produto__r.Fornecedor__r.Name</formula>
    <label>Fornecedor</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/Reserva__c.field-meta.xml
<CustomField>
    <fullName>Reserva__c</fullName>
    <label>Reserva</label>
    <referenceTo>Reserva__c</referenceTo>
    <relationshipLabel>Produtos da reserva</relationshipLabel>
    <relationshipName>ProdutosReserva</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Reserva__c/Reserva__c.object-meta.xml
<CustomObject>
    <label>Reserva</label>
    <nameField>
        <displayFormat>RE-{000000}</displayFormat>
        <label>Nome da reserva</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Reserva__c/recordTypes/ReservaCliente.recordType-meta.xml
<RecordType>
    <fullName>ReservaCliente</fullName>
    <active>true</active>
    <label>Reserva de cliente</label>
</RecordType>

Git Tests/force-app/main/default/default/objects/ResponsabilidadeAprovacao__c/ResponsabilidadeAprovacao__c.object-meta.xml
<CustomObject>
    <label>Responsabilidade de aprovação</label>
    <nameField>
        <displayFormat>RA-{00000}</displayFormat>
        <label>Nome de Responsabilidade de aprovação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responsabilidades de aprovação</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ResponsabilidadeAprovacao__c/fields/Categorias__c.field-meta.xml
<CustomField>
    <fullName>Categorias__c</fullName>
    <label>Categorias</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>AMBOS</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>DIABETES</label>
            </value>
            <value>
                <fullName>G</fullName>
                <label>GENÉRICO</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>MATERIAIS</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>NUTRIÇÃO</label>
            </value>
            <value>
                <fullName>Q</fullName>
                <label>ODONTOLOGIA</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>MEDCTECH</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>SPECIALTY</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <label>EQUIPAMENTO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/ResponsabilidadeAprovacao__c/fields/CodigoMesa__c.field-meta.xml
<CustomField>
    <fullName>CodigoMesa__c</fullName>
    <externalId>true</externalId>
    <label>Código da mesa</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ResponsabilidadeAprovacao__c/fields/Regiao__c.field-meta.xml
<CustomField>
    <fullName>Regiao__c</fullName>
    <externalId>true</externalId>
    <label>Região</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ResponsabilidadeAprovacao__c/fields/UsuarioAprovador__c.field-meta.xml
<CustomField>
    <fullName>UsuarioAprovador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário aprovador</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ResponsabilidadeAprovacao</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ResponsabilidadeAprovacao__c/recordTypes/AprovacaoReserva.recordType-meta.xml
<RecordType>
    <fullName>AprovacaoReserva</fullName>
    <active>true</active>
    <label>Aprovação reserva de produto</label>
</RecordType>

Git Tests/force-app/main/default/default/classes/ReservationRecipientTriggerTest.cls
@isTest
public with sharing class ReservationRecipientTriggerTest {
    
    @TestSetup
    static void makeData(){

        Fornecedor__c fornecedor = new Fornecedor__c(Name = 'testfor', ExternalId__c = '12345');
        insert fornecedor;

        Product2 product = TestUtility.createProduct();
        product.ExternalId__c = '1234';
        product.UnidadeMedida__c = 'F';
        product.fornecedor__c = fornecedor.Id;
        product.CategoriaComercial__c = 'G';
        insert product;

        GrupoCliente__c grupo = new GrupoCliente__c();
        grupo.CodigoGrupo__c = '5';
        insert grupo;
        
        Account acc = TestUtility.createAccount();
        acc.CNPJ__c = '61182609000113';
        acc.GrupoCliente__c = grupo.Id;
        insert acc;

        Reserva__c reservation = TestUtility.createReservation();
        reservation.RecordTypeId = Schema.SObjectType.Reserva__c.getRecordTypeInfosByDeveloperName().get('ReservaCliente').getRecordTypeId();
        insert reservation;      

        ProdutoReserva__c reservationProd = TestUtility.createReservationProduct(reservation.Id, product.Id);
        insert reservationProd;

        ProdutoReserva__c reservationProd2 = TestUtility.createReservationProduct(reservation.Id, product.Id);
        reservationProd2.Armazem__c = '20';
        insert reservationProd2;        

        ProdutoReserva__c reservationProd3 = TestUtility.createReservationProduct(reservation.Id, product.Id);
        reservationProd3.Armazem__c = '30';
        insert reservationProd3;      
        
        
        DestinatarioReserva__c reservationDest = TestUtility.createReservationDest(reservation.Id, acc.Id);
        reservationDest.CodigoRegiao__c = '';
        reservationDest.Cliente__c = null;
        reservationDest.GrupoClientes__c = grupo.id;
        insert reservationDest;

        DestinatarioReserva__c reservationDest2 = TestUtility.createReservationDest(reservation.Id, acc.Id);
        reservationDest2.CodigoRegiao__c = '';
        reservationDest2.GrupoClientes__c = null;
        reservationDest2.Cliente__c = acc.id;
        try {
            
        insert reservationDest2;            
        } catch (Exception ex) {
            

        System.debug(ex.getMessage());
            Boolean expectedExceptionThrown =  ex.getMessage().contains('FIELD_CUSTOM_VALIDATION_EXCEPTION') ? true : false;
            System.assertEquals(expectedExceptionThrown, true);

        } 

      

        ResponsabilidadeAprovacao__c respAprovacao = new ResponsabilidadeAprovacao__c();
        respAprovacao.UsuarioAprovador__c = UserInfo.getUserId();
        respAprovacao.Categorias__c = 'M';
        respAprovacao.CodigoMesa__c = 'TESTE';
        respAprovacao.Regiao__c ='ABCDE';
        respAprovacao.Categorias__c ='';
        respAprovacao.RecordTypeId =Schema.SObjectType.ResponsabilidadeAprovacao__c.getRecordTypeInfosByDeveloperName().get('AprovacaoReserva').getRecordTypeId();

        insert respAprovacao;

        ResponsabilidadeAprovacao__c respAprovacao2 = new ResponsabilidadeAprovacao__c();
        respAprovacao2.UsuarioAprovador__c = UserInfo.getUserId();
        respAprovacao2.Categorias__c = 'M';
        respAprovacao2.CodigoMesa__c = 'TESTE';
        respAprovacao2.Regiao__c ='ABCDE';
        respAprovacao2.Categorias__c ='G';
        respAprovacao2.RecordTypeId =Schema.SObjectType.ResponsabilidadeAprovacao__c.getRecordTypeInfosByDeveloperName().get('AprovacaoReserva').getRecordTypeId();

        insert respAprovacao2;
    }

    @isTest
    public static void ReservationRecipientTriggerTest() {

        ReservationRecipientTriggerHelper desti = new ReservationRecipientTriggerHelper();

        List<DestinatarioReserva__c> lstDestinatarioReserva = [SELECT id FROM DestinatarioReserva__c];      

        ReservationRecipientTriggerHandler.disableTrigger();
        ReservationRecipientTriggerHandler.enableTrigger();        
        ReservationRecipientTriggerHandler.isTriggerEnabled();

        Test.startTest();
        
        delete lstDestinatarioReserva[1];

        update lstDestinatarioReserva[0];



        Test.stopTest();

    }
}