Git Tests/force-app/main/default/default/objects/Account/fields/Armazem__c.field-meta.xml
<CustomField>
    <fullName>Armazem__c</fullName>
    <label>Armazém</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <externalId>true</externalId>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/CodigoRegiao__c.field-meta.xml
<CustomField>
    <fullName>CodigoRegiao__c</fullName>
    <label>Código da Região</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <externalId>true</externalId>
    <label>CPF</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/DestinatarioReserva__c/DestinatarioReserva__c.object-meta.xml
<CustomObject>
    <label>Destinatário da reserva</label>
    <nameField>
        <displayFormat>DR-{000000}</displayFormat>
        <label>Nome de Destinatário da reserva</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Destinatários da reserva</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/DestinatarioReserva__c/fields/ChaveUnica__c.field-meta.xml
<CustomField>
    <fullName>ChaveUnica__c</fullName>
    <externalId>true</externalId>
    <label>Chave única</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/DestinatarioReserva__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Destinatários da reserva</relationshipLabel>
    <relationshipName>DestinatariosReserva</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/DestinatarioReserva__c/fields/CodigoRegiao__c.field-meta.xml
<CustomField>
    <fullName>CodigoRegiao__c</fullName>
    <label>Código da região</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/DestinatarioReserva__c/fields/Reserva__c.field-meta.xml
<CustomField>
    <fullName>Reserva__c</fullName>
    <label>Reserva</label>
    <referenceTo>Reserva__c</referenceTo>
    <relationshipLabel>Destinatários da reserva</relationshipLabel>
    <relationshipName>DestinatariosReserva</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/Integracoes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuração  personalizada utilizada para gerir os dados de acessos das integrações</description>
    <label>Integrações</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <inlineHelpText>URL de acesso ao serviço</inlineHelpText>
    <label>EndPoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Método</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Senha</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>Usuário</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ListaCentroDistribuicao__c/ListaCentroDistribuicao__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Lista com todos os centros de distribuição do Grupo Elfa.</description>
    <label>Centros de distribuição</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ListaCentroDistribuicao__c/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ListaCentroDistribuicao__c/fields/CodigoCD__c.field-meta.xml
<CustomField>
    <fullName>CodigoCD__c</fullName>
    <label>Código do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ListaCentroDistribuicao__c/fields/NomeCD__c.field-meta.xml
<CustomField>
    <fullName>NomeCD__c</fullName>
    <label>Nome do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CentroDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentroDistribuicao__c</fullName>
    <label>Centro de distribuição</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ChaveUnica__c.field-meta.xml
<CustomField>
    <fullName>ChaveUnica__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>ChaveUnica</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <formula>Account.CNPJ__c</formula>
    <label>CNPJ</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <formula>Account.CPF__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CPF</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Chave única: Número do pedido + Código do CD</description>
    <externalId>true</externalId>
    <label>Código do pedido TOTVS</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do produto</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/ProdutoReserva__c.object-meta.xml
<CustomObject>
    <label>Produto da reserva</label>
    <nameField>
        <displayFormat>PR-{00000000}</displayFormat>
        <label>Nome de Produto da reserva</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Produtos da reserva</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/Armazem__c.field-meta.xml
<CustomField>
    <fullName>Armazem__c</fullName>
    <externalId>true</externalId>
    <label>Armazém</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Produtos da reserva</relationshipLabel>
    <relationshipName>ProdutosReserva</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/QuantidadeAtiva__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeAtiva__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantidade solicitada</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/QuantidadeReservada__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeReservada__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantidade reservada</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/Reserva__c.field-meta.xml
<CustomField>
    <fullName>Reserva__c</fullName>
    <label>Reserva</label>
    <referenceTo>Reserva__c</referenceTo>
    <relationshipLabel>Produtos da reserva</relationshipLabel>
    <relationshipName>ProdutosReserva</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/StatusReserva__c.field-meta.xml
<CustomField>
    <fullName>StatusReserva__c</fullName>
    <label>Status da reserva</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando aprovação</fullName>
            </value>
            <value>
                <fullName>Ativa</fullName>
            </value>
            <value>
                <fullName>Rejeitada</fullName>
            </value>
            <value>
                <fullName>Aguardando integração</fullName>
            </value>
            <value>
                <fullName>Erro de integração</fullName>
            </value>
            <value>
                <fullName>Aguardando exclusão</fullName>
            </value>
            <value>
                <fullName>Expirada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Reserva__c/Reserva__c.object-meta.xml
<CustomObject>
    <label>Reserva</label>
    <nameField>
        <displayFormat>RE-{000000}</displayFormat>
        <label>Nome da reserva</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Reserva__c/fields/CentroDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentroDistribuicao__c</fullName>
    <externalId>true</externalId>
    <label>Centro de distribuição</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Reserva__c/fields/ChaveUnica__c.field-meta.xml
<CustomField>
    <fullName>ChaveUnica__c</fullName>
    <externalId>true</externalId>
    <label>Chave única</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Reserva__c/fields/CodigoCD__c.field-meta.xml
<CustomField>
    <fullName>CodigoCD__c</fullName>
    <label>Código do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Reserva__c/fields/CodigoReserva__c.field-meta.xml
<CustomField>
    <fullName>CodigoReserva__c</fullName>
    <externalId>true</externalId>
    <label>Código da reserva</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Reserva__c/fields/Descricao__c.field-meta.xml
<CustomField>
    <fullName>Descricao__c</fullName>
    <label>Descrição</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Reserva__c/fields/FimReserva__c.field-meta.xml
<CustomField>
    <fullName>FimReserva__c</fullName>
    <label>Fim da reserva</label>
    <type>DateTime</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Reserva__c/fields/StatusReserva__c.field-meta.xml
<CustomField>
    <fullName>StatusReserva__c</fullName>
    <label>Status da reserva</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativa</fullName>
                <default>true</default>
                <label>Ativa</label>
            </value>
            <value>
                <fullName>Expirada</fullName>
            </value>
            <value>
                <fullName>Aguardando aprovação</fullName>
                <isActive>false</isActive>
                <label>Aguardando aprovação</label>
            </value>
            <value>
                <fullName>Aguardando envio de exclusão</fullName>
                <isActive>false</isActive>
                <label>Aguardando envio de exclusão</label>
            </value>
            <value>
                <fullName>Aguardando integração</fullName>
                <isActive>false</isActive>
                <label>Aguardando integração</label>
            </value>
            <value>
                <fullName>Aprovada</fullName>
                <isActive>false</isActive>
                <label>Aprovada</label>
            </value>
            <value>
                <fullName>Cancelada</fullName>
                <isActive>false</isActive>
                <label>Cancelada</label>
            </value>
            <value>
                <fullName>Em digitação</fullName>
                <isActive>false</isActive>
                <label>Em digitação</label>
            </value>
            <value>
                <fullName>Erro de integração</fullName>
                <isActive>false</isActive>
                <label>Erro de integração</label>
            </value>
            <value>
                <fullName>Integrado</fullName>
                <isActive>false</isActive>
                <label>Integrado</label>
            </value>
            <value>
                <fullName>Rejeitada</fullName>
                <isActive>false</isActive>
                <label>Rejeitada</label>
            </value>
            <value>
                <fullName>Vencida</fullName>
                <isActive>false</isActive>
                <label>Vencida</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/classes/IntegrationReservationOUT.cls
global with sharing class IntegrationReservationOUT {

    global class listReservationRequest {
        public List<ReservationRequest> reservations;
        public listReservationRequest (List<ReservationRequest> reservations){
            this.reservations = reservations;
        }        
    }

    global class ReservationRequest {
        public String CgcEmp;
        public String descricao;
        public String validade;
        public String tipo;
        public String CodigoReserva;
        public Integer ValorLimite;
        public List<ReservationAccountsRequest> clientes;
        public List<ReservationProductsRequest> produtos;
        
        public ReservationRequest (String reserveCode, String descReserva, String cnpjCD, String limiteDate, String type,list<ReservationAccountsRequest> listAccounts, list<ReservationProductsRequest> listProducts){
            this.CgcEmp = cnpjCD;
            this.descricao = descReserva;
            this.validade = limiteDate;
            this.tipo = type == 'Reserva de cliente' ? 'C': 'G';
            this.clientes = listAccounts;
            this.produtos = listProducts;
            this.CodigoReserva = reserveCode;
            this.ValorLimite = 15000000;
        }
    }

    global class ReservationAccountsRequest {
        public String cnpj;
        public String regiao;
        
        public ReservationAccountsRequest (DestinatarioReserva__c reservationObj){
            this.cnpj         = reservationObj.Cliente__r.CNPJ__c != null ? reservationObj.Cliente__r.CNPJ__c : reservationObj.Cliente__r.CPF__c;
            this.regiao       = reservationObj.CodigoRegiao__c;
        }
    }

    global class ReservationProductsRequest {
        public String armazem;
        public String codigo;
        public Decimal quantidade;
        
        
        public ReservationProductsRequest (ProdutoReserva__c reservationObj){
            this.armazem      = reservationObj.Armazem__c;
            this.codigo       = reservationObj.Produto__r.ExternalId__c;
            this.quantidade   = reservationObj.QuantidadeReservada__c;
            
        }
    }

    public class ResultClass{
        public String message {get;set;}
        public String detailMessage {get;set;}
    }

    global class ReservationRequestDelete {
        public String CgcEmp;
        public String CodigoReserva;
        public String tipo;
        public List<ReservationAccountsRequest> clientes;
        public List<ReservationProductsRequest> produtos;
        
        public ReservationRequestDelete (String cnpjCD, String reserveCode, String type,list<ReservationAccountsRequest> listAccounts, list<ReservationProductsRequest> listProducts){
            this.CgcEmp = cnpjCD;
            this.tipo = type == 'Reserva de cliente' ? 'C': 'G';
            this.clientes = listAccounts;
            this.produtos = listProducts;
            this.CodigoReserva = reserveCode;
        }
    }

    public static ResultClass sendReservationERP(List<Reserva__c> listReservation, Boolean isInsert) {
        ResultClass resultobj = new ResultClass();

        Map<String, ListaCentroDistribuicao__c> mapDistributionCenterCNPJToListaCentroDistribuicao = new Map<String, ListaCentroDistribuicao__c>();
        Map<String, ListaCentroDistribuicao__c> mapDistributionCenterCodeToListaCentroDistribuicao = new Map<String, ListaCentroDistribuicao__c>();
        Map<String, ProdutoReserva__c> reservationMap = new Map<String, ProdutoReserva__c>();

        for(ListaCentroDistribuicao__c iListaDistribuicao : [
            SELECT Id, CNPJCD__c, CodigoCD__c, NomeCD__c 
            FROM ListaCentroDistribuicao__c 
            WHERE CNPJCD__c != NULL 
            AND CodigoCD__c != NULL 
            AND NomeCD__c != NULL]) {
            mapDistributionCenterCNPJToListaCentroDistribuicao.put(iListaDistribuicao.CNPJCD__c, iListaDistribuicao);
            mapDistributionCenterCodeToListaCentroDistribuicao.put(iListaDistribuicao.CodigoCD__c, iListaDistribuicao);
        }

        try {
            
            Integracoes__c intCustomerApi = new Integracoes__c();
            
            System.debug('====== listReservation'+ listReservation);
            if(listReservation.size() > 0){

                Map<Id, List<ProdutoReserva__c>> productsMap = new Map<Id, List<ProdutoReserva__c>>();
                for(ProdutoReserva__c r : [SELECT Id, Reserva__r.CodigoCD__c, Armazem__c, Reserva__c, Produto__r.ExternalId__c, QuantidadeReservada__c, QuantidadeAtiva__c, Reserva__r.CodigoReserva__c, CodigoProduto__c, StatusReserva__c FROM ProdutoReserva__c WHERE Reserva__c IN :listReservation AND ( StatusReserva__c ='Aguardando Integração' OR StatusReserva__c ='Erro de integração') ORDER BY Reserva__r.FimReserva__c DESC]){
                    if (productsMap.containsKey(r.Reserva__c)){
                        productsMap.get(r.Reserva__c). add(r);
                    }else{
                        List<ProdutoReserva__c> productList = new List<ProdutoReserva__c>();
                        productList.add(r);
                        productsMap.put(r.Reserva__c, productList);
                    }

                    if (!String.isBlank(r.Reserva__r.CodigoReserva__c)) {
                        
                        if (!reservationMap.containsKey(r.Reserva__r.CodigoReserva__c.substring(5, 11)+r.CodigoProduto__c)) {
                        
                            reservationMap.put(r.Reserva__r.CodigoReserva__c.substring(5, 11)+r.CodigoProduto__c, r);
                        }
                    }
                  
                }

                Map<Id, List<DestinatarioReserva__c>> destMap = new Map<Id, List<DestinatarioReserva__c>>();
                for(DestinatarioReserva__c r : [SELECT Id, CodigoRegiao__c, Reserva__c, Cliente__c, Cliente__r.CNPJ__c, Cliente__r.CPF__c, Cliente__r.CodigoRegiao__c FROM DestinatarioReserva__c WHERE Reserva__c IN :listReservation ORDER BY Reserva__r.FimReserva__c DESC]){
                    if (destMap.containsKey(r.Reserva__c)){
                        destMap.get(r.Reserva__c).add(r);
                    }else{
                        List<DestinatarioReserva__c> destList = new List<DestinatarioReserva__c>();
                        destList.add(r);
                        destMap.put(r.Reserva__c, destList);
                    }
                }

                List<ReservationRequest> reservationsList = new List<ReservationRequest>();
                Set<String> setAccountCnpj = new Set<String>();
                for(Reserva__c r : listReservation){
                    List<ReservationAccountsRequest> listReservationAccountReq =  new List<ReservationAccountsRequest>();
                    if (destMap.containsKey(r.Id)){
                        for(DestinatarioReserva__c dest : destMap.get(r.Id)){

                            ReservationAccountsRequest accountObj = new ReservationAccountsRequest(dest);

                            // if (!setAccountCnpj.contains(accountObj.cnpj)) {
                                
                                listReservationAccountReq.add(accountObj);
                                setAccountCnpj.add(accountObj.cnpj);

                            // }
                        }
                    }

                    List<ReservationProductsRequest> listReservationItemReq = new List<ReservationProductsRequest>();
                    if (productsMap.containsKey(r.Id)){
                        for(ProdutoReserva__c prod : productsMap.get(r.Id)){
                            ReservationProductsRequest productObj = new ReservationProductsRequest(prod);
                            listReservationItemReq.add(productObj);
                        }
                    }

                    if (String.isBlank(r.CodigoReserva__c)) {

                        intCustomerApi = Integracoes__c.getValues(IntegrationConstants.RESERVATION_POST_METADATA);
                        ReservationRequest reservationReq = new ReservationRequest(null, r.Descricao__c, mapDistributionCenterCodeToListaCentroDistribuicao.containsKey(r.CodigoCD__c) ? mapDistributionCenterCodeToListaCentroDistribuicao.get(r.CodigoCD__c).CNPJCD__c : null, IntegrationContractOUT.getFormattedDate(Date.valueOf(r.FimReserva__c)), r.RecordType.Name, listReservationAccountReq, listReservationItemReq);
                        reservationsList.add(reservationReq);
                        
                    }else{
                        
                        intCustomerApi = isInsert ? Integracoes__c.getValues(IntegrationConstants.RESERVATION_INC_METADATA) : Integracoes__c.getValues(IntegrationConstants.RESERVATION_ALT_METADATA);
                        ReservationRequest reservationReq = new ReservationRequest(r.CodigoReserva__c.substring(5, 11),  r.Descricao__c, mapDistributionCenterCodeToListaCentroDistribuicao.containsKey(r.CodigoCD__c) ? mapDistributionCenterCodeToListaCentroDistribuicao.get(r.CodigoCD__c).CNPJCD__c : null, IntegrationContractOUT.getFormattedDate(Date.valueOf(r.FimReserva__c)), r.RecordType.Name, listReservationAccountReq, listReservationItemReq);
                        reservationsList.add(reservationReq);
                    }                    
                                       
                    System.debug('reservationsList ===> ' + reservationsList);
                   
                }
                listReservationRequest requestRes = new listReservationRequest(reservationsList);

                String body = Json.serialize(reservationsList[0]);
                
                System.debug('body ===> ' + body);  
            
                System.debug('====== intCustomerApi'+ intCustomerApi);
                String method   = intCustomerApi.Method__c;
                String endpoint = intCustomerApi.Endpoint__c;
                String username = intCustomerApi.User__c;
                String password = intCustomerApi.Password__c;
                
                
                HttpRequest req = new HttpRequest();
                req.setEndpoint(endpoint);
                req.setHeader(IntegrationConstants.AUTHORIZATION, IntegrationConstants.BASIC + EncodingUtil.base64Encode(Blob.valueOf(username + ':' + password)));
                req.setHeader(IntegrationConstants.HEADER_TYPE_CONTENT, IntegrationConstants.HEADER_TYPE_CONTENT_JSON);
                req.setMethod(method);
                req.setTimeout(IntegrationConstants.TIMEOUT);
                req.setBody(body);

                HttpResponse resp = new HttpResponse();
                resp = new Http().send(req);
                String resultString = resp.getBody();  
                
                System.debug('resultString ===> ' + resultString);
                IntegrationUtils.WSLog(IntegrationConstants.RESERVATION, IntegrationConstants.OUTBOUND, body, resultString, (resp.getStatusCode() == 200 || resp.getStatusCode() == 201) ? false : true);
                resultobj = (ResultClass)JSON.deserialize(resultString, ResultClass.class);

                if (method == 'POST') {

                    List<ProdutoReserva__c> listPd = new  List<ProdutoReserva__c>();

                    for (ReservationProductsRequest reservationProduct : reservationsList[0].produtos) {

                        for (String key : productsMap.keySet()) {

                            for (ProdutoReserva__c pd : productsMap.get(key)) {

                                if (reservationProduct.codigo == pd.CodigoProduto__c) {
                                    
                                    pd.StatusReserva__c = resultobj.message != 'Cadastro realizado com Sucesso !!!' ? IntegrationConstants.STATUS_INTEGRATION_ERROR : IntegrationConstants.STATUS_INTEGRATION_ACTIVE;
                                    pd.QuantidadeAtiva__c = resultobj.message != 'Cadastro realizado com Sucesso !!!' ? pd.QuantidadeAtiva__c : reservationProduct.quantidade;
                                    pd.ChaveUnica__c = resultobj.message != 'Cadastro realizado com Sucesso !!!' ? '' : pd.Reserva__r.CodigoCD__c + resultobj.detailMessage + pd.CodigoProduto__c + pd.Armazem__c;
                                   
                                    listPd.add(pd);
                                }
                                
                            }

                        }
                    }

                    update listPd;

                }else{
                    for (ReservationProductsRequest pd : reservationsList[0].produtos) {
                        String key = reservationsList[0].CodigoReserva+pd.codigo;
                        
                        if (checkProductInErrorMessage(pd.codigo, resultobj.message)) {
                            if(reservationMap.get(key).StatusReserva__c != 'Ativa') {
                                reservationMap.get(key).StatusReserva__c = IntegrationConstants.STATUS_INTEGRATION_ERROR;
                                reservationMap.get(key).QuantidadeAtiva__c = reservationMap.get(key).QuantidadeAtiva__c;
                            }
                        } else {
                            if (resultobj.detailMessage != 'Reserva alterada com sucesso !!!') {
                                reservationMap.get(key).StatusReserva__c = IntegrationConstants.STATUS_INTEGRATION_ERROR;
                                reservationMap.get(key).QuantidadeAtiva__c = reservationMap.get(key).QuantidadeAtiva__c;
                            } else {
                                reservationMap.get(key).StatusReserva__c = IntegrationConstants.STATUS_INTEGRATION_ACTIVE;
                                reservationMap.get(key).QuantidadeAtiva__c = pd.quantidade;
                            }
                        }
                    }
    
                    update reservationMap.values();
                }
            }
        } catch (Exception e){
            resultobj.message = e.getMessage();
            resultobj.detailMessage = '';
            System.debug(e.getMessage());
        }
        
        return resultobj;
    }

    public static Boolean checkProductInErrorMessage(String productCode, String erpMessage) {
        String unavailableStockMessage = 'Produtos com saldo indisponivel para alteracao/inclusao na reserva';

        if (erpMessage.contains(unavailableStockMessage)) {
            List<String> paramsString = erpMessage.split('>>>'); // msg >>> codProduto, codProduto..

            if (paramsString.size() == 2) {
                return paramsString[1].contains(productCode);
            }
        }

        return false;
    }

    public static List<Reserva__c> getReservations(List<Id> reservationsList){
        return [
            SELECT 
                Id, 
                CodigoReserva__c,
                CodigoReservaProtheus__c,
                FimReserva__c, 
                CentroDistribuicao__c, 
                MensagemErroIntegracao__c, 
                StatusReserva__c, 
                RecordType.Name, 
                CodigoCD__c, 
                Descricao__c 
            FROM Reserva__c 
            WHERE Id IN :reservationsList
        ];
    }

    @InvocableMethod(label='Send Reservation to Protheus' 
                    description='Send Reservation to Protheus')
    public static void sendToProtheus(List<Id> reservationIdList) {
        List<Reserva__c> listReservation = getReservations(reservationIdList);
        System.debug(JSON.serialize(listReservation));
        ResultClass response = IntegrationReservationOUT.sendReservationERP(listReservation, true);
        updateReservationInt(listReservation,response);
    }

    public static void updateReservationInt(List<Reserva__c> listReservation, ResultClass response){
        List<Reserva__c> reserUpdateList = new List<Reserva__c>();
        for(Reserva__c r : listReservation){
            r.MensagemErroIntegracao__c = response.message;
            if (response.message == 'Cadastro realizado com Sucesso !!!') {
                
                r.CodigoReserva__c = r.CodigoCD__c + response.detailMessage;
            }
            r.ErroIntegracao__c  = true;
            reserUpdateList.add(r);
        }
        update reserUpdateList;
    }

    @future(callout = true)
    public static void asyncSendToProtheus(List<Id> reservationIdList) {
        List<Reserva__c> listReservation = getReservations(reservationIdList);
        System.debug(JSON.serialize(listReservation));
        ResultClass response = IntegrationReservationOUT.sendReservationERP(listReservation, true);
        updateReservationInt(listReservation,response);
    }

    public static ResultClass deleteProductReservationERP(List<Reserva__c> listReservation, String productReservationId) {

        Map<String, ListaCentroDistribuicao__c> mapDistributionCenterCNPJToListaCentroDistribuicao = new Map<String, ListaCentroDistribuicao__c>();
        Map<String, ListaCentroDistribuicao__c> mapDistributionCenterCodeToListaCentroDistribuicao = new Map<String, ListaCentroDistribuicao__c>();
        Map<String, ProdutoReserva__c> reservationMap = new Map<String, ProdutoReserva__c>();
        ResultClass resultobj = new ResultClass();

        for(ListaCentroDistribuicao__c iListaDistribuicao : [
            SELECT Id, CNPJCD__c, CodigoCD__c, NomeCD__c 
            FROM ListaCentroDistribuicao__c 
            WHERE CNPJCD__c != NULL 
            AND CodigoCD__c != NULL 
            AND NomeCD__c != NULL]) {
            mapDistributionCenterCNPJToListaCentroDistribuicao.put(iListaDistribuicao.CNPJCD__c, iListaDistribuicao);
            mapDistributionCenterCodeToListaCentroDistribuicao.put(iListaDistribuicao.CodigoCD__c, iListaDistribuicao);
        }

        try {
            
            Integracoes__c intCustomerApi = new Integracoes__c();
            List<ReservationRequestDelete> reservationsList = new List<ReservationRequestDelete>();

            
            System.debug('====== listReservation'+ listReservation);
            if(listReservation.size() > 0){

                Map<Id, List<ProdutoReserva__c>> productsMap = new Map<Id, List<ProdutoReserva__c>>();
                for(ProdutoReserva__c r : [SELECT Id, Reserva__r.CodigoCD__c, Armazem__c, Reserva__c, Produto__r.ExternalId__c, QuantidadeReservada__c, QuantidadeAtiva__c, Reserva__r.CodigoReserva__c, CodigoProduto__c FROM ProdutoReserva__c WHERE Id =: productReservationId]){
                    if (productsMap.containsKey(r.Reserva__c)){
                        productsMap.get(r.Reserva__c). add(r);
                    }else{
                        List<ProdutoReserva__c> productList = new List<ProdutoReserva__c>();
                        productList.add(r);
                        productsMap.put(r.Reserva__c, productList);
                    }

                    if (!String.isBlank(r.Reserva__r.CodigoReserva__c)) {
                        
                        if (!reservationMap.containsKey(r.Reserva__r.CodigoReserva__c.substring(5, 11)+r.CodigoProduto__c)) {
                        
                            reservationMap.put(r.Reserva__r.CodigoReserva__c.substring(5, 11)+r.CodigoProduto__c, r);
                        }
                    }
                  
                }

                Set<String> setAccountCnpj = new Set<String>();                

                List<ReservationProductsRequest> listReservationItemReq = new List<ReservationProductsRequest>();

                intCustomerApi = Integracoes__c.getValues(IntegrationConstants.RESERVATION_DEL_METADATA);

                for (Reserva__c r : listReservation) {
                    
                    for(ProdutoReserva__c prod : productsMap.get(r.Id)){
                        ReservationProductsRequest productObj = new ReservationProductsRequest(prod);
                        listReservationItemReq.add(productObj);
                    }
                    ReservationRequestDelete deleteRequest = new ReservationRequestDelete(mapDistributionCenterCodeToListaCentroDistribuicao.containsKey(r.CodigoCD__c) ? mapDistributionCenterCodeToListaCentroDistribuicao.get(r.CodigoCD__c).CNPJCD__c : null, r.CodigoReserva__c.substring(5, 11), r.RecordType.Name, new List<ReservationAccountsRequest>(), listReservationItemReq);
                    reservationsList.add(deleteRequest);
                }         
                   
                }

                String body = Json.serialize(reservationsList[0]);
                
                System.debug('body ===> ' + body);  
            
                System.debug('====== intCustomerApi'+ intCustomerApi);
                String method   = intCustomerApi.Method__c;
                String endpoint = intCustomerApi.Endpoint__c;
                String username = intCustomerApi.User__c;
                String password = intCustomerApi.Password__c;
                
                
                HttpRequest req = new HttpRequest();
                req.setEndpoint(endpoint);
                req.setHeader(IntegrationConstants.AUTHORIZATION, IntegrationConstants.BASIC + EncodingUtil.base64Encode(Blob.valueOf(username + ':' + password)));
                req.setHeader(IntegrationConstants.HEADER_TYPE_CONTENT, IntegrationConstants.HEADER_TYPE_CONTENT_JSON);
                req.setMethod(method);
                req.setTimeout(IntegrationConstants.TIMEOUT);
                req.setBody(body);

                HttpResponse resp = new HttpResponse();
                resp = new Http().send(req);
                String resultString = resp.getBody();
                resultobj = (ResultClass)JSON.deserialize(resultString, ResultClass.class);
                
                System.debug('resultString ===> ' + resultString);
                System.debug('resultobj ===> ' + resultobj);
                IntegrationUtils.WSLog(IntegrationConstants.RESERVATION, IntegrationConstants.OUTBOUND, body, resultString, (resp.getStatusCode() == 200 || resp.getStatusCode() == 201) ? false : true);
                    
                // return resultobj.message != 'Exclusao realizada com sucesso' ? false : true;
                return resultobj;


        }catch (Exception e){
            // resultobj.message = e.getMessage();
            // resultobj.detailMessage = '';
            System.debug(e.getMessage());
            ResultClass result = new ResultClass();
            result.message = e.getMessage();
            result.detailMessage = e.getStackTraceString();
            return result;
        }
    }

    public static Boolean deleteReservationHeaderERP(List<Reserva__c> listReservation) {
        if (listReservation.size() > 0) {
            Reserva__c currentReservation = listReservation[0];

            ListaCentroDistribuicao__c deliveryCenter = [
                SELECT 
                    Id, 
                    CNPJCD__c
                FROM ListaCentroDistribuicao__c 
                WHERE CodigoCD__c =: currentReservation.CodigoCD__c
                LIMIT 1
            ];

            if (deliveryCenter == null) {
                return false;
            }
            
            try {
                ReservationRequestDelete deleteRequest = new ReservationRequestDelete(
                    deliveryCenter.CNPJCD__c,
                    currentReservation.CodigoReservaProtheus__c,
                    currentReservation.RecordType.Name,
                    new List<ReservationAccountsRequest>(),
                    new List<ReservationProductsRequest>()
                );
                    
                String body = JSON.serialize(deleteRequest);
                System.debug('body ===> ' + body);
                
                ResultClass resultobj = new ResultClass();
                Integracoes__c intCustomerApi = Integracoes__c.getValues(IntegrationConstants.RESERVATION_DEL_METADATA);
                System.debug('====== intCustomerApi'+ intCustomerApi);
                String method   = intCustomerApi.Method__c;
                String endpoint = intCustomerApi.Endpoint__c;
                String username = intCustomerApi.User__c;
                String password = intCustomerApi.Password__c;

                HttpRequest req = new HttpRequest();
                req.setEndpoint(endpoint);
                req.setHeader(IntegrationConstants.AUTHORIZATION, IntegrationConstants.BASIC + EncodingUtil.base64Encode(Blob.valueOf(username + ':' + password)));
                req.setHeader(IntegrationConstants.HEADER_TYPE_CONTENT, IntegrationConstants.HEADER_TYPE_CONTENT_JSON);
                req.setMethod(method);
                req.setTimeout(IntegrationConstants.TIMEOUT);
                req.setBody(body);

                HttpResponse resp = new HttpResponse();
                resp = new Http().send(req);
                String resultString = resp.getBody();
                resultobj = (ResultClass) JSON.deserialize(resultString, ResultClass.class);
                
                System.debug('resultString ===> ' + resultString);
                System.debug('resultobj ===> ' + resultobj);
                IntegrationUtils.WSLog(IntegrationConstants.RESERVATION, IntegrationConstants.OUTBOUND, body, resultString, (resp.getStatusCode() == 200 || resp.getStatusCode() == 201) ? false : true);
                    
                return resultobj.message != 'Exclusao realizada com sucesso' ? false : true;
            } catch (Exception e) {
                System.debug(e.getMessage());
                return false;
            }
        } else {
            return false;
        }
    }
}