Git Tests/force-app/main/default/default/objects/Account/fields/Armazem__c.field-meta.xml
<CustomField>
    <fullName>Armazem__c</fullName>
    <label>Armazém</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <externalId>true</externalId>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/DestinatarioReserva__c/DestinatarioReserva__c.object-meta.xml
<CustomObject>
    <label>Destinatário da reserva</label>
    <nameField>
        <displayFormat>DR-{000000}</displayFormat>
        <label>Nome de Destinatário da reserva</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Destinatários da reserva</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/DestinatarioReserva__c/fields/Reserva__c.field-meta.xml
<CustomField>
    <fullName>Reserva__c</fullName>
    <label>Reserva</label>
    <referenceTo>Reserva__c</referenceTo>
    <relationshipLabel>Destinatários da reserva</relationshipLabel>
    <relationshipName>DestinatariosReserva</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Fornecedor__c/Fornecedor__c.object-meta.xml
<CustomObject>
    <label>Fornecedor</label>
    <nameField>
        <label>Nome do fornecedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fornecedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Fornecedor__c/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Fornecedor__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do fornecedor</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/CategoriaComercial__c.field-meta.xml
<CustomField>
    <fullName>CategoriaComercial__c</fullName>
    <label>Categoria comercial</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>G</fullName>
                <label>GENÉRICO</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>MATERIAIS</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>NUTRIÇÃO</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Medctech</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>REFERÊNCIA</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>AMBOS</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>DIABETES</label>
            </value>
            <value>
                <fullName>Q</fullName>
                <label>ODONTOLOGIA</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Especialidade</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <label>EQUIPAMENTO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do produto</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fornecedor</label>
    <referenceTo>Fornecedor__c</referenceTo>
    <relationshipLabel>Produtos</relationshipLabel>
    <relationshipName>Produtos</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/UnidadeMedida__c.field-meta.xml
<CustomField>
    <fullName>UnidadeMedida__c</fullName>
    <label>Unidade de medida</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/ProdutoReserva__c.object-meta.xml
<CustomObject>
    <label>Produto da reserva</label>
    <nameField>
        <displayFormat>PR-{00000000}</displayFormat>
        <label>Nome de Produto da reserva</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Produtos da reserva</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/Armazem__c.field-meta.xml
<CustomField>
    <fullName>Armazem__c</fullName>
    <externalId>true</externalId>
    <label>Armazém</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <formula>Produto__r.Fornecedor__r.Name</formula>
    <label>Fornecedor</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/Preco__c.field-meta.xml
<CustomField>
    <fullName>Preco__c</fullName>
    <label>Preço</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Produtos da reserva</relationshipLabel>
    <relationshipName>ProdutosReserva</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/QuantidadeConsumida__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeConsumida__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantidade consumida</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/QuantidadeTransferida__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeTransferida__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Quantidade transferida</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/Reserva__c.field-meta.xml
<CustomField>
    <fullName>Reserva__c</fullName>
    <label>Reserva</label>
    <referenceTo>Reserva__c</referenceTo>
    <relationshipLabel>Produtos da reserva</relationshipLabel>
    <relationshipName>ProdutosReserva</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/ReservaRecebedora__c.field-meta.xml
<CustomField>
    <fullName>ReservaRecebedora__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Reserva recebedora</label>
    <referenceTo>Reserva__c</referenceTo>
    <relationshipLabel>Produtos da reserva (Reserva recebedora)</relationshipLabel>
    <relationshipName>ProdutoReserva</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/StatusReserva__c.field-meta.xml
<CustomField>
    <fullName>StatusReserva__c</fullName>
    <label>Status da reserva</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando aprovação</fullName>
            </value>
            <value>
                <fullName>Ativa</fullName>
            </value>
            <value>
                <fullName>Rejeitada</fullName>
            </value>
            <value>
                <fullName>Aguardando integração</fullName>
            </value>
            <value>
                <fullName>Erro de integração</fullName>
            </value>
            <value>
                <fullName>Aguardando exclusão</fullName>
            </value>
            <value>
                <fullName>Expirada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Reserva__c/Reserva__c.object-meta.xml
<CustomObject>
    <label>Reserva</label>
    <nameField>
        <displayFormat>RE-{000000}</displayFormat>
        <label>Nome da reserva</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Reserva__c/fields/CodigoReserva__c.field-meta.xml
<CustomField>
    <fullName>CodigoReserva__c</fullName>
    <externalId>true</externalId>
    <label>Código da reserva</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Reserva__c/fields/StatusReserva__c.field-meta.xml
<CustomField>
    <fullName>StatusReserva__c</fullName>
    <label>Status da reserva</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativa</fullName>
                <default>true</default>
                <label>Ativa</label>
            </value>
            <value>
                <fullName>Expirada</fullName>
            </value>
            <value>
                <fullName>Aguardando aprovação</fullName>
                <isActive>false</isActive>
                <label>Aguardando aprovação</label>
            </value>
            <value>
                <fullName>Aguardando envio de exclusão</fullName>
                <isActive>false</isActive>
                <label>Aguardando envio de exclusão</label>
            </value>
            <value>
                <fullName>Aguardando integração</fullName>
                <isActive>false</isActive>
                <label>Aguardando integração</label>
            </value>
            <value>
                <fullName>Aprovada</fullName>
                <isActive>false</isActive>
                <label>Aprovada</label>
            </value>
            <value>
                <fullName>Cancelada</fullName>
                <isActive>false</isActive>
                <label>Cancelada</label>
            </value>
            <value>
                <fullName>Em digitação</fullName>
                <isActive>false</isActive>
                <label>Em digitação</label>
            </value>
            <value>
                <fullName>Erro de integração</fullName>
                <isActive>false</isActive>
                <label>Erro de integração</label>
            </value>
            <value>
                <fullName>Integrado</fullName>
                <isActive>false</isActive>
                <label>Integrado</label>
            </value>
            <value>
                <fullName>Rejeitada</fullName>
                <isActive>false</isActive>
                <label>Rejeitada</label>
            </value>
            <value>
                <fullName>Vencida</fullName>
                <isActive>false</isActive>
                <label>Vencida</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Reserva__c/recordTypes/ReservaRegional.recordType-meta.xml
<RecordType>
    <fullName>ReservaRegional</fullName>
    <active>true</active>
    <label>Reserva regional</label>
</RecordType>

Git Tests/force-app/main/default/default/objects/ResponsabilidadeAprovacao__c/ResponsabilidadeAprovacao__c.object-meta.xml
<CustomObject>
    <label>Responsabilidade de aprovação</label>
    <nameField>
        <displayFormat>RA-{00000}</displayFormat>
        <label>Nome de Responsabilidade de aprovação</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Responsabilidades de aprovação</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ResponsabilidadeAprovacao__c/fields/Categorias__c.field-meta.xml
<CustomField>
    <fullName>Categorias__c</fullName>
    <label>Categorias</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>AMBOS</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>DIABETES</label>
            </value>
            <value>
                <fullName>G</fullName>
                <label>GENÉRICO</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>MATERIAIS</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>NUTRIÇÃO</label>
            </value>
            <value>
                <fullName>Q</fullName>
                <label>ODONTOLOGIA</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>MEDCTECH</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>SPECIALTY</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <label>EQUIPAMENTO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/ResponsabilidadeAprovacao__c/fields/CodigoMesa__c.field-meta.xml
<CustomField>
    <fullName>CodigoMesa__c</fullName>
    <externalId>true</externalId>
    <label>Código da mesa</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ResponsabilidadeAprovacao__c/fields/Regiao__c.field-meta.xml
<CustomField>
    <fullName>Regiao__c</fullName>
    <externalId>true</externalId>
    <label>Região</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ResponsabilidadeAprovacao__c/fields/UsuarioAprovador__c.field-meta.xml
<CustomField>
    <fullName>UsuarioAprovador__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário aprovador</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ResponsabilidadeAprovacao</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ResponsabilidadeAprovacao__c/recordTypes/AprovacaoReserva.recordType-meta.xml
<RecordType>
    <fullName>AprovacaoReserva</fullName>
    <active>true</active>
    <label>Aprovação reserva de produto</label>
</RecordType>

Git Tests/force-app/main/default/default/classes/ReservationProductTriggerTest.cls
@isTest
public with sharing class ReservationProductTriggerTest {
   
    @TestSetup
    static void makeData(){

        Fornecedor__c fornecedor = new Fornecedor__c(Name = 'testfor', ExternalId__c = '12345');
        insert fornecedor;

        Product2 product = TestUtility.createProduct();
        product.ExternalId__c = '1234';
        product.UnidadeMedida__c = 'F';
        product.fornecedor__c = fornecedor.Id;
        product.CategoriaComercial__c = 'G';
        insert product;
        
        Account acc = TestUtility.createAccount();
        acc.CNPJ__c = '61182609000113';
       
        Reserva__c reservation = TestUtility.createReservation();
        reservation.RecordTypeId = Schema.SObjectType.Reserva__c.getRecordTypeInfosByDeveloperName().get('ReservaRegional').getRecordTypeId();
        insert reservation;

        Reserva__c reservation2 = TestUtility.createReservation();
        reservation2.RecordTypeId = Schema.SObjectType.Reserva__c.getRecordTypeInfosByDeveloperName().get('ReservaRegional').getRecordTypeId();
        reservation2.CodigoReserva__c = '5';
        insert reservation2;

        ProdutoReserva__c reservationProd = TestUtility.createReservationProduct(reservation.Id, product.Id);
        insert reservationProd;

        ProdutoReserva__c reservationProd2 = TestUtility.createReservationProduct(reservation.Id, product.Id);
        reservationProd2.Armazem__c = '20';
        insert reservationProd2;        

        ProdutoReserva__c reservationProd3 = TestUtility.createReservationProduct(reservation.Id, product.Id);
        reservationProd3.Armazem__c = '30';
        insert reservationProd3;              
        
        DestinatarioReserva__c reservationDest = TestUtility.createReservationDest(reservation.Id, acc.Id);
        insert reservationDest;

        DestinatarioReserva__c reservationDest2 = TestUtility.createReservationDest(reservation.Id, acc.Id);
        insert reservationDest2;

        ResponsabilidadeAprovacao__c respAprovacao = new ResponsabilidadeAprovacao__c();
        respAprovacao.UsuarioAprovador__c = UserInfo.getUserId();
        respAprovacao.Categorias__c = 'M';
        respAprovacao.CodigoMesa__c = 'TESTE';
        respAprovacao.Regiao__c ='ABCDE';
        respAprovacao.Categorias__c ='';
        respAprovacao.RecordTypeId =Schema.SObjectType.ResponsabilidadeAprovacao__c.getRecordTypeInfosByDeveloperName().get('AprovacaoReserva').getRecordTypeId();

        insert respAprovacao;

        ResponsabilidadeAprovacao__c respAprovacao2 = new ResponsabilidadeAprovacao__c();
        respAprovacao2.UsuarioAprovador__c = UserInfo.getUserId();
        respAprovacao2.Categorias__c = 'M';
        respAprovacao2.CodigoMesa__c = 'TESTE';
        respAprovacao2.Regiao__c ='ABCDE';
        respAprovacao2.Categorias__c ='G';
        respAprovacao2.RecordTypeId =Schema.SObjectType.ResponsabilidadeAprovacao__c.getRecordTypeInfosByDeveloperName().get('AprovacaoReserva').getRecordTypeId();

        insert respAprovacao2;
    }

    @isTest
    public static void ReservationProductTest() {

        ReservationProductTriggerHelper reserva = new ReservationProductTriggerHelper();

        List<Reserva__c> lstReserva = [SELECT id FROM Reserva__c];      
        List<ProdutoReserva__c> lstProdutoReserva = [SELECT id,ReservaRecebedora__c,Produto__c,QuantidadeTransferida__c, Armazem__c, Preco__c FROM ProdutoReserva__c];      
        List<ResponsabilidadeAprovacao__c> lstResponsabilidadeAprovacao = [SELECT id,Regiao__c,Categorias__c,UsuarioAprovador__c FROM ResponsabilidadeAprovacao__c];      

        System.debug(lstResponsabilidadeAprovacao);
        System.debug([
            SELECT id, Regiao__c, Categorias__c, UsuarioAprovador__c
            FROM
            ResponsabilidadeAprovacao__c
            WHERE
            Regiao__c IN('ABCDE')
            AND RecordTypeId IN('012q0000000BnOQAA0')
            AND (Categorias__c INCLUDES('G') 
            OR Categorias__c = null)                                                               
        ]);
        ReservationProductTriggerHandler.disableTrigger();
        ReservationProductTriggerHandler.enableTrigger();        
        ReservationProductTriggerHandler.isTriggerEnabled();

        Test.startTest();

        ReservationProductTriggerHelper.createInstanceReservationProduct(lstProdutoReserva[1]);
        
        delete lstProdutoReserva[1];

        lstProdutoReserva[2].ReservaRecebedora__c = lstReserva[0].Id;
        lstProdutoReserva[2].StatusReserva__c = 'Aguardando Integração';
        update  lstProdutoReserva[2];

        lstProdutoReserva[0].StatusReserva__c = 'Aguardando aprovação';
        lstProdutoReserva[0].QuantidadeConsumida__c = 4;
        update lstProdutoReserva[0];

        List<ProcessInstanceWorkitem> lstProcessInstanceWorkitem =  [SELECT p.ProcessInstance.Status, p.ProcessInstance.TargetObjectId,
                                                                    p.ProcessInstanceId,
                                                                    p.OriginalActorId,
                                                                    p.Id,
                                                                    p.ActorId FROM ProcessInstanceWorkitem p
                                                                    WHERE p.ProcessInstance.TargetObjectId = : lstProdutoReserva[0].Id];


        Approval.ProcessWorkitemRequest req2 = new Approval.ProcessWorkitemRequest();
        req2.setComments('Approving request.');
        req2.setAction('Approve');
        req2.setNextApproverIds(new Id[] {UserInfo.getUserId()});

        // Use the ID from the newly created item to specify the item to be worked
        req2.setWorkitemId(lstProcessInstanceWorkitem[0].Id);

        // Submit the request for approval
        Approval.ProcessResult result2 = Approval.process(req2);


        lstProdutoReserva[0].StatusReserva__c = 'Ativa';
        update lstProdutoReserva[0];

        Test.stopTest();

    }
}