Git Tests/force-app/main/default/default/objects/Account/fields/Bloqueado__c.field-meta.xml
<CustomField>
    <fullName>Bloqueado__c</fullName>
    <label>Ativo?</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativo</fullName>
            </value>
            <value>
                <fullName>Inativo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/Deletado__c.field-meta.xml
<CustomField>
    <fullName>Deletado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deletado</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/TabelaPrecos__c.field-meta.xml
<CustomField>
    <fullName>TabelaPrecos__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tabela de preços</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/TipoCliente__c.field-meta.xml
<CustomField>
    <fullName>TipoCliente__c</fullName>
    <label>Tipo do cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamento__c/CondicaoPagamento__c.object-meta.xml
<CustomObject>
    <label>Condição de pagamento</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condições de pagamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Order/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Chave única: Número do pedido + Código do CD</description>
    <externalId>true</externalId>
    <label>Código do pedido TOTVS</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/TipoCliente__c.field-meta.xml
<CustomField>
    <fullName>TipoCliente__c</fullName>
    <formula>Account.TipoCliente__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo de Cliente</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Pricebook2/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Catálogos de preços</relationshipLabel>
    <relationshipName>CatalogoPreco</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Pricebook2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/Deletado__c.field-meta.xml
<CustomField>
    <fullName>Deletado__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Deletado</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do produto</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/classes/CustomLookupControllerTest.cls
@IsTest
public with sharing class CustomLookupControllerTest {
    @TestSetup
    static void makeData(){
        CondicaoPagamento__c conditionMakeData = TestUtility.createConditionPayment();
        insert conditionMakeData;
        CustomLookupController.CondicaoData conditionData = new CustomLookupController.CondicaoData(conditionMakeData);

        Account accountMakeData = TestUtility.createAccPJ();
        insert accountMakeData;
        CustomLookupController.AccData accData         = new CustomLookupController.AccData(accountMakeData);
        CustomLookupController.AccountData accountData = new CustomLookupController.AccountData(accountMakeData);

        Contact contactMakeData = TestUtility.createContact(accountMakeData.Id);
        insert contactMakeData;
        CustomLookupController.ContactData contactData = new CustomLookupController.ContactData(contactMakeData);

        Product2 product = TestUtility.createProduct();
        insert product;
        Pricebook2 pricebook = TestUtility.createPricebook2(product);
        CustomLookupController.Pricebook2Data pricebookData = new CustomLookupController.Pricebook2Data(pricebook);
    }

    @IsTest
    public static void fetchLookupValuesTest() {
        List<Account> accountList = [SELECT Id, Name FROM Account WHERE Name LIKE: 'Teste 1' ORDER BY createdDate DESC limit 5];

        System.assertEquals(accountList, CustomLookUpController.fetchLookUpValues('Teste 1', 'Account'), 'fetchLookupValuesTest');
    }

    @IsTest
    public static void getAccountsTest() {
        List<Account> accountList = [SELECT Id, Name, ExternalId__c, TipoCliente__c, TabelaPrecos__c, CondicaoPagamento__c, CondicaoPagamento__r.Name, Bloqueado__c FROM Account WHERE Deletado__c = false LIMIT 10];

        System.assertEquals(accountList, CustomLookUpController.getAccounts(), 'getAccountsTest');
    }

    @IsTest
    public static void searchObjectTest() {
        List<String> fields = new List<String>{'Name'};

        String searchKeyword = 'Account' + '*';
        String returningQuery = '';
        returningQuery = 'Account' + ' ( Id, ' + String.join(fields, ',') + ')';
        String query = 'FIND :searchKeyword IN ALL FIELDS RETURNING ' + returningQuery + ' LIMIT 20';
        System.debug(' query ' + query);
        List<List<sObject>> searchRecords = Search.Query(Query);
        List<Account> accountList = searchRecords.get(0);

        System.assertEquals(accountList, CustomLookUpController.searchObject('Account', fields, 'Account'), 'searchObjectTest');
    }

    @IsTest
    public static void searchTest() {
        List<Account> accountList = [SELECT Id, Name FROM Account WHERE LastViewedDate != NULL ORDER BY LastViewedDate DESC LIMIT  5];

        //System.assertEquals(accountList, CustomLookUpController.search('Teste 1', 'Account', ''), 'searchTest');
        //System.assertEquals(accountList, CustomLookUpController.search('Teste 1', 'Account', ''), 'searchTest');
        System.assertEquals(accountList, CustomLookUpController.search('', 'Account', ''), 'searchTest');
    }

    @IsTest
    public static void getAvailableDataTest() {
        Account account = TestUtility.createAccount();
        insert account;
        CondicaoPagamento__c conditionP = TestUtility.createConditionPayment();
        insert conditionP;
        Contact contact = TestUtility.createContact(account);
        insert contact;

        System.assertEquals('[]', CustomLookUpController.getAvailableData(String.valueOf(account.Id), String.valueOf(conditionP.Id), 'Account', 'Pricebook2'), 'getAvailableDataTest 1');
        System.assertEquals('[]', CustomLookUpController.getAvailableData(String.valueOf(account.Id), String.valueOf(conditionP.Id), 'Account', 'CondicaoPagamento__c'), 'getAvailableDataTest 2');
        System.assertEquals('[]', CustomLookUpController.getAvailableData(String.valueOf(account.Id), String.valueOf(conditionP.Id), 'Account', 'Contact'), 'getAvailableDataTest 3');
        System.assertEquals('[]', CustomLookUpController.getAvailableData(String.valueOf(account.Id), String.valueOf(conditionP.Id), 'Account', ''), 'getAvailableDataTest 4');
    }

    @IsTest
    public static void getRecordsTest() {
        System.assertNotEquals(null, CustomLookUpController.getRecords('SELECT Id, Name FROM Account', 'Account'), 'getRecordsTest 1');
        System.assertNotEquals(null, CustomLookUpController.getRecords('SELECT Id, Name FROM CondicaoPagamento__c', 'CondicaoPagamento__c'), 'getRecordsTest 2');
        System.assertNotEquals(null, CustomLookUpController.getRecords('SELECT Id, Name FROM Pricebook2', 'Pricebook2'), 'getRecordsTest 3');
        System.assertEquals(null, CustomLookUpController.getRecords('', 'Contact'), 'getRecordsTest');
    }

    @IsTest
    public static void getContaOrdemTest() {
        Account account = TestUtility.createAccount();
        insert account;
        
        System.assertNotEquals(null, CustomLookUpController.getContaOrdem(account.Id, null), 'getContaOrdemTest');
    }

    @IsTest
    public static void getRecordTypeIdsTest() {
        Account account = TestUtility.createAccount();
        insert account;

        List<Account> accountList = [SELECT Id, Name FROM Account WHERE Name = 'Teste 1'];

        System.assertEquals(null, CustomLookUpController.getRecordTypeIds('', '', ''), 'getRecordTypeIdsTest');
        //System.assertEquals(accountList, CustomLookUpController.getRecordTypeIds('Account', 'Name', 'Name = 'Teste 1''), 'getRecordTypeIdsTest');
    }
}