Git Tests/force-app/main/default/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <externalId>true</externalId>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Campaign/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Campaign/fields/CodigoCD__c.field-meta.xml
<CustomField>
    <fullName>CodigoCD__c</fullName>
    <label>Código de CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Campaign/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <label>Condição de pagamento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Campaign/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código da campanha</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Campaign/recordTypes/Campanha.recordType-meta.xml
<RecordType>
    <fullName>Campanha</fullName>
    <active>true</active>
    <description>Tipo de registro utilizado para campanhas de produtos</description>
    <label>Campanha de produto</label>
</RecordType>

Git Tests/force-app/main/default/default/objects/Contract/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <formula>Account.CNPJ__c</formula>
    <label>CNPJ</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Estoque__c/Estoque__c.object-meta.xml
<CustomObject>
    <label>Estoque</label>
    <nameField>
        <label>Número do estoque</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estoques</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Estoque__c/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <externalId>true</externalId>
    <label>CNPJ CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Estoque__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do estoque</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Estoque__c/recordTypes/Estoque.recordType-meta.xml
<RecordType>
    <fullName>Estoque</fullName>
    <active>true</active>
    <description>Identificação do estoque para criação de pedidos e cotações.</description>
    <label>Estoque</label>
</RecordType>

Git Tests/force-app/main/default/default/objects/Integracoes__c/Integracoes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuração  personalizada utilizada para gerir os dados de acessos das integrações</description>
    <label>Integrações</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <inlineHelpText>URL de acesso ao serviço</inlineHelpText>
    <label>EndPoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Método</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Senha</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>Usuário</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/ItemCampanha__c.object-meta.xml
<CustomObject>
    <label>Item da campanha</label>
    <nameField>
        <label>Código do item de campanha</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens da campanha</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do item de campanha</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/VigenciaFinal__c.field-meta.xml
<CustomField>
    <fullName>VigenciaFinal__c</fullName>
    <label>Vigência final</label>
    <type>Date</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/ItemContrato__c.object-meta.xml
<CustomObject>
    <label>Item de contrato</label>
    <nameField>
        <displayFormat>IT-{00000000}</displayFormat>
        <label>Número do item de contrato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens de contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rascunho</fullName>
                <default>true</default>
                <label>Rascunho</label>
            </value>
            <value>
                <fullName>Em Aprovação</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
            <value>
                <fullName>Expirado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
            <value>
                <fullName>Aguardando integração</fullName>
            </value>
            <value>
                <fullName>Ativo</fullName>
                <isActive>false</isActive>
                <label>Ativo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/fields/VigenciaFinal__c.field-meta.xml
<CustomField>
    <fullName>VigenciaFinal__c</fullName>
    <label>Vigência final</label>
    <type>Date</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <formula>Account.CNPJ__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CNPJ</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Orcamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Chave Externa</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/FatorConversao__c.field-meta.xml
<CustomField>
    <fullName>FatorConversao__c</fullName>
    <label>Fator de Conversao</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/ItemCampanha__c.field-meta.xml
<CustomField>
    <fullName>ItemCampanha__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item da campanha</label>
    <referenceTo>ItemCampanha__c</referenceTo>
    <relationshipLabel>Produto do orçamento</relationshipLabel>
    <relationshipName>ProdutoOrcamento</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NÃO IDENTIFICADO</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>IDENTIFICADO</fullName>
            </value>
            <value>
                <fullName>QUALIFICADO</fullName>
            </value>
            <value>
                <fullName>Respondido</fullName>
            </value>
            <value>
                <fullName>Resgatado</fullName>
            </value>
            <value>
                <fullName>Aguardando Integração</fullName>
            </value>
            <value>
                <fullName>Falha na Integração</fullName>
            </value>
            <value>
                <fullName>Não Vinculado</fullName>
            </value>
            <value>
                <fullName>Vinculado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/ValorPortal__c.field-meta.xml
<CustomField>
    <fullName>ValorPortal__c</fullName>
    <inlineHelpText>Valor Portal</inlineHelpText>
    <label>Valor Portal</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do produto</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/FatorConversao__c.field-meta.xml
<CustomField>
    <fullName>FatorConversao__c</fullName>
    <label>Fator de conversão</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <description>
        Objeto recebido na integração do portal de cotações (class: IntegrationPortalQuoteIN) e
        utilizado para armazenar as requisições de produtos efetuada pelos clientes,
        assim como a resposta efetuada pelos vendedores.
        Sua estrutura a nível de negócio existe de duas formas:
        1. a nível de item, sendo o item entendido como as informações advindas da integração com a requisição do cliente.
        2. a nível de resposta, sendo a resposta entendida como as informações enviadas do vendedor para o cliente como resposta.
        Esse objeto pode ser visualizado a nível de usuário nas telas de orçamento do tipo portal (Opportunity > RecordType > OrcamentoPortal),
        que é o mestre do relacionamento mestre-detalhe contido nesse objeto.
        O item é enviado ao portal como resposta na integração do portal de cotação (class: IntegrationPortalQuoteOUT).
        E também é enviado quando é efetuado vínculo de produto (class: IntegrationPortalVinculoOUT)
    </description>
    <label>Item da Cotação</label>
    <nameField>
        <label>Nome do Item da Cotação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens da Cotação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <description>Cnpj do centro de distribuição vinculado</description>
    <label>CNPJ do CD</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>OpportunityId__r.ExternalPortal__c + _ + IdPotal__c + _ + Vendedor__c + _ + Categoria__c</description>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Chave Externa</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/FatorConversao__c.field-meta.xml
<CustomField>
    <fullName>FatorConversao__c</fullName>
    <description>
        campo utilizado para armazenar o fator de conversão inputado pelo vendedor durante a resposta cotada
        Também pode ser visto como a quantidade presente em caixa caso o valor do TipoConversao__c seja Dividir
    </description>
    <label>Fator de Conversao</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Identificador de condição da resposta, (Responde a pergunta: Em que estapa está a resposta?)</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NÃO IDENTIFICADO</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>IDENTIFICADO</fullName>
            </value>
            <value>
                <fullName>QUALIFICADO</fullName>
            </value>
            <value>
                <fullName>Respondido</fullName>
            </value>
            <value>
                <fullName>Resgatado</fullName>
            </value>
            <value>
                <fullName>Aguardando Integração</fullName>
            </value>
            <value>
                <fullName>Falha na Integração</fullName>
            </value>
            <value>
                <fullName>Não Vinculado</fullName>
                <default>true</default>
                <label>Não Vinculado</label>
            </value>
            <value>
                <fullName>Vinculado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/classes/BudgetInfoCDControllerTest.cls
@isTest
public with sharing class BudgetInfoCDControllerTest {
    @TestSetup
    static void makeData(){
        Integracoes__c integrationConfigPortal = new Integracoes__c(
			Name        = 'InformaticaGetMalhaPortal',
			Method__c   = 'POST',
			Endpoint__c = 'undefined',
			User__c     = 'sample@grupoelfa.com.br',
			Password__c = 'samplePassword'
		);
        insert integrationConfigPortal;
        Account account = TestUtility.createAccPJ();
        account.CNPJ__c = '60495624000159';
        insert account;
        
        Contact contact = TestUtility.createContact(account);

        CondicaoPagamento__c conPay = TestUtility.createPaymentCondition2();
        conPay.ExternalId__c = '043';
        insert conPay;

        Opportunity oppWon = TestUtility.createOpportunity(account, contact, conPay);
        oppWon.StageName = 'Gerar Pedido';
        Opportunity oppLost = TestUtility.createOpportunity(account, contact, conPay);
        oppLost.StageName = 'Sem Retorno';
        insert new List<Opportunity>{oppWon, oppLost};

        Product2 product = TestUtility.createProduct();
        product.FatorConversao__c = '1';
        product.ProductCode = '1001';
        insert product;
        
        PricebookEntry pricebookEntry = [
            SELECT Id 
            FROM PricebookEntry 
            WHERE Product2Id = :product.Id 
            AND PriceBook2Id = :Test.getStandardPricebookId() 
            LIMIT 1
        ];

        OpportunityLineItem oppLineItemWon = TestUtility.createOpportunityLineItem(oppWon, product, pricebookEntry);
        oppLineItemWon.ValorPortal__c = 10;
        OpportunityLineItem oppLineItemLost = TestUtility.createOpportunityLineItem(oppLost, product, pricebookEntry);
        oppLineItemLost.ValorPortal__c = 10;
        insert new List<OpportunityLineItem>{oppLineItemWon, oppLineItemLost};

        Estoque__c estoque = TestUtility.createStock('getDistCenterTest', product.Id);
        estoque.ExternalId__c = 'getDistCenterTest';
        estoque.CNPJCD__c = '52202744000788';
        insert estoque;

        Campaign campanha = TestUtility.createCampaign();
        Campaign campanhaComCd = TestUtility.createCampaign();
        campanhaComCd.CodigoCD__c = '0101007';
        insert new List<Campaign>{campanha, campanhaComCd};

        ItemCampanha__c itemCamp = TestUtility.createItemCampanha(campanha.Id, product.Id);
        ItemCampanha__c itemCampComCd = TestUtility.createItemCampanha(campanhaComCd.Id, product.Id);

        insert new List<ItemCampanha__c>{itemCamp, itemCampComCd};

        Contract contractTypeA = TestUtility.createContract(account);
        insert contractTypeA;

        ItemContrato__c itemContrato = TestUtility.createContractItem(contractTypeA, product);
        //itemContrato.Status__c = 'Aprovado';
        itemContrato.VigenciaFinal__c = Date.today().addDays(1);
        insert itemContrato;

        QuoteItem__c qItem = TestUtility.createQuoteItem(oppWon);
        qItem.IdPortal__c = 'setItemCd';
        qItem.Categoria__c = 'M';
        qItem.OpportunityLineItem__c = oppLineItemWon.Id;
        qItem.Product__c = product.Id;
        insert qItem;
    }

    public class MockHttpResponseGenerator implements HttpCalloutMock {
        private Boolean isSuccess;
        private String integration;

        public MockHttpResponseGenerator(Boolean isSuccess, String integration){
            this.isSuccess   = isSuccess;
            this.integration = integration;
        }
        // Implement this interface method
        public HTTPResponse respond(HTTPRequest req) {
            // Create a fake response
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setStatusCode(this.isSuccess? 200 : 500);

            if (integration == 'Malha') {
                if (res.getStatusCode() == 200){
                    res.setBody('{"output": [{"cds": [{"aliquota": 18,"foramalha": false,"prioridade": "1","cnpj": "52202744000192","saldo": 4,"custo": 174.64,"cd": "0101001","filial": "NACIONAL - RIBEIRAO PRETO (MATRIZ)"},{"aliquota": 18,"foramalha": false,"prioridade": "2","cnpj": "52202744000788","saldo": 0,"custo": 274.89,"cd": "0101007","filial": "NACIONAL - SANT. DE PARNAIBA (FILIAL 03)"}],"codprotheus": "0000310","ean": null}]}');
                }
            } else if (integration == 'Lotes') {
                if (res.getStatusCode() == 200){
                    res.setBody('{"estoque": [{"cod_distribuicao": "1","cod_operacao_logistica": "1","cod_operacao_logistica_polo": "01006","cod_produto": "27","lote": "LOTE UNICO","estoque": "20.0000","retido": "0.0000","cod_produto_polo": "0000002","validade": "2025-12-31T00:00:00-03:00"}]}');
                }
            }
            return res;
        }
    }

    @isTest
    static void getGroupTest(){
        StandardResponse response = BudgetInfoCDController.getGroup();
        System.assertEquals(false, response.hasError);
    }

    @isTest
    static void getDistCenterTest(){
        CondicaoPagamento__c conPay = [SELECT Id FROM CondicaoPagamento__c WHERE ExternalId__c = '043' LIMIT 1];
        Account acc = [SELECT Id, RecordType.Name FROM Account WHERE CNPJ__c = '60495624000159'];
        BudgetCtrl.ParamsMalha paramsMalha = new BudgetCtrl.ParamsMalha();
        paramsMalha.cnpj = '60495624000159';
        paramsMalha.UF = 'SP';
        paramsMalha.productCode = '1001';
        paramsMalha.calcMargem = true;
        paramsMalha.pricebookExternalId = '043';
        paramsMalha.condPagamento = conPay.Id;
        paramsMalha.isForaMalha = false;
        String paramsMalhaJSON = JSON.serialize(paramsMalha);

        BudgetCtrl.ParamsProd paramsProd = new BudgetCtrl.ParamsProd();
        paramsProd.quantidadeSolicitada = 1;
        paramsProd.cdsBloqueados = '52202744000192;';
        paramsProd.accountId = acc.Id;
        paramsProd.accountType = acc.RecordType.Name;
        paramsProd.tipoConversao = 'M';
        paramsProd.fatorConversao = '10';
        paramsProd.unidadePrincipal = 'UN';
        paramsProd.unidadeSecundaria = 'CX';
        String paramsProdJSON = JSON.serialize(paramsProd);
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(true, 'Malha'));
        BudgetInfoCDController.getDistCenter(paramsMalhaJSON, paramsProdJSON);
        Test.stopTest();
    }

    @isTest
    static void getConversaoUnidadeTexto(){
        BudgetInfoCDController.getConversaoUnidadeTexto(
            'D', '1', 'CX', 'UN'
        );
        BudgetInfoCDController.getConversaoUnidadeTexto(
            'M', '1', 'CX', 'UN'
        );
        BudgetInfoCDController.getConversaoUnidadeTexto(
            'N', '1', 'CX', 'UN'
        );
        BudgetInfoCDController.getConversaoUnidadeTexto(
            'M', '', 'CX', 'UN'
        );
    }

    @isTest
    static void setItemCdTest(){
        QuoteItem__c qItem = [
            SELECT Id,
            OpportunityLineItem__c, OpportunityId__c,
            Product__c, Product__r.ProductCode 
            FROM QuoteItem__c 
            WHERE IdPortal__c = 'setItemCd'
        ];
        BudgetDetailEditItemController.BudgetResposta item = new BudgetDetailEditItemController.BudgetResposta();
        item.id = qItem.Id;
        item.categoria = 'String';
        item.categoriaDesc = 'String';
        item.categoriaVendedor = 'M';
        item.categoriaVendedorDesc = 'String';
        item.comentario = 'String';
        item.cnpjCd = '52202744000192';
        item.dataHoraResposta = String.valueOf(System.now());
        item.fatorConversao = 1;
        item.idPortal = 'setItemCd';
        item.itemId = qItem.OpportunityLineItem__c;
        item.marcaProdOfertado = 'String';
        item.nome = 'String';
        item.nomeCd = 'String';
        item.nomeVendedor = 'String';
        item.principioAtivo = 'String';
        item.prodCode = qItem.Product__r.ProductCode;
        item.prodId = qItem.Product__c;
        item.productURL = 'String';
        item.SequenciaOC = 'String';
        item.status = 'Vinculado';
        item.tabulacaoN1 = 'Cotado';
        item.temperatura = 'String';
        item.tipoConversao = 'M';
        item.unidadePrincipal = 'String';
        item.unidadeSecundaria = 'String';
        item.unitarioPortal = 1;
        item.valorBloqueado = false;
        item.vendedorId = UserInfo.getUserId();

        String budgetRespostaJSON = JSON.serialize(item);

        BudgetCtrl.DistCenter dCenter = new BudgetCtrl.DistCenter();
        dCenter.id = 'String';
        dCenter.nome = 'String';
        dCenter.cnpj = 'String';
        dCenter.custo = 1;
        dCenter.preco = 1;
        dCenter.aliquota = 1;
        dCenter.precoFabrica = 1;
        dCenter.estoque = 1;
        dCenter.prioridade = 'String';
        dCenter.foramalha = false;
        dCenter.unidadePrincipal = 'String';
        dCenter.quantidadeElfa = 1;
        dCenter.valorElfa = 1;
        dCenter.desconto = 1;
        dCenter.validadeMin = null;
        dCenter.score = 1;
        dCenter.margem = 1;
        dCenter.margemAlvo = 1;
        dCenter.quantidadePortal = 1;
        dCenter.valorPortal = 1;
        dCenter.valorTotal = 1;
        dCenter.cdBloqueado = false;
        dCenter.bloqueioRegional = false;
        dCenter.dataGanho = 'String';
        dCenter.valorGanho = 1;
        dCenter.dataPerdido = 'String';
        dCenter.valorPerdido = 1;
        dCenter.previsaoEntrada = 'String';
        dCenter.quantPrevista = 1;
        dCenter.unidadeSecundaria = 'String';
        dCenter.conversaoUnidadeTexto = 'String';
        dCenter.estoqueSecundario = 1;
        dCenter.precoSecundario = 1;
        dCenter.precoFabricaSecundario = 1;

        String dCenterJSON = JSON.serialize(dCenter);
        
        BudgetCtrl.ExtraFields extraFields = new BudgetCtrl.ExtraFields();
        extraFields.oppId = qItem.OpportunityId__c;
        extraFields.foraMalha = false;
        extraFields.fatorConversaoProd = 1;
        extraFields.tipoConversaoProd = 'M';
        extraFields.comentario  = 'String';

        String extraFieldsJSON = JSON.serialize(extraFields);

        BudgetInfoCDController.setItemCd(budgetRespostaJSON, dCenterJSON, extraFieldsJSON);

        item.itemId = null;
        budgetRespostaJSON = JSON.serialize(item);
        BudgetInfoCDController.setItemCd(budgetRespostaJSON, dCenterJSON, extraFieldsJSON);

    }

    @isTest
    static void getFatorProdutoTest(){
        QuoteItem__c qItem = [
            SELECT Id,
            Product__c
            FROM QuoteItem__c 
            WHERE IdPortal__c = 'setItemCd'
        ];
        Product2 updateProduct = new Product2(Id = qItem.Product__c);
        updateProduct.TipoConversao__c = 'M';
        update updateProduct;
        BudgetInfoCDController.getFatorProduto(qItem.Product__c, qItem.Id);
        updateProduct.TipoConversao__c = 'D';
        update updateProduct;
        BudgetInfoCDController.getFatorProduto(qItem.Product__c, qItem.Id);
    }
    
    @isTest
    static void updateProductTest(){
        Product2 prod = [SELECT Id FROM Product2 LIMIT 1];
        prod.FatorConversaoPortal__c = '1';
        prod.TipoConversaoPortal__c = 'M';
        String prodJSON = JSON.serialize(prod);

        OpportunityLineItem oppLineItem = [SELECT Id FROM OpportunityLineItem LIMIT 1];
        oppLineItem.Comentarios__c = 'test';
        String oppLineItemJSON = JSON.serialize(oppLineItem);
        BudgetInfoCDController.updateProduct(prodJSON, oppLineItemJSON);
    }
}