Git Tests/force-app/main/default/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <externalId>true</externalId>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/Documento__c.field-meta.xml
<CustomField>
    <fullName>Documento__c</fullName>
    <formula>IF(RecordType.Name = &apos;Pessoa física&apos;, CPF__c, CNPJ__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CNPJ/CPF</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/TabelaPrecos__c.field-meta.xml
<CustomField>
    <fullName>TabelaPrecos__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Tabela de preços</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamento__c/CondicaoPagamento__c.object-meta.xml
<CustomObject>
    <label>Condição de pagamento</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condições de pagamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/classes/AccountSelector.cls
public without sharing class AccountSelector {
    
    private static AccountSelector instance;

    public static AccountSelector getInstance(){
        if(instance == null){
            instance = new AccountSelector();
        }
        return instance; 
    }
    
    public Account getAccountByDocument(String documentNumber){
        Map<String, Account> macAccs = getAccountsByDocument(new Set<String>{documentNumber});
        if(!macAccs.isEmpty()){
            return macAccs.get(documentNumber);
        } else {                  
            return null;                                         
        }
    }

    public Map<String, Account> getAccountsByDocument(Set<String> documentNumbers){
        Map<String, Account> result = new Map<String,Account>();
        List<Account> lstAccs = [
            SELECT 
                Id, 
                CNPJ__c,
                Documento__c,
                CondicaoPagamento__c,
                CondicaoPagamento__r.Name,
                Name,
                ExternalId__c,
                TabelaPrecos__c
            FROM Account 
            WHERE Documento__c IN: documentNumbers
        ];
        for(Account acc: lstAccs){
            result.put(acc.Documento__c, acc);
        }
        return result;
    }
    
}