Git Tests/force-app/main/default/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <externalId>true</externalId>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamento__c/CondicaoPagamento__c.object-meta.xml
<CustomObject>
    <label>Condição de pagamento</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condições de pagamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Estoque__c/Estoque__c.object-meta.xml
<CustomObject>
    <label>Estoque</label>
    <nameField>
        <label>Número do estoque</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estoques</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Estoque__c/recordTypes/Estoque.recordType-meta.xml
<RecordType>
    <fullName>Estoque</fullName>
    <active>true</active>
    <description>Identificação do estoque para criação de pedidos e cotações.</description>
    <label>Estoque</label>
</RecordType>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <formula>Account.CNPJ__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CNPJ</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Orcamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/ExternalPortal__c.field-meta.xml
<CustomField>
    <fullName>ExternalPortal__c</fullName>
    <externalId>true</externalId>
    <label>ExternalPortal</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/IdPortal__c.field-meta.xml
<CustomField>
    <fullName>IdPortal__c</fullName>
    <externalId>true</externalId>
    <label>Id Portal</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/TabulacaoN1__c.field-meta.xml
<CustomField>
    <fullName>TabulacaoN1__c</fullName>
    <inlineHelpText>Este campo é um refinamento do valor do campo Status</inlineHelpText>
    <label>Tabulação N1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recusa</fullName>
            </value>
            <value>
                <fullName>Aceite</fullName>
            </value>
            <value>
                <fullName>Improdutiva</fullName>
            </value>
            <value>
                <fullName>Envio Automático</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/IdPortal__c.field-meta.xml
<CustomField>
    <fullName>IdPortal__c</fullName>
    <description>Id do item no Portal de Cotações.</description>
    <externalId>true</externalId>
    <label>Id do Portal</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NÃO IDENTIFICADO</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>IDENTIFICADO</fullName>
            </value>
            <value>
                <fullName>QUALIFICADO</fullName>
            </value>
            <value>
                <fullName>Respondido</fullName>
            </value>
            <value>
                <fullName>Resgatado</fullName>
            </value>
            <value>
                <fullName>Aguardando Integração</fullName>
            </value>
            <value>
                <fullName>Falha na Integração</fullName>
            </value>
            <value>
                <fullName>Não Vinculado</fullName>
            </value>
            <value>
                <fullName>Vinculado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/TabulacaoN1__c.field-meta.xml
<CustomField>
    <fullName>TabulacaoN1__c</fullName>
    <inlineHelpText>Refinamento do valor do campo Status.</inlineHelpText>
    <label>Tabulação N1</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FORA DE MALHA</fullName>
                <label>Fora de malha</label>
            </value>
            <value>
                <fullName>SEM ESTOQUE</fullName>
                <label>Sem estoque</label>
            </value>
            <value>
                <fullName>NÃO TEMOS NESSA APRESENTAÇÃO</fullName>
                <label>Não temos nessa apresentação</label>
            </value>
            <value>
                <fullName>NÃO TEMOS A VALIDADE SOLICITADA</fullName>
                <label>Não temos a validade solicitada</label>
            </value>
            <value>
                <fullName>Não temos a quantidade solicitada</fullName>
            </value>
            <value>
                <fullName>Bloqueio por regionalização</fullName>
            </value>
            <value>
                <fullName>Termolab alto SLA de entrega</fullName>
            </value>
            <value>
                <fullName>Não pertence a minha BU</fullName>
            </value>
            <value>
                <fullName>Cotado</fullName>
            </value>
            <value>
                <fullName>NÃO TEM NO PORTIFÓLIO</fullName>
                <label>Não tem no portifólio</label>
            </value>
            <value>
                <fullName>COM OFERTA</fullName>
                <isActive>false</isActive>
                <label>Com oferta</label>
            </value>
            <value>
                <fullName>NÃO TEMOS A QTDE SOLICITADA</fullName>
                <isActive>false</isActive>
                <label>NÃO TEMOS A QTDE SOLICITADA</label>
            </value>
            <value>
                <fullName>NÃO TRABALHAMOS</fullName>
                <isActive>false</isActive>
                <label>NÃO TRABALHAMOS</label>
            </value>
            <value>
                <fullName>NÃO CONSEGUIMOS ATENDER NO PRAZO SOLICITADO</fullName>
                <isActive>false</isActive>
                <label>Não conseguimos atender no prazo solicitado</label>
            </value>
            <value>
                <fullName>SEM OFERTA</fullName>
                <isActive>false</isActive>
                <label>Sem oferta</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <description>
        Objeto recebido na integração do portal de cotações (class: IntegrationPortalQuoteIN) e
        utilizado para armazenar as requisições de produtos efetuada pelos clientes,
        assim como a resposta efetuada pelos vendedores.
        Sua estrutura a nível de negócio existe de duas formas:
        1. a nível de item, sendo o item entendido como as informações advindas da integração com a requisição do cliente.
        2. a nível de resposta, sendo a resposta entendida como as informações enviadas do vendedor para o cliente como resposta.
        Esse objeto pode ser visualizado a nível de usuário nas telas de orçamento do tipo portal (Opportunity > RecordType > OrcamentoPortal),
        que é o mestre do relacionamento mestre-detalhe contido nesse objeto.
        O item é enviado ao portal como resposta na integração do portal de cotação (class: IntegrationPortalQuoteOUT).
        E também é enviado quando é efetuado vínculo de produto (class: IntegrationPortalVinculoOUT)
    </description>
    <label>Item da Cotação</label>
    <nameField>
        <label>Nome do Item da Cotação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens da Cotação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/IdPortal__c.field-meta.xml
<CustomField>
    <fullName>IdPortal__c</fullName>
    <description>Id do item no Portal de Cotações (hash), não vem da integradora, é criado para cada item dentro do portal.</description>
    <externalId>true</externalId>
    <label>Id do Portal</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <description>relacionamento mestre detalhe, orçamento, cotação, opportunidade referente ao item.</description>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Itens da Cotação</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/ProdutosVinculadosAnteriormente__c.field-meta.xml
<CustomField>
    <fullName>ProdutosVinculadosAnteriormente__c</fullName>
    <description>JSON de produtos que estavam vinculados a mesma requisição (mesmo IdCustomer__c) em outras cotações.</description>
    <label>Produtos Vinculados Anteriormente</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Identificador de condição da resposta, (Responde a pergunta: Em que estapa está a resposta?)</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NÃO IDENTIFICADO</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>IDENTIFICADO</fullName>
            </value>
            <value>
                <fullName>QUALIFICADO</fullName>
            </value>
            <value>
                <fullName>Respondido</fullName>
            </value>
            <value>
                <fullName>Resgatado</fullName>
            </value>
            <value>
                <fullName>Aguardando Integração</fullName>
            </value>
            <value>
                <fullName>Falha na Integração</fullName>
            </value>
            <value>
                <fullName>Não Vinculado</fullName>
                <default>true</default>
                <label>Não Vinculado</label>
            </value>
            <value>
                <fullName>Vinculado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/TabulacaoN1__c.field-meta.xml
<CustomField>
    <fullName>TabulacaoN1__c</fullName>
    <inlineHelpText>Refinamento do valor do campo Status.</inlineHelpText>
    <label>Tabulação N1</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FORA DE MALHA</fullName>
                <label>Fora de malha</label>
            </value>
            <value>
                <fullName>SEM ESTOQUE</fullName>
                <label>Sem estoque</label>
            </value>
            <value>
                <fullName>NÃO TEMOS NESSA APRESENTAÇÃO</fullName>
                <label>Não temos nessa apresentação</label>
            </value>
            <value>
                <fullName>NÃO TEMOS A VALIDADE SOLICITADA</fullName>
                <label>Não temos a validade solicitada</label>
            </value>
            <value>
                <fullName>Não temos a quantidade solicitada</fullName>
            </value>
            <value>
                <fullName>Bloqueio por regionalização</fullName>
            </value>
            <value>
                <fullName>Termolab alto SLA de entrega</fullName>
            </value>
            <value>
                <fullName>Não pertence a minha BU</fullName>
            </value>
            <value>
                <fullName>Cotado</fullName>
            </value>
            <value>
                <fullName>NÃO TEM NO PORTIFÓLIO</fullName>
                <label>Não tem no portifólio</label>
            </value>
            <value>
                <fullName>COM OFERTA</fullName>
                <isActive>false</isActive>
                <label>Com oferta</label>
            </value>
            <value>
                <fullName>NÃO TEMOS A QTDE SOLICITADA</fullName>
                <isActive>false</isActive>
                <label>NÃO TEMOS A QTDE SOLICITADA</label>
            </value>
            <value>
                <fullName>NÃO TRABALHAMOS</fullName>
                <isActive>false</isActive>
                <label>NÃO TRABALHAMOS</label>
            </value>
            <value>
                <fullName>NÃO CONSEGUIMOS ATENDER NO PRAZO SOLICITADO</fullName>
                <isActive>false</isActive>
                <label>Não conseguimos atender no prazo solicitado</label>
            </value>
            <value>
                <fullName>SEM OFERTA</fullName>
                <isActive>false</isActive>
                <label>Sem oferta</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/classes/BudgetHistoricoVinculosControllerTest.cls
@isTest
public class BudgetHistoricoVinculosControllerTest {
    public static final Id RT_ORCAMENTOS_PORTAL_ID = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Orçamento do Portal').getRecordTypeId();

    @TestSetup
    static void makeData(){
        Account acc = TestUtility.createAccount();
        acc.CNPJ__c = '12345678901234';
        insert acc;
        Contact contact = TestUtility.createContact(acc);
        insert contact;
        CondicaoPagamento__c conPay = TestUtility.createPaymentCondition2();
        insert conPay;

        Opportunity opp = TestUtility.createOpportunity(acc, contact, conPay);
        opp.ExternalPortal__c = 'testHistoricoVinculos';
        opp.RecordTypeId = RT_ORCAMENTOS_PORTAL_ID;
        opp.StageName = 'Gerar Pedido';
        insert opp;
        Product2 prod = TestUtility.createProduct();
        prod.ProductCode = '0000364';
        insert prod;
        PricebookEntry pb = [
            SELECT Id 
            FROM PricebookEntry 
            WHERE Product2Id = :prod.Id 
            AND Pricebook2Id = :Test.getStandardPricebookId()
        ];
        Estoque__c estoque = TestUtility.createStock('extEstoque', prod.Id);
        insert estoque;
        OpportunityLineItem oppLineItem = TestUtility.createOpportunityLineItem(opp, prod, pb);
        oppLineItem.Status__c = 'Vinculado';
        oppLineItem.TabulacaoN1__c = 'Cotado';
        insert oppLineItem;
        QuoteItem__c qItem = TestUtility.createQuoteItem(opp);
        qItem.ProdutosVinculadosAnteriormente__c = '[{"vendedor":"","updateAt":"2022-09-17T19:10:55.700Z","tipoConversaoUnidadeMedida":"DIVIDIR","mesa":"","idERP":null,"fatorConversao":1.0,"createdAt":"2022-07-06T17:51:45.373Z","codigoProdutoERP":"0000364","bu":"G"}]';
        qItem.IdPortal__c = 'testHistoricoVinculos';
        insert qItem;
    }

    @IsTest
    static void getHistoricoVinculosTest(){
        Opportunity opp = [SELECT Id FROM Opportunity WHERE ExternalPortal__c = 'testHistoricoVinculos'];
        Test.startTest();
        StandardResponse response = BudgetHistoricoVinculosController.getHistoricoVinculos('testHistoricoVinculos', opp.Id);
        System.assertEquals(false, response.hasError);

        StandardResponse responseError1 = BudgetHistoricoVinculosController.getHistoricoVinculos(null, opp.Id);
        System.assertEquals(true, responseError1.hasError);
        QuoteItem__c qItem = [
            SELECT Id, ProdutosVinculadosAnteriormente__c 
            FROM QuoteItem__c 
            WHERE OpportunityId__c = :opp.Id 
            AND IdPortal__c = 'testHistoricoVinculos'
        ];
        qItem.ProdutosVinculadosAnteriormente__c = '[{{error]';
        update qItem;
        StandardResponse responseError2 = BudgetHistoricoVinculosController.getHistoricoVinculos('testHistoricoVinculos', opp.Id);
        System.assertEquals(true, responseError2.hasError);
        Test.stopTest();

    }
}