Git Tests/force-app/main/default/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <externalId>true</externalId>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/Setorizacao__c.object-meta.xml
<CustomObject>
    <label>Setorização</label>
    <nameField>
        <displayFormat>SET-{000000}</displayFormat>
        <label>Número da setorização</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setorizações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome do cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Setorização</relationshipLabel>
    <relationshipName>Setorizacao</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/DataFinal__c.field-meta.xml
<CustomField>
    <fullName>DataFinal__c</fullName>
    <label>Data final</label>
    <type>Date</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/DataInicial__c.field-meta.xml
<CustomField>
    <fullName>DataInicial__c</fullName>
    <label>Data inicial</label>
    <type>Date</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Gerente__c.field-meta.xml
<CustomField>
    <fullName>Gerente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Gerente externo</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Setor</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VDE</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Setorizacao</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/SetorizacaoHelperTest.cls
@isTest
public with sharing class SetorizacaoHelperTest {

    @TestSetup
    static void makeData(){
        List<Account> listAcc = new List<Account>();
        Account acc = TestUtility.createAccPJ();
        acc.ExternalId__c = '04585497000108';
        listAcc.add(acc);

        Account acc2 = TestUtility.createAccPJ();
        acc2.CNPJ__c = '05411870000177';
        acc2.ExternalId__c = '05411870000177';
        listAcc.add(acc2);

        insert listAcc;

        User us = TestUtility.createUser();
        system.debug(us);
        insert us;

        List<Setorizacao__c> listSetorizacao = new List<Setorizacao__c>();

        Setorizacao__c setValid1 = TestUtility.createSetorizacaoWithValidData(acc, us);
        setValid1.ExternalId__c = '001';
        listSetorizacao.add(setValid1);
        system.debug(setValid1);

        Setorizacao__c setValid2 = TestUtility.createSetorizacaoWithValidData(acc2, us);
        setValid2.ExternalId__c = '002';
        listSetorizacao.add(setValid2);
        system.debug(setValid2);

        Setorizacao__c setInvalid1 = TestUtility.createSetorizacaoWithInvalidData(acc, us);
        setInvalid1.ExternalId__c = '003';
        listSetorizacao.add(setInvalid1);
        system.debug(setInvalid1);

        insert listSetorizacao;
    }

    @isTest
    public static void addAccTeamMemberBySectorizationTest() {

        List<Setorizacao__c> listSetorizacao = [SELECT Id, Conta__c, Vendedor__c, Gerente__c, DataInicial__c, DataFinal__c FROM Setorizacao__c WHERE ExternalId__c != '003'];

        SetorizacaoHelper.addAccTeamMemberBySectorization(listSetorizacao);
    }

    
    @isTest
    public static void upAccTeamMemberBySectorizationTest() {
        Setorizacao__c setValid1 = new Setorizacao__c();
        Setorizacao__c setValid2 = new Setorizacao__c();
        Setorizacao__c setInvalid1 = new Setorizacao__c();


        for (Setorizacao__c setorizacao : [SELECT Id, Conta__c, Vendedor__c, DataInicial__c, DataFinal__c, ExternalId__c FROM Setorizacao__c]) {
            if (setorizacao.ExternalId__c == '001') {
                setValid1 = setorizacao;
            }
            if (setorizacao.ExternalId__c == '002') {
                setValid2 = setorizacao;
            }
            if (setorizacao.ExternalId__c == '003') {
                setInvalid1 = setorizacao;
            }
        }

		setInvalid1.DataInicial__c = Date.Today().addDays(-1);
		setInvalid1.DataFinal__c   = Date.Today().addDays(1);
        
		setValid1.DataInicial__c = Date.Today().addDays(-5);
		setValid1.DataFinal__c   = Date.Today().addDays(-2);

        setValid2.DataFinal__c = null;
        
        List<Setorizacao__c> listSetorizacaoToUpdate = new List<Setorizacao__c>{setValid1, setValid2, setInvalid1};
        
        update listSetorizacaoToUpdate;
    }
    
    @isTest
    public static void delAccTeamMemberBySectorizationTest() {
        Setorizacao__c setValid1 = [SELECT Id, Conta__c, Vendedor__c, DataInicial__c, DataFinal__c FROM Setorizacao__c WHERE ExternalId__c = '001'][0];

        delete setValid1;
    }
    
    @isTest
    public static void SetorizacaoHelperTest() {
        SetorizacaoHelper setHelp = new SetorizacaoHelper();
        System.debug(SetorizacaoHandler.disableTrigger());
        System.debug(SetorizacaoHandler.enableTrigger());
    }
}