Git Tests/force-app/main/default/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <externalId>true</externalId>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/Integracoes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuração  personalizada utilizada para gerir os dados de acessos das integrações</description>
    <label>Integrações</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <inlineHelpText>URL de acesso ao serviço</inlineHelpText>
    <label>EndPoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Método</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Senha</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>Usuário</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CanalEntrada__c.field-meta.xml
<CustomField>
    <fullName>CanalEntrada__c</fullName>
    <label>Canal de entrada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ACSC - Associação Congregação de Santa Catarina</fullName>
            </value>
            <value>
                <fullName>Apoio</fullName>
            </value>
            <value>
                <fullName>Ariba/Amil</fullName>
            </value>
            <value>
                <fullName>Bionexo</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>CONTRATO</fullName>
            </value>
            <value>
                <fullName>E-mail</fullName>
            </value>
            <value>
                <fullName>E-MAIL MARKETING</fullName>
            </value>
            <value>
                <fullName>GERENCIA</fullName>
                <label>GERÊNCIA</label>
            </value>
            <value>
                <fullName>GT Plan</fullName>
            </value>
            <value>
                <fullName>Humma</fullName>
            </value>
            <value>
                <fullName>INPART</fullName>
            </value>
            <value>
                <fullName>Max Cotações</fullName>
            </value>
            <value>
                <fullName>Portal Sintese</fullName>
            </value>
            <value>
                <fullName>Portal GTPLAN</fullName>
            </value>
            <value>
                <fullName>Medical VM</fullName>
            </value>
            <value>
                <fullName>MICROSOFT TEAMS</fullName>
            </value>
            <value>
                <fullName>Movi Tech</fullName>
            </value>
            <value>
                <fullName>MVM RS</fullName>
            </value>
            <value>
                <fullName>NEOGRID</fullName>
            </value>
            <value>
                <fullName>Nimbi</fullName>
            </value>
            <value>
                <fullName>PANFLETO</fullName>
            </value>
            <value>
                <fullName>Paradigma</fullName>
            </value>
            <value>
                <fullName>Plani Max</fullName>
            </value>
            <value>
                <fullName>PORTAL FAEPA</fullName>
            </value>
            <value>
                <fullName>Portal HR</fullName>
            </value>
            <value>
                <fullName>PORTAL MULTICENTRAIS</fullName>
            </value>
            <value>
                <fullName>PORTAL MV SISTEMA</fullName>
            </value>
            <value>
                <fullName>PORTAL SAO MARTINHO</fullName>
            </value>
            <value>
                <fullName>PORTAL SGHCOT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <formula>Account.CNPJ__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CNPJ</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/ExternalPortal__c.field-meta.xml
<CustomField>
    <fullName>ExternalPortal__c</fullName>
    <externalId>true</externalId>
    <label>ExternalPortal</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/IdIntegrator__c.field-meta.xml
<CustomField>
    <fullName>IdIntegrator__c</fullName>
    <externalId>true</externalId>
    <label>Id do Integrador</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/Integradora__c.field-meta.xml
<CustomField>
    <fullName>Integradora__c</fullName>
    <label>Integradora</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <description>
        Objeto recebido na integração do portal de cotações (class: IntegrationPortalQuoteIN) e
        utilizado para armazenar as requisições de produtos efetuada pelos clientes,
        assim como a resposta efetuada pelos vendedores.
        Sua estrutura a nível de negócio existe de duas formas:
        1. a nível de item, sendo o item entendido como as informações advindas da integração com a requisição do cliente.
        2. a nível de resposta, sendo a resposta entendida como as informações enviadas do vendedor para o cliente como resposta.
        Esse objeto pode ser visualizado a nível de usuário nas telas de orçamento do tipo portal (Opportunity > RecordType > OrcamentoPortal),
        que é o mestre do relacionamento mestre-detalhe contido nesse objeto.
        O item é enviado ao portal como resposta na integração do portal de cotação (class: IntegrationPortalQuoteOUT).
        E também é enviado quando é efetuado vínculo de produto (class: IntegrationPortalVinculoOUT)
    </description>
    <label>Item da Cotação</label>
    <nameField>
        <label>Nome do Item da Cotação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens da Cotação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <description>Campo usado para itentificar a categoria do vendedor responsável (advém de setorizacao__c)</description>
    <label>Categoria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/IdCustomer__c.field-meta.xml
<CustomField>
    <fullName>IdCustomer__c</fullName>
    <description>Id do produto cadastrado pelo cliente na integradora, usado para identificar mesmo produto em requisições diferentes, juntamente com o AccountId</description>
    <externalId>true</externalId>
    <label>Id do Cliente</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/IdIntegrator__c.field-meta.xml
<CustomField>
    <fullName>IdIntegrator__c</fullName>
    <description>Id usado para identificar o item advindo da integradora</description>
    <externalId>true</externalId>
    <label>Id do Integrador</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <description>relacionamento mestre detalhe, orçamento, cotação, opportunidade referente ao item.</description>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Itens da Cotação</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>produto vinculado a resposta.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Items da Cotação</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/StatusIntegracaoVinculoProdutos__c.field-meta.xml
<CustomField>
    <fullName>StatusIntegracaoVinculoProdutos__c</fullName>
    <description>Status utilizado para verificar a integridade das integrações dessa resposta na class: IntegrationPortalVinculoOUT</description>
    <label>Status Integração - Vínculo de Produtos</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não Integrado</fullName>
                <default>true</default>
                <label>Não Integrado</label>
            </value>
            <value>
                <fullName>Falha na Integração</fullName>
            </value>
            <value>
                <fullName>Integrado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/VendedorRespondeu__c.field-meta.xml
<CustomField>
    <fullName>VendedorRespondeu__c</fullName>
    <description>
        Em alguns casos o vendedor que responde a cotação não é o responsável primário por dar a resposta.
        Esse campo armazena o usuário que efetuou a resposta do item por último.
    </description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor que respondeu</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ItemOrcamentoRespondido</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/Setorizacao__c.object-meta.xml
<CustomObject>
    <label>Setorização</label>
    <nameField>
        <displayFormat>SET-{000000}</displayFormat>
        <label>Número da setorização</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setorizações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>BU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>G</fullName>
                <label>GENÉRICO</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>MATERIAIS</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>NUTRIÇÃO</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Medctech</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>SPECIALTY</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>AMBOS</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>DIABETES</label>
            </value>
            <value>
                <fullName>Q</fullName>
                <label>ODONTOLOGIA</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <label>EQUIPAMENTO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/User/fields/CodigoUsuario__c.field-meta.xml
<CustomField>
    <fullName>CodigoUsuario__c</fullName>
    <externalId>true</externalId>
    <label>Código do usuário</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/IntegrationPortalVinculoOUT.cls
global without sharing class IntegrationPortalVinculoOUT {

    public static final Integer MAX_ROWS = 100;

    @future(callout=true)
    public static void sendAsync(Set<Id> quoteItemIds) {
        send(quoteItemIds);
    }

    public static StandardResponse send(Set<Id> quoteItemIds) {
        RequestData reqData;
        List<Setorizacao__c> setorizacao;
        List<QuoteItem__c> quoteItems;
        HttpRequest req                     = new HttpRequest();
        HttpResponse resp                   = new HttpResponse();
        StandardResponse response           = new StandardResponse();
        Integracoes__c apiSettings          = Integracoes__c.getValues('InformaticaAtualizarVinculo');
        String method                       = apiSettings.Method__c;
        String endpoint                     = apiSettings.Endpoint__c;
        String authorizationHeader          = 'Basic ' + EncodingUtil.base64Encode(Blob.valueOf(apiSettings.User__c + ':' + apiSettings.Password__c));

        req.setEndpoint(endpoint);
        req.setMethod(method);
        req.setHeader('Authorization', authorizationHeader);
        req.setHeader('Content-Type', 'application/json;charset=UTF-8');

        try {
            
            List<Opportunity> lstOpps = [
                SELECT Id,
                    Account.CNPJ__c,
                    Integradora__c,
                    IdIntegrator__c,
                    ExternalPortal__c,
                    CanalEntrada__c,
                    (
                        SELECT Id,
                            Categoria__c,
                            IdCustomer__c,
                            IdIntegrator__c,
                            OpportunityId__c,
                            Product__r.ProductCode,
                            VendedorRespondeu__r.CodigoUsuario__c,
                            LastModifiedBy.CodigoUsuario__c
                        FROM QuoteItems__r 
                        WHERE (StatusIntegracaoVinculoProdutos__c = 'Não Integrado' OR StatusIntegracaoVinculoProdutos__c = '') AND Id IN: quoteItemIds
                        LIMIT :MAX_ROWS
                    )
                FROM Opportunity 
                WHERE Id IN (SELECT OpportunityId__c FROM QuoteItem__c WHERE (StatusIntegracaoVinculoProdutos__c = 'Não Integrado' OR StatusIntegracaoVinculoProdutos__c = '') AND Id IN: quoteItemIds)
                LIMIT :MAX_ROWS
            ];

                
            Boolean hasError = false;
            String body;

            if(!lstOpps.isEmpty()){

                reqData = new RequestData(lstOpps);
            
                body = JSON.serialize(reqData);
                
                req.setBody(body);
                resp = new Http().send(req);
                
                response.setData('response', resp.getBody());
    
                List<QuoteItem__c> quoteItemToUpdate = new List<QuoteItem__c>();
    
                if(resp.getStatusCode() != 200 && resp.getStatusCode() != 201){
                    
                    hasError = true;
                    for(Opportunity opp: lstOpps){
                        for(QuoteItem__c qItem: opp.QuoteItems__r){
                            quoteItemToUpdate.add(new QuoteItem__c(
                                Id = qItem.Id,
                                StatusIntegracaoVinculoProdutos__c = 'Falha na Integração'
                            ));
                        }
                    }
    
                } else {
                    
                    for(Opportunity opp: lstOpps){
                        for(QuoteItem__c qItem: opp.QuoteItems__r){
                            quoteItemToUpdate.add(new QuoteItem__c(
                                Id = qItem.Id,
                                StatusIntegracaoVinculoProdutos__c = 'Integrado'
                            ));
                        }
                    }
                }
                    
                update quoteItemToUpdate;
    
                if(hasError){
                    response.addError('Falha na integração');
                }
                
                IntegrationUtils.WSLog('Vinculo de Produtos', 'Outbound', body, resp.getBody(), hasError, endpoint, response.code);

            } else {

                IntegrationUtils.WSLog('Vinculo de Produtos', 'Outbound', body, 'Não há vinculos a serem integrados.', hasError, endpoint, response.code);
            }

        } catch (Exception e) {
            response.addError(e);
        }
        return response;
    }
    
	public class RequestData {
		public List<OrcamentosCls> orcamentos { get; set; }

        public RequestData(List<Opportunity> lstOpps){
            this.orcamentos = new List<OrcamentosCls>();
            for(Opportunity opp: lstOpps){
                this.orcamentos.add(new OrcamentosCls(opp));
            }
        }
	}

	public class OrcamentosCls {
		public List<ItemsCls> items { get; set; }
		public String id { get; set; }
		public String integradoraId { get; set; }
		public String integradora { get; set; }
		public CustomerCls cliente { get; set; }

        public OrcamentosCls(Opportunity opp){
            this.id = opp.ExternalPortal__c;
            this.integradoraId = opp.IdIntegrator__c;
            this.integradora = opp.CanalEntrada__c;
            this.cliente = new CustomerCls(opp.Account);

            this.items = new List<ItemsCls>();
            for(QuoteItem__c item: opp.Quoteitems__r){
                this.items.add(new ItemsCls(item));
            }
        }
	}

	public class ItemsCls {
		public String codigoProduto { get; set; }
		public String vendedorRespondeu { get; set; }
		public String codigoProdutoErp { get; set; }
		public String mesa { get; set; }
		public String bu { get; set; }

        public ItemsCls(QuoteItem__c item){
            this.codigoProduto = item.IdCustomer__c;
            this.vendedorRespondeu = item.LastModifiedBy.CodigoUsuario__c;//item.VendedorRespondeu__r.CodigoUsuario__c;
            this.codigoProdutoErp = item.Product__r.ProductCode;
            this.bu = String.isBlank(item.Categoria__c) ? '' : item.Categoria__c;
            this.mesa = '';
        }
	}

	public class CustomerCls {
		public String cnpj { get; set; }

        public CustomerCls(Account acc){
            if(acc != null){
                this.cnpj = acc.CNPJ__c;
            }
        }
	}
}