Git Tests/force-app/main/default/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <externalId>true</externalId>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <externalId>true</externalId>
    <label>CPF</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Contract/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <formula>Account.CNPJ__c</formula>
    <label>CNPJ</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Contract/fields/CodigoContrato__c.field-meta.xml
<CustomField>
    <fullName>CodigoContrato__c</fullName>
    <externalId>true</externalId>
    <label>Código do contrato</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Contract/fields/RetornoIntegracao__c.field-meta.xml
<CustomField>
    <fullName>RetornoIntegracao__c</fullName>
    <label>Retorno Integração</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Contract/fields/TipoRegra__c.field-meta.xml
<CustomField>
    <fullName>TipoRegra__c</fullName>
    <label>Tipo da regra</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>A</fullName>
                <label>Acordo comercial</label>
            </value>
            <value>
                <fullName>O</fullName>
                <label>Operação logística (OL)</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Contract/recordTypes/Contrato.recordType-meta.xml
<RecordType>
    <fullName>Contrato</fullName>
    <active>true</active>
    <description>Tipo de registro para os contratos de operação logística, acordo comercial e preço fixo.</description>
    <label>Contrato</label>
</RecordType>

Git Tests/force-app/main/default/default/objects/Integracoes__c/Integracoes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuração  personalizada utilizada para gerir os dados de acessos das integrações</description>
    <label>Integrações</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <inlineHelpText>URL de acesso ao serviço</inlineHelpText>
    <label>EndPoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Método</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Senha</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>Usuário</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/ItemContrato__c.object-meta.xml
<CustomObject>
    <label>Item de contrato</label>
    <nameField>
        <displayFormat>IT-{00000000}</displayFormat>
        <label>Número do item de contrato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens de contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/fields/CodigoProduto__c.field-meta.xml
<CustomField>
    <fullName>CodigoProduto__c</fullName>
    <formula>NomeProduto__r.ProductCode</formula>
    <label>Código do produto</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/fields/Desconto__c.field-meta.xml
<CustomField>
    <fullName>Desconto__c</fullName>
    <label>Desconto</label>
    <precision>5</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/fields/NomeProduto__c.field-meta.xml
<CustomField>
    <fullName>NomeProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome do produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>ItensContrato</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/fields/NumeroContrato__c.field-meta.xml
<CustomField>
    <fullName>NumeroContrato__c</fullName>
    <label>Número do contrato</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Itens de contrato (Número do contrato)</relationshipLabel>
    <relationshipName>ItensContrato</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/fields/PercentualDescontoBoleto__c.field-meta.xml
<CustomField>
    <fullName>PercentualDescontoBoleto__c</fullName>
    <label>% desconto no boleto</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/fields/PrecoMinimo__c.field-meta.xml
<CustomField>
    <fullName>PrecoMinimo__c</fullName>
    <label>Preço compra</label>
    <precision>12</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/fields/PrecoUnitario__c.field-meta.xml
<CustomField>
    <fullName>PrecoUnitario__c</fullName>
    <label>Preço venda</label>
    <precision>12</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Rascunho</fullName>
                <default>true</default>
                <label>Rascunho</label>
            </value>
            <value>
                <fullName>Em Aprovação</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
            <value>
                <fullName>Expirado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
            <value>
                <fullName>Aguardando integração</fullName>
            </value>
            <value>
                <fullName>Ativo</fullName>
                <isActive>false</isActive>
                <label>Ativo</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/fields/ValidadeLote__c.field-meta.xml
<CustomField>
    <fullName>ValidadeLote__c</fullName>
    <label>Validade do lote</label>
    <type>Date</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/fields/VigenciaFinal__c.field-meta.xml
<CustomField>
    <fullName>VigenciaFinal__c</fullName>
    <label>Vigência final</label>
    <type>Date</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/fields/VigenciaInicial__c.field-meta.xml
<CustomField>
    <fullName>VigenciaInicial__c</fullName>
    <label>Vigência inicial</label>
    <type>Date</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/ProductCodeElfa__c.field-meta.xml
<CustomField>
    <fullName>ProductCodeElfa__c</fullName>
    <externalId>true</externalId>
    <label>Código do produto Elfa</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/IntegrationContractOUT.cls
global without sharing class IntegrationContractOUT {

    global class ContractRequest {
        public String CgcCliente;
        public String TipoRegra;
        public String CodSalesForce;
        public String observacoes;
        public String descricao;
        public String ArquivoOL;
        public List<ContractItensRequest> itens;
        
        public ContractRequest (Contract con, list<ContractItensRequest> listContractItens){
            this.CgcCliente    = con.Account.CNPJ__c != null ? con.Account.CNPJ__c : con.Account.CPF__c;
            this.TipoRegra     = con.TipoRegra__c;
            this.CodSalesForce = con.Id;
            this.observacoes   = con.Description;
            this.descricao     = con.Description;
            this.ArquivoOL     = this.TipoRegra == 'O' ? 'S' : 'N';
            this.itens         = listContractItens;

        }
    }

    global class ContractItensRequest {
        public String produto;
        //public String ProdutoElfa;
        public String VigenciaInicial;
        public String VigenciaFinal;
        public String lote;
        public String validade;
        public String uf;
        public Decimal preco;
        public Decimal PrecoMinimo;
        public Decimal PercDesconto;
        // public Decimal PercentualDescontoBoleto;
        
        public ContractItensRequest (ItemContrato__c contractItem){
            this.produto         = contractItem.CodigoProduto__c; 
            //this.ProdutoElfa     = contractItem.NomeProduto__r.ProductCodeElfa__c; 
            this.VigenciaInicial = contractItem.VigenciaInicial__c == null ? null : getFormattedDate(contractItem.VigenciaInicial__c); 
            this.VigenciaFinal  = contractItem.VigenciaFinal__c == null ? null : getFormattedDate(contractItem.VigenciaFinal__c);
            this.uf              = contractItem.NumeroContrato__r.Account.ShippingState;  
            this.lote            = contractItem.Lote__c; 
            this.PercDesconto    = contractItem.Desconto__c; 
            this.preco           = contractItem.PrecoUnitario__c; 
            this.validade        = contractItem.ValidadeLote__c == null ? null : getFormattedDate(contractItem.ValidadeLote__c); 
            this.PrecoMinimo     = contractItem.PrecoMinimo__c; 
            // this.PercentualDescontoBoleto     = contractItem.PercentualDescontoBoleto__c; // precisamos do nome desse campo na estrutura Json para enviar ao ERP
        }
    }
    public class ResultClass{
        public String result {get;set;}
        public Boolean incluido {get;set;}

    }

    public static void sendContractToERP(Id conId) {
        
        // String tokenERP = Test.isRunningTest() ? 'tokenERP' : IntegrationUtils.getERPAccessToken();       

        Integracoes__c intCustomerApi = Integracoes__c.getValues('ElfaContractAPI');
        
        String method   = intCustomerApi.Method__c;
        String endpoint = intCustomerApi.Endpoint__c;
        String username = intCustomerApi.User__c;
        String password = intCustomerApi.Password__c;
        
        HttpRequest req = new HttpRequest();
        req.setEndpoint(endpoint);
        // req.setHeader('Username', username);
        // req.setHeader('Password', password);
        req.setHeader('Authorization', 'Basic ' + EncodingUtil.base64Encode(Blob.valueOf(username + ':' + password)));
        req.setHeader('Content-Type', 'application/json');
        req.setMethod(method);
        req.setTimeout(120000);

        System.debug(EncodingUtil.base64Encode(Blob.valueOf(username + ':' + password)));

        List<ContractItensRequest> listContractItemReq = new List<ContractItensRequest>();

        for (ItemContrato__c contractItem : [SELECT Id, NumeroContrato__r.Account.ShippingState, CodigoProduto__c, VigenciaInicial__c, VigenciaFinal__c, Lote__c, ValidadeLote__c, PrecoUnitario__c, 
                                             PrecoMinimo__c, Desconto__c, Status__c, PercentualDescontoBoleto__c FROM ItemContrato__c WHERE NumeroContrato__c =: conId]) {
            listContractItemReq.add(new ContractItensRequest(contractItem));
        }

        system.debug('listContractItemReq: ' + listContractItemReq);

        ContractRequest contractReq;

        for (Contract cont : [SELECT Id, AccountId, Account.CNPJ__c, Account.CPF__c, TipoRegra__c, CodigoContrato__c, Description FROM Contract WHERE Id =: conId]) {
            contractReq = new ContractRequest(cont, listContractItemReq);
        }

        system.debug('contractReq: ' + contractReq);

        String body;
        body = Json.serialize(contractReq);
        System.debug('Body: '+body);

        String resultString = '';
        HttpResponse resp = new HttpResponse();
        try {
            req.setBody(body);
            resp = new Http().send(req);
            
            system.debug(resp);
            system.debug(resp.getStatusCode());
            
            resultString = resp.getBody();
            system.debug('resp'+resultString);            
            
            if(resp.getStatusCode() == 200 || resp.getStatusCode() == 201){        
                resultString = resp.getBody();
                IntegrationUtils.WSLog('Contrato', 'Outbound', body, resultString, false);
            } else {
                resultString = resp.getBody();
                IntegrationUtils.WSLog('Contrato', 'Outbound', body, resultString, true);
            }

            ResultClass resClass = (ResultClass)JSON.deserialize(resultString, ResultClass.class);
            
            ContractHandler.disableTrigger();
            update new Contract(Id = conId, RetornoIntegracao__c = resClass.result.subString(0,resClass.result.length() > 255 ? 255 : resClass.result.length()));
            ContractHandler.enableTrigger();

        } catch (Exception e) {
            resultString = e.getMessage();
        }
    }

    // method to get ERP's date format
    public static String getFormattedDate(Date data) {
        return String.valueOf(data.year()) + (data.month() <= 9 ? '0'+String.valueOf(data.month()) : String.valueOf(data.month())) + (data.day() <= 9 ? '0'+String.valueOf(data.day()) : String.valueOf(data.day()));
    }


}