Git Tests/force-app/main/default/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <externalId>true</externalId>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/Integracoes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuração  personalizada utilizada para gerir os dados de acessos das integrações</description>
    <label>Integrações</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <inlineHelpText>URL de acesso ao serviço</inlineHelpText>
    <label>EndPoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Método</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Senha</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>Usuário</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <formula>Account.CNPJ__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CNPJ</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Orcamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/ExternalPortal__c.field-meta.xml
<CustomField>
    <fullName>ExternalPortal__c</fullName>
    <externalId>true</externalId>
    <label>ExternalPortal</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/IdIntegrator__c.field-meta.xml
<CustomField>
    <fullName>IdIntegrator__c</fullName>
    <externalId>true</externalId>
    <label>Id do Integrador</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/IdPortal__c.field-meta.xml
<CustomField>
    <fullName>IdPortal__c</fullName>
    <externalId>true</externalId>
    <label>Id Portal</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <inlineHelpText>Vendedor / Vendedor Externo</inlineHelpText>
    <label>Representante VDE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/CategoriaComercial__c.field-meta.xml
<CustomField>
    <fullName>CategoriaComercial__c</fullName>
    <formula>TEXT(PricebookEntry.Product2.CategoriaComercial__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Categoria comercial</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Chave Externa</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/IdCustomer__c.field-meta.xml
<CustomField>
    <fullName>IdCustomer__c</fullName>
    <externalId>true</externalId>
    <label>Id do Cliente</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/IdIntegrator__c.field-meta.xml
<CustomField>
    <fullName>IdIntegrator__c</fullName>
    <externalId>true</externalId>
    <label>Id do Integrador</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/IdPortal__c.field-meta.xml
<CustomField>
    <fullName>IdPortal__c</fullName>
    <description>Id do item no Portal de Cotações.</description>
    <externalId>true</externalId>
    <label>Id do Portal</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/ProgramacaoEntrega__c.field-meta.xml
<CustomField>
    <fullName>ProgramacaoEntrega__c</fullName>
    <label>Programacao Entrega</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ProdutoOrcamento</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityTeamMember/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Centro de distribuição</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/CategoriaComercial__c.field-meta.xml
<CustomField>
    <fullName>CategoriaComercial__c</fullName>
    <label>Categoria comercial</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>G</fullName>
                <label>GENÉRICO</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>MATERIAIS</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>NUTRIÇÃO</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Medctech</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>REFERÊNCIA</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>AMBOS</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>DIABETES</label>
            </value>
            <value>
                <fullName>Q</fullName>
                <label>ODONTOLOGIA</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Especialidade</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <label>EQUIPAMENTO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do produto</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <description>
        Objeto recebido na integração do portal de cotações (class: IntegrationPortalQuoteIN) e
        utilizado para armazenar as requisições de produtos efetuada pelos clientes,
        assim como a resposta efetuada pelos vendedores.
        Sua estrutura a nível de negócio existe de duas formas:
        1. a nível de item, sendo o item entendido como as informações advindas da integração com a requisição do cliente.
        2. a nível de resposta, sendo a resposta entendida como as informações enviadas do vendedor para o cliente como resposta.
        Esse objeto pode ser visualizado a nível de usuário nas telas de orçamento do tipo portal (Opportunity > RecordType > OrcamentoPortal),
        que é o mestre do relacionamento mestre-detalhe contido nesse objeto.
        O item é enviado ao portal como resposta na integração do portal de cotação (class: IntegrationPortalQuoteOUT).
        E também é enviado quando é efetuado vínculo de produto (class: IntegrationPortalVinculoOUT)
    </description>
    <label>Item da Cotação</label>
    <nameField>
        <label>Nome do Item da Cotação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens da Cotação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <description>Cnpj do centro de distribuição vinculado</description>
    <label>CNPJ do CD</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>OpportunityId__r.ExternalPortal__c + _ + IdPotal__c + _ + Vendedor__c + _ + Categoria__c</description>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Chave Externa</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/IdCustomer__c.field-meta.xml
<CustomField>
    <fullName>IdCustomer__c</fullName>
    <description>Id do produto cadastrado pelo cliente na integradora, usado para identificar mesmo produto em requisições diferentes, juntamente com o AccountId</description>
    <externalId>true</externalId>
    <label>Id do Cliente</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/IdERP__c.field-meta.xml
<CustomField>
    <fullName>IdERP__c</fullName>
    <description>Código do produto no Protheus. (Campo não utilizado 25/09/22)</description>
    <externalId>true</externalId>
    <label>Id do ERP</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/IdIntegrator__c.field-meta.xml
<CustomField>
    <fullName>IdIntegrator__c</fullName>
    <description>Id usado para identificar o item advindo da integradora</description>
    <externalId>true</externalId>
    <label>Id do Integrador</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/IdPortal__c.field-meta.xml
<CustomField>
    <fullName>IdPortal__c</fullName>
    <description>Id do item no Portal de Cotações (hash), não vem da integradora, é criado para cada item dentro do portal.</description>
    <externalId>true</externalId>
    <label>Id do Portal</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/OpportunityLineItem__c.field-meta.xml
<CustomField>
    <fullName>OpportunityLineItem__c</fullName>
    <description>
        Quando existe oferta para o QuoteItem__c em questão é criado um OpportunityLineItem com as informações do QuoteItem__c
        Esse item que foi criado fica relacionado por meio desse campo.
    </description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto de oportunidade</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Items da Cotação</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/ProgramacaoEntrega__c.field-meta.xml
<CustomField>
    <fullName>ProgramacaoEntrega__c</fullName>
    <description>Informações de entrega requeridas pelo cliente.</description>
    <label>Programacao Entrega</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>Quantidade de produtos requerida pelo cliente em sua deteminada unidade de medida</description>
    <label>Quantidade</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <description>Preço elfa para cada unidade ofertada</description>
    <label>Valor Unitário</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <description>
        Vendedor responsável por dar a resposta, advem da setorização, relacionado a VendedorSuporte__c
        Também chamado de VDS ou VDI
    </description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ItensOrcamentosPortal</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/User/fields/CodigoUsuario__c.field-meta.xml
<CustomField>
    <fullName>CodigoUsuario__c</fullName>
    <externalId>true</externalId>
    <label>Código do usuário</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/IntegrationPortalOrderINTest.cls
@isTest
global class IntegrationPortalOrderINTest {

    @TestSetup
    static void createData(){

        User user1 = new User(Id = UserInfo.getUserid());
        user1.codigoUsuario__c = 'POI_TEST_user1';
        try{
            update user1;
        }catch(Exception ex){}
        
        System.runAs(user1){

            CondicaoPagamento__c conditionMakeData = TestUtility.createConditionPayment();
            insert conditionMakeData;
    
            Account acc = TestUtility.createAccount();
            acc.CNPJ__c = '00012698000246';
            acc.CondicaoPagamento__c = conditionMakeData.id;
            insert acc;
            Product2 product = TestUtility.createProduct();
            product.ProductCode ='0001920';
            product.ExternalId__c = 'POI_TEST_180507232';
            product.CategoriaComercial__c = 'M';
            insert product;
            CondicaoPagamento__c condPag = TestUtility.createConditionPayment();
            condPag.ExternalId__c = '003';
            insert condPag;

            Opportunity opportunity = TestUtility.createOpportunity(new User(Id=UserInfo.getUserId()));
            opportunity.AccountId = acc.id;
            opportunity.CloseDate = Date.today().addDays(-1);
            opportunity.StageName = 'Em digitação';
            opportunity.IdPortal__c = 'POI_TEST_180507232';
            opportunity.ExternalPortal__c = 'POI_TEST_180507232';
            opportunity.IdIntegrator__c = '001';
            opportunity.CondicaoPagamento__c = condPag.Id;
            insert opportunity;
    
            OpportunityTeamMember members = new OpportunityTeamMember(
                                        TeamMemberRole = 'Sales Rep',
                                        UserId = user1.id, 
                                        OpportunityId = opportunity.Id,
                                        OpportunityAccessLevel = 'EDIT'
                                    );
            insert members;
          
            
            PricebookEntry pbEntry = [SELECT ID, IsActive FROM PricebookEntry WHERE Product2Id =: product.Id LIMIT 1];
            pbEntry.IsActive = true;
            update pbEntry;
    
            OpportunityLineItem oppLineItem = TestUtility.createOpportunityLineItem(opportunity, product, pbEntry);
            oppLineItem.Vendedor__r = new User(CodigoUsuario__c = 'POI_TEST_user1');
            insert oppLineItem;    
    
            Integracoes__c integration =  new Integracoes__c(
                Name        = 'InformaticaGetMalhaPortal',
                Method__c   = 'POST',
                Endpoint__c = 'https://na1.ai.dm-us.informaticacloud.com/active-bpel/rt/P-SFDC-Malha-Fiscal',
                User__c     = 'cloud.dev@grupoelfa.com.br',
                Password__c = 'Elf@Cloud'
            );
            insert integration;
    
            QuoteItem__c quoteItem1 = TestUtility.createQuoteItem(opportunity.IdIntegrator__c, user1.CodigoUsuario__c);
            quoteItem1.IdPortal__c = '001quoteItem';
            quoteItem1.IdCustomer__c = '001quoteItem';
            quoteItem1.IdERP__c = '001quoteItem';
            quoteItem1.ExternalId__c = '001quoteItem';
            quoteItem1.CNPJCD__c = '79231541000180';
            quoteItem1.ProgramacaoEntrega__c = '[{"quantidade":"8000","data":"16/02/2022"},{"quantidade":"9000","data":"03/03/2022"}]';
            quoteItem1.Quantity__c = 1;
            quoteItem1.UnitPrice__c = 1;
            quoteItem1.OpportunityLineItem__c = oppLineItem.Id;
    
            insert quoteItem1;
        }
    }

    @isTest
    public static void test_one_upsertOrder_OrderItem_success(){    
        
        Opportunity opp = [
            SELECT Id, CanalEntrada__c, IdIntegrator__c, ExternalPortal__c, Account.CNPJ__c, CondicaoPagamento__r.ExternalId__c,
            (SELECT Id, IdPortal__c, CNPJCD__c, OpportunityLineItem__r.Quantity  FROM QuoteItems__r) 
            FROM Opportunity LIMIT 1
        ];
    
        Test.startTest();

            RestRequest req = new RestRequest();
            RestResponse res = new RestResponse();
            req.requestUri = 'https://test.salesforce.com/services/apexrest/upsertPortalOrder/v1/';
            req.httpMethod = 'POST';

            String itensJSON = buildItemObject(
                opp.QuoteItems__r[0].IdPortal__c,
                opp.QuoteItems__r[0].CNPJCD__c, 
                opp.QuoteItems__r[0].Id, 
                opp.QuoteItems__r[0].OpportunityLineItem__r.Quantity
            );

            String orderDataJSON = buildOrderObject(
                opp.CanalEntrada__c, 
                opp.IdIntegrator__c, 
                opp.ExternalPortal__c, 
                opp.Account.CNPJ__c, 
                opp.CondicaoPagamento__r.ExternalId__c, 
                itensJSON
            );

            req.requestBody = Blob.valueOf(orderDataJSON);
               
            RestContext.request = req;
            RestContext.response = res;
        
            //Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(true, 'Malha'));
            IntegrationPortalOrderIN.getOpportunity('POI_TEST_180507232');
            IntegrationPortalOrderIN intPortalOrder = new IntegrationPortalOrderIN();
            IntegrationPortalOrderIN.upsertOrder();

        Test.stopTest();
    }

    @isTest
    public static void test_two_upsertOrder_OrderItem_failItem(){    
        
        Opportunity opp = [
            SELECT Id, CanalEntrada__c, IdIntegrator__c, ExternalPortal__c, Account.CNPJ__c, CondicaoPagamento__r.ExternalId__c,
            (SELECT Id, IdPortal__c, CNPJCD__c, OpportunityLineItem__r.Quantity  FROM QuoteItems__r) 
            FROM Opportunity LIMIT 1
        ];
    
        Test.startTest();

            RestRequest req = new RestRequest();
            RestResponse res = new RestResponse();
            req.requestUri = 'https://test.salesforce.com/services/apexrest/upsertPortalOrder/v1/';
            req.httpMethod = 'POST';

            String itensJSON = '{'+
            '    "idPortal": "'+opp.QuoteItems__r[0].IdPortal__c+'",'+
            '    "cnpjCd": "'+opp.QuoteItems__r[0].CNPJCD__c+'",'+
            '    "idItemConfirmado": "",'+
            '    "idSalesforce": "'+opp.QuoteItems__r[0].Id+'",'+
            '    "quantidade": "'+opp.QuoteItems__r[0].OpportunityLineItem__r.Quantity+'",'+
            '    "campoExtra": [';
            for(Integer i = 0; i<300; i++){
                itensJSON += 
                '        {'+
                '            "nome": "Valor_Unitario",'+
                '            "valor": "0.9602"'+
                '        },';
            }
            itensJSON += 
            '        {'+
            '            "nome": "Id_Unidade_Medida",'+
            '            "valor": "29"'+
            '        }'+
            '    ],'+
            '    "programacaoEntrega": ['+
            '        {'+
            '            "data": "12/08/2022",'+
            '            "quantidade": "160"'+
            '        }'+
            '    ]'+
            '}';

            String orderDataJSON = buildOrderObject(
                opp.CanalEntrada__c, 
                opp.IdIntegrator__c, 
                opp.ExternalPortal__c, 
                opp.Account.CNPJ__c, 
                opp.CondicaoPagamento__r.ExternalId__c, 
                itensJSON
            );

            req.requestBody = Blob.valueOf(orderDataJSON);
               
            RestContext.request = req;
            RestContext.response = res;
        
            //Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(true, 'Malha'));
            IntegrationPortalOrderIN.getOpportunity('POI_TEST_180507232');
            IntegrationPortalOrderIN intPortalOrder = new IntegrationPortalOrderIN();
            IntegrationPortalOrderIN.upsertOrder();

        Test.stopTest();
    }

    public static String buildItemObject(List<String> idPortal, List<String> cnpjCd, List<String> idSalesforce, List<Decimal> quantity, Integer size){
        String result = '';
        for(Integer i=0; i< size;i++){
            result += 
            '{'+
            '    "idPortal": "'+idPortal[i]+'",'+
            '    "cnpjCd": "'+cnpjCd[i]+'",'+
            '    "idItemConfirmado": "",'+
            '    "idSalesforce": "'+idSalesforce[i]+'",'+
            '    "quantidade": "'+quantity[i]+'",'+
            '    "campoExtra": ['+
            '        {'+
            '            "nome": "Valor_Unitario",'+
            '            "valor": "0.9602"'+
            '        },'+
            '        {'+
            '            "nome": "Id_Unidade_Medida",'+
            '            "valor": "29"'+
            '        }'+
            '    ],'+
            '    "programacaoEntrega": ['+
            '        {'+
            '            "data": "12/08/2022",'+
            '            "quantidade": "160"'+
            '        }'+
            '    ]'+
            '}';
            if(size-1 > i) result +=',';
        }
        return result;
    }
    public static String buildItemObject(String idPortal, String cnpjCd, String idSalesforce, Decimal quantity){
        return buildItemObject(
            new List<String>{idPortal},
            new List<String>{cnpjCd},
            new List<String>{idSalesforce},
            new List<Decimal>{quantity},
            1
        );
    }

    public static String buildOrderObject(String integradora, String integradoraId, String idPortal, String cnpj, String condicaoPagamento, String itens){
        return 
        '{'+
        '    "integradora": "'+integradora+'",'+
        '    "integradoraId": "'+integradoraId+'",'+
        '    "idPortal": "'+idPortal+'",'+
        '    "cliente": {'+
        '        "cnpj": "'+cnpj+'"'+
        '    },'+
        '    "nomeContato": "Claudio  De Andrade Avelino",'+
        '    "condicaoPagamento": {'+
        '        "id": "'+condicaoPagamento+'",'+
        '        "nome": "30 D"'+
        '    },'+
        '    "observacao": "-",'+
        '    "termosCondicoes": "---",'+
        '    "enderecoEntrega": "Lad Dos Guararapes, 263 - Cosme Velho,RIO DE JANEIRO,RJ",'+
        '    "campoExtra": [],'+
        '    "itensConfirmados": ['+itens+']'+
        '}';
    }
}