Git Tests/force-app/main/default/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <externalId>true</externalId>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/TipoFrete__c.field-meta.xml
<CustomField>
    <fullName>TipoFrete__c</fullName>
    <label>Tipo do frete</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/Integracoes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuração  personalizada utilizada para gerir os dados de acessos das integrações</description>
    <label>Integrações</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <inlineHelpText>URL de acesso ao serviço</inlineHelpText>
    <label>EndPoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Método</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Senha</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>Usuário</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <formula>Account.CNPJ__c</formula>
    <label>CNPJ</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CodigoIntegradora__c.field-meta.xml
<CustomField>
    <fullName>CodigoIntegradora__c</fullName>
    <externalId>true</externalId>
    <label>Código integradora</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/Inconsistencias__c.field-meta.xml
<CustomField>
    <fullName>Inconsistencias__c</fullName>
    <label>Inconsistências</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/Laboratorio__c.field-meta.xml
<CustomField>
    <fullName>Laboratorio__c</fullName>
    <label>Laboratório</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/RejeicaoProcesso__c.field-meta.xml
<CustomField>
    <fullName>RejeicaoProcesso__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Rejeição do processo?</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/SolicitacaoAprovada__c.field-meta.xml
<CustomField>
    <fullName>SolicitacaoAprovada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Solicitação Aprovada</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/StatusAprovacao__c.field-meta.xml
<CustomField>
    <fullName>StatusAprovacao__c</fullName>
    <label>Status de aprovação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>StatusAprovacao</valueSetName>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/TipoFrete__c.field-meta.xml
<CustomField>
    <fullName>TipoFrete__c</fullName>
    <label>Tipo do frete</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
            <value>
                <fullName>CLIENTE RETIRA</fullName>
            </value>
            <value>
                <fullName>Por conta de terceiros</fullName>
            </value>
            <value>
                <fullName>Por conta remetente</fullName>
            </value>
            <value>
                <fullName>Por conta destinatário</fullName>
            </value>
            <value>
                <fullName>Sem frete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/TipoOperacao__c.field-meta.xml
<CustomField>
    <fullName>TipoOperacao__c</fullName>
    <label>Tipo de operação</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/Laboratorio__c.field-meta.xml
<CustomField>
    <fullName>Laboratorio__c</fullName>
    <label>Laboratório</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/Lote__c.field-meta.xml
<CustomField>
    <fullName>Lote__c</fullName>
    <label>Lote</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/PrecoTotal__c.field-meta.xml
<CustomField>
    <fullName>PrecoTotal__c</fullName>
    <label>Preço total</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/TipoIntegradora__c.field-meta.xml
<CustomField>
    <fullName>TipoIntegradora__c</fullName>
    <label>Tipo integradora</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/TipoOperacao__c.field-meta.xml
<CustomField>
    <fullName>TipoOperacao__c</fullName>
    <label>Tipo da operação</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/PedidoIntegradora__c/PedidoIntegradora__c.object-meta.xml
<CustomObject>
    <label>Pedido de integradora</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Nome de Pedido de integradora</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Pedidos de integradora</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/PedidoIntegradora__c/fields/CNPJCliente__c.field-meta.xml
<CustomField>
    <fullName>CNPJCliente__c</fullName>
    <label>CNPJ do cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/PedidoIntegradora__c/fields/CodigoIntegradora__c.field-meta.xml
<CustomField>
    <fullName>CodigoIntegradora__c</fullName>
    <externalId>true</externalId>
    <label>Código integradora</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/PedidoIntegradora__c/fields/Inconsistencias__c.field-meta.xml
<CustomField>
    <fullName>Inconsistencias__c</fullName>
    <label>Inconsistências</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/PedidoIntegradora__c/fields/Laboratorio__c.field-meta.xml
<CustomField>
    <fullName>Laboratorio__c</fullName>
    <label>Laboratório</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/PedidoIntegradora__c/fields/Pedido__c.field-meta.xml
<CustomField>
    <fullName>Pedido__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Pedidos de integradora</relationshipLabel>
    <relationshipName>PedidosIntegradora</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/PedidoIntegradora__c/fields/RejeicaoProcesso__c.field-meta.xml
<CustomField>
    <fullName>RejeicaoProcesso__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Rejeição processo</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/PedidoIntegradora__c/fields/SolicitacaoAprovada__c.field-meta.xml
<CustomField>
    <fullName>SolicitacaoAprovada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Solicitação aprovada</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/PedidoIntegradora__c/fields/StatusAprovacao__c.field-meta.xml
<CustomField>
    <fullName>StatusAprovacao__c</fullName>
    <label>Status de aprovação</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Reprovado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/PedidoIntegradora__c/fields/TipoIntegradora__c.field-meta.xml
<CustomField>
    <fullName>TipoIntegradora__c</fullName>
    <label>Tipo integradora</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/globalValueSets/StatusAprovacao.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Em digitação</fullName>
    </customValue>
    <customValue>
        <fullName>Em aprovação</fullName>
    </customValue>
    <customValue>
        <fullName>Aprovado</fullName>
    </customValue>
    <customValue>
        <fullName>Cancelado</fullName>
    </customValue>
    <description>Valores de status para os processos de aprovação de orçamento e pedido.</description>
    <masterLabel>Status de aprovação</masterLabel>
</GlobalValueSet>

Git Tests/force-app/main/default/default/classes/PedidoIntegradoraHelperTest.cls
@isTest
public with sharing class PedidoIntegradoraHelperTest {
    @TestSetup
    static void makeData(){
        Account acc = TestUtility.createAccPJ();
        insert acc;

        Product2 prod = TestUtility.createProduct();
        insert prod;

        List<Order> listOrder = new List<Order>();
        Order ord1 = TestUtility.createOrder(acc);
        ord1.TipoFrete__c = 'CIF';
        ord1.CodigoIntegradora__c = '1234';
        listOrder.add(ord1);
        
        Order ord2 = TestUtility.createOrder(acc);
        ord2.CodigoIntegradora__c = '12345';
        listOrder.add(ord2);

        insert listOrder;

        Id pricebookEntryId = [SELECT Id FROM PricebookEntry WHERE Product2Id =: prod.Id][0].Id;

        List<OrderItem> listOrderItem = new List<OrderItem>();
        OrderItem orderItem1 = new OrderItem();
        orderItem1.orderId          = ord1.Id;
        orderItem1.Product2Id       = prod.Id;
        orderItem1.pricebookEntryId = pricebookEntryId;
        orderItem1.Quantity         = 5;
        orderItem1.UnitPrice        = 50;
        orderItem1.PrecoTotal__c    = 50;
        orderItem1.Lote__c          = '10';
        orderItem1.TipoOperacao__c  = '11';
        orderItem1.Laboratorio__c   = 'FAB';
        orderItem1.cnpjCD__c        = '52202744000192';
        listOrderItem.add(orderItem1);
        
        OrderItem orderItem2 = new OrderItem();
        orderItem2.orderId          = ord2.Id;
        orderItem2.Product2Id       = prod.Id;
        orderItem2.pricebookEntryId = pricebookEntryId;
        orderItem2.Quantity         = 5;
        orderItem2.UnitPrice        = 50;
        orderItem2.PrecoTotal__c    = 50;
        orderItem2.Lote__c          = '10';
        orderItem2.TipoOperacao__c  = '11';
        orderItem2.Laboratorio__c   = 'FAB';
        orderItem2.cnpjCD__c        = '52202744000192';
        listOrderItem.add(orderItem2);

        insert listOrderItem;

        PedidoIntegradora__c pedIntegradora = new PedidoIntegradora__c();
        pedIntegradora.CodigoIntegradora__c = '1234';
        pedIntegradora.CNPJCliente__c       = acc.CNPJ__c;
        pedIntegradora.TipoIntegradora__c   = '20';
        pedIntegradora.Laboratorio__c       = 'FAB';
        pedIntegradora.Inconsistencias__c   = null;
        pedIntegradora.StatusAprovacao__c   = 'Aprovado';
        pedIntegradora.Pedido__c            = ord1.Id;

        insert pedIntegradora;

        Integracoes__c integration =  new Integracoes__c(
			Name        = 'ElfaLaboratoryOrderAPI',
			Method__c   = 'POST',
			Endpoint__c = 'https://na1.ai.dm-us.informaticacloud.com/active-bpel/rt/P-SFDC-Reprocessamento-Pedido',
			User__c     = 'cloud.dev@grupoelfa.com.br',
			Password__c = 'Elf@Cloud'
		);
        insert integration;
       
    }

    @isTest
    public static void createPedidoIntegradoraTest() {
        PedidoIntegradora__c prod = new PedidoIntegradora__c(
            CodigoIntegradora__c = '12345'
        );
        insert prod;

        prod.StatusAprovacao__c = 'Aprovado';
        
        update prod;

        prod.SolicitacaoAprovada__c = true;
        prod.RejeicaoProcesso__c = true;

        update prod;

        PedidoIntegradoraHelper.FlowInputs fInputs = new PedidoIntegradoraHelper.FlowInputs();
        fInputs.labId = prod.id;
        fInputs.isApprove = true;
        
        PedidoIntegradoraHelper.ApproveRejectLaboratoryOrderThisUser(new List<PedidoIntegradoraHelper.FlowInputs>{fInputs});
    }
    
    @isTest
    public static void PedidoIntegradoraTest() {
        System.debug(PedidoIntegradoraHandler.disableTrigger());
        System.debug(PedidoIntegradoraHandler.enableTrigger());
        System.assertEquals(false, PedidoIntegradoraHandler.disableTrigger());
        System.assertEquals(true, PedidoIntegradoraHandler.enableTrigger());
    }
}