Git Tests/force-app/main/default/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <externalId>true</externalId>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/Documento__c.field-meta.xml
<CustomField>
    <fullName>Documento__c</fullName>
    <formula>IF(RecordType.Name = &apos;Pessoa física&apos;, CPF__c, CNPJ__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CNPJ/CPF</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/CondicaoPagamentoPorCD__c.object-meta.xml
<CustomObject>
    <label>Condição de pagamento por CD</label>
    <nameField>
        <label>Nome de Condição de pagamento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condições de pagamentos por CD</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/CloseDate__c.field-meta.xml
<CustomField>
    <fullName>CloseDate__c</fullName>
    <label>Data de validade</label>
    <type>Date</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Condição de Pagamento CD</relationshipLabel>
    <relationshipName>CondicoesPagamento</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/FretePicklist__c.field-meta.xml
<CustomField>
    <fullName>FretePicklist__c</fullName>
    <label>Tipo de Frete</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CIF</fullName>
                <default>true</default>
                <label>CIF</label>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/Integradora__c.field-meta.xml
<CustomField>
    <fullName>Integradora__c</fullName>
    <label>Integradora</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bionexo</fullName>
            </value>
            <value>
                <fullName>Apoio</fullName>
            </value>
            <value>
                <fullName>Sintese</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/MinimumBilling__c.field-meta.xml
<CustomField>
    <fullName>MinimumBilling__c</fullName>
    <label>Faturamento Mínimo</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/ObservacoesLongText__c.field-meta.xml
<CustomField>
    <fullName>ObservacoesLongText__c</fullName>
    <label>Observações</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/Orcamento__c.field-meta.xml
<CustomField>
    <fullName>Orcamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Orçamento</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Condições de pagamentos por CD</relationshipLabel>
    <relationshipName>Condicespagamentospor_CD</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/PrazoEntrega__c.field-meta.xml
<CustomField>
    <fullName>PrazoEntrega__c</fullName>
    <label>Prazo de Entrega</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/PrazoValidade__c.field-meta.xml
<CustomField>
    <fullName>PrazoValidade__c</fullName>
    <label>Prazo de validade (em dias)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Fornecedor__c/Fornecedor__c.object-meta.xml
<CustomObject>
    <label>Fornecedor</label>
    <nameField>
        <label>Nome do fornecedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fornecedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Fornecedor__c/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Fornecedor__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do fornecedor</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CanalEntrada__c.field-meta.xml
<CustomField>
    <fullName>CanalEntrada__c</fullName>
    <label>Canal de entrada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ACSC - Associação Congregação de Santa Catarina</fullName>
            </value>
            <value>
                <fullName>Apoio</fullName>
            </value>
            <value>
                <fullName>Ariba/Amil</fullName>
            </value>
            <value>
                <fullName>Bionexo</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>CONTRATO</fullName>
            </value>
            <value>
                <fullName>E-mail</fullName>
            </value>
            <value>
                <fullName>E-MAIL MARKETING</fullName>
            </value>
            <value>
                <fullName>GERENCIA</fullName>
                <label>GERÊNCIA</label>
            </value>
            <value>
                <fullName>GT Plan</fullName>
            </value>
            <value>
                <fullName>Humma</fullName>
            </value>
            <value>
                <fullName>INPART</fullName>
            </value>
            <value>
                <fullName>Max Cotações</fullName>
            </value>
            <value>
                <fullName>Portal Sintese</fullName>
            </value>
            <value>
                <fullName>Portal GTPLAN</fullName>
            </value>
            <value>
                <fullName>Medical VM</fullName>
            </value>
            <value>
                <fullName>MICROSOFT TEAMS</fullName>
            </value>
            <value>
                <fullName>Movi Tech</fullName>
            </value>
            <value>
                <fullName>MVM RS</fullName>
            </value>
            <value>
                <fullName>NEOGRID</fullName>
            </value>
            <value>
                <fullName>Nimbi</fullName>
            </value>
            <value>
                <fullName>PANFLETO</fullName>
            </value>
            <value>
                <fullName>Paradigma</fullName>
            </value>
            <value>
                <fullName>Plani Max</fullName>
            </value>
            <value>
                <fullName>PORTAL FAEPA</fullName>
            </value>
            <value>
                <fullName>Portal HR</fullName>
            </value>
            <value>
                <fullName>PORTAL MULTICENTRAIS</fullName>
            </value>
            <value>
                <fullName>PORTAL MV SISTEMA</fullName>
            </value>
            <value>
                <fullName>PORTAL SAO MARTINHO</fullName>
            </value>
            <value>
                <fullName>PORTAL SGHCOT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CDsBloqueado__c.field-meta.xml
<CustomField>
    <fullName>CDsBloqueado__c</fullName>
    <label>CDs bloqueado</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <formula>Account.CNPJ__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CNPJ</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Orcamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/DataVencimento__c.field-meta.xml
<CustomField>
    <fullName>DataVencimento__c</fullName>
    <label>Data de Vencimento</label>
    <type>DateTime</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/ExternalPortal__c.field-meta.xml
<CustomField>
    <fullName>ExternalPortal__c</fullName>
    <externalId>true</externalId>
    <label>ExternalPortal</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/FretePicklist__c.field-meta.xml
<CustomField>
    <fullName>FretePicklist__c</fullName>
    <label>Tipo de Frete</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/IdIntegrator__c.field-meta.xml
<CustomField>
    <fullName>IdIntegrator__c</fullName>
    <externalId>true</externalId>
    <label>Id do Integrador</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/IdPortal__c.field-meta.xml
<CustomField>
    <fullName>IdPortal__c</fullName>
    <externalId>true</externalId>
    <label>Id Portal</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/Integradora__c.field-meta.xml
<CustomField>
    <fullName>Integradora__c</fullName>
    <label>Integradora</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/LastIntegratedItem__c.field-meta.xml
<CustomField>
    <fullName>LastIntegratedItem__c</fullName>
    <description>Aponta para o último QuoteItem__c que foi enviado para o informática com sucesso.</description>
    <label>Último item integrado</label>
    <type>TextArea</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/MinimumBilling__c.field-meta.xml
<CustomField>
    <fullName>MinimumBilling__c</fullName>
    <label>Faturamento Mínimo</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/ObservacoesLongText__c.field-meta.xml
<CustomField>
    <fullName>ObservacoesLongText__c</fullName>
    <label>Observações</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/PrazoEntrega__c.field-meta.xml
<CustomField>
    <fullName>PrazoEntrega__c</fullName>
    <label>Prazo de Entrega</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/PrazoValidade__c.field-meta.xml
<CustomField>
    <fullName>PrazoValidade__c</fullName>
    <label>Prazo de validade (em dias)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/RepresentanteVDELookup__c.field-meta.xml
<CustomField>
    <fullName>RepresentanteVDELookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Representante VDE</label>
    <referenceTo>User</referenceTo>
    <relationshipName>OportunidadesTrabalhadas</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do produto</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/classes/OpportunitySelector.cls
public without sharing class OpportunitySelector {
    
    private static OpportunitySelector instance;

    public static OpportunitySelector getInstance(){
        if(instance == null){
            instance = new OpportunitySelector();
        }
        return instance;
    }
    
    // public Opportunity getOpportunityById(Id accId){
    //     List<Opportunity> lstOpp = getOpportunitysById(new Set<Id>{accId});
    //     if(lstOpp.size() > 0){
    //         return lstOpp[0];
    //     } else {
    //         return null;
    //     }
    // }

    // public List<Opportunity> getOpportunitysById(Set<Id> setIds){
    //     return [
    //         SELECT 
    //             Id,
    //             CNPJ__c,
    //             Documento__c,
    //             Name,
    //             ExternalId__c
    //         FROM Opportunity 
    //         WHERE Id IN: setIds
    //     ];
    // }

    public Opportunity getOpportunityByIdForIntegrationPortalQuoteOUT(Id oppId){
        return [
            SELECT 
                Id,
                Name,
                ExternalPortal__c,
                Integradora__c,
                IdPortal__c,
                IdIntegrator__c,
                LastIntegratedItem__c,
                CDsBloqueado__c,
                CNPJ__c,
                StageName,
                RepresentanteVDELookup__r.Email,
                CanalEntrada__c,
                AccountId,
                Account.Name,
                DataVencimento__c,
                (
                    SELECT 
                        MinimumBilling__c,
                        CloseDate__c,
                        PrazoEntrega__c,
                        PrazoValidade__c,
                        CondicaoPagamento__r.ExternalId__c,
                        ObservacoesLongText__c,
                        CNPJCD__c,
                        FretePicklist__c
                    FROM Condicespagamentospor_CD__r
                ),
                (
                    SELECT
                        Id,
                        IdPortal__c,
                        IdArtigo__c,
                        CNPJCD__c,
                        Quantity,
                        UnitPrice,
                        ListPrice,
                        CodigoRastreio__c,
                        Comentarios__c,
                        TabulacaoN1__c,
                        Product2.ExternalId__c,
                        Product2.Fornecedor__r.Name,
                        Product2.UnidadeMedida__c,
                        Product2.Fornecedor__r.ExternalId__c,
                        Vendedor__r.CodigoUsuario__c
                    FROM OpportunityLineItems
                ),
                (
                    SELECT
                        TabulacaoN1__c,
                        TabulacaoN2__c,
                        User.CodigoUsuario__c,
                        HasChangesUnsync__c,
                        User.Name
                    FROM OpportunityTeamMembers
                    WHERE User.CodigoUsuario__c != NULL
                )
            FROM Opportunity 
            WHERE Id =: oppId
        ];
        // Vendedor__r.CodigoUsuario__c
    }
    
}