Git Tests/force-app/main/default/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <externalId>true</externalId>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/CodigoLoja__c.field-meta.xml
<CustomField>
    <fullName>CodigoLoja__c</fullName>
    <formula>CodigoCliente__c &amp; &quot;/&quot; &amp; LojaCliente__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código/loja</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>TextArea</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CompanyParameters__c/CompanyParameters__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Todos emails de compras</description>
    <label>Parametros da empresa</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/CompanyParameters__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <description>Email de compras</description>
    <inlineHelpText>Email de compras</inlineHelpText>
    <label>Email de compras</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CentroDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentroDistribuicao__c</fullName>
    <label>Centro de distribuição</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <formula>Account.CNPJ__c</formula>
    <label>CNPJ</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CodigoLoja__c.field-meta.xml
<CustomField>
    <fullName>CodigoLoja__c</fullName>
    <formula>Account.CodigoLoja__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Código/loja</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ComentariosCancelamento__c.field-meta.xml
<CustomField>
    <fullName>ComentariosCancelamento__c</fullName>
    <label>Comentários (opcional)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/MotivoCancelamento__c.field-meta.xml
<CustomField>
    <fullName>MotivoCancelamento__c</fullName>
    <label>Motivo de cancelamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Desistência do cliente</fullName>
            </value>
            <value>
                <fullName>Cancelado para correção</fullName>
            </value>
            <value>
                <fullName>Falha operacional</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/StatusIntegracao__c.field-meta.xml
<CustomField>
    <fullName>StatusIntegracao__c</fullName>
    <label>Status da integração</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Integrado</fullName>
            </value>
            <value>
                <fullName>Não integrado</fullName>
            </value>
            <value>
                <fullName>Erro de aprovação/rejeição</fullName>
            </value>
            <value>
                <fullName>Nota fiscal cancelada</fullName>
            </value>
            <value>
                <fullName>Pedido em aberto</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por regra</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por crédito</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por estoque</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por crédito e estoque</fullName>
            </value>
            <value>
                <fullName>Pedido aguardando separação</fullName>
            </value>
            <value>
                <fullName>Pedido em separação</fullName>
            </value>
            <value>
                <fullName>Pedido separado/aguardando faturamento</fullName>
            </value>
            <value>
                <fullName>Pedido faturado</fullName>
            </value>
            <value>
                <fullName>Pedido com resíduo eliminado (sem faturamento)</fullName>
            </value>
            <value>
                <fullName>Pedido com resíduo eliminado (com faturamento)</fullName>
            </value>
            <value>
                <fullName>Pedido liberado</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado na alçada de desconto</fullName>
            </value>
            <value>
                <fullName>Pedido com SC</fullName>
            </value>
            <value>
                <fullName>Pedido aguardando saldo</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por regra de bonificação</fullName>
            </value>
            <value>
                <fullName>Pedido cancelado</fullName>
            </value>
            <value>
                <fullName>Pedido rejeitado no Salesforce</fullName>
            </value>
            <value>
                <fullName>Pedido rejeitado na alçada financeira</fullName>
            </value>
            <value>
                <fullName>Erro integração (Envio ao Protheus)</fullName>
            </value>
            <value>
                <fullName>Erro integração (geração do pedido no Protheus)</fullName>
            </value>
            <value>
                <fullName>Pedido aguardando envio/processamento do comprovante de pagamento RA</fullName>
            </value>
            <value>
                <fullName>Pedido aguardando aprovação de pagamento RA</fullName>
            </value>
            <value>
                <fullName>Pedido rejeitado na alçada de aprovação de pagamento RA</fullName>
            </value>
            <value>
                <fullName>Aguardando processamento na integradora</fullName>
            </value>
            <value>
                <fullName>Aprovado na integradora</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/SubmotivosCancelamento__c.field-meta.xml
<CustomField>
    <fullName>SubmotivosCancelamento__c</fullName>
    <label>Submotivo de cancelamento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>MotivoCancelamento__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Preço</fullName>
            </value>
            <value>
                <fullName>Prazo de entrega</fullName>
            </value>
            <value>
                <fullName>Condição de pagamento</fullName>
            </value>
            <value>
                <fullName>Qualidade do produto</fullName>
            </value>
            <value>
                <fullName>Quantidade insuficiente</fullName>
            </value>
            <value>
                <fullName>Preferiu a concorrência</fullName>
            </value>
            <value>
                <fullName>Inclusão de item</fullName>
            </value>
            <value>
                <fullName>Exclusão de item</fullName>
            </value>
            <value>
                <fullName>Erro de estoque</fullName>
            </value>
            <value>
                <fullName>Correção de preço</fullName>
            </value>
            <value>
                <fullName>Marca do produto</fullName>
            </value>
            <value>
                <fullName>Quantidade do item</fullName>
            </value>
            <value>
                <fullName>Endereço de entrega</fullName>
            </value>
            <value>
                <fullName>Tamanho diferente da nota fiscal</fullName>
            </value>
            <value>
                <fullName>Quantidade diferente da nota fiscal</fullName>
            </value>
            <value>
                <fullName>Aprovação fora do prazo</fullName>
            </value>
            <value>
                <fullName>Aprovação de cadastro</fullName>
            </value>
            <value>
                <fullName>Erro na descrição</fullName>
            </value>
            <value>
                <fullName>Devolução e troca do material</fullName>
            </value>
            <value>
                <fullName>Faturado o mesmo pedido duas vezes</fullName>
            </value>
            <value>
                <fullName>Fator de conversão e unidade de medida</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/CentroDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentroDistribuicao__c</fullName>
    <label>Centro de distribuição</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/ItemPendente__c.field-meta.xml
<CustomField>
    <fullName>ItemPendente__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Item pendente</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/SendEmailMessage.cls
global without sharing class SendEmailMessage { 
    public static void emailMessage(Order pendingOrder) {
        Order orderEmail = [SELECT Id, OrderNumber, CreatedBy.Email, CreatedBy.CompanyName, Account.Name, Account.CNPJ__c, Account.CodigoLoja__c FROM Order WHERE Id = :pendingOrder.Id][0];

        Messaging.reserveSingleEmailCapacity(2);
        Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
        List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();

        List<OrderItem> orderItemList = [SELECT Id, OrderId, Quantity, Product2.ProductCode, Product2.Name, ItemPendente__c, CentroDistribuicao__c FROM OrderItem WHERE OrderId = :pendingOrder.Id AND ItemPendente__c = true];
        
        List<String> splitList = orderEmail.CreatedBy.CompanyName.split('/');
        List<String> toAddresses = new List<String>{};
        String tituloEmail = '';
        for (String split : splitList) {
            if (tituloEmail == '') {
                tituloEmail = split;
            } else {
                tituloEmail = tituloEmail + ' | ' + split;
            }
            CompanyParameters__c emails = CompanyParameters__c.getAll().get(split);
            toAddresses.add(Test.isRunningTest() ? 'test@test.com' : emails?.Email__c);
        }
        toAddresses.add(orderEmail.CreatedBy.Email);
        
        mail.setToAddresses(toAddresses);
        mail.setSaveAsActivity(false);
        mail.setSubject('[ ' + tituloEmail.toUppercase() + ' ]' + ' Solicitação de compras');

        String bodyEmail = 'Foi gerado o pedido ' + orderEmail.OrderNumber + ' com pendências.<br/>' + orderEmail.Account.Name + ' | ' + orderEmail.Account.CNPJ__c + ' | ' + orderEmail.Account.CodigoLoja__c + '<br/>Produtos:<br/>';
        for (OrderItem orderItem : orderItemList) {
            bodyEmail = bodyEmail + orderItem.Product2.ProductCode + '-' + orderItem.Product2.Name + ' | Quantidade pendente: ' + orderItem.Quantity + ' | ' + orderItem.CentroDistribuicao__c + '<br/>';
        }

        mail.setHtmlBody(bodyEmail);
        emailList.add(mail);

        if (!emailList.isEmpty()) {
            List<Messaging.SendEmailResult> results = Messaging.sendEmail(emailList);
            System.debug('Email de pedido pendente enviado com sucesso para:');
            System.debug(toAddresses);
            System.debug(results);
        }
        System.debug('Enviou Email de Pedido Pendente.');
    }

    public static void sendEmailMessageCancelledOrder(List<Order> listCancelledOrders){
        Set<String> orderOwnerIds = new Set<String>();
        Set<String> orderAccountIds = new Set<String>();

        for(Order cancelledOrder : listCancelledOrders){
            orderOwnerIds.add(cancelledOrder.OwnerId);
            orderAccountIds.add(cancelledOrder.AccountId);
        }

        Map<Id, User> mapUsers = new Map<Id, User>([SELECT Id, Name, Email FROM User WHERE Id IN : orderOwnerIds]);
        Map<Id, Account> mapAccounts = new Map<Id, Account>([SELECT Id, Name, CNPJ__c, CodigoLoja__c FROM Account WHERE Id IN : orderAccountIds]);
        CustomNotificationType notificationType = [SELECT Id, DeveloperName FROM CustomNotificationType WHERE DeveloperName = 'CancelledOrderNotification'];

        List<Messaging.SingleEmailMessage> emailListCancelledOrders = new List<Messaging.SingleEmailMessage>();
        for(Order cancelledOrder : listCancelledOrders){
            if(mapUsers.containsKey(cancelledOrder.OwnerId)){
                if(mapAccounts.containsKey(cancelledOrder.AccountId)){
                    User currentUser = mapUsers.get(cancelledOrder.OwnerId);
                    Account currentAccount = mapAccounts.get(cancelledOrder.AccountId);
                    
                    Messaging.reserveSingleEmailCapacity(2);
                    Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
                    
                    List<String> toAddresses = new List<String>{currentUser.Email};

                    mail.setToAddresses(toAddresses);
                    mail.setSubject('Aviso de cancelamento de pedido - ' + cancelledOrder.OrderNumber);

                    String bodyEmail;

                    if (cancelledOrder.MotivoCancelamento__c == null) {
                        bodyEmail = 'Olá ' + currentUser.Name + '.<br/><br/>O pedido ' + cancelledOrder.OrderNumber + ' do cliente ' + currentAccount.Name + ' - ' + currentAccount.CNPJ__c + ' - ' + currentAccount.CodigoLoja__c + ' foi cancelado no dia ' + cancelledOrder.LastModifiedDate.format() + '<br/>Motivo do cancelamento: ' + cancelledOrder.StatusIntegracao__c + ' - ' + cancelledOrder.ComentariosCancelamento__c;
                    } else {
                        bodyEmail = 'Olá ' + currentUser.Name + '.<br/><br/>O pedido ' + cancelledOrder.OrderNumber + ' do cliente ' + currentAccount.Name + ' - ' + currentAccount.CNPJ__c + ' - ' + currentAccount.CodigoLoja__c + ' foi cancelado no dia ' + cancelledOrder.LastModifiedDate.format() + '<br/>Motivo do cancelamento: ' + cancelledOrder.MotivoCancelamento__c + ' - ' + cancelledOrder.SubmotivosCancelamento__c;
                    }

                    mail.setHtmlBody(bodyEmail);
                    emailListCancelledOrders.add(mail);                     
        
                    Messaging.CustomNotification cancelledOrderNotification = new Messaging.CustomNotification();
                        
                    String bodyNotification;

                    cancelledOrderNotification.setTitle('Aviso de cancelamento de pedido');
                    cancelledOrderNotification.setTargetId(cancelledOrder.Id);
                    cancelledOrderNotification.setNotificationTypeId(notificationType.Id);
                    
                    if (cancelledOrder.MotivoCancelamento__c == null) {
                        bodyNotification = 'O pedido ' + cancelledOrder.OrderNumber + ' do cliente ' + currentAccount.Name + ' - ' + currentAccount.CNPJ__c + ' - ' + currentAccount.CodigoLoja__c + ' foi cancelado no dia ' + cancelledOrder.LastModifiedDate.format() + '\nMotivo do cancelamento: ' + cancelledOrder.StatusIntegracao__c + ' - ' + cancelledOrder.ComentariosCancelamento__c;
                        System.debug('Cancelamento automático');
                    } else {
                        bodyNotification = 'O pedido ' + cancelledOrder.OrderNumber + ' do cliente ' + currentAccount.Name + ' - ' + currentAccount.CNPJ__c + ' - ' + currentAccount.CodigoLoja__c + ' foi cancelado no dia ' + cancelledOrder.LastModifiedDate.format() + '\nMotivo do cancelamento: ' + cancelledOrder.MotivoCancelamento__c + ' - ' + cancelledOrder.SubmotivosCancelamento__c;
                        System.debug('Cancelamento manual');
                    } 
                    cancelledOrderNotification.setBody(bodyNotification);
                    
                    try {
                        cancelledOrderNotification.send(orderOwnerIds);
                    }
                    catch (Exception e) {
                        System.debug('Erro na notificação de sininho cancelamento de pedido ' + e.getMessage());
                    } 
                }
            }
        }     
        if (!emailListCancelledOrders.isEmpty()) {
            List<Messaging.SendEmailResult> results = Messaging.sendEmail(emailListCancelledOrders);
            System.debug(results);
        }
    }
}