Git Tests/force-app/main/default/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <externalId>true</externalId>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <externalId>true</externalId>
    <label>CPF</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Estoque__c/Estoque__c.object-meta.xml
<CustomObject>
    <label>Estoque</label>
    <nameField>
        <label>Número do estoque</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estoques</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Estoque__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do estoque</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Fornecedor__c/Fornecedor__c.object-meta.xml
<CustomObject>
    <label>Fornecedor</label>
    <nameField>
        <label>Nome do fornecedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fornecedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Fornecedor__c/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Fornecedor__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do fornecedor</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/ItemCampanha__c.object-meta.xml
<CustomObject>
    <label>Item da campanha</label>
    <nameField>
        <label>Código do item de campanha</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens da campanha</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do item de campanha</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <formula>NomeProduto__r.Fornecedor__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fornecedor</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/Lote__c.field-meta.xml
<CustomField>
    <fullName>Lote__c</fullName>
    <label>Lote</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CentroDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentroDistribuicao__c</fullName>
    <label>Centro de Distribuição</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <formula>Account.CNPJ__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CNPJ</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Orcamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/ContatoOrcamento__c.field-meta.xml
<CustomField>
    <fullName>ContatoOrcamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato do orçamento</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Orcamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <formula>Account.CPF__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CPF</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/MargemAlvo__c.field-meta.xml
<CustomField>
    <fullName>MargemAlvo__c</fullName>
    <label>Margem alvo</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/CategoriaComercial__c.field-meta.xml
<CustomField>
    <fullName>CategoriaComercial__c</fullName>
    <formula>TEXT(PricebookEntry.Product2.CategoriaComercial__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Categoria comercial</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/CentroDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentroDistribuicao__c</fullName>
    <label>Centro de distribuição</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Chave Externa</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/ForaMalha__c.field-meta.xml
<CustomField>
    <fullName>ForaMalha__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Fora de malha?</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <formula>PricebookEntry.Product2.Fornecedor__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fornecedor</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/ItemCampanha__c.field-meta.xml
<CustomField>
    <fullName>ItemCampanha__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item da campanha</label>
    <referenceTo>ItemCampanha__c</referenceTo>
    <relationshipLabel>Produto do orçamento</relationshipLabel>
    <relationshipName>ProdutoOrcamento</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/JustificativaDesconto__c.field-meta.xml
<CustomField>
    <fullName>JustificativaDesconto__c</fullName>
    <label>Justificativa de desconto</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/Lote__c.field-meta.xml
<CustomField>
    <fullName>Lote__c</fullName>
    <label>Lote</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/MargemAlvo__c.field-meta.xml
<CustomField>
    <fullName>MargemAlvo__c</fullName>
    <label>Margem Alvo</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/MargemAtual__c.field-meta.xml
<CustomField>
    <fullName>MargemAtual__c</fullName>
    <label>Margem Atual</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Pricebook2/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Catálogos de preços</relationshipLabel>
    <relationshipName>CatalogoPreco</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Pricebook2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/CategoriaComercial__c.field-meta.xml
<CustomField>
    <fullName>CategoriaComercial__c</fullName>
    <label>Categoria comercial</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>G</fullName>
                <label>GENÉRICO</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>MATERIAIS</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>NUTRIÇÃO</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Medctech</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>REFERÊNCIA</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>AMBOS</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>DIABETES</label>
            </value>
            <value>
                <fullName>Q</fullName>
                <label>ODONTOLOGIA</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Especialidade</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <label>EQUIPAMENTO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do produto</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fornecedor</label>
    <referenceTo>Fornecedor__c</referenceTo>
    <relationshipLabel>Produtos</relationshipLabel>
    <relationshipName>Produtos</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/UnidadeMedida__c.field-meta.xml
<CustomField>
    <fullName>UnidadeMedida__c</fullName>
    <label>Unidade de medida</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteLineItem/fields/UnidadeMedida__c.field-meta.xml
<CustomField>
    <fullName>UnidadeMedida__c</fullName>
    <label>Unidade de medida</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/RecomendacaoCotacao__c/RecomendacaoCotacao__c.object-meta.xml
<CustomObject>
    <label>Recomendação da cotação</label>
    <nameField>
        <label>Nome de Recomendação da cotação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recomendações da cotação</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/RecomendacaoCotacao__c/fields/CentroDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentroDistribuicao__c</fullName>
    <label>Centro de distribuição</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/RecomendacaoCotacao__c/fields/Cotacao__c.field-meta.xml
<CustomField>
    <fullName>Cotacao__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cotação</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Recomendações da cotação</relationshipLabel>
    <relationshipName>RecomendacaoCotacao</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/RecomendacaoCotacao__c/fields/UnidadeMedida__c.field-meta.xml
<CustomField>
    <fullName>UnidadeMedida__c</fullName>
    <label>Unidade de medida</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/TemplatePDF__c/TemplatePDF__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Objeto para os dados de template de PDF.</description>
    <label>Template PDF</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/TemplatePDF__c/fields/Id__c.field-meta.xml
<CustomField>
    <fullName>Id__c</fullName>
    <label>Id</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/OpportunityCreatePDF.cls
public without sharing class OpportunityCreatePDF {
    
    @InvocableMethod(label='Generate PDF' description='Button to generate the opportunity PDF')
    public static List<String> flowCreatePDF(List<FlowInputs> flowInputsList) {

        String oppId = null;
        String pdf = null;
        String prodCode = '';
        for (FlowInputs flow : flowInputsList) {
            oppId = flow.opportunityId;
            pdf = flow.pdfChoice;
            prodCode = flow.productCode;
        }

        List<String> prodCodeList = prodCode.split(',');
        System.debug('prodCodeList => '+ prodCodeList);
        Map<String, Product2> prodCodeToIdMap = new Map<String, Product2>();
        for (Product2 prod : [SELECT Id, ExternalId__c, Description, CategoriaComercial__c, UnidadeMedida__c FROM Product2 WHERE ExternalId__c IN: prodCodeList]) {
            prodCodeToIdMap.put(prod.ExternalId__c, prod);
        }
        System.debug('prodCodeToIdMap => '+ prodCodeToIdMap);

        Opportunity contextOpportunity = null;
        for (Opportunity o : [SELECT Id, Name, ContatoOrcamento__c, CloseDate, Account.CNPJ__c, Account.CPF__c, Pricebook2.ExternalId__c, CondicaoPagamento__r.ExternalId__c FROM Opportunity WHERE Id = :oppId]) {
            contextOpportunity = o;
        }

        Boolean hasPermissionERB = false;
        for (PermissionSetAssignment pSet : [SELECT Id, PermissionSet.Name, Assignee.Name, AssigneeId FROM PermissionSetAssignment WHERE Assignee.Username =: UserInfo.getUsername() AND PermissionSet.Name =: 'UsuarioERB']) {
            hasPermissionERB = true;
        }

        // List<RecomendacaoCotacao__c> recommendationQuoteList = [SELECT Id FROM RecomendacaoCotacao__c WHERE Cotacao__r.OpportunityId = :oppId];
        // if (recommendationQuoteList.size() > 0) {
        //     hasPermissionERB = false;
        // }

        List<Object> malhaResult = null;
        if (pdf == 'ElfaQuoteRecommendationTemplate' && hasPermissionERB) {
            malhaResult = OrderScreenController.getMalha(contextOpportunity.Account.CNPJ__c != null ? contextOpportunity.Account.CNPJ__c : contextOpportunity.Account.CPF__c, prodCode, true, contextOpportunity.Pricebook2.ExternalId__c, contextOpportunity.CondicaoPagamento__r.ExternalId__c, false);
            System.debug(malhaResult);
        }        
        
        Quote newQuote = new Quote(
            name           = contextOpportunity.name,
            OpportunityId  = contextOpportunity.Id,
            ContactId      = contextOpportunity.ContatoOrcamento__c,
            ExpirationDate = contextOpportunity.CloseDate
        );
        insert newQuote;

        List<QuoteLineItem> quoteLineItemList = new List<QuoteLineItem>();

        List<OpportunityLineItem> newOppLineItemList = new List<OpportunityLineItem>();

        for (OpportunityLineItem oLineItem : [SELECT Id, CategoriaComercial__c, CentroDistribuicao__c, ProductCode, ServiceDate, Discount, Description, 
                                                ForaMalha__c, Fornecedor__c, ItemCampanha__c, JustificativaDesconto__c, Lote__c, MargemAlvo__c, MargemAtual__c, 
                                                Name, NumeroAnvisa__c, OpportunityId, ListPrice, UnitPrice, TotalPrice, PrincipioAtivo__c, Product2Id, Quantity, 
                                                QuantidadeUn__c, ScoreAlvo__c, ScoreAtual__c, Subtotal, Temperatura__c, ValidadeMinima__c, ValorCx__c, ValorUn__c,
                                                ValorTotal__c, Vendedor__c, Product2.FatorConversao__c, Product2.Fornecedor__r.Name, Product2.ProductCode,
                                                Product2.UnidadeMedida__c, Product2.Name, PricebookEntryId, CNPJCD__c, Product2.CategoriaComercial__c
                                                FROM OpportunityLineItem WHERE OpportunityId = :contextOpportunity.Id]) {
            
            QuoteLineItem quoteLineItem            = new QuoteLineItem();
            quoteLineItem.CentroDistribuicao__c    = oLineItem.CentroDistribuicao__c;
            quoteLineItem.CodigoItem__c            = oLineItem.Product2.ProductCode;
            quoteLineItem.ServiceDate              = oLineItem.ServiceDate;
            quoteLineItem.Discount                 = oLineItem.Discount;
            quoteLineItem.Description              = oLineItem.Description;
            quoteLineItem.Fabricante__c            = oLineItem.Product2.Fornecedor__r.Name;
            quoteLineItem.FatorConversao__c        = oLineItem.Product2.FatorConversao__c;
            quoteLineItem.Product2Id               = oLineItem.Product2Id;
            quoteLineItem.QuoteId                  = newQuote.Id;
            quoteLineItem.PricebookEntryId         = oLineItem.PricebookEntryId;
            quoteLineItem.Produto__c               = oLineItem.Product2.name;
            quoteLineItem.Quantity                 = oLineItem.Quantity;
            quoteLineItem.UnidadeMedida__c         = oLineItem.Product2.UnidadeMedida__c;
            quoteLineItem.ValorCx__c               = oLineItem.ValorCx__c;
            quoteLineItem.UnitPrice                = oLineItem.UnitPrice;
            quoteLineItem.CNPJCD__c                = oLineItem.CNPJCD__c;
            quoteLineItem.OpportunityLineItemId    = oLineItem.Id;

            if (oLineItem.Product2.CategoriaComercial__c == 'S' || oLineItem.Product2.CategoriaComercial__c == 'G') {
                quoteLineItem.PrincipioAtivo__c    = oLineItem.PrincipioAtivo__c;
            }

            quoteLineItemList.add(quoteLineItem);
        }

        if (!quoteLineItemList.isEmpty()) {
            insert quoteLineItemList;
        }

        if (pdf == 'ElfaQuoteRecommendationTemplate' && hasPermissionERB) {
            List<RecomendacaoCotacao__c> quoteRecommendationList = new List<RecomendacaoCotacao__c>();
            for (Object obj: malhaResult) {
                MalhaObject malhaObj = (MalhaObject) JSON.deserialize(JSON.serialize(obj), MalhaObject.class);
                System.debug('malhaObj: ' + malhaObj);
                if (malhaObj != null && malhaObj.cds != null) {
                    for (CdObject cdObj : malhaObj.cds) {
                        if (cdObj.saldo == 0) 
                            continue;
                        RecomendacaoCotacao__c quoteRecommendation = new RecomendacaoCotacao__c();
                        quoteRecommendation.Name = malhaObj.codprotheus;
                        quoteRecommendation.Cotacao__c = newQuote.Id;
                        quoteRecommendation.Estoque__c = cdObj.saldo;
                        quoteRecommendation.ValorUnitario__c = cdObj.preco;
                        quoteRecommendation.CentroDistribuicao__c = cdObj.filial;
                        quoteRecommendation.Produto__c = prodCodeToIdMap.containsKey(malhaObj.codprotheus) ? prodCodeToIdMap.get(malhaObj.codprotheus).Id : null;                        
                        quoteRecommendation.UnidadeMedida__c = prodCodeToIdMap.containsKey(malhaObj.codprotheus) ? prodCodeToIdMap.get(malhaObj.codprotheus).UnidadeMedida__c : null;                        
                        System.debug('recomendação => ' + quoteRecommendation);
                        quoteRecommendationList.add(quoteRecommendation);
                        break;
                    }                    
                }
            }

            if (!quoteRecommendationList.isEmpty()) {
                insert quoteRecommendationList;
            }
        }

        getQuoteTemplate(newQuote.id, pdf);
        
        return new List<String>{newQuote.id};
    }

    @AuraEnabled
    public static void getQuoteTemplate(Id recordId, String pdf) {
        insertQuoteTemplate(recordId, pdf);
    }

    @future(callout=true)
    public static void insertQuoteTemplate(Id recordId, String pdf) {

        TemplatePDF__c template = TemplatePDF__c.getValues(pdf);
        String templateId = template.Id__c;

        PageReference pr = new PageReference('/quote/quoteTemplateDataViewer.apexp?id=' + recordId + '&summlid=' + templateId); 

        QuoteDocument qd = new QuoteDocument(); 
        Blob b = !Test.isRunningTest() ? pr.getContentAsPDF() : Blob.valueOf('Test');

        qd.Document = b;
        qd.QuoteId = recordId;
        insert qd;

        Quote contextQuote = null;
        for (Quote quote : [SELECT Id, Opportunity.Name, OpportunityId/*, ContatoOrcamento__c, ContatoOrcamento__r.Email*/ FROM Quote WHERE Id = :recordId]) {
            contextQuote = quote;
        }

        ContentVersion ctVersion    = new ContentVersion();
        String attName = 'Orçamento' + contextQuote.Opportunity.Name +'.pdf';
        ctVersion.Title             = attName;
        ctVersion.PathOnClient      = attName;
        ctVersion.VersionData       = b;
        insert ctVersion;

        ContentDocumentLink cdl     = new ContentDocumentLink();
        cdl.ContentDocumentId       = [SELECT Id, ContentDocumentId FROM ContentVersion WHERE Id =: ctVersion.Id].ContentDocumentId;
        cdl.LinkedEntityId          = contextQuote.OpportunityId;
        cdl.ShareType               = 'V';
        cdl.Visibility              = 'AllUsers';
        insert cdl;

        // Id templateEmailId;
        // for (EmailTemplate e : [SELECT Id, Name, Body, Subject, HtmlValue FROM EmailTemplate WHERE DeveloperName = 'EmailGeracaoPDF' LIMIT 1]) {
        //     templateEmailId = e.Id;
        // }

        // List<Messaging.singleEmailMessage> messageList = new List<Messaging.singleEmailMessage>();
        // Messaging.singleEmailMessage ownerMessage = new Messaging.singleEmailMessage();
        // Messaging.EmailFileAttachment efa = new Messaging.EmailFileAttachment();
        // efa.setFileName(attName);
        // efa.setBody(b);
       
        // ownerMessage.setToAddresses(new List<String>{contextQuote.ContatoOrcamento__r.Email});
        // ownerMessage.setTemplateId(templateEmailId);
        // ownerMessage.setTargetObjectId(contextQuote.ContatoOrcamento__c);
        // ownerMessage.setWhatId(contextQuote.OpportunityId);
        // ownerMessage.setSaveAsActivity(false);
        // ownerMessage.setFileAttachments(new Messaging.EmailFileAttachment[] {efa});
        // messageList.add(ownerMessage);

        // if(!messageList.isEmpty()) {
        //     Messaging.sendEmail(messageList);
        // } 
    }
    
    public class FlowInputs{
    
        @InvocableVariable
        public String opportunityId;
        
        @InvocableVariable
        public String pdfChoice;

        @InvocableVariable
        public String productCode;
    }

    public class MalhaObject {
    
        public List<CdObject> cds;
        public String codprotheus;
        public String ean;
    }

    public class CdObject {
    
        public Decimal aliquota;
        public String  foramalha;
        public String  prioridade;
        public String  cnpj;
        public Decimal saldo;
        public Decimal custo;
        public String  cd;
        public String  filial;
        public String  tipopreco;
        public Decimal preco;
        public String  BloqRegionalizacao;
        public String  laboratorio;
        // public List<Object> range;
    }
}