Git Tests/force-app/main/default/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <externalId>true</externalId>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Case/fields/AnaliseDoCaso__c.field-meta.xml
<CustomField>
    <fullName>AnaliseDoCaso__c</fullName>
    <label>Análise do Caso</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Procedente</fullName>
            </value>
            <value>
                <fullName>Não Procedente</fullName>
            </value>
            <value>
                <fullName>Em Análise</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
                <default>true</default>
                <label>N/A</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Case/fields/Razao__c.field-meta.xml
<CustomField>
    <fullName>Razao__c</fullName>
    <label>Razão</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Cadastro</fullName>
            </value>
            <value>
                <fullName>Carta de Comprometimento de Troca</fullName>
            </value>
            <value>
                <fullName>Carta de Correção</fullName>
            </value>
            <value>
                <fullName>Cotação</fullName>
            </value>
            <value>
                <fullName>Devolução</fullName>
            </value>
            <value>
                <fullName>Faturamento Pedido</fullName>
            </value>
            <value>
                <fullName>Fechamento de Loop</fullName>
            </value>
            <value>
                <fullName>Financeiro</fullName>
            </value>
            <value>
                <fullName>Pedido não faturado</fullName>
            </value>
            <value>
                <fullName>Pesquisa Ativa</fullName>
            </value>
            <value>
                <fullName>Reclamação</fullName>
            </value>
            <value>
                <fullName>Tracking do Pedido</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Case/fields/ToAddress__c.field-meta.xml
<CustomField>
    <fullName>ToAddress__c</fullName>
    <label>To Address</label>
    <type>Email</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/LogIntegration__c/LogIntegration__c.object-meta.xml
<CustomObject>
    <label>Log de Integração</label>
    <nameField>
        <displayFormat>LOG-{000000}</displayFormat>
        <label>Nome de Log de Integração</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Log das Integrações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/LogIntegration__c/recordTypes/Chatbot.recordType-meta.xml
<RecordType>
    <fullName>Chatbot</fullName>
    <active>true</active>
    <label>Chat bot</label>
</RecordType>

Git Tests/force-app/main/default/default/objects/NotasFiscais__c/NotasFiscais__c.object-meta.xml
<CustomObject>
    <label>Nota fiscal</label>
    <nameField>
        <label>Número da nota fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas fiscais</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/NotasFiscais__c/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <formula>Conta__r.CNPJ__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CNPJ</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/NotasFiscais__c/fields/Pedido__c.field-meta.xml
<CustomField>
    <fullName>Pedido__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número do pedido</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>NotasFiscais</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/NotasFiscais__c/fields/SerieNota__c.field-meta.xml
<CustomField>
    <fullName>SerieNota__c</fullName>
    <label>Série da nota</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/NotasFiscais__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Emitido</fullName>
                <default>true</default>
                <label>Emitido</label>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ClienteRecebedor__c.field-meta.xml
<CustomField>
    <fullName>ClienteRecebedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente recebedor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedido</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <formula>Account.CNPJ__c</formula>
    <label>CNPJ</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Chave única: Número do pedido + Código do CD</description>
    <externalId>true</externalId>
    <label>Código do pedido TOTVS</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/Numero_da_Nota_Fiscal_Normalizado__c.field-meta.xml
<CustomField>
    <fullName>Numero_da_Nota_Fiscal_Normalizado__c</fullName>
    <formula>SUBSTITUTE(
	SUBSTITUTE(
		SUBSTITUTE( NumeroNotaFiscal__c ,&quot;.&quot;,&quot;&quot;),
	&quot;/&quot;,&quot;&quot;),
&quot;-&quot;,&quot;&quot;)</formula>
    <label>Número da Nota Fiscal Normalizado</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/NumeroPedidoCliente__c.field-meta.xml
<CustomField>
    <fullName>NumeroPedidoCliente__c</fullName>
    <inlineHelpText>Ex: AF123, OC345, ID6864</inlineHelpText>
    <label>Ordem de compra do cliente</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/PedidoPai__c.field-meta.xml
<CustomField>
    <fullName>PedidoPai__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido pai</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Pedidos filho</relationshipLabel>
    <relationshipName>PedidoFilho</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/ChatBot.cls
public without sharing class ChatBot {
    
    @InvocableVariable(required=true)
    public String cnpj;
    
    @InvocableMethod(label='Create a case')
    public static List<String> createCase(List<String> cnpj) {
        
        try {
            
            Contact con = [SELECT Id, Account.Id, Email FROM Contact WHERE Account.CNPJ__c =: cnpj LIMIT 1];
            Group gr = [SELECT Id FROM Group WHERE DeveloperName =: 'AtendimentoAoClienteQueue'];
            
            Case c = new Case(
                AccountId = con.Account.Id,
                ContactId = con.Id,
                Status = 'New',
                AnaliseDoCaso__c = 'Procedente',
                Origin = 'Chatbot',
                Priority = 'Medium',
                SuppliedEmail = con.Email,
                ToAddress__c = con.Email,
                Type = 'Solicitação',
                Razao__c = 'Cadastro',
                OwnerId = gr.Id
            );
            
            insert c;
            
            c = [SELECT CaseNumber 
                 FROM Case WHERE Id=: c.Id];
            
            return new String[]{ c.CaseNumber};
                
                } catch (Exception ex) {
                    LogIntegration__c log = new LogIntegration__c(
                        RecordTypeId      = Schema.SObjectType.LogIntegration__c.getRecordTypeInfosByDeveloperName().get('Chatbot').getRecordTypeId(),
                        Integration__c    = ChatBot.class.getName(),
                        Status__c         = 'ERROR',
                        ExecuteDate__c    = System.today(),
                        Message__c = ex.getMessage() + ' ' + ex.getStackTraceString()
                    );
                }
        
        return null;
    }
    
    @AuraEnabled
    public static String fetchBase64File(Map<String, Object> params) {
        
        try {
            
            String customerId = (String)params.get('customerId');
            String invoiceNumber = (String)params.get('invoiceNumber');
            String documentType = (String)params.get('documentType');
            String orderNumber = (String)params.get('orderNumber');
            
            Map<String, Object> body;
            
            switch on documentType {
                when 'invoice' {		
                    return getInvoice(customerId, invoiceNumber);            
                }	
                when 'paymentSlip' {	
                    return getPaymentSlip(customerId, orderNumber);
                }
            }        
            
        } catch (Exception ex) {
            LogIntegration__c log = new LogIntegration__c(
                RecordTypeId      = Schema.SObjectType.LogIntegration__c.getRecordTypeInfosByDeveloperName().get('Chatbot').getRecordTypeId(),
                Integration__c    = ChatBot.class.getName(),
                Status__c         = 'ERROR',
                ExecuteDate__c    = System.today()
            );
            String message = ex.getMessage() + ' ' + ex.getStackTraceString();
            if (message.length() >= 255) {
                message = message.substring(0, 254);
            }
            log.Message__c = message;
            insert log;

            return log.Id;
        }
        
        return null;
    }  
    
    private static String getInvoice(String customerId, String invoiceNumber) {
        
        String likeCondition = '%' + invoiceNumber + '%';
        NotasFiscais__c invoice = [ SELECT Pedido__r.CNPJCD__c, SerieNota__c, ExternalId__c
                                   FROM NotasFiscais__c
                                   WHERE ExternalId__c LIKE :likeCondition];
                        
        String path = '/P-PROTHEUS-PORT-CLIENTE-DANFE-XML';
        Map<String, String> body = new Map<String, String> {
            'cnpj_cd' => invoice.Pedido__r.CNPJCD__c,
                'Nota' => invoice.ExternalId__c.substring(5, 14),
                'Serie' => invoice.SerieNota__c,
                'tipo' => 'D'
                };
                    
                    
                    Map<String, Object> desResponse = (Map<String, Object>)JSON.deserializeUntyped(requestData(path, body));
        
        return (String)desResponse.get('danfe');
        
    }
    
    private static String getPaymentSlip(String customerId, String orderNumber) {
        
        String path = '/P-SFDC-Consulta-TitulosAbertos';
        Map<String, String> body = new Map<String, String> {
            'CGC' => customerId
                };
                    
		OpenPayments payments = (OpenPayments)JSON.deserialize(requestData(path, body), OpenPayments.class);

        Order order = [SELECT Numero_da_Nota_Fiscal_Normalizado__c FROM Order WHERE CNPJ__c=: customerId AND NumeroPedidoCliente__c =: orderNumber AND PedidoPai__c <> NULL LIMIT 1];

        OpenPayment openPayment;
        for (OpenPayment op : payments.TituloAberto) {
            if ((String.isNotBlank(order.Numero_da_Nota_Fiscal_Normalizado__c) && order.Numero_da_Nota_Fiscal_Normalizado__c.contains(op.NUM)) || op.PEDIDO == orderNumber) {
                openPayment = op;
                break;
            }
        }

        if (openPayment == null) {
            return null;
        }
        
        path = '/P-SFDC-BOLETOS';
        body = new Map<String, String> {
            'cnpj_cd' => openPayment.CGC_CD,
                'NumeroBoleto' => openPayment.NUM,
                'prefixo' => openPayment.PREFIXO,
                'tipo' => openPayment.TIPO,
                'parcela' => openPayment.PARCELA
                };
                    
		Map<String, Object> desResponse = (Map<String, Object>)JSON.deserializeUntyped(requestData(path, body));   
        
        
        return (String)desResponse.get('boleto');
        
    }  
    
    private static String requestData(String path, Map<String, String> body) {
        
        HttpRequest req = new HttpRequest();
        req.setEndpoint('callout:DanfeSync' + path);
        req.setMethod('POST');
        req.setTimeout(120000);
        req.setHeader('Content-Type', 'application/json');
        req.setHeader('Accept', 'application/json');
        req.setHeader('Accept-Encoding', 'gzip');
        req.setBody(JSON.serialize(body));
        Http http = new Http();
        HttpResponse res = http.send(req);
        System.debug(res.getBody());
        
        if (res.getStatusCode() == 200) {
            
            Map<String, Object> desResponse = (Map<String, Object>)JSON.deserializeUntyped(res.getBody());
            
            if (desResponse.containsKey('error')) {
                throw new ChatbotException(res.getBody());
            }
            
            return res.getBody();
            
        } else {
            throw new ChatbotException(res.getBody());
        }
        
    }
    
    private class ChatbotException extends Exception {}
    
    private class OpenPayments {
        List<OpenPayment> TituloAberto;
    }
    
    private class OpenPayment {
        String NUM;
        String CLIENTE;
        String CGC;
        String NUMBCO;
        String PARCELA;
        String PEDIDO;
        String PREFIXO;
        String TIPO;
        String CGC_CD;     
    }
    
}