Git Tests/force-app/main/default/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <externalId>true</externalId>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/FormaPagamento__c.field-meta.xml
<CustomField>
    <fullName>FormaPagamento__c</fullName>
    <label>Forma de pagamento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamento__c/CondicaoPagamento__c.object-meta.xml
<CustomObject>
    <label>Condição de pagamento</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condições de pagamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/AprovadoComercial__c.field-meta.xml
<CustomField>
    <fullName>AprovadoComercial__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Aprovado Comercial?</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/AprovadoPricing__c.field-meta.xml
<CustomField>
    <fullName>AprovadoPricing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Aprovado Pricing?</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CanalEntrada__c.field-meta.xml
<CustomField>
    <fullName>CanalEntrada__c</fullName>
    <label>Canal de entrada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ACSC - Associação Congregação de Santa Catarina</fullName>
            </value>
            <value>
                <fullName>Apoio</fullName>
            </value>
            <value>
                <fullName>Ariba/Amil</fullName>
            </value>
            <value>
                <fullName>Bionexo</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>CONTRATO</fullName>
            </value>
            <value>
                <fullName>E-mail</fullName>
            </value>
            <value>
                <fullName>E-MAIL MARKETING</fullName>
            </value>
            <value>
                <fullName>GERENCIA</fullName>
                <label>GERÊNCIA</label>
            </value>
            <value>
                <fullName>GT Plan</fullName>
            </value>
            <value>
                <fullName>Humma</fullName>
            </value>
            <value>
                <fullName>INPART</fullName>
            </value>
            <value>
                <fullName>Max Cotações</fullName>
            </value>
            <value>
                <fullName>Portal Sintese</fullName>
            </value>
            <value>
                <fullName>Portal GTPLAN</fullName>
            </value>
            <value>
                <fullName>Medical VM</fullName>
            </value>
            <value>
                <fullName>MICROSOFT TEAMS</fullName>
            </value>
            <value>
                <fullName>Movi Tech</fullName>
            </value>
            <value>
                <fullName>MVM RS</fullName>
            </value>
            <value>
                <fullName>NEOGRID</fullName>
            </value>
            <value>
                <fullName>Nimbi</fullName>
            </value>
            <value>
                <fullName>PANFLETO</fullName>
            </value>
            <value>
                <fullName>Paradigma</fullName>
            </value>
            <value>
                <fullName>Plani Max</fullName>
            </value>
            <value>
                <fullName>PORTAL FAEPA</fullName>
            </value>
            <value>
                <fullName>Portal HR</fullName>
            </value>
            <value>
                <fullName>PORTAL MULTICENTRAIS</fullName>
            </value>
            <value>
                <fullName>PORTAL MV SISTEMA</fullName>
            </value>
            <value>
                <fullName>PORTAL SAO MARTINHO</fullName>
            </value>
            <value>
                <fullName>PORTAL SGHCOT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <formula>Account.CNPJ__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CNPJ</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Orcamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/ContatoOrcamento__c.field-meta.xml
<CustomField>
    <fullName>ContatoOrcamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contato do orçamento</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Orcamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/DataVencimento__c.field-meta.xml
<CustomField>
    <fullName>DataVencimento__c</fullName>
    <label>Data de Vencimento</label>
    <type>DateTime</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/EnviarAprovacao__c.field-meta.xml
<CustomField>
    <fullName>EnviarAprovacao__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enviar para aprovação</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/FormaPagamento__c.field-meta.xml
<CustomField>
    <fullName>FormaPagamento__c</fullName>
    <label>Forma de pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Boleto</fullName>
            </value>
            <value>
                <fullName>Depósito</fullName>
            </value>
            <value>
                <fullName>Carteira</fullName>
            </value>
            <value>
                <fullName>Cartão de Credito</fullName>
            </value>
            <value>
                <fullName>Cartão de Debito</fullName>
            </value>
            <value>
                <fullName>Cheque</fullName>
            </value>
            <value>
                <fullName>Dinheiro</fullName>
            </value>
            <value>
                <fullName>Eletrônico</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/IdIntegrator__c.field-meta.xml
<CustomField>
    <fullName>IdIntegrator__c</fullName>
    <externalId>true</externalId>
    <label>Id do Integrador</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/Margem__c.field-meta.xml
<CustomField>
    <fullName>Margem__c</fullName>
    <label>Margem</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/MargemAlvo__c.field-meta.xml
<CustomField>
    <fullName>MargemAlvo__c</fullName>
    <label>Margem alvo</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/NecessitaAprovacaoComercial__c.field-meta.xml
<CustomField>
    <fullName>NecessitaAprovacaoComercial__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Necessita aprovação comercial</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/NecessitaAprovacaoPricing__c.field-meta.xml
<CustomField>
    <fullName>NecessitaAprovacaoPricing__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Necessita aprovação pricing</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/ObservacoesCliente__c.field-meta.xml
<CustomField>
    <fullName>ObservacoesCliente__c</fullName>
    <label>Observações (cliente)</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/PrazoValidade__c.field-meta.xml
<CustomField>
    <fullName>PrazoValidade__c</fullName>
    <label>Prazo de validade (em dias)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/RecallProcesso__c.field-meta.xml
<CustomField>
    <fullName>RecallProcesso__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Recall do processo?</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/RejeicaoProcesso__c.field-meta.xml
<CustomField>
    <fullName>RejeicaoProcesso__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Rejeição do processo?</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <label>Score</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/SolicitacaoAprovada__c.field-meta.xml
<CustomField>
    <fullName>SolicitacaoAprovada__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Solicitação Aprovada</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/TabulacaoN1__c.field-meta.xml
<CustomField>
    <fullName>TabulacaoN1__c</fullName>
    <inlineHelpText>Este campo é um refinamento do valor do campo Status</inlineHelpText>
    <label>Tabulação N1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recusa</fullName>
            </value>
            <value>
                <fullName>Aceite</fullName>
            </value>
            <value>
                <fullName>Improdutiva</fullName>
            </value>
            <value>
                <fullName>Envio Automático</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/recordTypes/OrcamentoPortal.recordType-meta.xml
<RecordType>
    <fullName>OrcamentoPortal</fullName>
    <active>true</active>
    <businessProcess>Portal de Cotações</businessProcess>
    <label>Orçamento do Portal</label>
    <!---->
    <!---->
</RecordType>

Git Tests/force-app/main/default/default/objects/OpportunityTeamMember/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Centro de distribuição</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityTeamMember/fields/TabulacaoN1__c.field-meta.xml
<CustomField>
    <fullName>TabulacaoN1__c</fullName>
    <inlineHelpText>Este campo é um refinamento do valor do campo Status</inlineHelpText>
    <label>Tabulação N1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recusa</fullName>
            </value>
            <value>
                <fullName>Aceite</fullName>
            </value>
            <value>
                <fullName>Improdutiva</fullName>
            </value>
            <value>
                <fullName>Envio Automático</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Pricebook2/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Catálogos de preços</relationshipLabel>
    <relationshipName>CatalogoPreco</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Pricebook2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Score__c/Score__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Score</label>
</CustomObject>

Git Tests/force-app/main/default/default/classes/BudgetDetailTabulacaoControllerTest.cls
@isTest
public with sharing class BudgetDetailTabulacaoControllerTest {
    public static final Id PRICEBOOKID = Test.getStandardPricebookId();
    public static final Id RECORDTYPE_PORTALID = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('OrcamentoPortal').getRecordTypeId();
    @TestSetup
    static void makeData(){

        CondicaoPagamento__c condicaoPagamento1  =  TestUtility.createPaymentCondition();
        condicaoPagamento1.ExternalId__c = '00cp';
        insert condicaoPagamento1;

        Pricebook2 pb2 = TestUtility.createPricebook2();
        pb2.ExternalId__c = 'pb2';
        insert pb2;

        Account account1 = TestUtility.createAccPJ();
        insert account1;

        Contact contact1 = TestUtility.createContactFromCNPJ(account1.CNPJ__c);
        contact1.ExternalId__c = '00contact';
        insert contact1;

        Opportunity opportunity1 = new Opportunity(
            RecordTypeId = RECORDTYPE_PORTALID,
            Pricebook2 = new Pricebook2(ExternalId__c = pb2.ExternalId__c),
            CondicaoPagamento__r = new CondicaoPagamento__c(ExternalId__c = condicaoPagamento1.ExternalId__c),
            Account = new Account(CNPJ__c = account1.CNPJ__c),
            ContatoOrcamento__r = new Contact(ExternalId__c = contact1.ExternalId__c),
            Amount = 219.679262,
            Probability = 10,
            MargemAlvo__c = 100,
            Margem__c = 100,
            PrazoValidade__c = 3,
            Score__c = 100,
            TotalOpportunityQuantity = 22,
            IsPrivate = false,
            IsExcludedFromTerritory2Filter = false,
            Budget_Confirmed__c = false,
            Discovery_Completed__c = false,
            ROI_Analysis_Completed__c = false,
            AprovadoComercial__c = false,
            AprovadoPricing__c = false,
            EnviarAprovacao__c = false,
            RecomendacaoRespondida__c = false,
            NecessitaAprovacaoComercial__c = false,
            NecessitaAprovacaoPricing__c = false,
            RecallProcesso__c = false,
            RejeicaoProcesso__c = false,
            SolicitacaoAprovada__c = false,
            Name = 'OppTest',
            StageName = 'Em digitação',
            CanalEntrada__c = 'Chat',
            FormaPagamento__c = 'Carteira',
            ObservacoesCliente__c = 'Cliente não atende aos fins de semana.',
            TabulacaoN1__c  = 'Aceite',
            IdIntegrator__c = '001',
            CloseDate = Date.newInstance(2021,12,06),
            DataVencimento__c = Date.today()+1
        );
        insert opportunity1;

        OpportunityTeamMember opp1TeamMember = TestUtility.createOpportunityTeamMember(opportunity1);
        insert opp1TeamMember;

    }

    @isTest
    static void GetTabulacaoValuesTest(){
        Opportunity opp = [SELECT Id FROM Opportunity limit 1];

        Test.startTest();
        StandardResponse response =  BudgetDetailTabulacaoController.getTabulacaoValues(opp.Id);
        Test.stopTest();
        //System.assertEquals(true, response.data != null);
    }

    @isTest
    static void GetTabulacaoTeamMemberInOppTest(){
        Opportunity opp = [SELECT Id FROM Opportunity limit 1];

        Test.startTest();
        StandardResponse response =  BudgetDetailTabulacaoController.getTabulacaoTeamMember(opp.Id);
        Test.stopTest();
        //System.assertEquals(true, response.data != null);
    }

    @isTest
    static void GetTabulacaoTeamMemberNotInOppTest(){
        Opportunity opp = [SELECT Id FROM Opportunity limit 1];
        User user = [SELECT Id FROM User WHERE Id != :UserInfo.getUserId() limit 1];
        StandardResponse response = new StandardResponse();
        System.runAs(user){
            Test.startTest();
                response =  BudgetDetailTabulacaoController.getTabulacaoTeamMember(opp.Id);
            Test.stopTest();
        }
        //System.assertEquals(true, response.data != null);
    }

    @isTest
    static void oppDueDateWasUpdatedByPortalFalseTest(){
        Opportunity opp = [SELECT Id, DataVencimento__c FROM Opportunity limit 1];
        Test.startTest();
        Map<String, Boolean> response =  BudgetDetailTabulacaoController.oppDueDateWasUpdatedByPortal(opp.Id);
        Test.stopTest();
        //System.assertEquals(false, response.get('updatedByPortal'));
    }
}