Git Tests/force-app/main/default/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <externalId>true</externalId>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CanalEntrada__c.field-meta.xml
<CustomField>
    <fullName>CanalEntrada__c</fullName>
    <label>Canal de entrada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ACSC - Associação Congregação de Santa Catarina</fullName>
            </value>
            <value>
                <fullName>Apoio</fullName>
            </value>
            <value>
                <fullName>Ariba/Amil</fullName>
            </value>
            <value>
                <fullName>Bionexo</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>CONTRATO</fullName>
            </value>
            <value>
                <fullName>E-mail</fullName>
            </value>
            <value>
                <fullName>E-MAIL MARKETING</fullName>
            </value>
            <value>
                <fullName>GERENCIA</fullName>
                <label>GERÊNCIA</label>
            </value>
            <value>
                <fullName>GT Plan</fullName>
            </value>
            <value>
                <fullName>Humma</fullName>
            </value>
            <value>
                <fullName>INPART</fullName>
            </value>
            <value>
                <fullName>Max Cotações</fullName>
            </value>
            <value>
                <fullName>Portal Sintese</fullName>
            </value>
            <value>
                <fullName>Portal GTPLAN</fullName>
            </value>
            <value>
                <fullName>Medical VM</fullName>
            </value>
            <value>
                <fullName>MICROSOFT TEAMS</fullName>
            </value>
            <value>
                <fullName>Movi Tech</fullName>
            </value>
            <value>
                <fullName>MVM RS</fullName>
            </value>
            <value>
                <fullName>NEOGRID</fullName>
            </value>
            <value>
                <fullName>Nimbi</fullName>
            </value>
            <value>
                <fullName>PANFLETO</fullName>
            </value>
            <value>
                <fullName>Paradigma</fullName>
            </value>
            <value>
                <fullName>Plani Max</fullName>
            </value>
            <value>
                <fullName>PORTAL FAEPA</fullName>
            </value>
            <value>
                <fullName>Portal HR</fullName>
            </value>
            <value>
                <fullName>PORTAL MULTICENTRAIS</fullName>
            </value>
            <value>
                <fullName>PORTAL MV SISTEMA</fullName>
            </value>
            <value>
                <fullName>PORTAL SAO MARTINHO</fullName>
            </value>
            <value>
                <fullName>PORTAL SGHCOT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <formula>Account.CNPJ__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CNPJ</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/DataVencimento__c.field-meta.xml
<CustomField>
    <fullName>DataVencimento__c</fullName>
    <label>Data de Vencimento</label>
    <type>DateTime</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/IdIntegrator__c.field-meta.xml
<CustomField>
    <fullName>IdIntegrator__c</fullName>
    <externalId>true</externalId>
    <label>Id do Integrador</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/NumeroOrcamento__c.field-meta.xml
<CustomField>
    <fullName>NumeroOrcamento__c</fullName>
    <displayFormat>OR-{00000000}</displayFormat>
    <label>Número do orçamento</label>
    <type>AutoNumber</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/QuantidadeItensConfirmados__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeItensConfirmados__c</fullName>
    <label>Quantidade de itens confirmados</label>
    <summaryFilterItems>
        <field>QuoteItem__c.Status__c</field>
        <operation>equals</operation>
        <value>RESGATADO</value>
    </summaryFilterItems>
    <summaryForeignKey>QuoteItem__c.OpportunityId__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/QuantidadeItensRespondidos__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeItensRespondidos__c</fullName>
    <label>Quantidade de Itens Respondidos</label>
    <summaryFilterItems>
        <field>QuoteItem__c.AnsweredQuote__c</field>
        <operation>equals</operation>
        <value>True</value>
    </summaryFilterItems>
    <summaryForeignKey>QuoteItem__c.OpportunityId__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/QuantidadeItensTotal__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeItensTotal__c</fullName>
    <label>Quantidade de Itens Total</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/QuantidaItensNaoResp__c.field-meta.xml
<CustomField>
    <fullName>QuantidaItensNaoResp__c</fullName>
    <label>Quantida de Itens Não Respondidos</label>
    <summaryFilterItems>
        <field>QuoteItem__c.Status__c</field>
        <operation>equals</operation>
        <value>Não Vinculado</value>
    </summaryFilterItems>
    <summaryForeignKey>QuoteItem__c.OpportunityId__c</summaryForeignKey>
    <summaryOperation>count</summaryOperation>
    <type>Summary</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/QuoteType__c.field-meta.xml
<CustomField>
    <fullName>QuoteType__c</fullName>
    <label>Tipo de Cotação</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <inlineHelpText>Vendedor / Vendedor Externo</inlineHelpText>
    <label>Representante VDE</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CanalEntrada__c.field-meta.xml
<CustomField>
    <fullName>CanalEntrada__c</fullName>
    <label>Canal de entrada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ACSC - Associação Congregação de Santa Catarina</fullName>
            </value>
            <value>
                <fullName>Apoio</fullName>
            </value>
            <value>
                <fullName>Ariba/Amil</fullName>
            </value>
            <value>
                <fullName>Bionexo</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>CONTRATO</fullName>
            </value>
            <value>
                <fullName>E-mail</fullName>
            </value>
            <value>
                <fullName>E-MAIL MARKETING</fullName>
            </value>
            <value>
                <fullName>GERENCIA</fullName>
                <label>GERÊNCIA</label>
            </value>
            <value>
                <fullName>GTPLAN</fullName>
            </value>
            <value>
                <fullName>Humma</fullName>
            </value>
            <value>
                <fullName>INPART</fullName>
            </value>
            <value>
                <fullName>Max Cotações</fullName>
            </value>
            <value>
                <fullName>Medical VM</fullName>
            </value>
            <value>
                <fullName>MICROSOFT TEAMS</fullName>
            </value>
            <value>
                <fullName>Movi Tech</fullName>
            </value>
            <value>
                <fullName>MVM RS</fullName>
            </value>
            <value>
                <fullName>NEOGRID</fullName>
            </value>
            <value>
                <fullName>Nimbi</fullName>
            </value>
            <value>
                <fullName>PANFLETO</fullName>
            </value>
            <value>
                <fullName>Paradigma</fullName>
            </value>
            <value>
                <fullName>Plani Max</fullName>
            </value>
            <value>
                <fullName>PORTAL FAEPA</fullName>
            </value>
            <value>
                <fullName>Portal HR</fullName>
            </value>
            <value>
                <fullName>PORTAL MULTICENTRAIS</fullName>
            </value>
            <value>
                <fullName>PORTAL MV SISTEMA</fullName>
            </value>
            <value>
                <fullName>PORTAL SAO MARTINHO</fullName>
            </value>
            <value>
                <fullName>PORTAL SGHCOT</fullName>
            </value>
            <value>
                <fullName>PORTAL SINCONECTA</fullName>
            </value>
            <value>
                <fullName>PORTAL UNIFENAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <formula>Account.CNPJ__c</formula>
    <label>CNPJ</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <description>
        Objeto recebido na integração do portal de cotações (class: IntegrationPortalQuoteIN) e
        utilizado para armazenar as requisições de produtos efetuada pelos clientes,
        assim como a resposta efetuada pelos vendedores.
        Sua estrutura a nível de negócio existe de duas formas:
        1. a nível de item, sendo o item entendido como as informações advindas da integração com a requisição do cliente.
        2. a nível de resposta, sendo a resposta entendida como as informações enviadas do vendedor para o cliente como resposta.
        Esse objeto pode ser visualizado a nível de usuário nas telas de orçamento do tipo portal (Opportunity > RecordType > OrcamentoPortal),
        que é o mestre do relacionamento mestre-detalhe contido nesse objeto.
        O item é enviado ao portal como resposta na integração do portal de cotação (class: IntegrationPortalQuoteOUT).
        E também é enviado quando é efetuado vínculo de produto (class: IntegrationPortalVinculoOUT)
    </description>
    <label>Item da Cotação</label>
    <nameField>
        <label>Nome do Item da Cotação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens da Cotação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/IdCustomer__c.field-meta.xml
<CustomField>
    <fullName>IdCustomer__c</fullName>
    <description>Id do produto cadastrado pelo cliente na integradora, usado para identificar mesmo produto em requisições diferentes, juntamente com o AccountId</description>
    <externalId>true</externalId>
    <label>Id do Cliente</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/IdIntegrator__c.field-meta.xml
<CustomField>
    <fullName>IdIntegrator__c</fullName>
    <description>Id usado para identificar o item advindo da integradora</description>
    <externalId>true</externalId>
    <label>Id do Integrador</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <description>relacionamento mestre detalhe, orçamento, cotação, opportunidade referente ao item.</description>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Itens da Cotação</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>produto vinculado a resposta.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Items da Cotação</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Identificador de condição da resposta, (Responde a pergunta: Em que estapa está a resposta?)</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NÃO IDENTIFICADO</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>IDENTIFICADO</fullName>
            </value>
            <value>
                <fullName>QUALIFICADO</fullName>
            </value>
            <value>
                <fullName>Respondido</fullName>
            </value>
            <value>
                <fullName>Resgatado</fullName>
            </value>
            <value>
                <fullName>Aguardando Integração</fullName>
            </value>
            <value>
                <fullName>Falha na Integração</fullName>
            </value>
            <value>
                <fullName>Não Vinculado</fullName>
                <default>true</default>
                <label>Não Vinculado</label>
            </value>
            <value>
                <fullName>Vinculado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <description>
        Vendedor responsável por dar a resposta, advem da setorização, relacionado a VendedorSuporte__c
        Também chamado de VDS ou VDI
    </description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Vendedor</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ItensOrcamentosPortal</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/Setorizacao__c.object-meta.xml
<CustomObject>
    <label>Setorização</label>
    <nameField>
        <displayFormat>SET-{000000}</displayFormat>
        <label>Número da setorização</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setorizações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <label>CNPJ</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VDE</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Setorizacao</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/BudgetSearchDTO.cls
public without sharing class BudgetSearchDTO {

    public Boolean nullsLast {get{return this.nullsLast == null ? true : this.nullsLast;}set;}

    public Set<Id> listOppId                            { get; set; }
    public List<String> statusSearch                    { get; set; }
    public List<String> canalEntradaSelected            { get; set; }
    public List<String> vendedorSelected                { get; set; }
    public List<String> teamMember                      { get; set; }
    public String quoteIntegratorId                     { get; set; }
    public String quoteType                             { get; set; }
    public String cnpjCliente                           { get; set; }
    public String nomeCliente                           { get; set; }
    public List<String> mesaSelected                    { get; set; }
    public List<String> categoriaSelected               { get; set; }
    public String searchText                            { get; set; }
    public String normText                              { get; set; }
    public Decimal searchNumber                         { get; set; }
    public List<String> ufCliente                       { get; set; }
    public List<String> cidadeCliente                   { get; set; }
    public DateRange vencimentoCotacao                  { get; set; }
    public String produto                               { get; set; }
    public Boolean notAnswered                          { get; set; }
    public Set<Id> answeredQuoteIds                     { get; set; }
    public Boolean expired                              { get; set; }
    public Boolean dateSearch                           { get; set; }
    public Boolean hourSearch                           { get; set; }
    public Boolean minuteSearch                         { get; set; }
    public Map<String,String> lastRecord                { get; set; }
    public String orderBy                               = 'DataVencimento__c';
    public String orderDirection                        = 'DESC';
    public Integer itemsPerPage                         = 20;
    public Integer queryLimit {
        get {
            if(this.queryLimit == null){
                this.queryLimit = this.itemsPerPage;
            }
            return this.queryLimit;
        }
        set;
    }

    public List<SObject> toList(){
        QueryBuilder query = new QueryBuilder('Opportunity')
            .addFields(new List<String>{
                'Id', 
                'Amount', 
                'Account.BillingCity', 
                'Account.BillingState', 
                'Account.CNPJ__c', 
                'Account.Name', 
                'AccountId', 
                'CanalEntrada__c', 
                'CloseDate',
                'CNPJ__c', 
                'CreatedDate',
                'DataVencimento__c',
                'IdIntegrator__c', 
                'Name',
                'QuantidadeItensConfirmados__c',
                'QuantidadeItensRespondidos__c',
                'QuantidaItensNaoResp__c',
                'QuantidadeItensTotal__c',
                'NumeroOrcamento__c',
                //'QuoteType__c',
                'StageName', 
                'TotalOpportunityQuantity'
            })
            .addSubQuery(new QueryBuilder('QuoteItems__r').addFields(new List<String>{'Id', 'Product__c','Vendedor__c','Status__c','IdCustomer__c','TabulacaoN1__c'}))
            .addSubQuery(orderSubQuery())
            .addConditions()
            .add(buildConditions(true))
            .endConditions();
        
            
            System.debug(this.orderBy);
            System.debug(this.orderDirection.equals('DESC')? 'DESC' : 'ASC');
            System.debug(this.nullsLast ? 'LAST' : 'FIRST');
        query.addOrder(new QueryBuilder.Order(this.orderBy, this.orderDirection.equals('DESC')? 'DESC' : 'ASC', this.nullsLast ? 'LAST' : 'FIRST'));
        query.addOrder(new QueryBuilder.Order('Id', 'ASC', this.nullsLast ? 'LAST' : 'FIRST'));
        query.setLimit(this.queryLimit);

        return query.toList();
    }

    public Map<Id, SObject> toMap(){
        return new QueryBuilder('Opportunity')
            .addFields(new List<String>{'Id'})
            .addConditions()
            .add(buildConditions(false))
            .endConditions()
            .toMap();
    }

    public Integer toCount(){
        return new QueryBuilder('Opportunity')
            .addConditions()
            .add(buildConditions(false))
            .endConditions()
            .toCount();
    }
    
    public static BudgetSearchDTO parse(String jsonObj){
        BudgetSearchDTO response;
        System.debug('\n\nRequestBody:: ' + jsonObj);

        try {
            response = (BudgetSearchDTO) JSON.deserialize(jsonObj, BudgetSearchDTO.class);
        } catch(Exception ex) {
            System.debug('\n\nRequestBody:: ' + jsonObj);
            throw ex;
        }
        
        Map<String, String> mapNewValues = new Map<String, String>{
            '\\\\' => '',
            '\\\'' => '\\\\\\\''
        };

        response.statusSearch                       = StringUtils.replaceSpecialCharacters(response.statusSearch, mapNewValues);
        response.canalEntradaSelected               = StringUtils.replaceSpecialCharacters(response.canalEntradaSelected, mapNewValues);
        response.vendedorSelected                   = StringUtils.replaceSpecialCharacters(response.vendedorSelected, mapNewValues);
        response.teamMember                         = StringUtils.replaceSpecialCharacters(response.teamMember, mapNewValues);
        response.quoteIntegratorId                  = StringUtils.replaceSpecialCharacters(response.quoteIntegratorId, mapNewValues);
        response.quoteType                          = StringUtils.replaceSpecialCharacters(response.quoteType, mapNewValues);
        response.cnpjCliente                        = StringUtils.replaceSpecialCharacters(response.cnpjCliente, mapNewValues);
        response.mesaSelected                       = StringUtils.replaceSpecialCharacters(response.mesaSelected, mapNewValues);
        response.categoriaSelected                  = StringUtils.replaceSpecialCharacters(response.categoriaSelected, mapNewValues);
        response.nomeCliente                        = StringUtils.replaceSpecialCharacters(response.nomeCliente, mapNewValues);
        response.ufCliente                          = StringUtils.replaceSpecialCharacters(response.ufCliente, mapNewValues);
        response.cidadeCliente                      = StringUtils.replaceSpecialCharacters(response.cidadeCliente, mapNewValues);
        response.searchText                         = StringUtils.replaceSpecialCharacters(response.searchText, mapNewValues);
        response.normText                           = StringUtils.replaceSpecialCharacters(response.normText, mapNewValues);
        response.produto                            = StringUtils.replaceSpecialCharacters(response.produto, mapNewValues);
        

        if(response.teamMember != null  && !response.teamMember.isEmpty()){
            Integer userIndex = response.teamMember.indexOf('userId');
            if(userIndex != -1){
                response.teamMember.remove(userIndex);
                response.teamMember.add(UserInfo.getUserId());
            }
        }else{
            response.teamMember = null;
        }
        
        response.vendedorSelected = response.vendedorSelected != null && response.vendedorSelected.isEmpty() ? null : response.vendedorSelected;
        response.mesaSelected = response.mesaSelected != null && response.mesaSelected.isEmpty() ? null : response.mesaSelected;


        if(response.statusSearch != null){
            Integer statusIndex = response.statusSearch.indexOf('Encerrado');
            if(statusIndex != -1){
                response.statusSearch.remove(statusIndex);
                response.statusSearch.add('Fechado/Ganho');
                response.statusSearch.add('Fechado/Perdido');
            }

        }

        if(response.searchText != null){

            response.searchNumber = StringUtils.transformToNumber(response.searchText);
            response.dateSearch = StringUtils.isDateDDMMYY(response.searchText);
            response.hourSearch = StringUtils.isDateTimeDDMMYYhh(response.searchText);
            response.minuteSearch = StringUtils.isDateTimeDDMMYYhhmm(response.searchText);
        }

        if(String.isBlank(response.orderBy)){
            response.orderBy = 'DataVencimento__c';
        }

        if(String.isBlank(response.orderDirection)){
            response.orderDirection = 'DESC';
        } else {
            response.orderDirection = response.orderDirection.toUpperCase();
        }

        response.expired = response.expired == true;
        response.notAnswered = response.notAnswered == true;

        return response;
    }

    public QueryBuilder orderSubQuery(){
        return new QueryBuilder('Orders')
            .addFields(new List<String>{'Id', 'Status'})
            .addConditions()
            .add(new QueryBuilder.CompareCondition('RecordType.Name').eq('Pedido pai'))
            .endConditions();
    }

    public QueryBuilder.ComplexCondition buildConditions(Boolean addLimit){
        if(this.listOppId != null && !this.listOppId.isEmpty()){
            QueryBuilder.ComplexCondition result = new QueryBuilder.ComplexCondition();
                
            result.andCondition(
                new QueryBuilder.InCondition('Id').inCollection(queryQuoteItems())
            )
            .andCondition(
                new QueryBuilder.InCondition('Id').ignoreConditionsForNullValues().inCollection(this.listOppId)
            );

            if(addLimit && this.lastRecord != null && !this.lastRecord.isEmpty()){
                String lastValue = this.lastRecord.get('value');
                String lastId = this.lastRecord.get('id');
                String fieldType = SObjectUtils.getFieldType('Opportunity', this.orderBy);
                Boolean isDesc = this.orderDirection.equals('DESC');
                System.debug('lastValue$: '+lastValue);
                System.debug('lastId$: '+lastId);
                QueryBuilder.ComplexCondition ordByLimit = new QueryBuilder.ComplexCondition();
                if(this.nullsLast){
                    if(String.isNotBlank(lastId) && lastValue != null){
                        if(isDesc){
                            ordByLimit.orCondition(new QueryBuilder.CompareCondition(this.orderBy).lt(lastValue, this.orderBy, 'Opportunity'));
                        }else{
                            ordByLimit.orCondition(new QueryBuilder.CompareCondition(this.orderBy).gt(lastValue, this.orderBy, 'Opportunity'));
                        }
                        ordByLimit.orCondition(
                            new QueryBuilder.ComplexCondition()
                            .andCondition(new QueryBuilder.NullCondition(this.orderBy).isNull())
                            .andCondition(new QueryBuilder.CompareCondition('Id').gt(lastId))
                        );
                        ordByLimit.orCondition(
                            new QueryBuilder.ComplexCondition()
                            .andCondition(new QueryBuilder.CompareCondition(this.orderBy).eq(lastValue, this.orderBy, 'Opportunity'))
                            .andCondition(new QueryBuilder.CompareCondition('Id').gt(lastId))
                        );
                    }
                    else if(String.isNotEmpty(lastId)){
                        ordByLimit.andCondition(new QueryBuilder.CompareCondition('Id').gt(lastId));
                        ordByLimit.andCondition(new QueryBuilder.NullCondition(this.orderBy).isNull());
                    }
                    result.andCondition(ordByLimit);
                }
            }
            
            return result;
        }

        QueryBuilder.ComplexCondition result = 
            new QueryBuilder.ComplexCondition()
                .andCondition(
                    new QueryBuilder.LikeCondition('QuoteType__c').ignoreConditionsForNullValues().likeAnyBoth(this.quoteType)
                )
                .andCondition(
                    new QueryBuilder.InCondition('Account.BillingCity').ignoreConditionsForNullValues().inCollection(this.cidadeCliente)
                )
                .andCondition(
                    new QueryBuilder.InCondition('Account.BillingState').ignoreConditionsForNullValues().inCollection(this.ufCliente)
                )
                .andCondition(
                    new QueryBuilder.LikeCondition('Account.Name').ignoreConditionsForNullValues().likeAnyBoth(this.nomeCliente)
                )
                .andCondition(
                    new QueryBuilder.InCondition('StageName').ignoreConditionsForNullValues().inCollection(this.statusSearch)//convertListToSet
                )
                .andCondition(
                    new QueryBuilder.InCondition('CanalEntrada__c').ignoreConditionsForNullValues().inCollection(this.canalEntradaSelected)
                )
                .andCondition(
                    new QueryBuilder.CompareCondition('IdIntegrator__c').ignoreConditionsForNullValues().eq(this.quoteIntegratorId)
                )
                .andCondition(
                    new QueryBuilder.ComplexCondition()
                    .orCondition(new QueryBuilder.LikeCondition('Account.CNPJ__c').ignoreConditionsForNullValues().likeAnyBoth(this.cnpjCliente))
                    .orCondition(new QueryBuilder.LikeCondition('CNPJClienteRecebedor__c').ignoreConditionsForNullValues().likeAnyBoth(this.cnpjCliente))
                );
                
                if(this.notAnswered){
                    result.andCondition(
                        new QueryBuilder.InCondition('Id').notIn(
                            new QueryBuilder('OpportunityTeamMember')
                            .addFields(new List<String>{'OpportunityId'})
                            .addConditions()
                            .add(
                                new QueryBuilder.ComplexCondition()
                                .andCondition(
                                new QueryBuilder.CompareCondition('QuoteIsAnswered__c').ignoreConditionsForNullValues().eq(true))
                                .andCondition(
                                new QueryBuilder.CompareCondition('UserId').ignoreConditionsForNullValues().eq(UserInfo.getUserId()))
                            )
                            .endConditions()
                        )
                    );
                }
                if((this.mesaSelected != null && !this.mesaSelected.isEmpty()) || (this.teamMember != null && !this.teamMember.isEmpty()) || (this.vendedorSelected != null && !this.vendedorSelected.isEmpty())){
                    result.andCondition(
                        new QueryBuilder.InCondition('AccountId')
                        .inCollection(
                            new QueryBuilder('Setorizacao__c')
                                .addFields(new List<String>{'Conta__c'})
                                .addConditions()
                                .add(
                                    new QueryBuilder.ComplexCondition()
                                    .andCondition(new QueryBuilder.InCondition('Mesa__c').ignoreConditionsForNullValues().inCollection(this.mesaSelected))
                                    .andCondition(new QueryBuilder.InCondition('VendedorSuporte__c').ignoreConditionsForNullValues().inCollection(this.teamMember))
                                    .andCondition(new QueryBuilder.InCondition('Vendedor__c').ignoreConditionsForNullValues().inCollection(this.vendedorSelected))
                                )
                                .endConditions()
                            )
                    );
                }


                if(this.mesaSelected != null && !this.mesaSelected.isEmpty()){
                    result.andCondition(
                    new QueryBuilder.InCondition('AccountId')
                    .inCollection(
                        new QueryBuilder('Setorizacao__c')
                            .addFields(new List<String>{'Conta__c'})
                            .addConditions()
                            .add(new QueryBuilder.InCondition('Mesa__c')
                            .inCollection(this.mesaSelected))
                            .endConditions()
                        )
                    );
                }
                

            if(this.vencimentoCotacao != null && this.vencimentoCotacao.isNotEmpty()){
                System.debug('this.vencimentoCotacao:::' + JSON.serializePretty(this.vencimentoCotacao));
                result.andCondition(this.vencimentoCotacao.toQueryBuilderCondition('DataVencimento__c'));
            }else if(this.expired){
                result.andCondition(new QueryBuilder.CompareCondition('DataVencimento__c').lte(Datetime.now()));
            }else{
                result.andCondition(new QueryBuilder.CompareCondition('DataVencimento__c').gte(Datetime.now()));
            }
            if(this.orderBy.toLowerCase() == 'lastvieweddate'){
                result.andCondition(new QueryBuilder.CompareCondition(this.orderBy).gt(Datetime.now().addDays(-15)));
            }

            if(this.searchText != null && this.searchText != '' && this.searchText.length() >= 4){
                if(this.dateSearch != null && this.dateSearch){
                result.andCondition(
                    new QueryBuilder.ComplexCondition()
                    .orCondition(
                        new QueryBuilder.ComplexCondition()
                        .andCondition(new QueryBuilder.CompareCondition('DataVencimento__c').lte(Datetime.parse(this.searchText+' 00:00').addMinutes(-1)+1))
                        .andCondition(new QueryBuilder.CompareCondition('DataVencimento__c').gte(Datetime.parse(this.searchText+' 00:00')))
                    )
                    .orCondition(
                        new QueryBuilder.ComplexCondition()
                        .andCondition(new QueryBuilder.CompareCondition('CreatedDate').gte(Datetime.parse(this.searchText+' 00:00')))
                        .andCondition(new QueryBuilder.CompareCondition('CreatedDate').lte(Datetime.parse(this.searchText+' 00:00').addMinutes(-1)+1)) 
                    )
                );
                }else if(this.hourSearch != null && this.hourSearch){
                    result.andCondition(
                        new QueryBuilder.ComplexCondition()
                        .orCondition(
                            new QueryBuilder.ComplexCondition()
                            .andCondition(new QueryBuilder.CompareCondition('DataVencimento__c').gte(Datetime.parse(this.searchText+':00')))
                            .andCondition(new QueryBuilder.CompareCondition('DataVencimento__c').lte(Datetime.parse(this.searchText+':00').addHours(1).addMinutes(-1)))
                        )
                        .orCondition(
                            new QueryBuilder.ComplexCondition()
                            .andCondition(new QueryBuilder.CompareCondition('CreatedDate').gte(Datetime.parse(this.searchText+':00')))
                            .andCondition(new QueryBuilder.CompareCondition('CreatedDate').lte(Datetime.parse(this.searchText+':00').addHours(1).addMinutes(-1)))     
                        )
                    );
                }else if(this.minuteSearch!= null && this.minuteSearch){
                    result.andCondition(
                        new QueryBuilder.ComplexCondition()
                        .orCondition(
                            new QueryBuilder.ComplexCondition()
                            .andCondition(new QueryBuilder.CompareCondition('DataVencimento__c').gte(Datetime.parse(this.searchText)))
                            .andCondition(new QueryBuilder.CompareCondition('DataVencimento__c').lte(Datetime.parse(this.searchText).addMinutes(1)))
                        )
                        .orCondition(
                            new QueryBuilder.ComplexCondition()
                            .andCondition(new QueryBuilder.CompareCondition('CreatedDate').gte(Datetime.parse(this.searchText)))
                            .andCondition(new QueryBuilder.CompareCondition('CreatedDate').lte(Datetime.parse(this.searchText).addMinutes(1)))
                        )
                    );
                } else{
                    String normTextUP = String.isNotBlank(this.normText) ? this.normText.toUpperCase() : null;
                    QueryBuilder.ComplexCondition complex = new QueryBuilder.ComplexCondition()
                        .orCondition(new QueryBuilder.LikeCondition('StageName').ignoreConditionsForNullValues().likeAnyBoth(this.searchText))
                        .orCondition(new QueryBuilder.LikeCondition('QuoteType__c').ignoreConditionsForNullValues().likeAnyBoth(this.searchText))
                        .orCondition(new QueryBuilder.LikeCondition('QuoteType__c').ignoreConditionsForNullValues().likeAnyBoth(this.normText))
                        .orCondition(new QueryBuilder.LikeCondition('Account.BillingCity').ignoreConditionsForNullValues().likeAnyBoth(normTextUP))
                        .orCondition(new QueryBuilder.LikeCondition('Account.CNPJ__c').ignoreConditionsForNullValues().likeAnyBoth(this.searchText))
                        .orCondition(new QueryBuilder.LikeCondition('Account.Name').ignoreConditionsForNullValues().likeAnyBoth(this.searchText))
                        .orCondition(new QueryBuilder.LikeCondition('Account.Name').ignoreConditionsForNullValues().likeAnyBoth(normTextUP))
                        .orCondition(new QueryBuilder.LikeCondition('CanalEntrada__c').ignoreConditionsForNullValues().likeAnyBoth(this.searchText))
                        .orCondition(new QueryBuilder.LikeCondition('CNPJ__c').ignoreConditionsForNullValues().likeAnyBoth(this.searchText))
                        .orCondition(new QueryBuilder.LikeCondition('IdIntegrator__c').ignoreConditionsForNullValues().likeAnyBoth(this.searchText))
                        .orCondition(new QueryBuilder.LikeCondition('Name').ignoreConditionsForNullValues().likeAnyBoth(this.searchText))
                        .orCondition(new QueryBuilder.LikeCondition('Name').ignoreConditionsForNullValues().likeAnyBoth(normTextUP))
                        .orCondition(new QueryBuilder.LikeCondition('NumeroOrcamento__c').ignoreConditionsForNullValues().likeAnyBoth(this.searchText))
                        .orCondition(new QueryBuilder.LikeCondition('NumeroOrcamento__c').ignoreConditionsForNullValues().likeAnyBoth(normTextUP));
                        
                        if(this.searchNumber != null){
                            complex.orCondition(new QueryBuilder.CompareCondition('Amount').ignoreConditionsForNullValues().eq(this.searchNumber));
                        }
                    result.andCondition(complex);
                }
            }

            if(addLimit && this.lastRecord != null && !this.lastRecord.isEmpty()){
                String lastValue = this.lastRecord.get('value');
                String lastId = this.lastRecord.get('id');
                String fieldType = SObjectUtils.getFieldType('Opportunity', this.orderBy);
                Boolean isDesc = this.orderDirection.equals('DESC');
                System.debug('lastValue$: '+lastValue);
                System.debug('lastId$: '+lastId);
                QueryBuilder.ComplexCondition ordByLimit = new QueryBuilder.ComplexCondition();
                if(this.nullsLast){
                    if(String.isNotBlank(lastId) && lastValue != null){
                        if(isDesc){
                            ordByLimit.orCondition(new QueryBuilder.CompareCondition(this.orderBy).lt(lastValue, this.orderBy, 'Opportunity'));
                        }else{
                            ordByLimit.orCondition(new QueryBuilder.CompareCondition(this.orderBy).gt(lastValue, this.orderBy, 'Opportunity'));
                        }
                        ordByLimit.orCondition(
                            new QueryBuilder.ComplexCondition()
                            .andCondition(new QueryBuilder.NullCondition(this.orderBy).isNull())
                            .andCondition(new QueryBuilder.CompareCondition('Id').gt(lastId))
                        );
                        ordByLimit.orCondition(
                            new QueryBuilder.ComplexCondition()
                            .andCondition(new QueryBuilder.CompareCondition(this.orderBy).eq(lastValue, this.orderBy, 'Opportunity'))
                            .andCondition(new QueryBuilder.CompareCondition('Id').gt(lastId))
                        );
                    }
                    else if(String.isNotEmpty(lastId)){
                        ordByLimit.andCondition(new QueryBuilder.CompareCondition('Id').gt(lastId));
                        ordByLimit.andCondition(new QueryBuilder.NullCondition(this.orderBy).isNull());
                    }
                    result.andCondition(ordByLimit);
                }
            }
        return result;
    }

    public QueryBuilder queryQuoteItems(){
        
        QueryBuilder.ComplexCondition qitemConditions = new QueryBuilder.ComplexCondition()
        .andCondition(
            new QueryBuilder.InCondition('OpportunityId__c').inCollection(this.listOppId)
        );

        if(String.isNotBlank(this.produto)){
            qitemConditions.andCondition(
                new QueryBuilder.ComplexCondition()
                .orCondition(
                    new QueryBuilder.LikeCondition('Product__r.Name').likeAnyBoth(this.produto)
                )
                .orCondition(
                    new QueryBuilder.LikeCondition('Product__r.ProductCode').likeAnyBoth(this.produto)
                )
            );
        }

        if(this.categoriaSelected != null && !this.categoriaSelected.isEmpty()){
            qitemConditions.andCondition(
                new QueryBuilder.InCondition('CategoriaCliente__c').inCollection(this.categoriaSelected)
            );
        }

        QueryBuilder qitemQuery = new QueryBuilder('QuoteItem__c')
            .addFields(new List<String>{'OpportunityId__c'})
            .addConditions().add(qitemConditions).endConditions();
        return qitemQuery;
    }

    public class DateRange {
        public String date1                       { get; set; }
        public String date2                       { get; set; }
        public Boolean yesterday                  { get; set; } 
        public Integer last_n_days                { get; set; }

        public DateRange(Boolean yesterday){
            this.yesterday = yesterday;     
           }

        public QueryBuilder.ComplexCondition toQueryBuilderCondition(String fieldName){
            Date today = System.today();
            
            QueryBuilder.ComplexCondition result = new QueryBuilder.ComplexCondition();
            if(this.date1 != null || this.date2 != null){
                if(this.date1 != null){
                    result.andCondition(new QueryBuilder.CompareCondition(fieldName).gte(this.date1, fieldName, 'Opportunity'));
                }
                if(this.date2 != null){
                    result.andCondition(new QueryBuilder.CompareCondition(fieldName).lte(this.date2, fieldName, 'Opportunity'));
                }
            } else if(this.last_n_days == 0){
                result.andCondition(new QueryBuilder.CompareCondition(fieldName).lte(today-1, fieldName, 'Opportunity'));
                result.andCondition(new QueryBuilder.CompareCondition(fieldName).gte(today, fieldName, 'Opportunity'));
            }else if(this.last_n_days != null){
                result.andCondition(new QueryBuilder.CompareCondition(fieldName).lte(today, fieldName, 'Opportunity'));
                result.andCondition(new QueryBuilder.CompareCondition(fieldName).gte(today-this.last_n_days, fieldName, 'Opportunity'));
            } else if(this.yesterday == true){
                result.andCondition(new QueryBuilder.CompareCondition(fieldName).lte(today, fieldName, 'Opportunity'));
                result.andCondition(new QueryBuilder.CompareCondition(fieldName).gte(today-1, fieldName, 'Opportunity'));
            }
            
            System.debug('result:::' + JSON.serializePretty(result));
            System.debug('ComplexCondition:::' + JSON.serializePretty(this));
            return result;
        }

        public Boolean isNotEmpty(){
            return this.date1 != null || this.date2 != null || this.last_n_days != null || (this.yesterday == true);
        }
    }

}