Git Tests/force-app/main/default/default/objects/Account/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <externalId>true</externalId>
    <label>CNPJ</label>
    <length>14</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/DescontoCliente__c.field-meta.xml
<CustomField>
    <fullName>DescontoCliente__c</fullName>
    <label>Desconto do cliente</label>
    <precision>10</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <formula>Account.CNPJ__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>CNPJ</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/TabulacaoN2__c.field-meta.xml
<CustomField>
    <fullName>TabulacaoN2__c</fullName>
    <inlineHelpText>Este campo é o segundo refinamento do valor do campo Status</inlineHelpText>
    <label>Tabulação N2</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>TabulacaoN1__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cotação Enviada TT</fullName>
            </value>
            <value>
                <fullName>Cotação Enviada Parcial</fullName>
            </value>
            <value>
                <fullName>Fora de Malha</fullName>
            </value>
            <value>
                <fullName>Falta de estoque</fullName>
            </value>
            <value>
                <fullName>Não temos o item no portifólio</fullName>
            </value>
            <value>
                <fullName>Não temos a apresentação solicitada</fullName>
            </value>
            <value>
                <fullName>Não temos a validade solicitada</fullName>
            </value>
            <value>
                <fullName>Não temos a quantidade solicitada</fullName>
            </value>
            <value>
                <fullName>Não trabalhamos</fullName>
            </value>
            <value>
                <fullName>Não conseguimos atender no prazo solicitado</fullName>
            </value>
            <value>
                <fullName>Não atinge o faturamento mínimo</fullName>
            </value>
            <value>
                <fullName>Área Restrita / Regionalização</fullName>
            </value>
            <value>
                <fullName>Bloqueio Financeiro</fullName>
            </value>
            <value>
                <fullName>Cotação Vencida</fullName>
            </value>
            <value>
                <fullName>BU Material</fullName>
            </value>
            <value>
                <fullName>BU Genérico</fullName>
            </value>
            <value>
                <fullName>BU Especialidade</fullName>
            </value>
            <value>
                <fullName>Envio Automático</fullName>
            </value>
            <value>
                <fullName>BLACK LIST</fullName>
                <isActive>false</isActive>
                <label>BLACK LIST</label>
            </value>
            <value>
                <fullName>NÃO É CLIENTE ALVO</fullName>
                <isActive>false</isActive>
                <label>NÃO É CLIENTE ALVO</label>
            </value>
            <value>
                <fullName>Outro Distribuidor</fullName>
                <isActive>false</isActive>
                <label>Outro Distribuidor</label>
            </value>
            <value>
                <fullName>PARCIAL</fullName>
                <isActive>false</isActive>
                <label>PARCIAL</label>
            </value>
            <value>
                <fullName>Preço melhor do concorrente</fullName>
                <isActive>false</isActive>
                <label>Preço melhor do concorrente</label>
            </value>
            <value>
                <fullName>TODOS OS ITENS - NÃO CONSEGUIMOS ATENDER NO PRAZO SOLICITADO</fullName>
                <isActive>false</isActive>
                <label>TODOS OS ITENS - NÃO CONSEGUIMOS ATENDER NO PRAZO SOLICITADO</label>
            </value>
            <value>
                <fullName>TODOS OS ITENS - NÃO TRABALHAMOS</fullName>
                <isActive>false</isActive>
                <label>TODOS OS ITENS - NÃO TRABALHAMOS</label>
            </value>
            <value>
                <fullName>TODOS OS ITENS FORA DE MALHA</fullName>
                <isActive>false</isActive>
                <label>TODOS OS ITENS FORA DE MALHA</label>
            </value>
            <value>
                <fullName>TODOS OS ITENS FORA DO PORTFOLIO</fullName>
                <isActive>false</isActive>
                <label>TODOS OS ITENS FORA DO PORTFOLIO</label>
            </value>
            <value>
                <fullName>TODOS OS ITENS SEM A APRESENTAÇÃO SOLICITADA</fullName>
                <isActive>false</isActive>
                <label>TODOS OS ITENS SEM A APRESENTAÇÃO SOLICITADA</label>
            </value>
            <value>
                <fullName>TODOS OS ITENS SEM A QUANTIDADE SOLICITADA</fullName>
                <isActive>false</isActive>
                <label>TODOS OS ITENS SEM A QUANTIDADE SOLICITADA</label>
            </value>
            <value>
                <fullName>TODOS OS ITENS SEM A VALIDADE SOLICITADA</fullName>
                <isActive>false</isActive>
                <label>TODOS OS ITENS SEM A VALIDADE SOLICITADA</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/classes/SObjectUtilsTest.cls
@IsTest
public with sharing class SObjectUtilsTest {

    
    @TestSetup
    public static void init() {
        // createAccount(1);
        
        // result.Name = 'Account-' + i;
        // result.NumberOfEmployees = 0;
        Account acc = TestUtility.createAccPJ();
        acc.Name = 'Account-1';
        acc.NumberOfEmployees = 0;
        acc.DescontoCliente__c = 2;
        acc.CNPJ__c = '47782743000124';
        acc.ExternalId__c = '47782743000124';
        insert acc;

        Account acc3 = TestUtility.createAccPJ();
        acc3.Name = 'Account-2';
        acc3.NumberOfEmployees = 0;
        acc3.ParentId = acc.Id;
        acc3.DescontoCliente__c = 2;
        acc.CNPJ__c = '34349677000151';
        acc.ExternalId__c = '34349677000151';
        insert acc3;

        Contact contact = TestUtility.createContact(acc.Id);
        insert contact;
        
        Contact contact3 = TestUtility.createContact(acc3.Id);
        contact3.Email = 'teste'+Integer.valueof((Math.random() * 100)) +'@test.com';
        insert contact3;
    }
    @IsTest
    public static void testAllMethods() {


        SObjectUtils obj = new SObjectUtils();
        SObject acc =[SELECT Id, Name FROM Account where name ='Account-1'];
        List<SObject> lstRecords = new List<SObject>{acc};
        Map<Id, SObject> mapObject = new Map<Id, SObject>{acc.id => acc};
        Map<String,String> mapFields = new Map<String,String>{'Id' => acc.id};
        Set<String> fieldNames = new Set<String>{'Name'};
        SObjectUtils.hasChangedFields(acc, mapObject, 'Name');
        SObjectUtils.copyFieldValues(acc, acc, 'Name');
        SObjectUtils.copyFieldValues(acc, acc, 'Name', true);
        SObjectUtils.copyFieldValues(acc, acc, fieldNames);
        SObjectUtils.copyFieldValues(acc, acc, fieldNames, true);
        SObjectUtils.copyFieldValues(acc, acc, fieldNames, true, true);
        SObjectUtils.mapObjectsByField(lstRecords, 'Name');
        SObjectUtils.mapObjectsByField(lstRecords, 'Name', true);
        SObjectUtils.mapObjectsByField(lstRecords, fieldNames);
        SObjectUtils.getLookupIds(lstRecords, 'id', true);
        SObjectUtils.getObjectNameById(acc.id);
        SObjectUtils.hasSObjectField('Name', acc);
        SObjectUtils.getPickListValuesList('Account', 'Rating');
        SObjectUtils.getPickListValuesMap('Account', 'Rating');
        SObjectUtils.getFieldType('Account', 'Name');
        SObjectUtils.copyFieldValues(new Account(), acc, new Map<String,String>{'Name' => 'Name'}, false, true);
        SObjectUtils.validateSObjectType(acc, 'Account');
        SObjectUtils.getDependentPicklistValues('Opportunity','TabulacaoN2__c');
        List<Account> accountListTest = new List<Account>{new Account(Name= 'name')};
        SObjectUtils.filterLists(accountListTest, accountListTest[0]);
        SObjectUtils.filterAttrEq(accountListTest, new List<String>{'Name'}, new List<String>{'name'});
        SObjectUtils.filterAttrEq(accountListTest, 'Name', 'notName');
        SObjectUtils.filterAttrNeq(accountListTest, new List<String>{'Name'}, new List<String>{'name'});
        SObjectUtils.filterAttrNeq(accountListTest, 'Name', 'notName');
    }
}