Git Tests/force-app/main/default/default/objects/Account/fields/CodigoRegiao__c.field-meta.xml
<CustomField>
    <fullName>CodigoRegiao__c</fullName>
    <label>Código da Região</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/recordTypes/PessoaFisica.recordType-meta.xml
<RecordType>
    <fullName>PessoaFisica</fullName>
    <active>true</active>
    <label>Pessoa física</label>
</RecordType>

Git Tests/force-app/main/default/default/objects/Account/recordTypes/PessoaJuridica.recordType-meta.xml
<RecordType>
    <fullName>PessoaJuridica</fullName>
    <active>true</active>
    <label>Pessoa jurídica</label>
</RecordType>

Git Tests/force-app/main/default/default/objects/ProcessActingTable__e/ProcessActingTable__e.object-meta.xml
<CustomObject>
    <label>ProcessActingTable</label>
    <pluralLabel>ProcessActingTables</pluralLabel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ProcessActingTable__e/fields/ExecuteNextProcesses__c.field-meta.xml
<CustomField>
    <fullName>ExecuteNextProcesses__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ExecuteNextProcesses</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProcessActingTable__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo de processo</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/Setorizacao__c.object-meta.xml
<CustomObject>
    <label>Setorização</label>
    <nameField>
        <displayFormat>SET-{000000}</displayFormat>
        <label>Número da setorização</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setorizações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome do cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Setorização</relationshipLabel>
    <relationshipName>Setorizacao</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Regiao__c.field-meta.xml
<CustomField>
    <fullName>Regiao__c</fullName>
    <label>Região</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Territory2/fields/Regiao__c.field-meta.xml
<CustomField>
    <fullName>Regiao__c</fullName>
    <externalId>true</externalId>
    <label>Região</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/BatchAssociateAccountWithoutSetorizacao.cls
public with sharing class BatchAssociateAccountWithoutSetorizacao implements Database.Batchable<SObject> {
    
    
    public Boolean callNextProcess = false;
    public Set<String> setRecorType = new Set<String>{'PessoaFisica', 'PessoaJuridica'};
    
    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([
            SELECT 
                Id, 
                CodigoRegiao__c 
                FROM Account 
                WHERE RecordType.DeveloperName IN:setRecorType 
                AND Id NOT IN (SELECT Conta__c FROM Setorizacao__c)
        ]);
    }

    public void execute(Database.BatchableContext BC, List<Account> scope) {
     
        Set<String> setCodigoRegiao = new Set<String>();
        Map<String,List<Account>> mapAccxRegiao = new Map<String,List<Account>>();
        List<ObjectTerritory2Association> associationsToCreate = new List<ObjectTerritory2Association>();

        for (Account acc : scope) {

            if (acc.CodigoRegiao__c != null) {
                
                setCodigoRegiao.add(acc.CodigoRegiao__c);

                if (!mapAccxRegiao.containsKey(acc.CodigoRegiao__c)) {                    
                    mapAccxRegiao.put(acc.CodigoRegiao__c, new List<Account>{acc});

                }else{
                    mapAccxRegiao.get(acc.CodigoRegiao__c).add(acc);
                }
            }
          
        }

        if (setCodigoRegiao.size() > 0) {

            List<Territory2> lstTerritory2 = [SELECT Id,Regiao__c FROM Territory2 WHERE Regiao__c IN: setCodigoRegiao];
          
            if (lstTerritory2.size() > 0) {

                for (Territory2 territory : lstTerritory2) {

                    if (mapAccxRegiao.containsKey(territory.Regiao__c)) {
                        
                        for(Account acc : mapAccxRegiao.get(territory.Regiao__c)){
                            ObjectTerritory2Association accAssociation = new ObjectTerritory2Association(
                                Territory2Id = territory.Id,
                                ObjectId = acc.Id,
                                AssociationCause = 'Territory2Manual'
                            );
                            associationsToCreate.add(accAssociation);
                        }                        
                        
                    }                    
                }
                
            }
            
        }
        
        System.debug(associationsToCreate.size());
        if (associationsToCreate.size() > 0) {
            System.debug(associationsToCreate);
            Database.insert(associationsToCreate, false);
        }
    }

    public void finish(Database.BatchableContext BC) {
        if (callNextProcess) {
            Eventbus.publish(new ProcessActingTable__e(
                Type__c = 'revalidate_approval_associations',
                ExecuteNextProcesses__c = true
            ));
        }
    }

}