Git Tests/force-app/main/default/default/objects/Account/fields/CodigoCliente__c.field-meta.xml
<CustomField>
    <fullName>CodigoCliente__c</fullName>
    <label>Código do cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/CodigoGrupoClientes__c.field-meta.xml
<CustomField>
    <fullName>CodigoGrupoClientes__c</fullName>
    <label>Código do grupo de clientes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/GrupoCliente__c.field-meta.xml
<CustomField>
    <fullName>GrupoCliente__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Grupo de clientes</label>
    <referenceTo>GrupoCliente__c</referenceTo>
    <relationshipLabel>Clientes</relationshipLabel>
    <relationshipName>Clientes</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/GrupoCliente__c/GrupoCliente__c.object-meta.xml
<CustomObject>
    <label>Grupo de clientes</label>
    <nameField>
        <label>Nome de grupo de clientes</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos de cliente</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Pricebook2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/PricebookEntry/fields/PrecoFabrica__c.field-meta.xml
<CustomField>
    <fullName>PrecoFabrica__c</fullName>
    <label>Preço de fábrica</label>
    <precision>12</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/CategoriaComercial__c.field-meta.xml
<CustomField>
    <fullName>CategoriaComercial__c</fullName>
    <label>Categoria comercial</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>G</fullName>
                <label>GENÉRICO</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>MATERIAIS</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>NUTRIÇÃO</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Medctech</label>
            </value>
            <value>
                <fullName>R</fullName>
                <label>REFERÊNCIA</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>AMBOS</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>DIABETES</label>
            </value>
            <value>
                <fullName>Q</fullName>
                <label>ODONTOLOGIA</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>Especialidade</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <label>EQUIPAMENTO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do produto</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/FatorConversao__c.field-meta.xml
<CustomField>
    <fullName>FatorConversao__c</fullName>
    <label>Fator de conversão</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/UnidadeMedida__c.field-meta.xml
<CustomField>
    <fullName>UnidadeMedida__c</fullName>
    <label>Unidade de medida</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/ProductSearchControllerTest.cls
@IsTest
public with sharing class ProductSearchControllerTest {

    @IsTest
    public static void testgetLookupRecords() {
        try {
            Pricebook2 pricebook = new Pricebook2(
                Name = 'Pricebook Test',
                ExternalId__c = 'B01'
            );
            insert pricebook;
    
            Product2 product = TestUtility.createProduct();
            product.FatorConversao__c = '1';
            product.CategoriaComercial__c = 'teste';
            product.Description = 'teste';
            product.Name = 'teste';
            product.UnidadeMedida__c = 'un';
            product.ProductCode = 'teste';
            insert product;
    
            PricebookEntry pricebookEntry = TestUtility.createPricebookEntry(pricebook.Id, product.Id);
            pricebookEntry.PrecoFabrica__c = 123;
            pricebookEntry.ExternalId__c = 'teste';
            pricebookEntry.UnitPrice = 123;
            insert pricebookEntry;
    
            Account account = TestUtility.createAccPJ();
            account.CodigoCliente__c = '0168444';
            account.CodigoGrupoClientes__c = '000001';
            insert account;
    
            Opportunity opportunity = new Opportunity(
                Name = 'Opportunity Test',
                StageName = 'Novo',
                CloseDate = Date.today().addDays(10),
                AccountId = account.Id,
                Pricebook2Id = pricebook.Id
            );
            insert opportunity;
    
    
            Test.startTest();
    
                String[] fieldNames = new String[]{'Name', 'BillingCity'};
                String[] lookupSelectFields = new String[]{'GrupoCliente__c', 'BillingCity'};
                pricebookEntry.Product2 = product;
                ProductSearchController.Product prod = new ProductSearchController.Product(pricebookEntry, 12);
                
                ProductSearchController.getLookupRecords('Lectrum', opportunity.Id);
            Test.stopTest();
        } catch(Exception e) {
            System.debug(e);
        }
        
    }

    
}