Git Tests/force-app/main/default/default/objects/Account/fields/CodigoCliente__c.field-meta.xml
<CustomField>
    <fullName>CodigoCliente__c</fullName>
    <label>Código do cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/CodigoGrupoClientes__c.field-meta.xml
<CustomField>
    <fullName>CodigoGrupoClientes__c</fullName>
    <label>Código do grupo de clientes</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>TextArea</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/Saldo__c.field-meta.xml
<CustomField>
    <fullName>Saldo__c</fullName>
    <formula>LimiteCredito__c  -  IF(ISBLANK(Titulos__c), 0, VALUE(Titulos__c))</formula>
    <inlineHelpText>Limite de crédito - Títulos</inlineHelpText>
    <label>Saldo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Estoque__c/Estoque__c.object-meta.xml
<CustomObject>
    <label>Estoque</label>
    <nameField>
        <label>Número do estoque</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estoques</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Estoque__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do estoque</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Estoque__c/fields/NomeProduto__c.field-meta.xml
<CustomField>
    <fullName>NomeProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome do produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Estoques</relationshipLabel>
    <relationshipName>Estoques</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Estoque__c/fields/Saldo__c.field-meta.xml
<CustomField>
    <fullName>Saldo__c</fullName>
    <label>Saldo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Fornecedor__c/Fornecedor__c.object-meta.xml
<CustomObject>
    <label>Fornecedor</label>
    <nameField>
        <label>Nome do fornecedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fornecedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Fornecedor__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do fornecedor</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/GeneralParameters__c/GeneralParameters__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Parâmetros gerais.</description>
    <label>Parâmetros gerais</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/GeneralParameters__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <defaultValue>&apos;tatiana.santos@grupoelfa.com.br&apos;</defaultValue>
    <description>Email de compras</description>
    <inlineHelpText>Email de compras</inlineHelpText>
    <label>Email de compras</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/GeneralParameters__c/fields/StockNotification__c.field-meta.xml
<CustomField>
    <fullName>StockNotification__c</fullName>
    <defaultValue>4</defaultValue>
    <label>Notificação entrada de estoque</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Chave única: Número do pedido + Código do CD</description>
    <externalId>true</externalId>
    <label>Código do pedido TOTVS</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Número do item do pedido</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <formula>Product2.Fornecedor__r.Name</formula>
    <label>Fornecedor</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/ItemPendente__c.field-meta.xml
<CustomField>
    <fullName>ItemPendente__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Item pendente</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/QuantidadeUn__c.field-meta.xml
<CustomField>
    <fullName>QuantidadeUn__c</fullName>
    <inlineHelpText>Secundário: Segunda unidade de medida do produto</inlineHelpText>
    <label>Quantidade (Secundário)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/ValorCx__c.field-meta.xml
<CustomField>
    <fullName>ValorCx__c</fullName>
    <inlineHelpText>Principal: Unidade de medida principal do produto</inlineHelpText>
    <label>Valor (Principal)</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/ValorUn__c.field-meta.xml
<CustomField>
    <fullName>ValorUn__c</fullName>
    <inlineHelpText>Secundário: Segunda unidade de medida do produto</inlineHelpText>
    <label>Valor (Secundário)</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Pricebook2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do produto</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/FatorConversao__c.field-meta.xml
<CustomField>
    <fullName>FatorConversao__c</fullName>
    <label>Fator de conversão</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fornecedor</label>
    <referenceTo>Fornecedor__c</referenceTo>
    <relationshipLabel>Produtos</relationshipLabel>
    <relationshipName>Produtos</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/EstoqueHelperTest.cls
@isTest
public with sharing class EstoqueHelperTest {
    @isTest
    public static void EstoqueHelperTest() {
        
        GeneralParameters__c parameters = new GeneralParameters__c();
        parameters.Name = 'Parametro geral';
        parameters.Email__c = 'thomas.anderson@nescara.com';
        parameters.StockNotification__c = 4;
        insert parameters;
        
        Fornecedor__c provider = new Fornecedor__c(
            Name = 'Provider Test'
        );
        insert provider;

        Account account = TestUtility.createAccPJ();
        account.CodigoCliente__c = '0168444';
        account.CodigoGrupoClientes__c = '000001';
        insert account;

        Pricebook2 pricebook = new Pricebook2(
            Name = 'Pricebook Test',
            ExternalId__c = 'B01'
        );
        insert pricebook;
        
        Order order = TestUtility.createOrder(account);
        order.Pricebook2Id = pricebook.Id;
        order.Status = 'Em digitação';
        insert order;
        
        Product2 product = TestUtility.createProduct();
        product.FatorConversao__c = '1';
        product.Fornecedor__c = provider.Id;
        product.Description = 'Lectrum';
        product.ProductCode = '55801';
        product.IsActive = true;
        insert product;

        PricebookEntry pricebookEntry = TestUtility.createPricebookEntry(pricebook.Id, product.Id);
        insert pricebookEntry;

        OrderItem orderItem = new OrderItem(
            OrderId = order.Id,
            Product2Id = product.Id,
            pricebookEntryId = pricebookEntry.Id,
            UnitPrice = 100,
            Quantity = 10,
            ValorUn__c = 10,
            QuantidadeUn__c = 10,
            ValorCx__c = 10,
            ItemPendente__c = true
        );
        insert orderItem;

        Estoque__c inventory = new Estoque__c(
            NomeProduto__c = product.Id,
            Saldo__c = 5
        );
        insert inventory;

        inventory.Saldo__c = 10;
        update inventory;

        inventory = [SELECT Id, Saldo__c FROM Estoque__c LIMIT 1];
        System.assertEquals(inventory.Saldo__c, 10);
    }
}