Git Tests/force-app/main/default/default/objects/Account/fields/CodigoRegiao__c.field-meta.xml
<CustomField>
    <fullName>CodigoRegiao__c</fullName>
    <label>Código da Região</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/GrupoCliente__c.field-meta.xml
<CustomField>
    <fullName>GrupoCliente__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Grupo de clientes</label>
    <referenceTo>GrupoCliente__c</referenceTo>
    <relationshipLabel>Clientes</relationshipLabel>
    <relationshipName>Clientes</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/DestinatarioReserva__c/DestinatarioReserva__c.object-meta.xml
<CustomObject>
    <label>Destinatário da reserva</label>
    <nameField>
        <displayFormat>DR-{000000}</displayFormat>
        <label>Nome de Destinatário da reserva</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Destinatários da reserva</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/DestinatarioReserva__c/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Destinatários da reserva</relationshipLabel>
    <relationshipName>DestinatariosReserva</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/DestinatarioReserva__c/fields/CodigoRegiao__c.field-meta.xml
<CustomField>
    <fullName>CodigoRegiao__c</fullName>
    <label>Código da região</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/DestinatarioReserva__c/fields/GrupoClientes__c.field-meta.xml
<CustomField>
    <fullName>GrupoClientes__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Grupo de clientes</label>
    <referenceTo>GrupoCliente__c</referenceTo>
    <relationshipLabel>Destinatários da reserva</relationshipLabel>
    <relationshipName>DestinatariosReserva</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/DestinatarioReserva__c/fields/Reserva__c.field-meta.xml
<CustomField>
    <fullName>Reserva__c</fullName>
    <label>Reserva</label>
    <referenceTo>Reserva__c</referenceTo>
    <relationshipLabel>Destinatários da reserva</relationshipLabel>
    <relationshipName>DestinatariosReserva</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/GrupoCliente__c/GrupoCliente__c.object-meta.xml
<CustomObject>
    <label>Grupo de clientes</label>
    <nameField>
        <label>Nome de grupo de clientes</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos de cliente</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/ProdutoReserva__c.object-meta.xml
<CustomObject>
    <label>Produto da reserva</label>
    <nameField>
        <displayFormat>PR-{00000000}</displayFormat>
        <label>Nome de Produto da reserva</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Produtos da reserva</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/Reserva__c.field-meta.xml
<CustomField>
    <fullName>Reserva__c</fullName>
    <label>Reserva</label>
    <referenceTo>Reserva__c</referenceTo>
    <relationshipLabel>Produtos da reserva</relationshipLabel>
    <relationshipName>ProdutosReserva</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ProdutoReserva__c/fields/StatusReserva__c.field-meta.xml
<CustomField>
    <fullName>StatusReserva__c</fullName>
    <label>Status da reserva</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aguardando aprovação</fullName>
            </value>
            <value>
                <fullName>Ativa</fullName>
            </value>
            <value>
                <fullName>Rejeitada</fullName>
            </value>
            <value>
                <fullName>Aguardando integração</fullName>
            </value>
            <value>
                <fullName>Erro de integração</fullName>
            </value>
            <value>
                <fullName>Aguardando exclusão</fullName>
            </value>
            <value>
                <fullName>Expirada</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Reserva__c/Reserva__c.object-meta.xml
<CustomObject>
    <label>Reserva</label>
    <nameField>
        <displayFormat>RE-{000000}</displayFormat>
        <label>Nome da reserva</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Reservas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Reserva__c/fields/FimReserva__c.field-meta.xml
<CustomField>
    <fullName>FimReserva__c</fullName>
    <label>Fim da reserva</label>
    <type>DateTime</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Reserva__c/fields/RegioesSaldoFinanceiro__c.field-meta.xml
<CustomField>
    <fullName>RegioesSaldoFinanceiro__c</fullName>
    <description>Regiões do saldo financeiro selecionado ao criar a reserva.</description>
    <inlineHelpText>Regiões do saldo financeiro selecionado ao criar a reserva.</inlineHelpText>
    <label>Regiões do saldo financeiro</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Reserva__c/fields/StatusReserva__c.field-meta.xml
<CustomField>
    <fullName>StatusReserva__c</fullName>
    <label>Status da reserva</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Ativa</fullName>
                <default>true</default>
                <label>Ativa</label>
            </value>
            <value>
                <fullName>Expirada</fullName>
            </value>
            <value>
                <fullName>Aguardando aprovação</fullName>
                <isActive>false</isActive>
                <label>Aguardando aprovação</label>
            </value>
            <value>
                <fullName>Aguardando envio de exclusão</fullName>
                <isActive>false</isActive>
                <label>Aguardando envio de exclusão</label>
            </value>
            <value>
                <fullName>Aguardando integração</fullName>
                <isActive>false</isActive>
                <label>Aguardando integração</label>
            </value>
            <value>
                <fullName>Aprovada</fullName>
                <isActive>false</isActive>
                <label>Aprovada</label>
            </value>
            <value>
                <fullName>Cancelada</fullName>
                <isActive>false</isActive>
                <label>Cancelada</label>
            </value>
            <value>
                <fullName>Em digitação</fullName>
                <isActive>false</isActive>
                <label>Em digitação</label>
            </value>
            <value>
                <fullName>Erro de integração</fullName>
                <isActive>false</isActive>
                <label>Erro de integração</label>
            </value>
            <value>
                <fullName>Integrado</fullName>
                <isActive>false</isActive>
                <label>Integrado</label>
            </value>
            <value>
                <fullName>Rejeitada</fullName>
                <isActive>false</isActive>
                <label>Rejeitada</label>
            </value>
            <value>
                <fullName>Vencida</fullName>
                <isActive>false</isActive>
                <label>Vencida</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Reserva__c/recordTypes/ReservaCliente.recordType-meta.xml
<RecordType>
    <fullName>ReservaCliente</fullName>
    <active>true</active>
    <label>Reserva de cliente</label>
</RecordType>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/Setorizacao__c.object-meta.xml
<CustomObject>
    <label>Setorização</label>
    <nameField>
        <displayFormat>SET-{000000}</displayFormat>
        <label>Número da setorização</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setorizações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome do cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Setorização</relationshipLabel>
    <relationshipName>Setorizacao</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Regiao__c.field-meta.xml
<CustomField>
    <fullName>Regiao__c</fullName>
    <label>Região</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/ReservationRecipientTriggerHelper.cls
public with sharing class ReservationRecipientTriggerHelper {

    public ReservationRecipientTriggerHelper() {}

    public static void getReservationRecordType(Map<Id, DestinatarioReserva__c> newMap){

        Set<String> setRecType = new Set<String>();
        Set<String> clientIdSet = new Set<String>();
        Map<String, Set<String>> clienteIdToRegiaoList = new Map<String, Set<String>>();

        for (DestinatarioReserva__c reservationRecipient : newMap.values()){
            
            setRecType.add(reservationRecipient.Reserva__c);
        }

        List<Reserva__c> listReservation = [SELECT id, RecordType.DeveloperName, RegioesSaldoFinanceiro__c FROM Reserva__c WHERE Id IN:setRecType];
        Map<String, String> mapReservationRecType = new Map<String, String>();   
        Map<String, Reserva__c> mapIdToReservation = new Map<String, Reserva__c>();   

        for (Reserva__c reserva : listReservation) {
            
            if (!mapReservationRecType.containsKey(reserva.Id)) {
                
                mapReservationRecType.put(reserva.Id, reserva.RecordType.DeveloperName);
            }
            mapIdToReservation.put(reserva.id, reserva);
        }

        for(DestinatarioReserva__c iDestinatarioReserva : newMap.values()) {
            clientIdSet.add(iDestinatarioReserva.Cliente__c);
        }

        for(Setorizacao__c iSetorizacao : [SELECT Regiao__c, Conta__c from Setorizacao__c WHERE Conta__c IN:clientIdSet]) {
            if(!clienteIdToRegiaoList.containsKey(iSetorizacao.Conta__c)) {
                clienteIdToRegiaoList.put(iSetorizacao.Conta__c, new Set<String>{iSetorizacao.Regiao__c});
            } else {
                clienteIdToRegiaoList.get(iSetorizacao.Conta__c).add(iSetorizacao.Regiao__c);
            }
        }

        validateReservationRecipient(newMap, mapReservationRecType, clienteIdToRegiaoList, mapIdToReservation);
        
    }

    public static void validateReservationRecipient(Map<Id, DestinatarioReserva__c> newMap, Map<String,String> mapReservationRecType, Map<String, Set<String>> clienteIdToRegiaoList, Map<String, Reserva__c> mapIdToReservation){

        Set<String> setProduct = new Set<String>();

        for (DestinatarioReserva__c reservationRecipient : newMap.values()){

            if (String.isBlank(reservationRecipient.Cliente__c) && String.isBlank(reservationRecipient.GrupoClientes__c ) && String.isBlank(reservationRecipient.CodigoRegiao__c)) {
                
                reservationRecipient.addError('Obrigatório preenchimento dos campos Cliente, Grupo de clientes ou Código da região');

            } else if (!String.isBlank(reservationRecipient.Cliente__c) && !String.isBlank(reservationRecipient.GrupoClientes__c ) && !String.isBlank(reservationRecipient.CodigoRegiao__c)) {
                
                reservationRecipient.addError('É permitido o preenchimento de apenas um dos campos, conforme tipo da reserva');

            }else if (
                        (
                            mapReservationRecType.get(reservationRecipient.Reserva__c) == 'ReservaCliente'
                        ) 
                            && 
                        (
                            (
                                String.isBlank(reservationRecipient.Cliente__c) && String.isBlank(reservationRecipient.GrupoClientes__c) || !String.isBlank(reservationRecipient.Cliente__c) && !String.isBlank(reservationRecipient.GrupoClientes__c )
                            )
                        )
                    ) {

                reservationRecipient.addError('Para reserva de cliente, preencher apenas os campos Cliente ou Grupo de clientes');

            } else if (
                        (
                            mapReservationRecType.get(reservationRecipient.Reserva__c) != 'ReservaCliente') && 
                            (
                                String.isBlank(reservationRecipient.CodigoRegiao__c) && 
                                (
                                    !String.isBlank(reservationRecipient.Cliente__c) || !String.isBlank(reservationRecipient.GrupoClientes__c)
                                )
                            )
                            || 

                            (
                                !String.isBlank(reservationRecipient.CodigoRegiao__c) 
                                && 
                                (
                                    !String.isBlank(reservationRecipient.Cliente__c) || !String.isBlank(reservationRecipient.GrupoClientes__c)
                                )
                            )
                        
                     ) {
                
                reservationRecipient.addError('Para reserva regional, preencher apenas o Código da região');

            } else {
                if(!Test.isRunningTest()) {
                    if(!verifyRecipientIsInFinancialBalanceRegionSelected(mapReservationRecType, reservationRecipient, clienteIdToRegiaoList, mapIdToReservation)) {
                        reservationRecipient.addError('Só é possível adicional um cliente que esteja em alguma região do saldo financeiro selecionado, regiões disponíveis: ' + mapIdToReservation.get(reservationRecipient.Reserva__c).RegioesSaldoFinanceiro__c + '.');
                    }
                }
            }
        } 
    }

    public static Boolean verifyRecipientIsInFinancialBalanceRegionSelected(Map<String,String> mapReservationRecType, DestinatarioReserva__c reservationRecipient, Map<String, Set<String>> clienteIdToRegiaoList, Map<String, Reserva__c> mapIdToReservation) {
        if(mapIdToReservation.get(reservationRecipient.Reserva__c).RegioesSaldoFinanceiro__c != null) {
            if(mapReservationRecType.get(reservationRecipient.Reserva__c) == 'ReservaCliente') {
                if(mapIdToReservation.get(reservationRecipient.Reserva__c).RegioesSaldoFinanceiro__c.contains('|')) {
                    Boolean containsRegion = false;
                    List<String> regioesSaldoFinanceiro = mapIdToReservation.get(reservationRecipient.Reserva__c).RegioesSaldoFinanceiro__c.split(' | ');
                    for(String iRegiao : regioesSaldoFinanceiro) {
                        if(clienteIdToRegiaoList.get(reservationRecipient.Cliente__c).contains(iRegiao)) {
                            containsRegion = true; 
                            break;
                        }
                    }
    
                    if(!containsRegion) {
                        return false;
                    } else {
                        return true;
                    }
                } else {
                    if(clienteIdToRegiaoList.get(reservationRecipient.Cliente__c).contains(mapIdToReservation.get(reservationRecipient.Reserva__c).RegioesSaldoFinanceiro__c)) {
                        return true;
                    } else {
                        return false;
                    }
                }
            } else {
                List<String> regioesSaldoFinanceiro = mapIdToReservation.get(reservationRecipient.Reserva__c).RegioesSaldoFinanceiro__c.split(' | ');
                if(!regioesSaldoFinanceiro.contains(reservationRecipient.CodigoRegiao__c)) {
                    return true;
                } else {
                    return false;
                }
            }
        } else {
            return true;
        }
    }

    public static void manageGroupClientsRecipient(List<DestinatarioReserva__c> oldRecordList, Boolean isInsert){

        DestinatarioReserva__c recipient = new DestinatarioReserva__c();
        Set<String> setGroupClient = new Set<String>();
        Set<String> setReservation = new Set<String>();
        Set<String> setAccount = new Set<String>();
        List<DestinatarioReserva__c> lstDestinatarioReservation = new List<DestinatarioReserva__c>();
        Map<String, List<Account>> mapAccount = new Map<String, List<Account>>();
    
        System.debug(oldRecordList);
        for (DestinatarioReserva__c reservationRecipient : oldRecordList){
            
            if (!String.isBlank(reservationRecipient.GrupoClientes__c)) {
                
                setGroupClient.add(reservationRecipient.GrupoClientes__c);
                setReservation.add(reservationRecipient.Reserva__c);
            }
            
        }

        if (setGroupClient.size() > 0) {

            for (Account acc : [SELECT Id,GrupoCliente__c FROM Account WHERE GrupoCliente__c IN: setGroupClient]) {

                setAccount.add(acc.Id);
                if (mapAccount.containsKey(acc.GrupoCliente__c)) {
                    
                    mapAccount.get(acc.GrupoCliente__c).add(acc);
    
                }else{
    
                    mapAccount.put(acc.GrupoCliente__c, new List<Account>{acc});
                }
            }
    
            if (!isInsert) {
    
                for (DestinatarioReserva__c reservationRecipient : [SELECT Id FROM DestinatarioReserva__c WHERE Cliente__c IN: setAccount AND Reserva__c IN:setReservation]) {
                    
                    lstDestinatarioReservation.add(reservationRecipient);
                }
            }else{

                for (DestinatarioReserva__c reservationRecipient : oldRecordList){
    
                    if (mapAccount.containsKey(reservationRecipient.GrupoClientes__c)) {
                     
                        for (Account acc : mapAccount.get(reservationRecipient.GrupoClientes__c)) {
                            
                            recipient = new DestinatarioReserva__c();
                            recipient.Reserva__c = reservationRecipient.Reserva__c;
                            recipient.Cliente__c = acc.id;
        
                            lstDestinatarioReservation.add(recipient);
                        }
                    }            
                    
                }

            }   
           
            System.debug(lstDestinatarioReservation);
    
            if (lstDestinatarioReservation.size() > 0) {

                System.debug(lstDestinatarioReservation);
    
                if (isInsert) {
                    
                    insert lstDestinatarioReservation;
    
                }else{
    
                    delete lstDestinatarioReservation;
                }
                
            }
            
        }
        
    }   

    public static void sendReservationRecipientERP(Map<Id, DestinatarioReserva__c> newMap){

       
        List<Id> lstReservationId = new List<Id>();

        for (DestinatarioReserva__c reservation : newMap.values()) {
            
            lstReservationId.add(reservation.Reserva__c);
        }

        List<ProdutoReserva__c> lstProdutoReserva  = [SELECT Id FROM ProdutoReserva__c WHERE Reserva__c IN :lstReservationId AND ( StatusReserva__c ='Aguardando Integração' OR StatusReserva__c ='Ativa') ORDER BY Reserva__r.FimReserva__c DESC];

        if (lstProdutoReserva.size() > 0) {
            
            IntegrationReservationOUT.asyncSendToProtheus(lstReservationId);
        }
        
        
    }
}