Git Tests/force-app/main/default/default/objects/Account/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/GrupoCliente__c.field-meta.xml
<CustomField>
    <fullName>GrupoCliente__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Grupo de clientes</label>
    <referenceTo>GrupoCliente__c</referenceTo>
    <relationshipLabel>Clientes</relationshipLabel>
    <relationshipName>Clientes</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Campaign/fields/Cliente__c.field-meta.xml
<CustomField>
    <fullName>Cliente__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Campanhas</relationshipLabel>
    <relationshipName>Campanhas</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Campaign/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Campaign/fields/CodigoCD__c.field-meta.xml
<CustomField>
    <fullName>CodigoCD__c</fullName>
    <label>Código de CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Campaign/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <label>Condição de pagamento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Campaign/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código da campanha</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Campaign/fields/FimRecorrencia__c.field-meta.xml
<CustomField>
    <fullName>FimRecorrencia__c</fullName>
    <label>Fim da recorrência</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Campaign/fields/GrupoCliente__c.field-meta.xml
<CustomField>
    <fullName>GrupoCliente__c</fullName>
    <label>Grupo de cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Campaign/fields/InicioRecorrencia__c.field-meta.xml
<CustomField>
    <fullName>InicioRecorrencia__c</fullName>
    <label>Início da recorrência</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Campaign/fields/RegrasCampanha__c.field-meta.xml
<CustomField>
    <fullName>RegrasCampanha__c</fullName>
    <label>Regras da campanha</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Campaign/fields/Validade__c.field-meta.xml
<CustomField>
    <fullName>Validade__c</fullName>
    <label>Validade</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Segunda</fullName>
            </value>
            <value>
                <fullName>Terça</fullName>
            </value>
            <value>
                <fullName>Quarta</fullName>
            </value>
            <value>
                <fullName>Quinta</fullName>
            </value>
            <value>
                <fullName>Sexta</fullName>
            </value>
            <value>
                <fullName>Sábado</fullName>
            </value>
            <value>
                <fullName>Domingo</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Campaign/recordTypes/Campanha.recordType-meta.xml
<RecordType>
    <fullName>Campanha</fullName>
    <active>true</active>
    <description>Tipo de registro utilizado para campanhas de produtos</description>
    <label>Campanha de produto</label>
</RecordType>

Git Tests/force-app/main/default/default/objects/Campaign/recordTypes/CampanhaVendedor.recordType-meta.xml
<RecordType>
    <fullName>CampanhaVendedor</fullName>
    <active>true</active>
    <description>Tipo de registro utilizado para campanhas (precificação/desconto para vendedor)</description>
    <label>Campanha de vendedor</label>
</RecordType>

Git Tests/force-app/main/default/default/objects/Campaign/recordTypes/ContratoShelfLife.recordType-meta.xml
<RecordType>
    <fullName>ContratoShelfLife</fullName>
    <active>true</active>
    <description>Tipo de registro utilizado para campanhas do tipo Shelf Life.</description>
    <label>Campanha de shelf life</label>
</RecordType>

Git Tests/force-app/main/default/default/objects/CondicaoPagamento__c/CondicaoPagamento__c.object-meta.xml
<CustomObject>
    <label>Condição de pagamento</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condições de pagamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/GrupoCliente__c/GrupoCliente__c.object-meta.xml
<CustomObject>
    <label>Grupo de clientes</label>
    <nameField>
        <label>Nome de grupo de clientes</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos de cliente</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/GrupoCliente__c/fields/CodigoGrupo__c.field-meta.xml
<CustomField>
    <fullName>CodigoGrupo__c</fullName>
    <externalId>true</externalId>
    <label>Código do grupo</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/ItemCampanha__c.object-meta.xml
<CustomObject>
    <label>Item da campanha</label>
    <nameField>
        <label>Código do item de campanha</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens da campanha</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/Campanha__c.field-meta.xml
<CustomField>
    <fullName>Campanha__c</fullName>
    <label>Campanha</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipName>ItemCampanha</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/Desconto__c.field-meta.xml
<CustomField>
    <fullName>Desconto__c</fullName>
    <label>Desconto (%)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do item de campanha</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/Lote__c.field-meta.xml
<CustomField>
    <fullName>Lote__c</fullName>
    <label>Lote</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/NomeProduto__c.field-meta.xml
<CustomField>
    <fullName>NomeProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome do produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>ItemCampanha</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/PrecoMinimo__c.field-meta.xml
<CustomField>
    <fullName>PrecoMinimo__c</fullName>
    <label>Preço mínimo</label>
    <precision>12</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/PrecoUnitario__c.field-meta.xml
<CustomField>
    <fullName>PrecoUnitario__c</fullName>
    <label>Preço unitário</label>
    <precision>12</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/TipoGatilho__c.field-meta.xml
<CustomField>
    <fullName>TipoGatilho__c</fullName>
    <label>Tipo de gatilho</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FLD</fullName>
            </value>
            <value>
                <fullName>Volume</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/Validade__c.field-meta.xml
<CustomField>
    <fullName>Validade__c</fullName>
    <label>Validade</label>
    <type>Date</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/VigenciaFinal__c.field-meta.xml
<CustomField>
    <fullName>VigenciaFinal__c</fullName>
    <label>Vigência final</label>
    <type>Date</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/VigenciaInicial__c.field-meta.xml
<CustomField>
    <fullName>VigenciaInicial__c</fullName>
    <label>Vigência inicial</label>
    <type>Date</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CentroDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentroDistribuicao__c</fullName>
    <label>Centro de distribuição</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Chave única: Número do pedido + Código do CD</description>
    <externalId>true</externalId>
    <label>Código do pedido TOTVS</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/Score__c.field-meta.xml
<CustomField>
    <fullName>Score__c</fullName>
    <label>Score</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/CentroDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentroDistribuicao__c</fullName>
    <label>Centro de distribuição</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/Desconto__c.field-meta.xml
<CustomField>
    <fullName>Desconto__c</fullName>
    <label>Desconto</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Número do item do pedido</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/ItemCampanha__c.field-meta.xml
<CustomField>
    <fullName>ItemCampanha__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item da campanha</label>
    <referenceTo>ItemCampanha__c</referenceTo>
    <relationshipLabel>Produtos do pedido</relationshipLabel>
    <relationshipName>ProdutosPedido</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/Lote__c.field-meta.xml
<CustomField>
    <fullName>Lote__c</fullName>
    <label>Lote</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/ScoreItem__c.field-meta.xml
<CustomField>
    <fullName>ScoreItem__c</fullName>
    <label>Score do item</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/ValorCx__c.field-meta.xml
<CustomField>
    <fullName>ValorCx__c</fullName>
    <inlineHelpText>Principal: Unidade de medida principal do produto</inlineHelpText>
    <label>Valor (Principal)</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do produto</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Score__c/Score__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>Score</label>
</CustomObject>

Git Tests/force-app/main/default/default/classes/ProductCampaignController.cls
public with sharing class ProductCampaignController {

    @AuraEnabled
    public static List<OrderScreenController.ProductData> getProductCampaign(String pricebook, String clienteId, String offSetValue, String searchGenericValue, String searchFabricanteValue, String condPag) {
        system.debug('getProductCampaign');
        List<String> listProdCode = new List<String>();

        Set<String> setCodCampanha = new Set<String>();
        Set<Id> setGroupId = new Set<Id>();
        Set<Id> setAccountId = new Set<Id>();
        Map<Id, String> mapCodCampaignToIdCampaign = new Map<Id, String>();

        fillProdCampaignInfo(setCodCampanha, setGroupId, setAccountId, mapCodCampaignToIdCampaign, condPag);

        system.debug('setCodCampanha: ' + setCodCampanha);
        system.debug('setGroupId: ' + setGroupId);
        system.debug('setAccountId: ' + setAccountId);
        system.debug('mapCodCampaignToIdCampaign: ' + mapCodCampaignToIdCampaign);

        for (ItemCampanha__c campanha : [SELECT Id , NomeProduto__c, NomeProduto__r.ProductCode, PrecoUnitario__c, PrecoMinimo__c, Campanha__r.RecordType.DeveloperName, TipoGatilho__c, VigenciaFinal__c, CNPJCD__c, Campanha__r.EndDate, Lote__c, Campanha__r.Validade__c,
                                Campanha__r.InicioRecorrencia__c, Campanha__r.FimRecorrencia__c, Campanha__r.CondicaoPagamento__c, Campanha__r.Type, Campanha__r.CNPJCD__c, Desconto__c, Campanha__r.CodigoCD__c, Campanha__r.RegrasCampanha__c
                                FROM ItemCampanha__c 
                                WHERE Campanha__r.RecordType.DeveloperName IN ('ContratoShelfLife','Campanha', 'CampanhaVendedor')
                                AND ((Campanha__r.StartDate <= TODAY AND Campanha__r.EndDate >= TODAY)
                                OR (VigenciaInicial__c <= TODAY AND VigenciaFinal__c >= TODAY))
                                ORDER BY Campanha__r.RecordType.DeveloperName DESC]) {
            system.debug('campanha: ' + campanha);
            if(campanha.Campanha__r.RecordType.DeveloperName == 'ContratoShelfLife'){
                listProdCode.add(campanha.NomeProduto__c);
            }
            if(campanha.Campanha__r.RecordType.DeveloperName == 'Campanha'){
                listProdCode.add(campanha.NomeProduto__c);
            }
            if(campanha.Campanha__r.RecordType.DeveloperName == 'CampanhaVendedor'){
                listProdCode.add(campanha.NomeProduto__c);
            }

        }

        system.debug(listProdCode);

        List<OrderScreenController.ProductData> listProd = OrderScreenController.getProduct(pricebook, clienteId, offSetValue, searchGenericValue, searchFabricanteValue, condPag, true, listProdCode).productDataList;

        List<OrderScreenController.ProductData> listProdCampaign = new List<OrderScreenController.ProductData>();

        system.debug('listProd: ' + listProd);

        for (OrderScreenController.ProductData prod : listProd) {
            system.debug('prod: ' + prod);
            if (prod != null) {
                system.debug('prod.showBadgeCampanha: ' + prod.showBadgeCampanha);
                system.debug('prod.showBadgeCampanhaVendedor: ' + prod.showBadgeCampanhaVendedor);
                system.debug('prod.showBadgeshelflife: ' + prod.showBadgeshelflife);
                prod.showBadgeCampanha         = prod.showBadgeCampanha == null ? false : prod.showBadgeCampanha;
                prod.showBadgeCampanhaVendedor = prod.showBadgeCampanhaVendedor == null ? false : prod.showBadgeCampanhaVendedor;
                prod.showBadgeshelflife        = prod.showBadgeshelflife == null ? false : prod.showBadgeshelflife;
                if (prod.showBadgeCampanha || prod.showBadgeCampanhaVendedor || prod.showBadgeshelflife) {
                    listProdCampaign.add(prod);
                }
            }
        }
        
        for (OrderScreenController.ProductData prod: listProdCampaign) {
            system.debug(prod.nome);
            system.debug(prod.principioAtivo);
        }
        system.debug('listProdCampaign: ' + listProdCampaign);
        return listProdCampaign;
    }

    public static void fillProdCampaignInfo(Set<String> setCodCampanha, Set<Id> setGroupId, Set<Id> setAccountId, Map<Id, String> mapCodCampaignToIdCampaign, String condPag) {
        for (Campaign camp: [SELECT GrupoCliente__c, Cliente__c FROM Campaign WHERE RecordType.DeveloperName = 'Campanha' AND GrupoCliente__c != null]) {
            setCodCampanha.add(camp.GrupoCliente__c);
            if (camp.Cliente__c != null) {
                setAccountId.add(camp.Cliente__c);
            }
        }
        for (CondicaoPagamento__c condPagamento : [SELECT Id, ExternalId__c FROM CondicaoPagamento__c WHERE Id =: condPag]) {
            if (condPagamento.ExternalId__c != null) {
                mapCodCampaignToIdCampaign.put(condPagamento.Id, condPagamento.ExternalId__c);
            }
        }
        if (!setCodCampanha.isEmpty()) {
            for (GrupoCliente__c gpCli : [SELECT Id, Name, CodigoGrupo__c FROM GrupoCliente__c WHERE CodigoGrupo__c IN: setCodCampanha]) {
                system.debug(gpCli.Name);
                setGroupId.add(gpCli.Id);
            }
            for (Account acc : [SELECT Id FROM Account WHERE GrupoCliente__c IN: setGroupId]) {
                system.debug(acc.Id);
                setAccountId.add(acc.Id);
            }
        }
    }

    @AuraEnabled(cacheable=true)
    public static List<MixClientController.OrderData> getClientOrderData(String accId, String prodId) {

        List<MixClientController.OrderData> ordDataList = new List<MixClientController.OrderData>();
        for (OrderItem ordItem : [SELECT Id, Quantity, ValorCx__c, OrderId, ScoreItem__c, Order.Score__c, Order.OrderNumber, CentroDistribuicao__c , FORMAT(Order.CreatedDate), Order.EffectiveDate FROM OrderItem WHERE Product2Id =: prodId AND Order.AccountId =:accId /*AND (Order.Status = 'Faturado' OR Order.Status = 'Faturado (Histórico)')*/ Order by Order.EffectiveDate DESC LIMIT 30000]) {
            ordDataList.add(new MixClientController.OrderData(ordItem));
        }
        return ordDataList;
    }

}