Git Tests/force-app/main/default/default/objects/Account/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/CondicaoPagamentoPorCD__c.object-meta.xml
<CustomObject>
    <label>Condição de pagamento por CD</label>
    <nameField>
        <label>Nome de Condição de pagamento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condições de pagamentos por CD</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/CentroDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentroDistribuicao__c</fullName>
    <label>Centro de distribuição</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/CloseDate__c.field-meta.xml
<CustomField>
    <fullName>CloseDate__c</fullName>
    <label>Data de validade</label>
    <type>Date</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Condição de Pagamento CD</relationshipLabel>
    <relationshipName>CondicoesPagamento</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/CondicaoPagamentoPL__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamentoPL__c</fullName>
    <label>Condição de Pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Integradora__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>002/28 D</fullName>
            </value>
            <value>
                <fullName>003/30 D</fullName>
            </value>
            <value>
                <fullName>004/45 D</fullName>
            </value>
            <value>
                <fullName>042/60 D</fullName>
            </value>
            <value>
                <fullName>012/30,45,60 D</fullName>
            </value>
            <value>
                <fullName>028/35 D</fullName>
            </value>
            <value>
                <fullName>058/56 D</fullName>
            </value>
            <value>
                <fullName>046/45,60 D</fullName>
            </value>
            <value>
                <fullName>013/30,60 D</fullName>
            </value>
            <value>
                <fullName>036/21 D</fullName>
            </value>
            <value>
                <fullName>115/20 D</fullName>
            </value>
            <value>
                <fullName>065/25 D</fullName>
            </value>
            <value>
                <fullName>007/28,35 D</fullName>
            </value>
            <value>
                <fullName>008/28,35,42 D</fullName>
            </value>
            <value>
                <fullName>010/28,35,42,49,56</fullName>
            </value>
            <value>
                <fullName>081/28,42 D</fullName>
            </value>
            <value>
                <fullName>011/30,45 D</fullName>
            </value>
            <value>
                <fullName>049/14 DIAS</fullName>
            </value>
            <value>
                <fullName>066/10 D</fullName>
            </value>
            <value>
                <fullName>045/120 D</fullName>
            </value>
            <value>
                <fullName>006/90 D</fullName>
            </value>
            <value>
                <fullName>043/A VISTA</fullName>
            </value>
            <value>
                <fullName>001/30 D - 5,15,25</fullName>
            </value>
            <value>
                <fullName>003</fullName>
            </value>
            <value>
                <fullName>004</fullName>
            </value>
            <value>
                <fullName>005</fullName>
            </value>
            <value>
                <fullName>005/49 D</fullName>
            </value>
            <value>
                <fullName>006</fullName>
            </value>
            <value>
                <fullName>009/28,35,42,49 D</fullName>
            </value>
            <value>
                <fullName>014/30,60,90 D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/FretePicklist__c.field-meta.xml
<CustomField>
    <fullName>FretePicklist__c</fullName>
    <label>Tipo de Frete</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CIF</fullName>
                <default>true</default>
                <label>CIF</label>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/Integradora__c.field-meta.xml
<CustomField>
    <fullName>Integradora__c</fullName>
    <label>Integradora</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bionexo</fullName>
            </value>
            <value>
                <fullName>Apoio</fullName>
            </value>
            <value>
                <fullName>Sintese</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/MinimumBilling__c.field-meta.xml
<CustomField>
    <fullName>MinimumBilling__c</fullName>
    <label>Faturamento Mínimo</label>
    <precision>16</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CentroDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentroDistribuicao__c</fullName>
    <label>Centro de Distribuição</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Orcamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/ExternalPortal__c.field-meta.xml
<CustomField>
    <fullName>ExternalPortal__c</fullName>
    <externalId>true</externalId>
    <label>ExternalPortal</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/FretePicklist__c.field-meta.xml
<CustomField>
    <fullName>FretePicklist__c</fullName>
    <label>Tipo de Frete</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/IdPortal__c.field-meta.xml
<CustomField>
    <fullName>IdPortal__c</fullName>
    <externalId>true</externalId>
    <label>Id Portal</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/Integradora__c.field-meta.xml
<CustomField>
    <fullName>Integradora__c</fullName>
    <label>Integradora</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/StatusIntegracaoPortalCotacoes__c.field-meta.xml
<CustomField>
    <fullName>StatusIntegracaoPortalCotacoes__c</fullName>
    <label>Status de Integração (Portal)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não Integrado</fullName>
                <default>true</default>
                <label>Não Integrado</label>
            </value>
            <value>
                <fullName>Falha na Integração</fullName>
            </value>
            <value>
                <fullName>Integrado</fullName>
            </value>
            <value>
                <fullName>Recebendo dados</fullName>
            </value>
            <value>
                <fullName>Recebida</fullName>
            </value>
            <value>
                <fullName>Integrada</fullName>
                <isActive>false</isActive>
                <label>Integrada</label>
            </value>
            <value>
                <fullName>Não Integrada</fullName>
                <isActive>false</isActive>
                <label>Não Integrada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/CentroDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentroDistribuicao__c</fullName>
    <label>Centro de distribuição</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/IdPortal__c.field-meta.xml
<CustomField>
    <fullName>IdPortal__c</fullName>
    <description>Id do item no Portal de Cotações.</description>
    <externalId>true</externalId>
    <label>Id do Portal</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/QuantidadePortal__c.field-meta.xml
<CustomField>
    <fullName>QuantidadePortal__c</fullName>
    <inlineHelpText>Quantidade Portal</inlineHelpText>
    <label>Quantidade Portal</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/ValorPortal__c.field-meta.xml
<CustomField>
    <fullName>ValorPortal__c</fullName>
    <inlineHelpText>Valor Portal</inlineHelpText>
    <label>Valor Portal</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Pricebook2/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Catálogos de preços</relationshipLabel>
    <relationshipName>CatalogoPreco</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <description>
        Objeto recebido na integração do portal de cotações (class: IntegrationPortalQuoteIN) e
        utilizado para armazenar as requisições de produtos efetuada pelos clientes,
        assim como a resposta efetuada pelos vendedores.
        Sua estrutura a nível de negócio existe de duas formas:
        1. a nível de item, sendo o item entendido como as informações advindas da integração com a requisição do cliente.
        2. a nível de resposta, sendo a resposta entendida como as informações enviadas do vendedor para o cliente como resposta.
        Esse objeto pode ser visualizado a nível de usuário nas telas de orçamento do tipo portal (Opportunity > RecordType > OrcamentoPortal),
        que é o mestre do relacionamento mestre-detalhe contido nesse objeto.
        O item é enviado ao portal como resposta na integração do portal de cotação (class: IntegrationPortalQuoteOUT).
        E também é enviado quando é efetuado vínculo de produto (class: IntegrationPortalVinculoOUT)
    </description>
    <label>Item da Cotação</label>
    <nameField>
        <label>Nome do Item da Cotação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens da Cotação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <description>Campo usado para itentificar a categoria do vendedor responsável (advém de setorizacao__c)</description>
    <label>Categoria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <description>Cnpj do centro de distribuição vinculado</description>
    <label>CNPJ do CD</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/IdPortal__c.field-meta.xml
<CustomField>
    <fullName>IdPortal__c</fullName>
    <description>Id do item no Portal de Cotações (hash), não vem da integradora, é criado para cada item dentro do portal.</description>
    <externalId>true</externalId>
    <label>Id do Portal</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/OpportunityLineItem__c.field-meta.xml
<CustomField>
    <fullName>OpportunityLineItem__c</fullName>
    <description>
        Quando existe oferta para o QuoteItem__c em questão é criado um OpportunityLineItem com as informações do QuoteItem__c
        Esse item que foi criado fica relacionado por meio desse campo.
    </description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto de oportunidade</label>
    <referenceTo>OpportunityLineItem</referenceTo>
    <relationshipLabel>Items da Cotação</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>produto vinculado a resposta.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Items da Cotação</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/ConditionPaymentBudgetControllerTest.cls
@isTest
public class ConditionPaymentBudgetControllerTest {

    @TestSetup
    static void makeData(){
        Account acc = TestUtility.createAccount();
        insert acc;

        Contact contact = TestUtility.createContact(acc.Id);
        insert contact;

        CondicaoPagamento__c condPag = TestUtility.createPaymentCondition();
        insert condPag;
        
        Pricebook2 pb = TestUtility.createPricebook2();
        insert pb;

        Opportunity opp = TestUtility.createOpportunity(acc, contact, condPag);
        opp.ExternalPortal__c = '786876876';
        opp.StatusIntegracaoPortalCotacoes__c = 'Integrado';
        opp.Pricebook2Id = pb.Id;
        insert opp;

        Id pricebookId = Test.getStandardPricebookId();
        
        Product2 prod = TestUtility.createProduct();
        prod.Name = 'prod1';
        insert prod;

        Product2 prod2 = TestUtility.createProduct();
        prod2.Name = 'prod2';
        insert prod2;
        

        PricebookEntry pbEntry = TestUtility.createPricebookEntry(pb.Id,prod.Id);
        insert pbEntry;

        
        OpportunityLineItem oppLineItem = TestUtility.createOpportunityLineItem(opp, prod2, pbEntry);
        oppLineItem.CNPJCD__c = '18269125000187';
        oppLineItem.ValorPortal__c = 2;
        oppLineItem.QuantidadePortal__c = 2;
        insert oppLineItem;

        QuoteItem__c qItem = TestUtility.createQuoteItem(opp);
        qItem.IdPortal__c = '012131231';
        qItem.Categoria__c = 'categTest';
        qItem.Product__c = prod.Id;
        qItem.CNPJCD__c = '18269125000187';
        qItem.OpportunityLineItem__c = oppLineItem.Id;
        insert qItem;

        CondicaoPagamentoPorCD__c conPagCD = new CondicaoPagamentoPorCD__c(
            CentroDistribuicao__c = 'ABC',
            CloseDate__c = System.today(),
            CNPJCD__c = '18269125000187',
            CondicaoPagamentoPL__c = '043/A VISTA',
            Integradora__c = 'Bionexo',
            CondicaoPagamento__c = condPag.Id,
            FretePicklist__c = 'CIF',
            MinimumBilling__c = 1,
            ObservacoesLongText__c = 'a',
            PrazoEntrega__c = 1,
            PrazoValidade__c = 1,
            Orcamento__c = opp.Id
        );
        insert conPagCD;
    }

    @isTest
    static void test_getConditionPayment(){
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        ConditionPaymentBudgetController.getConditionPayment(opp.Id);
    }
}