Git Tests/force-app/main/default/default/objects/Account/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CanalEntrada__c.field-meta.xml
<CustomField>
    <fullName>CanalEntrada__c</fullName>
    <label>Canal de entrada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ACSC - Associação Congregação de Santa Catarina</fullName>
            </value>
            <value>
                <fullName>Apoio</fullName>
            </value>
            <value>
                <fullName>Ariba/Amil</fullName>
            </value>
            <value>
                <fullName>Bionexo</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>CONTRATO</fullName>
            </value>
            <value>
                <fullName>E-mail</fullName>
            </value>
            <value>
                <fullName>E-MAIL MARKETING</fullName>
            </value>
            <value>
                <fullName>GERENCIA</fullName>
                <label>GERÊNCIA</label>
            </value>
            <value>
                <fullName>GT Plan</fullName>
            </value>
            <value>
                <fullName>Humma</fullName>
            </value>
            <value>
                <fullName>INPART</fullName>
            </value>
            <value>
                <fullName>Max Cotações</fullName>
            </value>
            <value>
                <fullName>Portal Sintese</fullName>
            </value>
            <value>
                <fullName>Portal GTPLAN</fullName>
            </value>
            <value>
                <fullName>Medical VM</fullName>
            </value>
            <value>
                <fullName>MICROSOFT TEAMS</fullName>
            </value>
            <value>
                <fullName>Movi Tech</fullName>
            </value>
            <value>
                <fullName>MVM RS</fullName>
            </value>
            <value>
                <fullName>NEOGRID</fullName>
            </value>
            <value>
                <fullName>Nimbi</fullName>
            </value>
            <value>
                <fullName>PANFLETO</fullName>
            </value>
            <value>
                <fullName>Paradigma</fullName>
            </value>
            <value>
                <fullName>Plani Max</fullName>
            </value>
            <value>
                <fullName>PORTAL FAEPA</fullName>
            </value>
            <value>
                <fullName>Portal HR</fullName>
            </value>
            <value>
                <fullName>PORTAL MULTICENTRAIS</fullName>
            </value>
            <value>
                <fullName>PORTAL MV SISTEMA</fullName>
            </value>
            <value>
                <fullName>PORTAL SAO MARTINHO</fullName>
            </value>
            <value>
                <fullName>PORTAL SGHCOT</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Orcamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/DataVencimento__c.field-meta.xml
<CustomField>
    <fullName>DataVencimento__c</fullName>
    <label>Data de Vencimento</label>
    <type>DateTime</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/ExternalPortal__c.field-meta.xml
<CustomField>
    <fullName>ExternalPortal__c</fullName>
    <externalId>true</externalId>
    <label>ExternalPortal</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/IdPortal__c.field-meta.xml
<CustomField>
    <fullName>IdPortal__c</fullName>
    <externalId>true</externalId>
    <label>Id Portal</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/StatusIntegracaoPortalCotacoes__c.field-meta.xml
<CustomField>
    <fullName>StatusIntegracaoPortalCotacoes__c</fullName>
    <label>Status de Integração (Portal)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não Integrado</fullName>
                <default>true</default>
                <label>Não Integrado</label>
            </value>
            <value>
                <fullName>Falha na Integração</fullName>
            </value>
            <value>
                <fullName>Integrado</fullName>
            </value>
            <value>
                <fullName>Recebendo dados</fullName>
            </value>
            <value>
                <fullName>Recebida</fullName>
            </value>
            <value>
                <fullName>Integrada</fullName>
                <isActive>false</isActive>
                <label>Integrada</label>
            </value>
            <value>
                <fullName>Não Integrada</fullName>
                <isActive>false</isActive>
                <label>Não Integrada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/VendedorSuporte__c.field-meta.xml
<CustomField>
    <fullName>VendedorSuporte__c</fullName>
    <inlineHelpText>Vendedor Interno / Vendedor Suporte</inlineHelpText>
    <label>Representante VDI/VDS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityTeamMember/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Centro de distribuição</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CanalEntrada__c.field-meta.xml
<CustomField>
    <fullName>CanalEntrada__c</fullName>
    <label>Canal de entrada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>ACSC - Associação Congregação de Santa Catarina</fullName>
            </value>
            <value>
                <fullName>Apoio</fullName>
            </value>
            <value>
                <fullName>Ariba/Amil</fullName>
            </value>
            <value>
                <fullName>Bionexo</fullName>
            </value>
            <value>
                <fullName>Chat</fullName>
            </value>
            <value>
                <fullName>CONTRATO</fullName>
            </value>
            <value>
                <fullName>E-mail</fullName>
            </value>
            <value>
                <fullName>E-MAIL MARKETING</fullName>
            </value>
            <value>
                <fullName>GERENCIA</fullName>
                <label>GERÊNCIA</label>
            </value>
            <value>
                <fullName>GTPLAN</fullName>
            </value>
            <value>
                <fullName>Humma</fullName>
            </value>
            <value>
                <fullName>INPART</fullName>
            </value>
            <value>
                <fullName>Max Cotações</fullName>
            </value>
            <value>
                <fullName>Medical VM</fullName>
            </value>
            <value>
                <fullName>MICROSOFT TEAMS</fullName>
            </value>
            <value>
                <fullName>Movi Tech</fullName>
            </value>
            <value>
                <fullName>MVM RS</fullName>
            </value>
            <value>
                <fullName>NEOGRID</fullName>
            </value>
            <value>
                <fullName>Nimbi</fullName>
            </value>
            <value>
                <fullName>PANFLETO</fullName>
            </value>
            <value>
                <fullName>Paradigma</fullName>
            </value>
            <value>
                <fullName>Plani Max</fullName>
            </value>
            <value>
                <fullName>PORTAL FAEPA</fullName>
            </value>
            <value>
                <fullName>Portal HR</fullName>
            </value>
            <value>
                <fullName>PORTAL MULTICENTRAIS</fullName>
            </value>
            <value>
                <fullName>PORTAL MV SISTEMA</fullName>
            </value>
            <value>
                <fullName>PORTAL SAO MARTINHO</fullName>
            </value>
            <value>
                <fullName>PORTAL SGHCOT</fullName>
            </value>
            <value>
                <fullName>PORTAL SINCONECTA</fullName>
            </value>
            <value>
                <fullName>PORTAL UNIFENAS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Chave única: Número do pedido + Código do CD</description>
    <externalId>true</externalId>
    <label>Código do pedido TOTVS</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ExternalPortal__c.field-meta.xml
<CustomField>
    <fullName>ExternalPortal__c</fullName>
    <externalId>true</externalId>
    <label>ExternalPortal</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <description>
        Objeto recebido na integração do portal de cotações (class: IntegrationPortalQuoteIN) e
        utilizado para armazenar as requisições de produtos efetuada pelos clientes,
        assim como a resposta efetuada pelos vendedores.
        Sua estrutura a nível de negócio existe de duas formas:
        1. a nível de item, sendo o item entendido como as informações advindas da integração com a requisição do cliente.
        2. a nível de resposta, sendo a resposta entendida como as informações enviadas do vendedor para o cliente como resposta.
        Esse objeto pode ser visualizado a nível de usuário nas telas de orçamento do tipo portal (Opportunity > RecordType > OrcamentoPortal),
        que é o mestre do relacionamento mestre-detalhe contido nesse objeto.
        O item é enviado ao portal como resposta na integração do portal de cotação (class: IntegrationPortalQuoteOUT).
        E também é enviado quando é efetuado vínculo de produto (class: IntegrationPortalVinculoOUT)
    </description>
    <label>Item da Cotação</label>
    <nameField>
        <label>Nome do Item da Cotação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens da Cotação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <description>Campo usado para itentificar a categoria do vendedor responsável (advém de setorizacao__c)</description>
    <label>Categoria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>OpportunityId__r.ExternalPortal__c + _ + IdPotal__c + _ + Vendedor__c + _ + Categoria__c</description>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Chave Externa</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/Setorizacao__c.object-meta.xml
<CustomObject>
    <label>Setorização</label>
    <nameField>
        <displayFormat>SET-{000000}</displayFormat>
        <label>Número da setorização</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setorizações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>BU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>G</fullName>
                <label>GENÉRICO</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>MATERIAIS</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>NUTRIÇÃO</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Medctech</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>SPECIALTY</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>AMBOS</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>DIABETES</label>
            </value>
            <value>
                <fullName>Q</fullName>
                <label>ODONTOLOGIA</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <label>EQUIPAMENTO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/VendedorSuporte__c.field-meta.xml
<CustomField>
    <fullName>VendedorSuporte__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VDI</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SetorizacoesVendedor</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/SalesmanNotificationPortalTest.cls
@isTest
public class SalesmanNotificationPortalTest {
    @TestSetup
    static void makeData(){
        Account acc = TestUtility.createAccount();
        insert acc;

        Setorizacao__c setor = TestUtility.createSetorizacaoWithValidData(acc, new User(Id = UserInfo.getUserId()));
        setor.Categoria__c = 'M';
        setor.VendedorSuporte__c = UserInfo.getUserId();
        insert setor;

        Contact contact = TestUtility.createContact(acc.Id);
        insert contact;

        CondicaoPagamento__c condPag = TestUtility.createPaymentCondition2();
        insert condPag;

        Opportunity opp = TestUtility.createOpportunity(acc, contact, condPag);
        opp.CanalEntrada__c = 'Bionexo';
        opp.DataVencimento__c = System.now();
        opp.ExternalPortal__c = 'test1';
        opp.StatusIntegracaoPortalCotacoes__c = 'Integrado';
        insert opp;

        User userOne = TestUtility.createUser('user1');
        User userTwo = TestUtility.createUser('user2');
        insert new List<User>{userOne, userTwo};

        Setorizacao__c setorizacao1 = TestUtility.createSetorizacaoWithValidData(acc, userOne);
        setorizacao1.VendedorSuporte__c = userOne.Id;
        setorizacao1.Categoria__c = 'M';
        setorizacao1.ExternalId__c = '1';
        Setorizacao__c setorizacao2 = TestUtility.createSetorizacaoWithValidData(acc, userTwo);
        setorizacao2.VendedorSuporte__c = userTwo.Id;
        setorizacao2.Categoria__c = 'M';
        setorizacao2.ExternalId__c = '2';
        insert new List<Setorizacao__c>{setorizacao1, setorizacao2};

        OpportunityTeamMember oppTeamMemberOne = TestUtility.createOpportunityTeamMember(opp);
        oppTeamMemberOne.UserId = userOne.Id;
        OpportunityTeamMember oppTeamMemberTwo = TestUtility.createOpportunityTeamMember(opp);
        oppTeamMemberTwo.UserId = userTwo.Id;
        insert new List<OpportunityTeamMember>{oppTeamMemberOne,oppTeamMemberTwo};

        QuoteItem__c qItem = TestUtility.createQuoteItem(opp);
        qItem.IdPortal__c = '1';
        qItem.Categoria__c = 'M';
        qItem.Vendedor__c = userOne.Id;
        qItem.VendedorRespondeu__c = userTwo.Id;
        QuoteItem__c qItem2 = TestUtility.createQuoteItem(opp);
        qItem2.IdPortal__c = '1';
        qItem2.Categoria__c = 'M';
        qItem2.Vendedor__c = userTwo.Id;
        qItem2.VendedorRespondeu__c = userOne.Id;
        insert new List<QuoteItem__c>{qItem, qItem2};

        Order orderOne = TestUtility.createOrder(acc);
        orderOne.OpportunityId = opp.Id;
        orderOne.IdPortalCotacoes__c = '1';
        insert orderOne;
    }

    @isTest
    static void orderInNotificationTest(){
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Order order = [SELECT Id FROM Order LIMIT 1];
        QuoteItem__c qItem = [SELECT Id FROM QuoteItem__c LIMIT 1];

        SalesmanNotificationPortal.orderInNotification(
            order.Id,
            opp.Id,
            new List<String>{qItem.Id},
            0
        );
    }
}