Git Tests/force-app/main/default/default/objects/Account/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <label>Email</label>
    <type>TextArea</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/GrupoCliente__c.field-meta.xml
<CustomField>
    <fullName>GrupoCliente__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Grupo de clientes</label>
    <referenceTo>GrupoCliente__c</referenceTo>
    <relationshipLabel>Clientes</relationshipLabel>
    <relationshipName>Clientes</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/Saldo__c.field-meta.xml
<CustomField>
    <fullName>Saldo__c</fullName>
    <formula>LimiteCredito__c  -  IF(ISBLANK(Titulos__c), 0, VALUE(Titulos__c))</formula>
    <inlineHelpText>Limite de crédito - Títulos</inlineHelpText>
    <label>Saldo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Campaign/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <label>Condição de pagamento</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Campaign/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código da campanha</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Campaign/fields/GrupoCliente__c.field-meta.xml
<CustomField>
    <fullName>GrupoCliente__c</fullName>
    <label>Grupo de cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamento__c/CondicaoPagamento__c.object-meta.xml
<CustomObject>
    <label>Condição de pagamento</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condições de pagamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Estoque__c/Estoque__c.object-meta.xml
<CustomObject>
    <label>Estoque</label>
    <nameField>
        <label>Número do estoque</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estoques</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Estoque__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do estoque</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Estoque__c/fields/NomeProduto__c.field-meta.xml
<CustomField>
    <fullName>NomeProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome do produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Estoques</relationshipLabel>
    <relationshipName>Estoques</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Estoque__c/fields/Saldo__c.field-meta.xml
<CustomField>
    <fullName>Saldo__c</fullName>
    <label>Saldo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Fornecedor__c/Fornecedor__c.object-meta.xml
<CustomObject>
    <label>Fornecedor</label>
    <nameField>
        <label>Nome do fornecedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fornecedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Fornecedor__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do fornecedor</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/GeneralParameters__c/GeneralParameters__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Parâmetros gerais.</description>
    <label>Parâmetros gerais</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/GeneralParameters__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <defaultValue>&apos;tatiana.santos@grupoelfa.com.br&apos;</defaultValue>
    <description>Email de compras</description>
    <inlineHelpText>Email de compras</inlineHelpText>
    <label>Email de compras</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/GeneralParameters__c/fields/StockNotification__c.field-meta.xml
<CustomField>
    <fullName>StockNotification__c</fullName>
    <defaultValue>4</defaultValue>
    <label>Notificação entrada de estoque</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/GrupoCliente__c/GrupoCliente__c.object-meta.xml
<CustomObject>
    <label>Grupo de clientes</label>
    <nameField>
        <label>Nome de grupo de clientes</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Grupos de cliente</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/ItemCampanha__c.object-meta.xml
<CustomObject>
    <label>Item da campanha</label>
    <nameField>
        <label>Código do item de campanha</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens da campanha</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do item de campanha</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <formula>NomeProduto__r.Fornecedor__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Fornecedor</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/NomeProduto__c.field-meta.xml
<CustomField>
    <fullName>NomeProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome do produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>ItemCampanha</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Pricebook2/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Catálogos de preços</relationshipLabel>
    <relationshipName>CatalogoPreco</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Pricebook2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do produto</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/FatorConversao__c.field-meta.xml
<CustomField>
    <fullName>FatorConversao__c</fullName>
    <label>Fator de conversão</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fornecedor</label>
    <referenceTo>Fornecedor__c</referenceTo>
    <relationshipLabel>Produtos</relationshipLabel>
    <relationshipName>Produtos</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/Setorizacao__c.object-meta.xml
<CustomObject>
    <label>Setorização</label>
    <nameField>
        <displayFormat>SET-{000000}</displayFormat>
        <label>Número da setorização</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setorizações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>BU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>G</fullName>
                <label>GENÉRICO</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>MATERIAIS</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>NUTRIÇÃO</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Medctech</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>SPECIALTY</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>AMBOS</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>DIABETES</label>
            </value>
            <value>
                <fullName>Q</fullName>
                <label>ODONTOLOGIA</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <label>EQUIPAMENTO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome do cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Setorização</relationshipLabel>
    <relationshipName>Setorizacao</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fornecedor do produto</label>
    <referenceTo>Fornecedor__c</referenceTo>
    <relationshipLabel>Setorização</relationshipLabel>
    <relationshipName>Setorizacao</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Produto__c.field-meta.xml
<CustomField>
    <fullName>Produto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Setorização</relationshipLabel>
    <relationshipName>Setorizacao</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Vendedor__c.field-meta.xml
<CustomField>
    <fullName>Vendedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VDE</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Setorizacao</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/ProductCampaignControllerTest.cls
@isTest
public with sharing class ProductCampaignControllerTest {
    
    @isTest
    public static void testGetProduct() {

        GeneralParameters__c parameters = new GeneralParameters__c();
        parameters.Name = 'Parametro geral';
        parameters.Email__c = 'test.test@nescara.com';
        parameters.StockNotification__c = 4;
        insert parameters;

        GrupoCliente__c gCli = TestUtility.createGrupoCliente();
        insert gCli;

        Account account = TestUtility.createAccPJ();
        account.GrupoCliente__c = gCli.Id;
        insert account;

        Pricebook2 pricebook = new Pricebook2(
            Name = 'Pricebook Test',
            ExternalId__c = 'B01'
        );
        insert pricebook;

        Fornecedor__c provider = new Fornecedor__c(
            Name = 'Provider Test'
        );
        insert provider;

        Product2 product = TestUtility.createProduct();
        product.FatorConversao__c = '1';
        product.Fornecedor__c = provider.Id;
        product.Description = 'Lectrum';
        product.ProductCode = '55801';
        product.IsActive = true;
        insert product;

        Estoque__c inventory = new Estoque__c(
            NomeProduto__c = product.Id,
            Saldo__c = 5
        );
        insert inventory;

        PricebookEntry pricebookEntry = TestUtility.createPricebookEntry(pricebook.Id, product.Id);
        pricebookEntry.UnitPrice = 10;
        insert pricebookEntry;

        Setorizacao__c sectorization =new Setorizacao__c(
            Categoria__c = 'M',
            Produto__c = product.Id,
            Fornecedor__c = provider.Id,
            Vendedor__c = UserInfo.getUserid(),
            Conta__c = account.Id
        );
        insert sectorization;

        Campaign camp = TestUtility.createCampaign();
        camp.GrupoCliente__c = '123';
        Campaign camp2 = TestUtility.createCampaignShelfLife();        
        Campaign camp3 = TestUtility.createCampaignVendedor();
        
        insert new List<Campaign>{camp, camp2, camp3};

        ItemCampanha__c itemCamp = TestUtility.createItemCampanha(camp.Id, product.Id);
        ItemCampanha__c itemCamp2 = TestUtility.createItemCampanha(camp2.Id, product.Id);
        ItemCampanha__c itemCamp3 = TestUtility.createItemCampanha(camp3.Id, product.Id);

        insert new List<ItemCampanha__c>{itemCamp, itemCamp2, itemCamp3};

        CondicaoPagamento__c paymentCondition = TestUtility.createPaymentCondition();
        insert paymentCondition;

        String pricebookId = pricebook.Id; 
        String clienteId = account.Id; 
        String offSetValue = ''; 
        String searchGenericValue = ''; 
        String searchFabricanteValue = '';

        List<OrderScreenController.ProductData> productList = ProductCampaignController.getProductCampaign(
            pricebookId,
            clienteId,
            offSetValue,
            searchGenericValue,
            searchFabricanteValue,
            paymentCondition.Id
        );

        ProductCampaignController.getClientOrderData(clienteId, product.Id);
    }

}