Git Tests/force-app/main/default/default/objects/Account/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamento__c/CondicaoPagamento__c.object-meta.xml
<CustomObject>
    <label>Condição de pagamento</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condições de pagamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/CondicaoPagamentoPorCD__c.object-meta.xml
<CustomObject>
    <label>Condição de pagamento por CD</label>
    <nameField>
        <label>Nome de Condição de pagamento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condições de pagamentos por CD</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Condição de Pagamento CD</relationshipLabel>
    <relationshipName>CondicoesPagamento</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/Orcamento__c.field-meta.xml
<CustomField>
    <fullName>Orcamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Orçamento</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Condições de pagamentos por CD</relationshipLabel>
    <relationshipName>Condicespagamentospor_CD</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Estoque__c/Estoque__c.object-meta.xml
<CustomObject>
    <label>Estoque</label>
    <nameField>
        <label>Número do estoque</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estoques</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/ItemCampanha__c.object-meta.xml
<CustomObject>
    <label>Item da campanha</label>
    <nameField>
        <label>Código do item de campanha</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens da campanha</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ItemContrato__c/ItemContrato__c.object-meta.xml
<CustomObject>
    <label>Item de contrato</label>
    <nameField>
        <displayFormat>IT-{00000000}</displayFormat>
        <label>Número do item de contrato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens de contrato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ListaCentroDistribuicao__c/ListaCentroDistribuicao__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Lista com todos os centros de distribuição do Grupo Elfa.</description>
    <label>Centros de distribuição</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ListaCentroDistribuicao__c/fields/CodigoCD__c.field-meta.xml
<CustomField>
    <fullName>CodigoCD__c</fullName>
    <label>Código do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Orcamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/ExternalPortal__c.field-meta.xml
<CustomField>
    <fullName>ExternalPortal__c</fullName>
    <externalId>true</externalId>
    <label>ExternalPortal</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/IdPortal__c.field-meta.xml
<CustomField>
    <fullName>IdPortal__c</fullName>
    <externalId>true</externalId>
    <label>Id Portal</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/StatusIntegracaoPortalCotacoes__c.field-meta.xml
<CustomField>
    <fullName>StatusIntegracaoPortalCotacoes__c</fullName>
    <label>Status de Integração (Portal)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não Integrado</fullName>
                <default>true</default>
                <label>Não Integrado</label>
            </value>
            <value>
                <fullName>Falha na Integração</fullName>
            </value>
            <value>
                <fullName>Integrado</fullName>
            </value>
            <value>
                <fullName>Recebendo dados</fullName>
            </value>
            <value>
                <fullName>Recebida</fullName>
            </value>
            <value>
                <fullName>Integrada</fullName>
                <isActive>false</isActive>
                <label>Integrada</label>
            </value>
            <value>
                <fullName>Não Integrada</fullName>
                <isActive>false</isActive>
                <label>Não Integrada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/VendedorSuporte__c.field-meta.xml
<CustomField>
    <fullName>VendedorSuporte__c</fullName>
    <inlineHelpText>Vendedor Interno / Vendedor Suporte</inlineHelpText>
    <label>Representante VDI/VDS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/IdPortal__c.field-meta.xml
<CustomField>
    <fullName>IdPortal__c</fullName>
    <description>Id do item no Portal de Cotações.</description>
    <externalId>true</externalId>
    <label>Id do Portal</label>
    <length>64</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/ItemCampanha__c.field-meta.xml
<CustomField>
    <fullName>ItemCampanha__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item da campanha</label>
    <referenceTo>ItemCampanha__c</referenceTo>
    <relationshipLabel>Produto do orçamento</relationshipLabel>
    <relationshipName>ProdutoOrcamento</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <description>
        Objeto recebido na integração do portal de cotações (class: IntegrationPortalQuoteIN) e
        utilizado para armazenar as requisições de produtos efetuada pelos clientes,
        assim como a resposta efetuada pelos vendedores.
        Sua estrutura a nível de negócio existe de duas formas:
        1. a nível de item, sendo o item entendido como as informações advindas da integração com a requisição do cliente.
        2. a nível de resposta, sendo a resposta entendida como as informações enviadas do vendedor para o cliente como resposta.
        Esse objeto pode ser visualizado a nível de usuário nas telas de orçamento do tipo portal (Opportunity > RecordType > OrcamentoPortal),
        que é o mestre do relacionamento mestre-detalhe contido nesse objeto.
        O item é enviado ao portal como resposta na integração do portal de cotação (class: IntegrationPortalQuoteOUT).
        E também é enviado quando é efetuado vínculo de produto (class: IntegrationPortalVinculoOUT)
    </description>
    <label>Item da Cotação</label>
    <nameField>
        <label>Nome do Item da Cotação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens da Cotação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <description>Campo usado para itentificar a categoria do vendedor responsável (advém de setorizacao__c)</description>
    <label>Categoria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/IdPortal__c.field-meta.xml
<CustomField>
    <fullName>IdPortal__c</fullName>
    <description>Id do item no Portal de Cotações (hash), não vem da integradora, é criado para cada item dentro do portal.</description>
    <externalId>true</externalId>
    <label>Id do Portal</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>produto vinculado a resposta.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Items da Cotação</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/Setorizacao__c.object-meta.xml
<CustomObject>
    <label>Setorização</label>
    <nameField>
        <displayFormat>SET-{000000}</displayFormat>
        <label>Número da setorização</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setorizações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>BU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>G</fullName>
                <label>GENÉRICO</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>MATERIAIS</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>NUTRIÇÃO</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Medctech</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>SPECIALTY</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>AMBOS</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>DIABETES</label>
            </value>
            <value>
                <fullName>Q</fullName>
                <label>ODONTOLOGIA</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <label>EQUIPAMENTO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/VendedorSuporte__c.field-meta.xml
<CustomField>
    <fullName>VendedorSuporte__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VDI</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SetorizacoesVendedor</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/BudgetDetailSelectorTest.cls
@isTest
public with sharing class BudgetDetailSelectorTest {
    @TestSetup
    static void makeData(){
        Account acc = TestUtility.createAccount();
        insert acc;

        Setorizacao__c setor = TestUtility.createSetorizacaoWithValidData(acc, new User(Id = UserInfo.getUserId()));
        setor.Categoria__c = 'S';
        setor.VendedorSuporte__c = UserInfo.getUserId();
        insert setor;

        ListaCentroDistribuicao__c cdlist = TestUtility.createListaCentroDistribuicao();

        Contact contact = TestUtility.createContact(acc.Id);
        insert contact;

        CondicaoPagamento__c condPag = TestUtility.createPaymentCondition();
        insert condPag;

        Opportunity opp = TestUtility.createOpportunity(acc, contact, condPag);
        opp.ExternalPortal__c = '786876876';
        opp.StatusIntegracaoPortalCotacoes__c = 'Integrado';
        insert opp;


        Product2 prod = TestUtility.createProduct();
        insert prod;

        QuoteItem__c qItem = TestUtility.createQuoteItem(opp);
        qItem.IdPortal__c = '012131231';
        qItem.Categoria__c = 'categTest';
        qItem.Product__c = prod.Id;
        insert qItem;
    }

    @isTest
    static void getCondicaoPagamentoPorCDTest(){
        Opportunity opp = [SELECT Id FROM Opportunity][0];

        Test.startTest();
        List<CondicaoPagamentoPorCD__c> result = BudgetDetailSelector.getCondicaoPagamentoPorCD(String.valueOf(opp.Id));
        Test.stopTest();

        System.assertEquals(false, result.size() > 1);
    }

    @isTest
    static void getEstoqueAggregatedTest(){
        Opportunity opp = [SELECT Id FROM Opportunity][0];
        Account acc = [SELECT Id FROM Account][0];
        List<Product2> productList = [SELECT Id FROM Product2];
        Set<Id> idSet = (new Map<Id,Product2>(productList)).keySet();

        Test.startTest();
        List<AggregateResult> result = BudgetDetailSelector.getEstoqueAggregated(String.valueOf(acc.Id), idSet);
        Test.stopTest();

        System.assertEquals(true, result.size() == 0 );
    }

    @isTest
    static void getOpportunityTest(){
        Opportunity opp = [SELECT Id FROM Opportunity][0];

        Test.startTest();
        Opportunity result = BudgetDetailSelector.getOpportunity(String.valueOf(opp.Id));
        Test.stopTest();

        System.assertEquals(true, result != null);
    }

    @isTest
    static void getOpportunityTeamMemberTest(){
        Opportunity opp = [SELECT Id FROM Opportunity][0];

        Test.startTest();
        OpportunityTeamMember result = BudgetDetailSelector.getOpportunityTeamMember(String.valueOf(opp.Id));
        Test.stopTest();

        System.assertEquals(true, result != null);
    }

    @isTest
    static void getAllQuoteItemListTest(){
        Opportunity opp = [SELECT Id FROM Opportunity][0];

        Test.startTest();
        List<QuoteItem__c> result = BudgetDetailSelector.getAllQuoteItemList(String.valueOf(opp.Id));
        Test.stopTest();

        System.assertEquals(true, result.size() > 0);
    }

    @isTest
    static void getQuoteItemMapTest(){
        QuoteItem__c quote = [SELECT Id FROM QuoteItem__c][0];
        List<String> qItemIdList = new List<String>();
        qItemIdList.add(String.valueOf(quote.Id));

        Test.startTest();
        Map<Id, QuoteItem__c> result = BudgetDetailSelector.getQuoteItemMap(qItemIdList);
        Test.stopTest();

        System.assertEquals(true, result.size() > 0);
    }

    @isTest
    static void getSetorizacaoListTest(){
        Account acc = [SELECT Id FROM Account][0];

        Test.startTest();
        List<Setorizacao__c> result = BudgetDetailSelector.getSetorizacaoList(String.valueOf(acc.Id));
        Test.stopTest();

        System.assertEquals(true, result.size() > 0);
    }

    @isTest
    static void getUniqueQuoteItemByIdPortalTest(){
        Opportunity opp = [SELECT Id FROM Opportunity][0];

        Test.startTest();
        QuoteItem__c result = BudgetDetailSelector.getUniqueQuoteItemByIdPortal('123123123', String.valueOf(opp.Id));
        Test.stopTest();

        System.assertEquals(false, result != null);
    }
    
    @isTest
    static void getQuoteItemsByIdPortalTest(){
        Opportunity opp = [SELECT Id FROM Opportunity][0];

        Test.startTest();
        List<QuoteItem__c> result = BudgetDetailSelector.getQuoteItemsByIdPortal('123123123', String.valueOf(opp.Id));
        Test.stopTest();

        System.assertEquals(false, result.size() > 0);
    }

    @isTest
    static void getQuoteItemTest(){
        QuoteItem__c quote = [SELECT Id FROM QuoteItem__c][0];

        Test.startTest();
        QuoteItem__c result = BudgetDetailSelector.getQuoteItem(String.valueOf(quote.Id));
        Test.stopTest();

        System.assertEquals(true, result != null);
    }

    @isTest
    static void getPricebookEntryListTest(){
        Product2 prod = [SELECT Id FROM Product2][0];
        PricebookEntry pbEntry = [SELECT Id FROM PricebookEntry][0];

        Test.startTest();
        List<PricebookEntry> result = BudgetDetailSelector.getPricebookEntryList(String.valueOf(prod.Id), String.valueOf(pbEntry.Id));
        Test.stopTest();

        System.assertEquals(false, result.size() > 0);
    }

    @isTest
    static void getConditionPaymentByCDTest(){
        Opportunity opp = [SELECT Id FROM Opportunity][0];

        Test.startTest();
        List<CondicaoPagamentoPorCD__c> result = BudgetDetailSelector.getConditionPaymentByCD(String.valueOf(opp.Id), '45456789000132');
        Test.stopTest();

        System.assertEquals(false, result.size() > 0);
    }

    @isTest
    static void getCurrentUserGroupTest(){
        Opportunity opp = [SELECT Id FROM Opportunity][0];

        Test.startTest();
        Group result = BudgetDetailSelector.getCurrentUserGroup();
        Test.stopTest();

        System.assertEquals(true, result != null);
    }

    @isTest
    static void getCurrentUserGroupListTest(){
        Opportunity opp = [SELECT Id FROM Opportunity][0];

        Test.startTest();
        List<Group> result = BudgetDetailSelector.getCurrentUserGroupList();
        Test.stopTest();

        System.assertEquals(true, result.size() > 0);
    }

    @isTest
    static void getEstoqueListByProdCodeTest(){
        Opportunity opp = [SELECT Id FROM Opportunity][0];

        Test.startTest();
        List<Estoque__c> result = BudgetDetailSelector.getEstoqueListByProdCode('BHGF34256');
        Test.stopTest();

        System.assertEquals(false, result.size() > 0);
    }

    @isTest
    static void getLastOppLineItemWonTest(){
        Account acc = [SELECT Id FROM Account][0];

        Test.startTest();
        OpportunityLineItem result = BudgetDetailSelector.getLastOppLineItemWon('BHGF34256', String.valueOf(acc.Id));
        Test.stopTest();

        System.assertEquals(false, result != null);
    }

    @isTest
    static void getLastOppLineItemLostTest(){
        Account acc = [SELECT Id FROM Account][0];

        Test.startTest();
        OpportunityLineItem result = BudgetDetailSelector.getLastOppLineItemLost('BHGF34256', String.valueOf(acc.Id));
        Test.stopTest();

        System.assertEquals(false, result != null);
    }

    @isTest
    static void getQuoteItemsWithCNPJCDTest(){
        Opportunity opp = [SELECT Id FROM Opportunity][0];

        Test.startTest();
        List<QuoteItem__c> result = BudgetDetailSelector.getQuoteItemsWithCNPJCD(String.valueOf(opp.Id));
        Test.stopTest();

        System.assertEquals(false, result.size() > 0);
    }

    @isTest
    static void getConditionPaymentListTest(){
        Opportunity opp = [SELECT Id FROM Opportunity][0];

        Test.startTest();
        List<CondicaoPagamentoPorCD__c> result = BudgetDetailSelector.getConditionPaymentList(String.valueOf(opp.Id));
        Test.stopTest();

        System.assertEquals(false, result.size() > 0);
    }

    @isTest
    static void getUserCategoriesAggregatedTest(){
        Opportunity opp = [SELECT Id FROM Opportunity][0];

        Test.startTest();
        List<AggregateResult> result = BudgetDetailSelector.getUserCategoriesAggregated(String.valueOf(opp.Id));
        Test.stopTest();

        System.assertEquals(true, result.size() > 0);
    }

    @isTest
    static void getQuoteItemForSetItemCdTest(){
        Opportunity opp = [SELECT Id FROM Opportunity][0];
        QuoteItem__c quote = [SELECT Id FROM QuoteItem__c][0];

        Test.startTest();
        List<QuoteItem__c> result = BudgetDetailSelector.getQuoteItemForSetItemCd(String.valueOf(opp.Id), '35467656000132', String.valueOf(quote.Id), '012131231');
        Test.stopTest();

        System.assertEquals(false, result.size() > 0);
    }

    @isTest
    static void getItemCampaignByCDTest(){
        Account acc = [SELECT Id FROM Account][0];
        Product2 prod = [SELECT ProductCode FROM Product2][0];
        QuoteItem__c quote = [SELECT Id FROM QuoteItem__c][0];
        List<String> cdCodeList = new List<String>();
        ListaCentroDistribuicao__c cd = [SELECT CodigoCD__c FROM ListaCentroDistribuicao__c][0];
        cdCodeList.add(cd.CodigoCD__c);

        Test.startTest();
        List<ItemCampanha__c> result = BudgetDetailSelector.getItemCampaignByCD(cdCodeList,String.valueOf(prod.ProductCode), String.valueOf(acc.Id) );
        Test.stopTest();

        System.assertEquals(false, result.size() > 0);
    }

    @isTest
    static void getContractByProductTest(){
        Account acc = [SELECT Id FROM Account][0];
        Product2 prod = [SELECT ProductCode FROM Product2][0];

        Test.startTest();
        List<ItemContrato__c> result = BudgetDetailSelector.getContractByProduct(String.valueOf(acc.Id), String.valueOf(prod.ProductCode));
        Test.stopTest();

        System.assertEquals(false, result.size() > 0);
    }

    @isTest
    static void getQuoteItemsFromIdPortalUserBuTest(){

        Test.startTest();
        List<QuoteItem__c> result = BudgetDetailSelector.getQuoteItemsFromIdPortalUserBu(new List<String>(),'2131232131', '21312312321', new List<String>() );
        Test.stopTest();

        System.assertEquals(false, result.size() > 0);
    }

    @isTest
    static void getQuoteItemListToCopyTest(){
        Opportunity opp = [SELECT Id FROM Opportunity][0];

        Test.startTest();
        List<QuoteItem__c> result = BudgetDetailSelector.getQuoteItemListToCopy(new Set<String>(), String.valueOf(opp.Id));
        Test.stopTest();

        System.assertEquals(false, result.size() > 0);
    }

    @isTest
    static void getQuoteItemProgramacaoEntregaTest(){
        Opportunity opp = [SELECT Id FROM Opportunity][0];

        Test.startTest();
        List<QuoteItem__c> result = BudgetDetailSelector.getQuoteItemProgramacaoEntrega('324242342');
        Test.stopTest();

        System.assertEquals(false, result.size() > 0);
    }

    @isTest
    static void getQuoteItemCategoryAggregateTest(){
        Opportunity opp = [SELECT Id FROM Opportunity][0];

        Test.startTest();
        List<AggregateResult> result = BudgetDetailSelector.getQuoteItemCategoryAggregate('324242342');
        Test.stopTest();

        System.assertEquals(false, result.size() > 0);
    }

    @isTest
    static void getConditionPaymentByNameTest(){
        Opportunity opp = [SELECT Id FROM Opportunity][0];

        Test.startTest();
        List<CondicaoPagamento__c> result = BudgetDetailSelector.getConditionPaymentByName(new List<String>());
        Test.stopTest();

        System.assertEquals(false, result.size() > 0);
    }

    @isTest
    static void getQuoteItemWithHistoryTest(){
        Opportunity opp = [SELECT Id FROM Opportunity][0];

        Test.startTest();
        QuoteItem__c result = BudgetDetailSelector.getQuoteItemWithHistory('21312312312', String.valueOf(opp.Id));
        Test.stopTest();
 
        System.assertEquals(false, result != null);
    }
    
    @isTest
    static void getProductListFromCodeTest(){
        Opportunity opp = [SELECT Id FROM Opportunity][0];

        Test.startTest();
        List<Product2> result = BudgetDetailSelector.getProductListFromCode(new Set<String>());
        Test.stopTest();

        System.assertEquals(false, result.size() > 0);
    }
    
    @isTest
    static void getProductMapFromCodeTest(){
        Opportunity opp = [SELECT Id FROM Opportunity][0];

        Test.startTest();
        Map<Id, Product2> result = BudgetDetailSelector.getProductMapFromCode(new Set<String>());
        Test.stopTest();

        System.assertEquals(false, result.size() > 0);
    }
    
    @isTest
    static void getLastOpportunityLineItemAggrTest(){
        Opportunity opp = [SELECT Id FROM Opportunity][0];
        Account acc = [SELECT Id FROM Account][0];

        Test.startTest();
        List<AggregateResult> result = BudgetDetailSelector.getLastOpportunityLineItemAggr(String.valueOf(acc.Id), new Set<Id>());
        Test.stopTest();

        System.assertEquals(false, result.size() > 0);
    }
    
    @isTest
    static void getLastOpportunityLineItemMapTest(){
        Test.startTest();
        Map<Id, OpportunityLineItem> result = BudgetDetailSelector.getLastOpportunityLineItemMap(new List<String>());
        Test.stopTest();

        System.assertEquals(false, result.size() > 0);
    }

    @isTest
    static void getUnfilledConditionPaymentTest(){
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        CondicaoPagamento__c condPag = [SELECT Id FROM CondicaoPagamento__c LIMIT 1];
        CondicaoPagamentoPorCD__c conpagcd = TestUtility.createCondicaoPagamentoPorCD(condPag.Id);
        conpagcd.orcamento__c = opp.Id;
        insert conpagcd;
        Test.startTest();
        BudgetDetailSelector.getUnfilledConditionPayment(opp.Id, new List<String>());
        Test.stopTest();

    }

}