Git Tests/force-app/main/default/default/objects/Account/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Estoque__c/Estoque__c.object-meta.xml
<CustomObject>
    <label>Estoque</label>
    <nameField>
        <label>Número do estoque</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estoques</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Estoque__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do estoque</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Estoque__c/recordTypes/Estoque.recordType-meta.xml
<RecordType>
    <fullName>Estoque</fullName>
    <active>true</active>
    <description>Identificação do estoque para criação de pedidos e cotações.</description>
    <label>Estoque</label>
</RecordType>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Orcamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/ExternalPortal__c.field-meta.xml
<CustomField>
    <fullName>ExternalPortal__c</fullName>
    <externalId>true</externalId>
    <label>ExternalPortal</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/IdPortal__c.field-meta.xml
<CustomField>
    <fullName>IdPortal__c</fullName>
    <externalId>true</externalId>
    <label>Id Portal</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/StatusIntegracaoPortalCotacoes__c.field-meta.xml
<CustomField>
    <fullName>StatusIntegracaoPortalCotacoes__c</fullName>
    <label>Status de Integração (Portal)</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Não Integrado</fullName>
                <default>true</default>
                <label>Não Integrado</label>
            </value>
            <value>
                <fullName>Falha na Integração</fullName>
            </value>
            <value>
                <fullName>Integrado</fullName>
            </value>
            <value>
                <fullName>Recebendo dados</fullName>
            </value>
            <value>
                <fullName>Recebida</fullName>
            </value>
            <value>
                <fullName>Integrada</fullName>
                <isActive>false</isActive>
                <label>Integrada</label>
            </value>
            <value>
                <fullName>Não Integrada</fullName>
                <isActive>false</isActive>
                <label>Não Integrada</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/TabulacaoN1__c.field-meta.xml
<CustomField>
    <fullName>TabulacaoN1__c</fullName>
    <inlineHelpText>Este campo é um refinamento do valor do campo Status</inlineHelpText>
    <label>Tabulação N1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recusa</fullName>
            </value>
            <value>
                <fullName>Aceite</fullName>
            </value>
            <value>
                <fullName>Improdutiva</fullName>
            </value>
            <value>
                <fullName>Envio Automático</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/VendedorSuporte__c.field-meta.xml
<CustomField>
    <fullName>VendedorSuporte__c</fullName>
    <inlineHelpText>Vendedor Interno / Vendedor Suporte</inlineHelpText>
    <label>Representante VDI/VDS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityTeamMember/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Centro de distribuição</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityTeamMember/fields/TabulacaoN1__c.field-meta.xml
<CustomField>
    <fullName>TabulacaoN1__c</fullName>
    <inlineHelpText>Este campo é um refinamento do valor do campo Status</inlineHelpText>
    <label>Tabulação N1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recusa</fullName>
            </value>
            <value>
                <fullName>Aceite</fullName>
            </value>
            <value>
                <fullName>Improdutiva</fullName>
            </value>
            <value>
                <fullName>Envio Automático</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>Categoria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do produto</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <description>
        Objeto recebido na integração do portal de cotações (class: IntegrationPortalQuoteIN) e
        utilizado para armazenar as requisições de produtos efetuada pelos clientes,
        assim como a resposta efetuada pelos vendedores.
        Sua estrutura a nível de negócio existe de duas formas:
        1. a nível de item, sendo o item entendido como as informações advindas da integração com a requisição do cliente.
        2. a nível de resposta, sendo a resposta entendida como as informações enviadas do vendedor para o cliente como resposta.
        Esse objeto pode ser visualizado a nível de usuário nas telas de orçamento do tipo portal (Opportunity > RecordType > OrcamentoPortal),
        que é o mestre do relacionamento mestre-detalhe contido nesse objeto.
        O item é enviado ao portal como resposta na integração do portal de cotação (class: IntegrationPortalQuoteOUT).
        E também é enviado quando é efetuado vínculo de produto (class: IntegrationPortalVinculoOUT)
    </description>
    <label>Item da Cotação</label>
    <nameField>
        <label>Nome do Item da Cotação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens da Cotação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <description>Campo usado para itentificar a categoria do vendedor responsável (advém de setorizacao__c)</description>
    <label>Categoria</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/CategoriaCliente__c.field-meta.xml
<CustomField>
    <fullName>CategoriaCliente__c</fullName>
    <description>Recebido do portal via integração a categoria do produto declarada pelo cliente para o produto requisitado.</description>
    <label>Categoria do Cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>OpportunityId__r.ExternalPortal__c + _ + IdPotal__c + _ + Vendedor__c + _ + Categoria__c</description>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Chave Externa</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/IdPortal__c.field-meta.xml
<CustomField>
    <fullName>IdPortal__c</fullName>
    <description>Id do item no Portal de Cotações (hash), não vem da integradora, é criado para cada item dentro do portal.</description>
    <externalId>true</externalId>
    <label>Id do Portal</label>
    <length>32</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>produto vinculado a resposta.</description>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Items da Cotação</relationshipLabel>
    <relationshipName>QuoteItems</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/ProgramacaoEntrega__c.field-meta.xml
<CustomField>
    <fullName>ProgramacaoEntrega__c</fullName>
    <description>Informações de entrega requeridas pelo cliente.</description>
    <label>Programacao Entrega</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/TabulacaoN1__c.field-meta.xml
<CustomField>
    <fullName>TabulacaoN1__c</fullName>
    <inlineHelpText>Refinamento do valor do campo Status.</inlineHelpText>
    <label>Tabulação N1</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FORA DE MALHA</fullName>
                <label>Fora de malha</label>
            </value>
            <value>
                <fullName>SEM ESTOQUE</fullName>
                <label>Sem estoque</label>
            </value>
            <value>
                <fullName>NÃO TEMOS NESSA APRESENTAÇÃO</fullName>
                <label>Não temos nessa apresentação</label>
            </value>
            <value>
                <fullName>NÃO TEMOS A VALIDADE SOLICITADA</fullName>
                <label>Não temos a validade solicitada</label>
            </value>
            <value>
                <fullName>Não temos a quantidade solicitada</fullName>
            </value>
            <value>
                <fullName>Bloqueio por regionalização</fullName>
            </value>
            <value>
                <fullName>Termolab alto SLA de entrega</fullName>
            </value>
            <value>
                <fullName>Não pertence a minha BU</fullName>
            </value>
            <value>
                <fullName>Cotado</fullName>
            </value>
            <value>
                <fullName>NÃO TEM NO PORTIFÓLIO</fullName>
                <label>Não tem no portifólio</label>
            </value>
            <value>
                <fullName>COM OFERTA</fullName>
                <isActive>false</isActive>
                <label>Com oferta</label>
            </value>
            <value>
                <fullName>NÃO TEMOS A QTDE SOLICITADA</fullName>
                <isActive>false</isActive>
                <label>NÃO TEMOS A QTDE SOLICITADA</label>
            </value>
            <value>
                <fullName>NÃO TRABALHAMOS</fullName>
                <isActive>false</isActive>
                <label>NÃO TRABALHAMOS</label>
            </value>
            <value>
                <fullName>NÃO CONSEGUIMOS ATENDER NO PRAZO SOLICITADO</fullName>
                <isActive>false</isActive>
                <label>Não conseguimos atender no prazo solicitado</label>
            </value>
            <value>
                <fullName>SEM OFERTA</fullName>
                <isActive>false</isActive>
                <label>Sem oferta</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/Setorizacao__c.object-meta.xml
<CustomObject>
    <label>Setorização</label>
    <nameField>
        <displayFormat>SET-{000000}</displayFormat>
        <label>Número da setorização</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Setorizações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/Categoria__c.field-meta.xml
<CustomField>
    <fullName>Categoria__c</fullName>
    <label>BU</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>G</fullName>
                <label>GENÉRICO</label>
            </value>
            <value>
                <fullName>M</fullName>
                <label>MATERIAIS</label>
            </value>
            <value>
                <fullName>N</fullName>
                <label>NUTRIÇÃO</label>
            </value>
            <value>
                <fullName>E</fullName>
                <label>Medctech</label>
            </value>
            <value>
                <fullName>S</fullName>
                <label>SPECIALTY</label>
            </value>
            <value>
                <fullName>A</fullName>
                <label>AMBOS</label>
            </value>
            <value>
                <fullName>C</fullName>
                <label>DIABETES</label>
            </value>
            <value>
                <fullName>Q</fullName>
                <label>ODONTOLOGIA</label>
            </value>
            <value>
                <fullName>Y</fullName>
                <label>EQUIPAMENTO</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Setorizacao__c/fields/VendedorSuporte__c.field-meta.xml
<CustomField>
    <fullName>VendedorSuporte__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>VDI</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SetorizacoesVendedor</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/budgetDetailControllerTest.cls
@isTest
public with sharing class budgetDetailControllerTest {
    
    @TestSetup
    static void makeData(){
        Account acc = TestUtility.createAccount();
        insert acc;

        Setorizacao__c setor = TestUtility.createSetorizacaoWithValidData(acc, new User(Id = UserInfo.getUserId()));
        setor.Categoria__c = 'M';
        setor.VendedorSuporte__c = UserInfo.getUserId();
        insert setor;

        Contact contact = TestUtility.createContact(acc.Id);
        insert contact;

        CondicaoPagamento__c condPag = TestUtility.createPaymentCondition2();
        insert condPag;

        Opportunity opp = TestUtility.createOpportunity(acc, contact, condPag);
        opp.ExternalPortal__c = 'getBudgetDataWithItensTest';
        opp.StatusIntegracaoPortalCotacoes__c = 'Integrado';
        insert opp;

        OpportunityTeamMember oppTeamMember = TestUtility.createOpportunityTeamMember(opp);
        insert oppTeamMember;

        Product2 prod = TestUtility.createProduct();
        insert prod;

        QuoteItem__c qItem = TestUtility.createQuoteItem(opp);
        qItem.IdPortal__c = 'setTabulacao';
        qItem.Categoria__c = 'M';
        QuoteItem__c qItemWithEstoque = TestUtility.createQuoteItem(opp);
        qItemWithEstoque.Product__c = prod.Id;
        QuoteItem__c qItemProgEntrega = TestUtility.createQuoteItem(opp);
        qItemProgEntrega.IdPortal__c = 'progEntrega';
        qItemProgEntrega.ProgramacaoEntrega__c = '[{"quantidade":"10","data":"19/03/2022"}]';
        QuoteItem__c qItemCategoriaCliente = TestUtility.createQuoteItem(opp);
        qItemCategoriaCliente.IdPortal__c = 'categoriaCliente';
        qItemCategoriaCliente.Categoria__c = 'M';
        qItemCategoriaCliente.CategoriaCliente__c = 'categoriaTeste';
        insert new List<QuoteItem__c>{qItem, qItemWithEstoque, qItemProgEntrega, qItemCategoriaCliente};

        Estoque__c estoque = TestUtility.createStock('getBudgetDataWithItensTest', prod.Id);
        estoque.ExternalId__c = 'getBudgetDataWithItensTest';
        insert estoque;
    }

    @isTest
    static void getBudgetDataWithItensTest(){
        Opportunity opp = [SELECT Id FROM Opportunity WHERE ExternalPortal__c = 'getBudgetDataWithItensTest'];
        StandardResponse response = BudgetDetailController.getBudgetDataWithItens(opp.Id);
        System.assertEquals(false, response.hasError);
        //StandardResponse responseError = BudgetDetailController.getBudgetDataWithItens('Error');
        //System.assertEquals(true, responseError.hasError);
    }

    @isTest
    static void setItemTabulacaoN1Test(){
        Opportunity opp = [SELECT Id, AccountId FROM Opportunity WHERE ExternalPortal__c = 'getBudgetDataWithItensTest'];
        StandardResponse response = BudgetDetailController.setItemTabulacaoN1(
            new List<String>{'setTabulacao'},
            opp.Id,
            opp.AccountId,
            new List<String>{'M','S'},
            'Não pertence a minha BU'
        );
        System.assertEquals(false, response.hasError);
        StandardResponse responseError = BudgetDetailController.setItemTabulacaoN1(
            new List<String>{'setTabulacao'},
            'error',
            opp.AccountId,
            new List<String>{'M','S'},
            'Não pertence a minha BU'
        );
        System.assertEquals(true, responseError.hasError);
    }

    @isTest
    static void getProgramacaoEntregaTest(){
        BudgetDetailController.getProgramacaoEntrega('progEntrega');
    }

    @isTest
    static void getCustomerCategoryTest(){
        Opportunity opp = [SELECT Id FROM Opportunity WHERE ExternalPortal__c = 'getBudgetDataWithItensTest'];
        BudgetDetailController.getCustomerCategory(opp.Id);
        //BudgetDetailController.getCustomerCategory('Error');
    }

    @isTest
    static void saveBudgetTest(){
        Opportunity opp = [SELECT Id FROM Opportunity WHERE ExternalPortal__c = 'getBudgetDataWithItensTest'];
        opp.TabulacaoN1__c = 'Aceite';
        opp.TabulacaoN2__c = 'Cotação Enviada TT';
        opp.StageName = 'Novo';
        update opp;
        BudgetDetailController.saveBudget(opp, false, null);
        opp.DataVencimento__c = DateTime.now().addDays(-1);
        update opp;
        BudgetDetailController.saveBudget(opp, true, null);
        opp.DataVencimento__c = DateTime.now().addDays(1);
        update opp;
        BudgetDetailController.saveBudget(opp, true, null);
        opp.TabulacaoN1__c = null;
        opp.TabulacaoN2__c = null;
        String cdValues = '[{"totItem":100,"resp":1,"qtdItensTotal":568,"PrazoValidade":0,"PrazoEntrega":3,"ObservacoesLongText":null,"MinimumBilling":1,"Id":"a0i21000003w8CYAAY","FretePicklist":"CIF","CondicaoPagamentoPL":"043/A VISTA","CNPJCD":"25211499000107","CloseDate":"2022-09-17","CentroDistribuicao":"MEDCOM - GOIANIA (MATRIZ)"}]';
        BudgetDetailController.saveBudget(opp, true, cdValues);
        BudgetDetailController.saveBudget(new Opportunity(), false, null);
    }

    @isTest
    static void getUserCategoriesTest(){
        Opportunity opp = [SELECT Id FROM Opportunity WHERE ExternalPortal__c = 'getBudgetDataWithItensTest'];
        StandardResponse response = BudgetDetailController.getUserCategories(opp.Id);
        System.assertEquals(false, response.hasError);
        //StandardResponse responseError = BudgetDetailController.getUserCategories('error');
        //System.assertEquals(true, responseError.hasError);
    }

    @isTest
    static void getPdfPageTest(){
        Opportunity opp = [SELECT Id FROM Opportunity WHERE ExternalPortal__c = 'getBudgetDataWithItensTest'];
        StandardResponse response = BudgetDetailController.getPdfPage(opp.Id);
        System.assertEquals(false, response.hasError);
        //StandardResponse responseError = BudgetDetailController.getPdfPage('error');
        //System.assertEquals(true, responseError.hasError);
    }

    @isTest
    static void putStatusItemAndStyleTest(){
        Opportunity opp = [SELECT Id FROM Opportunity WHERE ExternalPortal__c = 'getBudgetDataWithItensTest'];
        QuoteItem__c qItem = TestUtility.createQuoteItem(opp);
        qItem.Status__c = 'Vinculado';
        qItem.TabulacaoN1__c = null;
        QuoteItem__c qItemAnswered = TestUtility.createQuoteItem(opp);
        qItemAnswered.Status__c = 'Vinculado';
        qItemAnswered.TabulacaoN1__c = 'Cotado';
        List<QuoteItem__c> qItemList = new List<QuoteItem__c>{qItemAnswered};
        BudgetDetailController.putStatusItemAndStyle(new BudgetDetailController.budgetItemData(), qItemList);
        qItemList.add(qItem);
        BudgetDetailController.putStatusItemAndStyle(new BudgetDetailController.budgetItemData(), qItemList);
    }
}