Git Tests/force-app/main/default/default/objects/Account/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamento__c/CondicaoPagamento__c.object-meta.xml
<CustomObject>
    <label>Condição de pagamento</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condições de pagamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/CondicaoPagamentoPorCD__c.object-meta.xml
<CustomObject>
    <label>Condição de pagamento por CD</label>
    <nameField>
        <label>Nome de Condição de pagamento</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condições de pagamentos por CD</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Condição de Pagamento CD</relationshipLabel>
    <relationshipName>CondicoesPagamento</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/CondicaoPagamentoPL__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamentoPL__c</fullName>
    <label>Condição de Pagamento</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Integradora__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>002/28 D</fullName>
            </value>
            <value>
                <fullName>003/30 D</fullName>
            </value>
            <value>
                <fullName>004/45 D</fullName>
            </value>
            <value>
                <fullName>042/60 D</fullName>
            </value>
            <value>
                <fullName>012/30,45,60 D</fullName>
            </value>
            <value>
                <fullName>028/35 D</fullName>
            </value>
            <value>
                <fullName>058/56 D</fullName>
            </value>
            <value>
                <fullName>046/45,60 D</fullName>
            </value>
            <value>
                <fullName>013/30,60 D</fullName>
            </value>
            <value>
                <fullName>036/21 D</fullName>
            </value>
            <value>
                <fullName>115/20 D</fullName>
            </value>
            <value>
                <fullName>065/25 D</fullName>
            </value>
            <value>
                <fullName>007/28,35 D</fullName>
            </value>
            <value>
                <fullName>008/28,35,42 D</fullName>
            </value>
            <value>
                <fullName>010/28,35,42,49,56</fullName>
            </value>
            <value>
                <fullName>081/28,42 D</fullName>
            </value>
            <value>
                <fullName>011/30,45 D</fullName>
            </value>
            <value>
                <fullName>049/14 DIAS</fullName>
            </value>
            <value>
                <fullName>066/10 D</fullName>
            </value>
            <value>
                <fullName>045/120 D</fullName>
            </value>
            <value>
                <fullName>006/90 D</fullName>
            </value>
            <value>
                <fullName>043/A VISTA</fullName>
            </value>
            <value>
                <fullName>001/30 D - 5,15,25</fullName>
            </value>
            <value>
                <fullName>003</fullName>
            </value>
            <value>
                <fullName>004</fullName>
            </value>
            <value>
                <fullName>005</fullName>
            </value>
            <value>
                <fullName>005/49 D</fullName>
            </value>
            <value>
                <fullName>006</fullName>
            </value>
            <value>
                <fullName>009/28,35,42,49 D</fullName>
            </value>
            <value>
                <fullName>014/30,60,90 D</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/FretePicklist__c.field-meta.xml
<CustomField>
    <fullName>FretePicklist__c</fullName>
    <label>Tipo de Frete</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CIF</fullName>
                <default>true</default>
                <label>CIF</label>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamentoPorCD__c/fields/Orcamento__c.field-meta.xml
<CustomField>
    <fullName>Orcamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Orçamento</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Condições de pagamentos por CD</relationshipLabel>
    <relationshipName>Condicespagamentospor_CD</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/Integracoes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuração  personalizada utilizada para gerir os dados de acessos das integrações</description>
    <label>Integrações</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <inlineHelpText>URL de acesso ao serviço</inlineHelpText>
    <label>EndPoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Método</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Senha</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>Usuário</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Orcamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/DataVencimento__c.field-meta.xml
<CustomField>
    <fullName>DataVencimento__c</fullName>
    <label>Data de Vencimento</label>
    <type>DateTime</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/FretePicklist__c.field-meta.xml
<CustomField>
    <fullName>FretePicklist__c</fullName>
    <label>Tipo de Frete</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/TabulacaoN1__c.field-meta.xml
<CustomField>
    <fullName>TabulacaoN1__c</fullName>
    <inlineHelpText>Este campo é um refinamento do valor do campo Status</inlineHelpText>
    <label>Tabulação N1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recusa</fullName>
            </value>
            <value>
                <fullName>Aceite</fullName>
            </value>
            <value>
                <fullName>Improdutiva</fullName>
            </value>
            <value>
                <fullName>Envio Automático</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/recordTypes/OrcamentoPortal.recordType-meta.xml
<RecordType>
    <fullName>OrcamentoPortal</fullName>
    <active>true</active>
    <businessProcess>Portal de Cotações</businessProcess>
    <label>Orçamento do Portal</label>
    <!---->
    <!---->
</RecordType>

Git Tests/force-app/main/default/default/objects/OpportunityTeamMember/fields/TabulacaoN1__c.field-meta.xml
<CustomField>
    <fullName>TabulacaoN1__c</fullName>
    <inlineHelpText>Este campo é um refinamento do valor do campo Status</inlineHelpText>
    <label>Tabulação N1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Recusa</fullName>
            </value>
            <value>
                <fullName>Aceite</fullName>
            </value>
            <value>
                <fullName>Improdutiva</fullName>
            </value>
            <value>
                <fullName>Envio Automático</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <description>
        Objeto recebido na integração do portal de cotações (class: IntegrationPortalQuoteIN) e
        utilizado para armazenar as requisições de produtos efetuada pelos clientes,
        assim como a resposta efetuada pelos vendedores.
        Sua estrutura a nível de negócio existe de duas formas:
        1. a nível de item, sendo o item entendido como as informações advindas da integração com a requisição do cliente.
        2. a nível de resposta, sendo a resposta entendida como as informações enviadas do vendedor para o cliente como resposta.
        Esse objeto pode ser visualizado a nível de usuário nas telas de orçamento do tipo portal (Opportunity > RecordType > OrcamentoPortal),
        que é o mestre do relacionamento mestre-detalhe contido nesse objeto.
        O item é enviado ao portal como resposta na integração do portal de cotação (class: IntegrationPortalQuoteOUT).
        E também é enviado quando é efetuado vínculo de produto (class: IntegrationPortalVinculoOUT)
    </description>
    <label>Item da Cotação</label>
    <nameField>
        <label>Nome do Item da Cotação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens da Cotação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Identificador de condição da resposta, (Responde a pergunta: Em que estapa está a resposta?)</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NÃO IDENTIFICADO</fullName>
            </value>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>IDENTIFICADO</fullName>
            </value>
            <value>
                <fullName>QUALIFICADO</fullName>
            </value>
            <value>
                <fullName>Respondido</fullName>
            </value>
            <value>
                <fullName>Resgatado</fullName>
            </value>
            <value>
                <fullName>Aguardando Integração</fullName>
            </value>
            <value>
                <fullName>Falha na Integração</fullName>
            </value>
            <value>
                <fullName>Não Vinculado</fullName>
                <default>true</default>
                <label>Não Vinculado</label>
            </value>
            <value>
                <fullName>Vinculado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/TabulacaoN1__c.field-meta.xml
<CustomField>
    <fullName>TabulacaoN1__c</fullName>
    <inlineHelpText>Refinamento do valor do campo Status.</inlineHelpText>
    <label>Tabulação N1</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Status__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FORA DE MALHA</fullName>
                <label>Fora de malha</label>
            </value>
            <value>
                <fullName>SEM ESTOQUE</fullName>
                <label>Sem estoque</label>
            </value>
            <value>
                <fullName>NÃO TEMOS NESSA APRESENTAÇÃO</fullName>
                <label>Não temos nessa apresentação</label>
            </value>
            <value>
                <fullName>NÃO TEMOS A VALIDADE SOLICITADA</fullName>
                <label>Não temos a validade solicitada</label>
            </value>
            <value>
                <fullName>Não temos a quantidade solicitada</fullName>
            </value>
            <value>
                <fullName>Bloqueio por regionalização</fullName>
            </value>
            <value>
                <fullName>Termolab alto SLA de entrega</fullName>
            </value>
            <value>
                <fullName>Não pertence a minha BU</fullName>
            </value>
            <value>
                <fullName>Cotado</fullName>
            </value>
            <value>
                <fullName>NÃO TEM NO PORTIFÓLIO</fullName>
                <label>Não tem no portifólio</label>
            </value>
            <value>
                <fullName>COM OFERTA</fullName>
                <isActive>false</isActive>
                <label>Com oferta</label>
            </value>
            <value>
                <fullName>NÃO TEMOS A QTDE SOLICITADA</fullName>
                <isActive>false</isActive>
                <label>NÃO TEMOS A QTDE SOLICITADA</label>
            </value>
            <value>
                <fullName>NÃO TRABALHAMOS</fullName>
                <isActive>false</isActive>
                <label>NÃO TRABALHAMOS</label>
            </value>
            <value>
                <fullName>NÃO CONSEGUIMOS ATENDER NO PRAZO SOLICITADO</fullName>
                <isActive>false</isActive>
                <label>Não conseguimos atender no prazo solicitado</label>
            </value>
            <value>
                <fullName>SEM OFERTA</fullName>
                <isActive>false</isActive>
                <label>Sem oferta</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/classes/IntegrationPortalQuoteOUTScheduleTest.cls
@isTest
public with sharing class IntegrationPortalQuoteOUTScheduleTest {

    @TestSetup
    static void makeData(){
        Account acc = TestUtility.createAccount();
        insert acc;
        CondicaoPagamento__c conditionPayment = TestUtility.createPaymentCondition2();
        insert conditionPayment;
        Contact contact = TestUtility.createContact(acc);
        insert contact;
        Opportunity opp = TestUtility.createOpportunity(acc, contact, conditionPayment);
        opp.DataVencimento__c = System.now().addMinutes(1);
        opp.RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('OrcamentoPortal').getRecordTypeId();
        opp.StageName = 'Em digitação';
        insert opp;
        CondicaoPagamentoPorCD__c conPagCd = TestUtility.createCondicaoPagamentoPorCD(conditionPayment);
        conPagCd.Orcamento__c = opp.Id;
        conPagCd.FretePicklist__c = null;
        CondicaoPagamentoPorCD__c conPagCdWithoutConPay = TestUtility.createCondicaoPagamentoPorCD(conditionPayment);
        conPagCdWithoutConPay.Orcamento__c = opp.Id;
        conPagCdWithoutConPay.FretePicklist__c = null;
        conPagCdWithoutConPay.CondicaoPagamento__r = null;
        conPagCdWithoutConPay.CondicaoPagamento__c = null;
        conPagCdWithoutConPay.CondicaoPagamentoPL__c = null;
        insert new List<CondicaoPagamentoPorCD__c>{conPagCd, conPagCdWithoutConPay};
        OpportunityTeamMember otm = TestUtility.createOpportunityTeamMember(opp);
        insert otm;
        QuoteItem__c qItem = TestUtility.createQuoteItem(opp, new User(Id = UserInfo.getUserId()));
        qItem.Status__c = 'Vinculado';
        qItem.TabulacaoN1__c = 'Sem Estoque';
        insert qItem;

        Integracoes__c integration =  new Integracoes__c(
            Name        = 'InformaticaAtualizarCotacao',
            Method__c   = 'POST',
            Endpoint__c = 'https://na1.ai.dm-us.informaticacloud.com/active-bpel/rt/',
            User__c     = 'test123@grupoelfa.com.br',
            Password__c = 'test123'
        );
        insert integration;
    }

    @isTest
    public static void testIntegrationQuoteOutSchedule(){
        Test.StartTest();
        IntegrationPortalQuoteOUTSchedule.scheduleQueue();
        Test.StopTest();
    }
}