Git Tests/force-app/main/default/default/objects/Account/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamento__c/CondicaoPagamento__c.object-meta.xml
<CustomObject>
    <label>Condição de pagamento</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condições de pagamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ItensNotaFiscal__c/ItensNotaFiscal__c.object-meta.xml
<CustomObject>
    <label>Item da nota fiscal</label>
    <nameField>
        <displayFormat>{0000000}</displayFormat>
        <label>Item da nota fiscal</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Itens da nota fiscal</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ItensNotaFiscal__c/fields/CFOP__c.field-meta.xml
<CustomField>
    <fullName>CFOP__c</fullName>
    <label>CFOP</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItensNotaFiscal__c/fields/CodigoItemNotaVenda__c.field-meta.xml
<CustomField>
    <fullName>CodigoItemNotaVenda__c</fullName>
    <externalId>true</externalId>
    <label>Código do item da nota de venda</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItensNotaFiscal__c/fields/ItemNotaVenda__c.field-meta.xml
<CustomField>
    <fullName>ItemNotaVenda__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Item da nota de venda</label>
    <referenceTo>ItensNotaFiscal__c</referenceTo>
    <relationshipName>ItensNotaFiscal</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItensNotaFiscal__c/fields/NotaFiscal__c.field-meta.xml
<CustomField>
    <fullName>NotaFiscal__c</fullName>
    <label>Número da Nota Fiscal</label>
    <referenceTo>NotasFiscais__c</referenceTo>
    <relationshipLabel>Itens da nota fiscal</relationshipLabel>
    <relationshipName>ItensNotaFiscal</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/NotasFiscais__c/NotasFiscais__c.object-meta.xml
<CustomObject>
    <label>Nota fiscal</label>
    <nameField>
        <label>Número da nota fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas fiscais</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/NotasFiscais__c/fields/CFOP__c.field-meta.xml
<CustomField>
    <fullName>CFOP__c</fullName>
    <label>CFOP</label>
    <length>5</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/NotasFiscais__c/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>NotasFiscais</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/NotasFiscais__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Nome do cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>NotasFiscais</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/NotasFiscais__c/fields/DataEmissao__c.field-meta.xml
<CustomField>
    <fullName>DataEmissao__c</fullName>
    <label>Data de emissão</label>
    <type>Date</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/NotasFiscais__c/fields/Empresa__c.field-meta.xml
<CustomField>
    <fullName>Empresa__c</fullName>
    <label>Empresa/Filial</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/NotasFiscais__c/fields/Pedido__c.field-meta.xml
<CustomField>
    <fullName>Pedido__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número do pedido</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>NotasFiscais</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/NotasFiscais__c/fields/SerieNota__c.field-meta.xml
<CustomField>
    <fullName>SerieNota__c</fullName>
    <label>Série da nota</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/NotasFiscais__c/recordTypes/Venda.recordType-meta.xml
<RecordType>
    <fullName>Venda</fullName>
    <active>true</active>
    <label>Venda</label>
</RecordType>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Orcamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/recordTypes/OrcamentoPortal.recordType-meta.xml
<RecordType>
    <fullName>OrcamentoPortal</fullName>
    <active>true</active>
    <businessProcess>Portal de Cotações</businessProcess>
    <label>Orçamento do Portal</label>
    <!---->
    <!---->
</RecordType>

Git Tests/force-app/main/default/default/objects/Order/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Chave única: Número do pedido + Código do CD</description>
    <externalId>true</externalId>
    <label>Código do pedido TOTVS</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Pricebook2/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Catálogos de preços</relationshipLabel>
    <relationshipName>CatalogoPreco</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Pricebook2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do produto</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/classes/ItensNotasFiscaisTHTest.cls
@IsTest
public with sharing class ItensNotasFiscaisTHTest {

    public static final Id PRICEBOOKID = Test.getStandardPricebookId();
    public static final Id RECORDTYPE_PORTALID = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('OrcamentoPortal').getRecordTypeId();
    
    @TestSetup
    public static void init() {

        List<SObject> listToInsert = new List<SObject>();
        List<SObject> listToInsert2 = new List<SObject>();

        Account account = TestUtility.createAccPJ();
        insert account;

        Pricebook2 pb2 = TestUtility.createPricebook2();
        pb2.ExternalId__c = 'pb2';
        listToInsert.add(pb2);
  

        Product2 product1 = TestUtility.createProduct();
        product1.ExternalId__c = '00prod';
        product1.ProductCode = '00prod';
        listToInsert.add(product1);

        PricebookEntry pbEntry1 = TestUtility.createPricebookEntry(pb2, product1);
        pbEntry1.ExternalId__c = '00pb';
        listToInsert.add(pbEntry1);

        CondicaoPagamento__c condPag = TestUtility.createPaymentCondition();
        insert condPag;
       
        Order order = TestUtility.createOrder(account);
        order.Pricebook2Id = pb2.Id;
        insert order;


        NotasFiscais__c nf = new NotasFiscais__c();
        nf.Name = 'testeVenda';
        nf.SerieNota__c = '2';
        nf.DataEmissao__c = System.Today();
        nf.Pedido__c = order.Id;
        nf.CondicaoPagamento__c = condPag.Id;
        nf.Empresa__c = 'Emrpesa teste Venda';
        nf.Conta__c = account.Id;
        insert nf;

        ItensNotaFiscal__c itemVenda = new ItensNotaFiscal__c();
        itemVenda.ExternalId__c = '123';
        itemVenda.NotaFiscal__c = nf.id;
        insert itemVenda;

        NotasFiscais__c nfDevolucao = new NotasFiscais__c();
        nfDevolucao.Name = 'testeDevolucao';
        nfDevolucao.SerieNota__c = '1';
        nfDevolucao.DataEmissao__c = System.Today();
        nfDevolucao.Pedido__c = order.Id;
        nfDevolucao.CondicaoPagamento__c = condPag.Id;
        nfDevolucao.Empresa__c = 'Emrpesa teste';
        nfDevolucao.CFOP__c = '1202';
        nfDevolucao.Conta__c = account.Id;
        insert nfDevolucao;

        ItensNotaFiscal__c itemDevolucao = new ItensNotaFiscal__c();
        itemDevolucao.CodigoItemNotaVenda__c = '123';
        itemDevolucao.NotaFiscal__c = nfDevolucao.id;
        itemDevolucao.ItemNotaVenda__c = null;
        insert itemDevolucao;  

        //insert listToInsert;
        //insert listToInsert2;
    }

    
    @IsTest
    public static void testAllMethods() {

        List<ItensNotaFiscal__c> newRecordList = [SELECT id, CodigoItemNotaVenda__c, ExternalId__c,ItemNotaVenda__c FROM ItensNotaFiscal__c WHERE CodigoItemNotaVenda__c != '' LIMIT 1];
        Map<Id, ItensNotaFiscal__c> mapOld = new Map<Id, ItensNotaFiscal__c>{newRecordList[0].Id => newRecordList[0]};
        ItensNotasFiscaisTH.disableTrigger();

        ItensNotasFiscaisBO ItensNotasFiscaisBO = new ItensNotasFiscaisBO();
        ItensNotasFiscaisBO.vinculaItemVenda(mapOld, newRecordList);

        ItensNotasFiscaisTH.enableTrigger();
        
        update   newRecordList;

        delete newRecordList;

    }
}