Git Tests/force-app/main/default/default/objects/Account/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamento__c/CondicaoPagamento__c.object-meta.xml
<CustomObject>
    <label>Condição de pagamento</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condições de pagamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Orcamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/DataVencimento__c.field-meta.xml
<CustomField>
    <fullName>DataVencimento__c</fullName>
    <label>Data de Vencimento</label>
    <type>DateTime</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <description>
        Objeto recebido na integração do portal de cotações (class: IntegrationPortalQuoteIN) e
        utilizado para armazenar as requisições de produtos efetuada pelos clientes,
        assim como a resposta efetuada pelos vendedores.
        Sua estrutura a nível de negócio existe de duas formas:
        1. a nível de item, sendo o item entendido como as informações advindas da integração com a requisição do cliente.
        2. a nível de resposta, sendo a resposta entendida como as informações enviadas do vendedor para o cliente como resposta.
        Esse objeto pode ser visualizado a nível de usuário nas telas de orçamento do tipo portal (Opportunity > RecordType > OrcamentoPortal),
        que é o mestre do relacionamento mestre-detalhe contido nesse objeto.
        O item é enviado ao portal como resposta na integração do portal de cotação (class: IntegrationPortalQuoteOUT).
        E também é enviado quando é efetuado vínculo de produto (class: IntegrationPortalVinculoOUT)
    </description>
    <label>Item da Cotação</label>
    <nameField>
        <label>Nome do Item da Cotação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens da Cotação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/fields/CategoriaCliente__c.field-meta.xml
<CustomField>
    <fullName>CategoriaCliente__c</fullName>
    <description>Recebido do portal via integração a categoria do produto declarada pelo cliente para o produto requisitado.</description>
    <label>Categoria do Cliente</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/UserCustomization__c/UserCustomization__c.object-meta.xml
<CustomObject>
    <description>Usado inicialmente para salvar os filtros customizados na tela de orçamentos do portal, posteriormente pode vir a ser usado para outros fins.</description>
    <label>UserCustomization</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>UserCustomizations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/classes/BudgetTabControllerTest.cls
@isTest
public class BudgetTabControllerTest {
    @TestSetup
    static void makeData(){
        Account acc = TestUtility.createAccount();
        insert acc;
        Contact contact = TestUtility.createContact(acc);
        insert contact;
        CondicaoPagamento__c conditionPayment = TestUtility.createConditionPayment(); 
        insert conditionPayment;
        Opportunity opp = TestUtility.createOpportunity(acc, contact, conditionPayment);
        opp.DataVencimento__c = System.now().addDays(1);
        insert opp;
        QuoteItem__c qItem = TestUtility.createQuoteItem(opp);
        qItem.CategoriaCliente__c = 'teste';
        insert qItem;
    }

    @isTest
    static void doSearchTest1(){
        String json1doSearch  =  
        '{'+
            '"searchStatus"     :null,'+
            '"statusSearch"     :["Encerrado"],'+
            '"vendedorSelected" :[],'+
            '"teamMember"       :["userId"],'+
            '"quoteIntegratorId":"0000123",'+
            '"quoteType"        :"Portal",'+
            '"cnpjCliente"      :"26495652000138",'+
            '"mesaSelected"     :null,'+
            '"nomeCliente"      :"Artevaldo",'+
            '"ufCliente"        :["RJ"],'+
            '"cidadeCliente"    :["Rio de Janeiro"],'+
            '"vencimentoCotacao":'+
            '{'+
                '"date1"        :"2022-03-01T12:59:00.000Z",'+
                '"date2"        :"2022-03-02T12:59:00.000Z"'+
            '},'+
            '"searchText"       :"01/06/1999",'+
            '"orderBy"          :"CreatedDate",'+
            '"orderDirection"   :"desc",'+
            '"lastRecord"       :null,'+
            '"itemsPerPage"     :200,'+
            '"produto"          :"0000364",'+
            '"expired"          :true,'+
            '"notAnswered"      :true'+
        '}';


        BudgetTabController.doSearch(json1doSearch);

    }
    
    @isTest
    static void doSearchTestError(){
        try{
            BudgetTabController.doSearch('Error');

        }catch(Exception e){
            System.debug(e.getMessage());
        }
        
    }
    

    @isTest
    static void doSearchTest2(){
        String json2doSearch  =  
            '{'+
            '"searchText"        :"lul",'+
            '"vencimentoCotacao":{},'+
            '"orderBy"          :"CreatedDate",'+
            '"orderDirection"   :"desc",'+
            '"lastRecord"       :null,'+
            '"itemsPerPage"     :200,'+
            '"notAnswered"      :true,'+
            '"last_n_days"       :1'+
        '}';

        BudgetTabController.doSearch(json2doSearch);

    }

    @isTest
    static void doSearchTest3(){
        String json2doSearch  =  
            '{'+
            '"searchText"        :"01/06/1999",'+
            '"vencimentoCotacao" :{},'+
            '"lastRecord"        :null,'+
            '"itemsPerPage"      :200,'+
            '"mesaSelected"      :["sul"],'+
            '"last_n_days"       :0'+
        '}';

        BudgetTabController.doSearch(json2doSearch);

    }

    @isTest
    static void doSearchTest4(){
        String json2doSearch  =  
            '{'+
            '"searchText"        :"01/06/1999 09",'+
            '"vencimentoCotacao":{},'+
            '"lastRecord"       :null,'+
            '"itemsPerPage"     :200,'+
        '}';

        BudgetTabController.doSearch(json2doSearch);

    }

    @isTest
    static void doSearchTest5(){
        String json2doSearch  =  
            '{'+
            '"searchText"        :"01/06/1999 09:15",'+
            '"vencimentoCotacao":{},'+
            '"orderBy"          :"CreatedDate",'+
            '"orderDirection"   :"desc",'+
            '"lastRecord"       :null,'+
            '"itemsPerPage"     :200'+
        '}';

        BudgetTabController.doSearch(json2doSearch);

    }

    @isTest
    static void doSearchTest6(){
        String json2doSearch  =  
            '{'+
            '"searchText"        :"126,12",'+
            '"vencimentoCotacao":{},'+
            '"orderBy"          :"CreatedDate",'+
            '"orderDirection"   :"desc",'+
            '"lastRecord"       :null,'+
            '"itemsPerPage"     :200,'+
            '"yesterday"       :true'+
            
        '}';

        BudgetTabController.doSearch(json2doSearch);

    }

    @isTest
    static void doSearchTest7(){
        String json2doSearch  =  
            '{'+
            '"produto"        :"0000364",'+
            '"vencimentoCotacao":{},'+
            '"orderBy"          :"CreatedDate",'+
            '"orderDirection"   :"desc",'+
            '"lastRecord"       :null,'+
            '"itemsPerPage"     :200'+
        '}';

        BudgetTabController.doSearch(json2doSearch);

    }

    @isTest 
    static void getUsersSetorTest1(){

        BudgetTabController.getUsersPicklist();

    }

    @isTest 
    static void test_fixedFilters_success(){
        String json2doSave  = '{"searchStatus":null,"vendedorSelected":[],"teamMember":[],"quoteIntegratorId":null,"quoteType":"Portal","cnpjCliente":null,"mesaSelected":null,"nomeCliente":null,"ufCliente":null,"cidadeCliente":null,"vencimentoCotacao":{},"orderBy":"CreatedDate","orderDirection":"desc","lastRecord":null,"itemsPerPage":200}';
        BudgetTabController.saveFixFilter('filterName', json2doSave);
        BudgetTabController.getFixedFilters();
        UserCustomization__c userCustom = [SELECT Id FROM UserCustomization__c LIMIT 1];
        BudgetTabController.deleteFixedFilters(new List<String>{userCustom.Id});
    }
    
    @isTest
    static void test_deleteFixFilters_error(){
        BudgetTabController.deleteFixedFilters(new List<String>{'asd'});
    }

    @isTest
    static void test_fixedFilters_errorJson(){
        BudgetTabController.saveFixFilter('filterName', '{"asd":asd"asd}');
        BudgetTabController.getFixedFilters();
    }

    @isTest 
    static void test_fixedFilters_error_empty(){
        BudgetTabController.saveFixFilter(null, 'filterParams');

    }

    @isTest 
    static void test_fixedFilters_error_toolong(){

        BudgetTabController.saveFixFilter('afhaefeafeafaefaefeffaefaefeafeaafhaefeafeafaefaefeffaefaefeafeaafhaefeafeafaefaefeffaefaefeafeaafhaefeafeafaefaefeffaefaefeafeaafhaefeafeafaefaefeffaefaefeafeaafhaefeafeafaefaefeffaefaefeafeaafhaefeafeafaefaefeffaefaefeafeaafhaefeafeafaefaefeffaefaefeafea', 'filterParams');

    }

    @isTest 
    static void test_getVendedor(){

        BudgetTabController.getVendedor(new List<String>{'filterName'});

    }
    
    @isTest 
    static void test_getCategoria(){
        BudgetTabController.getCategoria();
    }

    @isTest 
    static void test_getMesa(){

        BudgetTabController.getMesa();

    }

    @isTest 
    static void test_getUserOrders(){

        BudgetTabController.getUserOrders();
    }
}