Git Tests/force-app/main/default/default/objects/Account/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Contas</relationshipLabel>
    <relationshipName>Contas</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/CondicaoPagamento__c/CondicaoPagamento__c.object-meta.xml
<CustomObject>
    <label>Condição de pagamento</label>
    <nameField>
        <label>Nome</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Condições de pagamento</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Oportunidades</relationshipLabel>
    <relationshipName>Orcamentos</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedidos</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/QuoteItem__c.field-meta.xml
<CustomField>
    <fullName>QuoteItem__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Resposta do Orçamento</label>
    <referenceTo>QuoteItem__c</referenceTo>
    <relationshipLabel>Items Pedidos</relationshipLabel>
    <relationshipName>ProdutoPedidoGerado</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Pricebook2/fields/CondicaoPagamento__c.field-meta.xml
<CustomField>
    <fullName>CondicaoPagamento__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Condição de pagamento</label>
    <referenceTo>CondicaoPagamento__c</referenceTo>
    <relationshipLabel>Catálogos de preços</relationshipLabel>
    <relationshipName>CatalogoPreco</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/QuoteItem__c/QuoteItem__c.object-meta.xml
<CustomObject>
    <description>
        Objeto recebido na integração do portal de cotações (class: IntegrationPortalQuoteIN) e
        utilizado para armazenar as requisições de produtos efetuada pelos clientes,
        assim como a resposta efetuada pelos vendedores.
        Sua estrutura a nível de negócio existe de duas formas:
        1. a nível de item, sendo o item entendido como as informações advindas da integração com a requisição do cliente.
        2. a nível de resposta, sendo a resposta entendida como as informações enviadas do vendedor para o cliente como resposta.
        Esse objeto pode ser visualizado a nível de usuário nas telas de orçamento do tipo portal (Opportunity > RecordType > OrcamentoPortal),
        que é o mestre do relacionamento mestre-detalhe contido nesse objeto.
        O item é enviado ao portal como resposta na integração do portal de cotação (class: IntegrationPortalQuoteOUT).
        E também é enviado quando é efetuado vínculo de produto (class: IntegrationPortalVinculoOUT)
    </description>
    <label>Item da Cotação</label>
    <nameField>
        <label>Nome do Item da Cotação</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens da Cotação</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/classes/OrderItemHelperTest.cls
@isTest
public with sharing class OrderItemHelperTest {
    @TestSetup
    static void makeData(){
        
        Account acc = TestUtility.createAccount();
        insert acc;
        
        Contact contact = TestUtility.createContact(acc);
        insert contact;
        
        CondicaoPagamento__c conditionPayment = TestUtility.createConditionPayment();
        insert conditionPayment;
        
        Opportunity opp = TestUtility.createOpportunity(acc, contact, conditionPayment);
        insert opp;
        
        QuoteItem__c qItem = TestUtility.createQuoteItem(opp, new User(Id = UserInfo.getUserId()));
        insert qItem;

        PriceBook2 pricebook2 = TestUtility.createPricebook2();
        insert pricebook2;
        
        Order order = TestUtility.createOrder(acc);
        order.OpportunityId = opp.Id;
        order.Pricebook2Id = pricebook2.id;
        insert order;
        
        Product2 product = TestUtility.createProduct();
        insert product;

        PricebookEntry pbEntry = TestUtility.createPricebookEntry(pricebook2.id, product.id);
        insert pbEntry;
        
        OrderItem orderItem = TestUtility.createOrderItem(order, product, pbEntry);
        insert orderItem;
        
    }
    @isTest
    public static void orderItemTriggerVerify(){
        List<OrderItem> ordItem = [SELECT Id FROM OrderItem];
        OrderItemHandler.disableTrigger();
        OrderItemHandler.enableTrigger();

        update ordItem;
    }
}