Git Tests/force-app/main/default/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Campaign/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código da campanha</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Campaign/recordTypes/Campanha.recordType-meta.xml
<RecordType>
    <fullName>Campanha</fullName>
    <active>true</active>
    <description>Tipo de registro utilizado para campanhas de produtos</description>
    <label>Campanha de produto</label>
</RecordType>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/ItemCampanha__c.object-meta.xml
<CustomObject>
    <label>Item da campanha</label>
    <nameField>
        <label>Código do item de campanha</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Itens da campanha</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/Campanha__c.field-meta.xml
<CustomField>
    <fullName>Campanha__c</fullName>
    <label>Campanha</label>
    <referenceTo>Campaign</referenceTo>
    <relationshipName>ItemCampanha</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do item de campanha</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/NomeProduto__c.field-meta.xml
<CustomField>
    <fullName>NomeProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome do produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>ItemCampanha</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/VigenciaFinal__c.field-meta.xml
<CustomField>
    <fullName>VigenciaFinal__c</fullName>
    <label>Vigência final</label>
    <type>Date</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/ItemCampanha__c/fields/VigenciaInicial__c.field-meta.xml
<CustomField>
    <fullName>VigenciaInicial__c</fullName>
    <label>Vigência inicial</label>
    <type>Date</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Chave única: Número do pedido + Código do CD</description>
    <externalId>true</externalId>
    <label>Código do pedido TOTVS</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Pricebook2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do produto</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/FatorConversao__c.field-meta.xml
<CustomField>
    <fullName>FatorConversao__c</fullName>
    <label>Fator de conversão</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/CampaignManagementControllerTest.cls
@isTest
public with sharing class CampaignManagementControllerTest {
    @isTest
    public static void CampaignManagementControllerTest() {
        try {
            Account account = TestUtility.createAccPJ();
        insert account;

        Pricebook2 pricebook = new Pricebook2(
            Name = 'Pricebook Test',
            ExternalId__c = 'B01'
        );
        insert pricebook;
        
        Order order = TestUtility.createOrder(account);
        order.Pricebook2Id = pricebook.Id;
        insert order;

        Product2 prod = TestUtility.createProduct();
        prod.FatorConversao__c = '1';
        Product2 prod2 = TestUtility.createProduct();
        prod.Name += '2';
        prod.FatorConversao__c = '2';
        Product2 prod3 = TestUtility.createProduct();
        prod.Name += '3';
        prod.FatorConversao__c = '3';

        insert new List<Product2>{prod, prod2, prod3};

        PricebookEntry pricebookEntry = TestUtility.createPricebookEntry(pricebook.Id, prod.Id);
        insert pricebookEntry;

        Campaign campaign = new Campaign(
            Name = 'Campaign Test',
            ExternalId__c = '2186',
            RecordTypeId = Schema.SObjectType.Campaign.getRecordTypeInfosByDeveloperName().get('Campanha').getRecordTypeId()
        );
        insert campaign;

        ItemCampanha__c campaignItem = new ItemCampanha__c(
            Campanha__c = campaign.Id,
            NomeProduto__c = prod.Id,
            VigenciaInicial__c = Date.today().addDays(-10),
            VigenciaFinal__c = Date.today()
        );
        ItemCampanha__c campaignItem2 = new ItemCampanha__c(
            Campanha__c = campaign.Id,
            NomeProduto__c = prod2.Id,
            VigenciaInicial__c = Date.today().addDays(-10),
            VigenciaFinal__c = Date.today()
        );
        ItemCampanha__c campaignItem3 = new ItemCampanha__c(
            Campanha__c = campaign.Id,
            NomeProduto__c = prod3.Id,
            VigenciaInicial__c = Date.today().addDays(-10),
            VigenciaFinal__c = Date.today()
        );
        insert new List<ItemCampanha__c>{campaignItem, campaignItem2, campaignItem3};
        
        ContentVersion ctVersion = TestUtility.createContentVersion();
        insert ctVersion;
        
        List<ContentDocument> contentDocumentList = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        
        ContentDocumentLink link = new ContentDocumentLink();
        link.LinkedEntityId = order.Id;
        link.ContentDocumentId = contentDocumentList[0].Id;
        link.ShareType = 'V';
        link.Visibility = 'AllUsers';
        insert link;

        CampaignManagementController camp = new CampaignManagementController();

        CampaignManagementController.CampaignData campData = new CampaignManagementController.CampaignData();

        CampaignManagementController.FilterProductData filterProd = new CampaignManagementController.FilterProductData();
        filterProd.product  = 'Pricebook Test';
        filterProd.producer = 'B01';
        
        CampaignManagementController.AvailableProductsParams availableProductsParams = new CampaignManagementController.AvailableProductsParams();
        availableProductsParams.filter = filterProd;
        availableProductsParams.offset = 0;

        String availableProductsParamsStr = JSON.serialize(availableProductsParams);
        system.debug(availableProductsParamsStr);

        CampaignManagementController.SaveData saveData = new CampaignManagementController.SaveData();
        saveData.Id          = campaignItem.Id;
        saveData.Campanha    = campaign.Id;
        saveData.NomeProduto = prod.Id;
        saveData.CNPJCD      = '1234564';
        saveData.NomeEmpresa = 'Nome Empresa 1';
        saveData.MetaVolume  = 10;
        saveData.MetaValor   = 123;

        CampaignManagementController.SaveData saveData2 = new CampaignManagementController.SaveData();
        saveData2.Id          = campaignItem2.Id;
        saveData2.Campanha    = campaign.Id;
        saveData2.NomeProduto = prod2.Id;
        saveData2.CNPJCD      = '1234563';
        saveData2.NomeEmpresa = 'Nome Empresa 12';
        saveData2.MetaVolume  = null;
        saveData2.MetaValor   = 123;

        CampaignManagementController.SaveData saveData3 = new CampaignManagementController.SaveData();
        saveData3.Id          = null;
        saveData3.Campanha    = campaign.Id;
        saveData3.NomeProduto = prod3.Id;
        saveData3.CNPJCD      = '1234562';
        saveData3.NomeEmpresa = 'Nome Empresa 123';
        saveData3.MetaVolume  = 10;
        saveData3.MetaValor   = null;

        List<CampaignManagementController.SaveData> listSaveData = new List<CampaignManagementController.SaveData>{saveData, saveData2, saveData3};

        String saveDataString = JSON.serialize(listSaveData);
        system.debug(saveDataString);
        
        CampaignManagementController.loadParams();
        CampaignManagementController.getCampaignData(campaign.Id);
        CampaignManagementController.refreshProducts(campaign.Id);
        CampaignManagementController.updateSequence(campaign.Id);
        CampaignManagementController.loadProducts(filterProd, 0);
        CampaignManagementController.loadCampaign(campaign.Id);
        CampaignManagementController.loadCampaignItems(campaign.Id);
        CampaignManagementController.loadCampaignItemsByProductId(campaign.Id, prod.Id);
        CampaignManagementController.loadMapProductToCampaignItems(campaign.Id);
        CampaignManagementController.loadProductIdsByProductCode(new Set<String>{prod.Id, prod2.Id, prod3.Id});
        CampaignManagementController.getAvailableDistributionCenters();
        CampaignManagementController.createItemsByCSVFile(campaign.id, contentDocumentList[0].Id);
        CampaignManagementController.getAvailableProducts(availableProductsParamsStr);
        CampaignManagementController.saveProducts(campaign.Id, saveDataString);
        
        CampaignManagementController.deleteProduct(campaign.id, campaignItem.id);
        } catch(Exception e) {
            System.debug(e);
        }

    }
}