Git Tests/force-app/main/default/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Estoque__c/Estoque__c.object-meta.xml
<CustomObject>
    <label>Estoque</label>
    <nameField>
        <label>Número do estoque</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estoques</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Estoque__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do estoque</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Chave única: Número do pedido + Código do CD</description>
    <externalId>true</externalId>
    <label>Código do pedido TOTVS</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/PedidoPendente__c.field-meta.xml
<CustomField>
    <fullName>PedidoPendente__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pedido pendente</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Número do item do pedido</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/ItemPendente__c.field-meta.xml
<CustomField>
    <fullName>ItemPendente__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Item pendente</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do produto</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/classes/BatchStockEmailsTest.cls
@isTest
public with sharing class BatchStockEmailsTest {
    @TestSetup
    static void makeData(){
        Account account = TestUtility.createAccPJ();
        insert account;
        Product2 product = TestUtility.createProductToStock();
        insert product;
        Order order = TestUtility.createOrder(account);
        order.PedidoPendente__c = true;
        order.Status = 'Em digitação';
        insert order;
        PricebookEntry pricebookEntry = [SELECT Id, Product2Id, pricebookEntry.UnitPrice FROM PricebookEntry WHERE Product2Id =: product.Id][0];
        OrderItem orderItem = TestUtility.createOrderItem(order, product, pricebookEntry);
        orderItem.ItemPendente__c = true;
        insert orderItem;
        Estoque__c stock = TestUtility.createStock(product.ExternalId__c, product.Id);
        insert stock;
    }
    
    @isTest
    public static void BatchStockEmails() {
        BatchStockEmailsSchedule batchSchedule = new BatchStockEmailsSchedule();
        batchSchedule.execute(null);
        BatchStockEmailsSchedule.scheduleBatch();
    }
}