Git Tests/force-app/main/default/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/PrazoValidade__c.field-meta.xml
<CustomField>
    <fullName>PrazoValidade__c</fullName>
    <label>Prazo de validade (em dias)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/recordTypes/OrcamentoContaOrdem.recordType-meta.xml
<RecordType>
    <fullName>OrcamentoContaOrdem</fullName>
    <active>true</active>
    <businessProcess>Status do orçamento</businessProcess>
    <label>Orçamento conta e ordem</label>
</RecordType>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Chave Externa</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/FatorConversao__c.field-meta.xml
<CustomField>
    <fullName>FatorConversao__c</fullName>
    <label>Fator de Conversao</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/ValorCx__c.field-meta.xml
<CustomField>
    <fullName>ValorCx__c</fullName>
    <inlineHelpText>Principal: Unidade de medida principal do produto</inlineHelpText>
    <label>Valor (Principal)</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Pricebook2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do produto</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/FatorConversao__c.field-meta.xml
<CustomField>
    <fullName>FatorConversao__c</fullName>
    <label>Fator de conversão</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/RecommendationsServiceTest.cls
@isTest
public with sharing class RecommendationsServiceTest {

    @isTest(SeeAllData=true)
    public static void RecommendationsServiceTest() {
        Account account = TestUtility.createAccPJ();
        insert account;

        
        Opportunity opportunity = new Opportunity(
            Name = 'Opportunity Test',
            StageName = 'Novo',
            CloseDate = Date.today().addDays(10),
            AccountId = account.Id,
            RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('OrcamentoContaOrdem').getRecordTypeId(),
            PrazoValidade__c = 10
        );
        insert opportunity;

        Pricebook2 pricebook = new Pricebook2(
            Name = 'Pricebook Test 123',
            ExternalId__c = 'B123123'
        );
        insert pricebook;

        Product2 product = TestUtility.createProduct();
        product.FatorConversao__c = '1';
        insert product;

        PricebookEntry pricebookEntry = TestUtility.createPricebookEntry(pricebook.Id, product.Id);
        insert pricebookEntry;

        OpportunityLineItem opportunityLineItem = new OpportunityLineItem(
            OpportunityId = opportunity.Id,
            Quantity = 1,
            TotalPrice = 100,
            PricebookEntryId = pricebookEntry.Id,
            Product2Id = product.Id,
            ValorCx__c = 100
        );
        insert opportunityLineItem;

        List<RecommendationsService.RecommendationData> listRecData = new List<RecommendationsService.RecommendationData>();

        listRecData.addAll(RecommendationsService.getRecommendations(opportunity.Id, 1));

        RecommendationsService.ReactionDataInput reactDataInput = new RecommendationsService.ReactionDataInput();
        if(!listRecData.isEmpty()) {
            reactDataInput.externalId       = listRecData[0].externalId;
            reactDataInput.targetId         = listRecData[0].targetId;
            reactDataInput.targetActionId   = listRecData[0].targetActionId;
            reactDataInput.targetActionName = listRecData[0].targetActionName;
            reactDataInput.reaction         = 'Accepted';
    
            RecommendationsService.setReaction(reactDataInput);
            RecommendationsService.getRecommendationPDF(new List<String>{opportunity.Id});
        }
    }
}