Git Tests/force-app/main/default/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/Integracoes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuração  personalizada utilizada para gerir os dados de acessos das integrações</description>
    <label>Integrações</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <inlineHelpText>URL de acesso ao serviço</inlineHelpText>
    <label>EndPoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Método</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Senha</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>Usuário</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/NotasFiscais__c/NotasFiscais__c.object-meta.xml
<CustomObject>
    <label>Nota fiscal</label>
    <nameField>
        <label>Número da nota fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas fiscais</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/NotasFiscais__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Nome do cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>NotasFiscais</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/NotasFiscais__c/fields/Pedido__c.field-meta.xml
<CustomField>
    <fullName>Pedido__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número do pedido</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>NotasFiscais</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/NotasFiscais__c/fields/SerieNota__c.field-meta.xml
<CustomField>
    <fullName>SerieNota__c</fullName>
    <label>Série da nota</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ClienteRecebedor__c.field-meta.xml
<CustomField>
    <fullName>ClienteRecebedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cliente recebedor</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Pedidos</relationshipLabel>
    <relationshipName>Pedido</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Chave única: Número do pedido + Código do CD</description>
    <externalId>true</externalId>
    <label>Código do pedido TOTVS</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/TitulosAbertos__c/TitulosAbertos__c.object-meta.xml
<CustomObject>
    <label>Título em aberto</label>
    <nameField>
        <displayFormat>TIT-{0000000}</displayFormat>
        <label>Número do título em aberto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Títulos em aberto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/TitulosAbertos__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Nome do cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Títulos em aberto</relationshipLabel>
    <relationshipName>TitulosEmAberto</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/TitulosAbertos__c/fields/NumeroBoleto__c.field-meta.xml
<CustomField>
    <fullName>NumeroBoleto__c</fullName>
    <externalId>true</externalId>
    <label>Número do boleto</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/TitulosAbertos__c/fields/Pedido__c.field-meta.xml
<CustomField>
    <fullName>Pedido__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Número do pedido</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Títulos em Aberto</relationshipLabel>
    <relationshipName>TitulosEmAberto</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/IntegrationGETAttachment.cls
public without sharing class IntegrationGETAttachment {
    @InvocableMethod(label='Get Open Title Attachment' 
                    description='Call integration to get the Attachment of this "Título em Aberto"')
    public static List<String> flowHandler(List<String> titleIdSet){
        String integrationType = 'GetTitulosAttachment';

        String titleExternalId = '';
        String titleAccountExternalId = '';
        String titleSerieExternalId = '3';   

        for(TitulosAbertos__c nf : [SELECT id, NumeroBoleto__c, Conta__r.ExternalId__c FROM TitulosAbertos__c WHERE Id IN :titleIdSet]){
            titleExternalId = nf.NumeroBoleto__c;
            titleAccountExternalId = nf.Conta__r.ExternalId__c;
        }

        return getAttachment(titleIdSet.get(0), integrationType, titleExternalId, titleAccountExternalId, titleSerieExternalId);
    }

    public static List<String> getAttachment(String objId, String endpointType, string nfExternalId, string accountExternalId, string serieExternalId){
        String returnMsg = '';
        try{
            Integracoes__c endpoint = Integracoes__c.getAll().get(endpointType);
            HttpRequest req = new HttpRequest();
            // 172.30.0.20:1006/DEV/GetXML?cCgcEmp={{CGC}}&cNota={{externalId}}&cSerie={{nfSerieExternalId}}&cTpNF=S
            req.setEndpoint(endpoint.Endpoint__c.replace('{{CGC}}', accountExternalId).replace('{{externalId}}', nfExternalId).replace('{{nfSerieExternalId}}', serieExternalId));
            req.setMethod(endpoint.Method__c);
            req.setHeader('Authorization', 'Basic ' + EncodingUtil.base64Encode(Blob.valueOf(endpoint.user__c + ':' + endpoint.Password__c)));
            req.setHeader('Content-Type', 'application/json;charset=UTF-8');
            req.setTimeout(120000);

            HttpResponse resp = new HttpResponse();
            resp = new Http().send(req);

            System.debug(resp.getStatusCode());

            String resultString = resp.getBody();

            System.debug(resultString);
            if(resp.getStatusCode() == 200 || resp.getStatusCode() == 201){
                system.debug(resp.getBody());
                returnMsg = null;
            }else{
                system.debug(resp.getStatusCode());
                system.debug(resp.getBody());
                returnMsg = 'Erro';
            }
        }catch(Exception ex){
            system.debug(ex.getMessage());
            returnMsg = ex.getMessage();
        }
        system.debug('returnMsg: '+ returnMsg);
        return new List<String>{returnMsg};
    }

    public static List<String> flowHandlerNF(List<String> nfIdSet, String documentType){
        String nfExternalId = '';
        String nfAccountExternalId = '';
        String nfSerieExternalId = '';

        for(NotasFiscais__c nf : [SELECT id, ExternalId__c, Pedido__r.CNPJCD__c, SerieNota__c FROM NotasFiscais__c WHERE Id IN: nfIdSet]){
            nfAccountExternalId =  nf.Pedido__r.CNPJCD__c;
            nfSerieExternalId = nf.SerieNota__c;
            nfExternalId =  nf.ExternalId__c.substring(5, 14);
        }

        RequestDTO requestData = new RequestDTO(documentType, nfAccountExternalId, nfSerieExternalId, nfExternalId);

        return IntegrationGETAttachment.getAttachmentNF(requestData);
    }

    public static List<String> getAttachmentNF(RequestDTO requestData){
        String returnMsg = '';
        try {
            Integracoes__c endpoint = Integracoes__c.getAll().get('GetFiscalAttachment');

            HttpRequest req = new HttpRequest();
            req.setEndpoint(endpoint.Endpoint__c);
            req.setMethod(endpoint.Method__c);
            req.setHeader('Authorization', 'Basic ' + EncodingUtil.base64Encode(Blob.valueOf(endpoint.user__c + ':' + endpoint.Password__c)));
            req.setHeader('Content-Type', 'application/json;charset=UTF-8');
            req.setBody(JSON.serialize(requestData));
            req.setTimeout(120000);

            HttpResponse resp = new HttpResponse();
            resp = new Http().send(req);

            System.debug(resp.getStatusCode());

            String resultString = resp.getBody();

            ResultClass resClass = null;
            try {
                resClass = (ResultClass)JSON.deserialize(resultString, ResultClass.class);                
            } catch (Exception e) {
                System.debug(e.getMessage());
            }

            System.debug(resultString);
            if (resp.getStatusCode() == 200 || resp.getStatusCode() == 201){
                System.debug(resp.getBody());
                returnMsg = resClass.result;
            } else {
                System.debug(resp.getStatusCode());
                System.debug(resp.getBody());
                returnMsg = resClass.result;
            }
        } catch (Exception ex){
            System.debug(ex.getMessage());
            returnMsg = ex.getMessage();
        }

        System.debug('returnMsg: ' + returnMsg);
        return new List<String>{returnMsg};
    }

    public class ResultClass{
        public String result {get;set;}
        public Boolean incluido {get;set;}
    }

    public class RequestDTO {
        public String tipo;
        public String cnpj_cd;
        public String serie;
        public String nota;
        public String origem = 'SFC';

        public RequestDTO(String tipo, String cnpj_cd, String serie, String nota) {
            this.tipo = tipo;
            this.cnpj_cd = cnpj_cd;
            this.serie = serie;
            this.nota = nota;
        }
    }
}