Git Tests/force-app/main/default/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/Filtro_PDF__c.field-meta.xml
<CustomField>
    <fullName>Filtro_PDF__c</fullName>
    <label>Filtro PDF</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/PrazoValidade__c.field-meta.xml
<CustomField>
    <fullName>PrazoValidade__c</fullName>
    <label>Prazo de validade (em dias)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/recordTypes/OrcamentoContaOrdem.recordType-meta.xml
<RecordType>
    <fullName>OrcamentoContaOrdem</fullName>
    <active>true</active>
    <businessProcess>Status do orçamento</businessProcess>
    <label>Orçamento conta e ordem</label>
</RecordType>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Chave Externa</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/FatorConversao__c.field-meta.xml
<CustomField>
    <fullName>FatorConversao__c</fullName>
    <label>Fator de Conversao</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/ValorCx__c.field-meta.xml
<CustomField>
    <fullName>ValorCx__c</fullName>
    <inlineHelpText>Principal: Unidade de medida principal do produto</inlineHelpText>
    <label>Valor (Principal)</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Pricebook2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do produto</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/FatorConversao__c.field-meta.xml
<CustomField>
    <fullName>FatorConversao__c</fullName>
    <label>Fator de conversão</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/TemplatePDF__c/TemplatePDF__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Objeto para os dados de template de PDF.</description>
    <label>Template PDF</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/TemplatePDF__c/fields/PDFTemplateClass__c.field-meta.xml
<CustomField>
    <fullName>PDFTemplateClass__c</fullName>
    <label>Classe do modelo PDF</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/GeneratePDFServiceTest.cls
@isTest
public class GeneratePDFServiceTest {

    @IsTest
    static void loadClassTest(){
        
      
        GeneratePDFService.FlowInputs flInp = new GeneratePDFService.FlowInputs();

        Account account = TestUtility.createAccPJ();
        insert account;

        Opportunity opportunity = new Opportunity(
            Name = 'Opportunity Test',
            StageName = 'Novo',
            CloseDate = Date.today().addDays(10),
            AccountId = account.Id,
            RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('OrcamentoContaOrdem').getRecordTypeId(),
            PrazoValidade__c = 10,
            Filtro_PDF__c = 'Ordem alfabética'
        );
        insert opportunity;

        Pricebook2 pricebook = new Pricebook2(
            Name = 'Pricebook Test',
            ExternalId__c = 'B01'
        );
        insert pricebook;

        Product2 product = TestUtility.createProduct();
        product.FatorConversao__c = '1';
        insert product;

        PricebookEntry pricebookEntry = TestUtility.createPricebookEntry(pricebook.Id, product.Id);
        insert pricebookEntry;

        OpportunityLineItem opportunityLineItem = new OpportunityLineItem(
            OpportunityId = opportunity.Id,
            Quantity = 1,
            TotalPrice = 100,
            PricebookEntryId = pricebookEntry.Id,
            Product2Id = product.Id,
            ValorCx__c = 100
        );
        insert opportunityLineItem;


        flInp.opportunityId = opportunity.Id;
        flInp.pdfChoice = 'GeneratePDFOrcamento';
        flInp.productCode = product.ProductCode;
        flInp.landscape = false;

        TemplatePDF__c template = new TemplatePDF__c(Name = 'GeneratePDFOrcamento', Id = null);
        insert template;

        GeneratePDFService.loadClass(new List<GeneratePDFService.FlowInputs>{flInp});


        TemplatePDF__c template2 = new TemplatePDF__c(Name = 'GeneratePDFOrcamento', Id = null, PDFTemplateClass__c='GeneratePDFOrcamento');
        insert template2;

        flInp.landscape = true;

        GeneratePDFService.loadClass(new List<GeneratePDFService.FlowInputs>{flInp});


        ApexPages.StandardController sc = new ApexPages.StandardController(opportunity);
        PageReference pageRef = Page.PDFOrcamento;
        pageRef.getParameters().put('id', opportunity.Id);
        pageRef.getParameters().put('prdCode', flInp.productCode);
        pageRef.getParameters().put('landScape', 'false'); 

        Test.setCurrentPage(pageRef);
        // GeneratePDFOrcamento generatePDFOrcamento = new GeneratePDFOrcamento(sc);
        
       
        
    }
    
    
}