Git Tests/force-app/main/default/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/Integracoes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuração  personalizada utilizada para gerir os dados de acessos das integrações</description>
    <label>Integrações</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/NotasFiscais__c/NotasFiscais__c.object-meta.xml
<CustomObject>
    <label>Nota fiscal</label>
    <nameField>
        <label>Número da nota fiscal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Notas fiscais</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/NotasFiscais__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Nome do cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Notas fiscais</relationshipLabel>
    <relationshipName>NotasFiscais</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Chave única: Número do pedido + Código do CD</description>
    <externalId>true</externalId>
    <label>Código do pedido TOTVS</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/TitulosAbertos__c/TitulosAbertos__c.object-meta.xml
<CustomObject>
    <label>Título em aberto</label>
    <nameField>
        <displayFormat>TIT-{0000000}</displayFormat>
        <label>Número do título em aberto</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Títulos em aberto</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/TitulosAbertos__c/fields/Conta__c.field-meta.xml
<CustomField>
    <fullName>Conta__c</fullName>
    <label>Nome do cliente</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Títulos em aberto</relationshipLabel>
    <relationshipName>TitulosEmAberto</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/IntegrationGETAttachmentTest.cls
@isTest
global with sharing class IntegrationGETAttachmentTest {

    @TestSetup
    static void makeData(){
        Account acc = TestUtility.createAccPJ();
        insert acc;

        Order ord = TestUtility.createOrder(acc);
        insert ord;

        NotasFiscais__c nf = TestUtility.createNotaFiscal(ord, acc);
        insert nf;
        
        TitulosAbertos__c tit = TestUtility.createTituloAberto(acc, nf);
        insert tit;
        
        Integracoes__c integrationGetAttPDF = TestUtility.createCustomSettingGetAttPDF();
        Integracoes__c integrationGetAttXML = TestUtility.createCustomSettingGetAttXML();
        Integracoes__c integrationGetAtt = TestUtility.createCustomSettingGetAtt();

        List<Integracoes__c> listIntegracoes = new List<Integracoes__c>{integrationGetAttPDF, integrationGetAttXML, integrationGetAtt};

        insert listIntegracoes;
    }

    global class MockHttpResponseGenerator implements HttpCalloutMock {
        private Boolean isSuccess;

        public MockHttpResponseGenerator(Boolean isSuccess){
            this.isSuccess = isSuccess;
        }
        // Implement this interface method
        global HTTPResponse respond(HTTPRequest req) {
            // Create a fake response
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setBody('{"CgcCli": "","CgcEmp": "","TpInteg": "","laboratorio": "","regra": "","PedidoIntegrador": "","CondicaoPagamento": "","TabelaPreco": "","TipoFrete": "CIF","observacoes": "","ObservacoesNF": "","itens": [{"produto": "","TpOper": "","ShelfLife": "AAAAMMDD","preco": 1,"lote": "","quantidade": 0.00}]}');
            res.setStatusCode(this.isSuccess? 201 : 500);

            if (res.getStatusCode() == 201){
                res.setBody('{"result": "Pedido incluido na fila de processamento!!","incluido": true}');
            } else {
                res.setBody('{"result": "Pedido não incluido na fila de processamento!!","incluido": false}');
            }
            return res;
        }
    }

    @isTest
    public static void flowHandlerTest() {
        IntegrationGETAttachmentNFPDF getAttchNFPDF = new IntegrationGETAttachmentNFPDF();
        IntegrationGETAttachmentNFXML getAttchNFXML = new IntegrationGETAttachmentNFXML();

        List<String> listNFId = new List<String>{[SELECT Id, ExternalId__c, Conta__c FROM NotasFiscais__c][0].Id};
        List<String> listTitId = new List<String>{[SELECT Id FROM TitulosAbertos__c][0].Id};
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(true));
        IntegrationGetAttachment.flowHandler(listTitId);       
        IntegrationGETAttachmentNFPDF.flowHandlerXML(listNFId);
        IntegrationGETAttachmentNFXML.flowHandlerPDF(listNFId);

        Test.stopTest();    

        Test.setMock(HttpCalloutMock.class, new MockHttpResponseGenerator(false));
        IntegrationGetAttachment.flowHandler(listTitId);
        IntegrationGETAttachmentNFPDF.flowHandlerXML(listNFId);
        IntegrationGETAttachmentNFXML.flowHandlerPDF(listNFId);


    }
}