Git Tests/force-app/main/default/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>External Id</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/MotivoCancelamento__c.field-meta.xml
<CustomField>
    <fullName>MotivoCancelamento__c</fullName>
    <label>Motivo Cancelamento</label>
    <type>TextArea</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/fields/PrazoValidade__c.field-meta.xml
<CustomField>
    <fullName>PrazoValidade__c</fullName>
    <label>Prazo de validade (em dias)</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Opportunity/recordTypes/OrcamentoContaOrdem.recordType-meta.xml
<RecordType>
    <fullName>OrcamentoContaOrdem</fullName>
    <active>true</active>
    <businessProcess>Status do orçamento</businessProcess>
    <label>Orçamento conta e ordem</label>
</RecordType>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>Chave Externa</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/FatorConversao__c.field-meta.xml
<CustomField>
    <fullName>FatorConversao__c</fullName>
    <label>Fator de Conversao</label>
    <precision>18</precision>
    <scale>8</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/MotivoCancelamento__c.field-meta.xml
<CustomField>
    <fullName>MotivoCancelamento__c</fullName>
    <label>Motivo de cancelamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Desistiu da compra</fullName>
            </value>
            <value>
                <fullName>Não tem mais interesse no produto</fullName>
            </value>
            <value>
                <fullName>Falta de estoque do produto</fullName>
            </value>
            <value>
                <fullName>Preço</fullName>
            </value>
            <value>
                <fullName>Aprovação interna fora do prazo</fullName>
            </value>
            <value>
                <fullName>Analise interna financeira</fullName>
            </value>
            <value>
                <fullName>Prazo de entrega</fullName>
            </value>
            <value>
                <fullName>Orçamento cancelado por falta de tratativa dentro do vencimento</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/OpportunityLineItem/fields/ValorCx__c.field-meta.xml
<CustomField>
    <fullName>ValorCx__c</fullName>
    <inlineHelpText>Principal: Unidade de medida principal do produto</inlineHelpText>
    <label>Valor (Principal)</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Pricebook2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>80</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>Código do produto</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/FatorConversao__c.field-meta.xml
<CustomField>
    <fullName>FatorConversao__c</fullName>
    <label>Fator de conversão</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/CancelOppItemControllerTest.cls
@isTest
public with sharing class CancelOppItemControllerTest {
    @isTest
    public static void testCancelOppItem() {
        Account account = TestUtility.createAccPJ();
        insert account;

        Opportunity opportunity = new Opportunity(
            Name = 'Opportunity Test',
            StageName = 'Novo',
            CloseDate = Date.today().addDays(10),
            AccountId = account.Id,
            RecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('OrcamentoContaOrdem').getRecordTypeId(),
            PrazoValidade__c = 10
        );
        insert opportunity;

        Pricebook2 pricebook = new Pricebook2(
            Name = 'Pricebook Test',
            ExternalId__c = 'B01'
        );
        insert pricebook;

        Product2 product = TestUtility.createProduct();
        product.FatorConversao__c = '1';
        insert product;

        PricebookEntry pricebookEntry = TestUtility.createPricebookEntry(pricebook.Id, product.Id);
        insert pricebookEntry;

        List<OpportunityLineItem> listOppLineItem = new List<OpportunityLineItem>();
        OpportunityLineItem opportunityLineItem = new OpportunityLineItem(
            OpportunityId = opportunity.Id,
            Quantity = 1,
            TotalPrice = 100,
            PricebookEntryId = pricebookEntry.Id,
            Product2Id = product.Id,
            ValorCx__c = 100
        );
        OpportunityLineItem opportunityLineItem2 = new OpportunityLineItem(
            OpportunityId = opportunity.Id,
            Quantity = 1,
            TotalPrice = 100,
            PricebookEntryId = pricebookEntry.Id,
            Product2Id = product.Id,
            ValorCx__c = 100,
            MotivoCancelamento__c = 'Desistiu da compra'
        );
        listOppLineItem.add(opportunityLineItem);
        listOppLineItem.add(opportunityLineItem2);
        insert listOppLineItem;

        CancelOppItemController.getBudgetItens(String.valueOf(opportunity.id));

        List<CancelOppItemController.ProductData> listProdData = new List<CancelOppItemController.ProductData>();
        listProdData.add(new CancelOppItemController.ProductData(opportunityLineItem));
        listProdData.add(new CancelOppItemController.ProductData(opportunityLineItem2));

        system.debug(JSON.serializePretty(listProdData));

        CancelOppItemController.cloneBudget(JSON.serialize(listProdData));

        listProdData[0].motivoCancelamento = 'Desistiu da compra';

        CancelOppItemController.cloneBudget(JSON.serialize(listProdData));
    }
}