Git Tests/force-app/main/default/default/objects/Account/fields/Saldo__c.field-meta.xml
<CustomField>
    <fullName>Saldo__c</fullName>
    <formula>LimiteCredito__c  -  IF(ISBLANK(Titulos__c), 0, VALUE(Titulos__c))</formula>
    <inlineHelpText>Limite de crédito - Títulos</inlineHelpText>
    <label>Saldo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Estoque__c/Estoque__c.object-meta.xml
<CustomObject>
    <label>Estoque</label>
    <nameField>
        <label>Número do estoque</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estoques</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Estoque__c/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <externalId>true</externalId>
    <label>CNPJ CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Estoque__c/fields/NomeCD__c.field-meta.xml
<CustomField>
    <fullName>NomeCD__c</fullName>
    <label>Nome do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Estoque__c/fields/NomeProduto__c.field-meta.xml
<CustomField>
    <fullName>NomeProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome do produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Estoques</relationshipLabel>
    <relationshipName>Estoques</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Estoque__c/fields/Saldo__c.field-meta.xml
<CustomField>
    <fullName>Saldo__c</fullName>
    <label>Saldo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Estoque__c/recordTypes/Estoque.recordType-meta.xml
<RecordType>
    <fullName>Estoque</fullName>
    <active>true</active>
    <description>Identificação do estoque para criação de pedidos e cotações.</description>
    <label>Estoque</label>
</RecordType>

Git Tests/force-app/main/default/default/objects/Fornecedor__c/Fornecedor__c.object-meta.xml
<CustomObject>
    <label>Fornecedor</label>
    <nameField>
        <label>Nome do fornecedor</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Fornecedores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Order/fields/CentroDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentroDistribuicao__c</fullName>
    <label>Centro de distribuição</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/CentroDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentroDistribuicao__c</fullName>
    <label>Centro de distribuição</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <formula>Product2.Fornecedor__r.Name</formula>
    <label>Fornecedor</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/ItemPendente__c.field-meta.xml
<CustomField>
    <fullName>ItemPendente__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Item pendente</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Product2/fields/Fornecedor__c.field-meta.xml
<CustomField>
    <fullName>Fornecedor__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Fornecedor</label>
    <referenceTo>Fornecedor__c</referenceTo>
    <relationshipLabel>Produtos</relationshipLabel>
    <relationshipName>Produtos</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/BatchStockEmails.cls
global class BatchStockEmails implements Database.Batchable<sObject>{
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([SELECT Id, OrderId, ItemPendente__c, Order.Status, CNPJCD__c, CentroDistribuicao__c, Product2Id, Product2.Name, Product2.ProductCode, Product2.Fornecedor__r.Name, Quantity FROM OrderItem WHERE ItemPendente__c = true AND Order.Status = 'Em digitação']);
    }

    global void execute(Database.BatchableContext BC, List<OrderItem> scope) {
        List<Messaging.SingleEmailMessage> emailList = new List<Messaging.SingleEmailMessage>();
        Id templateEmailId;
        for (EmailTemplate template : [SELECT Id, Name, Body, Subject, HtmlValue FROM EmailTemplate WHERE DeveloperName = 'EmailStatusPendingOrder' LIMIT 1]) {
            templateEmailId = template.Id;
        }

        Map<Id, List<Estoque__c>> orderItemToStockMap = new Map<Id, List<Estoque__c>>();
        Map<Id, List<OrderItem>> orderToOrderItemMap = new Map<Id, List<OrderItem>>();
        Set<Id> productIdsSet = new Set<Id>();

        for (OrderItem orderItem : scope) {
            productIdsSet.add(orderItem.Product2Id);
            if (!orderToOrderItemMap.containsKey(orderItem.OrderId)) {
                orderToOrderItemMap.put(orderItem.OrderId, new List<OrderItem>{});
            }
            orderToOrderItemMap.get(orderItem.OrderId).add(orderItem);
        }
        for (Estoque__c stock : [SELECT Id, NomeProduto__r.Name, NomeProduto__c, NomeProduto__r.ProductCode, NomeCD__c, CNPJCD__c, Saldo__c FROM Estoque__c WHERE NomeProduto__c IN: productIdsSet AND CNPJCD__c <> null AND NomeCD__c <> null]) {
            for (OrderItem orderItem : scope) {
                if (orderItem.Product2Id == stock.NomeProduto__c) {
                    if (!orderItemToStockMap.containsKey(orderItem.Id)) {
                        orderItemToStockMap.put(orderItem.Id, new List<Estoque__c>{});
                    }
                    orderItemToStockMap.get(orderItem.Id).add(stock);
                }
            }
        }
        
        for (Order order : [SELECT Id, OrderNumber, CreatedById, CreatedBy.Email, Account.Name, Status FROM Order WHERE Id IN: orderToOrderItemMap.keySet() AND Status = 'Em digitação']) {
            System.debug('Pedido => ' + order.OrderNumber);
            String bodyEmail = 'Status do estoque do pedido ' + order.OrderNumber + '<br/><br/>';
            for (OrderItem orderItem : orderToOrderItemMap.get(order.Id)) {
                if (orderItemToStockMap.containsKey(orderItem.Id)) {
                    String bodyCds = '';
                    Integer stockCd = 0;
                    System.debug('Itens do Pedido => ' + orderItem.Product2.Name);
                    for (Estoque__c stock : orderItemToStockMap.get(orderItem.Id)) {
                        if (stock.NomeCD__c == orderItem.CentroDistribuicao__c) {
                            stockCd = stock.Saldo__c.intValue();
                        } else if (stock.Saldo__c > 0) {
                            bodyCds += stock.NomeCD__c + ' => <b>' + stock.Saldo__c.intValue() + '</b><br/>';
                        }
                    }
                    bodyEmail += 'Produto => <b>' + orderItem.Product2.ProductCode + '</b> - ' + orderItem.Product2.Name + '<br/>CD => ' + orderItem.CentroDistribuicao__c + '<br/>Fabricante => ' + orderItem.Product2.Fornecedor__r.Name + '<br/>Quantidade pendente => ' + orderItem.Quantity.intValue() + ' | <b>Quantidade disponível => ' + stockCd + '</b><br/><font color="#00cc00"><u><b>Quantidade em estoque de outros CDs:</font></u></b><br/>';
                    if (bodyCds == '') {
                        bodyEmail += '<b>Não há estoque disponível em outros CDs.</b>' + '<br/>';
                    } else {
                        bodyEmail += bodyCds + '<br/>';
                    }
                }
            }

            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            List<String> toAddresses = new List<String>{order.CreatedBy.Email};
            
            mail.setSubject('Status dos pedidos pendentes');
            mail.setTargetObjectId(order.CreatedById);
            mail.setTemplateId(templateEmailId);
            mail.setToAddresses(toAddresses);
            mail.setSaveAsActivity(false);
            mail.setHtmlBody(bodyEmail);
            emailList.add(mail);
        }

        if (!emailList.isEmpty()) {
            List<Messaging.SendEmailResult> results = Messaging.sendEmail(emailList);
            System.debug('Todos emails de pedido pendente enviados com sucesso.');
            System.debug(results);
        }
    }

    global void finish(Database.BatchableContext BC) {}
}