Git Tests/force-app/main/default/default/objects/Account/fields/Saldo__c.field-meta.xml
<CustomField>
    <fullName>Saldo__c</fullName>
    <formula>LimiteCredito__c  -  IF(ISBLANK(Titulos__c), 0, VALUE(Titulos__c))</formula>
    <inlineHelpText>Limite de crédito - Títulos</inlineHelpText>
    <label>Saldo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Estoque__c/Estoque__c.object-meta.xml
<CustomObject>
    <label>Estoque</label>
    <nameField>
        <label>Número do estoque</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Estoques</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Estoque__c/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <externalId>true</externalId>
    <label>CNPJ CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Estoque__c/fields/NomeCD__c.field-meta.xml
<CustomField>
    <fullName>NomeCD__c</fullName>
    <label>Nome do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Estoque__c/fields/NomeProduto__c.field-meta.xml
<CustomField>
    <fullName>NomeProduto__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Nome do produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Estoques</relationshipLabel>
    <relationshipName>Estoques</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Estoque__c/fields/Saldo__c.field-meta.xml
<CustomField>
    <fullName>Saldo__c</fullName>
    <label>Saldo</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Estoque__c/recordTypes/Estoque.recordType-meta.xml
<RecordType>
    <fullName>Estoque</fullName>
    <active>true</active>
    <description>Identificação do estoque para criação de pedidos e cotações.</description>
    <label>Estoque</label>
</RecordType>

Git Tests/force-app/main/default/default/objects/GeneralParameters__c/GeneralParameters__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Parâmetros gerais.</description>
    <label>Parâmetros gerais</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/GeneralParameters__c/fields/StockNotification__c.field-meta.xml
<CustomField>
    <fullName>StockNotification__c</fullName>
    <defaultValue>4</defaultValue>
    <label>Notificação entrada de estoque</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CentroDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentroDistribuicao__c</fullName>
    <label>Centro de distribuição</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/CentroDistribuicao__c.field-meta.xml
<CustomField>
    <fullName>CentroDistribuicao__c</fullName>
    <label>Centro de distribuição</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/ItemPendente__c.field-meta.xml
<CustomField>
    <fullName>ItemPendente__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Item pendente</label>
    <type>Checkbox</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/LastNotification__c.field-meta.xml
<CustomField>
    <fullName>LastNotification__c</fullName>
    <description>Última notificação recebida do controle de estoque.</description>
    <inlineHelpText>Última notificação recebida do controle de estoque.</inlineHelpText>
    <label>Última notificação</label>
    <type>DateTime</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/EstoqueHelper.cls
public with sharing class EstoqueHelper {
    public EstoqueHelper() {}

    public static void stockNotification(List<Estoque__c> newRecords, Map<Id, Estoque__c> oldMapRecords) {
        CustomNotificationType notificationType = [SELECT Id, DeveloperName FROM CustomNotificationType WHERE DeveloperName = 'StockNotification'];
        GeneralParameters__c parameters = GeneralParameters__c.getValues('Parametro geral');
        Messaging.CustomNotification notification = new Messaging.CustomNotification();

        Map<OrderItem, String> mapOrderItemToStock = new Map<OrderItem, String>();
        Map<Id, Set<String>> recipientsToOrder = new Map<Id, Set<String>>();
        Set<String> recipientsIds = new Set<String>();
        Set<String> cdNameList = new Set<String>();
        Set<Id> productIdList = new Set<Id>();
        Set<Id> orderIds = new Set<Id>();
        Set<Id> setOrderItemNotificationUpdate = new Set<Id>();


        Datetime datetimeCompare = datetime.now().addHours(-parameters.StockNotification__c.intValue());

        for (Estoque__c newStock : newRecords) {
            productIdList.add(newStock.NomeProduto__c);
            cdNameList.add(newStock.NomeCD__c);
        }

        List<OrderItem> orderItemList = [SELECT Id, OrderId, Order.OrderNumber, OrderItemNumber, Quantity, LastNotification__c, ItemPendente__c, Product2Id, Product2.Name, CreatedById, CentroDistribuicao__c, CNPJCD__c FROM OrderItem WHERE Product2Id IN: productIdList AND CentroDistribuicao__c IN: cdNameList AND ItemPendente__c = true AND Order.Status = 'Em digitação'];
        List<OrderItem> orderItemUpdateList = new List<OrderItem>();
        List<OrderItem> orderItemNotificationUpdate = new List<OrderItem>();
        
        for (Estoque__c stock : newRecords) {
            Estoque__c oldStock = oldMapRecords.get(stock.Id);
            List<OrderItem> orderItemProductList = new List<OrderItem>();
            for (OrderItem orderItem : orderItemList) {
                if (stock.NomeProduto__c == orderItem.Product2Id && stock.CNPJCD__c == orderItem.CNPJCD__c) {
                    if (stock.Saldo__c == 0) {
                        System.debug('NÃO VAI NOTIFICAR');
                        if (orderItem.LastNotification__c != null) {
                            orderItem.LastNotification__c = null;
                            if (!setOrderItemNotificationUpdate.contains(orderItem.id)) {
                                orderItemNotificationUpdate.add(orderItem);
                                setOrderItemNotificationUpdate.add(orderItem.id);
                            }
                        }
                    } else {
                        if (orderItem.LastNotification__c == null || orderItem.LastNotification__c <= datetimeCompare) {
                            System.debug('VAI NOTIFICAR');
                            orderItem.LastNotification__c = datetime.now();
                            if (!setOrderItemNotificationUpdate.contains(orderItem.id)) {
                                orderItemNotificationUpdate.add(orderItem);
                                setOrderItemNotificationUpdate.add(orderItem.id);
                            }
                            mapOrderItemToStock.put(orderItem, String.valueOf(stock.Saldo__c));
                            orderIds.add(orderItem.OrderId);
                            if (!recipientsToOrder.containsKey(orderItem.OrderId)) {
                                recipientsToOrder.put(orderItem.OrderId, new Set<String>{});
                            }
                            recipientsToOrder.get(orderItem.OrderId).add(orderItem.CreatedById);
                        } else if (stock.Saldo__c >= orderItem.Quantity) {
                            if (oldStock.Saldo__c < orderItem.Quantity) {
                                System.debug('VAI NOTIFICAR POR QUE CHEGOU MAIS ESTOQUE');
                                orderItem.LastNotification__c = datetime.now();
                                if (!setOrderItemNotificationUpdate.contains(orderItem.id)) {
                                    orderItemNotificationUpdate.add(orderItem);
                                    setOrderItemNotificationUpdate.add(orderItem.id);
                                }
                                mapOrderItemToStock.put(orderItem, String.valueOf(stock.Saldo__c));
                                orderIds.add(orderItem.OrderId);
                                if (!recipientsToOrder.containsKey(orderItem.OrderId)) {
                                    recipientsToOrder.put(orderItem.OrderId, new Set<String>{});
                                }
                                recipientsToOrder.get(orderItem.OrderId).add(orderItem.CreatedById);
                            } 
                        }
                    }
                }
            }
        }

        Map<Id, Order> orderMap = new Map<Id, Order>();
        for (Order order : [SELECT Id, Account.Name FROM Order WHERE Id IN: orderIds]) {
            orderMap.put(order.Id, order);
        }

        if (!orderItemNotificationUpdate.isEmpty()) {
            update orderItemNotificationUpdate;
        }
        if (!mapOrderItemToStock.isEmpty()) {
            System.debug('ENVIANDO ...');
            for (orderItem orderItem : mapOrderItemToStock.keySet()) {                
                notification.setTitle('Notificação de estoque.');
                notification.setBody('Estoque do produto ' + orderItem.Product2.Name + '\nCD => ' + orderItem.CentroDistribuicao__c + '\nEstoque novo => ' + Integer.valueOf(mapOrderItemToStock.get(orderItem)) + '\nPedido => ' + orderItem.Order.OrderNumber + '\nCliente => ' + orderMap.get(orderItem.OrderId).Account.Name);
    
                notification.setNotificationTypeId(notificationType.Id);
                notification.setTargetId(orderItem.OrderId);
    
                try {
                    notification.send(recipientsToOrder.get(orderItem.OrderId));
                }
                catch (Exception e) {
                    System.debug('Erro ao enviar notificação de estoque ' + e.getMessage());
                }
            }
        }
    }
}