Git Tests/force-app/main/default/default/objects/Account/fields/TipoFrete__c.field-meta.xml
<CustomField>
    <fullName>TipoFrete__c</fullName>
    <label>Tipo do frete</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/StatusEntrega__c.field-meta.xml
<CustomField>
    <fullName>StatusEntrega__c</fullName>
    <label>Status de entrega</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Link de rastreamento disponível</fullName>
            </value>
            <value>
                <fullName>Em Rota</fullName>
                <label>Em rota</label>
            </value>
            <value>
                <fullName>A caminho</fullName>
            </value>
            <value>
                <fullName>Chegou</fullName>
            </value>
            <value>
                <fullName>Entregue</fullName>
            </value>
            <value>
                <fullName>Entregue SL</fullName>
            </value>
            <value>
                <fullName>Em pausa</fullName>
            </value>
            <value>
                <fullName>Não entregue</fullName>
            </value>
            <value>
                <fullName>Abortada</fullName>
            </value>
            <value>
                <fullName>Coletado</fullName>
            </value>
            <value>
                <fullName>Não coletado</fullName>
            </value>
            <value>
                <fullName>Conferindo</fullName>
            </value>
            <value>
                <fullName>Conferido</fullName>
            </value>
            <value>
                <fullName>Sem rota</fullName>
            </value>
            <value>
                <fullName>Devolvido</fullName>
            </value>
            <value>
                <fullName>Cancelado</fullName>
            </value>
            <value>
                <fullName>Agendado</fullName>
            </value>
            <value>
                <fullName>Com ajudante</fullName>
            </value>
            <value>
                <fullName>Transferido</fullName>
            </value>
            <value>
                <fullName>Em transferência</fullName>
            </value>
            <value>
                <fullName>Programado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/TipoFrete__c.field-meta.xml
<CustomField>
    <fullName>TipoFrete__c</fullName>
    <label>Tipo do frete</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CIF</fullName>
            </value>
            <value>
                <fullName>FOB</fullName>
            </value>
            <value>
                <fullName>CLIENTE RETIRA</fullName>
            </value>
            <value>
                <fullName>Por conta de terceiros</fullName>
            </value>
            <value>
                <fullName>Por conta remetente</fullName>
            </value>
            <value>
                <fullName>Por conta destinatário</fullName>
            </value>
            <value>
                <fullName>Sem frete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/TipoOperacao__c.field-meta.xml
<CustomField>
    <fullName>TipoOperacao__c</fullName>
    <label>Tipo de operação</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/Lote__c.field-meta.xml
<CustomField>
    <fullName>Lote__c</fullName>
    <label>Lote</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/PrecoTotal__c.field-meta.xml
<CustomField>
    <fullName>PrecoTotal__c</fullName>
    <label>Preço total</label>
    <precision>18</precision>
    <scale>6</scale>
    <type>Currency</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/TipoOperacao__c.field-meta.xml
<CustomField>
    <fullName>TipoOperacao__c</fullName>
    <label>Tipo da operação</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/classes/ShippingTrackingControllerTest.cls
@isTest
public with sharing class ShippingTrackingControllerTest {
    @TestSetup
    static void makeData(){
        Account acc = TestUtility.createAccPJ();
        insert acc;

        Product2 prod = TestUtility.createProduct();
        insert prod;

        List<Order> listOrder = new List<Order>();
        Order ord1 = TestUtility.createOrder(acc);
        ord1.TipoFrete__c = 'CIF';
        listOrder.add(ord1);

        insert listOrder;

        Id pricebookEntryId = [SELECT Id FROM PricebookEntry WHERE Product2Id =: prod.Id][0].Id;

        List<OrderItem> listOrderItem = new List<OrderItem>();
        OrderItem orderItem1 = new OrderItem();
        orderItem1.orderId          = ord1.Id;
        orderItem1.Product2Id       = prod.Id;
        orderItem1.pricebookEntryId = pricebookEntryId;
        orderItem1.Quantity         = 5;
        orderItem1.UnitPrice        = 50;
        orderItem1.PrecoTotal__c    = 50;
        orderItem1.Lote__c          = '10';
        orderItem1.TipoOperacao__c  = '11';
        orderItem1.cnpjCD__c        = '52202744000192';
        listOrderItem.add(orderItem1);

        insert listOrderItem;
    }

    @isTest
    public static void ShippingTrackingControllerTest() {
        List<Order> lOrder = [SELECT Id, StatusEntrega__c FROM Order LIMIT 1];

        lOrder[0].StatusEntrega__c = 'Link de rastreamento disponível';

        update lOrder;

        ShippingTrackingController.getDeliveryHistory(lOrder[0].Id);

        ShippingTrackingController.getDeliveryURL(lOrder[0].Id);
        ShippingTrackingController.getStatusType('Entregue');
        ShippingTrackingController.getStatusType('Não entregue');
        ShippingTrackingController.getStatusType('Teste');
    }
}