Git Tests/force-app/main/default/default/objects/GeneralParameters__c/GeneralParameters__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Parâmetros gerais.</description>
    <label>Parâmetros gerais</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/GeneralParameters__c/fields/CentroCusto__c.field-meta.xml
<CustomField>
    <fullName>CentroCusto__c</fullName>
    <label>Centro de custo</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/Integracoes__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>Configuração  personalizada utilizada para gerir os dados de acessos das integrações</description>
    <label>Integrações</label>
</CustomObject>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <inlineHelpText>URL de acesso ao serviço</inlineHelpText>
    <label>EndPoint</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <label>Método</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/Password__c.field-meta.xml
<CustomField>
    <fullName>Password__c</fullName>
    <label>Senha</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Integracoes__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <label>Usuário</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CNPJ__c.field-meta.xml
<CustomField>
    <fullName>CNPJ__c</fullName>
    <formula>Account.CNPJ__c</formula>
    <label>CNPJ</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/MensagemNF__c.field-meta.xml
<CustomField>
    <fullName>MensagemNF__c</fullName>
    <label>Mensagem da NF</label>
    <type>TextArea</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/Order/fields/StatusIntegracao__c.field-meta.xml
<CustomField>
    <fullName>StatusIntegracao__c</fullName>
    <label>Status da integração</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Integrado</fullName>
            </value>
            <value>
                <fullName>Não integrado</fullName>
            </value>
            <value>
                <fullName>Erro de aprovação/rejeição</fullName>
            </value>
            <value>
                <fullName>Nota fiscal cancelada</fullName>
            </value>
            <value>
                <fullName>Pedido em aberto</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por regra</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por crédito</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por estoque</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por crédito e estoque</fullName>
            </value>
            <value>
                <fullName>Pedido aguardando separação</fullName>
            </value>
            <value>
                <fullName>Pedido em separação</fullName>
            </value>
            <value>
                <fullName>Pedido separado/aguardando faturamento</fullName>
            </value>
            <value>
                <fullName>Pedido faturado</fullName>
            </value>
            <value>
                <fullName>Pedido com resíduo eliminado (sem faturamento)</fullName>
            </value>
            <value>
                <fullName>Pedido com resíduo eliminado (com faturamento)</fullName>
            </value>
            <value>
                <fullName>Pedido liberado</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado na alçada de desconto</fullName>
            </value>
            <value>
                <fullName>Pedido com SC</fullName>
            </value>
            <value>
                <fullName>Pedido aguardando saldo</fullName>
            </value>
            <value>
                <fullName>Pedido bloqueado por regra de bonificação</fullName>
            </value>
            <value>
                <fullName>Pedido cancelado</fullName>
            </value>
            <value>
                <fullName>Pedido rejeitado no Salesforce</fullName>
            </value>
            <value>
                <fullName>Pedido rejeitado na alçada financeira</fullName>
            </value>
            <value>
                <fullName>Erro integração (Envio ao Protheus)</fullName>
            </value>
            <value>
                <fullName>Erro integração (geração do pedido no Protheus)</fullName>
            </value>
            <value>
                <fullName>Pedido aguardando envio/processamento do comprovante de pagamento RA</fullName>
            </value>
            <value>
                <fullName>Pedido aguardando aprovação de pagamento RA</fullName>
            </value>
            <value>
                <fullName>Pedido rejeitado na alçada de aprovação de pagamento RA</fullName>
            </value>
            <value>
                <fullName>Aguardando processamento na integradora</fullName>
            </value>
            <value>
                <fullName>Aprovado na integradora</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <label>CNPJ do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/CodigoProduto__c.field-meta.xml
<CustomField>
    <fullName>CodigoProduto__c</fullName>
    <formula>Product2.ExternalId__c</formula>
    <label>Código do produto</label>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/OrderItem/fields/SolicitacaoCompras__c.field-meta.xml
<CustomField>
    <fullName>SolicitacaoCompras__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Solicitação de compras</label>
    <referenceTo>SolicitacaoCompras__c</referenceTo>
    <relationshipLabel>Itens de solicitação de compras</relationshipLabel>
    <relationshipName>Itens_de_pedido</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/SolicitacaoCompras__c/SolicitacaoCompras__c.object-meta.xml
<CustomObject>
    <label>Solicitação de compras</label>
    <nameField>
        <displayFormat>SC-{0000000}</displayFormat>
        <label>Nome de Solicitação de compras</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Solicitações de compras</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Git Tests/force-app/main/default/default/objects/SolicitacaoCompras__c/fields/CNPJCD__c.field-meta.xml
<CustomField>
    <fullName>CNPJCD__c</fullName>
    <externalId>true</externalId>
    <label>CNPJ do CD</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/SolicitacaoCompras__c/fields/CodigoSolicitacao__c.field-meta.xml
<CustomField>
    <fullName>CodigoSolicitacao__c</fullName>
    <externalId>true</externalId>
    <label>Código da solicitação</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/SolicitacaoCompras__c/fields/MensagemIntegracao__c.field-meta.xml
<CustomField>
    <fullName>MensagemIntegracao__c</fullName>
    <label>Mensagem de integração</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/SolicitacaoCompras__c/fields/Pedido__c.field-meta.xml
<CustomField>
    <fullName>Pedido__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pedido</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Solicitações de compras</relationshipLabel>
    <relationshipName>SolicitacoesCompras</relationshipName>
    <type>Lookup</type>
</CustomField>

Git Tests/force-app/main/default/default/objects/SolicitacaoCompras__c/fields/StatusIntegracao__c.field-meta.xml
<CustomField>
    <fullName>StatusIntegracao__c</fullName>
    <label>Status de integração</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Sucesso</fullName>
            </value>
            <value>
                <fullName>Erro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Git Tests/force-app/main/default/default/classes/IntegrationPurchaseReqOUT.cls
global without sharing class IntegrationPurchaseReqOUT {

    global class PurchaseRequest {
        public String CgcEmp;
        public String CgcCliente;
        public String usuario;
        public String ObservacoesPedido;
        public String ObservacoesNF;
        public String origem;
        public List<OrderItensRequest> itens;
        
        public PurchaseRequest (SolicitacaoCompras__c pReq, list<OrderItensRequest> listOrderItens) {
            this.CgcEmp            = pReq.CNPJCD__c;
            this.CgcCliente        = pReq.Pedido__r.CNPJ__c;
            this.usuario           = 'elfa.middleware';
            this.ObservacoesPedido = pReq.Pedido__r.Description == null ? '' : pReq.Pedido__r.Description;
            this.ObservacoesNF     = pReq.Pedido__r.MensagemNF__c == null ? '' : pReq.Pedido__r.MensagemNF__c;
            this.origem            = 'SFC';
            this.itens             = listOrderItens;      
        }
    }

    global class OrderItensRequest {
        public String  produto;
        public String  item;
        public Decimal quantidade;
        public Decimal ValorEstimado;
        public String  CCusto;
        public String  PrevisaoFaturamento;
        public String  observacao;
        
        public OrderItensRequest (OrderItem orderItem, Integer ordItemSize, String CentroCusto) {
            this.produto             = orderItem.CodigoProduto__c; 
            this.item                = ordItemSize < 10 ? '0' + String.valueOf(ordItemSize) : String.valueOf(ordItemSize); 
            this.quantidade          = orderItem.Quantity; 
            this.ValorEstimado       = orderItem.UnitPrice;
            this.CCusto              = CentroCusto; 
            this.PrevisaoFaturamento = Date.today().format(); 
            this.observacao          = ''; 
        }
    }

    public class ResultClass{
        public String Result {get;set;}
        public String Doc {get;set;}
        public String lret {get;set;}
    }

    public static void sendPurchaseReqToERP(Id purshReqId) {
        
        Integracoes__c intCustomerApi = Integracoes__c.getValues('ElfaPurchaseReqAPI');
        
        String method   = intCustomerApi.Method__c;
        String endpoint = intCustomerApi.Endpoint__c;
        String username = intCustomerApi.User__c;
        String password = intCustomerApi.Password__c;
        
        HttpRequest req = new HttpRequest();
        req.setEndpoint(endpoint);
        req.setHeader('Authorization', 'Basic ' + EncodingUtil.base64Encode(Blob.valueOf(username + ':' + password)));
        req.setHeader('Content-Type', 'application/json;charset=UTF-8');
        req.setMethod(method);
        req.setTimeout(120000);

        System.debug(EncodingUtil.base64Encode(Blob.valueOf(username + ':' + password)));

        List<SolicitacaoCompras__c> pReqList = [
            SELECT 
                Id,
                Pedido__r.CNPJ__c,
                Pedido__r.Description,
                Pedido__r.MensagemNF__c,
                CreatedBy.CodigoUsuarioProtheus__c,
                CNPJCD__c,
                StatusIntegracao__c,
                MensagemIntegracao__c,
                CodigoSolicitacao__c,  
                ( 
                    SELECT
                        Id, 
                        UnitPrice,
                        Quantity,
                        CodigoProduto__c,
                        CNPJCD__c,
                        Custo__c
                    FROM Itens_de_pedido__r
                )
            FROM SolicitacaoCompras__c WHERE Id = :purshReqId
        ];
        PurchaseRequest purshReq;

        GeneralParameters__c gParam = GeneralParameters__c.getValues('Parametro geral');
        
        for (SolicitacaoCompras__c pReq : pReqList) {
            purshReq = fillOrderItems(pReq, gParam.CentroCusto__c);
        }

        System.debug('purshReq: ' + purshReq);

        String body;
        body = Json.serialize(purshReq);
        System.debug('Body: '+body);

        String resultString = '';
        HttpResponse resp = new HttpResponse();
        try {
            req.setBody(body);
            resp = new Http().send(req);
            System.debug(resp);
            System.debug(resp.getStatusCode());
            
            resultString = resp.getBody();
            System.debug('resp'+resultString);
            Boolean hasError = false;
            String message = '';
            String doc = '';
            if(resp.getStatusCode() == 200 || resp.getStatusCode() == 201){        
                resultString = resp.getBody();
                IntegrationUtils.WSLog('Solicitação de compras', 'Outbound', body, resultString, false);
            } else {
                resultString = resp.getBody();
                IntegrationUtils.WSLog('Solicitação de compras', 'Outbound', body, resultString, true);
                hasError = true;
            }
            ResultClass resClass = null;
            try {
                resClass = (ResultClass)JSON.deserialize(resultString, ResultClass.class);
                message  = resClass.Result;
                doc      = resClass.Doc;
            } catch (Exception e) {
                System.debug(e.getMessage());
                hasError = true;
                message  = 'Erro no envio da solicitação de compras';
            }
            SolicitacaoCompras__c purchaseReq = pReqList[0];
            purchaseReq.StatusIntegracao__c   = hasError ? 'Erro' : 'Sucesso';
            purchaseReq.MensagemIntegracao__c = hasError ? message : null;
            purchaseReq.CodigoSolicitacao__c  = doc != '' ? doc : null;
            update purchaseReq;

        } catch (Exception e) {
            resultString = e.getMessage();
        }
    }

    public static PurchaseRequest fillOrderItems(SolicitacaoCompras__c pReq, String CentroCusto) {
        List<OrderItensRequest> listOrderItemReq = new List<OrderItensRequest>();
        Integer count = 1;
        for (OrderItem oi : pReq.Itens_de_pedido__r) {
            listOrderItemReq.add(new OrderItensRequest(oi, count++, CentroCusto));
        }
        return new PurchaseRequest(pReq, listOrderItemReq);
    }

}